/*
 *		rtwizard/lib/examples//PictureTypeA/Cakefile
 */
#include "../../../../Cakefile.defs"

#define PRODUCTS title.txt preview.small.gif intro.txt helpstr.txt desc.txt
#define STATIC_PRODUCTS	title.txt preview.small.gif intro.txt helpstr.txt desc.txt
#define SRCDIR	../../../tclscripts/rtwizard/examples/PictureTypeA
#undef BINDIR
#define BINDIR	TCLSCRIPTSDIR/rtwizard/examples/PictureTypeA

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

tclIndex:
	../../../../tclscripts/ami.tcl ../../../../rtwizard/examples/PictureTypeA

clean&:
	@echo "" > /dev/null

noprod&:
	rm -f tclIndex

clobber&:
	@echo "" > /dev/null

#include "../../../../Cakefile.rules"









