#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: checkbox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

#
# Demo script for the Checkbox class
#
iwidgets::checkbox .cb -labeltext Styles
.cb add bold -text Bold
.cb add italic -text Italic
.cb add underline -text Underline
.cb select underline

pack .cb -padx 10 -pady 10 -fill both -expand yes
