#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: disjointlistbox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

iwidgets::disjointlistbox .dlb
pack .dlb -padx 10 -pady 10 -fill both -expand yes 

.dlb insertlhs {black white red blue yellow green magenta}
