#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: extfileselectiondialog in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

iwidgets::extfileselectiondialog .efsd -modality application

button .select -text "Files..." -command {
    if {[.efsd activate]} {
        puts "selected: [.efsd get]"
    } else {
        puts ""
    }
}
pack .select -side left
