#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: radiobox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

# itkwish interprets the rest...
# ----------------------------------------------------------------------
iwidgets::radiobox .rb -labeltext "Size:" -labelpos nw
pack .rb -padx 4 -pady 4 -fill both

.rb add small -text "Small"
.rb add med -text "Medium"
.rb add large -text "Large"
.rb add xlarge -text "Biggie"

.rb select med
