#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: selectionbox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::selectionbox .sb -selectionlabel "Font:" -height 2i
pack .sb

.sb insert items end Ariel Courier Helvetica Knarly Lucida \
    Rumpus Symbol Times "Zapf Dingbats"
