#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: spintime in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::spintime .st
pack .st
