#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: timefield in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

proc returnCmd {} {
  puts [.df get]
}

iwidgets::timefield .df -labeltext "Time:" -command returnCmd
pack .df -fill x -expand yes -padx 10 -pady 10

