#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: timeentry in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

iwidgets::timeentry .de -labeltext "Time:"
pack .de -fill x -expand yes -padx 10 -pady 10
