.TH G_DIFF 1
.\"                       G _ D I F F . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.SH NAME
g_diff \- a BRL-CAD differential geometry comparator
.SH SYNOPSIS
.BR "g_diff " "[-m] [-f] [-v] model1.g model2.g"
.SH DESCRIPTION
.I G_diff
compares the two BRL-CAD models specified on the comand line. The results of this comparison
are written to standard out in a human readable form describing the changes from model1 to model2.
If the
.I -m
option is exercised, the output will be a script, readable by mged(1), that will perform the
necessary changes to model1 to make it a copy of model2. The produced script makes extensive use
of the
.I db get, db put,
and
.I db adjust
commands in mged(1). A few solid types are not supported by these commands, and changes involving these
solids are merely noted (the script will not actually be capable of performing all the changes in this case).
The
.I -f
option requests that all floating point numerical comparisons be done in single precision rather
than the default double precision. This may be useful when comparing different format databases.
The
.I -v
option requests that the default attributes of each region in both files be checked for
consistency. Any inconsistencies are written to stderr.
.SH EXAMPLE
The command
.sp
.in +5
\fIg_diff -m uncle.g aunt.g > mged.script\fR
.in -5
.sp
will create a file named "mged.script" that may be sourced in mged(1) to change
uncle.g into aunt.g.

.SH SEE ALSO
mged(1)
.SH AUTHOR
John Anderson
.SH SOURCE
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5068  USA
.SH BUG REPORTS
Reports of bugs should be submitted via the
.I cadbug.sh
shell script.
Alternatively, bugs or problems may be submitted by electronic mail
to <devs@brlcad.org>.
