.TH G_LINT 1
.\"                       G _ L I N T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.SH NAME
g_lint \- a BRL-CAD geometry checker
.SH SYNOPSIS
.BR "g_lint " "[ options ] model.g objects ..."
.SH DESCRIPTION
.I G_lint
uses
.IR librt (3)
to fire an array of parallel rays
at the specified
.I objects
in the database
.I model.g
and reports
overlaps,
vacuums,
and potential problems with air regions.
By default, the output consists of single-line reports,
each of which contains a tag identifying the report type
and then other data as appropriate for that type report.
Unless the
.I -p
option is specified,
the exact formats are:

.TP 12
.BI overlap " r1 r2 length x_in y_in z_in x_out y_out z_out"
Consecutive partitions overlap by more than
.I tol
(see the
.I -t
option).
The data reported are
the names of the two regions involved,
the length of the overlap along the ray,
and the model coordinates of the ray's entry into and exit from
the overlap.
.TP 12
.BI air_contiguous " r1 a1 r2 a2 x y z"
Consecutive partitions have unlike (nonzero) air codes
and the space between them is less than
.I tol
(see the
.I -t
option).
The data reported are
the names and air codes of the two regions involved
and the model coordinates of the point of contiguity.
.TP 12
.BI air_unconfined " r1 (s1) r2 (s2) length x1 y1 z1 x2 y2 z2"
A partition with nonzero air code
follows or precedes another partition
and the space between them is more than
.I tol
(see the
.I -t
option).
The data reported are
the names of the two regions (and solids) involved,
the length of the gap along the ray,
and the model coordinates of the ray's exiting the first partition
and entering the second.
.TP 12
.BI air_first " r a x y z"
The first partition has a nonzero air code.
The data reported are
the name and air code of the region involved
and the model coordinates of the ray's entering the partition.
.TP 12
.BI air_last " r a x y z"
The last partition has a nonzero air code.
The data reported are
the name and air code of the region involved
and the model coordinates of the ray's exiting the partition.
.TP 12
.BI vacuum " r1 (s1) r2 (s2) length x1 y1 z1 x2 y2 z2"
The space between consecutive partitions is more than
.I tol
(see the
.I -t
option).
The data reported are
the names of the two regions (and solids) involved,
the length of the gap along the ray,
and the model coordinates of the ray's exiting the first partition
and entering the second.

.SS Command-line options
.TP 12
.BI "-a" " az"
Sets the azimuth from which to fire rays to
.I az
degrees.
The default is 0.
.TP 12
.B "-c"
Specifies that one ray should be fired from the center of each grid cell.
By default,
.I g_lint
fires a ray from one random point in each cell.
.TP 12
.BI "-e" " el"
Sets the elevation from which to fire rays to
.I el
degrees.
The default is 0.
.TP 12
.BI "-g" " gridsize"
Sets the width and height of each grid cell to
.I gridsize
millimeters.
The default is 100 mm.
.TP 12
.B "-o"
Causes
.I g_lint
to include in each report
the model coordinates of the ray origination point.
These appear between the tag and the rest of the data.
.TP 12
.B "-p"
Causes
.I g_lint
to produce its reports as
.I plot3(5)
drawing commands instead of ASCII text.
This is useful in conjunction with the ``overlay'' command of
.I mged.
.TP 12
.BI "-r" " bits"
Specifies which types of reports to produce.
If, after an optional minus sign,
.I bits
begins with either ``0x'' or ``0X'',
the remainder is interpreted in hexadecimal.
Otherwise, if
.I bits
begins with ``0'',
the remainder is interpreted in octal.
Otherwise,
.I bits
is interpreted in decimal.
The meaning of the individual bits is as follows:
.in +5
 1 overlaps
.in -5
.in +5
 2 contiguous unlike airs
.in -5
.in +5
 4 unconfined airs
.in -5
.in +5
 8 air first on rays
.in -5
.in +5
16 air last on rays
.in -5
.in +5
32 vacuums.
.in -5
If there was no initial minus sign, then
.I bits
specifies which report types to produce.
The minus sign implies complementation:
when it is present,
.I bits
specifies which report types
.I not
to produce.
The default is 1.
.TP 12
.B "-s"
Causes
.I g_lint
to collect all the overlap reports and sort them before printing them.
The reports for a given pair of regions
are printed contiguously,
and the clusters of reports for the various pairs of regions
appear in order of decreasing cumulative overlap length.
By default,
.I g_lint
reports overlaps immediately and in the order of their discovery.
.TP 12
.BI "-t" " tol"
Sets the tolerance for overlaps, contiguous and unconfined airs,
and vacuums
to
.I tol
millimeters.
The default is 0.
.TP 12
.B "-u"
Sets the
.I useair
member of the
.I rt_i
structure to 1,
which causes
.I librt
to report partitions containing air.
It is also set implicitly if any air-related reports have been specified.
By default,
.I librt
ignores air regions.
.TP 12
.BI "-x" " bits"
Sets the
.I g_lint
debug flags to
.I bits.
See the
.I -r
option
for more details.
Note that some of the report types have no corresponding diagnostics.
.SH EXAMPLE
The command
.sp
.in +5
\fIg_lint -a 35 -e 25 -c -g 1 -r 31 -t 0.01 kitchen.g appliances\fR
.in -5
.sp
fires a ray every millimeter and produces overlap reports
and every type of air-related report,
but no vacuum reports.

.SH SEE ALSO
mged(1), librt(3), strtoul(3), plot3(5)
.SH AUTHOR
Paul Tanenbaum
.SH SOURCE
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5068  USA
.SH BUG REPORTS
Reports of bugs should be submitted via the
.I cadbug.sh
shell script.
Alternatively, bugs or problems may be submitted by electronic mail
to <devs@brlcad.org>.
