.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.TH G_QA 1
.SH NAME
g_qa \- a BRL-CAD geometry analysis tool
.SH SYNOPSIS
.BR "g_qa " "[options] model.g objects"
.SH DESCRIPTION
The 
.I g_qa 
program computes the weight, and volume of the 
.I objects
specified from the given 
.I model.g
geometric desctription.
It also reports overlaps.
Only the 
.I objects
from the database specified on the command line are analyzed.
It works by shooting grids of rays from the three axis-aligned directions.  
The resulting weight calculations for each axis of computation are compared to each other.
The grid of rays is progressively refined until the results from all three axes of computation agree 
within a given tolerance.

.SH OPTIONS
.TP
.B -a analysis_flags
Specifies which computations are to be performed.  The parameter is one or more of the following:
.B a, o, w, v,
for 
.I all, overlaps, weight
and 
.I volume 
respectively.  Only those reports requested will be provided.  The default is 
.I all.
.TP
.B \-f filename
Specifies that density values should be taken from an external file instead of from the _DENSITIES object in the database.
.TP
.B -g gridsize

Specifies the spacing between rays in the grids.  The default value is
50.0mm or a minumum of 10 rays per axis of the bounding box of the
geometry.  For example, a geometry with a 10x10x10mm bounding box
would (by default) get a 1mm grid size.  If the user specifies a
value, it is used.  If that value does not guarantee 10 samples per
axis, a warning is printed.  If the user does not specify a grid size,
the program will set the grid size to asure 10 rays/axis.  The gridsize may be specified with units.  For example:
.B 5mm
or 
.B 10in.

.TP
.B -m hits
Specifies that the grid be refined until each region has at least 
.I hits
ray intersections.

.TP
.B \-P ncpu
Specifies that
.I ncpu
CPU's should be used for performing the caluclation.  Note that
specifying more cpus than are present on the machine does not increase
the number of computation threads.  By default, all local cpu's are
utilized.  This option exists primarily to reduce the number of
computation threads from the machine maximum.
.TP
.B \-t tolerance
Specifies a tolerance value which the 3 view computations must be within for computation to complete.  The default value is 0.5.

.TP
.B \-r
Specifies that per-region statistics about volume and weight are desired.

.TP
.B \-q num_samples
Specifies that the tolerance of at least 
.I num_samples
(10 by default) samples per axis be applied to the smallest region bounding box, not the model bounding box.  This results in much tighter grids, longer runtimes, and higher quality answers.

.SH EXAMPLES
.P
To compute the weight an volume of objects.
.IP
g_qa -a wv 
.SH AUTHOR
.SH 