'\" t
.\"     Title: BRLCAD-CONFIG
.\"    Author:
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/04/2012
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "BRLCAD\-CONFIG" "1" "12/04/2012" "BRL\-CAD" "BRL\-CAD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
brlcad-config \- script to get information about the installed version of BRL\-CAD
.SH "SYNOPSIS"
.HP \w'\fBbrlcad\-config\fR\ 'u
\fBbrlcad\-config\fR [\-\-prefix\ [\fI=DIR\fR]] [\-\-libs] [\-\-cflags] [\-\-version] [\-\-help]
.SH "DESCRIPTION"
.PP
\fBbrlcad\-config\fR
is a script that describes the compile and linker flags that should be used to compile and link programs that use
\fIBRL\-CAD\fR\*(Aqs libraries\&.
.SH "OPTIONS"
.PP
\fBbrlcad\-config\fR
.RS 4
accepts the following options:
.RE
.PP
\fB\-\-prefix=PREFIX\fR
.RS 4
If specified, use the provided installation PREFIX instead of the prefix that
\fIBRL\-CAD\fR
was compiled with when providing the output for the other
\fBbrlcad\-config\fR
script options\&.
.RE
.PP
\fB\-\-libs\fR
.RS 4
Prints out library linker flags that are generally needed when creating a program that links to
\fIBRL\-CAD\fR
libraries\&.
.RE
.PP
\fB\-\-cflags\fR
.RS 4
Prints out compilation flags that are generally needed when creating a program that refers to
\fIBRL\-CAD\fR
headers\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Prints out the version of
\fIBRL\-CAD\fR
that is installed\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display usage\&.
.RE
.SH "SEE ALSO"
.PP
\fBbrlcad\fR(1),
\fBlibbu\fR(3),
\fBlibbn\fR(3),
\fBlibrt\fR(3),
\fBlibwdb\fR(3)\&.
.SH "BUGS"
.PP
No bugs known for
\fBbrlcad\-config\fR\&.
.SH "AUTHOR"
.PP
Christopher Sean Morrison
.SH "COPYRIGHT"
.PP
This software is Copyright (c) 2007\-2012 United States Government as represented by the U\&.S\&. Army Research Laboratory\&. All rights reserved\&.
.SH "BUG REPORTS"
.PP
Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad\&.org>\&.
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
