.TH G-TANKILL 1 BRL-CAD
.\"                    G - T A N K I L L . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
g-tankill \- TANKILL Translator (BRL-CAD to TANKILL)
.SH SYNOPSIS
.B g-tankill
[-v] [-xX lvl] [-i idents_file] [-s surroundings_code] [-a abs_tol] [-r rel_tol] [-n norm_tol] [-o tankill_file] database.g object(s)
.SH DESCRIPTION
.I g-tankill\^
converts the specified
.I object(s)
from a BRL-CAD
.I database.g
file to the
.I TANKILL
format.
The
.I tankill_file
represents each object as a series
of triangular faces.
This converter creates a region for each object ident number by unioning
together all the objects with the same ident number. The
.I -x
option specifies a LIBRT debug flag, and the
.I -X
option specifies an NMG-Library debug flag. The
.I -a
,
.I -r
, and
.I -n
options specifiy tesselation tolerances. The
.I -o
option specifies the name of the file to receive the output
(stdout is the default). The
.I -i
option specifies that ident numbers should be assigned sequentially
rather than using the idents assigned in the BRL-CAD model. A list
of the regions and the assigned idents are written to
.I idents_file
along with the BRL-CAD ident number, aircode, gift material code,
los, and any material name assigned through the
.I mater
command. The
.I -s
option specifies that the provided surroundings code should be used for
all the components in the
.I TANKILL
output model.  The default is to use a surroundings code of 1000.
.SH EXAMPLE
.RS
$ \|\fIg-tankill \|-o sample.tankill \|sample.g \|sample_object\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
