# - Find UtahRLE binaries and libraries
#
# The following variables are set:
#
# UTAHRLE_LIBRARY

FIND_LIBRARY(UTAHRLE_LIBRARY NAMES utahrle)

FOREACH(pattern ${UTAHRLE_PATH_NOMATCH_PATTERNS})
	IF(UTAHRLE_LIBRARY MATCHES "${pattern}")
		SET(UTAHRLE_LIBRARY "utahrle-NOTFOUND")
	ENDIF(UTAHRLE_LIBRARY MATCHES "${pattern}")
ENDFOREACH(pattern ${UTAHRLE_PATH_NOMATCH_PATTERNS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UTAHRLE DEFAULT_MSG UTAHRLE_LIBRARY)
