# - Find STEP Class Library binaries and libraries
#
# The following variables are set:
#
# OPENNURBS_LIBRARY

FIND_LIBRARY(OPENNURBS_LIBRARY NAMES opennurbs openNURBS OpenNURBS)

FOREACH(pattern ${OPENNURBS_PATH_NOMATCH_PATTERNS})
	IF(OPENNURBS_LIBRARY MATCHES "${pattern}")
		SET(OPENNURBS_LIBRARY "openNURBS-NOTFOUND")
	ENDIF(OPENNURBS_LIBRARY MATCHES "${pattern}")
ENDFOREACH(pattern ${OPENNURBS_PATH_NOMATCH_PATTERNS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENNURBS DEFAULT_MSG OPENNURBS_LIBRARY)
