# - Find OpenNURBS
#
# The following variables are set:
#
#  OPENNURBS_INCLUDE_DIRS   - where to find zlib.h, etc.
#  OPENNURBS_LIBRARIES      - List of libraries when using zlib.
#  OPENNURBS_FOUND          - True if zlib found.

FIND_PATH(OPENNURBS_INCLUDE_DIR opennurbs.h)
FIND_LIBRARY(OPENNURBS_LIBRARY NAMES opennurbs openNURBS OpenNURBS)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENNURBS DEFAULT_MSG OPENNURBS_LIBRARY OPENNURBS_INCLUDE_DIR)

IF (OPENNURBS_FOUND)
    SET(OPENNURBS_INCLUDE_DIRS ${OPENNURBS_INCLUDE_DIR})
    SET(OPENNURBS_LIBRARIES    ${OPENNURBS_LIBRARY})
ENDIF()