MACRO(RESET_CACHE_FILE)
	SET(CACHE_FILE "")
	IF(EXISTS ${CMAKE_BINARY_DIR}/CMakeCache.txt)
		FILE(READ ${CMAKE_BINARY_DIR}/CMakeCache.txt CACHE_FILE)
		STRING(REGEX REPLACE ";" "-" ENT1 "${CACHE_FILE}")
		STRING(REGEX REPLACE "\r?\n" ";" ENT "${ENT1}")
		FOREACH(line ${ENT})
			IF(NOT ${line} MATCHES "^CMAKE_")
				IF(NOT ${line} MATCHES "^//")
					IF(${line} MATCHES "FILEPATH=")
						IF(${line} MATCHES "LIB")
							STRING(REGEX REPLACE ":.*" "" var ${line})
							SET(${var} NOTFOUND CACHE FILEPATH "reset" FORCE)
						ENDIF(${line} MATCHES "LIB")
					ENDIF(${line} MATCHES "FILEPATH=")
				ENDIF(NOT ${line} MATCHES "^//")
			ENDIF(NOT ${line} MATCHES "^CMAKE_")
		ENDFOREACH(line ${ENT})
	ENDIF(EXISTS ${CMAKE_BINARY_DIR}/CMakeCache.txt)
ENDMACRO()

