find_program(SVN_EXEC NAMES svn)
IF(SVN_EXEC)
	IF(EXISTS ${CMAKE_SOURCE_DIR}/.svn)
		EXEC_PROGRAM(${SVN_EXEC} ${CMAKE_SOURCE_DIR} > ${CMAKE_BINAR_DIR}/CMakeTmp/svnstatus)
		FILE(READ  ${CMAKE_BINARY_DIR}/CMakeTmp/svnstatus SVNSTATUS)
		STRING(REGEX REPLACE "\r?\n" ";" STATUSLIST "${SVNSTATUS}")
		FOREACH(line ${STATUSLIST})
			IF(NOT ${line} MATCHES "src/other/libz/zconf.h")
				SET(SVNMESSAGE "${SVNMESSAGE}\n${line}")
			ENDIF(NOT ${line} MATCHES "src/other/libz/zconf.h")
		ENDFOREACH(line ${STATUSLIST})

		IF(SVNMESSAGE)
			MESSAGE(FATAL_ERROR "\nSVN Check:  Uncommitted files or changes in source tree, distcheck failed:\n${SVNMESSAGE}\n")
		ELSE(SVNMESSAGE)
			MESSAGE("SVN Check: Passed")
		ENDIF(SVNMESSAGE)
	ENDIF(EXISTS ${CMAKE_SOURCE_DIR}/.svn)
ENDIF(SVN_EXEC)
