#!/bin/csh

# A simple script to run all the tests
# Ian Soboroff

echo "---------------------"
echo "(# Running p21read #)"
echo "---------------------"
cd p21read
p21read
cd ..

echo "---------------------"
echo "(# Running tstatic #)"
echo "---------------------"
cd tstatic
tstatic
cd ..

echo "------------------"
echo "(# Running treg #)"
echo "See treg.out for output file"
echo "------------------"
cd treg
treg ../treg.out
cd ..

echo "-----------------"
echo "(# Running tio #)"
echo "See tio.out for output file"
echo "-----------------"
cd tio
tio testfile.step ../tio.out
cd ..

# end

