/*
 *			pro-engineer/Cakefile
 */
#include "../../Cakefile.defs"

#define PRODUCTS		proe_brl.res proe_brl_error.res
#define STATIC_PRODUCTS		proe_brl.res proe_brl_error.res
#define SRCDIR			resource
#undef BINDIR
#define BINDIR			BASEDIR/pro-engineer/text/usascii/resource
#undef BINPERM
#define BINPERM 444

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo SRCDIR:  all done

#include "../../Cakefile.rules"
