.TH BW-FB 1 BRL-CAD
.SH NAME
bw\(hyfb \- display a black and white bw image on a framebuffer
.SH SYNOPSIS
.B bw-fb
.RB [ \-ahiczRGB ]
.RB [ \-F\  framebuffer]
.RB [ \-s\  squarefilesize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
.RB [ \-S\  squarescrsize]
.RB [ \-W\  scr_width]
.RB [ \-N\  scr_height]
.RB [ \-x\  file_xoff]
.RB [ \-y\  file_yoff]
.RB [ \-X\  scr_xoff]
.RB [ \-Y\  src_yoff]
[infile.bw]
.SH DESCRIPTION
.I Bw-fb
reads a
.IR bw (5)
format file
from standard input if an input file is not given, and displays the
image on the currently selected framebuffer.
The environment variable 
.I FB_FILE
specifies
the current framebuffer, see
.IR brlcad (1).
Alternatively, the framebuffer may be explicitly specified
by using the
.B \-F
flag.
.PP
By default, the
.I bw
file, and the requested framebuffer size, is assumed to be 512x512 pixels.
Specifying the
.B \-a
flag causes the program to attempt to autosize.
A table of common image sizes is consulted, and if any match
the size of the input file, then the width and height values
associated with that size will be used.
Specifying the
.B \-h
flag changes both of these sizes to 1024x1024.
.PP
If the
.B \-i
flag is specified, the image is output from top to bottom.
Customarily,
.I bw
files are stored bottom to top, so this
inverts the image.
.PP
The
.B \-c
flag causes the screen to be cleared before the image is displayed.
The default behavior is to overwrite the current image
with the new image without clearing the screen.
.PP
The
.B \-z
flag will zoom and center on the image being displayed
to make it fill the display area.
.PP
The flags
.BR \-R , \ \-G ,\ and \ \-B
select individual color planes into which the image will be loaded.
One or more can be given.  By default all three colors are written
with the
.I bw
pixel value.
.PP
The
.BR \-w\  file_width
flag specifies the width of each scanline in the input file, in pixels.
.BR \-W\  scr_width
does the same for the display device.
.PP
The
.BR \-n\  file_height
and
.BR \-N\  scr_height
flags specify the height in scanlines of the input file or display device
respectively.
.PP
.BR \-s\  squarefilesize
and
.BR \-S\  squarescrsize
set both the height and width to the size given.
.PP
.BR \-x\  file_xoff,
.BR \-y\  file_yoff,
.BR \-X\  scr_xoff,
and
.BR \-Y\  scr_yoff
will offset into the file or onto the screen by the given amounts.
The coordinate system for these offsets is first quadrant, with
the origin at the lower left corner of the image.
.SH "FORMAT"
A
.IR bw (5)
file contains sequences of pixels.
Each pixel is stored as one
.B unsigned char
The first pixel in a
.I bw
file is the lower left corner of the image.
The pixels proceed from left-to-right across each scanline,
with scanlines being written from the bottom to the top of the image.
.SH "SEE ALSO"
fb-bw(1), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
