.TH CAT-FB 1 BRL-CAD
.\"                       C A T - F B . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
cat\(hyfb \(em display a troff C/A/T document on a framebuffer
.SH SYNOPSIS
.B cat-fb
.RB [ \-hcoO ]
.RB [ \-F\  framebuffer]
.RB [ \-C\  r/g/b]
.RB [ \-{sS}\  squarescrsize]
.RB [ \-{wW}\  scr_width]
.RB [ \-{nN}\  scr_height]
[troff_files]
.SH DESCRIPTION
.I cat-fb
reads a
.IR troff (1)
C/A/T phototypesetter document
from the named file(s), or from
standard in if no file is specified.
The document is converted to a bitmap using the
Berkeley font files from /usr/lib/vfont and
.IR libfont (3),
and is either displayed
on the currently selected framebuffer,
or output as a
.IR pix (5)
format image.
The environment variable FB_FILE specifies
the current framebuffer, see
.IR brlcad (1).
Alternatively, the framebuffer may be explicitly specified
by using the
.B \-F
flag.
.PP
By default,
the requested framebuffer size is assumed to be 512x512 pixels.
Specifying the
.B \-h
flag changes the size to 1024x1024.
.PP
The
.BI \-w\  scr_width
and
.BI \-W\  scr_width
flags specifies the width of each scanline for the display device,
in pixels.
.PP
The
.BI \-n\  scr_height
and
.BI \-N\  scr_height
flags specifies the height of each scanline for the display device.
.PP
.BI \-s\  squarescrsize
and
.BI \-S\  squarescrsize
set both the height and width to the size given.
.PP
By default, the text bitmaps are overlaid on top of the
image resident in the current framebuffer.
However, the
.B \-c
flag causes the screen to be cleared before the image is displayed.
The
.B \-O
flag specifies that the background image is to be read instead
from standard input.  This forces the
.IR troff (1)
input to be stored in a temporary file which is given as a parameter.
If the
.B \-o
flag is given, then no framebuffer operations are performed, and
the output image is written to standard output.
If this option is specified, and the
.B \-O
option is not given, then the
.B \-c
(clear) operation is silently forced.
.PP
The default color of the text is full intensity white.
This can be changed by specifying the text color option
.BI \-C r/g/b
where each of "r", "g", and "b" represent integers from 0 to 255,
and the slashes (``/'') are entered literally.
.SH NOTES
Because the way that text is processed (top to bottom) is different
from the way that
.IR pix (5)
files are processed (bottom to top), any
.IR pix (5)
files input or output will need to be processed with an
inversion
.B \-i
flag on other tools.
.SH EXAMPLES
Simple white on black typesetting:
.sp .5
  tbl files | eqn | troff -t - | cat-fb -c
.LP
Typesetting on top of a nice shaded background:
.sp .5
  tbl files | eqn | troff -t - > doc.tr
  pixbackgnd -i 160 200 | cat-fb -O doc.tr
.LP
Typesetting upside-down:
.sp .5
  tbl files | eqn | troff -t - | cat-fb -o | pix-fb
.SH "SEE ALSO"
pix-fb(1), fb-pix(1), troff(1), libfb(3), libfont(3), pix(5)
.SH DIAGNOSTICS
``cat-fb: -O ignored, stdin used for C/A/T code''.
An attempt was made to take both the overlay picture and
the C/A/T code from stdin.
.PP
``cat-fb:  X off right edge of screen''.
An attempt was made to typeset the character ``X'' beyond the right
edge of the screen/file.
.SH FILES
 .railmag
 /usr/lib/vfont/railmag
.SH AUTHOR
Ronald B. Natalie
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
