.TH FB-BW 1 BRL-CAD
.\"                        F B - B W . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
fb\(hybw \- save a framebuffer image in a black and white bw file
.SH SYNOPSIS
.B fb-bw
.RB [ \-hi ]
.RB [ \-F framebuffer]
.RB [ \-X\  scr_xoff]
.RB [ \-Y\  scr_yoff]
.RB [ \-s\  squaresize]
.RB [ \-w\  width]
.RB [ \-n\  height]
[file.bw]
.SH DESCRIPTION
.I Fb-bw
will take a region of a framebuffer display and save it as a black and
white
.IR bw (5)
format file.
The environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad (1)).
If this variable is not set, the default device for your system will
be used.
Alternatively, the framebuffer may be explicitly specified
by using the
.B \-F
flag.
.PP
By default, the output file will be made size 512x512 pixels.
Specifying the
.B \-h
flag, changes the default to 1024x1024.
The
.B \-s
flag will set both the file height and width to be the given size, while
.B \-w
and
.B \-n
sets them individually.
.PP
A first quadrant coordinate system is used (origin in lower left of
screen), and the area saved is normally from this origin.  The
.B \-X
and
.B \-Y
flags can be used to move the origin to an offset position on the screen.
The
.B \-i
flag switches to a fourth quadrant system, both in the storage order as
well as the origin offset coordinates (i.e. origin is now the upper left
corner of the screen).
.PP
An equal blending of red, green, and blue is done.  For more complicated
black and white conversion use
.IR fb-pix (1)
and
.IR pix-bw (1).
.SH "SEE ALSO"
brlcad(1), bw-fb(1), fb-pix(1), pix-bw(1), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
