.TH FB-BW 1 BRL-CAD
.SH NAME
fb\(hybw \- save a framebuffer image in a black and white bw file
.SH SYNOPSIS
.B fb-bw
.RB [ \-hi ]
.RB [ \-X\  scr_xoff]
.RB [ \-Y\  scr_yoff]
.RB [ \-s\  squaresize]
.RB [ \-w\  width]
.RB [ \-n\  height]
[file.bw]
.SH DESCRIPTION
.I Fb-bw
will take a region of a framebuffer display and save it as a black and
white
.IR bw (5)
format file.
The environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad (1)).
If this variable is not set, the default device for your system will
be used.
By default, the output file will be made size 512x512 pixels.
Specifying the
.B \-h
flag, changes the default to 1024x1024.
The
.B \-s
flag will set both the file height and width to be the given size, while
.B \-w
and
.B \-n
sets them individually.
.PP
A first quadrant coordinate system is used (origin in lower left of
screen), and the area saved is normally from this origin.  The
.B \-X
and
.B \-Y
flags can be used to move the origin to an offset position on the screen.
The
.B \-i
flag switches to a fourth quadrant system, both in the storage order as
well as the origin offset coordinates (i.e. origin is now the upper left
corner of the screen).
.PP
An equal blending of red, green, and blue is done.  For more complicated
black and white conversion use
.IR fb-pix (1)
and
.IR pix-bw (1).
.SH "SEE ALSO"
brlcad(1), bw-fb(1), fb-pix(1), pix-bw(1), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
