.TH FB-PNG 1 BRL-CAD
.SH NAME
fb-png - save a framebuffer image in a color Portable Network Graphics (PNG) file
.SH SYNOPSIS
.B fb-png
.RB [ -hic ]
.RB [ -F  framebuffer]
.RB [ -s  squaresize]
.RB [ -w  width]
.RB [ -n  height]
[file.png]
.SH DESCRIPTION
.I Fb-png
will take a region of a framebuffer display and save it as a color
.IR png
format file.
The environment
variable
.I
.SM FB_FILE
is used to select the display device (see
.IR brlcad(1) ).
If this variable is not set, the default device for your system will
be used.
Alternatively, the framebuffer may be explicitly specified
by using the
.I -F
flag.
.PP
By default, the output
.I png
file, and the requested framebuffer size, is assumed to be 512x512 pixels.
Specifying the
.I -h
flag, changes the default to 1024x1024.
The
.I -s
flag will set both the file height and width to be the given size, while
.I -w
and
.I -n
sets them individually.
.PP
A first quadrant coordinate system is used (origin in lower left of
screen), and the area saved is normally from this origin.
The
.I -i
flag switches to a fourth quadrant system, both in the storage order as
well as the origin offset coordinates (i.e. origin is now the upper left
corner of the screen).
.PP
The
.I -c
flag specifies that the color map in the frame buffer should
be applied to the pixel values (``crunched'') before they are written to the
output file.
.SH "SEE ALSO"
brlcad(1), png-fb(1), fb-bw(1), pix(5)
.SH AUTHOR
John R. Anderson
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
