.TH FBANIM 1 BRL-CAD
.\"                       F B A N I M . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
fbanim \- animate small images on framebuffer using hardware pan and zoom
.SH SYNOPSIS
.B fbanim
.RB [ \-hirv ]
.RB [ \-S\  screen\ squaresize]
.RB [ \-W\  screen\ width]
.RB [ \-N\  screen\ height]
.RB [ \-s\  file\ squaresize]
.RB [ \-w\  file\ width]
.RB [ \-n\  file\ height]
.RB [ \-p\  npasses]
width nframes [fps]
.SH DESCRIPTION
.I Fbanim
assumes that the current framebuffer (determined by environment variable
FB_FILE) contains a collection of small square
images ``tiled'' together by
.IR pixtile (1).
This permits a limited sequence of low resolution images to be viewed at
various speeds, to create the sensation of motion, or to highlight
the differences between the frames.
The typical use of this program is to animate sequences of 64x64 or 128x128
tiles generated by animation studies.
It can also be used to create ``blink comparisons'' between a small number
of large images.
.PP
The width of each tile is specified by the
.I width
argument, and the number of tiles is specified by the
.I nframes
argument.
The optional argument
.I fps
specifies the number of frames (tiles) per second to be displayed.
24 fps is the standard movie rate, 30 the standard video rate.
Slower rates may also be used.  The default is 8 frames/second.
.PP
By default, the framebuffer is assumed to be
loaded with a 512x512 pixel image.
Specifying the
.B \-h
flag, changes the default to 1024x1024.  Alternatively, the
.B \-SWN
flags can be used in the normal way to specify the size of
the screen (see
.IR brlcad (1)).
.PP
By default, the sequence of tiles is considered to be a circular (repeating)
sequence, ie, the first tile immediately follows the last one.
If this is not the case, the
.B \-r
flag will cause the sequence to ``rock'' from beginning to end to beginning,
which is sometimes more pleasing.
.PP
The
.B \-v
flag will cause the frame number and
center coordinates of each frame to be printed
as they are passed to fb_window(), for debugging purposes.
.PP
By default, the
.I fbanim
program repeats for 100 passes.  When creating demonstration scripts,
it may be desirable to specify the number of passes through the animation.
The
.BI \-p\  npasses
option is used to indicate this.
.PP
For compatability with old animation images which were generated by
fourth-quadrant programs, where the first image starts in the upper left
corner of the screen rather than the lower left corner, the
.B \-i
flag is used to indicate this inverse order.
.SH "SEE ALSO"
brlcad(1), pixtile(1), pix-fb(1), pix(5)
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
