.TH FBCLEAR 1 BRL-CAD
.\"                      F B C L E A R . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
fbclear \- clear a frame buffer image
.SH SYNOPSIS
.B fbclear
.RB [ \-h\ \-c ]
.RB [ \-F\  framebuffer]
[red green blue]
.PP
.B fbclear
.RB [ \-h\ \-c ]
.RB [ \-F\  framebuffer]
[gray_value]
.RB
.SH DESCRIPTION
.I Fbclear
is used to erase a frame buffer using whatever method is efficient for the
device being accessed.
By default, the selected color will be flooded into the color planes.
If the
.B \-c
option is used,
a standard linear colormap will be loaded and the pan and zoom values
will be reset.
.PP
If the optional color values are given,
.I fbclear
writes the specified color over the entire
image.
The color values must be in the range 0 to 255.
In the second form shown above, the single gray_value is written into
all three color channels.
.PP
The frame buffer to be cleared is determined from the
.B \-F
option if given.
Otherwise the environment variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad (1)).
If this variable is not set, the default device for your system will
be used.
If the
.B \-h
option is used on those devices where it makes a difference (e.g. Adage),
the
.SM
.B HIRES
(1024x1024x24) memory is cleared; otherwise a
.SM
.B LORES
(512x512x24) device is assumed.
.PP
In addition to those flags shown above, the
.BI \-W\  width
.BI \-N\  height
and
.BI \-S\  square_size
flags can be used to set the size of the output frame buffer.
.SH "SEE ALSO"
brlcad(1), fbcmap(1), fbhelp(1)
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
