.TH FBCMAP 1 BRL-CAD
.\"                       F B C M A P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
fbcmap \- change the color map of a frame buffer
.SH SYNOPSIS
.B fbcmap
.RB [ \-h ]
.RB [ \-F\  framebuffer]
.RB [ \-{sS}\  squarescrsize]
.RB [ \-{wW}\  scr_width]
.RB [ \-{nN}\  scr_height]
[map_number]
.SH DESCRIPTION
.I Fbcmap
is used to change the color map of a frame buffer.
The environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad (1)).
If this variable is not set, the default device for your system will
be used.
.PP
The requested framebuffer size will be the default size for the
selected device (often 512x512 pixels).
Specifying the
.B \-h
flag changes the size to 1024x1024.
.PP
The
.BI \-w\  scr_width
and
.BI \-W\  scr_width
flags specifies the width of each scanline for the display device,
in pixels.
.PP
The
.BI \-n\  scr_height
and
.BI \-N\  scr_height
flags specifies the height of each scanline for the display device.
.PP
.BI \-s\  squarescrsize
and
.BI \-S\  squarescrsize
set both the height and width to the size given.
This size distinction is important only for devices like the Adage
framebuffers which have different operating modes based on the
display size.
.PP
If an optional color
.I map_number
is given, that map is used;
the default is the standard linear map.
There are currently six other maps supplied
numbered 1 through 6 as follows:
.TP
1
reverse-linear (negative) map.
.TP
2
one corrected for Polaroid 809/891 film.
.TP
3
a linear mapping in which the first 100 values are black.
.TP
4
a linear map with values 1->191 incremented by 64 to boost dim pictures.
The values at 191 and above are all full on.  Zero remains at zero.
.TP
5
a gamma correcting color map used by the University of Utah Alpha_1 project.
A better source of gamma correction is the
.IR fbgamma (1)
utility.
.TP
6
a map with a series of color deltas.
This map is mostly black with the following colors,
appearing at multiples of 32,
having values full on:
white (0), magenta (32), red (64), yellow (96), green (128),
cyan (160), blue (192).  This map is most useful in conjunction
with
.IR fbcmrot (1)
and will show which pixels have the same intensities in one, two, or
all three color planes.
.PP
There are also three special maps used to quickly change the display
to a solid color for adjusting a camera without losing image memory,
numbered 10 through 12 for
black,
white,
and 18% neutral grey, respectively.
.SH "SEE ALSO"
brlcad(1), fbcmrot(1), fbgamma(1), cmap-fb(1), fb-cmap(1), cmap(5)
.SH AUTHORS
Gary S. Moss
.br
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
