.TH FBCOLOR 1 BRL-CAD
.\"                      F B C O L O R . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
fbcolor \- interactively pick colors
.SH SYNOPSIS
.B fbcolor
.RB [ \-h ]
.RB [ \-S\  screen\ squaresize]
.RB [ \-W\  screen\ width]
.RB [ \-N\  screen\ height]

.SH DESCRIPTION
.I Fbcolor
is an interactive color picking facility.
It allows you to pick and display colors, by varying parameters in
either RGB (red, green, blue)
or HSI (hue, saturation, intensity) space.
The environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad (1)).
If this variable is not set, the default device for your system will
be used.
If the
.B \-h
option is used,
1024x1024 resolution is used.
Alternatively, the
.B \-SWN
options can all be used in the normal way to specify the size of
the screen (see
.IR brlcad (1)).
.PP
.I Fbcolor
draws a set of color bars in the lower left corner of the display,
sets the remainder of the display to the current color,
then starts reading standard in for color editing commands.
As you change the various parameters which specify
the color, the color bars grow and shrink to show the relative red, green
and blue intensities.
.PP
At the same time,
.I fbcolor
displays the current RGB and HSI values on your terminal.  This
allows you to record the RGB or HSI values of the colors you
select for later use.
.PP
.I Fbcolor
recognizes two main sets of commands; those which select which parameter to
edit, and those which vary the value of the selected parameter.
.RB `` r '',
.RB `` g '',
and
.RB `` b ''
selects the red, green, or blue color for editing, while
.RB `` h '',
.RB `` s '',
and
.RB `` i '',
(or
.RB `` v '')
selects the hue, saturation, or intensity for editing.
There is one other parameter selection character, the
.RB `` / '',
which steps through the list of color parameters in the order
given above.
.PP
.RB `` + ''
and
.RB `` . ''
both increment the currently selected parameter by one;
.RB `` - ''
and
.RB `` , ''
both decrement by one, and
.RB `` > ''
and
.RB `` < ''
increments and decrements by 16.
The value of each of the parameters
can range from 0 to 255
and all parameters wrap in both directions.
.PP
A
.RB `` ? ''
prints a short command summary,
and typing
.RB `` q '',
.RB `` Q '',
.RB `` <CR> '',
or
.RB `` <LF> ''
exits the program.
.SH "SEE ALSO"
brlcad(1), fbclear(1), fbcmap(1)
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
