.TH FBFADE \*(ms "BRL-CAD package"
.\"                       F B F A D E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
'\" Edit the next two lines to configure for your system:
.ds ms 1\" utility manual section, normally 1B -- alternatives are 1, 1L, etc.
.ds ls 3\" library manual section, normally 3B -- alternatives are 3, 3L, etc.
.ds fs 5\" format manual section, normally 4B -- alternatives are 5, 4L, etc.
.ie t .ds pf B\" "printout" font, normally (CW -- use B if you don't have one
.el .ds pf 1
'\"
.de CW
.lg 0
\%\&\\$3\f\*(pf\\$1\fP\&\\$2
.lg
..
.SH NAME
fbfade \- fade a frame buffer image in or out
.SH SYNOPSIS
.CW fbfade
[
.CW -h
] [
.CW -f
.I "input image name"
] [
.CW -s
.I "input square size"
] [
.CW -w
.I "input width"
]
.br
	[
.CW -n
.I "input height"
] [
.CW -S
.I "output square size"
] [
.CW -W
.I "output width"
] [
.CW -N
.I "output height"
]
.br
	[ [
.CW -F
]
.I "output frame buffer name"
]
.SH DESCRIPTION
.CW fbfade
gradually displays an image on a frame buffer,
one randomly chosen pixel at a time.
.SS Options
.TP "\w'\f\*(pf-F\fP \fIoutput frame buffer name\fP\ \ \ 'u"
.CW -h
(``high resolution'')\
Assumes 1024 by 1024 pixels for default input image size
instead of 512 by 512.
Explicitly specified sizes override the default,
and if actual input image size is smaller than requested,
the actual size will be used.
If output frame buffer size is not specified,
the revised input size will be requested for output.
If actual output frame buffer size is greater than requested,
only the lower-left portion of the frame buffer will be used.
Actual sizes depend on details of specific frame buffers.
.TP
\f\*(pf-f\fP \fIinput image name\fP
Inputs the image to be displayed
from the specified frame buffer or \fIpix\^\fP(\*(fs) file,
instead of using pure background
(which fades out the image already
on the output frame buffer).
.TP
\f\*(pf-s\fP \fIinput square size\fP
Specifies input image width and height.
.TP
\f\*(pf-w\fP \fIinput width\fP
Specifies input image width.
.TP
\f\*(pf-n\fP \fIinput height\fP
Specifies input image height.
.TP
\f\*(pf-S\fP \fIoutput square size\fP
Specifies output frame buffer width and height.
.TP
\f\*(pf-W\fP \fIoutput width\fP
Specifies output frame buffer width.
.TP
\f\*(pf-N\fP \fIoutput height\fP
Specifies output frame buffer height.
.TP
\f\*(pf-F\fP \fIoutput frame buffer name\fP
Outputs to the specified frame buffer
instead of the one specified by the
.CW FB_FILE
environment variable
(or the default, if
.CW FB_FILE
is not set).
If this is the last option specified, the
.CW -F
is optional.
.SH CAVEAT
.CW fbfade
works best in conjunction with a frame buffer having very fast access to pixels.
.SH EXAMPLE
The following shell script can be used to produce a slick ``slide show'':
.RS
\f\*(pffbclear
.br
for \|i \|in \|*.pix
.br
do	fbfade \|-f $i
.br
	sleep \|15
.br
done
.br
fbfade\fP
.RE
.SH "SEE ALSO"
libfb(\*(ls), pix(\*(fs).
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHORS
Douglas A.\& Gwyn, BRL/VLD-VMB
.br
Gary S.\& Moss, BRL/VLD-VMB
