.TH FBFREE 1 BRL-CAD
.\"                       F B F R E E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
fbfree \- free any frame buffer resources
.SH SYNOPSIS
.B fbfree
.RB [ \-F
.IR framebuffer ]
.SH DESCRIPTION
.I Fbfree
is used to free any resources associated with a frame buffer.
Its most common use is to close down an
.IR fbserv (1)
process and its associated frame buffer.
This command can also be used to free any shared memory segments
on e.g. Sun and SGI frame buffers.
.PP
This program simply calls the fb_free() routine in
.IR libfb (3).
.SH "SEE ALSO"
brlcad(1), fbclear(1), libfb(3)
.SH AUTHORS
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
