.TH FBFRAME 1 BRL-CAD
.\"                      F B F R A M E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
fbframe \- place a colored frame around a framebuffer
.SH SYNOPSIS
.B fbframe
.RB [ \-h ]
.RB [ \-F\ framebuffer]
.RB [\-w\ frame_width]
.RB [\-n\ frame_height]
.RB [ \-s\ squareframesize]
.SH DESCRIPTION
.I Fbframe
places a colored frame around the edge pixels of a framebuffer.
It is mostly for purposes of framebuffer alignment.
The
.B \-F
option can be used to specify the frambuffer.
If this option is omitted,
the environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad (1)).
If the variable is not set, the default device for your system will
be used.
.PP
The frame starts in the lower left with a red line running to the
right to the next to last pixel.  Next, a green line from there up to the next
to top scan line is drawn.  Then blue across the top scan line to the next to
first column.  Finally a white line down the left edge stopping just
above the red line.
.PP
By default, the dimensions of the frame will be taken from the framebuffer
used.  Alternatively, one or more of the options
.B \-h \-s \-w \-n
may be used to set the dimensions of the frame drawn.
.PP
The
.B \-h
option sets the frame dimensions to
1024x1024.
The options
.BI \-w\  frame_width
and
.BI \-n\  frame_height
are used to
specify the width and height in scanlines of the frame on the framebuffer
respectively.
The
.BI \-s\  squareframesize
option specifies both the height and width of the frame to be drawn.

.SH "SEE ALSO"
brlcad(1), fbgrid(1)
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
