.TH FBFRAME 1 BRL-CAD
.\"                      F B F R A M E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
fbframe \- place a colored frame around a framebuffer
.SH SYNOPSIS
.B fbframe
.RB [ \-h ]
.RB[ \-F\ framebuffer]
.RB [\-w\ frame_width]
.RB [\-n\ frame_height]
.RB [ \-s\ squareframesize]
.SH DESCRIPTION
.I Fbframe
places a colored frame around the edge pixels of a framebuffer.
It is mostly for purposes of framebuffer alignment.
The
.B \-F
option can be used to specify the frambuffer.
If this option is omitted,
the environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad (1)).
If the variable is not set, the default device for your system will
be used.
.PP
The frame starts in the lower left with a red line running to the
right to the next to last pixel.  Next, a green line from there up to the next
to top scan line is drawn.  Then blue across the top scan line to the next to
first column.  Finally a white line down the left edge stopping just
above the red line.
.PP
By default, the dimensions of the frame will be taken from the framebuffer
used.  Alternatively, one or more of the options
.B \-h \-s \-w \-n
may be used to set the dimensions of the frame drawn.
.PP
The
.B \-h
option sets the frame dimensions to
1024x1024.
The options
.BI \-w\  frame_width
and
.BI \-n\  frame_height
are used to
specify the width and height in scanlines of the frame on the framebuffer
respectively.
The
.BI \-s\  squareframesize
option specifies both the height and width of the frame to be drawn.

.SH "SEE ALSO"
brlcad(1), fbgrid(1)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
