.TH FBLABEL 1 BRL-CAD
.\"                      F B L A B E L . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
fblabel \- display a text string on a framebuffer
.SH SYNOPSIS
.B fblabel
.RB [ \-hca ]
.RB [ \-F\  framebuffer]
.RB [ \-f\  fontname]
.RB [ \-C\  r/g/b]
.RB x_position
.RB y_position
.RB text_string
.SH DESCRIPTION
.I Fblabel
writes a text string to
the image on the currently selected framebuffer.
The text string will be filtered to the image currently
displayed.
Use
.IR fbpoint (1)
to determine where to position the text string.
The lower left corner of the text string starts
displaying at the x and y position given.
The environment variable FB_FILE specifies
the current framebuffer, see
.IR brlcad (1).
Alternatively, the framebuffer may be explicitly specified
by using the
.B \-F
flag.
.PP
By default, the
requested framebuffer size, is assumed to be 512x512 pixels.
Specifying the
.B \-h
flag changes the size to 1024x1024.
.PP
The
.B \-c
flag causes the screen to be cleared before the text string is displayed.
The default behavior is to label the current image
without clearing the screen.
.PP
The
.B \-a
The flag causes the text not to be filtered against the frame buffer image.
.PP
The
.B \-C r/g/b
specifies red, green, and blue rgb values [0..255] for the text.
The default color is white.
.PP
The
.B \-f fontname
flag will change the current default
font from nonie.r.12 to "/usr/lib/vfont/fontname".
.SH "FONTS"
.I Fblabel
expects the Berkley fonts in the directory /usr/lib/vfont.
The fonts are expected to be in Vax byte order,
even if that is not the natural byte order of the machine,
to avoid having to create a font converter.
.SH EXAMPLE
fblabel -h -f "oldenglish.14" `fbpoint -h` "Hello"
.SH "SEE ALSO"
brlcad(1), fbed(1), fbpoint(1), libfb(3), pix(5)
.SH AUTHOR
Paul Randal Stay
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
