.TH FBSCANPLOT 1 BRL-CAD
.\"                   F B S C A N P L O T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
fbscanplot \- plot the intensities of a framebuffer scanline
.SH SYNOPSIS
.B fbscanplot
.RB [ \-h ]
.RB [ \-v ]
.RB [ \-o ]
.RB [ \-c ]
.RB [ \-r ]
.RB [ \-W\  scr_width]
.RB [ \-F\  outframebuffer]
yline
.SH DESCRIPTION
.I Fbscanplot
will plot the red, green, and blue, pixel intensities of a selected
scanline of a framebuffer.  The line to be plotted has a first quadrant
y coordinate of
.IR yline ,
i.e. a value of zero indicates the bottom line of the display.
The environment
variable
.B
.SM FB_FILE
is used to select the input display device (see
.IR brlcad (1)).
If this variable is not set, the default device for your system will
be used.
The output will appear on this same device unless a
.BI \-F\  outframebuffer
flag is given to redirect the output.
.PP
If no size if specified the selected device(s) will be opened at it's
default size (usually the full screen).  The flag
.BI \-W\  scr_width
can be used to set a screen width (scanline length) other than this
default.
The
.B \-h
flag is a shorthand for a size of 1024x1024.
.PP
Either the bottom 256 or top 256 scanlines will be used to
output the plot; whichever will not cover the selected line.
A black background is drawn with horizontal grey lines
at intervals of 16 and 64 scanlines in order to provide a scale.
The intensities of the selected line are then plotted, the
bottom of the graph being intensity zero; the top 255.
.PP
The
.B \-o
flag will plot the scanline in overlay mode.  With this flag no background
or grid lines are drawn, and the output always appears in the
bottom 256 scanlines of the display.  Using this option more of the
image will remain visible, and multiple scanlines can be plotted
on top of each other for comparison.  The image may make the plot
harder to see however.
.PP
If the
.B \-r
flag is given, a reverse image of the selected scanline is
drawn, i.e. the intensities from 0->255 become 255->0.  This is
simply to highlight the line selected.  The plot will still be
of the non-reversed values.
.PP
The
.B \-v
flag causes the pixel values to be output to the terminal as
well as displayed.
.PP
The
.B \-c
flag causes the current colormap of the framebuffer to be applied
to the pixel values ("crunched") before plotting them.
This allows the effects of the color map to be readily viewed.
.SH EXAMPLE
.I fbscanplot -r 37
.br
will plot the intensities of the scanline 37 up from the bottom.
This line will be hightlighted by replacing it with its negative.
The output will appear in the top 256 scanlines so as not to cover
the selected line.
.PP
.I "fbscanplot \-v \-W512 \-o `fbpoint \-y` > scan.out"
.br
will use
.I fbpoint
to select a y scanline, then plot 512 pixel values
in overlay mode.  These values will also be saved in the file
.I scan.out
for closer examination.
.PP
A handy C-shell alias is:
.br
.I "alias fbsp 'fbscanplot \-r `fbpoint \-y`'"
.SH "SEE ALSO"
brlcad(1), fbgrid(1), fbzoom(1)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
