.TH FBZOOM 1 BRL-CAD
./"                       F B Z O O M . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
fbzoom \- modify zoom and window parameters of a frame buffer
.SH SYNOPSIS
.B fbzoom
.RB [ \-F\  frame_buffer]
.RB [ \-h ]
.RB [ \-s\  image_sqrsize]
.RB [ \-w\  image_width]
.RB [ \-n\  image_height]
.SH DESCRIPTION
Using
.IR vi (1)
and/or
.IR emacs (1)
-like keystrokes,
.I fbzoom
allows interactive zooming and panning of a frame buffer.  Using the
optional command line arguments,
.PP
.TP
.B \-F\  frame_buffer
explicitly specifies the frame buffer.  Otherwise, the environment variable
.I FB_FILE
specifies
the current framebuffer, see
.IR brlcad (1).
.TP
.B \-h
changes the frame buffer size to 1024x1024.
By default, it is assumed to be 512x512 pixels.
.TP
.B \-s\  image_sqrsize
disaplays the image file as a square,
.B image_sqrsize
pixels per side (default is 512x512).
.TP
.B \-w\  image_width
disaplays the image
.B image_width
pixels wide (default is 512).
.TP
.B \-n\  image_height
disaplays the image
.B image_height
pixels high (default is 512).
.PP
.I Fbzoom
will display the image currently in the frame buffer and then act on commands
entered by the user.  Available commands are:
.PP

.TP
.B b ^V
zoom Bigger (*2)
.TP
.B s
zoom Smaller (*0.5)
.TP
.B +
zoom Bigger (+1)
.TP
.B -
zoom Smaller (-1)
.TP
.B h B
pan Left (1)
.TP
.B j N
pan Down (1)
.TP
.B k P
pan Up (1)
.TP
.B l F
pan Right (1)
.TP
.B H ^B
pan Left (many)
.TP
.B J ^N
pan Down (many)
.TP
.B K ^P
pan Up (many)
.TP
.B L ^F
pan Right (many)
.TP
.B T
toggle sense of pan commands
.TP
.B c
goto Center
.TP
.B z
zoom 1 1
.TP
.B r
Reset to normal
.TP
.B q
Exit
.TP
.B RETURN
Exit
.PP
Note that these commands change the way the frame buffer is viewed
but not the image in the frame buffer.
.SH "SEE ALSO"
bw-fb(1), gif-fb(1), pix-fb(1), pl-fb(1), rle-fb(1)
.SH AUTHOR
Bob Suckling
.br
Michael John Muuss
.br
Gary S. Moss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
