.TH ORLE-FB 1 BRL-CAD
.\"                      O R L E - F B . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
orle\(hyfb \- decode old run-length encoded image onto a frame buffer
.SH SYNOPSIS
.B orle-fb
[
.B \-Otdv
] [
.B \-b
{
.B rgbwBG
} ] [
.B \-F
framebuffer ] [
.B \-p
x y ] [ file.rle ]
.SH DESCRIPTION
.I orle-fb\^
decodes an old, Edition-2
University of Utah standard Run-Length Encoded (RLE) format file
(saved with
.IR fb-orle\^ (1)
or a similar program)
to a frame buffer device or a file.
If
.I file.rle\^
is not specified, standard input is read.
.I orle-fb\^
determines the type and size of the saved file (color or B&W)
and acts accordingly.
The environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad(1) ).
If this variable is not set, the default device for your system will
be used.
.TP
.B \-t
Alters the normal bottom-up display order to be top-down.
This option can be useful when the image contains accompaning text.
Note that the image is inverted in memory, using as large a buffer as
.I malloc(3)
will permit.  This means that the entire image will be decoded
before output will begin appearing.
.TP
.B \-d
Debug option, provides verbose description of file structure and
processes called, written on standard error.
.TP
.B \-v
Provides a verbose description of the parameters of the saved image
on standard error.
.TP
.B \-O
Restores the image data in \fIoverlay\fP mode.
Only areas of the original image which were not the background color are
decoded.  The rest of the image already in the frame buffer is undisturbed.
Note that this mode uses twice as many DMAs to the frame buffer as
the normal mode, as the previous image must be read back into the host.
.TP
.BI \-b x\^
If the image is not being decoded in overlay mode, the background is
normally set to the value recorded in the RLE file.
This option permits
the user to specify an alternate background color from a limited
set of colors.
The character
.I x
can be any of
.B r
(red),
.B g
(green),
.B b
(blue),
.B w
(white),
.B B
(black), or
.B G
(18% grey).
.TP
.BI \-p "x y"
Reposition the image.
The original lower left corner is positioned at
.RI ( x\^ ", " y\^ )
before restoring the image.
Warning:
a saved image should not be
repositioned so that any saved data wraps around the X borders.  If the
input image is 512x512,
and it is repositioned, the framebuffer will be opened in
1024x1024 mode.
.TP
.BI \-F\ framebuffer
indicates that the output should be sent to the indicated framebuffer.
See
.IR libfb (3)
for more details on the specification of a framebuffer.
.TP
.I file.rle\^
Name of file to decode, in old RLE format.
.SH EXAMPLES
.RS
.ft I
\|orle-fb \|truck.rle
.br
\|orle-fb \|\-Ot \|text.rle
.br
\|orle-fb \|\-bG \|<car.rle
.ft R
.RE
.SH SEE ALSO
brlcad(1), rle-fb(1), fb-rle(1), rle-pix(1), pix-rle(1), librle(3),
liborle(3).
.SH BUG REPORTS
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
