.TH PIXAUTOSIZE 1 BRL-CAD
.\"                  P I X A U T O S I Z E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pixautosize \- determine if a file size or byte count is a standard image size
.SH SYNOPSIS
.B pixautosize
.RB [ \-b\  bytes_per_sample]
.RB [ \-f\  file_name]
.RB [ \-l\  file_length]
.SH DESCRIPTION
.I pixautosize
determines if a given file is one of the ``standard'' sizes used in the
BRL-CAD package, \fIi.e.\fR one of the sizes recognized by the
.B \-a
option on
.IR pix-fb (1).
If the dimensions are recognized, it prints a string suitable for use in
a Bourne shell
.IR sh (1)
script to set the variables WIDTH and HEIGHT, \fIe.g.\fR
.sp .5
.ft I
   WIDTH=512; HEIGHT=512
.fr R
.PP
The file name can be specified by using the
.BI \-f\  file_name
commandline option, or the file length (in bytes) can be
specified by using the
.BI \-l\  file_length
commandline option.
One of these two options must be present.
In either case, the
.BI \-b\  bytes_per_sample
option can be used to specify the number of bytes which are used
for each sample (pixel) in the file.
The default value is three (3), which is appropriate for use
with
.IR pix (5)
files.
This should be changed to one with
.BI \-b\  1
when processing a
.IR bw (5)
file.
Similarly, the proper value for a
.IR dbw (5)
file is 8 (1 channel of 8 byte samples),
and the value for
.IR dpix (5)
files is 24 (3 channels of 8 byte samples)
.SH "EXAMPLES"
.PP
These two examples both give the result of
.sp .5
.ft I
   WIDTH=50; HEIGHT=50;
.ft R
.sp .5
the first could be for a
.IR bw (5)
file and the second for a
.IR pix (5)
file:
.sp .5
.ft I
   pixautosize -b 1 -l 2500
.br
   pixautosize -b 3 -l 7500
.ft R
.PP
This example shows how to determine the size of a
.IR pix (5)
file by giving the file name:
.sp .5
.ft I
   pixautosize -b 3 -f ../pix/moss.pix
.sp
   WIDTH=512; HEIGHT=512
.ft I
.PP
This command can be used easily in shell scripts with a line like this:
.sp .5
.ft I
   eval `pixautosize -b 3 -f $FILE`	# sets WIDTH, HEIGHT
.ft R
.PP
For a major shell script which uses this program, examine
.IR pixinfo.sh (1)
.SH "SEE ALSO"
pixinfo.sh(1), pix-fb(1), libfb(3), bw(5), pix(5)
.SH DIAGNOSTICS
If the file or file_length specified does not match any
of the standard sizes, one of these messages is printed on standard error:
.br
.ft I
   pixautosize: unable to autosize nsamples=999
.br
   pixautosize: unable to autosize file '/dev/null'
.ft R
.br
In this case, the string printed on standard output is:
.sp .5
.ft I
   WIDTH=0; HEIGHT=0
.ft R
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
