.TH PL-FB 1 BRL-CAD
.SH NAME
pl\(hyfb \- display 3-D UNIX plot on a framebuffer
.SH SYNOPSIS
.B pl-fb
.RB [ \-hoid ]
.RB [ \-t\  line_thickness]
.RB [ \-F\  framebuffer]
.RB [ \-S\  squaresize]
.RB [ \-W\  width]
.RB [ \-N\  height]
[file.plot]
.SH DESCRIPTION
.I Pl-fb
displays a BRL extended three dimensional UNIX plot file on a framebuffer.
The environment
variable
.B
.SM FB_FILE
is used to select the display device (see
.IR brlcad(1) ).
If this variable is not set, the default device for your system will
be used.
By default, the display size is assumed to be 512x512 pixels.
Specifying the
.B \-h
flag, changes the output size to 1024x1024.
The
.BI \-S\  squaresize
.BI \-W\  width
and
.BI \-N\  height
flags allow different screen sizes to be set.  The plotting space
will fill the given screen dimensions.  No attempt is made at present
to preserve aspect.
.PP
The
.B \-o
flag is for overlay mode, where the current framebuffer image will
be left in the background.
The
.B \-i
flag causes the rasterized image to be plotted immediately, rather
than buffering up rasterized data into bands.  While useful for
quick feedback on small plots, this mode is generally more expenisve
in CPU time.
The
.B \-d
flag outputs a very verbose debugging stream to standard error
listing every UNIX plot command
and the corresponding framebuffer coordinates.
The
.B \-t
flag causes all lines to be thickened perpendicular to their length,
to the given number of pixels.
This is especially useful when making images for recording on videotape,
as single pixel lines are difficult to resolve.
The thickening will be reduced so that a
line will never be wider than it is long.
.PP
If
.I file.plot
is not specified,
the plot commands are read from standard in.
.PP
Note that 3-D UNIX plot is a superset of the standard UNIX plot
format, thus this program can display normal plot files as well.
.SH "SEE ALSO"
pl-sgi(1), plrot(1), pldebug(1), libplot3(3), brlcad(1).
.SH AUTHORS
Douglas A. Gwyn
.br
Michael John Muuss
.br
Joseph C. Pistritto
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
