.TH PNG-FB 1 BRL-CAD
.\"                       P N G - F B . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
png-fb - display a Portable Network Graphics (PNG) image file on a framebuffer
.SH SYNOPSIS
.B png-fb
.RB [ -Hhicvz1 ]
.RB [ -g screen_gamma]
.RB [ -F  framebuffer]
.RB [ -m  #lines]
.RB [ -S  squarescrsize]
.RB [ -W  scr_width]
.RB [ -N  scr_height]
.RB [ -x  file_xoff]
.RB [ -y  file_yoff]
.RB [ -X  scr_xoff]
.RB [ -Y  scr_yoff]
[file.png]
.SH DESCRIPTION
.I Png-fb
reads a
.IR PNG
format file from the named file, or from
standard in if no file is specified, and displays the
image on the currently selected framebuffer.
The environment variable FB_FILE may be used to specify
the current framebuffer, see
.IR brlcad (1).
Alternatively, the framebuffer may be explicitly specified
by using the
.I -F
flag.
.PP
By default, the requested framebuffer size, is assumed to be 512x512 pixels.
.I -h
flag changes the size to 1024x1024.
.PP
The
.I -g
option specifies the gamma value for the screen where the image is to be displayed.
Larger values will produce lighter colored display.
.PP
If the
.I -i
flag is specified, the image is inverted.
.PP
The
.I -c
flag causes the screen to be cleared before the image is displayed.
The default behavior is to overwrite the current image
with the new image without clearing the screen.
.PP
The
.I -v
option will print verbose information about the PNG file.
.PP
The
.I -H
option will print a single line on standard output providing
the dimensions of the image in a format readily usable in shell scripts,
e.g. WIDTH=42 HEIGHT=17.
.PP
The
.I -z
flag will zoom and center on the image being displayed
to make it fill the display area, using the libfb fb_zoom() routine.
fb_zoom only offers integer zoom factors, so displays with non-square
screens (such as the SGI 3D machines) may find this option of limited
usefulness.
.PP
The
.I -W  scr_width
flag specifies the width of each scanline in the display device, in pixels.
.PP
The
.I -N  scr_height
flag specifies the height in scanlines of the display device.
.PP
.I -S  squarescrsize
set both the height and width to the size given.
.PP
.I -x  file_xoff  -y  file_yoff
and
.I -X  scr_xoff  -Y  scr_yoff
will offset into the file or onto the screen by the given amounts.
The coordinate system for these offsets is first quadrant, with
the origin at the lower left corner of the image.
.PP
The
.I -1
flag causes the image to be written to the framebuffer one line at
a time, using the
.IR fb_write (3)
routine.  This is the default behavior.
The
.I -m  #lines
flag can be used to specify the number of lines to be written to the
framebuffer in rectangular blocks of scanlines, using the
.IR fb_writerect (3)
routine.
In some circumstances, this can result in significantly faster image
display, at the expense of the image being written less smoothly.
If both
.I -m
and
.I -1
are specified,
.I -1
wins.
.SH "SEE ALSO"
rt(1), fb-png(1), libfb(3), pix(5)
.SH DIAGNOSTICS
.SH AUTHOR
John R. Anderson
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
