.TH POLAR-FB 1 BRL-CAD
./"                     P O L A R - F B . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.\"  define new caret and tilde symbols
.ds ^ \v'+.15v'\s+2^\s-2\v'-.15v'
.ds ~ \v'-.1v'\s-4\(ap\s+4\v'+.1v'
.\" \*^ and \*~ insert them into text
.\" Define [nt]roff strings for Greek letters
.if t .ds ph \(*f
.if n .ds ph phi
.if t .ds pi \(*p
.if n .ds pi pi
.if t .ds rh \(*r
.if n .ds rh rho
.if t .ds th \(*h
.if n .ds th theta
.\" Define upstart and upend macros for superscripts
.\" to insert them, use \*(us and \*(ue, respectively
.if t .ds us \v'-.4m'\s-3
.if n .ds us \u
.if t .ds ue \s0\v'.4m'
.if n .ds ue \d
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1.5v
.\"
.\" The man page begins...
.\"
.SH NAME
polar-fb \- produce polar plots on a frame buffer
.SH SYNOPSIS
.B polar-fb
[ \fBoptions\fR ] [ \fBfile\fR ]
.SH DESCRIPTION
.I Polar-fb
reads data for a normalized polar function (npf)
from
.I file,
and produces the graph on a frame buffer.
If
.I file
is not specified, the standard input is read.
The input should be a sequence of numbers;
it is interpreted as pairs of polar coordinates.
The first number in each pair is interpreted as a value of \*(th,
the second as a value of \*(rh.
.PP
An npf is a function,
.\".sp
.\".ce
\*(ph\ :\ [0,\ 2\*(pi)\ \(->\ [0,\ 1],
.\".sp
that maps angles between 0 and 2\*(pi (i.e., between 0 and 360 degrees)
into the unit interval.
A typical application for an npf
is to describe some attribute of an MGED model
as a function of the direction from which the geometry is viewed.
.PP
In the absence of command-line options,
.I polar-fb
fills the default area of the frame buffer
(typically 512\(mu512 pixels)
with a background color
and displays the interior of the npf
(i.e., {(\*(th,\ \*(rh)\ |\ \*(rh\ \(<=\ \*(ph(\*(th)}).
The graph is positioned with its origin
.I O,
at the center of the frame-buffer,
oriented with \*(th\ \(eq\ 0 at the bottom,
and scaled so that the unit circle just fits in the frame buffer.
The graph consists of concentric regions colored
blue, green, yellow, orange, or red,
depending on distance from
.I O.\
Finally,
.I polar-fb
superimposes a polar grid in black.
.PP
In the description that follows of the valid options,
``\fIr\ g\ b\fR''
is a triplet of integers in {0,\ ...,\ 255}
that specifies a color in terms of
intensities for red, green, and blue, respectively.
The options and their meanings are:
.sp
.TP 8
.BI -F \ fbfile
Send the results to the frame buffer
.I fbfile.\
In the absence of the
.B -F
option, if the shell variable
.B FB_FILE
is defined, its value is used.
Otherwise, the host's default frame buffer is used.
.TP 8
.BI -N \ scr_height
Set screen (frame-buffer) height to
.I scr_height
pixels.
.TP 8
.BI -S \ scr_size
Set screen (frame-buffer) height and width to
.I scr_size
pixels.
.TP 8
.BI -W \ scr_width
Set screen (frame-buffer) width to
.I scr_width
pixels.
.TP 8
.BI -a \ u\ v
Plot only the portion of the npf between \fIu\fR and \fIv\fR degrees
(i.e., \fIu\fR\ \(<=\ \*(th\ \(<=\ \fIv\fR).
Default is \fIu\fR\ \(eq\ 0, \fIv\fR\ \(eq\ 360.
.TP 8
.BI -b \ r\ g\ b
Set the background color to
(\fIr\fR,\ \fIg\fR,\ \fIb\fR).
Default is (255,\ 255,\ 255) (i.e., white).
.TP 8
.BI -c
Clear the frame buffer to the background color.
.TP 8
.BI -e
Use empty-interior mode.
This is useful with the
.B -p
option.
.TP 8
.B -g
Do not plot the polar grid.
.TP 8
.B -h
Use high-resolution mode.
The frame buffer is 1024\(mu1024 pixels.
This has the same effect as
.B -S 1024 .
.TP 8
.BI -i \ r\ g\ b
Display the interior of the npf with constant color
(\fIr\fR,\ \fIg\fR,\ \fIb\fR).
.TP 8
.BI -l \ r\ g\ b
Display the interior of the npf in annular regions
whose colors are a linear ramp from (0,\ 0,\ 0) at
.I O,
to
(\fIr\fR,\ \fIg\fR,\ \fIb\fR)
at \*(rh\ \(eq\ 1.
.TP 8
.B -m
Merge the graph with the current contents of the frame buffer.
Given this option,
.I polar-fb
does not modify the area of the frame buffer outside the npf.
.TP 8
.B -n
Use no-warning mode.
If this option is specified,
.I polar-fb
will abort if it detects any irregularities in the input stream.
.TP 8
.BI -o \ x\ y
Translate the graph, putting
.I O
at frame-buffer location (\fIx\fR, \fIy\fR).
.TP 8
.BI -p \ r\ g\ b
Plot the perimeter of the npf in the color
(\fIr\fR,\ \fIg\fR,\ \fIb\fR).
.TP 8
.BI -q \ q
Set the angular quantum to
.IR q \ degrees.
The graph will consist of circular sectors, with the arc of each sector
subtending an angle of
.I q.\
Default is 1.
.TP 8
.B -r
Interpret the \*(th values on the input in radians.
Default is degrees.
.TP 8
.BI -s \ s
Scale the graph so that the unit radius is
.I s
pixels.
The dimensions of the background region of the graph will be
.RI 2 s \(mu2 s
pixels.
.TP 8
.BI -t \ t
Rotate (twist) the npf
.I t
degrees clockwise.
Negative values of
.I t
specify counterclockwise rotation.
Any bounds specified with the
.B -a
option are applied before the npf is rotated.
.TP 8
.BI -w
Display the interior of the npf in angular wedges
colored blue, green, yellow, orange, or red, depending on radius.
.TP 8
.BI -z \ side
Plot only one half of the graph.
.I Side
may be either of the characters `l' or `r',
which specify the left and right halves of the graph, respectively.
This functionality could be duplicated through judicious combination
of the
.BR -a " and " -t
options.
.SH SEE ALSO
brlcad(1)
.SH AUTHOR
Paul J. Tanenbaum, BRL/VLD-GSB
