#!/bin/sh

co Makefile
co dpmenuitem.h
co dpmenuitem.cc
co headerdisp.h
co headerdisp.cc
co instcmdbufdisp.h
co instcmdbufdisp.cc
co probe.h
co probe.cc
co probemain.cc
co seedefines.h
co seestreditors.h
co seestreditors.cc
co seinstdisp.h
co seinstdisp.cc
co setypedisp.h
co setypedisp.cc
co stepentdescriptor.h
co stepentdescriptor.cc
co stepenteditor.h
co stepenteditor.cc
co sclfilechooser.h
co sclfilechooser.cc

# entitystreditor.cc
# entitystreditor.h
# seeinfo.h
# seeinfo.inline.h
# seeinfodefault.h
# seeinfodefault.inline.h
