/*
 *			tcl/Cakefile
 */

#define SRCDIR	tcl
#define PRODUCTS	tclsh wish
#define	SRCSUFF	.c
#define MANSECTION	1

#define CONFIGDEFS -I''XINCDIR

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

tclsh:  tclAppInit.o LIBTCL_DEP
	CC LDFLAGS -o tclsh tclAppInit.o LIBTCL LIBES

wish: tkAppInit.o LIBTCL_DEP LIBTK_DEP
	CC LDFLAGS -o wish tkAppInit.o LIBTK LIBTCL -L''XLIBDIR -lX11 LIBES

/* This one needs tclInt.h to compile.  Ugh.

tcltest:	tclTest.o LIBTCL_DEP
	CC LDFLAGS -o tcltest tclTest.o LIBTCL LIBES

*/

#include "../Cakefile.rules"
