/*
 *			tcl/Cakefile
 */

#define SRCDIR	tcl
#define PRODUCTS	tclsh tcltest
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"

/* Eliminate the normal BRL-CAD defines */
#undef CFLAGS
/* Keep the -64 flag, etc */
#define CFLAGS TCL_DEFS  GFLAG -I''INCDIR


/* Explicit composition of each product */

everything&::	PRODUCTS

tclsh:  tclAppInit.o LIBTCL_DEP
	CC LDFLAGS -o tclsh tclAppInit.o LIBTCL LIBTCL_LIBES LIBES

tcltest: tclTest.o LIBTCL_DEP
	CC LDFLAGS -o tcltest tclTest.o LIBTCL LIBTCL_LIBES LIBES

tclAppInit.o: ../SRCDIR/tclAppInit.c
	CC CFLAGS -c ../SRCDIR/tclAppInit.c

tclTest.o: ../SRCDIR/tclTest.c
	CC CFLAGS -c ../SRCDIR/tclTest.c

#include "../Cakefile.rules"
