.TH CAD_PAREA 1 BRL-CAD
.\"                    C A D _ P A R E A . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
'\"	last edit:	85/03/05	D A Gwyn
'\"	SCCSID		@(#)parea.1	1.7
.SH NAME
cad_parea \- compute area of polygon
.SH SYNOPSIS
.B cad_parea
[
.B \-i
input
] [
.B \-o
output
]
.SH DESCRIPTION
.I cad_parea\^
reads from
.I input\^
(standard input if not given)
a series of
polygon vertex
.RI ( x\^ , y\^ )
coordinate values
and writes to
.I output\^
(standard output if not given)
the polygon's area.
Lines not beginning with a number
are silently skipped.
Vertices are assumed to be given
in counter-clockwise cyclic order.
.SH HINTS
A hole can be accommodated as
a clockwise section
connected to the periphery
by a line segment
traced in both directions.
.P
Disjoint pieces may be connected
by a line segment
traced in both directions.
.SH EXAMPLE
.RS
$ \|\fIcad_parea
.br
# \|comment
.br
1 \|0
.br
2 \|0
.br
2 \|1
.br
3 \|1
.br
3 \|2
.br
2 \|2
.br
1 \|2
.br
0 \|2
.br
0 \|1
.br
1 \|1
.br
^D\fP
.br
4
.RE
.SH "SEE ALSO"
cad_boundp(1).
.SH DIAGNOSTICS
Improperly formatted input
produces an error message
and terminates
.I cad_parea\^
with non-zero exit status.
.P
.I cad_parea\^
outputs ``0''
for the area
of a degenerate polygon.
.SH AUTHOR
Douglas A. Gwyn, BRL/VLD-VMB
