.TH CAD_BOUNDP 1V VMB
.\"                   C A D _ B O U N D P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
'\"	last edit:	85/03/05	D A Gwyn
'\"	SCCSID		@(#)boundp.1	1.9
.SH NAME
cad_boundp \- find bounding polygon of two-dimensional view
.SH SYNOPSIS
.B cad_boundp
[
.B \-i
input
] [
.B \-o
output
] [
.B \-t
tolerance
] [
.B \-v
]
.SH DESCRIPTION
.I cad_boundp\^
reads from
.I input\^
(standard input if not specified)
a series of line segment endpoint
.RI ( x\^ , y\^ )
coordinate values
describing a two-dimensional view
of the edges of a
(possibly transparent)
three-dimensional object
and writes to
.I output\^
(standard output if not specified)
the
.RI ( x\^ , y\^ )
coordinates
of vertices of the bounding polygon
in counter-clockwise order,
starting with the vertex
having the smallest
.I y\^
coordinate.
If the
.B \-v
argument is used,
instead of points
the output will consist of
line segment data
suitable for input into
another invocation of
.IR cad_boundp\^ .
.P
Input lines not beginning with a number
are silently skipped.
This feature can be used to
accommodate comments or
additional control information
in the data stream.
.P
When a
.I tolerance\^
is specified,
a point is considered to be identical
to a previously-input point
if its
.I x\^
and
.I y\^
coordinates are both within
.I tolerance\^
of the first point encountered
within a group passing the tolerance test.
Otherwise,
point coordinates must match precisely
or the algorithm will produce
erroneous results.
.SH RESTRICTIONS
.I cad_boundp\^
may output a polygon
smaller than desired
or produce a
``degenerate input''
message
if the
.I tolerance\^
is too tight
or if input is incomplete.
It may be wise to specify
double the expected
.IR tolerance\^ .
.P
Holes within the view
cannot be recognized.
.P
Silhouette thickness must everywhere exceed
.I tolerance\^
(no narrow necking-down)
or a portion of the silhouette
will be ``lost'';
in particular,
the view should not consist of
disjoint parts.
.SH EXAMPLE
.RS
$ \|\fIcad_boundp \|\-t 0.1
.br
# \|comment
.br
0 \|2 \|0 \|1
.br
3 \|2 \|3 \|1
.br
2 \|0 \|1 \|0
.br
0 \|2 \|3 \|2
.br
0 \|2 \|3 \|1
.br
0 \|1 \|3 \|2
.br
2 \|2 \|2 \|0
.br
1 \|0 \|1 \|2
.br
2 \|2 \|1 \|2
.br
0 \|1 \|3 \|1
.br
^D\fP
.br
1 \|0
.br
2 \|0
.br
2 \|1
.br
3 \|1
.br
3 \|2
.br
2 \|2
.br
1 \|2
.br
0 \|2
.br
0 \|1
.br
1 \|1\fR
.RE
.SH "SEE ALSO"
cad_parea(1).
.SH DIAGNOSTICS
Any error condition causes
.I cad_boundp\^
to terminate
with non-zero exit status
after it prints an error message
on the standard error output.
.P
An illegal argument
or improperly formatted input
produces an appropriate message.
.P
If a vertex
having only one line segment
connected to it
is found on the perimeter,
.I cad_boundp\^
produces the message
``degenerate input''.
.P
If there is too much data for
.I cad_boundp\^
to handle,
the message
``out of memory''
is produced.
.SH AUTHOR
Douglas A. Gwyn, BRL/VLD-VMB
