.TH MGED 1 BRL-CAD
.\"                         M G E D . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
mged \- multi-display interactive combinatorial solid geometry editor
.SH SYNOPSIS
.B mged
[-r] [-c] [-f] database.g [mged_command]
.SH DESCRIPTION
.I mged\^
interactively edits the specified database file
.I database.g
on any one of a number of display devices, including
any UNIX-plot device,
a Vector General 3300,
a Megatek 7250,
a Tektronix 4014 or compatable display,
a Tektronix 4109 or compatable display,
a Raster Technologies One/80,
an Evans and Sutherland Picture System 300,
a Silicon Graphics IRIS 2400 or 3030 workstation,
a Silicon Graphics IRIS 4D workstation,
or any workstation which supports the MIT X-Window System (X11).
.PP
For detailed documentation,
obtain a copy of
the guide ``\fIComputer Graphics for Target Descriptions\fR'',
BRL Technical Report ARBRL-TR-02480,
``\fIGED:  An Interactive
Solid Modeling System for Vulnerability Assessments\fR'',
or refer to the ``\fIUsers Manual for BRL-CAD Graphics Editor MGED\fR''
which is included in the full BRL-CAD manual set.
.SH HINTS
.I mged\^
database names conventionally end with
.BR .g .
.PP
SIGINT aborts the current command.
.PP
"q" or EOF exits the program.
.PP
.SH EXAMPLE
.RS
$ \|\fImged \|tank.g\fP
.RE
.SH "STARTUP"
.I mged\^
may be run in one of three modes.
(a) single-shot command.  One command is given on the command line,
after the database name.
(b) multiple commands from a file.
The input is not from a terminal, but instead from a file or
shell-script ``here document''.
No display manager is attached to.
(c)  interactive mode.
.br
The ".mgedrc" file is processed and then either a multiple window
graphical user interface (GUI) is presented or the user is prompted
for which display manager they wish to attach to, with a question
like:
.br
  attach (nu|tek|tek4109|ps|plot|sgi|X)[nu]?
.PP
The ".mgedrc" file is searched for in three places.
The first one found is used, and any others are ignored.
(a) If the environment variable MGED_RCFILE is set, it is used
as a path name for the file to be used.
(b) If the environment variable HOME is set, then HOME/.mgedrc
is used.
(c) If the file ".mgedrc" exists in the current directory, it is used.
.PP
Whether or not mged presents a multiple window GUI depends on whether
or not it is running in "classic" mode.  By default, it will create a
multiple window GUI and automatically detach from the executing
terminal so it may run as a background process.
.SH MODES
The "set" command can be used to select various operating modes for
.I mged\^.
This is most useful in conjunction with the ".mgedrc" file, to
establish per-user preferences.
.br
  set autosize=0
.br
will defeat the automatic resizing of the view when the screen is empty.
.sp
  set sgi_win_size=1024
.br
  set sgi_win_origin=200,0
.br
can be used (\fIbefore\fR attaching to the SGI display manager) to
establish a preference for the size and location of the window to be opened.
.PP
The
.I -r
option to
.I mged
opens the database in a read-only mode.
.PP
The
.I -c
option to
.I mged
will run in "classic" mode.
.PP
The
.I -f
option to
.I mged
will prevent the application from automatically detaching and running
in the background.
.SH "X11 NOTES"
When using
.I mged\^
with the X11 display manager
(or the SGI display manager on an SGI 4D running IRIX 4.0),
be certain that the shell variable DISPLAY is set to indicate the host
that you wish to have your window opened on.
Failure to set the DISPLAY variable, or setting it improperly,
can cause bemusing error messages from the X window system.
.SH "SEE ALSO"
.I
Computer Graphics for Target Descriptions
.br
brlcad(1), rt(1), comgeom-g(1), vdeck(1), librt(3).
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHORS
Keith Applin
.br
Doug Gwyn
.br
Chuck Kennedy
.br
Gary Kuehl
.br
Gary Moss
.br
Mike Muuss
.br
Chuck Stanley
.br
Bob Suckling
.br
Earl Weaver
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
