.TH ANIM_ORIENT 1 BRL/CAD
.SH NAME
anim_orient - convert between orientation formats
.SH SYNOPSIS
.B anim_orient 
.B [qyazmt][vr]
.B [qyazmt][vr]
.B < in.table 
.B > out.table
.SH DESCRIPTION
.I Anim_orient
is a filter which translates a table of orientation
information from one format to another. The method used is to convert
the input format to a matrix, then convert the matrix to the desired
output format. The input format is specified in the first argument, and
the output format is specified in the second. The orientation formats
must be one of the following: 
.B q 
(quaternion), 
.B y
(yaw,pitch, and roll), 
.B a
(azimuth, elevation, and twist), 
.B z 
(x-y-z angles), 
.B m 
(rotation matrix), or 
.B t 
(transposed matrix). These are described in greater detail below. 

In addition, the input and output formats may be modified by the 
.B r 
or
.B v
options. The 
.B r 
option specifies that angles are read or written in radians, rather
than degrees. 
.sp
The 
.B v
option specifies an alternate starting point for the orientation
transformation. By default, the object being oriented is assumed
initially to face the positive x direction, with the y-axis to the left 
and the z-axis leading upwards. All of the orientation formats define
transformations which are applied to this initial object to achieve the
desired orientation.  This is the convention for vehicles modeled
in 
.IR brlcad .
The 
.B v 
option facilitates animating the virtual camera in 
.IR brlcad .
In this case, the object is assumed to initially face the negative z
direction, with the x-axis to the right and the y-axis going up (the
default position of the virtual camera). 
See the Examples section for more information.

The input and output format codes are:
.TP
.BR q : 
Quaternions, in the order x,y,z,w. This is the default input and
output format. The output will
always be unit quaternions. For a unit quaternion, the
xyz-vector represents an axis of rotation and and w represents 
cos(omega/2), where
omega is the angle to be rotated about the given axis.
.TP
.BR z : 
x-y-z angles, in the order x, y, z. They represent a rotation
of z degrees around the z-axis, followed by y degrees around the y-axis,
followed by x degrees around the x-axis. If the code 
.B zr 
is used
then the angles will be read or written in radians
rather than degrees.
.TP
.BR y : 
yaw-pitch-roll format, in that order. They represent
a rotation of +roll degrees about the x-axis, -pitch degrees about
the y-axis, followed by +yaw degrees about the z-axis. If the code
.B yr 
is used, angles are in radians rather than degrees. 
.TP
.BR a :
azimuth, elevation, twist, in that order. They represent a rotation of
-twist degrees about the x-axis, +elevation degrees about the y-axis,
and +azimuth + 180 degrees about the z-axis. Alternatively, they can
be thought of as a 180 degree rotation about the z-axis followed by a
rotation of +twist degrees about the x-axis, -elevation degrees about
the y-axis, and +azimuth degrees about the z-axis.
.TP
.BR m : 
pre-multiplication rotation matrix. Sixteen
numbers form a 4x4 matrix, although only the nine elements in the upper
left corner are actually used. This is the format used at the interior of
the conversion routine. It is a transformation from initial orientation to 
a new orientation.
.TP
.BR t : 
Transposed matrix. A matrix which is the transpose of the 
.B m
matrix. Because these are rotation matrices, the transposed matrix is
also the inverse of the 
.B m 
matrix, and can be though of the transformation from the new orientation
back into the initial orientation space. The
.B t 
and
.B v
options together represent the "Viewrot" transformation used by 
.I mged
and 
.IR rt.
See the examples below.

.SH EXAMPLES
.sp
Normalize a table of quaternions to unit magnitude.
.sp
	anim_orient < in.table > out.table 
.sp
change xyz angles to a rotation matrix
.sp
	anim_orient z m < in.table > out.table
.sp
change azimuth,elevation, and twist to a matrix suitable for the 
.I rt
viewrot command
.sp
	anim_orient a tv < in.table > out.table
.sp
transpose matrices
.sp
	anim_orient m t < in.table > out.table
.sp
change radian xyz angles to yaw-pitch-roll in degrees
.sp
	anim_orient zr y < in.table > out.table
.sp
given quaternion being applied to an object, find the quaternion needed
to turn the virtual camera in the same direction using rt's orientation
command
.sp
	anim_orient q qv < in.table > out.table
.SH BUGS
There are built in trouble spots which occur, in ypr, xyz, or aet
formats, when the pitch, y-rotation, or elevation is an odd multiple of 90
degrees, because at this point the other two angles become
indistinguishable. The program makes the arbitrary assumption that the
roll is zero or that the x-rotation is zero, depending on the format,
and gives a warning to that effect on stderr.
.SH AUTHOR
Carl J. Nuzman
.SH COPYRIGHT
	This software is Copyright (C) 1993 by the United States Army
in all countries except the USA.  All rights reserved.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.

