/*
 *			tab/Cakefile
 */

#define SRCDIR	anim
#define PRODUCTS	anim_script chan_permute anim_orient anim_fly anim_lookat anim_keyread anim_track anim_offset anim_sort anim_hardtrack anim_turn
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define FILES	anim anim_script chan_permute anim_orient anim_fly anim_lookat anim_keyread anim_offset anim_sort anim_hardtrack anim_turn

/* Explicit composition of each product */

add_chan: add_chan.o
	CC LDFLAGS add_chan.o -o add_chan

anim_script: anim_script.o anim.o
	CC LDFLAGS anim_script.o anim.o LIBRT -lm -lmpc -o anim_script

chan_permute: chan_permute.o
	CC LDFLAGS chan_permute.o -o chan_permute

anim_orient: anim_orient.o anim.o
	CC LDFLAGS anim_orient.o anim.o -lm -o anim_orient

anim_fly: anim_fly.o
	CC LDFLAGS anim_fly.o -lm -o anim_fly

anim_lookat: anim_lookat.o anim.o
	CC LDFLAGS anim_lookat.o anim.o -lm -o anim_lookat

anim_keyread: anim_keyread.o anim.o
	CC LDFLAGS anim_keyread.o anim.o LIBES -o anim_keyread

mult_chan: mult_chan.o
	CC LDFLAGS mult_chan.o -o mult_chan

anim_track: anim_track.o cattrack.o anim.o
	CC LDFLAGS anim_track.o cattrack.o anim.o LIBRT -lm -lmpc -o anim_track

anim_offset: anim_offset.o anim.o
	CC LDFLAGS anim_offset.o anim.o -lm -o anim_offset

anim_sort: anim_sort.o
	CC LDFLAGS anim_sort.o -o anim_sort

anim_hardtrack: anim_hardtrack.o anim.o
	CC LDFLAGS anim_hardtrack.o anim.o LIBRT -lm -lmpc -o anim_hardtrack

anim_turn: anim_turn.o anim.o
	CC LDFLAGS anim_turn.o anim.o LIBRT -lm -lmpc -o anim_turn

#include "../Cakefile.rules"
