/*
 *			tab/Cakefile
 */

#define SRCDIR	anim
#define PRODUCTS	qinterp keyread convert
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define FILES	qinterp anim

/* Explicit composition of each product */

ascript: ascript.o anim.o
	CC LDFLAGS ascript.o anim.o LIBRT -lm -lmpc -o ascript

channel: channel.o
	CC LDFLAGS channel.o -o channel

convert: convert.o anim.o
	CC LDFLAGS convert.o anim.o -lm -o convert

fly: fly.o
	CC LDFLAGS fly.o -lm -o fly

lookat: lookat.o anim.o
	CC LDFLAGS lookat.o anim.o -lm -o lookat

keyread: keyread.o anim.o
	CC LDFLAGS keyread.o anim.o LIBES -o keyread

offset: offset.o anim.o
	CC LDFLAGS offset.o anim.o -lm -o offset

qinterp: qinterp.o 
	CC LDFLAGS qinterp.o LIBES -o qinterp

scriptsort: scriptsort.o
	CC LDFLAGS scriptsort.o -o scriptsort

track: track.o anim.o
	CC LDFLAGS track.o anim.o LIBRT -lm -lmpc -o track

turn: turn.o anim.o
	CC LDFLAGS turn.o anim.o LIBRT -lm -lmpc -o turn

#include "../Cakefile.rules"
