/*
 *			proc-db/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	proc-db
#define PRODUCTS	pyramid molecule clutter kurt room tube teapot \
			pipetest
#define STATIC_PRODUCTS	mol-data mol-data1 mol-data2 mol-cube \
			mol-gfa2 mol-gfa3
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* These programs are not really for system-wide installation */
#define DONT_INSTALL	1
#undef BINDIR
#define BINDIR	/tmp
#define AFTERINSTALL	rm

/* Explicit composition of each product */

tube:	tube.o 
	CC LDFLAGS  tube.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o tube

room:	room.o common.o
	CC LDFLAGS  room.o common.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o room

clutter:	clutter.o common.o mathtab.o
	CC LDFLAGS  clutter.o common.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES mathtab.o LIBES -o clutter

kurt:		kurt.o
	CC LDFLAGS  kurt.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o kurt

pyramid:	pyramid.o
	CC LDFLAGS  pyramid.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o pyramid

molecule:	molecule.o 
	CC LDFLAGS  molecule.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o molecule

teapot:		tea.o
	CC LDFLAGS tea.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o teapot

pipetest:	pipetest.o
	CC LDFLAGS pipetest.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o pipetest

/*
 *  Special rules for additions from other directories
 */
%.o&:	rt,,%,o			if exist ../rt/%.c

%9,,%,o&:	../%9/%.c [[cakeinclude.sh ../%9/%.c INCDIR ../%9]] \
					if exist ../%9/%.c
	CC CFLAGS -c ../%9/%.c

#include "../Cakefile.rules"
