/*
 *			proc-db/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	proc-db
#define PRODUCTS	pyramid molecule clutter kurt room tube teapot \
			pipetest nmgmodel brickwall wall \
			mk_bolt mk_handle mk_window mk_winfrm mk_gastank \
			mk_wire pipe
#define STATIC_PRODUCTS		\
	../SRCDIR/mol-data.dat ../SRCDIR/mol-data1.dat \
	../SRCDIR/mol-data2.dat \
	../SRCDIR/mol-cube.dat \
	../SRCDIR/mol-gfa2.dat ../SRCDIR/mol-gfa3.dat ../SRCDIR/pipe_helix.input
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* These programs are not really for system-wide installation */
#define DONT_INSTALL	1
#undef BINDIR
#define BINDIR	/tmp
#define AFTERINSTALL	rm

/* Explicit composition of each product */

pipe:	pipe.o
	CC LDFLAGS  pipe.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o pipe

tube:	tube.o 
	CC LDFLAGS  tube.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o tube

spltest:	spltest.o 
	CC LDFLAGS  spltest.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o spltest

room:	room.o common.o
	CC LDFLAGS  room.o common.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o room

clutter:	clutter.o common.o mathtab.o
	CC LDFLAGS  clutter.o common.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES mathtab.o LIBES -o clutter

kurt:		kurt.o
	CC LDFLAGS  kurt.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o kurt

pyramid:	pyramid.o
	CC LDFLAGS  pyramid.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o pyramid

molecule:	molecule.o 
	CC LDFLAGS  molecule.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o molecule

teapot:		tea.o
	CC LDFLAGS tea.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o teapot

pipetest:	pipetest.o
	CC LDFLAGS pipetest.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o pipetest

nmgmodel:	nmgmodel.o
	CC LDFLAGS nmgmodel.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o nmgmodel

brickwall:	brickwall.o
	CC LDFLAGS brickwall.o LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o brickwall

wall:	wall.o
	CC LDFLAGS wall.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o wall

mk_bolt:	mk_bolt.o
	CC LDFLAGS mk_bolt.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o mk_bolt

mk_handle:	mk_handle.o
	CC LDFLAGS mk_handle.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o mk_handle

mk_window:	mk_window.o
	CC LDFLAGS mk_window.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o mk_window

mk_winfrm:	mk_winfrm.o
	CC LDFLAGS mk_winfrm.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o mk_winfrm

mk_gastank:	mk_gastank.o
	CC LDFLAGS mk_gastank.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o mk_gastank

mk_wire:	mk_wire.o
	CC LDFLAGS mk_wire.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES -o mk_wire

/*
 *  Special rules for additions from other directories
 */
%.o&:	rt,,%,o			if exist ../rt/%.c

%9,,%,o&:	../%9/%.c HDR_DEP9	if exist ../%9/%.c
	CC CFLAGS -c ../%9/%.c

#include "../Cakefile.rules"
