/*
 *			proc-db/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	proc-db
#define PRODUCTS	pyramid molecule clutter kurt room tube teapot \
			pipetest nmgmodel brickwall wall tea_nmg \
			pipe terrain
#define STATIC_PRODUCTS		\
	../SRCDIR/mol-data.dat ../SRCDIR/mol-data1.dat \
	../SRCDIR/mol-data2.dat \
	../SRCDIR/mol-cube.dat \
	../SRCDIR/mol-gfa2.dat ../SRCDIR/mol-gfa3.dat ../SRCDIR/pipe_helix.input
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* These programs are not really for system-wide installation */
#define DONT_INSTALL	1
#undef BINDIR
#define BINDIR	/tmp
#define AFTERINSTALL	rm

/* Explicit composition of each product */

pipe:	pipe.o
	CC LDFLAGS  pipe.o LIBWDB LIBRT LIBRT_LIBES LIBES -o pipe

tube:	tube.o 
	CC LDFLAGS  tube.o LIBWDB LIBRT LIBRT_LIBES LIBES -o tube

spltest:	spltest.o 
	CC LDFLAGS  spltest.o LIBWDB LIBRT LIBRT_LIBES LIBES -o spltest

room:	room.o common.o
	CC LDFLAGS  room.o common.o LIBWDB LIBRT LIBRT_LIBES LIBES -o room

clutter:	clutter.o common.o mathtab.o
	CC LDFLAGS  clutter.o common.o LIBWDB LIBRT LIBRT_LIBES mathtab.o LIBES -o clutter

kurt:		kurt.o
	CC LDFLAGS  kurt.o LIBWDB LIBRT LIBRT_LIBES LIBES -o kurt

pyramid:	pyramid.o
	CC LDFLAGS  pyramid.o LIBWDB LIBRT LIBRT_LIBES LIBES -o pyramid

molecule:	molecule.o 
	CC LDFLAGS  molecule.o LIBWDB LIBRT LIBRT_LIBES LIBES -o molecule

teapot:		tea.o
	CC LDFLAGS tea.o LIBWDB LIBRT LIBRT_LIBES LIBES -o teapot

terrain: terrain.o
	CC LDFLAGS terrain.o LIBWDB LIBRT LIBRT_LIBES LIBES -o terrain

tea_nmg:	tea_nmg.o LIBWDB_DEP LIBRT_DEP
	CC LDFLAGS tea_nmg.o LIBWDB LIBRT LIBRT_LIBES LIBES -o tea_nmg

pipetest:	pipetest.o
	CC LDFLAGS pipetest.o LIBWDB LIBRT LIBRT_LIBES LIBES -o pipetest

nmgmodel:	nmgmodel.o
	CC LDFLAGS nmgmodel.o LIBWDB LIBRT LIBRT_LIBES LIBES -o nmgmodel

brickwall:	brickwall.o
	CC LDFLAGS brickwall.o LIBRT LIBRT_LIBES LIBES -o brickwall

wall:	wall.o
	CC LDFLAGS wall.o LIBWDB LIBRT LIBRT_LIBES LIBES -o wall

/*
 *  Special rules for additions from other directories
 */
%.o&:	rt,,%,o			if exist ../rt/%.c

%9,,%,o&:	../%9/%.c HDR_DEP9	if exist ../%9/%.c
	CC CFLAGS -c ../%9/%.c

#include "../Cakefile.rules"
