= Untitled
:doctype: article
:toc:
:toclevels: 3

== Application Development with BRL-CAD

../presentations/en/brlcad-app-devel_2.html

A suite of utilities capable of interactively displaying, editing, and interrogating geometric models is known as BRL-CAD. BRL-CAD has become a powerful constructive solid geometry (CSG) modeling package. The package includes a large collection of tools and utilities including an interactive geometry editor, ray tracing and generic framebuffer libraries, a network-distributed image-processing and signal-processing capability, and an embedded scripting language.

A particular strength of the package lies in its ability to build and analyze realistic models of complex objects using a relatively small set of "primitive shapes." Another strength of the package is the speed of its ray tracer, which is one of the fastest in existence. Finally, BRL-CAD users can accurately model objects on scales ranging from the subatomic through the galactic and get "all the details, all the time." BRL-CAD has been used for a wide variety of engineering and graphics applications. BRL-CAD is basically a collection of libraries, tools, and utilities that work together to create, raytrace, and interrogate geometry and manipulate files and data. In BRL-CAD library, Each library fits into one of three categories:


* creating and/or editing geometry,
* raytracing geometry
* image handling.






----

The application side of BRL-CAD also offers a number of tools and utilities.
rt – the main raytracer for rendering images in BRL-CAD.
nirt – a package for firing rays interactively and getting information about what the rays run into.
remrt – a network-distributed ray tracing package.
----




