.TH FBSERV 1 BRL-CAD
.\"                       F B S E R V . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
fbserv \- Frame-buffer Server
.SH SYNOPSIS
.B fbserv
[-h] [-s|S square_size] [-w|W width] [-n|N height] [-p port_number] [-F frame_buffer] [port_number] [frame_buffer]
.SH DESCRIPTION
.I fbserv
opens a framebuffer that may be used by any BRL-CAD routine accessing a framebuffer.
The
.B \-s or \-S
options specify that a square framebuffer of the specified size (in pixels) is desired. The
.B \-n or \-N
options may be used to indicated the height of the desired framebuffer.
The
.B \-w or \-W
options indicate the framebuffer width, and the
.B \-h
option indicates a 1024 X 1024 pixel framebuffer.
The
.B \-p
option supplies a port number and the
.B \-F
option indicates what framebuffer device to use.
The framebuffer device may be included on the command line without the
.B \-F
option if it is the last token on the command line. The port number may
also be specified without the
.B \-p
option. If both the
.B \-F and \-p
options are not used, the port number must be followed by the framebuffer
device on the command line. While
.I fbserv
is running, its port number may then be used in other commands
that access a framebuffer by supplying that port number with the
.B \-F
option for that command. The
.I fbserv
command may be executed by users at a shell prompt, or it may be used as
an inetd remote framebuffer server by specifying
.I fbserv
as a server program in
.B inetd.conf.
.SH EXAMPLES
.nf
.ce
fbserv 0 &
.fi
This command will start a standalone fbserv daemon. Any access of a framebuffer
specifying port 0 will result in opening a new framebuffer.
.nf
.ce
fbserv -h 0 /dev/sgil &
.fi
The above command will open a 1024 X 1024 '/dev/sgil' framebuffer and associate port number 0
with it. Any access of a framebuffer specifying port 0 will use the already opened '/dev/sgil' framebuffer.
.SH "SEE ALSO"
bw-fb(1), cat-fb(1), cell-fb(1), cmap-fb(1), gif-fb(1), pix-fb(1), pl-fb(1), polar-fb(1), rle-fb(1),
fbcmap(1), fbcmrot(1), fbclear(1), fbcbars(1), fbanin(1), fbcolor(1), fbfade(1), fbframe(1),
fbfree(1), fbgamma(1), fbgrid(1), fbhelp(1), fblabel(1), fbline(1), fbpoint(1), fbscanplot(1),
fbstretch(1), fbzoom(1).
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
