.\" Copyright (c) 1986, 1987, University of Utah
.TH RLE_PUTEOF 3 2/2/87 3
.UC 4
.SH NAME
rle_puteof \- write an end of image to an RLE file.
.SH SYNOPSIS
.B
#include <rle.h>
.sp
.B
rle_puteof( the_hdr );
.br
.B
rle_hdr * the_hdr;
.SH DESCRIPTION
Call
.I rle_puteof
to write an end of image opcode into an
.IR RLE (5)
file.
.I Rle_puteof
also frees some storage allocated by
.IR rle_putrow (3),
"flushes" the output file, and generally cleans up.
.SH SEE ALSO
.na
.IR rle_hdr (3),
.IR rle_put_setup (3),
.IR rle_putrow (3),
.IR rle_putraw (3),
.IR librle (3),
.IR RLE (5).
.ad b
.SH AUTHOR
Spencer W. Thomas
.br
University of Utah
