.\" Copyright (c) 1986, 1987, University of Utah
.TH RLE_PUTCOM 3 2/2/87 3
.UC 4
.SH NAME
.HP
rle_putcom \- set the value of a picture comment in an RLE file.
.PD 0
.LP
rle_getcom \- get a picture comment from an RLE file.
.br
rle_delcom \- delete a picture comment from an RLE file.
.PD
.SH SYNOPSIS
.B
#include <rle.h>
.sp
.B
char * rle_putcom( value, the_hdr )
.br
.B
char * value;
.br
.B
rle_hdr * the_hdr;
.sp
.B
char * rle_getcom( name, the_hdr )
.br
.B
char * name;
.br
.B
rle_hdr * the_hdr;
.sp
.B
char * rle_delcom( name, the_hdr )
.br
.B
char * name;
.br
.B
rle_hdr * the_hdr;
.SH DESCRIPTION
.I Rle_putcom
can be used to add a picture comment or change the value of a picture
comment in a
.IR rle_hdr (3)
structure.  The argument
.I value
is the string value of the comment, and is generally of the form
.IR name=value .
It may also be of the form
.IR name .
If there is another comment with the same
.IR name ,
it will be replaced with the new
.IR value ,
and the previous comment will be returned as the value of
.IR rle_putcom .

.I Rle_getcom
returns a pointer to the data portion of a picture comment from an RLE file.
The comment is assumed to be in the form
.IR name=value ;
a pointer to
.I value
is returned.  If the comment is of the form
.IR name ,
a pointer to the null character at the end of the string is returned.
If there is no comment of the above forms, a
.I NULL
pointer is returned.
The
.I the_hdr
structure contains the picture comments in question.

.I Rle_delcom
is used to delete a picture comment from a
.IR rle_hdr (3)
structure.  It is called with the
.I name
of the comment and the
.I the_hdr
structure to be modified.  The first comment in the
.I rle_hdr
structure of the form
.I name=value
or
.IR name
will be deleted.  The deleted comment will be returned as the function
value.
.SH SEE ALSO
.IR rle_addhist (3),
.IR rle_hdr (3),
.IR librle (3),
.IR RLE (5).
.SH AUTHOR
Spencer W. Thomas
.br
University of Utah
