/*
 *			vdeck/Cakefile
 */

#define SRCDIR	vdeck
#define PRODUCTS	vdeck
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	vdeck cgarbs match parsarg

#define EXTRA_CLEAN	solids regions region_ids

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

vdeck:	OBJ LIBRT_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS -o vdeck OBJ LIBRT LIBBN LIBBU LIBBU_LIBES LIBES

#include "../Cakefile.rules"
