.TH VDECK 1 VMB
'\"	last edit:	5/24/84	G S Moss
'\"	SCCSID		@(#)vdeck.1	1.5
.SH NAME
Vdeck \- Generate COM-GEOM decks from a
.I vged
file
.SH SYNOPSIS
.B vdeck
{file}.g
.SH DESCRIPTION
A list of
.I objects
to be converted are selected interactively from the table of contents.
String matching operators (wild cards) like those used to specify file
or directory names as in
.IB sh (1)
are provided for this purpose, as well as to search for names in the
table of contents.
One or more COM-GEOM decks can be output.  Each deck consists of three
files, the solid, region and region-id tables.
.sp
A menu of the commands and their usage is available by typing '?' to
the program.
.sp
.SH FILES
Output files:
.sp
.in +1.0
solids,\ regions,\ region_ids\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Default file names
.br
{pre-fix}.st,\ {pre-fix}.rt,\ {pre-fix}.id\ \ \ \ Unique file names
.in -1.0
.sp
Temporary files:
.sp
.in +1.0
/tmp/disXXXXXX
/tmp/regXXXXXX
.in -1.0
.sp
.SH "SEE ALSO"
vged(1), gedu(1), gedplot(1)
.sp
.SH AUTHORS
.in +1.0
Gary S. Moss, BRL/VLD-VMB
.br
Keith Applin, BRL/VLD-TAB
.in -1.0
