.TH MK_WINDOW 1 BRL/CAD
.SH NAME
mk_window \- creates an mged file containing windows
.SH SYNOPSIS
.B mk_window
[ options... ]
.SH DESCRIPTION
Mk_window is a program to create an mged data base containing windows.
Up to twenty-six windows of the same size may
be created.  The windows are made with rounded corners.
Mk_window uses libwdb to create an mged data base.
The windows are composed of two arb8s and four cylinders.  This
program may be run interactively or the user may specify options on
a command line.  If the user chooses to run the program interactively
he answers the questions as the program prompts him.  Below are the
options that can be used on the command line.
.SS Options
.TP "\w'-G ``n cflag gflag vsize\'\'\     |'u"
.BI \-fname.g\^
Mged file name.
.TP
.BI \-n#\^
The number of windows to be created.  This number must be less than or
equal to 26.
.TP
.BI \-h#\^
Height of window in millimeters.
.TP
.BI \-w#\^
Width of window in millimeters.
.TP
.BI \-d#\^
Depth of window in millimeters.
.TP
.BI \-r#\^
Radius of the corner in millimeters
.TP
.SH EXAMPLE
The following is an example from an interactive session.
.sp
.nf
$ mk_window

The windows are composed of 2 arb8s and 4 cylinders.
The front of the window is centered at (0,0,0) and
extends in the negative x-direction the depth of the
window.

Enter the mged file to be created (25 char max).
	window.g
Enter the number of windows to create (26 max).
	3
Enter the height, width, and depth of the window.
	200 300 20
Enter the radius of the corner
	30

mged file name:  window.g
height of window:  200.000000 mm
width of window:  300.000000 mm
depth of window:  20.000000 mm
radius of corner:  30.000000 mm
number of windows:  3

.fi
The following is the same example where all dimensions are on the
command line.
.nf

	mk_window -fwindow.g -n3 -h200 -w300 -d20 -r30

.fi
In both these examples three windows are created with
a height of 200mm, width of 300mm, a depth of 20mm,
and a radius of the corner of 30mm.  The mged file created in
each case is window.g.

.SH  SEE ALSO
mk_bolt(1), mk_handle(1), mk_winfrm(1), mk_gastank(1)

.SH AUTHOR
Susan A. Coates
