/*
 *			vas4/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	vas4
#define PRODUCTS	vas4
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	vas4 vas_io record_seq

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

vas4:	OBJ LIBFB_DEP LIBBU_DEP
	CC LDFLAGS -o vas4 OBJ LIBFB LIBFB_LIBES LIBBU LIBBU_LIBES LIBES

#include "../Cakefile.rules"
