.TH AP-PIX 1 BRL-CAD
.SH NAME
ap\(hypix \- convert Applicon files to pix files
.SH SYNOPSIS
.B ap-pix
.RB [ \-v ]
file.ap
\>\ file.pix
.SH DESCRIPTION
.I Ap-pix
converts an
.I Applicon
drum plotter image file into a
.IR pix (5)
file.
.PP
The
.I Applicon
file is assumed to consist of a number lines each 3456 bits long, the
resulting
.I pix
file thus has scanlines of 3456 pixels.
.SH "SEE ALSO"
brlcad(1), pix(5).
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
