.TH AZEL 1 BRL-CAD
.\"                         A Z E L . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.\"  define new carat and tilde symbols
.ds ^ \v'+.15v'\s+2^\s-2\v'-.15v'
.ds ~ \v'-.1v'\s-4\(ap\s+4\v'+.1v'
.\" \*^ and \*~ insert them into text
.\" Define [nt]roff strings for Greek letters
.if t .ds be \(*b
.if n .ds be beta
.if t .ds pi \(*p
.if n .ds pi pi
.if t .ds rh \(*r
.if n .ds rh rho
.if t .ds th \(*h
.if n .ds th theta
.\" Define upstart and upend macros for superscripts
.\" to insert them, use \*(us and \*(ue, respectively
.if t .ds us \v'-.4m'\s-3
.if n .ds us \u
.if t .ds ue \s0\v'.4m'
.if n .ds ue \d
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.SH NAME
azel \- rotate 3-D Cartesian data in azimuth and elevation
.SH SYNOPSIS
.BR "azel  [ " options " ] [ infile [ outfile ] ]"
.SH DESCRIPTION
.I Azel
converts between right-handed Cartesian coordinate systems,
an application-geometry system
\fIx\fR, \fIy\fR, \fIz\fR
and a viewer-embedded system
\fId\fR, \fIh\fR, \fIv\fR.
These systems differ by rotation in azimuth and elevation
about their common origin.
Input comes from
.I infile
and output goes to
.I outfile
if they are specified, otherwise
.I azel
uses stdin and stdout, respectively.
Each line of input must contain three numbers separated by
white space.
Unless the
.B -i
option (q.v.) is specified,
.I azel
interprets each triple as the
\fIx\fR, \fIy\fR, \fIz\fR
coordinates of a vector, and prints out its
\fId\fR, \fIh\fR, \fIv\fR
coordinates.
Any other text on the input line beyond the triple is copied verbatim.
.SS Options
The command-line options and their meanings are given below.
.TP 12
.BI -a " azim"
Specifies azimuthal rotation of
.I azim
degrees.
Default is 0.
.TP 12
.BI -e " elev"
Specifies elevation rotation of
.I elev
degrees.
Default is 0.
.TP 12
.BI -c " celsiz"
Specifies a cell size of
.I celsiz.
Output vectors are scalar multiplied by
.RI 1/ celsiz.
Default is 1.
Useful with the
.B -r
option to bin output data into cells.
.TP 12
.B -i
Causes
.I azel
to perform the inverse rotation.
The input is transformed from viewer to application-geometry coordinates
(i.e., from
\fId\fR, \fIh\fR, \fIv\fR
to
\fIx\fR, \fIy\fR, \fIz\fR).
Incompatible with the
.B -p
option.
.TP 12
.B -p
Causes
.I azel
to project the output vectors onto the \fIhv\fR plane.
This gives grid-plane coordinates.
Incompatible with the
.B -i
option.
.TP 12
.B -r
Causes
.I azel
to round each coordinate of the output vectors to the nearest integer.
Useful with the
.B -c
option to bin output data into cells.
.SH DEFINITIONS
The viewer coordinates are defined so that
positive \fId\fR points toward the viewer,
positive \fIh\fR (horizontal) points to the viewer's right, and
positive \fIv\fR (vertical) points up.
When \fIazim\fR\ =\ \fIelev\fR\ =\ 0,
the two coordinate systems coincide, in which case
.I azel
performs the identity transformation.
Azimuth is the angle in the \fIdh\fR plane
from positive \fIh\fR to positive \fIy\fR,
measured toward positive \fId\fR.
Elevation is the angle in the \fIdv\fR plane
from positive \fIv\fR to positive \fIz\fR,
measured toward positive \fId\fR.
In the forward direction
the azimuthal rotation is performed before the elevation,
while in the inverse direction, the elevation is undone before the azimuth.
Thus, the \fIz\fR axis is always normal to the \fIh\fR axis.
When \fIazim\fR\ =\ 90 and \fIelev\fR\ =\ 0,
\fIx\fR\ =\ -\fIh\fR,
\fIy\fR\ =\ \fId\fR, and
\fIz\fR\ =\ \fIv\fR.
When \fIazim\fR\ =\ 0 and \fIelev\fR\ =\ 90,
\fIx\fR\ =\ -\fIv\fR,
\fIy\fR\ =\ \fIh\fR, and
\fIz\fR\ =\ \fId\fR.
.SH DIAGNOSTICS
The exit status is 0 if all input was successfully transformed,
1 otherwise.
.SH AUTHOR
Paul Tanenbaum
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
