.TH BARY 1
.\"                         B A R Y . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.SH NAME
bary \- compute weighted sums of points
.SH SYNOPSIS
.BR "bary  [ -nt ] [ -s " "'x y z'" " ] [ " "file" " ] "
.SH DESCRIPTION
.I Bary
computes weighted sums of a set of sites in Euclidean 3-space,
writing them on the standard output.
The site weights are read from
.I file
if it is specified;
otherwise,
.I bary
reads from the standard input.
A line of input must be either
(1) entirely white space,
(2) white space followed by a comment (begun with the '#' character),
or (3) white-space-separated weights, one per site.

By default,
.I bary
uses the three sites (1, 0, 0), (0, 1, 0), and (0, 0, 1).
One or more occurences of the
.B -s
option cause
.I bary
to replace
the default sites with all the sites
(\fIx\fR, \fIy\fR, \fIz\fR)
.\".RI "(" "x" ", " "y" ", " "z" ")" " " "huh?"
so specified.

The
.B -n
option causes
.I bary
to normalize each tuple of weights to sum to one.
This has the effect of computing
barycentric combinations of the sites.

If any line of weights in the input stream
contains more fields than the number of sites,
.I bary
will, by default,
ignore the excess fields.
The
.B -t
option causes
.I bary
to copy all such trailing fields verbatim onto the tail of
the corresponding line of output.

.SH EXAMPLE
The command

.nf
.in +4
bary -tn -s '0 0 0' -s '1 0 0' -s '0.5 0.866 0' <<EOF
#------------------------------
# x   y   z     aux. data
#------------------------------
 1.0 2.5 3.6    58 alpha
 0.0 1.0 2.0    37 bravo
13.0 9.2 6.3    69 charlie delta
EOF
.in -4
.fi

maps the triples to points in an equilateral triangle in the \fIxy\fR-plane,
producing the following output:

.nf
.in +4
0.605634 0.439099 0    58 alpha
0.666667 0.577333 0    37 bravo
0.433333 0.191432 0    69 charlie delta
.in -4
.fi
.SH AUTHOR
Paul Tanenbaum
