.TH BW-IMP 1 BRL-CAD
./"                       B W - I M P . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
bw\(hyimp \- convert a black and white bw image file to imPRESS bitmap
.SH SYNOPSIS
.B bw-imp
.RB [ \-Dh ]
.RB [ \-s\  squaresize]
.RB [ \-w\  width]
.RB [ \-n\  height]
.RB [ \-t\  thresh]
.RB [ \-X\  page_xoff]
.RB [ \-Y\  page_yoff]
[file]
.SH DESCRIPTION
.I Bw-imp
converts an 8-bit monochrome
.IR bw (5)
format
.I file
(read from the standard input if not specified)
to
.I Imagen imPRESS
language codes
for plotting a gray-scale image on a 300dpi
.I Imagen
laser printer.
.PP
The gray level is plotted on the
.I Imagen
as a small pattern of dots,
by default using ``ordered dither'',
magnifying each input pixel into multiple output pixels.
The
.B \-D
option causes the gray levels to instead be plotted using halftones,
as in newspaper/magazine reproductions of photographs.
The
.B \-t
option turns off the dithering, and uses the supplied integer value
as a threshold value.
Input pixels with magnitude >= thresh are output as white,
otherwise they are output as black.
Each input pixel produces exactly one output pixel.
If the input file is already bi-level, such as might be produced by the
.IR haltfone (1)
program, then this is the option to be used.
.P
The
.B \-h
option specifies a 1024x1024 image rather than the default of 512x512.
Printing is done in portrait mode.
The largest image which can generally be printed on an 8.5 by 11 inch
piece of paper is 2240 by 3200 pixels,
and the default page offsets are calculated for this size.
For smaller images, such as 512 squared,
.BR \-X 750
and
.BR \-Y 1200
produce the image roughly centered on the page.
.SH CAVEATS
.I Bw-imp
will take several CPU-minutes (on a VAX 780) to convert a single
.IR file .
.SH EXAMPLES
The following invocations are fairly typical:
.RS
\fIpix-bw\| -ntsc\| image.pix\| | \|bw-imp\| | \| qpr \|\-qi300\fP \|&
.RE
.sp
.RS
\fIrle-pix\| image.rle\| | \|pix-bw\| -ntsc\| | \|bw-imp\| | \|qpr \|\-qi300\fP \|&
.RE
.sp
The X and Y options in the bw-imp command below are to approximately
center a 1024x1024 or 512x512
figure on a 8.5 by 11 inch sheet of paper.
As of release 4.0 the default margins on an output page resulting from
a bw-imp usage are smaller.  This allows a larger image to be printed
on one page.
.RS
\fIrle-pix\| image.rle\| | \|pix-bw\| -ntsc\| | \|bw-imp -X 200 -Y 800\| | \|ipr -L impress -q i300 \fP
.RE
.sp
To threshold and invert the black/white sense of a pix file, use:
.RS
\fIbwmod\| -m\| -8\| -a\| 255\| image.pix\| | \|pix-bw\| | \|bw-imp\| -t1\| |
 ttcp\| -t\| -p35 printhost \fP
.RE
.sp
To use the halftone package:
.RS
\fIpix-bw\| -ntsc\| image.pix\| | \|haftone\| | \|bw-imp\| | \| qpr \|\-qi300\fP \|&
.RE
.SH "SEE ALSO"
rle-pix(1), pix-bw(1), bw(5), pix(5)
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHORS
Geoffrey Cooper, Imagen Corporation
.br
Douglas A. Gwyn, BRL
.br
Michael John Muuss, BRL
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
