.TH BW-PS 1 BRL-CAD
.\"                        B W - P S . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
bw-ps \- convert a black and white bw file to PostScript
.SH SYNOPSIS
.B bw-ps
.RB [ \-e ]\ [ -c ]
.RB [ \-L ]\ [ -h ]
.RB [ \-s\  input_squaresize]
.RB [ \-w\  input_width]
.RB [ \-n\  input_height]
.RB [ \-S\  inches_square]
.RB [ \-W\  inches_width]
.RB [ \-N\  inches_height]
[infile.bw] \>\ outfile.ps
.SH DESCRIPTION
.I Bw-ps
will take a black and white
.IR bw (5)
format file of given dimensions and produce a Postscript file
on the standard output.
The
.I \-w
and
.I \-n
flags specify the input file width and number of scan lines in pixels.
They can both be set to the same value via
.I \-s.
The
.I \-h
flag is a shorthand for an input image size of 1024 square.
If no input size is given, defaults of 512 are assumed.
.PP
By default the output PostScript image size is 6.75 inches.
The
.I \-c
option will center it on a 8.5 x 11 inch page.
If a different output size is desired,
.I \-S
.I \-W
and
.I \-N
can be used to set the size in inches analagous to the input
parameters.
Finally,
.I \-L
selects landscape mode, i.e. rotates the output image by ninty degrees.
.PP
Encapsulated PostScript files can be generated via
.I \-e.
.SH EXAMPLES
bw-ps -c image.bw > image.ps
.sp
Produces a 6.75 inch PostScript file from an 512 x512 input image
and centers it on an 8.5 x 11 inch page.
.PP
.sp
bw-ps -e -w 1024 -n 768 image.bw > image.ps
.sp
Takes the file image.bw which has the dimensions of 1024 pixels wide
by 768 pixel high, and produces an Encapsulated Postscript version
of it.
.PP
.sp
bw-ps -L -c -W 5.2 < image.bw > image.ps
.sp
Makes a PostScript file of the (assumed 512 square) image, with
the output image 5.2 inches square, in landscape mode, centered
on an 8.5 x 11 inch page.
.SH "SEE ALSO"
brlcad(1), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
