.TH BW3-PIX 1 BRL-CAD
.SH NAME
bw3\(hypix \- merge black and white bw images into a color pix file
.SH SYNOPSIS
.B bw3-pix
redinput greeninput blueinput \>\ file.pix
.SH DESCRIPTION
.I Bw3-pix
merges (combines the colors of)
.IR bw (5)
format files into a
.IR pix (5)
file.
.I Bw3-pix
reads the specified input files
and writes stdout until all files have been exhausted.
The first file goes into the red color plane, the second green,
the third blue.
.PP
.I Bw3-pix
accepts two special filename synonyms:
.RB `` \- '',
which stands for stdin, and
.RB `` . '',
which stands for
.IR /dev/null ,
the latter of which will write black into the corresponding color plane.
.SH "SEE ALSO"
brlcad(1), pix-bw3(1), pix(5), bw(5)
.SH AUTHORS
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
