.TH BWDIFF 1 BRL-CAD
.\"                       B W D I F F . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
bwdiff \- compare two black and white files
.SH SYNOPSIS
.B bwdiff
.RB [ \- { mglen }]
.RB [ \-b ]
file1 file2
.SH DESCRIPTION
.I Bwdiff
compares two black and white
.IR bw (5)
format files in one of several ways,
and writes the results on standard out
The default method of comparison is to record the differences
as offsets from neutral, half-intensity grey (128).
The value written will be brighter than this neutral grey
by an amount proportional to the signed difference between
the pixels in
.I file1
and
.IR file2 .
That is, pixels which are brighter in
.I file1
than in
.I file2
will be brighter than the neutral grey,
while pixels which are dimmer in
.I file1
than in
.I file2
will be dimmer.
This difference is divided by two so that the results will fit in
the 0->255 output range.
.PP
The
.B \-m
flag takes the magnitude of the difference, thus no offset or
divide is necessary.  Brighter pixels indicate larger differences
in value.  Black indicates no difference in value.
.PP
The flags
.B \-g \-l \-e
and
.B \-n
are relational operations, standing for greater-than, less-than,
equal-to, and not-equal-to respectively.  Only one of these
flags may be used at a time.  In this mode the value of a
pixel in the first file is compared to the corresponding pixel
in the second, and if the relation is true, a full-white (255)
pixel is output.
This mode is useful for producing masks
showing pixels which satisfy the given condition.
The default background is black, unless the
.B \-b
option is specified, is which case the background is file1, with a
lowered intensity.
.PP
.I Bwdiff
accepts
.RB `` \- ''
as a synonym for stdin, and
.RB `` . ''
as a synonym for
.RI / dev / null .
.PP
Note that this program also produces useful results on
color
.IR pix (5)
files.
.SH EXAMPLE
Suppose you ran
.IR pixstat (1)
on a file and found the modes to be red=107, green=93, blue=70.
You could display those pixels whose colors are at these values by:
.br
.I
gencolor 107 93 70 | bwdiff \-e file.pix \- | pix-fb
.SH "SEE ALSO"
brlcad(1), pixdiff(1), bwstat(1), bw(5), pix(5).
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
