.TH BWHISTEQ 1 BRL-CAD
.SH NAME
bwhisteq \- equalize the histogram of a black and white bw file
.SH SYNOPSIS
.B bwhisteq
.RB [ \-v ]
file.bw > file.equalized
.SH DESCRIPTION
.I Bwhisteq
automatically equalizes the histogram of a black and white
.IR bw (5)
format file.
It reads the file
.I file.bw
and writes a "remapped" version of it on its standard output.
The method used is to distribute the values of the histogram, as
best as possible, in order to
produce a constant average "density",
while maintaining monotonicity.
.PP
The
.B \-v
flag will output the old and new histogram values on the terminal.
.SH "SEE ALSO"
brlcad(1), bwhist(1), bwstat(1), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
