.TH BWMOD 1 BRL-CAD
.\"                        B W M O D . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
bwmod \- arithmetically modify pixel values in black and white bw file
.SH SYNOPSIS
.B bwmod
.BR [\-c]
.RB { \-a\ add
.BR \-s\  sub
.BR \-m\  mult
.BR \-d\  div
.B \-A
.BR \-e\  exp
.BR \-r\  root}
\....
\<\ file.bw
.SH DESCRIPTION
.I Bwmod
will perform a series of arithmetic operations on each 8-bit pixel
of it's input/output stream.  This is a
.IR bw (5)
file format.
The pixel values range from 0 to 255 and are internally operated on
in floating point form (unless the
.I \-c
option has been specified) so that dynamic range, truncation, and sign,
are not a problem.  On output they are converted back to 8-bit unsigned
values clipping to 0 and 255 if necessary.  The number of pixels clipped
high and low, if any, are reported to standard error on completion.
.PP
If the
.I -c
option is specified, then intermediate results are stored as signed characters, though
The command line arguments remain in floating point
format.
This is useful when one wishes to take advantage of wrap-around
characteristics of binary mathematics.
.PP
Any number of operations can be given and they are applied in order.
The choices are:
.br
.BI \-a\  val
to add a value.
.br
.BI \-s\  val
to subtract a value.
.br
.BI \-m\  val
to multiply by a value.
.br
.BI \-d\  val
to divide by a value.
.br
.B \-A
to take to absolute value of each pixel.
.br
.BI \-e\  val
to exponentiate, i.e. raise each pixel to the power
.I val.
.br
.BI \-r\  val
to take the
.I val
root of each pixel.
.PP
All arguments can be floating point values.  Note that this command
can be applied to color
.IR pix (5)
files also,
but no distinction can be made between color planes.
.SH EXAMPLES
The command
.br
.I bwmod\ \-m\-1\ \-a255\ \<\ file.bw\ \>\ file2.bw
.br
will produce the negative of a file by first mutiplying by minus
one, and then adding 255 to shift the pixels back into the 0->255 range.
.PP
One can apply a gamma factor to a file as follows:
.br
.I bwmod\ \-d255\ \-r2.2\ \-m255\ \<\ file.bw\ \>\ file2.bw
.br
which will first normalize the pixel values, then take the 2.2 root
of each pixel, and finally scale it back to 0->255.
[Note however that applying gammas this way is not recommended since
a function call per pixel results!]
.PP
Suppose you ran bwstat on a file and found min=80, max=210, mean=100.
If you wish to expand the range of intensities, while still preserving
the mean, this can be done by:
.I bwmod\ \-s100\ \-m1.409\ \-a100\ \<\ file.bw \>\ file2.bw
.br
Where 1.409 results from (255-100)/(210-100) which is what one would use
by boost the max value (210) to full scale (255) after subtracting the
mean (100).  Subtracting and adding 100 make the multiply occur
"about that point", i.e value less than 100 will get smaller; those
above, higher.
.SH "SEE ALSO"
brlcad(1), pix(5), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
