.TH BWSCALE 1 BRL-CAD
./"                      B W S C A L E . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
bwscale \- change the size of a black and white bw file
.SH SYNOPSIS
.B bwscale
.RB [ \-r ]
.RB [ \-s\  squareinsize]
.RB [ \-w\  in_width]
.RB [ \-n\  in_height]
.RB [ \-S\  squareoutsize]
.RB [ \-W\  out_width]
.RB [ \-N\  out_height]
.RB [ \-h ]
[infile.bw] \>\ outfile.bw
.SH DESCRIPTION
.I Bwscale
will take a black and white
.IR bw (5)
format file of given dimensions and produce a larger or smaller
scaled version.
The
.I \-w
and
.I \-n
flags specify the input file width and number of scan lines in pixels.
They can both be set to the same value via
.I \-s.
Similarly, the
.I \-W
and
.I \-N
flags specify the desired output file width and number of scan lines in
pixels.  They can both be set to the same value via
.I \-S.
Defaults of 512 are assumed for any unspecified dimensions.
.PP
By default,
the algorithm used is bilinear interpolation if scaling up, and
a box filter of arbitrary size if scaling down.  For the box filter a
"square pixel" assumption is made; that is, all whole and fractional
input pixels falling into a rectangle the size of an output pixel contribute
equally according to the fraction of the output pixel area they cover.
When interpolating, the edge pixels are preserved, i.e. all of the
interpolated pixels fall inside of the edges.  This can be a bit surprising
when doubling the size of a file, for example, as only the edge pixels
will fall at exactly the location of an output pixel.
.PP
Specifying the
.B \-r
flag changes from bilinear interpolation to
nearest neighbor interpolation, i.e. it enlarges the image by
pixel replication.
.PP
The
.B \-h
flag causes the frame buffer to be
used in high resolution mode (1024x1024).
This is important for frame buffers such as the Adage which operate
differently depending on the display size.  Without this flag
the default size for the selected device will be used (usually
the entire screen).
.SH "SEE ALSO"
brlcad(1), bwcrop(1), bwrect(1), bw(5), pixscale(1)
.SH BUGS
This program cannot scale up in one dimension and down in the other
at the same time.
.br
The box filter used for scaling down results in the usual high-frequency
ripple.
.br
Optional cubic interpolation would be nice.
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
