.TH BWSHRINK 1 BRL-CAD
.\"                     B W S H R I N K . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
bwshrink \- shrink a black and white bw file
.SH SYNOPSIS
.B bwshrink
.RB [ \-s\  squareinsize]
.RB [ \-w\  in_width]
.RB [ \-n\  in_height]
.RB [ \-f\  shrink_factor]
.RB [ \-h ]
.RB [ \-u ]
[infile.bw] \>\ outfile.bw
.SH DESCRIPTION
.I Bwshrink
will take a black and white
.IR bw (5)
format file of given dimensions and produce a smaller
scaled version.
The
.I \-w
and
.I \-n
flags specify the input file width and number of scan lines in pixels.
They can both be set to the same value via
.I \-s.
Defaults of 512 are assumed for unspecified dimensions.
The integer scaling factor is set with the
.I \-f
flag.  By default, the factor is 2.
.PP
The program reads the entire image into memory,
and then scales the image down by
to 1/factor the original size in both dimensions.


By default, bwshrink uses boxcar averaging to produce the output pixels from
the input.  The
.I \-u
option causes bwshrink to use image undersampling instead.
.PP
The
.B \-h
flag causes the file to be
read in high resolution mode (1024x1024).
.PP
.SH "SEE ALSO"
brlcad(1), bwcrop(1), bwrect(1), bwscale(1), bw(5).
.SH BUGS
If the dimensions of the input image are not evenly divisible by the shrink
factor, incorrect and bizzare output is generated.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
