.TH BWTHRESH 1 BRL-CAD
.\"                     B W T H R E S H . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
bwthresh \- threshold a black-and-white bw file
.SH SYNOPSIS
.B bwthresh
val ... < file.bw
.SH DESCRIPTION
.I Bwthresh
reads from standard input a stream of black-and-white data in
.IR bw (5)
format
and thresholds it among the
.I vals,
writing the resulting
.IR bw (5)
data to standard output.
The
.I vals
must appear on the command line in strictly increasing order.
.PP
The grey scale 0..255 is divided evenly into
.IR n +1
bins,
and each pixel of input is compared to the
.I vals,
to determine which of the
.IR n +1
grey levels should be output.
.SH EXAMPLE
The command
.sp
.in +5
.I "bwthresh 37 143 < file.bw > file2.bw"
.in -5
.sp
performs the following mapping:
.sp
.in +5
if (pixel_in < 37)
.in +2
pixel_out = 0
.in -2
else if (pixel_in < 143)
.in +2
pixel_out = 128
.in -2
else
.in +2
pixel_out = 255
.SH "SEE ALSO"
bwmod(1), bwstat(1), bw(5)
.SH AUTHOR
Paul Tanenbaum
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
