.TH CV 1 BRL-CAD
.\"                           C V . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
cv \- convert binary data files between representation formats
.SH SYNOPSIS
.B cv
in_pat out_pat [[infile] outfile]
.SH DESCRIPTION
Convert a binary data file from one representation (format) to another.
The particular representation desired is expressed as a set of choices
from the pattern: [h|n][s|u] c|s|i|l|d|8|16|32|64.
For example, "hui" is host unsigned int, "nl" is network (signed) long.
The default is NETWORK format.
.P
Host specific format is the native internal number representation used
inside the computer that
.B cv
is running on.
There is great variation between vendors in the host-specific formats
that they use.
Especially for double-precision floating point,
DEC, Cray, and IBM have peculiar formats and byte orderings.
The network-independent byte orderings used within BRL-CAD is
big-endian (most significant bit first, on the left side of the word),
twos compliment.
The network-independent double-precision floating point format used
within BRL-CAD is 64-bit IEEE 754, transmitted in big-endian order.
.P
Signed or unsigned integer formats can be selected.
This has no effect on the double-precision format.
.P
"char", "short", "int", "long", and "double" provide their C language
equivalent on this processor when used in "h" host-specific mode.
"8", "16", "32", and "64" allow more precise specification of
datum sizes for "n" network-independent mode.
.P
For example, to change a file of host-specific (machine-specific) signed
shorts to a file of network-independent 32-bit integers, the input
format would be "hss", and the output format would be "n32".
.SH "SEE ALSO"
pix-bw(1), dpix-pix(1), bw-pix(1).
.br
M. J. Muuss,
''\fIWorkstations, Networking, Distributed Graphics, and Parallel Processing\fR''
in Computer Graphics Techniques:  Theory and Practice,
edited by D. F. Rogers, R. A. Earnshaw, Springer-Verlag, 1990.
.SH AUTHORS
Michael John Muuss
.br
Christopher T. Johnson
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
