.TH DBCP 1 BRL-CAD
.\"                         D B C P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
dbcp \- double buffered copy
.SH SYNOPSIS
.B dbcp
.RB [ \-v ]
\fIblocksize\fR
< infile > outfile
.SH DESCRIPTION
.I dbcp
is a program for copying data rapidly between devices.
.PP
This command is DEPRECATED.  Use 'dd' instead.
.PP
While the primary application is to move data between raw devices such as
tape and disk, it can also be used with pipes.
No special support is required from the operating system;
.I dbcp
forks into two processes which communicate over a pair of regular pipes
using a token passing scheme to
synchronize their reading and writing activities.  They continue
copying until an end of file or error is detected.
.I dbcp
reads from the standard input and copies to the standard output.
The argument
.I blocksize
specifies the number of 512 byte "blocks" to be
read or written in each record.
.PP
If the
.B \-v
flag is given,
the number of records processed is printed upon exit.
.SH EXAMPLES
$ \fBdbcp 16 < /dev/rdk1a > /dev/rmt0\fR
.br
.I dbcp
copies the filesystem on dk1a to tape
with a record size of 8K bytes (16 * 512).
This allows ``streaming'' tape drives to operate a peak speed.
.PP
$ \fBtar cf - . | dbcp 20 > /dev/rmt0\fR
.br
The
.I tar
process runs independently of the
.IR dbcp ,
which rapidly copies the data to tape
with the usual
.I tar
tape record size of 10K bytes (20 * 512).
.SH SEE ALSO
cp(1), dd(1)
.SH AUTHOR
Douglas P. Kingston III
.SH SOURCE
Davis, Polk, and Wardwell
.br
Chase Manhattan Building
.br
New York, NY
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
