.TH DPIX-PIX 1 BRL-CAD
.SH NAME
dpix-pix \- convert a double precision dpix file to a pix file
.SH SYNOPSIS
.B dpix-pix
file.dpix \>\ file.pix
.SH DESCRIPTION
Outputs a dpix file to pix (see
.IR pix (5))
format.  If the
.B \-v
option is given, a summary of plot command usage is given at the
end of the file.  Standard input is read if a file name is not supplied.
.SH "SEE ALSO"
pl-pl(1), plrot(1), pl-fb(1), libplot3(3), plot(5)
.SH AUTHORS
S. Muuss, J. D.
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
