.TH DUNNCOLOR 1 BRL-CAD
.\"                    D U N N C O L O R . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
dunncolor \- set exposure values for a Dunn Model 631 camera
.SH SYNOPSIS
.B dunncolor
.RB [ \-p ]
baseval redval greenval blueval
.SH DESCRIPTION
.I Dunncolor
sets the exposure values in the Dunn Instruments Model 631 camera
to the specified values.
If the
.I -p
flag is used, the Polaroid (8X10) exposure values are set.
Otherwise, the auxiliary camera exposure values are set.
.I baseval,
.I redval,
.I greenval,
and
.I blueval,
are values between 0 and 255 used to calculate the exposure times for
the red, green, and blue filters. The final value for each color is the
product of
.I baseval
and the value for that color
.RI ( redval ,
.I greenval,
or
.IR blueval ).
Exposure timing is based on the counting of vertical SYNC pulses.
The final exposure value indicates the number of SYNC pulses for
which the camera's monitor should be unblanked. At a 60 Hz rate,
this means an exposure time of 1 second for every 60 SYNC pulses.
.I Dunncolor
reads the old values from the camera and prints them before setting the new values.
The new values are then read from the camera and printed to verify that they have
been changed. The five values printed are the exposure values for base, red,
green, blue and black/white.
.SH EXAMPLES
35mm Kodachrome 64 at f/4, shaded images
.RS
\fIdunncolor 2 80 16 16\fR
.RE
35mm Kodachrome 64 at f/4, single-pixel wireframes, hires
.RS
\fIdunncolor 14 70 16 18\fR
.RE
16mm Video News Film 7250, f/8
.RS
\fIdunncolor 1 56 14 14\fR
.RE
Typically, red is 4X green and blue.
.SH DIAGNOSTICS
Diagnostics are intended to be self-explanatory.
.SH FILES
/dev/camera
.SH "SEE ALSO"
brlcad(1), dunnsnap(1)
.SH AUTHOR
Don Merritt
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
