.TH DUNNCOLOR 1 BRL-CAD
.\"                    D U N N C O L O R . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
dunncolor \- set exposure values for a Dunn Model 631 camera
.SH SYNOPSIS
.B dunncolor
.RB [ \-p ]
baseval redval greenval blueval
.SH DESCRIPTION
.I Dunncolor
sets the exposure values in the Dunn Instruments Model 631 camera
to the specified values.
If the
.I -p
flag is used, the Polaroid (8X10) exposure values are set.
Otherwise, the auxiliary camera exposure values are set.
.I baseval,
.I redval,
.I greenval,
and
.I blueval,
are values between 0 and 255 used to calculate the exposure times for
the red, green, and blue filters. The final value for each color is the
product of
.I baseval
and the value for that color
.RI ( redval ,
.I greenval,
or
.IR blueval ).
Exposure timing is based on the counting of vertical SYNC pulses.
The final exposure value indicates the number of SYNC pulses for
which the camera's monitor should be unblanked. At a 60 Hz rate,
this means an exposure time of 1 second for every 60 SYNC pulses.
.I Dunncolor
reads the old values from the camera and prints them before setting the new values.
The new values are then read from the camera and printed to verify that they have
been changed. The five values printed are the exposure values for base, red,
green, blue and black/white.
.SH EXAMPLES
35mm Kodachrome 64 at f/4, shaded images
.RS
\fIdunncolor 2 80 16 16\fR
.RE
35mm Kodachrome 64 at f/4, single-pixel wireframes, hires
.RS
\fIdunncolor 14 70 16 18\fR
.RE
16mm Video News Film 7250, f/8
.RS
\fIdunncolor 1 56 14 14\fR
.RE
Typically, red is 4X green and blue.
.SH DIAGNOSTICS
Diagnostics are intended to be self-explanatory.
.SH FILES
/dev/camera
.SH "SEE ALSO"
brlcad(1), dunnsnap(1)
.SH AUTHOR
Don Merritt
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
