.TH DUNNSNAP 1 BRL-CAD
.\"                     D U N N S N A P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
dunnsnap \- expose film in a Dunn Model 631 camera
.SH SYNOPSIS
.B dunnsnap
.RB [ \-F\  framebuffer]
.RB [ \-{sS}\  squarescrsize]
.RB [ \-{wW}\  scr_width]
.RB [ \-{nN}\  scr_height]
.RB [ \-h ]
[num_frames]
.SH DESCRIPTION
.I Dunnsnap
checks the status of the Dunn Instruments Model 631 camera and
then attempts to take
.I num_frames
exposures.  If
.I num_frames
is not supplied, the number of frames exposed defaults to one.
Status of the camera is checked before every exposure.
Limits on
.I num_frames
include your film budget and the mean time between
failures of your computer, framebuffer and camera.
.PP
By default, the
.I dunnsnap
command operates independently of any framebuffer.
The
.B \-F
flag causes the named framebuffer to be opened before exposure,
and closed afterwards.
This is intended for use with display systems like the SGI 4-D,
which always run a window mamager.
The particular framebuffer options used could, for example,
cause the image to blanket the whole screen, or
change the video output to some other frequency.
The behavior of the framebuffer options are specific to the
type of device being used.
.PP
The
.BI \-w\  scr_width
and
.BI \-W\  scr_width
flags specifies the width of each scanline for the display device,
in pixels.
.PP
The
.BI \-n\  scr_height
and
.BI \-N\  scr_height
flags specifies the height of each scanline for the display device.
.PP
.BI \-s\  squarescrsize
and
.BI \-S\  squarescrsize
set both the height and width to the size given.
.PP
The
.B \-h
flag causes the frame buffer to be
used in high resolution mode (1024x1024).
This is important for frame buffers such as the Adage which operate
differently depending on the display size.  Without this flag
the default size for the selected device will be used (usually
the entire screen).
.PP
The Dunn camera has been successfully operated while attached to
an Adage (Ikonas) RDS-3000 frambuffer in both low-res (512\u2\d 60 Hz)
and high-res (1024\u2\d 30 Hz) modes.
The
.PP
The Dunn camera has also been successfully operated while attached to
an SGI 4-D with a 4-wire RS-343 connection when the video is operated
at 30 Hz.
The picture should be loaded into /dev/sgi5 (Full screen, Shared memory),
and then exposed with:
.sp .5
.ti +5
dunnsnap -F /dev/sgi13 1
.sp .5
Where /dev/sgi13 represents 30 Hz, Full Screen, and Shared memory bits.
This keeps the main SGI display watchable while the images are loaded.
.SH DIAGNOSTICS
Diagnostics are intended to be self-explanatory.
.SH FILES
/dev/camera
.SH "SEE ALSO"
brlcad(1), dunncolor(1)
.SH AUTHORS
Don Merritt
.br
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
