.TH HD 1 "18 February 1989"
.\"                           H D . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
hd \- Hexadecimal and ASCII dump
.SH SYNOPSIS
.B hd
.I
[
.I \-o offset
]
[
.I file .\|.\|.
]
.SH DESCRIPTION
.I Hd
reads each
.I file
in sequence and
produces a dump on the standard output
in hexadecimal and ASCII.  If no files are specified on the command
line,
.I hd
checks to to be sure the standard input is not comming from a terminal
before dumping from the standard input.
.LP
Input is
dumped 16 bytes at a time.  The program displays the offset
from the begining of the file/input
in hexadecimal, followed by
the hexadecimal representations for the
next 16
bytes of data, and their ASCII character representations.  Non-printing
characters are displayed as a period (".") in the ASCII section.  Vertical
bars delimit the ASCII section.
.LP
If multiple files are specified on the command line, each file's name is
printed before its dump.
.LP
.SH OPTIONS
.TP
.B \-o offset
start printing at byte position
.I offset
instead of at the begining of the data.
.I Offset
is rounded down to a multiple of 16.
.SH SEE ALSO
od

