.TH IMGDIMS 1
.\"                      I M G D I M S . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.SH NAME
imgdims \- guess the width and height of an image file
.SH SYNOPSIS
.B imgdims
.RB [ -ns ]
.RB [ \-#\  bytes_per_pixel]
file_name
.br
.B imgdims
.RB [ \-#\  bytes_per_pixel]
num_bytes

.SH DESCRIPTION
.I Imgdims
uses the autosizing capability of
.IR libbn "(5)"
to guess the dimensions (in pixels)
of an image.
The image size may be expressed either implicitly,
by specifying the name of the file,
or explicitly,
by specifying a number of bytes.

The
.B -n
option
specifies that
the dimensions should be extracted directly from
.IR file_name ,
in the form of any of the standard BRL-CAD command-line options.
Given the
.B -s
option,
.I imgdims
ignores any dimensions encoded in
.I file_name
and uses the size of the file in bytes
to compute the number of pixels in the image
and then guess the image's width and height.
The
.B -#
option
specifies the size of each pixel (in bytes).

If
.I file_name
is specified with neither of the
.BR -s " and " -n
options,
.I imgdims
tries to extract the dimensions from
.I file_name,
and if that fails
it computes the image size and guesses the width and height.
If the
.B -#
option is not specified,
.I imgdims
determines the pixel size based on the extension on
.I file_name.
If, additionally,
.I num_bytes
was specified or
.I file_name
contains none of the recognized extensions,
.I imgdims
assumes that there are 3-byte-wide pixels.

.SH SEE ALSO
.IR libbn "(3)"

.SH AUTHOR
Paul Tanenbaum
