.TH LOOP 1 BRL-CAD
.\"                         L O O P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
loop \- generate numerical indices for shell loops, etc
.SH SYNOPSIS
.B loop
start finish [increment]
.SH DESCRIPTION
.I Loop\^
generates a sequence of numbers between
.I start
and
.I finish
inclusive, one per line, on stdout.
This is mostly useful for driving loops when writing Shell programs
.IR sh (1).
The default increment is +1 when start<finish, and -1 when start>finish.
An optional
.I increment
may be specified.
If
.I increment
is zero, then the
.I start
value will be generated continuously.
.P
Both floating point and integer arguments can be used.  On
integer arguments, if leading zeros are specified, they will
be preserver on output.  This is useful for generating sequences
of file names which are numbered with leading zeros.
.SH EXAMPLE
\fI
.nf
for i in `loop 10 30 5`
do
  echo $i
done
.fi
\fP
Will display the values 10, 15, 20, 25, and 30.
.P
\fI
.nf
for i in `loop 008 005`
do
  echo $i
done
.fi
\fP
Will display the values 008, 007, 006, 005.
.P
\fI
.nf
for i in `loop 0.1 2.9 0.5`
do
  echo $i
done
.fi
\fP
Will display the values 0.1, 0.6, 1.1, 1.6, 2.1, 2.6.
.SH BUGS
This program just scratches the surface.
The shells could benefit from a greater ability to perform math.
Limitless opportunities for extensions exist, but
this simple version is adequate for most shell scripts
dealing with sequences of images, etc.
.SH AUTHORS
John Grosh
.br
Phillip Dykstra
.br
Douglas P. Kingston III
.br
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
