.TH MAC-PIX 1 BRL-CAD
.\"                      M A C - P I X . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
mac\(hypix \- convert Apple MacPaint bitmap into pix(5) or bw(5) raster image
.SH SYNOPSIS
.B mac-pix
.RB [ \-clb ]
.RB [ \-s\  squareMacSize]
.RB [ \-w\  Mac_width]
.RB [ \-n\  Mac_height]
.RB [ \-x\  Mac_xoff]
.RB [ \-y\  Mac_yoff]
.RB [ \-X\  output_xoff]
.RB [ \-Y\  output_yoff]
.RB [ \-S\  squareOutputSize]
.RB [ \-W\  output_width]
.RB [ \-N\  output_height]
.RB [ \-C\  r/g/b]
[file.mac]
.SH DESCRIPTION
.I Mac-pix
reads an Apple MacIntosh MacPaint bitmap file and generates a
.IR pix (5)
or
.IR bw (5)
raster image file.
While the MacPaint file is 720x576 pixels, it is possible to specify
an alternate size input file with the
.B \-s
.B \-w
and
.B \-n
flags;  the usefulness of this is unknown.
By default, the output
.IR pix (5)
file is 1024x1024 pixels, with the input image located in the lower
left corner of the output (nearest the origin).  The default color for
an "on" pixel is white (R=G=B=255); alternatively, the
.B \-C r/g/b
flag can be used to specify intensities for each of the colors, in
the range of [0..255].
The
.B \-b
flag will output a
.IR bw (5)
black and white file instead.
By specifying the
.B \-c
flag, the input image is centered in the middle of the output image.
By specifying the
.B \-l
flag, the default output size is changed to 512x512.
Alternatively, the
.B \-S
flag can be used to specify the square output size, or
.B \-W
and
.B \-N
flags can be used to specify the otuput width and height.
If no input file is specified, standard input is read instead.
.SH "EXAMPLES"
Especially pleasing displays of MacPaint documents can be made by using
.IR pixmerge (1)
to combine them with the output of
.IR pixbackgnd (1):
.br
.ft I
pixbackgnd -h 160 200 > bg.pix
.br
mac-pix -c file.mac | pixmerge \(em bg.pix | pix-fb
.ft R
.SH "SEE ALSO"
brlcad(1), pixmerge(1), pix(5), bw(5).
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
