.TH MAC-PIX 1 BRL-CAD
.\"                      M A C - P I X . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
mac\(hypix \- convert Apple MacPaint bitmap into pix(5) or bw(5) raster image
.SH SYNOPSIS
.B mac-pix
.RB [ \-clb ]
.RB [ \-s\  squareMacSize]
.RB [ \-w\  Mac_width]
.RB [ \-n\  Mac_height]
.RB [ \-x\  Mac_xoff]
.RB [ \-y\  Mac_yoff]
.RB [ \-X\  output_xoff]
.RB [ \-Y\  output_yoff]
.RB [ \-S\  squareOutputSize]
.RB [ \-W\  output_width]
.RB [ \-N\  output_height]
.RB [ \-C\  r/g/b]
[file.mac]
.SH DESCRIPTION
.I Mac-pix
reads an Apple MacIntosh MacPaint bitmap file and generates a
.IR pix (5)
or
.IR bw (5)
raster image file.
While the MacPaint file is 720x576 pixels, it is possible to specify
an alternate size input file with the
.B \-s
.B \-w
and
.B \-n
flags;  the usefulness of this is unknown.
By default, the output
.IR pix (5)
file is 1024x1024 pixels, with the input image located in the lower
left corner of the output (nearest the origin).  The default color for
an "on" pixel is white (R=G=B=255); alternatively, the
.B \-C r/g/b
flag can be used to specify intensities for each of the colors, in
the range of [0..255].
The
.B \-b
flag will output a
.IR bw (5)
black and white file instead.
By specifying the
.B \-c
flag, the input image is centered in the middle of the output image.
By specifying the
.B \-l
flag, the default output size is changed to 512x512.
Alternatively, the
.B \-S
flag can be used to specify the square output size, or
.B \-W
and
.B \-N
flags can be used to specify the otuput width and height.
If no input file is specified, standard input is read instead.
.SH "EXAMPLES"
Especially pleasing displays of MacPaint documents can be made by using
.IR pixmerge (1)
to combine them with the output of
.IR pixbackgnd (1):
.br
.ft I
pixbackgnd -h 160 200 > bg.pix
.br
mac-pix -c file.mac | pixmerge \(em bg.pix | pix-fb
.ft R
.SH "SEE ALSO"
brlcad(1), pixmerge(1), pix(5), bw(5).
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
