.TH ORLE-PIX 1 BRL-CAD
.\"                     O R L E - P I X . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
orle\(hypix \- convert old run-length encoded image to RGB pixel format
.SH SYNOPSIS
.B orle-pix
.RB [ \-dv ]
.RB [ \-b
{
.B rgbwBG
}] [file.rle]
.SH DESCRIPTION
.I orle-fb\^
decodes an old University of Utah standard (Edition-2)
Run-Length Encoded (RLE) format file
(saved with
.IR fb-orle\^ (1),
.IR pix-orle (1),
or a similar program),
converts it into
.IR pix\^ (5)
format, and writes it to standard out.
If
.I file.rle\^
is not specified, standard input is read.
.I orle-pix\^
determines the type and size of the saved file (color or B&W)
and acts accordingly.
If a non-linear colormap is stored in the RLE file,
is is applied to the pixels as they are output.
.TP
.B \-d
Debug option, provides verbose description of file structure and
processes called, written on standard error.
.TP
.B \-v
Provides a verbose description of the parameters of the saved image
on standard error.
.TP
.BI \-b x\^
The background of the image is
normally set to the value recorded in the RLE file.
This option permits
the user to specify an alternate background color from a limited
set of colors.
The character
.I x
can be any of
.B r
(red),
.B g
(green),
.B b
(blue),
.B w
(white),
.B B
(black), or
.B G
(18% grey).
.TP
.I file.rle\^
Name of file to decode, in old RLE format.
.SH EXAMPLE
.RS
\fI\|orle-pix \|tank.rle \|> tank.pix\fR
.RE
.SH "SEE ALSO"
brlcad(1), fb-orle(1), fb-rle(1), pix-fb(1), rle-pix(1), pix(5).
.SH AUTHOR
Gary S. Moss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
