.TH ORLE-PIX 1 BRL-CAD
.\"                     O R L E - P I X . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
orle\(hypix \- convert old run-length encoded image to RGB pixel format
.SH SYNOPSIS
.B orle-pix
.RB [ \-dv ]
.RB [ \-b
{
.B rgbwBG
}] [file.rle]
.SH DESCRIPTION
.I orle-fb\^
decodes an old University of Utah standard (Edition-2)
Run-Length Encoded (RLE) format file
(saved with
.IR fb-orle\^ (1),
.IR pix-orle (1),
or a similar program),
converts it into
.IR pix\^ (5)
format, and writes it to standard out.
If
.I file.rle\^
is not specified, standard input is read.
.I orle-pix\^
determines the type and size of the saved file (color or B&W)
and acts accordingly.
If a non-linear colormap is stored in the RLE file,
is is applied to the pixels as they are output.
.TP
.B \-d
Debug option, provides verbose description of file structure and
processes called, written on standard error.
.TP
.B \-v
Provides a verbose description of the parameters of the saved image
on standard error.
.TP
.BI \-b x\^
The background of the image is
normally set to the value recorded in the RLE file.
This option permits
the user to specify an alternate background color from a limited
set of colors.
The character
.I x
can be any of
.B r
(red),
.B g
(green),
.B b
(blue),
.B w
(white),
.B B
(black), or
.B G
(18% grey).
.TP
.I file.rle\^
Name of file to decode, in old RLE format.
.SH EXAMPLE
.RS
\fI\|orle-pix \|tank.rle \|> tank.pix\fR
.RE
.SH "SEE ALSO"
brlcad(1), fb-orle(1), fb-rle(1), pix-fb(1), rle-pix(1), pix(5).
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
