.TH PIX-PNG 1 BRL-CAD
.\"                      P I X - P N G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pix-png	\- convert a BRL-CAD PIX format image to a PNG format image
.SH SYNOPSIS
.B pix-png
.RB [ \-a ]
.RB [ \-g gamma ]
.RB [ \-s squaresize ]
.RB [ \-w file_width ]
.RB [ \-n file_height ]
.RB [ \-o PNG_file ]
 [PIX_file]
.RB [ > PNG_file ]
.SH DESCRIPTION
.I pix-png
converts a
.I BRL PIX(5)
format file to a
.I PNG
(Portable Network Graphics) format file on the standard output. The
PNG file created will be an RGB file with a bit-depth of 8 and a file
gamma of 1.0.
.LP
PIX image files do not contain information about their size.  The size
of the input PIX image file must be specified if the dimensions are
not the default 512x512 size.
.SH OPTIONS
.TP
.B \-a
autosize the input file to determine file image height and width
.TP
.B \-g gamma
sets the specified gamma correction value into the created PNG file.
A value of 0.6 is a close approximation of PC display monitors.  A
negative gamma value disables writing a gAMA chunk out entirely (and
is the default).
.TP
.B \-s squaresize
sets both the width and the height for the input to be
.I squaresize
.TP
.B \-w file_width
tells
.I pix-png
that the input is
.I file_width
pixels wide
.TP
.B \-n file_height
tells
.I pix-png
that the input is
.I file_height
scanlines tall
.TP
.B \-o PNG_file
tells
.I pix-png
to write image data to the specified
.I PNG_file
output file.  The
.I pix-png
command will not write out binary image data directly to a terminal
device as a safeguard.
.SH "SEE ALSO"
brlcad(1), png-pix(1), pix-fb(1), pix(5).
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
