.TH PIX-BW3 1 BRL-CAD
.SH NAME
pix\(hybw3 \- split up the color planes of a color pix file
.SH SYNOPSIS
.B pix-bw3
redout greenout blueout \<\ file.pix
.SH DESCRIPTION
.I Pix-bw3
reads a color
.IR pix (5)
format file
and outputs the red, green, and blue color planes into the given
files.  These files will then be in
.IR bw (5)
format.
.SH "SEE ALSO"
brlcad(1), bw3-pix(1), pix(5), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
