.TH PIX-SUN 1 BRL-CAD
.\"                      P I X - S U N . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pix\(hysun	\- convert a BRL PIX(5) format image to a Sun Rasterfile format
.SH SYNOPSIS
.B pix-sun
.RB [ \-d ]
.RB [ \-s\  squaresize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
< BRLpixfile > rasterfile
.SH DESCRIPTION
.Ipix\(hysun
converts the
.I BRL PIX(5)
format file on the standard input to a
.I Sun Rasterfile
format file on the standard output.  The rasterfile produced is a
"standard" (as opposed to "byte encoded") image, with
8 bits per pixel, with a pallete of 256 colors.
.SH OPTIONS
.TP
.B \-d
use a dither map
.TP
.B \-n file_height
tells
.I pix\(hysun
that the input is
.I file_height
scanlines tall
.TP
.B \-s squaresize
sets both the width and the height for the input to be
.I squaresize
.TP
.B \-w file_width
tells
.I pix\(hysun
that the input is
.I file_width
pixels wide
