.TH PIX-ORLE 1 BRL-CAD
.\"                     P I X - O R L E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pix\(hyorle \- convert a pix format RGB file into old run-length encoded form
.SH SYNOPSIS
.B pix-orle
.RB [ \-hdv ]
.RB [ \-s\  squarefilesize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
.RB [file.pix]
.RB [file.rle]
.SH DESCRIPTION
.I pix-orle\^
saves a
.IR pix (5)
format image in a
Run-Length Encoded (RLE) form,
using the old University of Utah standard (Edition-2) format.
This program is provided for compatability with the old RLE image
tools, and generally should not be used for saving new images,
except where compatability with the old tools is a factor.
The equivalent new tool is
.IR pix-rle(1) .
.PP
If
.I file.pix\^
is not specified, the
.IR pix (5)
file is read from standard in.
If
.I file.rle\^
is not specified, the encoded file is written to standard out.
.I pix-orle\^
attempts to compress flat-colored areas
as much as possible.
This means that it is generally reasonable to save an entire image,
since in RLE format it will not take up much more file space than
extracting and saving only the
interesting portion of the image.
.TP
.BI \-w\  file_width
Specify the width (in pixels) of the scanlines in the input file.
The default is 512.
.TP
.BI \-n\  file_height
Specify the number of scanlines of input to be encoded.
The default is 512.
.TP
.BI \-s\  squarefilesize
Specify both the number of pixels per scanline and the number of
scanlines in the file to process.
.TP
.B \-h
``hires'' flag.
Set both the height and width of the input to 1024.
The default is 512x512.
.TP
.B \-v
Verbose mode.
The program will provide voluminous status information
on standard error as it proceeds through encoding the image.
.TP
.B \-d
Debug mode.
.SH EXAMPLE
.RS
.ft I
pix-orle \|\<plane.pix \|plane.rle
.br
pix-orle \|\-h \|car.pix \|car.rle
.br
pixfilter -f lo <truck.pix | pix-orle > truck-filt.rle
.ft R
.RE
.SH "SEE ALSO"
brlcad(1), rle-pix(1), pix-fb(1), pix-rle(1), fb-pix(1),
librle(3), liborle(3).
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
