.TH PIX-ALIAS 1 BRL-CAD
.\"                    P I X - A L I A S . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pix\(hyalias \- convert an image from pix format to Alias(tm) pix format
.SH SYNOPSIS
.B pix-alias
.RB [ \-s\  squaresize ]
.RB [ \-w\  file_width ]
.RB [ \-n file_height ]
< BRLpixfile > ALIASpixfile
.SH DESCRIPTION
.I pix\(hyalias
converts the
.I brl pix(5)
format file on the standard input to an
.I Alias pix
format file on the standard output.
.SH OPTIONS
.TP
.BI \-n\  file_height
tells
.I pix\(hyalias
that the input is
.I file_height
scanlines tall
.TP
.BI \-s\  squaresize
sets both the width and the height for the input to be
.I squaresize
.TP
.BI \-w\  file_width
tells
.I pix\(hyalias
that the input is
.I file_width
pixels wide


