.TH PIX-BW 1 BRL-CAD
.\"                       P I X - B W . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pix\(hybw \- combine pix color planes into a bw black and white image
.SH SYNOPSIS
.B pix-bw
.RB [ \-ntsc ]
.RB [ \-crt ]
.RB [ \-R [num]]
.RB [ \-G [num]]
.RB [ \-B [num]]
[in.pix]
\>\ out.bw
.SH DESCRIPTION
.I Pix-bw
will combine or select the color planes of a
.IR pix (5)
format
file from it's standard input
and produce a black and white
.IR bw (5)
file on it's standard output.
By default all three colors are weighted equally.  The
.B \-ntsc
uses weighting based on the NTSC primaries and the D6500
alignment white.  The
.B \-crt
flag applies weights for "typical" CRT phosphor chromaticities
and the D6500 white.
.PP
Individual color plane(s) can be selected via the
.B \-R\ \-G
and
.B \-B
flags.
If one or more of these flags is followed by a value,
the value will be treated as a weight
to be applied to that color
This value is implicitly 1.0 divided by
the number of colors selected for the flags which are not followed
by a value.
.SH EXAMPLES
.I pix-bw\ \-R\ \-B\ \<\ file.pix\ \>\ file.bw
.br
will equally blend the red and blue color planes.
.PP
.I pix-bw\ \-R0.30\ \-G0.59\ \-B0.11\ \<\ file.pix\ \>\ file.bw
.br
has the same effect as the
.B \-ntsc
flag.
.br
[The
.B \-crt
weights are: 0.26, 0.66, 0.08]
.SH "SEE ALSO"
brlcad(1), pix-bw3(1), bw-pix(1), pix(5), bw(5).
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
