.TH PIXBLEND 1 BRL-CAD
.\"                     P I X B L E N D . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pixblend \-
blend two pix(5) or bw(5) images
.SH SYNOPSIS
.B pixblend
.RB [ \-{r|i}\ value ]
.RB [ -s\ seedval ]
.RB [ -S ]
file1.pix file2.pix > out.pix
.SH DESCRIPTION
.I pixblend
Given two streams of data, typically
.IR pix (5)
or
.IR bw (5)
images,
generate a "blended" output stream of the same size.
This routine operates on a pixel-by-pixel basis, and thus
is independent of the resolution of the image.
The type of blending performed
is determined by the following options:
.SH OPTIONS
.TP
.BI \-r " VALUE"
This specifies random blending; for each pixel of the output stream,
a number will be chosen uniformly from the interval [0, 1). If this
number exceeds VALUE,
then the pixel from the first image will be output; otherwise, the pixel
from the second image will be output.  Note that if VALUE is 0, then
the output will equal the first image; if VALUE is 1, then the output
will equal the second image.
.PP
.TP
.BI \-i " VALUE"
This specifies linear interpolation; for each pixel of the output
stream, the interpolated pixel
((1.0 - VALUE) * pixel1 + VALUE * pixel2)
will be output (where
pixel1 and pixel2 are the corresponding pixels from file1 and file2,
respectively.)  Note that if VALUE is 0, then the output will equal the
first image; if VALUE is 1, then the output will equal the second
image.
.PP
.TP
.BI \-s " SEEDVAL"
By default,
.I pixblend
uses the value 0 as the random number seed.
With the \-s option the user may set the random number seed to SEEDVAL.
.PP
.TP
.BI \-S
Instructs
.I pixblend
to use bits from the clock as a random number seed.
.PP
.TP
.BI \-g " GVALUE"
Tells
.I pixblend
to "glitterize" the image; if the random draw for a pixel is below
GVALUE, then the pixel output is white; otherwise, the pixel used is
determined by the ratio set with the \-r option (see above.)
.PP
.ft R
.SH EXAMPLES
.ft I
      pixblend -i .25 source.pix destination.pix > out.pix
.ft I
      pixblend -r .75 source.pix destination.pix > out.pix
.ft I
      pixblend -r .5 -s source.pix destination.pix > out.pix
.ft I
      pixblend -r .5 -s 23 source.pix destination.pix > out.pix
.SH "SEE ALSO"
brlcad(1), gencolor(1), pix(5), bw(5)
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
