.TH PIXBLEND 1 BRL-CAD
./"                     P I X B L E N D . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
pixblend \-
blend two pix(5) or bw(5) images
.SH SYNOPSIS
.B pixblend
.RB [ \-{r|i}\ value ]
.RB [ -s\ seedval ]
.RB [ -S ]
file1.pix file2.pix > out.pix
.SH DESCRIPTION
.I pixblend
Given two streams of data, typically
.IR pix (5)
or
.IR bw (5)
images,
generate a "blended" output stream of the same size.
This routine operates on a pixel-by-pixel basis, and thus
is independent of the resolution of the image.
The type of blending performed
is determined by the following options:
.SH OPTIONS
.TP
.BI \-r " VALUE"
This specifies random blending; for each pixel of the output stream,
a number will be chosen uniformly from the interval [0, 1). If this
number exceeds VALUE,
then the pixel from the first image will be output; otherwise, the pixel
from the second image will be output.  Note that if VALUE is 0, then
the output will equal the first image; if VALUE is 1, then the output
will equal the second image.
.PP
.TP
.BI \-i " VALUE"
This specifies linear interpolation; for each pixel of the output
stream, the interpolated pixel
((1.0 - VALUE) * pixel1 + VALUE * pixel2)
will be output (where
pixel1 and pixel2 are the corresponding pixels from file1 and file2,
respectively.)  Note that if VALUE is 0, then the output will equal the
first image; if VALUE is 1, then the output will equal the second
image.
.PP
.TP
.BI \-s " SEEDVAL"
By default,
.I pixblend
uses the value 0 as the random number seed.
With the \-s option the user may set the random number seed to SEEDVAL.
.PP
.TP
.BI \-S
Instructs
.I pixblend
to use bits from the clock as a random number seed.
.PP
.TP
.BI \-g " GVALUE"
Tells
.I pixblend
to "glitterize" the image; if the random draw for a pixel is below
GVALUE, then the pixel output is white; otherwise, the pixel used is
determined by the ratio set with the \-r option (see above.)
.PP
.ft R
.SH EXAMPLES
.ft I
      pixblend -i .25 source.pix destination.pix > out.pix
.ft I
      pixblend -r .75 source.pix destination.pix > out.pix
.ft I
      pixblend -r .5 -s source.pix destination.pix > out.pix
.ft I
      pixblend -r .5 -s 23 source.pix destination.pix > out.pix
.SH "SEE ALSO"
brlcad(1), gencolor(1), pix(5), bw(5)
.SH AUTHORS
Paul Randal Stay
.br
Glenn Durfee
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 247
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
