.TH PIXCUT 1 BRL-CAD
.\"                       P I X C U T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pixcut \- extract a pix file from another pix file
.SH SYNOPSIS
.B pixcut
.RB [ \-v]
.RB [ \-h]
.RB [ \-H]
.RB [ \-a]
.RB [ \-C\  red/green/blue]
.RB [ \-s\  in_square_size]
.RB [ \-w\  in_width]
.RB [ \-n\  in_height]
.RB [ \-S\  out_square_size]
.RB [ \-W\  out_width]
.RB [ \-N\  out_height]
.RB [ \-x\  horizontal]
.RB [ \-y\  vertical]
.RB [ infile]
.SH DESCRIPTION
.I Pixcut
will extract a color
.IR pix (5)
format file from another
.IR pix (5)
format file.

The
.I \-w
and
.I \-n
flags specify the input file width and number of scan lines in pixels.
They can both be set to the same value via
.I \-s.
Unspecified dimensions default to 512 pixels.
.PP
The
.I \-W
and
.I \-N
flags specify the output file width and number of scan lines in pixels.
They can both be set to the same value via
.I \-S.
Unspecified dimensions default to 512 pixels.
.PP
The
.B \-h
and
.B \-H
flags indicate that the input and/or output file is high
resolution (1024x1024) respectfully.
.PP
The
.B \-a
flag requests that the program attempt to autosize the input file.  Autosizing
only works with files, pipes can not be autosized.
.PP
The
.B \-v
flag requests verbose mode.  When verbose mode is selected the program
will display information on default background output if any background
is generated.
.PP
The
.I \-x
and
.I \-y
flags set the horizontal and vertical offsets from the lower left corner
to use for extracting
the image.  By default both are set to 0 (zero).
.PP
The
.I \-C
flag is used to set the background color of the output file.  If the
output file is larger than the input file or if the corners of the output
file do not reside within the bounds of the input file, the program will
output pixels of background color for those locations.
.PP
First quadrant coordinates
and file storage formats are used.
.pp
.SH EXAMPLES
The command
.br
.I pixcut\ \-S256\ file1.pix\ \>file2.pix
.br
will extract the lower left quadrent of "file1.pix" and place it in
file2.pix.
.PP
The command
.br
.I pixcut\ \-S256\ \-x128\ \-y128\ file1.pix\ \>file2.pix
.br
will extract the center of the 512x512 input file (file1.pix) and place
it in file2.pix.
.PP
The command
.br
.I pixcut\ \-x\ \-\1\ file1.pix\ \>file2.pix
.br
will shift file1.pix one pixel to the right.  If a raytrace was done with
default parameters, the background (rays which do not intersect the model)
are set to 0/0/1.  Since
.I pixcut
will fill with 0/0/1 the net result is that the model image is shifted.
.PP
The command
.br
.I pixcut\ \-h\ \-x128\ \-y256\ background.pix\ |
.br
.I pixmatte\ \-w512\ \-e\ image.pix\ \=0/0/1\ \-\ image.pix\ |
.br
.I pixpaste\ \-h\ \-x128\ \-y256\ background.pix\ \-\ \>new.pix
.br
will extract the center 512x512 section of the 1024x1024 background image
composite that section with a foreground image and the place the new
composite image into the center of the background image.
.PP
The
.I pixmatte
command options instruct the program that for every pixel in image.pix
which is equal (-e) to 0/0/1 to output the corrisponding pixel from
standard input and for all others, output the corrisponding pixel from
image.pix
.SH "SEE ALSO"
brlcad(1), pixpaste(1), bwrect(1), pix(5), bw(5)
.SH AUTHOR
Christopher T. Johnson
.SH SOURCE
Paladin Software
.br
P.O. Box 187
.br
Aberdeen, MD  21001-0187
.br
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
