.TH PIXCLUMP 1
.\"                     P I X C L U M P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.SH NAME
pixclump \- quantize the colors in a pix(5) stream
.SH SYNOPSIS
.B pixclump
.RB [ \-c\  R/G/B]"
.RB [ \-f\  color_file]
.RB [ \-x\  debug_flags]
[infile.pix [outfile.pix]]

.SH DESCRIPTION
.I Pixclump
reads an input stream of
.I pix
data,
converts each pixel to one of a set of specified colors,
and writes out these quantized pixels.

The colors
may be specified
either on the command line,
with one
.B -c
option per color,
or in a file specified with the
.B -f
option.

Each pixel in the input stream
is compared to all of the specified colors
and replaced on the output by the specified color most resembling it.
.I Pixclump
computes the difference between an input pixel and a specified color
as the sum of the squares of the differences in their respective
red, green, and blue channels.

The
.B -x
option may be used to selectively enable
various diagnostic print statements.

.SH HINT
A typical use for
.I pixclump
is in renormalizing an image.
For example,
if a tool such as
.I pixscale
has been used to transform
an image containing a relatively small number of colors,
.I pixclump
will change pixels whose colors have been interpolated
back to one of the original colors.

.SH AUTHOR
Paul Tanenbaum
