.TH PIXCOLORS 1 BRL-CAD
.\"                    P I X C O L O R S . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pixcolors	\- Count/list color values used in a PIX(5) format image
.SH SYNOPSIS
.B pixcolors
.RB [ \-v ]
< pixfile
.SH DESCRIPTION
.I Pixcolors
reports on the standard output the number of distinct colors used in the
.I pix(5)
format file on the standard input.
.SH OPTIONS
.TP
.BI \-v
Causes a sorted list of the unique colors
used to be printed on standard output in addition to the count report.
