.TH PIXFADE 1 BRL-CAD
./"                      P I X F A D E . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
pixfade \- darken a pix file
.SH SYNOPSIS
.B pixfade
.RB [ \-f\  fraction]
.RB [ \-m\  max]
.RB [ \-p\  percentage]
[infile.pix] \>\ outfile.pix
.SH DESCRIPTION
.I pixfade
darkens a color pix file by fading the entire image a fractional amount
or by using a pixel value as a maximum level.
.PP
The
.B \-f
option specifies a nonnegative fractional multiplier which is used
to scale the red, green, and blue values of each pixel.  In a similar
way, the
.B \-p
option is used to specify the multiplier as a nonnegative percentage.
.PP
An alternative way to darken the image is to specify a ceiling pixel
level (0 - 255) with the
.B \-m
option.  The pixel plotted is the minimum of the ceiling value and the
red, green, and blue levels of the pixel.
.SH "SEE ALSO"
brlcad(1), pix(5)
.SH AUTHOR
Christopher T. Johnson
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
