.TH PIXFILTER 1 BRL-CAD
.\"                    P I X F I L T E R . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pixfilter \- apply a 3x3 filter to a color pix file
.SH SYNOPSIS
.B pixfilter
.RB [ \-f\  type]
.RB [ \-v ]
.RB [ \-d\  div]
.RB [ \-o\  offset]
.RB [ \-w\  width]
.RB [ \-n\  height]
.RB [ \-s\  squaresize]
[file.pix]
\>\ newfile.pix
.SH DESCRIPTION
.I Pixfilter
applies one of several 3x3 kernel filters to a color
.IR pix (5)
format file.
It will take a file name or else read from standard input.
The input file size will be assumed to be 512 by 512 pixels
unless the
.BR \-w ,
and/or
.BR \-n ,
or the
.B \-s
flags are used to tell it otherwise.
By default a low pass filter is used.  The
.BI \-f\  type
flag can be used to specify a different type of filter.
.PP
The
.I type
choices include:
.TP
.B lo
low pass, the default.
.TP
.B hi
high pass
.TP
.B vg
vertical gradient
.TP
.B hg
horizontal gradient
.TP
.B la
laplacian
.TP
.B b
boxcar low pass
.PP
Most filters divide the result of the kernel mutiplication
by some value in order to scale it back to a 0->255 range.
For example, the boxcar divides by nine.  The
.B -d
flag can be used to change this divisor.
Some filters also add an offset to their results.  The output of
a laplacian for example is "centered" about zero, thus it
adds 128 to the answer to yield a difference from neutral grey.
The
.B \-o
flag can be used to change this offset.
.PP
The
.B \-v
flag displays the kernel values on standard error.
.SH "SEE ALSO"
brlcad(1), pixscale(1), pix(5)
.SH BUGS
This should allow any 3x3 kernel to be specified.
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
