.TH PIXMERGE 1 BRL-CAD
.\"                     P I X M E R G E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pixmerge \-
merge two pix(5) or bw(5) images by a formula
.SH SYNOPSIS
.B pixmerge
.RB [ \-glen ]
.RB [ \-w\  bytes_wide]
.RB [ \-C\  r/g/b]
foreground.pix background.pix > out.pix
.SH DESCRIPTION
.I pixmerge
Given two streams of data, typically
.IR pix (5)
or
.IR bw (5)
images,
generate an output stream of the same size, where the value of
the output is determined by a formula involving the first
(foreground) stream and a constant, or the value of the second
(background) stream.
This routine operates on a pixel-by-pixel basis, and thus
is independent of the resolution of the image.
More sophisticated processing can be performed by the
.I pixmatte
program.
.PP
The formula can be any combination of
.B \-g
(fg greater than bg),
.B \-l
(fg less than bg),
.B \-e
(fg equal to bg),
.B \-n
(fg not equal to bg).
For example,
.B \-le
selects a foreground pixel when it
is lexicaly less than or equal to the background pixel,
that is, when all bytes of the foreground pixel are less than
or equal to the background pixel.
The
.B \-w#
flag specifies the width (in bytes) of each "pixel";  the default is
3, \fIie\fR
.IR pix (5)
file format.  A width of 1 is used for processing
.IR bw (5)
files.  It is unclear if other widths are useful.
If the
.B \-C\ r/g/b
option is specified, then the constant color specified by r/g/b
is used in place of the appropriate background pixel values.
It is expected that there will be up to
.B width
slash-separated constants given as a single parameter here.
.PP
If no formula is specified, the default is to take all foreground
pixels greater than black (all bytes zero), which can be specified
as:
.br
.ft I
   pixmerge -g -C 0/0/0 fg.pix bg.pix
.ft R
.SH EXAMPLES
.ft I
   gencolor 200 0 200 |
      pixmerge -g -C 20/20/20 fg.pix - > out.pix
.sp .5
   pixbackgnd -t0 160 200 |
      pixmerge -n -C 63/0/127 fg.pix - | pix-fb
.ft R
The second example is used to composite an
.IR rt (1)
generated image on top of a shaded background.
.SH "SEE ALSO"
brlcad(1), gencolor(1), pixbackgnd(1), pixmatte(1), pix(5), bw(5)
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
