.TH PIXROT 1 BRL-CAD
.SH NAME
pixrot \- rotate, invert, or reverse a color pix file
.SH SYNOPSIS
.B pixrot
[
.RB [ \-# bytes]
.RB [ \-rifb ]
.RB [ \-s\  squaresize]
.RB [ \-w\  in_width]
.RB [ \-n\  in_height]
[file.pix] \>\ newfile.pix
.SH DESCRIPTION
.I Pixrot
will rotate, invert, or reverse a color
.IR pix (5)
format file or read from standard input if a file name is not given.  The
.I \-w
and
.I \-n
flags specify the input file width and number of scan lines in pixels.
They can both be set to same same value via
.I \-s.
.PP
The
.B \-r
flag reverses the scan lines left to right.
.br
The
.B \-i
flag inverts the image top to bottom.
.br
The
.B \-f
and
.B \-b
flag will rotate the image ninety degrees forward or backward respectively.
The sense of the rotation is relative to a first quadrant coordinate
system, i.e. origin lower left, where "forward" means clockwise.
.PP
Note that a 180 degree rotation can be obtained by both reversing
and inverting.
.PP
By default three byte pixels are assumed as in the
.IR pix (5)
format.  However, the
.BI \-# bytes
flag can be used to specify some other pixel size, where
.I bytes
is the number of bytes per pixel.  Thus this program
can be used to manipulate rectangles of other data types, such as
an array of floating point numbers, files of text, etc.
.SH METHOD
A fairly large buffer is kept in memory so that, file size permitting,
the entire rotation can occur without seeking on input or output.
In any event, the algorithm is designed to process the input sequentially,
so that if any seeking is required, it will happen on output only.  If
these seeks fail, e.g. the output is a pipe, the user will be told that
it needs a file on output.
A more general solution to this problem would be to see if seeks can
be done on input instead, and switch the algorithm to seek on input
only.
.SH "SEE ALSO"
brlcad(1), pixscale(1), pixrect(1), pix(5).
.SH BUGS
If the file size is very large, excessive seeking may occur on output
and the rotation will take a very long time.  More complicated
algorithms could remedy this.
.br
Rotations of arbitrary angle are not supported.
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
