.TH PIXRECT 1 BRL-CAD
.\"                      P I X R E C T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pixrect \- extract a rectangle from a color pix file
.SH SYNOPSIS
.B pixrect
.RB [ \-# bytes]
infile outfile
.SH DESCRIPTION
.I Pixrect
extracts a rectangular region from a color
.IR pix (5)
format file.
The program prompts for the area to extract in x and y pixels,
the scanline length of the input file in pixels, and the origin
in the input file from which to extract.  First quadrant coordinates
and file storage formats are used.
.PP
By default pixels of size three bytes are assumed as in the
.IR pix (5)
format.  However, the
.BI \-# bytes
flag can be used to specify some other pixel size, where
.I bytes
is the number of bytes per pixel.  Thus this program
can be used to extract rectangles of other data types, such as
an array of floats, etc.
.SH "SEE ALSO"
brlcad(1), bwrect(1), pix(5), bw(5)
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.br
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
