.TH PIXCOLORS 1 BRL-CAD
.\"                     P I X S U B S T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pixsubst	\- Change color values used in a PIX(5) format image
.SH SYNOPSIS
.B pixsubst
[R_in G_in B_in] R_out G_out B_out < pixfile_in > pixfile_out
.SH DESCRIPTION
.I Pixsubst
reads
.I pix(5)
format pixels on the standard input and converts all pixels matching
the {R_in G_in B_in} to {R_out G_out B_out}. The pixels values are
specified as integers from 0 to 255. If {R_in G_in B_in} is not specified,
the first pixel in the input stream is used as the value to be changed.
