.TH PIXSHRINK 1 BRL-CAD
.SH NAME
pixshrink \- shrink a color pix file
.SH SYNOPSIS
.B pixshrink
.RB [ \-s\  squareinsize]
.RB [ \-w\  in_width]
.RB [ \-n\  in_height]
.RB [ \-f\  shrink_factor]
.RB [ \-h ]
.RB [ \-u ]
[infile.pix] \>\ outfile.pix
.SH DESCRIPTION
.I Pixshrink
will take a color
.IR pix (5)
format file of given dimensions and produce a smaller
scaled version.
The
.I \-w
and
.I \-n
flags specify the input file width and number of scan lines in pixels.
They can both be set to the same value via
.I \-s.
Defaults of 512 are assumed for unspecified dimensions.
The integer scaling factor is set with the
.I \-w
flag.  By default, the factor is 2.  Thus, pixshrink forms the logical
opposite of the
.B pixinterp2x (1)
program.
.PP
The program reads the entire image into memory,
and then scales the image down by
to 1/factor the original size in both dimensions.


By default, pixshrink uses boxcar averaging to produce the output pixels from
the input.  The 
.I \-u
option causes pixshrink to use image undersampling instead.
.PP
The
.B \-h
flag causes the frame buffer to be
used in high resolution mode (1024x1024).
This is important for frame buffers such as the Adage which operate
differently depending on the display size.  Without this flag
the default size for the selected device will be used (usually
the entire screen).
.PP
.SH "SEE ALSO"
brlcad(1), pixcrop(1), pixrect(1), pixinterp2x(1), pixscale(1), pix(5).
.SH BUGS
If the dimensions of the input image are not evenly divisible by the shrink
factor, incorrect and bizzare output is generated.
.SH AUTHOR
Lee A. Butler
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
