.TH PIXSTAT 1 BRL-CAD
./"                      P I X S T A T . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
pixstat \- list statistics related to a color pix image
.SH SYNOPSIS
.B pixstat
.RB [ \-v ]
[file.pix]
.SH DESCRIPTION
.I Pixstat
will take the given
.IR pix (5)
format file,
or read from standard in.  A collection of statistics
related to the pixel intensities is produced for each color
plane (red, green, and blue).
.br
These include:
.br
The number of pixels (and the square root of this which is the
file dimensions if square).
.br
The max and min values.
.br
The mean.
.br
The median (dividing line where half the pixels are above this
value, half below).
.br
The mode (most frequently occuring value) and
the number of pixels at this value.
.br
The variance, standard deviation, and skew.
.PP
The
.B \-v
flag will also dump a histogram of the pixel values.
.SH METHOD
Since the pixel values are quantized (each color having discrete values
from 0 to 255), the statistics can be computed from "lump sums" after
building a histogram of the input.  This results in a fantastic
savings in computation while also making a single pass over the input
file sufficient.
.SH "SEE ALSO"
brlcad(1), pixhist(1), bwstat(1), pix(5).
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
