.TH PIXTILE 1 BRL-CAD
.\"                      P I X T I L E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pixtile \- paste small images together into one large image
.SH SYNOPSIS
.B pixtile
.RB [ \-h ]
.RB [ \-s\  squareinsize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
.RB [ \-S\  squareoutsize]
.RB [ \-W\  out_width]
.RB [ \-N\  out_height]
.RB [ \-o\  startframe]
basename
\>
file.pix
.PP
.B pixtile
.RB [ \-h ]
.RB [ \-s\  squareinsize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
.RB [ \-S\  squareoutsize]
.RB [ \-W\  out_width]
.RB [ \-N\  out_height]
file1 file2 ... fileN
\>
file.pix
.SH DESCRIPTION
.I Pixtile
takes a collection of numbered small images and places them side
by side in one larger image.  The input and output files are
assumed to be in
.IR pix (5)
format.
By default, the output file will be made 512x512 pixels in size.
Specifying the
.B \-h
flag, changes the default size to 1024x1024 pixels.
.PP
The input files have a default width of 64 pixels per scanline
and are usually square, i.e. have the same height as width.
Specifying the
.B \-s
flag, changes the default size to
.I squareinsize
pixels per scanline and
.I squareinsize
scanlines as given in the argument list.
The
.B \-w
flag can be used to specify the input file width in pixels and the
.B \-n
flag can be used to specify the input file height in scanlines.
.PP
If the
.B \-S
flag is supplied, the output
size is changed from the default value of 512 to
.I squareoutsize
pixels per scanline and
.I squareoutsize
scanlines.
The
.B \-W
flag sets the output width size to
.I out_width
pixels per scanline.
Similarly, the
.B \-N
flag sets the output height size to
.I out_height
scanlines.
.TP
.B \-h
``hires'' flag.
Set both the height and width of the output to 1024.
The default is 512x512.
.TP
.BI \-s\  squareinsize
Specify both the number of pixels per scanline and the number of
scanlines in the input files.  The default is 64.

.TP
.BI \-w\  file_width
Specify the width (in pixels) per scanline of the input file.
The default is 64.
.TP
.BI \-n\  file_height
Specify the number of scanlines to be read from the input file.
The default is 64.
.TP
.BI \-S\  squareoutsize
Specify both the number of pixels per scanline (width) and the number of
scanlines (height) for the output file.  The default is 512.
.TP
.BI \-W\  out_width
Specify the width (in pixels) per scanline of the output file.
The default is 512.
.TP
.BI \-N\  out_height
Specify the number of scanlines to be sent to the output file.
The default is 512.
.TP
.BI \-o\  startframe
Specify the starting frame number, where
.I startframe
is substituted for
.I num
in
.I basename.num
.PP
The files being pasted together should have names of the form
.IR basename.num ,
where
.I basename
is given on the command line, and
.I num
is a consecutive series of integers.  By default the first image
is assumed to be number `` 0 '', but an alternate
.I startframe
can be given by using the
.B \-o
flag and supplying
.IR startframe .
The program keeps reading these small files until either the next
frame does not exist, or the output file is full.
They are placed in the output file from lower left to upper right.
The progress
of the composition is displayed on standard error.
.PP
If the basename is given as "\-" (a minus sign),
preceeded by a "\-\-" (two minus signs) to terminate
.IR bu_getopt (3)
processing,
then the stream of images is read from stdin rather than a file, such as
might be generated by a program like
.IR pcd-pix (1).
Such a stream could also be processed into files by
.IR pixbustup (1).
.PP
Alternatively, if more than one
.I basename
(filename) argument is supplied on the command line,
the names of the files being pasted together are assumed
to be explicitly stated and the
.B \-o
flag is not valid.  This allows files with different names to be
used without having to change the name of the files.
.PP
This program is the companion of
.IR fbanim (1)
which will step through these small images on a framebuffer capable
of zooming and windowing.  Thus many small low resolution frames can
be used as an animation "preview" for a higher resolution sequence,
the latter of which would go onto video tape or film.
.SH EXAMPLE
.I
pixtile \-h \-s 128 \-o 2 anim \>\ out.pix
.br
will read files
.I anim.2
through
.I anim.65
placing them from lower left to upper right in a 1024x1024 pixel
file
.IR out.pix .
.PP
.I
pixtile \-s 256 lowerleft lowerright upperleft upperright \>\ out.pix
.br
will read files
.IR lowerleft ,
.IR lowerright ,
.IR upperleft ,
and
.I upperright
placing them from lower left to upper right in a 512x512 file
.IR out.pix .
.SH "SEE ALSO"
brlcad(1), fbanim(1), pix(5).
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
