.TH PIXUNTILE 1 BRL-CAD
.\"                    P I X U N T I L E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pixuntile \- break small images up into separate files
.SH SYNOPSIS
.B pixuntile
.RB [ \-h ]
.RB [ \-s\  squareinsize]
.RB [ \-w\  in_width]
.RB [ \-n\  in_height]
.RB [ \-S\  squareoutsize]
.RB [ \-W\  out_width]
.RB [ \-N\  out_height]
.RB [ \-o\  startframe]
basename
\<
file.pix
.PP
.B pixuntile
.RB [ \-h ]
.RB [ \-s\  squareinsize]
.RB [ \-w\  in_width]
.RB [ \-n\  in_height]
.RB [ \-S\  squareoutsize]
.RB [ \-W\  out_width]
.RB [ \-N\  out_height]
file1 file2 ... fileN
\<
file.pix
.SH DESCRIPTION
.I Pixuntile
performs the inverse operation of
.IR pixtile (1).
It takes a large image composed of a collection of small images and
places each of them in a separate file.
The input and output files are
assumed to be in
.IR pix (5)
format.
By default, the input file is assumed to be 512x512 pixels in size.
Specifying the
.B \-h
flag, changes the default input size to 1024x1024 pixels.
.PP
The output files have a default width of 64 pixels
and are usually square, i.e. have the same height as width.
Specifying the
.B \-S
flag, changes the default size to
.I squareoutsize
pixels in width and height.
.PP
The files being produces as output will have names of the form
.IR basename.num ,
where
.I basename
is given on the command line, and
.I num
is a consecutive series of integers.  By default the first image
is assumed to be number `` 0 '', but an alternate
.I startframe
can be given by using the
.BI \-o\  startframe
flag and specifying the starting output frame number, where
.I startframe
is substituted for
.I num
in
.I basename.num
.PP
Alternatively, if more than one
.I basename
(filename) argument is supplied on the command line,
the names of the files are used as the output file names.
.SH EXAMPLE
.I
pixuntile \-h \-S 128 out\ \<\ in.pix
.br
will read the 1024x1024 file
.I in.pix
and place the 128x128 chucks of that file from
lower left to upper right in the files
.I out.0
through
.IR out.15 .
.SH "SEE ALSO"
pixtile(1), brlcad(1), pix(5).
.SH AUTHOR
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
