.TH PL-ASC 1 BRL-CAD
.\"                       P L - A S C . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pl-asc \- convert a Plot3 stream to ASCII
.SH SYNOPSIS
.B pl-asc
.RB [ \-v ]
[unix_plot]
.SH DESCRIPTION
Reads a stream in
.IR plot3 (5)
format and converts it to an ASCII representation.
Standard input is read if a file name is not supplied.
If the
.B \-v
option is given,
the single-character command names
are replaced with mnemonic strings
and a summary of plot command usage is written to standard error.
.SH "SEE ALSO"
asc-pl(1), pl-pl(1), plrot(1), pl-fb(1), libplot3(3), plot3(5)
.SH AUTHORS
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
