.TH PL\-PS 1 BRL-CAD
.\"                        P L - P S . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pl\(hyps \- convert UnixPlot to PostScript file
.SH SYNOPSIS
.B pl-ps
[-ec] [-s square_output_size] [-w output_width] [-n output_height] < unix_plot
.SH DESCRIPTION
.I Pl-ps
converts an extended UnixPlot file to a PostScript file
suitable for embedding in a larger PostScript document.
This is especially useful for creating figures for inclusion in TeX
documents.
The
.I -e
option will produce and encapsulated PostScript file. The
.I -s
,
.I -w
, and
.I -n
options specify the size of the output image in inches (ignored when used with the
.I -e
option).
.P
All UnixPlot line types are supported.
.P
If no UnixPlot
.B space
directive is seen, the default space ranges from
(0, 0, 0) to (4096, 4096, 4096).
.SH BUGS
This is just the bare bones of a program at the time
of this writing.
.SH "SEE ALSO"
pl-fb(1), pl-sgi(1), pl-pl(1), pl-X(1), plot3(5).
.SH AUTHORS
Michael John Muuss
.br
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "TRADEMARKS"
PostScript is a trademark of Adobe Systems Incorporated.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
