.TH PL\-PL 1 BRL-CAD
.\"                        P L - P L . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pl\(hypl \- convert an extended to a simple UnixPlot file
.SH SYNOPSIS
.B pl-pl
.RB [ \-v ]
.RB [ \-S ]
< unix_plot > unix_plot
.SH DESCRIPTION
UnixPlot is a simple machine and device independent plotting file
format found on both System V and BSD Unix systems.  BRL has extended
that format to include color, three dimensional plotting, machine
independent floating point coordinates, and a flush command for
interactive output.
.PP
.I Pl-pl
converts an extended UnixPlot file to the simpler format for
use by older, and non-extended, programs.  It drops color and
flush commands, strips the Z coordinate of 3D commands, and
converts floating point coordinates to integer.  By default to
integer conversion is done by simple truncation.  If the
.B \-S
option is given, the "space" command in the plot file is used to
center and scale the plot to the full 16 bit signed interger plotting
space (-32767 to +32767).  This is particularly useful for converting
floating point files.  The
.B \-v
verbose option causes each plot command to be described as it is being
converted.
.SH DIAGNOSTICS
A warning message is given if the input plot file did not contain
a space command since most older UnixPlot programs require them.
.SH "SEE ALSO"
plot(1), plrot(1), pl-fb(1), pldebug(1), libplot3(3), plot(5)
.SH AUTHORS
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
