.TH PL\-SGI 1 BRL-CAD
.\"                       P L - S G I . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pl\(hysgi \- display UnixPlot on a Silicon Graphics workstation
.SH SYNOPSIS
.B pl-sgi
.RB [ \-f ]
.RB [ \-n ]
.RB [ \-t\  thickness]
[unix_plot]
.SH DESCRIPTION
.I Pl-sgi
runs only on the Silicon Graphics 3030 and 4D series workstations.
It takes an extended UnixPlot file or files as input and draws
then on the display.  If your system has a knob and button box
the knobs control rotations and translations and the button box
has several pre-defined views and options built in.  Specifically,
the left row of knobs from top down are X, Y, and Z rotations,
and the right row are X, Y, and Z translations and Scale.  The
top row of buttons are: ortho view, perspective view, and reset
view, and the lower two rows of buttons are the same predefined
orientations that the
.IR mged (1)
editor uses.
.PP
The
.B \-n
flag indicates that the plot is intended for display at NTSC
resolution.  The display hardware is set for NTSC video output.
The
.B \-t
flag specifies the thickening (pixel width) of each line.
By default, lines are only a single pixel wide.
A thickness value of one or two is usually good when making 35mm
slides, while a thickness value of three or four is usually best
when making NTSC videotape recordings.
.PP
The three mouse button are: left - zoom out (.5x smaller), middle
- zoom in (2x larger), right - gives you a small menu of options.
The default choice is to center the current point (the one under
the cursor at the time of the mouse press).  Menu options also
include turning coordinate axis on and off, and outputting the current
"center" point after each repaint (although in 3D with combined
rotates and translates you will probably find this value to be
of little use).  If you have a Dunn Instruments film recorder
connected to your workstation, and the
.IR dunnsnap (1)
program is installed, then a menu selection can be made to snap
a picture of the current view.
.PP
If you are running under a window system (which SGI seems to force
you to do these days) then the
.B \-f
option tells the program to use the full screen for its display, i.e.
it creates a window with the borders just beyond the edge of the
display.
.SH "SALES HYPE"
The full power of floating point plotting can be seen in this kind
of environment, where multiple plots can be overlayed in their
natural coordinate scale, and one can zoom in or out over several
orders of magnitude without loss of precision.
.SH BUGS
The predefined views also change the centering and scale; they
should only affect the rotation.  There is no substitute yet
for the knob and button box for those that don't have one.
Even though this program has been growing new features for some
time, there are still many things on our wish list that it doesn't
do.
.SH "SEE ALSO"
pl-fb(1), pl-X(1), pl-pl(1), plot3(5).
.SH AUTHORS
Phillip Dykstra
.br
Paul R. Stay
.br
Gary S. Moss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
