.TH PL-STARBASE 1 BRL-CAD
.\"                  P L - S T A R B A S E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pl-starbase \- convert a Unix Plot file to Starbase commands
.SH SYNOPSIS
.B pl-starbase
\<\ unix_plot \>\ starbase_cmds
.SH DESCRIPTION
Reads a Unix Plot file from standard input and
converts it to Starbase commands which are written to standard output.
.SH "SEE ALSO"
pl-asc(1), pl-hpgl(1), pl-pl(1), plrot(1), pl-fb(1), libplot3(3), plot(5)
.SH AUTHORS
Mark Huston Bowden
.SH SOURCE
Research Institute, E-47
.br
University of Alabama in Huntsville
.br
Huntsville, AL  35899
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
