.TH PL-STARBASE 1 BRL-CAD
.SH NAME
pl-starbase \- convert a Unix Plot file to Starbase commands
.SH SYNOPSIS
.B pl-starbase
\<\ unix_plot \>\ starbase_cmds
.SH DESCRIPTION
Reads a Unix Plot file from standard input and
converts it to Starbase commands which are written to standard output.
.SH "SEE ALSO"
pl-asc(1), pl-hpgl(1), pl-pl(1), plrot(1), pl-fb(1), libplot3(3), plot(5)
.SH AUTHORS
Mark Huston Bowden  
.SH SOURCE
Research Institute, E-47 
.br
University of Alabama in Huntsville  
.br
Huntsville, AL  35899
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
