.TH PL\-TEK 1 BRL-CAD
.\"                       P L - T E K . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pl\(hytek \- convert UnixPlot to Tektronix 4014 command stream
.SH SYNOPSIS
.B pl-tek
.RB [ \-e ]
.RB [ \-v ]
< file.pl [ > file.tek ]
.SH DESCRIPTION
.I pl-tek
converts an extended UnixPlot file to a Tektronix 4014 command stream
suitable for viewing on a Tektronix display,
or a Tektronix-compatible emulator.
The (binary) Tektronix command stream is written to stdout.
.P
The
.B -e
option expands the drawing area on the Tektronix to the full 4096x4096,
which is more than a real Tektronix can display.
It it not known if this feature is useful.
.P
The
.B -v
option turns on \fIverbose\fR mode, and each command is logged to stderr.
Occasionally useful for debugging Tektronix emulator problems,
but is very verbose.
.P
To send a Unix-plot to an Imagen printer, this command can be used:

.nf
	\fIpl-tek < file.pl | ipr -Ltektronix -q im101\fR
.fi
.P
All UnixPlot line types are supported.
.P
If no UnixPlot
.B space
directive is seen, the default space ranges from
(-32767, -32767) to (32767, 32767).
.SH BUGS
Circle and arc directives are not supported.
.SH "SEE ALSO"
pldebug(1), pl-fb(1), pl-ps(1), pl-sgi(1), pl-pl(1), pl-X(1), plot3(5).
.SH AUTHORS
Michael John Muuss
.br
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
