.TH PL\-X 1 BRL-CAD
.\"                         P L - X . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
pl\(hyX \- display UnixPlot in an X Window (X11)
.SH SYNOPSIS
.B pl-X
.RB [ \-v ]
< unix_plot
.br
.SH DESCRIPTION
.I Pl-X
displays an extended UnixPlot file on any workstation running the
X Window System (X11R2).  As with all X programs, the selected
display is determined from the
.B
.SM DISPLAY
environment variable.
.PP
The
.B \-v
verbose option causes descriptions of the plot commands to be
printed.
.SH BUGS
This is just the bare bones of a display program at the time
of this writing.  It needs the ability to rotate, translate, zoom, etc.
.SH "SEE ALSO"
pl-X10(1), pl-fb(1), pl-sgi(1), pl-pl(1), plot3(5).
.SH AUTHORS
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
