.TH PLLINE2 1 BRL-CAD
.SH NAME
plline2 \- output a 2D UnixPlot line
.SH SYNOPSIS
.B plline2 x1 y1 x2 y2
.RI [ r\ g\ b ]
[< unix_plot]
> unix_plot.
.SH DESCRIPTION
.I Plline2
outputs a UnixPlot command to draw a line in the XY plane from
the point 
.RB ( x1\ y1 )
to the point
.RB ( x2\ y2 ).
These points can be floating point and the output is always written
as a floating point plotting command.  If you need an integer command
then feed the output of this through
.IR pl\-pl (1).
If an optional
.RI [ r\ g\ b ]
is given, where
.I r, g,
and
.I b
are values from 0 to 255 representing Red, Green, and Blue color values,
the line will be drawn in that color.  Otherwise the current drawing
color (white by default) is used.
.PP
To allow this command to be used in pipelines, an optional input file
can be given.  All of the input will be passed through until end of
file, and then the line will be appended to the end.
.PP
This command exists mostly as an aid for making graphs and things
from shell commands.
.SH "SEE ALSO"
plcolor(1), pl-pl(1), plot3(5).
.SH AUTHORS
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
