.TH PLLINE2 1 BRL-CAD
.\"                      P L L I N E 2 . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
plline2 \- output a 2D UnixPlot line
.SH SYNOPSIS
.B plline2 x1 y1 x2 y2
.RI [ r\ g\ b ]
[< unix_plot]
> unix_plot.
.SH DESCRIPTION
.I Plline2
outputs a UnixPlot command to draw a line in the XY plane from
the point
.RB ( x1\ y1 )
to the point
.RB ( x2\ y2 ).
These points can be floating point and the output is always written
as a floating point plotting command.  If you need an integer command
then feed the output of this through
.IR pl\-pl (1).
If an optional
.RI [ r\ g\ b ]
is given, where
.I r, g,
and
.I b
are values from 0 to 255 representing Red, Green, and Blue color values,
the line will be drawn in that color.  Otherwise the current drawing
color (white by default) is used.
.PP
To allow this command to be used in pipelines, an optional input file
can be given.  All of the input will be passed through until end of
file, and then the line will be appended to the end.
.PP
This command exists mostly as an aid for making graphs and things
from shell commands.
.SH "SEE ALSO"
plcolor(1), pl-pl(1), plot3(5).
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
