.TH PLROT 1 BRL-CAD
.\"                        P L R O T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
plrot \- rotate, translate, or scale a UnixPlot file
.SH SYNOPSIS
.B plrot
.RB [ \-x#\ \-y#\ \-z# ]
.RB [ \-X#\ \-Y#\ \-Z# ]
.RB [ \-s# ]
.RB [ \-a#\ \-e# ]
.RB [ \-g# ]
.RB [ \-M ]
.RB [ \-m# ]
.RB [ \-v ]
.RB [ \-S# ]
< unix_plot > unix_plot
.SH DESCRIPTION
.I Plrot
will rotate translate or scale a UnixPlot file (see
.IR plot (5)).
Any number of the above options can be given.
Each operation is performed left to right in the order in which they appear
on the command line,
and the operations are concatenated.
It is important to note that rotations are not commutative,
so the order they are specified in is important.
Typing the command without any arguments
gives a useful summary.
.PP
The lower case
.B \-x# \-y# \-z#
flags perform a rotation about the X, Y, and Z axis respectively by
the given number of degrees.  A positive value indicates a right handed
rotation.  Upper case
.B \-X# \-Y# \-Z#
are translations along these axis in whatever units the plot file is in.
The
.B \-s#
flag applies a scale factor up (> 1) or down (< 1) to the plot.
.PP
The
.B \-a# \-e#
flags are for azimuth and elevation about the center point.
They are really shorthands for positive Z axis and negative X axis
rotations respectively, and should be used in the order shown for
the proper combined effect to occur.  These flags also cause
the plot to auto-center based on the "space" command
in the plot file, and the new "space" command will be shrunk to
fit the rotated plot as tightly as possible.
.PP
The
.B \-M
flag causes
the plot to auto-center based on the "space" command
in the plot file in much the same way that the
.IR rt (1)
ray tracer does to a model bounding box.  I.e. a sphere is fit to
this space and the diameter and center of this sphere are used as
the center and width of the plot in all three dimensions.  This has
the advantage of keeping the entire model in view from any angle,
and is invariant with respect to viewing direction.
It has the disadvantage that the "space" will be enlarged on every
cascaded pass through
.IR plrot (1)
where the
.B \-M
flag is used.
.PP
The
.B \-S#
flags takes a quoted string of 6 floating point numbers,
which are immediately output as a "space" command,
and which override any "space" commands found in the input file
or which are computed by
.PP
The
.B \-v
flag signals that verbose mode is requested.
When set, the initial transformation
matrix is printed.
In addition, every time a \fIspace\fR command is encountered in the
input file, the old and new bounding RPP is printed.
.PP
The
.B \-m#
flag takes a quoted string of 16 floating point numbers as its parameter.
This string is a 4x4 rotation matrix (see h/vmath.h for details).
Note that when using this flag, do not use
.I \-a#, \-e#,
or
.I \-g.
.PP
UnixPlot is traditionally a first quadrant 2D plotting space with
X increasing to the right of the plot, and Y increasing up the plot.
The "front" of a solid model in the BRL-CAD Package is traditionally
defined by the right handed system of X comming out of the screen
toward you, Y increasing to the right, and Z increasing up the display
(elevation above the XY ground plane).  The
.B \-g
flag is a convenient shorthand to transform azimuths and elevations
described in \fBgift\fR notation (as degrees off the front or -X view)
into the UnixPlot coordinate system for display.
If used, this option should usually
appear as the last argument, because it acts by modifying the rotation already
established.
The
.B \-g
command has exactly the same effect as giving
.B \-z\-90\ \-x\-90
in the same place.
.SH EXAMPLES
The command
.br
.I plrot\ \-z\30\ \-x20\ \<\ file.plot\ \>\ file2.plot
.br
performs a 30 degree positive rotation about the Z axis (counter
clockwise as viewed from the top), and then translates by 20
units
.B along this rotated axis.
If the order of these arguments was reversed the effect would not
be the same.
.PP
To view a plot of a model the way one would see it from a
ray trace command, you could use:
.br
.I rthide\ \-a35\ \-e25\ \-o\ file.plot
.br
.I plrot\ \-a\35\ \-e25\ \-g\ \<\ file.plot\ \|\ pl-fb
.br
The final
.B \-g
converts the \fBgift\fR style azimuth and elevations into the
conventional UnixPlot (screen) X,Y coordinate system.
.SH "SEE ALSO"
pl-pl(1), pldebug(1), pl-fb(1), libplot3(3), plot(5)
.SH AUTHORS
Phillip Dykstra
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
