.TH PNG-BW 1 BRL-CAD
.\"                       P N G - B W . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
png-bw \- convert a Portable Networks Graphics (PNG) format file to a BW format
.SH SYNOPSIS
.B png-bw
.RB [ \-ntsc ]
.RB [ \-crt ]
.RB [ \-R [num]]
.RB [ \-G [num]]
.RB [ \-B [num]]
[in.png]
> out.bw
.SH DESCRIPTION
.I Pix-bw
will convert a
.IR PNG
format
file from it's standard input
and produce a black and white
.IR bw (5)
file on it's standard output, If the PNG file contains a B/W image the conversion is direct, however, if the PNG file contains a color image, then
by default all three colors are weighted equally.  The
.B \-ntsc
uses weighting based on the NTSC primaries and the D6500
alignment white.  The
.B \-crt
flag applies weights for "typical" CRT phosphor chromaticities
and the D6500 white.
.PP
Individual color plane(s) can be selected via the
.B \-R\ \-G
and
.B \-B
flags.
If one or more of these flags is followed by a value,
the value will be treated as a weight
to be applied to that color
This value is implicitly 1.0 divided by
the number of colors selected for the flags which are not followed
by a value.
.SH EXAMPLES
.I png-bw -R -B < file.png > file.bw
.br
will equally blend the red and blue color planes.
.PP
.I png-bw bw_file.png < file.bw
will convert a b/w PNG file to
.I bw(5)
format.
.PP
.I png-bw -R0.30 -G0.59 -B0.11 < file.png > file.bw
.br
has the same effect as the
.B \-ntsc
flag.
.br
[The
.B \-crt
weights are: 0.26, 0.66, 0.08]
.SH "SEE ALSO"
brlcad(1), png-pix(1), bw-png(1), pix-png(1), pix(5), bw(5).
.SH AUTHOR
John R. Anderson
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
