.\" @(#) $Header$ (BRL)
.TH PNG-PIX 1 BRL-CAD
.SH NAME
png-pix \- convert Portable Network Graphics (PNG) encoded image to RGB pixel format
.SH SYNOPSIS
.B png-pix
.RB [ \-v ]
[file.png] > file.pix
.SH DESCRIPTION
.I png-fb\^
decodes a Portable Network Graphics (PNG) format file
(saved with
.IR fb-png\^ (1),
.IR pix-png (1),
or a similar program),
converts it into
.IR pix\^ (5)
format, and writes it to standard out.
If
.I file.png\^
is not specified, standard input is read. The
.BI \-v
option provide verbose information about the PNG file.
.TP
.I file.png\^
Name of file to decode, in PNG format.
.TP
.I file.pix\^
Name of file to store PIX image in.
.SH EXAMPLE
.RS
\fI\|png-pix tank.png > tank.pix\fR
.RE
.SH "SEE ALSO"
brlcad(1), png-fb(1), fb-png(1), pix-png(1), png-bw(1), bw-png(1), pix(5).
.SH AUTHOR
John R. Anderson
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
