.TH PNG_INFO 1 BRL-CAD
.\"                     P N G _ I N F O . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
png_info \- Display the non-image information available in a Portable Networks Graphics (PNG) format file.
.SH SYNOPSIS
.B png_info
[in.png]
.SH DESCRIPTION
.I Png_info
will print most of the information available from a PNG file other than the image itself.
.SH EXAMPLES
.I png_info
file.png
.SH "SEE ALSO"
brlcad(1), png-pix(1), bw-png(1), pix-png(1), png-bw(1), pix(5), bw(5).
.SH AUTHOR
John R. Anderson
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
