#!/bin/sh
#
# rtwizard - Shell wrapper for the rtwizard.tcl script
#
# The trailing backslash forces tcl to skip the next line \
exec bwish "$0" "$@"

#
# Begin Tcl here!
#
foreach i $auto_path {
    set wizpath [file join $i {..} tclscripts rtwizard rtwizard.tcl ]
    if {  [file exists $wizpath] } {
	    source $wizpath
	    exit
    }
}

puts "rtwizard not found in any of $auto_path"