.TH SUN-PIX 1 BRL-CAD
.\"                      S U N - P I X . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
sun\(hypix \-
convert Sun bitmaps from screendump(1) into pix(5) or bw(5) raster image
.SH SYNOPSIS
.B sun-pix
.RB [ \-b ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-P ]
.RB [ \-v ]
[sun.bitmap]
.SH DESCRIPTION
.I Sun-pix
is a program to take Sun bitmap files created with Sun's
.IR screendump (1)
command, and convert them to a
.IR pix (5)
format file.  If the
.B \-b
flag is specified, a
.IR bw (5)
format file is created instead.
The dimensions of the input file are the dimensions of the output
file;  invoking
.I sun-pix
with the
.B \-h
flag will cause the size of the image to be printed without further
processing of the input, or generation of any other output.
The image size is output as a pair
of command line options (\fIie,\fB -w1152 -n900\fR) suitable
for use with other
.IR brlcad (1)
tools such as
.IR pix-fb (1).
When the
.B \-v
flag is specified, all the fields of the header are printed on stderr,
to aid debugging.  Note that the ``encoded'' format is not supported.
.PP
Specifying the
.B \-i
flag will invert the sense of a one-bit wide input image, \fIie\fR,
exchanging black for white.  The default Sun image is black print on
white background; the
.B \-i
flag will give a white image on black background, which is often better
for purposes of creating overlays to be composited with
.IR pixmerge (1)
on top of color images.
.PP
The
.B \-P
flag indicates that the input is a pure bitmap with no Sun-style header
on it.  The first bit to be processed will be the most significant bit (MSB),
\fIie\fR, the left-most bit in the byte.
.PP
Note that the input file is expected to be in Sun (``network'') byte order
(\fIie\fR, ``big-endian'', with byte 0 on the left), regardless
of the byte order of the machine running this program.
.SH BUGS
24-bit images are not supported yet.
.SH "SEE ALSO"
brlcad(1), pix-fb(1), pixmerge(1), pix(5), bw(5)
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
