.TH TERRAIN 1 "27 June 2000"
./"                      T E R R A I N . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
terrain \- Generate terrain field from mathematical noise
.SH SYNOPSIS
.B terrain
.I [ -w x_postings]
.I [ -n y_postings]
.I [ -s xy_postings]
.I [ -L noise_Lacunarity]
.I [ -H noise_H_value]
.I [ -O noise_octaves]
.I [ -o noise_offset]
.I [ -S noise_scale]
.I [ -V noise_Vector_scale]
.I [ -D noise_Delta]
.I [ -f noise_function]
.I [ -c host/net format conversion off]
> file.dsp
.SH DESCRIPTION
The
.I terrain
program produces pseudo-terrain from procedural noise suitable for use with a
BRL-CAD dsp primitive.  Noise values are computed for the grid points of the
lattice and the resultant values are output on the standard output as unsigned
shorts in network byte order.  The size of the grid is specified with the
.I -w
and
.I -n
options.


.SH OPTIONS
.PP
.PD 0
.TP 10
.BI -w "\| grid_x_postings"
Specifies the number of grid points in the X dimension.  Default is 256.
.TP
.BI -n "\| grid_y_postings"
Specifies the number of grid points in the Y dimension.  Default is 256.
.TP
.B -c
Turns of the conversion of the data from host to network format.  This only
has an effect on little-endian machines.
.TP
.B -v
Turns on verbose mode.  Information about which filter is running is printed.
.TP
.BI -f "\| noise_type"
Selects the type of noise field to be used.  Options include
.RS
.TP
.B L
A lunar-like surface.
.TP
.B f
Fractional Brownian motion (fBm).
.TP
.B t
Turbulence.
.TP
.B T
Turbulence inverted: 1.0 - turb(pt).
.TP
.B m
A Multi-fractal.
.TP
.B r
A Ridged multi-fractal.
.RE
.PD
.PP
.SS Noise Options
.TP 10
.TP
.BI \-O "\| noise_octaves"
Specifies the number of octaves of noise to layer.
Typical values are 2 through 8.
.BR $0 .
.TP
.BI \-L "\| noise_Lacunarity"
Specifies the scaling factor between successive octaves of noise.  Practical
values are non-integer numbers between 1.7 and 4.0.

.TP
.BI \-H "\| noise_H_val"
Specifies the value of H in the noise equation.  Usually 1.0

.TP
.BI \-S "\| noise_scale"
Scales the noise uniformly in X, Y and Z dimensions by the value
.I noise_scale.
Values below 1.0 cause the noise pattern to become smaller. Values above 1.0 cause it to get bigger

.TP
.BI \-V "\| scale_x,scale_y,scale_z"
Allows non-uniform scaling of the X, Y and Z dimensions.  See
.I -S
above.

.TP
.BI \-D "\| delta_x,delta_y,delta_z"
Specifies a translation in noise space to be


