.TH WAVELET 1 BRL-CAD
.SH NAME
wavelet \- perform a haar wavelet decomposition/reconstruction
.SH SYNOPSIS
.B wavelet
.BR [\-1]
.BR [\-2]
.BR [\-d]
.BR [\-r]
.BR [\-#\ channels ]
.BR [\-t\ {c | d | f | i | l | s}]
.BR [\-w\ width]
.BR [\-n\ scanlines ]
.BR [\-s\ squaresize ]
.BR [\-S\ square_out_size ]
.BR [\-W\ width_out ]
\<\ file > wavelet
.SH DESCRIPTION
The
.I wavelet
command
will perform Haar wavelet decomposition or reconstruction
transforms 
on the input dataset.
The command line options are:

.BI \-d
perform decomposition.

.BI \-r
perform reconstruction.

.br
.BI \-1
perform a 1-dimensional (horizontal) transform.

.BI \-2
perform a 1-dimensional (interleaved horizontal and vertical) transform.

.BI \-#\ channels
Indicates the number of values in each sample point.  For example, to perform
a transform on a 
.IR pix (5)
file properly, specify ``-# 3''.  This causes the red, green and blue channels
to be transformed individually.

.BI \-t\ {cdfils}
specifies the data type of the input, and hence the data type in which the
wavelet calculations will be performed.  
The letters each stand for the first
character of the C programming language data type: 
\fBc\fRharacter,
\fBd\fRouble,
\fBf\fRloat,
\fBi\fRnt,
\fBl\fRong,
\fBs\fRhort.
Note that if lossless decomposition
and reconstruction are desired, then data sets should be converted to the next
larger data type before being processed.


.BI \-w\ width
Specifiy the number of samples per scanline.

.BI \-n\ scanline
Specify the number of scanlines in the dataset

.BI \-s\ squaresize
Specify both width and scanlines simultaneously (square image).

.BI \-W\ width_out
Specifies the width of the output image.  Normally this is 1 for a full
decomposition/reconstruction.  You may specify a width at which decomposition or reconstruction
should stop. This number should be a power of 2.  The result will be an
``average'' image of the specified size, with the remainder of the original
data width converted to ``detail'' coefficients.  See also: -R

.BI \-R\ avg_size
Resumes a transform that left off with an average image of avg_size.



.BI \-S\ square_out_size
This is the same as the 
.B \-W
option.  It implies the square size for a 2D decomposition limit.



.SH EXAMPLES


The command
.br
.I decompose -# 3 < img.pix | pix-fb 
.br
will display the horizontal decomposition of the file img.pix.

The command
.br
.I decompose -# 3 -s 1024 -l 64 < img.pix > 
.br
will decompose a 1024x1024 image.  The decomposition will stop when the
image has been decomposed to 64x64.  The output image will thus have a 64x64
version of the original in the lower left corner of the image, with detail
terms in the remainder.

.SH "SEE ALSO"
brlcad(1), pix(5), bw(5)
.SH AUTHOR
Lee A. Butler
.SH SOURCE
brlcad package

.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
