/*
 *			libbn/Cakefile
 */
#define SRCDIR	libbn
#define PRODUCTS	libbn.ARCH_SUF
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#define FILES	\
	bn_tcl \
	complex \
	const \
	mat \
	msr \
	noise \
	plane \
	poly \
	qmath \
	rand \
	wavelet \
	asize \
	anim \
	tabdata \
	sphmap \
	plot3 fortran font \
	axis list marker number \
	scale vectfont symbol vector \
	tplot

#define VERSION_VARIABLE	bn_version
#define LIBRARY_TITLE		"The BRL-CAD Numerical Computation Library"

#include "../Cakefile.lib"

#include "../Cakefile.rules"
