#!/bin/sh

# Expects file "version" in current directory
# Main result sent to stdout, errors must go to stderr

if test $# != 0
then
	echo "Usage: sharedlibvers.sh" 1>&2
	echo "e.g.	.librt.sun4" 1>&2
	exit 1
fi


# Obtain RELEASE, RCS_REVISION, and REL_DATE
if test -r ../gen.sh
then
	eval `grep '^RELEASE=' ../gen.sh`
else
	echo "$0: Unable to get release number"  1>&2
	exit 1
fi

LIB=$1

if test -r ./version
then
	MINOR=`cat ./version`
else
	echo "$0: Unable to get minor version number from ./version"  1>&2
	../newvers.sh version_fudge "vers.c file generated by sharedlibvers.sh as fixup."
	MINOR=`cat ./version`
fi

echo $RCS_REVISION.$MINOR
