= 3DM-G(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME
3dm-g - Rhinoceros 3D Translator (3dm to BRL-CAD)

== SYNOPSIS

[source]
----
3dm-g [-r] [-v] [-h] [-o output_file.g] input_file.3dm [output_file.g]
----


[[description]]
== DESCRIPTION

*3dm-g* converts the Rhino3D file _input_file.3dm_ to a BRL-CAD database _output_file.g_. 

Because BRL-CAD uses the OpenNURBS library to read and process .3dm files, and also uses it for its internal NURBS support, the conversion is typically direct and reliable.


[[options]]
== OPTIONS

*-o, --output* _output_file.g_::
Specify the output BRL-CAD database name. This option is required if the output file is not specified as the last positional argument.

*-r*::
Randomize colors assigned to imported objects.

*-v, --verbosity*::
Increase verbosity of conversion progress reporting. Can be specified multiple times.

*-h, --help, -?*::
Print help and exit.


[[examples]]
== EXAMPLES

.Standard Conversion
[example]
====
$ *3dm-g model.3dm model.g*

Converts the Rhino3D file _model.3dm_ into a BRL-CAD database named _model.g_.
====

.Conversion with Randomized Colors and Verbose Output
[example]
====
$ *3dm-g -r -v -o nist.g NIST_MBE_PMI_7-10.3dm*

Imports the NIST MBE PMI 7-10 model into a BRL-CAD database named _nist.g_. Randomizes the colors assigned to imported objects and increases the verbosity level for detailed conversion progress reporting.
====


[[diagnostics]]
== DIAGNOSTICS

Users will see OpenNURBS diagnostic reporting as the 3dm file is read.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1999-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
