= ALIAS-PIX(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
alias-pix - convert an image from Alias(tm) pix format to BRL PIX(5) format

== SYNOPSIS

[source]
----
alias-pix [-v] < ALIASpixfile > BRLpixfile
----


[[description]]
== DESCRIPTION

*alias-pix* converts an Alias(tm) pix format file from standard input to a BRL PIX(5) format file on standard output.


[[options]]
== OPTIONS


*-v*::
print a text summary of the Alias pix file header on standard error output.


[[examples]]
== EXAMPLES

.Convert an Alias(tm) pix file to a BRL PIX(5) file
====
[source,bash]
----
$ alias-pix < image.alias > image.pix
----
Converts the Alias(tm) pix file `image.alias` and saves the output to the BRL PIX(5) file `image.pix`.
====

.Print file header summary while converting
====
[source,bash]
----
$ alias-pix -v < image.alias > image.pix
----
Converts `image.alias` to `image.pix` and prints a summary of the Alias pix file header to standard error.
====


[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

[[bug-reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
