= ASC-NMG(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
asc-nmg - ascii-to-NMG converter

== SYNOPSIS

[source]
----
asc-nmg ascii_file nmg.g
----


[[description]]
== DESCRIPTION

*asc-nmg* converts the specified __ascii_file__ (not a .asc geometry database) to a binary BRL-CAD _nmg.g_ geometry database file containing NMG objects. The __ascii_file__ is expected to contain lines of the following forms:

To start a new outer loop for a face:


....

	l
....

To start a new "hole" loop in the current face:


....

	l hole
....

To indicate a vertex in the current loop:


....

	v# x y z
....

where # is the vertex number and x, y, and z are the coordinates of that vertex.

To extrude a face:


....

	e x y z
....

where x, y, and z compose the extrusion vector for the face.

If an extrusion vector is specified, then the first face in the NMG objects list of faces will be extruded. This is intended for cases where only one face is described and then extruded to form a solid. Supplying an extrusion vector when more than one face is described may produce erroneous results. A solid may be built by extruding a face or by building enough faces to produce a closed shell. Each execution of *asc-nmg* will produce a single NMG object.


[[example]]
== EXAMPLE

If the file __ascii_file__ contains the following:


....

l
	e	-1 0 0
	v0	1 -1 -1
	v1	1 1 -1
	v2	1 1 0
	v3	1 0 0
	v4	1 0 1
	v5	1 -1 1
....

the command:


----

$ asc-nmg ascii_file sample.g
----

will produce an 'L'-shaped NMG solid to the _sample.g_ database file.


[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1994-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
