= ASC2G(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
asc2g - convert a BRL-CAD mged geometry database from ASCII to binary form.

== SYNOPSIS

[source]
----
asc2g [-h] [-?] input.asc output.g
----


[[description]]
== DESCRIPTION

*asc2g* converts a BRL-CAD geometry database from an ASCII format (created by *g2asc*(1)) to the current binary format. The tool accepts both legacy and current ASCII formats (see *HISTORY*), but always outputs the current ("v5") binary geometry database format.

Historically, the binary representation of a geometry database was architecture-dependent. *asc2g* and *g2asc* were used to export databases to a portable ASCII format for transfer between systems. While this is no longer necessary for the architecture-independent "v5" binary format, the tools remain useful for migrating legacy "v4" databases, inspecting database contents, or procedurally generating models via scripts.


[[examples]]
== EXAMPLES

*asc2g* _old_database.asc new_database.g_

[quote]
____
Converts an ASCII geometry database file (_old_database.asc_) into a new binary geometry database file (_new_database.g_).
____

*g2asc* _file.g file.asc_

[quote]
____
On a local machine, convert a binary database to ASCII using *g2asc*.
____

scp _file.asc_ remote:_file.asc_

[quote]
____
Transfer the converted database to a remote machine.
____

ssh remote "*asc2g* _file.asc file.g_"

[quote]
____
On the remote machine, convert the ASCII file back into a binary representation suitable for that machine using *asc2g*.
____


[[options]]
== OPTIONS

*-h*, *-?*::
    Print a usage message and exit.


[[files]]
== FILES

_input.asc_ is a file previously created using *g2asc* and _output.g_ is the name of the file where the resulting binary database should be stored.


[[see_also]]
== SEE ALSO

*g2asc*(1), *brlcad*(1), *mged*(1)


[[diagnostics]]
== DIAGNOSTICS

The diagnostics are intended to be self-explanatory. Any warning messages are written to standard error.


[[bugs]]
== BUGS

Reports of bugs or problems should be submitted via e-mail to _devs@brlcad.org_.


[[history]]
== HISTORY

Release 6.0 introduced a new ASCII format. This format is simply a Tcl script that, when executed by a simplified geometry command interpreter (in essence, a properly empowered Tcl interpreter), rebuilds the database from which it was derived.

In contrast, the old ASCII format consisted of a sequence of one-line records that corresponded to the old database format records.


[[author]]
== AUTHOR

*BRL-CAD Team*


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[disclaimer]]
== DISCLAIMER

The ASCII representation of BRL-CAD geometry databases is not a fixed format and is allowed to change without deprecation notice. In general, this will not occur any more frequently than the binary geometry database format changes, though both are open specifications. Regardless, the ASCII representation is subject to change without notice and should not be relied upon by external codes. (See *HISTORY*.)
