= BW-PIX(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
bw-pix - convert a black and white image, or three individual color channels, to a color pix image

== SYNOPSIS

[source]
----
bw-pix [-h] [-o out_file.pix] [file.bw [out_file.pix]]
bw-pix [-h] [-o out_file.pix] file_red.bw file_green.bw file_blue.bw [out_file.pix]
----


[[description]]
== DESCRIPTION

*bw-pix* converts black and white *bw*(5) format files into a color *pix*(5) format file. It can operate in two different modes depending on the number of input files provided.

When a single input file is provided (or when reading from standard input), *bw-pix* replicates each input value three times. The resulting output file will have identical values in all three color planes, effectively creating a grayscale image in RGB *pix* format.

When three input files are provided, *bw-pix* reads them concurrently and merges them, treating them as separate red, green, and blue color channels (in that order). The resulting color output file interleaves the bytes from each of the three input files.

If an output file is not specified with the *-o* option or as the final positional argument, output is written to standard output. If no input file is specified, *bw-pix* reads from standard input.


[[options]]
== OPTIONS

*-o out_file.pix*::
Specify the output file name. If this option is not used, output goes to standard output unless specified as the final positional argument.

*-h*::
Print a help message and exit.


[[examples]]
== EXAMPLES

bw-pix -o _image.pix_ _image.bw_

Converts the grayscale image _image.bw_ into a color _image.pix_ file where all three RGB planes contain the grayscale values.

bw-pix _red.bw_ _green.bw_ _blue.bw_ _merged.pix_

Combines the individual red, green, and blue channel files into a single color _merged.pix_ file.


[[see_also]]
== SEE ALSO

*brlcad*(1), *pix-bw*(1), *pix*(5), *bw*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
