= BW-PNG(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
bw-png - convert a BRL BW(5) format image to a PNG (Portable Network Graphics) format image

== SYNOPSIS

[source]
----
bw-png [-a] [-n file_height] [-w file_width] [-s squaresize] [BRLbwfile] > PNG_file
----


[[description]]
== DESCRIPTION

*bw-png* converts a _BRL BW(5)_ format file to a _PNG_ format file on the standard output. The PNG file created will be a Gray scale file with a bit-depth of 8 and a file gamma of 1.0.


[[options]]
== OPTIONS


*-a*::
autosize the input file to determine file image height and width


*-n file_height*::
tells *bw-png* that the input is __file_height__ scanlines tall


*-w file_width*::
tells *bw-png* that the input is __file_width__ pixels wide


*-s squaresize*::
sets both the width and the height for the input to be _squaresize_




[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1998-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
