= BW-PS(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
bw-ps - convert a black and white bw file to PostScript

== SYNOPSIS

[source]
----
bw-ps [-e] [-c] [-L] [-s input_squaresize] [-w input_width] [-n input_height] [-S inches_square] [-W inches_width] [-N inches_height] [infile.bw] > outfile.ps
----


[[description]]
== DESCRIPTION

*bw-ps* reads a black and white *bw*(5) format file of given dimensions and produces a PostScript file on the standard output. If no input file is specified, standard input is read. If no input dimensions are given, the input is assumed to be 512x512 pixels. By default, the output PostScript image size is 6.75x6.75 inches.

[[options]]
== OPTIONS

*-c*::
Center the output image on an 8.5 x 11 inch page.

*-e*::
Generate an Encapsulated PostScript (EPS) file instead of standard PostScript.

*-L*::
Select landscape mode (rotates the output image by ninety degrees).

*-n input_height*::
Specify the input image height (number of scan lines) in pixels.

*-N inches_height*::
Specify the output image height in inches.

*-s input_squaresize*::
Specify both the input image width and height in pixels.

*-S inches_square*::
Specify both the output image width and height in inches.

*-w input_width*::
Specify the input image width in pixels.

*-W inches_width*::
Specify the output image width in inches.


[[examples]]
== EXAMPLES

bw-ps -c _image.bw_ > _image.ps_

Produces a 6.75 inch PostScript file from an 512 x 512 input image and centers it on an 8.5 x 11 inch page.

bw-ps -e -w 1024 -n 768 _image.bw_ > _image.ps_

Takes the file image.bw which has the dimensions of 1024 pixels wide by 768 pixels high, and produces an Encapsulated Postscript version of it.

bw-ps -L -c -S 5.2 < _image.bw_ > _image.ps_

Makes a PostScript file of the (assumed 512 square) image, with the output image 5.2 inches square, in landscape mode, centered on an 8.5 x 11 inch page.


[[see_also]]
== SEE ALSO

*brlcad*(1), *bw*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
