= BWHIST(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
bwhist - display a histogram of a black and white bw file on a framebuffer

== SYNOPSIS

[source]
----
bwhist [-h] [-?] [-v] [file.bw]
----


[[description]]
== DESCRIPTION

*bwhist* calculates and displays a histogram of the pixel values in a *bw*(5) format file. If a file is not specified, standard input is read. The histogram is displayed on the framebuffer selected via the `FB_FILE` environment variable (see *libfb*(3)).

The relative frequency of each pixel value is displayed on the x-axis, scaled so that the maximum frequency spans the full width of the screen. The pixel values (0-255) correspond to the y-axis, with 0 (black) at the bottom of the screen and 255 (white) at the top. The histogram is drawn as a white overlay on whatever is currently displayed on the framebuffer.


[[options]]
== OPTIONS

*-v*::
Print the calculated histogram values and their relative frequencies to standard output.

*-h*, *-?*::
Print a usage summary and exit.


[[examples]]
== EXAMPLES

.Display a histogram of a bw file
====
[source,bash]
----
$ bwhist -v image.bw
----
Displays the histogram of `image.bw` on the active framebuffer and prints the corresponding numerical values to the terminal.
====


[[see_also]]
== SEE ALSO

*brlcad*(1), *bwhisteq*(1), *bwstat*(1), *bw*(5)


[[bugs]]
== BUGS

This program assumes the framebuffer has at least 512 scanlines to display the full histogram (2 lines per pixel value).


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
