= BWSCALE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
bwscale - change the size of a black and white bw file

== SYNOPSIS

[source]
----
bwscale [-r] [-s squareinsize] [-w in_width] [-n in_height] [-S squareoutsize] [-W out_width] [-N out_height] [-h] [-?] [infile.bw] > outfile.bw
----

[source]
----
bwscale infile.bw in_width in_height out_width out_height > outfile.bw
----


[[description]]
== DESCRIPTION

*bwscale* takes a black and white *bw*(5) format file of given dimensions and produces a larger or smaller scaled version. If input and output dimensions are not specified, a default of 512x512 is assumed for both.

By default, the algorithm used is bilinear interpolation when scaling up, and a box filter of arbitrary size when scaling down. For the box filter, a "square pixel" assumption is made: all whole and fractional input pixels falling into a rectangle the size of an output pixel contribute equally, based on the fraction of the output pixel area they cover. When interpolating, edge pixels are preserved (all interpolated pixels fall inside the edges). This can be surprising when doubling the size of an image, for example, as only the edge pixels will fall at exactly the location of an output pixel.


[[options]]
== OPTIONS

*-r*::
Enlarges the image by pixel replication (nearest neighbor interpolation) instead of bilinear interpolation.

*-s squareinsize*::
Sets both the input width and height to the specified size in pixels.

*-w in_width*::
Specifies the input width in pixels.

*-n in_height*::
Specifies the input height in pixels.

*-S squareoutsize*::
Sets both the output width and height to the specified size in pixels.

*-W out_width*::
Specifies the output width in pixels.

*-N out_height*::
Specifies the output height in pixels.

*-h*, *-?*::
Print help message and exit.

*infile.bw*::
The input image file. If not specified, standard input is read.


[[examples]]
== EXAMPLES

.Scale a 512x512 image down to 256x256
====
[source,bash]
----
$ bwscale -s 512 -S 256 input.bw > output.bw
----
====

.Enlarge a 256x256 image to 1024x1024 using pixel replication
====
[source,bash]
----
$ bwscale -r -s 256 -S 1024 input.bw > output.bw
----
====


[[see_also]]
== SEE ALSO

*brlcad*(1), *bwcrop*(1), *bwrect*(1), *bw*(5), *pixscale*(1)


[[bugs]]
== BUGS

This program cannot scale up in one dimension and down in the other at the same time.

The box filter used for scaling down results in the usual high-frequency ripple.

Optional cubic interpolation would be nice.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1984-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
