= BWSHRINK(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
bwshrink - shrink a black and white bw file

== SYNOPSIS

[source]
----
bwshrink [-s squareinsize] [-w in_width] [-n in_height] [-f shrink_factor] [-u] [infile.bw] > outfile.bw
----


[[description]]
== DESCRIPTION

*bwshrink* reads a black and white *bw*(5) format file and produces a scaled-down version. The program reads the entire image into memory and then scales it down to 1/factor of the original size in both dimensions. By default, *bwshrink* uses boxcar averaging to produce the output pixels.

[[options]]
== OPTIONS

*-u*::
Use image undersampling instead of boxcar averaging.

*-w in_width*::
Specify the input file width in pixels. The default is 512.

*-n in_height*::
Specify the input file height (number of scanlines) in pixels. The default is 512.

*-s squareinsize*::
Set both the input file width and height to the given size in pixels.

*-f shrink_factor*::
Set the integer scaling factor. The default factor is 2.

[[examples]]
== EXAMPLES

.Shrinking a 1024x1024 image
====
[source,bash]
----
$ bwshrink -s 1024 -f 4 image.bw > image_small.bw
----
Shrinks the 1024x1024 input file `image.bw` by a factor of 4, producing a 256x256 output file named `image_small.bw`.
====

[[see_also]]
== SEE ALSO

*brlcad*(1), *bwcrop*(1), *bwrect*(1), *bwscale*(1), *bw*(5)


[[bugs]]
== BUGS

If the dimensions of the input image are not evenly divisible by the shrink factor, incorrect and bizarre output is generated.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
