= CAD_BOUNDP(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
cad_boundp - find bounding polygon of two-dimensional view

== SYNOPSIS

[source]
----
cad_boundp [-i input] [-o output] [-t tolerance] [-v] [-h] [-?]
----


[[description]]
== DESCRIPTION

*cad_boundp* reads a series of 2D line segment endpoints from an input file (or standard input) and computes the bounding polygon. It writes the vertices of the resulting bounding polygon to an output file (or standard output) in counter-clockwise order, starting with the vertex having the smallest _y_ coordinate. The input data describes a two-dimensional view of the edges of a 3D object.

Input lines that do not begin with a number are silently ignored, which allows for comments or additional control information to be interspersed with the data.


[[options]]
== OPTIONS

*-i input*::
Read line segment coordinate data from _input_. If not specified, standard input is used.

*-o output*::
Write the bounding polygon vertices to _output_. If not specified, standard output is used.

*-t tolerance*::
Specify a floating-point _tolerance_ for comparing point coordinates. A point is considered identical to a previously-input point if the Euclidean distance between them is less than or equal to _tolerance_. The algorithm groups points by matching against the first point encountered that satisfies the tolerance test. If not specified, point coordinates must match precisely. If the _tolerance_ is too tight, or if the input is incomplete, a degenerate or smaller-than-expected polygon may result.

*-v*::
Output the bounding polygon as line segment data (pairs of endpoints) rather than individual vertex points. This format is suitable for input into another invocation of *cad_boundp*.

*-h*, *-?*::
Print usage information and exit.


[[restrictions]]
== RESTRICTIONS

*cad_boundp* may output a polygon smaller than desired or produce a "degenerate input" message if the _tolerance_ is too tight or if input is incomplete. It may be wise to specify double the expected _tolerance_.

Holes within the view cannot be recognized.

Silhouette thickness must everywhere exceed _tolerance_ (no narrow necking-down) or a portion of the silhouette will be "lost"; in particular, the view should not consist of disjoint parts.


[[examples]]
== EXAMPLES

The following example demonstrates computing the bounding polygon for a set of four line segments forming a square.

.Using `cad_boundp` to find a bounding polygon
====
[source,sh]
----
$ cat square.txt
# Bottom edge
0.0 0.0 1.0 0.0
# Right edge
1.0 0.0 1.0 1.0
# Top edge
1.0 1.0 0.0 1.0
# Left edge
0.0 1.0 0.0 0.0

$ cad_boundp -t 0.01 -i square.txt
0 0
1 0
1 1
0 1
----
====


[[see_also]]
== SEE ALSO

*cad_parea*(1)


[[diagnostics]]
== DIAGNOSTICS

Any error condition causes *cad_boundp* to terminate with non-zero exit status after it prints an error message on the standard error output.

An illegal argument or improperly formatted input produces an appropriate message.

If a vertex having only one line segment connected to it is found on the perimeter, *cad_boundp* produces the message "degenerate input".

If there is too much data for *cad_boundp* to handle, the message "out of memory" is produced.


[[author]]
== AUTHOR

Douglas A. Gwyn, BRL/VLD-VMB


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
