= CAD_PAREA(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
cad_parea - compute area of polygon

== SYNOPSIS

*cad_parea* [-h] [-?] [-i _input_] [-o _output_]

[[description]]
== DESCRIPTION

*cad_parea* reads a series of 2D polygon vertex coordinate values (_x_, _y_) from an input stream and writes the computed polygon area to an output stream. Vertices are expected to be provided in counter-clockwise cyclic order.

Lines not beginning with a number are silently skipped.

[[options]]
== OPTIONS

*-h*, *-?*::
	Print a usage message and exit.

*-i* _input_::
	Read coordinates from the specified _input_ file instead of standard input.

*-o* _output_::
	Write the computed area to the specified _output_ file instead of standard output.


[[hints]]
== HINTS

A hole can be accommodated as a clockwise section connected to the periphery by a line segment traced in both directions.

Disjoint pieces may be connected by a line segment traced in both directions.


[[examples]]
== EXAMPLES

.Calculate the area of a square
====
Compute the area of a 1x1 square by providing its vertices via standard input:

[source,bash]
----
$ cat square.txt
0 0
1 0
1 1
0 1
$ cad_parea -i square.txt
1
----
====
[[see_also]]
== SEE ALSO

*cad_boundp*(1)


[[diagnostics]]
== DIAGNOSTICS

Improperly formatted input produces an error message and terminates *cad_parea* with non-zero exit status.

*cad_parea* outputs "0" for the area of a degenerate polygon.


[[author]]
== AUTHOR

Douglas A. Gwyn, BRL/VLD-VMB


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
