= CONV-VG2G(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
conv-vg2g - upgrade old binary MGED databases to version 4 format

== SYNOPSIS

[source]
----
conv-vg2g file.vg file.g
----


[[description]]
== DESCRIPTION

*conv-vg2g* converts older forms of binary *mged*(1) databases to the version 4 format.

The conversion from version 3 to version 4 is fairly straightforward. Conversion from older versions requires additional information, for which the user is interactively prompted. The user must specify the database units (1=mm, 2=cm, 3=meters, 4=inches, 5=feet) and a title for the database.


[[examples]]
== EXAMPLES

.Convert an old database and inspect the result
====
[source,bash]
----
conv-vg2g old_model.vg new_model.g
mged new_model.g
----
Converts the old binary database _old_model.vg_ to the version 4 format,
saving the output to _new_model.g_, then opens the converted database in
*mged*(1). If the input predates version 3, *conv-vg2g* interactively
prompts for the original units (1=mm, 2=cm, 3=meters, 4=inches, 5=feet)
and a title so geometry can be scaled to the millimeter base units used
internally.
====


[[see_also]]
== SEE ALSO

*brlcad*(1), *dbupgrade*(1), *mged*(1)


[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory and usually indicate errors in the input database. It may be possible to rescue a damaged old database by suitably modifying the source code to the converter.


[[author]]
== AUTHOR

Keith A. Applin


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
