= DECIMATE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
decimate - reduce the resolution of an image or data file

== SYNOPSIS

[source]
----
decimate nbytes/pixel width height [outwidth outheight]
----

[[description]]
== DESCRIPTION

*decimate* reads a file of _width_ by _height_ data items from standard input, and discards enough data to produce an output file of _outwidth_ by _outheight_ items on standard output. The size of each data item is specified by _nbytes/pixel_. If _outwidth_ and _outheight_ are not provided, both default to 512.

If the input image size is not an integer multiple of the output image size, the result is padded with zero elements (pixels) on the right and top to achieve an output image of exactly the specified size.

To process a *bw*(5) format file, use a value of 1 for _nbytes/pixel_. To process a *pix*(5) format file, use a value of 3.

[[examples]]
== EXAMPLES

.Downsample a large pix image so it fits on a framebuffer
====
[source,bash]
----
$ decimate 3 1024 1024 512 512 < input.pix | pix-fb -w 512 -n 512
----
Reduce a 1024x1024 *pix*(5) image (3 bytes/pixel) to 512x512 by discarding
every other sample and scanline, piping the result straight to *pix-fb*(1)
for a quick preview of an image too large for the framebuffer.
====

[[see_also]]
== SEE ALSO

*brlcad*(1), *pix-fb*(1), *bw*(5), *pix*(5)

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
