= DXF-G(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
dxf-g - DXF Translator (DXF to BRL-CAD)

== SYNOPSIS

[source]
----
dxf-g [-c] [-d] [-v] [-s scale_factor] [-t tolerance] file.dxf database.g
----


[[description]]
== DESCRIPTION

*dxf-g* converts the specified _file.dxf_ to a BRL-CAD _database.g_ file.

The following options are available:


*-c*::
Only the first color seen for a layer should be used. Without this option, layers may be broken into separate BOT primitives according to color assigned.


*-d*::
Sets a debug flag. The only effect is to cause a core dump on failure. This is probably not useful except for developers.


*-v*::
Produces very verbose output on stderr.


*-s* __scale_factor__::
Provides a scale factor to be applied to the DXF input. This can be used for DXF files that do not provide units information.


*-t* _tolerance_::
Specifies the maximum distance (in mm) between two vertices at which the two vertices will be considered to be the same vertex.



The _file.dxf_ file is expected to be in the ASCII Autodesk DXF format as defined in the Autocad 2006 manuals. This converter handles entities of types:

POLYLINELWPOLYLINELEADERDIMENSIONVERTEXLINECIRCLEARCELLIPSE3DFACETEXTMTEXTATTRIBSOLIDSPLINE

The POLYLINE entities in AUTOCAD are actually a container for numerous different entity types. The types of POLYLINE entities converted include:

3D polylines;3D polygon meshes;polyface meshes

SOLID entities are 2D shapes with a solid fill, but this converter does not do any filling. Each layer is converted to a separate object. Colors are also converted.


[[example]]
== EXAMPLE


----

$ dxf-g sample.dxf sample.g
----


[[see_also]]
== SEE ALSO

__http://images.autodesk.com/adsk/files/dxf_format.pdf__


[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1993-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
