= DXF-G(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
dxf-g - DXF Translator (DXF to BRL-CAD)

== SYNOPSIS

[source]
----
dxf-g [-c] [-d] [-v] [-s scale_factor] [-t tolerance] [-h] [-?] file.dxf database.g
----

[[description]]
== DESCRIPTION

*dxf-g* converts an AutoCAD DXF file (_file.dxf_) to a BRL-CAD
database (_database.g_). The input is expected to be in ASCII DXF
format as defined in the AutoCAD 2006 manuals.

Supported DXF entity types include: POLYLINE, LWPOLYLINE, LEADER,
DIMENSION, VERTEX, LINE, CIRCLE, ARC, ELLIPSE, 3DFACE, TEXT, MTEXT,
ATTRIB, SOLID, and SPLINE. Supported POLYLINE subtypes include 3D
polylines, 3D polygon meshes, and polyface meshes.

SOLID entities are 2D filled shapes, but this converter does not
perform any filling. Each DXF layer is converted to a separate
BRL-CAD object. Colors are also preserved.

[[options]]
== OPTIONS

*-c*::
Use only the first color encountered for each layer. Without this
option, layers may be split into separate BOT primitives by color.

*-d*::
Enable a debug flag that causes a core dump on failure. Useful only
for developers.

*-v*::
Produce verbose output on standard error.

*-s* _scale_factor_::
Apply _scale_factor_ to the DXF input. Useful for files that do not
specify units.

*-t* _tolerance_::
Maximum distance (in mm) between two vertices at which they are
considered the same vertex.

*-h, -?*::
Print a usage message and exit.

[[examples]]
== EXAMPLES

.Convert a DXF file to a BRL-CAD database
====
[source,bash]
----
$ dxf-g sample.dxf sample.g
----
====

.Convert with a scale factor and tight tolerance
====
[source,bash]
----
$ dxf-g -s 25.4 -t 0.01 drawing_inches.dxf drawing.g
----
Converts a DXF file drawn in inches to millimeters (25.4 mm/in)
with a vertex merge tolerance of 0.01 mm.
====

[[see_also]]
== SEE ALSO

*g-dxf*(1)

[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1993-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
