= ENF-G(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
enf-g - Elysium Neutral Format Translator (ENF to BRL-CAD)

== SYNOPSIS

[source]
----
enf-g [-t tolerance] [-i starting_ident_number] [-l name_length_limit] [-n part_number_to_name_mapping] [-v] input_enf_facet_file database.g
----


[[description]]
== DESCRIPTION

*enf-g* converts the specified _input_enf_facet_file_ to a BRL-CAD _database.g_ file. The input file is expected to be the ASCII output from the Elysium _enf2mxp_ tessellator.

[[options]]
== OPTIONS

*-i starting_ident_number*::
Specifies the starting ident number for the first region created. Each succeeding region will have its ident number incremented by one. The default is 1000.

*-t tolerance*::
Specifies the maximum distance (in mm) between two vertices at which they will be considered the same vertex. The default is the BRL-CAD standard tolerance (0.0005 mm).

*-l name_length_limit*::
Sets a maximum length limit for the resulting object names in the BRL-CAD model. Names exceeding this limit will be truncated.

*-n part_number_to_name_mapping*::
Specifies a file containing a mapping from part numbers to object names. The file is expected to contain one mapping per line, consisting of a part number and a legal BRL-CAD object name separated by whitespace (tab or space). This file is used to convert part numbers in the input ENF facet file to the corresponding names in the mapping.

*-v*::
Enables verbose output mode.

*-h, -?*::
Print a usage message and exit.

[[examples]]
== EXAMPLES

The following example demonstrates a basic conversion of an ENF file to a BRL-CAD database, starting region ident numbers at 2000 and limiting object names to 32 characters.

.Converting an ENF File with Custom Ident Numbers and Name Lengths
====
[prompt]#$# [in]`enf-g -i 2000 -l 32 sample.enf sample.g`
====


[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2001-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
