= FB-PIX(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fb-pix - save a framebuffer image as a color pix file

== SYNOPSIS

[source]
----
fb-pix [-i] [-c] [-F framebuffer] [-s squaresize] [-w width] [-n height] [-h] [-?] [file.pix]
----

[[description]]
== DESCRIPTION

*fb-pix* reads a region of a framebuffer and saves it as a
*pix*(5) format file. If no output file is given, data is written
to standard output.

By default, the output and framebuffer size are 512x512 pixels,
with a first-quadrant coordinate system (origin at the lower left).

[[options]]
== OPTIONS

*-i*::
Use a fourth-quadrant coordinate system (origin at the upper left),
affecting both the storage order and offset coordinates.

*-c*::
Apply the framebuffer color map to pixel values before writing.

*-F* _framebuffer_::
Specify the framebuffer device. Defaults to the `FB_FILE`
environment variable (see *brlcad*(1)).

*-s* _squaresize_::
Set both width and height to _squaresize_.

*-w* _width_::
Set the output width in pixels.

*-n* _height_::
Set the output height in pixels.

*-h, -?*::
Print a usage message and exit.

[[examples]]
== EXAMPLES

.Save a 1024x1024 framebuffer image to a file
====
[source,bash]
----
$ fb-pix -s 1024 render.pix
----
====

.Save with color map applied
====
[source,bash]
----
$ fb-pix -c -F /dev/ogl scene.pix
----
Saves the image from `/dev/ogl` with the framebuffer color map
baked into the output pixel values.
====

[[see_also]]
== SEE ALSO

*brlcad*(1), *pix-fb*(1), *fb-bw*(1), *pix*(5)

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
