= FB-PNG(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fb-png - save a framebuffer image in a color Portable Network Graphics (PNG) file

== SYNOPSIS

[source]
----
fb-png [-ic] [-# nbytes/pixel] [-g gamma] [-F framebuffer] [-s squaresize] [-w width] [-n height] [file.png]
----


[[description]]
== DESCRIPTION

*fb-png* will take a region of a framebuffer display and save it as a color _png_ format file. The environment variable `FB_FILE` is used to select the display device (see *brlcad*(1)). If this variable is not set, the default device for your system will be used. Alternatively, the framebuffer may be explicitly specified by using the *-F* flag.

By default, the output _png_ file, and the requested framebuffer size, is assumed to be 512x512 pixels. The *-s* flag will set both the file height and width to be the given size, while *-w* and *-n* are used for setting them individually.

A first quadrant coordinate system is used (origin in lower left of screen), and the area saved is normally from this origin. The *-i* flag switches to a fourth quadrant system, both in the storage order as well as the origin offset coordinates (i.e. origin is now the upper left corner of the screen).

The *-#* _nbytes/pixel_ flag specifies the number of bytes per pixel. The only values accepted are 1 and 3.

The *-c* flag specifies that the color map in the frame buffer should be applied to the pixel values (crunched) before they are written to the output file.

The *-g* _gamma_ flag sets the specified gamma correction value into the created PNG file. A value of 0.6 is a close approximation of PC display monitors. A negative gamma value disables writing a gAMA chunk out entirely (and is the default).


[[see_also]]
== SEE ALSO

*brlcad*(1), *png-fb*(1), *fb-bw*(1), *pix*(5)


[[author]]
== AUTHOR

John R. Anderson


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1998-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
