= FB-PNG(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fb-png - save a framebuffer image as a Portable Network Graphics (PNG) file

== SYNOPSIS

[source]
----
fb-png [-i] [-c] [-#  nbytes/pixel] [-g gamma] [-F framebuffer] [-s squaresize] [-w width] [-n height] [-h] [-?] [file.png]
----

[[description]]
== DESCRIPTION

*fb-png* reads a region of a framebuffer and saves it as a PNG
file. If no output file is given, data is written to standard
output.

By default, the output and framebuffer size are 512x512 pixels,
with a first-quadrant coordinate system (origin at the lower left).

[[options]]
== OPTIONS

*-i*::
Use a fourth-quadrant coordinate system (origin at the upper left).

*-c*::
Apply the framebuffer color map to pixel values before writing.

*-#* _nbytes/pixel_::
Number of bytes per pixel. Accepted values are 1 (grayscale) and 3
(color).

*-g* _gamma_::
Write the specified gamma correction value into the PNG gAMA chunk.
A value of 0.6 approximates PC display monitors. A negative value
(the default) disables writing the gAMA chunk entirely.

*-F* _framebuffer_::
Specify the framebuffer device. Defaults to the `FB_FILE`
environment variable (see *brlcad*(1)).

*-s* _squaresize_::
Set both width and height to _squaresize_.

*-w* _width_::
Set the output width in pixels.

*-n* _height_::
Set the output height in pixels.

*-h, -?*::
Print a usage message and exit.

[[examples]]
== EXAMPLES

.Save a 1024x1024 framebuffer image as PNG
====
[source,bash]
----
$ fb-png -s 1024 render.png
----
====

.Save with gamma correction for PC monitors
====
[source,bash]
----
$ fb-png -g 0.6 -s 512 scene.png
----
====

[[see_also]]
== SEE ALSO

*brlcad*(1), *png-fb*(1), *fb-bw*(1), *pix*(5)

[[author]]
== AUTHOR

John R. Anderson

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1998-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
