= FB-PIX(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fb-pix - save a framebuffer image in a color pix file

== SYNOPSIS

[source]
----
fb-pix [-ic] [-F framebuffer] [-s squaresize] [-w width] [-n height] [file.pix]
----


[[description]]
== DESCRIPTION

*fb-pix* will take a region of a framebuffer display and save it as a color *pix*(5) format file. The environment variable `FB_FILE` is used to select the display device (see *brlcad*(1)). If this variable is not set, the default device for your system will be used. Alternatively, the framebuffer may be explicitly specified by using the *-F* flag.

By default, the output _pix_ file, and the requested framebuffer size, is assumed to be 512x512 pixels. The *-s* flag will set both the file height and width to be the given size, while *-w* and *-n* are used for setting them individually.

A first quadrant coordinate system is used (origin in lower left of screen), and the area saved is normally from this origin. The *-i* flag switches to a fourth quadrant system, both in the storage order as well as the origin offset coordinates (i.e. origin is now the upper left corner of the screen).

The *-c* flag specifies that the color map in the frame buffer should be applied to the pixel values (crunched) before they are written to the output file.


[[see_also]]
== SEE ALSO

*brlcad*(1), *pix-fb*(1), *fb-bw*(1), *pix*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
