= FBCLEAR(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbclear - clear a frame buffer to a color

== SYNOPSIS

[source]
----
fbclear [-c] [-F framebuffer] [-{sS} squaresize] [-{wW} width] [-{nN} height] [gray | r g b]
----


[[description]]
== DESCRIPTION

*fbclear* erases a frame buffer using whatever method is efficient for
the device being accessed.  With no color arguments the frame buffer is
cleared to black.  A single _gray_ value (0 to 255) is written into all
three channels, while three values (_r g b_) set each channel
independently.

The frame buffer to clear is selected by the *-F* option, or by the
`FB_FILE` environment variable, or otherwise the default device for your
system (see *brlcad*(1)).

Unless *-c* is given, *fbclear* leaves any colormap and zoom/pan settings
untouched, printing a note if a non-linear colormap or non-unity zoom is
in effect.

[[options]]
== OPTIONS

*-c*::
  Also reset the colormap to linear and reset the pan and zoom to their
  default (centered, un-zoomed) values.

*-F* _framebuffer_::
  Use the specified _framebuffer_ device, overriding the `FB_FILE`
  environment variable.

*-s* _squaresize_, *-S* _squaresize_::
  Set both the width and height of the frame buffer to _squaresize_
  pixels.

*-w* _width_, *-W* _width_::
  Set the width of the frame buffer to _width_ pixels.

*-n* _height_, *-N* _height_::
  Set the height of the frame buffer to _height_ pixels.

[[examples]]
== EXAMPLES

.Reset a framebuffer before compositing
====
[source,bash]
----
fbclear -c -F /dev/X 64 64 96
pix-fb -F /dev/X scene.pix
----
Open the X11 framebuffer, clear it to a dark blue while resetting any
leftover colormap and zoom from a previous session, then display a
rendered image on the freshly prepared display.
====

[[see_also]]
== SEE ALSO

*brlcad*(1), *fbcmap*(1), *fbgamma*(1), *fbzoom*(1), *pix-fb*(1)

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
