= FBCOLOR(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbcolor - interactively pick colors

== SYNOPSIS

....
fbcolor [-F framebuffer] [-s|-S squaresize] [-w|-W width] [-n|-N height] [-h]
....

== DESCRIPTION

*fbcolor* is an interactive color picking facility. It displays color
bars and a solid background on a framebuffer, allowing you to pick and
display colors by varying parameters in either RGB (red, green, blue)
or HSV (hue, saturation, value) space.

*fbcolor* draws a set of color bars in the lower left corner of the
display, sets the remainder of the display to the current color, then
starts reading standard input for color editing commands. As the
various parameters are changed, the color bars grow and shrink to show
the relative red, green, and blue intensities.

At the same time, *fbcolor* displays the current RGB and HSV values on
the terminal, allowing you to record values for later use.

*fbcolor* recognizes two main sets of commands: those which select
which parameter to edit, and those which vary the value of the
selected parameter.

``*r*'', ``*g*'', and ``*b*'' select the red, green, or blue channel
for editing, while ``*h*'', ``*s*'', and ``*v*'' (or ``*i*'') select
the hue, saturation, or value for editing. The ``*/*'' key steps
through the list of parameters in the order given above.

``*+*'' and ``*.*'' both increment the currently selected parameter by
one; ``*-*'' and ``*,*'' both decrement by one; ``*>*'' and ``*<*''
increment and decrement by 16. Parameter values range from 0 to 255
and wrap in both directions.

A ``*?*'' prints a short command summary, and typing ``*q*'',
``*Q*'', ``*<CR>*'', or ``*<LF>*'' exits the program.

== OPTIONS

*-F* _framebuffer_::
Specifies the framebuffer device to use. If not given, the
environment variable *FB_FILE* is used to select the display device
(see *brlcad*(1)). If *FB_FILE* has not been set, the default
device for your system will be used.

*-s* _squaresize_::
Sets both the width and height of the framebuffer window to
_squaresize_ pixels.

*-S* _squaresize_::
Same as *-s*.

*-w* _width_::
Sets the width of the framebuffer window to _width_ pixels.

*-W* _width_::
Same as *-w*.

*-n* _height_::
Sets the height of the framebuffer window to _height_ pixels.

*-N* _height_::
Same as *-n*.

*-h*::
Prints a usage summary and exits.

== EXAMPLES

.Interactively pick colors on the default framebuffer.
....
fbcolor
....

.Use a specific framebuffer device with a 512x512 window.
....
fbcolor -F /dev/fb0 -s 512
....

== SEE ALSO

*brlcad*(1), *fbclear*(1), *fbcmap*(1)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
