= FBFADE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbfade - fade a frame buffer image in or out

== SYNOPSIS

[source]
----
fbfade [-H] [-f input_image_name] [-s input_square_size] [-w input_width] \
     [-n input_height] [-S output_square_size] [-W output_width] [-N output_height] \
     [[-F] output_frame_buffer_name]
----


[[description]]
== DESCRIPTION

*fbfade* gradually displays an image on a frame buffer, one randomly
selected pixel at a time. It requires fast single-pixel write support
for best effect.

If no input image is specified with *-f*, the program fades the
existing frame buffer contents to black (fade out). When an input
image is given, that image is faded in over whatever is currently
displayed.

[[options]]
== OPTIONS

*-H*::
Assumes 1024x1024 pixels for the default input image size instead of
512x512. Explicitly specified sizes override this default. If actual
input is smaller than requested, the actual size is used. If output
size is not specified, the revised input size is used.

*-f* _input_image_name_::
Reads the image to be displayed from the specified frame buffer file,
instead of using a black background (fade out).

*-s* _input_square_size_::
Sets both width and height of the input image.

*-w* _input_width_::
Sets the input image width.

*-n* _input_height_::
Sets the input image height.

*-S* _output_square_size_::
Sets both width and height of the output frame buffer.

*-W* _output_width_::
Sets the output frame buffer width.

*-N* _output_height_::
Sets the output frame buffer height.

*-F* _output_frame_buffer_name_::
Writes to the specified frame buffer instead of the one given by the
*FB_FILE* environment variable (or the default frame buffer). If this
is the last option specified, the *-F* flag is optional.

*-h* or *-?*::
Print usage information and exit.


[[caveat]]
== CAVEAT

*fbfade* works best in conjunction with a frame buffer having very
fast single-pixel access.


[[examples]]
== EXAMPLES

The following shell script produces a slide show by fading each image
in, pausing, then fading to black:

....
fbclear
for i in *.pix
do
    fbfade -f $i
    sleep 15
done
fbfade
....


[[see_also]]
== SEE ALSO

*libfb*(3), *pix*(5)


[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.


[[authors]]
== AUTHORS

Douglas A. Gwyn, BRL/VLD-VMB; Gary S. Moss, BRL/VLD-VMB


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
