= FBFRAME(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbframe - place a colored frame around a framebuffer

== SYNOPSIS

[source]
----
fbframe [-F framebuffer] [-s squaresize] [-S squaresize] [-w width] \
     [-W width] [-n height] [-N height]
----


[[description]]
== DESCRIPTION

*fbframe* draws a single-pixel-wide colored frame around the border
of a framebuffer. The frame is drawn counter-clockwise starting from
the bottom: red along the bottom, green up the right side, blue
across the top, and white down the left side.

This is primarily useful for framebuffer alignment and verifying
display dimensions.

If no size options are given, the dimensions are taken from the
framebuffer. The *-F* option selects a specific framebuffer; if
omitted, the *FB_FILE* environment variable is used (see
*brlcad*(1)).

[[options]]
== OPTIONS

*-F* _framebuffer_::
Specify the framebuffer device. If not provided, the default frame
buffer is used.

*-s* _squaresize_::
*-S* _squaresize_::
Set both the width and height of the frame.

*-w* _width_::
*-W* _width_::
Set the frame width in pixels.

*-n* _height_::
*-N* _height_::
Set the frame height in scanlines.

*-h* or *-?*::
Print usage information and exit.


[[examples]]
== EXAMPLES

Draw a frame on the default framebuffer:

....
fbframe
....

Draw a 1024x1024 frame on a specific framebuffer:

....
fbframe -F /dev/fb0 -s 1024
....


[[see_also]]
== SEE ALSO

*brlcad*(1), *fbgrid*(1)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
