= FBFREE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbfree - free any frame buffer resources

== SYNOPSIS

[source]
----
fbfree [-F framebuffer]
----


[[description]]
== DESCRIPTION

*fbfree* frees resources associated with a frame buffer. Its most
common use is to close down an *fbserv*(1) process and its associated
frame buffer. This command can also be used to free shared memory
segments on supported systems.

This program calls the *fb_free*() routine in *libfb*(3).

[[options]]
== OPTIONS

*-F* _framebuffer_::
Specify the target frame buffer. If not provided, the default frame
buffer is used (often determined by the *FB_FILE* environment
variable).

*-h* or *-?*::
Print usage information and exit.

[[examples]]
== EXAMPLES

Free the default frame buffer:

....
fbfree
....

Free a specific frame buffer:

....
fbfree -F /dev/sgifb0
....


[[see_also]]
== SEE ALSO

*brlcad*(1), *fbclear*(1), *libfb*(3)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
