= FBGRID(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbgrid - draw a grid on a frame buffer

== SYNOPSIS

[source]
----
fbgrid [-c] [-b] [-d] [-o] [-F framebuffer] [-s squaresize] [-S squaresize] \
     [-w width] [-W width] [-n height] [-N height]
----


[[description]]
== DESCRIPTION

*fbgrid* draws a calibration grid pattern on a frame buffer. Three
intensity levels of grid lines are drawn at different spacings, making
it easy to count pixels and verify display geometry.

The default grid pattern is decimal (*-d*), with dark lines every 10
pixels, grey lines every 50 pixels, and white lines every 100 pixels.

If the *FB_FILE* environment variable is set, it selects the display
device (see *brlcad*(1)). If this variable is not set, the default
device for the system is used.

[[options]]
== OPTIONS

*-c*::
Clear the framebuffer to black before drawing the grid.

*-b*::
Use binary spacing: dark lines every 8 pixels, grey lines every 64
pixels, and white lines every 128 pixels.

*-d*::
Use decimal spacing (default): dark lines every 10 pixels, grey lines
every 50 pixels, and white lines every 100 pixels.

*-o*::
Use the old cross grid pattern.

*-F* _framebuffer_::
Specify the framebuffer device. If not provided, the default frame
buffer is used.

*-s* _squaresize_::
*-S* _squaresize_::
Set both the width and height of the grid.

*-w* _width_::
*-W* _width_::
Set the grid width in pixels.

*-n* _height_::
*-N* _height_::
Set the grid height in scanlines.

*-h* or *-?*::
Print usage information and exit.


[[examples]]
== EXAMPLES

Draw a default decimal grid on the default framebuffer:

....
fbgrid
....

Clear the screen and draw a binary grid at 1024x1024:

....
fbgrid -c -b -S 1024
....

Draw a decimal grid on a specific framebuffer:

....
fbgrid -F /dev/fb0 -d
....


[[see_also]]
== SEE ALSO

*brlcad*(1), *fbpoint*(1), *fbzoom*(1), *fbframe*(1)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1986-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
