= FBHELP(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbhelp - provide information on frame buffer selections

== SYNOPSIS

[source]
----
fbhelp [-F framebuffer] [-h]
----


[[description]]
== DESCRIPTION

*fbhelp* displays information about how to select a frame buffer
device, lists all available frame buffer devices compiled into the
*libfb*(3) library, and then opens the currently selected device to
display its detailed help information.

The display device is determined first from the *-F* _framebuffer_
option if given, then from the environment variable __FB_FILE__, or
finally from whatever the default display device is for the system.


[[options]]
== OPTIONS

*-F* _framebuffer_
Explicitly specifies the frame buffer device to query.

*-h* or *-?*
Prints a usage message.


[[examples]]
== EXAMPLES

List available frame buffer devices and show help for the default
device:

....
fbhelp
....

Show help information for a specific frame buffer device:

....
fbhelp -F /dev/sgil
....


[[see_also]]
== SEE ALSO

*libfb*(3), *brlcad*(1)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1988-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
