= FBHELP(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbhelp - describe how to select a frame buffer and list available devices

== SYNOPSIS

[source]
----
fbhelp [-F framebuffer]
----


[[description]]
== DESCRIPTION

*fbhelp* explains how to select a frame buffer display device, lists
every frame buffer interface compiled into the *libdm*(3) library, then
opens the selected device and prints its device-specific help.

The device is chosen first from the *-F* _framebuffer_ option if given,
otherwise from the *FB_FILE* environment variable, and finally from the
built-in default for the system. Most BRL-CAD frame buffer tools, such
as *fb-pix*(1) and *pix-fb*(1), accept the same *-F* convention.


[[options]]
== OPTIONS

*-F* _framebuffer_::
  Specify the frame buffer device to describe rather than using
  *FB_FILE* or the system default.

*-h*::
  Print a usage message. *-?* is accepted as a synonym.


[[examples]]
== EXAMPLES

.List the available frame buffer devices
====
[source,bash]
----
fbhelp
----
Prints the *FB_FILE* selection instructions, the list of frame buffer
interfaces built into this installation (for example, the in-memory and
file-backed devices), and the help text for the default device.
====

.Inspect a specific frame buffer before writing an image to it
====
[source,bash]
----
fbhelp -F /tmp/output.pix
pix-fb -F /tmp/output.pix scene.pix
----
Queries the file-backed (_/tmp/output.pix_) frame buffer to confirm it
is available and learn its capabilities, then uses *pix-fb*(1) to
display a *pix*(5) image on that same device.
====


[[see_also]]
== SEE ALSO

*brlcad*(1), *fb-pix*(1), *pix-fb*(1), *fbclear*(1), *libdm*(3)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
