= FBHELP(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbhelp - provide information on frame buffer selections

== SYNOPSIS

[source]
----
fbhelp [-F framebuffer]
----


[[description]]
== DESCRIPTION

*fbhelp* displays information about the selection of frame buffer devices available to the *libfb*(3) frame buffer library and the whole family of *fb* programs in the BRL-CAD package, for the machine *fbhelp* is run on.

The display device used by a program is taken first from the *-F* _framebuffer_ option if given, else from the environment variable __FB_FILE__, or finally from whatever the default display is for that system. *fbhelp* will tell you what the available choices of frame buffers are, as well as detailed information about any options the currently selected device may have.


[[see_also]]
== SEE ALSO

*libfb*(3), *brlcad*(1)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1988-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
