= FBLINE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbline - draw a colored line on a framebuffer

== SYNOPSIS

[source]
----
fbline [-c] [-F framebuffer] [-s squaresize] [-S squaresize]
       [-w width] [-W width] [-n height] [-N height]
       [-r red] [-g green] [-b blue] x1 y1 x2 y2
----


[[description]]
== DESCRIPTION

*fbline* draws a line on the currently selected framebuffer between
the points (_x1_, _y1_) and (_x2_, _y2_) using a Bresenham line
algorithm. Points that exceed the framebuffer dimensions are silently
clamped to the screen edges.

Use *fbpoint*(1) to interactively determine endpoint coordinates.

The environment variable FB_FILE specifies the current framebuffer;
see *brlcad*(1). Alternatively, the framebuffer may be explicitly
specified with the *-F* flag.

By default, the requested framebuffer size is 512x512 pixels and the
line color is white (255, 255, 255).


[[options]]
== OPTIONS

*-c*
Clear the screen before drawing the line. The default behavior is to
draw the line on the current image without clearing the screen.

*-F* _framebuffer_
Explicitly specifies the framebuffer device.

*-s* _squaresize_ or *-S* _squaresize_
Sets both the width and height of the framebuffer to _squaresize_.

*-w* _width_ or *-W* _width_
Sets the framebuffer width.

*-n* _height_ or *-N* _height_
Sets the framebuffer height.

*-r* _red_
Specifies the red component [0..255] of the line color.

*-g* _green_
Specifies the green component [0..255] of the line color.

*-b* _blue_
Specifies the blue component [0..255] of the line color.

*-h* or *-?*
Prints a usage message.


[[examples]]
== EXAMPLES

Draw a white line from (10, 10) to (400, 400) on the default
framebuffer:

....
fbline 10 10 400 400
....

Draw a green line on a cleared 1024x1024 framebuffer:

....
fbline -s 1024 -c -r 0 -b 0 82 11 300 472
....


[[see_also]]
== SEE ALSO

*brlcad*(1), *fblabel*(1), *fbpoint*(1), *plot3-fb*(1), *libfb*(3), *pix*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1988-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
