= FBPOINT(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbpoint - point at and identify screen coordinates

== SYNOPSIS

[source]
----
fbpoint [-F framebuffer] [-s squaresize] [-S squaresize]
        [-w width] [-W width] [-n height] [-N height]
        [-x [prefix]] [-y [prefix]] [initialx initialy]
----


[[description]]
== DESCRIPTION

*fbpoint* allows you to move a non-destructive cursor around on the
display. As the cursor is moved, *fbpoint* writes the coordinates of
the pixel under the cursor, along with its red, green, and blue
values, on standard error. On exit, it writes the final coordinates
on standard output.

The starting position is center-screen unless optional _initialx_
_initialy_ values are given.

The ``*h*'', ``*j*'', ``*k*'', and ``*l*'' commands step the cursor
one pixel left, down, up, or right respectively. The ``*H*'',
``*J*'', ``*K*'', and ``*L*'' commands (or ``*^B*'', ``*^N*'',
``*^P*'', ``*^F*'') step the cursor in the corresponding directions
in large increments. A ``*?*'' prints a short command summary, and
typing ``*q*'', ``*Q*'', or Enter exits the program.

Using this program with command substitution in a shell script to
interactively grab coordinates is one of its main intended uses.
By default, both x and y coordinates are written to standard output.
If only *-x* or *-y* is given, only that coordinate is written. An
optional _prefix_ string can follow the flag, which will be prepended
to the output coordinate to facilitate passing the result as arguments
to another program.


[[options]]
== OPTIONS

*-F* _framebuffer_
Explicitly specifies the framebuffer device.

*-s* _squaresize_ or *-S* _squaresize_
Sets both the width and height of the framebuffer to _squaresize_.

*-w* _width_ or *-W* _width_
Sets the framebuffer width.

*-n* _height_ or *-N* _height_
Sets the framebuffer height.

*-x* [_prefix_]
Output only the x coordinate on exit. An optional _prefix_ string
is prepended to the coordinate value.

*-y* [_prefix_]
Output only the y coordinate on exit. An optional _prefix_ string
is prepended to the coordinate value.

*-h* or *-?*
Prints a usage message.


[[examples]]
== EXAMPLES

Interactively select a point on the default framebuffer:

....
fbpoint
....

Select a scanline to plot using *fbpoint*:

....
fbscanplot `fbpoint -y`
....

Select an x, y position and pass it as flags to *pix-fb*:

....
pix-fb `fbpoint -x-X -y-Y` file.pix
....


[[see_also]]
== SEE ALSO

*brlcad*(1), *fbgrid*(1), *fbzoom*(1)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1986-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
