= FBSERV(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
fbserv - Frame-buffer Server

== SYNOPSIS

[source]
----
fbserv [-s | S | square_size] [-w | W | width] [-n | N | height] [-p port_number] [-F frame_buffer] [-v] [-T] [-A] [port_number] [frame_buffer]
fbserv [-v] [-F frame_buffer] -I ipc_addr
----


[[description]]
== DESCRIPTION

*fbserv* opens a framebuffer that may be used by BRL-CAD routines accessing a framebuffer. The *-s* (or *-S*) option specifies that a square framebuffer of the specified size (in pixels) is desired. The *-n* (or *-N*) option indicates the framebuffer height. The *-w* (or *-W*) option indicates the framebuffer width. The *-v* option (verbosity) yields more information about the current process.

By default, *fbserv* listens in TCP mode. The *-p* option supplies a TCP port number and the *-F* option indicates what framebuffer device to use. The framebuffer device may be included on the command line without *-F* if it is the last token on the command line. The TCP port may also be specified without *-p*. If *-F* and *-p* are both omitted, the TCP port must be followed by the framebuffer device on the command line.

With *-I* _ipc_addr_, *fbserv* uses an IPC address instead of binding a TCP listener. In this mode, *-p* is ignored.

While *fbserv* is running, clients may connect using either the configured TCP port (TCP mode) or the configured IPC address (IPC mode), depending on how *fbserv* was started. The *fbserv* command may be executed by users at a shell prompt, or it may be used as an inetd remote framebuffer server by specifying *fbserv* as a server program in *inetd.conf*.

[[options]]
== OPTIONS

*-s* _square_size_, *-S* _square_size_::
Request a square framebuffer of size _square_size_ by _square_size_ pixels.

*-w* _width_, *-W* _width_::
Set framebuffer width in pixels.

*-n* _height_, *-N* _height_::
Set framebuffer height in pixels.

*-p* _port_number_::
Set the TCP port number in TCP mode.

*-F* _frame_buffer_::
Set the framebuffer device to open.

*-v*::
Enable verbose status output.

*-T*::
Enable TLS encryption for protocol traffic (requires an OpenSSL-enabled build).

*-A*::
Enable strict authentication. Clients that do not send authentication are rejected.

*-I* _ipc_addr_::
Use IPC transport at _ipc_addr_ instead of TCP.

[[security]]
== SECURITY

Token authentication is supported with or without TLS. If *FBSERV_TOKEN* is set in the environment before starting *fbserv*, that value is used as the required shared token. If *FBSERV_TOKEN* is not set, *fbserv* generates a fresh token at startup and prints it to standard error. Clients must use the same token value when connecting.


[[examples]]
== EXAMPLES


....

fbserv 0 &
....

This command will start a standalone fbserv daemon. Any access of a framebuffer specifying port 0 will result in opening a new framebuffer.


....

fbserv -s 1024 0 /dev/sgil &
....

The above command will open a 1024 X 1024 '/dev/sgil' framebuffer and associate port number 0 with it. Any access of a framebuffer specifying port 0 will use the already opened '/dev/sgil' framebuffer.


....

fbserv -F /dev/wgl -I C:\\Users\\you\\AppData\\Local\\Temp\\brl-fb.sock &
....

This command starts *fbserv* in IPC mode at the specified address. In IPC mode, *-p* is ignored.


....

set FBSERV_TOKEN=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
set FBSERV_TLS=1
fbserv -T -A -p 0 -F /dev/wgl &
rt -F 0 model.g object
....

These commands run *fbserv* in authenticated TLS mode and render to it with *rt*. Use the same *FBSERV_TOKEN* value in both environments. *FBSERV_TLS* requests TLS for client connections when available.


[[see_also]]
== SEE ALSO

*bw-fb*(1), *cell-fb*(1), *cmap-fb*(1), *gif-fb*(1), *pix-fb*(1), *plot3-fb*(1), *polar-fb*(1), *rle-fb*(1), *fbcmap*(1), *fbcmrot*(1), *fbclear*(1), *fbcbars*(1), *fbanin*(1), *fbcolor*(1), *fbfade*(1), *fbframe*(1), *fbfree*(1), *fbgamma*(1), *fbgrid*(1), *fbhelp*(1), *fblabel*(1), *fbline*(1), *fbpoint*(1), *fbscanplot*(1), *fbstretch*(1), *fbzoom*(1)


[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1994-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
