= G-ACAD(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
g-acad - BRL-CAD to Lockheed Martin ACAD converter

== SYNOPSIS

[source]
----
g-acad [-v] [-i] [-x lvl] [-X lvl] [-e error_file] [-D calc_tol] [-a abs_tol] [-r rel_tol] [-n norm_tol] [-P ncpus] [-o ACAD_file] [-h] [-?] database.g object(s)
----

[[description]]
== DESCRIPTION

*g-acad* converts the specified _object(s)_ from a BRL-CAD
_database.g_ file to Lockheed Martin's ACAD file format (formerly
General Dynamics ACAD). This is not related to Autodesk AutoCAD.

[[options]]
== OPTIONS

*-v*::
Verbose output.

*-i*::
Output in inches (default is mm).

*-x* _lvl_::
Set librt debug flag.

*-X* _lvl_::
Set NMG debug flag.

*-e* _error_file_::
Write error messages to _error_file_ instead of standard error.

*-D* _calc_tol_::
Calculation distance tolerance (mm). Vertices closer than this are
merged.

*-a* _abs_tol_::
Absolute tessellation tolerance (mm).

*-r* _rel_tol_::
Relative tessellation tolerance.

*-n* _norm_tol_::
Surface normal tolerance (degrees).

*-P* _ncpus_::
Number of CPUs to use; enables core dumps.

*-o* _ACAD_file_::
Output file (default is stdout).

*-h, -?*::
Print a usage message and exit.

[[examples]]
== EXAMPLES

.Convert a BRL-CAD object to ACAD format
====
[source,bash]
----
$ g-acad -o sample.ACAD sample.g sample_object
----
====

.Convert with tight tolerances in inches
====
[source,bash]
----
$ g-acad -i -a 0.1 -r 0.01 -o hull.ACAD vehicle.g hull
----
====

[[see_also]]
== SEE ALSO

*brlcad*(1)

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1997-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
