= G-DXF(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
g-dxf - BRL-CAD to AutoCAD DXF converter

== SYNOPSIS

[source]
----
g-dxf [-v] [-i] [-p] [-x lvl] [-X lvl] [-D calc_tol] [-a abs_tol] [-r rel_tol] [-n norm_tol] [-P ncpus] [-o DXF_file] [-h] [-?] database.g object(s)
----

[[description]]
== DESCRIPTION

*g-dxf* converts the specified _object(s)_ from a BRL-CAD
_database.g_ file to AutoCAD DXF format. By default, output uses
3DFACE entities; use *-p* for POLYFACE MESH entities instead.

[[options]]
== OPTIONS

*-v*::
Verbose output.

*-i*::
Output in inches (default is mm).

*-p*::
Output POLYFACE MESH entities instead of 3DFACE entities.

*-x* _lvl_::
Set librt debug flag.

*-X* _lvl_::
Set NMG debug flag.

*-D* _calc_tol_::
Calculation distance tolerance (mm). Vertices closer than this are
merged.

*-a* _abs_tol_::
Absolute tessellation tolerance (mm).

*-r* _rel_tol_::
Relative tessellation tolerance.

*-n* _norm_tol_::
Surface normal tolerance (degrees).

*-P* _ncpus_::
Number of CPUs (enables core dumps; currently disabled).

*-o* _DXF_file_::
Output file (default is stdout).

*-h, -?*::
Print a usage message and exit.

[[examples]]
== EXAMPLES

.Convert a BRL-CAD object to DXF
====
[source,bash]
----
$ g-dxf -o model.dxf sample.g component
----
====

.Convert using POLYFACE MESH entities in inches
====
[source,bash]
----
$ g-dxf -p -i -a 0.5 -o model.dxf sample.g turret
----
====

[[see_also]]
== SEE ALSO

*dxf-g*(1)

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2003-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
