= G-EGG(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

g-egg - Panda3D Translator (BRL-CAD to EGG)

== SYNOPSIS

*g-egg* [-v89] [-x _rt_debug_] [-X _nmg_debug_] [-a _abs_tol_] [-r _rel_tol_] [-n _norm_tol_] [-D _dist_tol_] [-o _egg_file_] [-P _ncpu_] _database.g_ _object(s)_

== DESCRIPTION

*g-egg* converts the specified geometry _object(s)_ from a BRL-CAD database _database.g_ to a Panda3D `.egg` file.

== OPTIONS

*-a* _abs_tol_::
	Specify absolute tessellation tolerance (in mm).

*-r* _rel_tol_::
	Specify relative tessellation tolerance. The default is 0.01.

*-n* _norm_tol_::
	Specify surface normal tessellation tolerance.

*-o* _egg_file_::
	Specify the output file name. If not specified, the output is written to standard output.

*-v*::
	Verbose output (printed to standard error).

*-P* _ncpu_::
	Specify the number of CPUs to use.

*-x* _rt_debug_::
	Specify an RT debug flag (hexadecimal format).

*-X* _nmg_debug_::
	Specify an NMG debug flag (hexadecimal format).

*-D* _dist_tol_::
	Specify calculation distance tolerance (in mm) used when checking if vertices are coincident.

*-8*::
	Use the marching cubes algorithm for facetization.

*-9*::
	Use the "bottess" algorithm for facetization.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Convert a BRL-CAD object to a Panda3D EGG file
[source,bash]
----
g-egg -o sample.egg sample.g sample_object
----

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
