= G-IGES(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

g-iges - IGES Translator (BRL-CAD to IGES)

== SYNOPSIS

*g-iges* [-f | -t | -m] [-v] [-s] [-x _rt_debug_] [-X _nmg_debug_] [-a _abs_tol_] [-r _rel_tol_] [-n _norm_tol_] [-d _dist_tol_] [-P _ncpu_] [-o _output_file_or_directory_] _database.g_ _object(s)_

== DESCRIPTION

*g-iges* converts the specified geometry _object(s)_ from a BRL-CAD database _database.g_ to an IGES version 5.1 file.

If none of the *-f*, *-t*, or *-m* options are selected, the default output is a CSG IGES file. In this case, all regions are written to the IGES file as Boolean trees with solids represented by their IGES CSG equivalents. When no IGES CSG equivalent is available, the BRL-CAD solid is tessellated (using the provided tolerances), and a boundary representation (B-Rep) object is written for that solid.

== OPTIONS

*-f*::
	Select a B-Rep IGES file output consisting of only Manifold Solid B-Rep Objects. All CSG solids in the specified objects are tessellated to produce faceted B-Rep objects, and then Boolean operations are evaluated for each region. Individual regions are written to the IGES file as individual B-Rep objects. The accuracy of the tessellation may be controlled using the *-a*, *-r*, and *-n* options.

*-t*::
	Produce an IGES file consisting of only trimmed NURBS. The trimmed NURBS are planar surfaces derived from the facets of the tessellated and Boolean-evaluated regions. The resulting file is suitable for import into systems like Pro/ENGINEER.

*-m*::
	Produce multiple IGES files (one for each converted region). This option implies *-t*. When using *-m*, the argument to *-o* must specify a directory where the generated IGES files will be stored.

*-s*::
	Output all facets in B-Rep objects as planar NURBS surfaces.

*-a* _abs_tol_::
	Set the absolute tessellation tolerance (in mm).

*-r* _rel_tol_::
	Set the relative (to object size) tessellation tolerance. The default is 0.01.

*-n* _norm_tol_::
	Set the surface normal tessellation tolerance.

*-d* _dist_tol_::
	Set the minimum distance tolerance (in mm) between distinct points. The default is 0.0005.

*-v*::
	Request verbose debugging output.

*-o* _output_file_or_directory_::
	Specify the output file path, or the output directory when using the *-m* option. If not specified, the output is written to standard output.

*-P* _ncpu_::
	Specify the number of processors to use.

*-x* _rt_debug_::
	Set the librt raytrace debug flag (hexadecimal format). See `raytrace.h` for values.

*-X* _nmg_debug_::
	Set the NMG debug flag (hexadecimal format). See `nmg.h` for values.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Convert a BRL-CAD object to a B-Rep IGES file
[source,bash]
----
g-iges -f -o sample.iges sample.g object1
----

== SEE ALSO

*iges-g*(1)

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1993-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
