= G-PLY(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

g-ply - Stanford PLY exporter (BRL-CAD to PLY)

== SYNOPSIS

*g-ply* [-v] [-s] [-x _rt_debug_] [-X _nmg_debug_] [-a _abs_tol_] [-r _rel_tol_] [-n _norm_tol_] [-t _type_] [-D _dist_tol_] -o _output_file_name_ _database.g_ _object(s)_...

== DESCRIPTION

*g-ply* converts the specified _object(s)_ from a BRL-CAD database _database.g_ to the Stanford PLY file format.

== OPTIONS

*-o* _output_file_name_::
	Specify the output file name. This option is required.

*-s*::
	Write out one object per file instead of merging individual objects into a single PLY file.

*-t* _type_::
	Specify the type of PLY file to write. The values can be:
	* `asc`::: ASCII format
	* `le`::: Binary little endian format
	* `be`::: Binary big endian format

*-D* _dist_tol_::
	Specify calculation distance tolerance (in mm) used when checking if vertices are coincident. The default is 0.0005.

*-a* _abs_tol_::
	Specify absolute tessellation tolerance (in mm).

*-r* _rel_tol_::
	Specify relative tessellation tolerance. The default is 0.01.

*-n* _norm_tol_::
	Specify surface normal tessellation tolerance.

*-x* _rt_debug_::
	Specify an RT debug flag (hexadecimal format).

*-X* _nmg_debug_::
	Specify an NMG debug flag (hexadecimal format).

*-v*::
	Enable verbose output.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Convert a BRL-CAD object to a PLY file
[source,bash]
----
g-ply -o sample.ply sample.g sample_object
----

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2003-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
