= G-RAW(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

g-raw - RAW Translator (BRL-CAD to RAW)

== SYNOPSIS

*g-raw* [-v] [-i] [-8] [-x _rt_debug_] [-X _nmg_debug_] [-a _abs_tol_] [-r _rel_tol_] [-n _norm_tol_] [-D _dist_tol_] [-o _output_file_ | -m _output_directory_] _database.g_ _object(s)_...

== DESCRIPTION

*g-raw* converts the specified _object(s)_ from a BRL-CAD database _database.g_ to the RAW triangle format.

== OPTIONS

*-o* _output_file_::
	Specify the output file name (default is standard output).

*-m* _output_directory_::
	Specify a directory for output files. Each region converted is written to a separate file within this directory. File names are constructed from the region's full path name (replacing "/" with "@", and spaces/periods with "_"). The *-o* and *-m* options are mutually exclusive.

*-i*::
	Use inches as the output units (the default is millimeters).

*-8*::
	Facetize using the marching cubes algorithm.

*-D* _dist_tol_::
	Specify calculation distance tolerance (in mm) used when checking if vertices are coincident. The default is 0.0005.

*-a* _abs_tol_::
	Specify absolute tessellation tolerance (in mm).

*-r* _rel_tol_::
	Specify relative tessellation tolerance. The default is 0.01.

*-n* _norm_tol_::
	Specify surface normal tessellation tolerance.

*-x* _rt_debug_::
	Specify an RT debug flag (hexadecimal format).

*-X* _nmg_debug_::
	Specify an NMG debug flag (hexadecimal format).

*-v*::
	Enable verbose output.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Convert a BRL-CAD object to a RAW file
[source,bash]
----
g-raw -o sample.raw sample.g sample_object
----

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2013-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
