= G-SHELL-RECT(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

g-shell-rect - Produce triangulated shell from BRL-CAD model

== SYNOPSIS

*g-shell-rect* [-bi] [-a _rpp_args_] [-R _edge_tol_] [-p _plotfile_] [-X _nmg_debug_] [-d _debug_level_] [-n] [-g _cell_size_] -o _brlcad_output_file_ _database.g_ _object(s)_

== DESCRIPTION

*g-shell-rect* converts the specified _object(s)_ from a BRL-CAD database _database.g_ to a single NMG solid or BOT using raytracing.

Rays are fired in a uniform grid. The direction for the first set of rays is chosen by calculating the presented area of the bounding box of the _object(s)_ and selecting the direction with the largest area. The user may override this by specifying a desired initial ray direction using the *-i* option.

The initial shell is constructed using only the first and last intersections with the _object(s)_. This typically results in some rather large faces with normals at right angles to the ray direction. Unless the *-n* option is specified, these faces are then subdivided (according to the *-g* _cell_size_) and additional rays fired from the other two directions are used to refine their shape. The resulting geometry is written to the specified _brlcad_output_file_.

== OPTIONS

*-o* _brlcad_output_file_::
	Specifies the name of the BRL-CAD geometry file to create. This option is required.

*-g* _cell_size_::
	Specify the dimensions (in millimeters) of the grid spacing. The default is 50.

*-i* _initial_ray_dir_::
	Specify the initial ray direction. Valid values are `X`, `Y`, or `Z`. The best results are usually obtained by raytracing in the direction that produces the most hits first.

*-d* _debug_level_::
	Set the debugging level. Higher values produce more debugging information.

*-n*::
	Suppress the refinement stage (firing rays from the secondary and tertiary axis directions).

*-b*::
	Output a BOT (Bag of Triangles) rather than an NMG (Non-Manifold Geometry).

*-a* _rpp_args_::
	Add a bounding box (RPP) for refining.

*-R* _edge_tol_::
	Specify the edge tolerance for refinement.

*-p* _plotfile_::
	Specify a plotfile for plotting edge-breaking steps.

*-X* _nmg_debug_::
	Specify NMG debug flags (hexadecimal format).

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Produce a shell from a BRL-CAD object
[source,bash]
----
g-shell-rect -o shell.g sample.g sample_object
----

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1998-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
