= G-STEP(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

g-step - STEP Translator/Exporter (BRL-CAD to STEP AP203)

== SYNOPSIS

*g-step* -o _output_file.stp_ _database.g_ [_object(s)_]

== DESCRIPTION

*g-step* converts the specified objects from a BRL-CAD database _database.g_ to a STEP AP203 file _output_file.stp_.

BRL-CAD's CSG models are converted to the STEP NURBS Boundary Representation format. Note that Boolean operations are not supported in AP203.

== OPTIONS

*-o* _output_file.stp_::
	Specify the output STEP file path. This option is required. Note that *g-step* will refuse to run if the output file already exists.

== EXAMPLES

.Export all geometry from a database to a STEP file
[source,bash]
----
g-step -o m35.stp m35.g
----

.Export specific parts from a database
[source,bash]
----
g-step -o m35.stp m35.g cab suspension
----

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1993-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
