= G-VAR(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

g-var - Produce (OpenGL) Vertex Arrays from BOT BRL-CAD geometry

== SYNOPSIS

*g-var* [-v] [-y] [-s _scale_] [-f] [-o _outfile_] _infile.g_ _object_

== DESCRIPTION

*g-var* writes the Bag of Triangles (BOT) primitives of the specified _object_ in a binary vertex array format to _outfile_ or to standard output.

== OPTIONS

*-v*::
	Request verbose output.

*-y*::
	Transform the coordinate system from XYZ (Z-up) to XZY (Y-up).

*-s* _scale_::
	Scale the output geometry by the specified factor. By default, the scale factor is 0.001 (converting meters to millimeters).

*-f*::
	Flip face normals. This changes both the vertex order and the output normal directions.

*-o* _outfile_::
	Specify the output file name. If not specified, the output is written to standard output.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Export a BOT object to a vertex array file
[source,bash]
----
g-var -o sample.mesh sample.g sample_object
----

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

Prasad Silva

== COPYRIGHT

This software is Copyright (c) 2006-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
