= G-VAR(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME
g-var - Produce (OpenGL) Vertex Arrays from BOT BRL-CAD geometry

== SYNOPSIS

[source]
----
g-var [-v] [-y] [-s scale] [-f] [-o outfile] infile.g object
----


[[description]]
== DESCRIPTION

*g-var* writes the bag of triangle (BOT) primitives of the specified _object_ in a binary array format to _outfile_ or to _stdout_.


[[options]]
== OPTIONS


*-v*::
Request verbose output.


*-y*::
Transform the coordinate system from xyz to xzy.


*-s* **scale**::
Scale the output geometry by factor _scale_. By default the scale factor is 0.001 (standard transformation from meters to millimeters).


*-f*::
Flip face normals. This changes both the vertex order and the output normals.


*-o* _outfile_::
The output will be written to _outfile_. By default the output is written to stdout.




[[file_format]]
== FILE FORMAT

_TODO_


[[example]]
== EXAMPLE


----

$ g-var -o sample.mesh sample.g sample_object
----


[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.


[[author]]
== AUTHOR

Prasad Silva


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2006-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
