= G-X3D(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

g-x3d - Perform Boolean evaluations to produce an X3D facetted model

== SYNOPSIS

*g-x3d* [-v] [-d _calc_dist_tol_] [-a _abs_tess_tol_] [-n _norm_tess_tol_] [-r _rel_tess_tol_] [-x _librt_debug_flag_] [-X _NMG_debug_flag_] [-u _units_name_] [-P _ncpu_] [-o _outfile_] _infile.g_ _object(s)_

== DESCRIPTION

*g-x3d* performs the Boolean operations specified in BRL-CAD database regions and writes the resulting geometry in X3D format to _outfile_ (or to standard output if *-o* is not used).

== OPTIONS

*-o* _outfile_::
	Specify the output file name. If not specified, the output is written to standard output.

*-v*::
	Verbose output.

*-d* _calc_dist_tol_::
	Specify calculation distance tolerance (in mm) used to distinguish neighboring vertices. The default value is 0.005.

*-a* _abs_tess_tol_::
	Specify absolute tessellation tolerance (in mm).

*-n* _norm_tess_tol_::
	Specify surface normal tessellation tolerance (in degrees).

*-r* _rel_tess_tol_::
	Specify relative tessellation tolerance (relative to primitive solid size).

*-x* _librt_debug_flag_::
	Set debug flags for `librt` (hexadecimal format). See `raytrace.h` for values.

*-X* _NMG_debug_flag_::
	Set NMG debug flags (hexadecimal format). See `nmg.h` for values.

*-u* _units_name_::
	Specify units for the resulting X3D file. The default is mm. Accepts any units name supported by MGED.

*-P* _ncpu_::
	Specify the number of processors to use. The default is 1.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Convert a BRL-CAD object to an X3D file
[source,bash]
----
g-x3d -o shell.x3d sample.g sample_object
----

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

Robert Parker (The SURVICE Engineering Co., Aberdeen, MD)

== COPYRIGHT

This software is Copyright (c) 2002-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
