= G2ASC(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

g2asc - convert a BRL-CAD mged geometry database from binary to ASCII form.

== SYNOPSIS

*g2asc* [-h] [_input.g_ _output.asc_]

== DESCRIPTION

*g2asc* converts BRL-CAD geometry databases from binary format to ASCII format.

The binary representation of a BRL-CAD database is inherently machine-dependent for older "v4" formats. *g2asc* and its converse, *asc2g*(1), are simple filters which convert between the binary form and an ASCII representation.

While the modern "v5" binary format is machine-independent and does not require conversion for transfer, *g2asc* can still be used to convert "v5" databases to a Tcl-script ASCII format (Tcl command sequence) or "v4" databases to the older one-line record ASCII format.

== OPTIONS

*-h*::
*--help*::
*-?*::
	Print a usage summary and exit.

== EXAMPLES

.Convert a binary database to an ASCII file
[source,bash]
----
g2asc file.g file.asc
----

== SEE ALSO

*asc2g*(1), *brlcad*(1), *mged*(1)

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
