= GASTANK(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
gastank - Creates a BRL-CAD .g file containing gas tanks.

== SYNOPSIS

[source]
----
gastank [options]...
----


[[description]]
== DESCRIPTION

*gastank* creates a BRL-CAD database containing solid gas tanks with rounded corners and edges. Up to 256 gas tanks of the same size may be generated per run. These models are appropriate for millimeter-wave signature analysis, but not for infrared or vulnerability analysis. *gastank* uses libwdb to create the database file, with each tank composed of three arb8s, eight spheres, and twelve cylinders.

If run without arguments, the program enters interactive mode and prompts for all required parameters. Alternatively, options may be specified directly on the command line.


[[options]]
== OPTIONS


*-f* _name.g_::
BRL-CAD file name.


*-n #*::
The number of gas tanks to be created (must be less than or equal to 256).


*-H #*::
Height of gas tank in millimeters.


*-w #*::
Width of gas tank in millimeters.


*-d #*::
Depth of gas tank in millimeters.


*-r #*::
Radius of the corner in millimeters.




[[examples]]
== EXAMPLES

.Interactive *gastank* Session
[example]
====



....

$ gastank

This program constructs a solid gas tank with all
edges and corners rounded.

Enter the mged file to be created (25 char max).
	gastank.g
Enter the number of gas tanks to create (26 max).
	3
Enter the height, width, and depth of the gas tank (units mm).
	300 200 400
Enter the radius of the corners (units mm).
	30

mged file:  gastank.g
height of gas tank:  300.000000 mm
width of gas tank:  200.000000 mm
depth of gas tank:  400.000000 mm
radius of corner:  30.000000 mm
number of gas tanks:  3
   
....



====

.Single-Line *gastank* Command
[example]
====
**gastank -fgastank.g -n3 -H300 -w200 -d400 -r30**

====

Both of these examples produce the same result - 3 gas tanks with a height of 300mm, a width of 200mm, a depth of 400mm, and a radius for the corner of 30mm. The BRL-CAD database file created in each case is gastank.g


[[author]]
== AUTHOR

Susan A. Coates


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2005-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[see_also]]
== SEE ALSO

bolt(1), handle(1), window(1), window_frame(1)


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
