= GENCOLOR(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

gencolor - output a repeated pattern of byte values

== SYNOPSIS

*gencolor* [-p | -b] [-r _repeat_count_] [-s _squaresize_ | -S _squaresize_] [-w _width_ | -W _width_] [-n _height_ | -N _height_] [_val1_ ... _valN_] > _output_file_

== DESCRIPTION

*gencolor* repeats a pattern of up to 8192 8-bit values to its standard output. The values (ranging from 0 to 255) are read either from the command line arguments or in binary format from standard input. If no values are supplied, a default single value of 0 (black) is used.

Note that *gencolor* will refuse to write its output directly to a terminal; you must redirect the output to a file or pipe it to another command.

== OPTIONS

*-p*::
	Specify a `.pix` file output format (3 bytes per pixel). This is the default.

*-b*::
	Specify a `.bw` file output format (1 byte per pixel).

*-r* _repeat_count_::
	Specify the number of times to repeat the given pattern. The default is infinity (unless another option that specifies dimensions is used).

*-w* _width_::
*-W* _width_::
	Specify the width of the image. The default is 512.

*-n* _height_::
*-N* _height_::
	Specify the height of the image. The default is 512.

*-s* _squaresize_::
*-S* _squaresize_::
	Set both the width and height of the image to the specified value.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Output a 512-pixel green pattern (0 255 0) to a file
[source,bash]
----
gencolor -r 512 0 255 0 > green.pix
----

.Generate a green pattern using standard input
[source,bash]
----
gencolor -r 1 0 255 0 | gencolor -r 512 > green.pix
----

== SEE ALSO

*brlcad*(1), *pix*(5), *bw*(5)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
