= GIF-FB(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

gif-fb - display GIF file on frame buffer

== SYNOPSIS

*gif-fb* [-c] [-o] [-v] [-z] [-F _frame_buffer_name_] [-i _image_number_] [_GIF_file_name_]

== DESCRIPTION

*gif-fb* displays CompuServe GIF (Graphics Interchange Format) images on a frame buffer. If no _GIF_file_name_ is specified, the input is read from standard input.

== OPTIONS

*-F* _frame_buffer_name_::
	Output to the specified frame buffer. If not specified, the frame buffer specified by the *FB_FILE* environment variable (or the default system frame buffer) is used. The frame buffer size requested will match the screen size specified in the GIF file.

*-c*::
	Use 8 bits per channel for color maps in the GIF file, overriding the color resolution specified in the file. (Some non-standard GIF implementations require this flag).

*-i* _image_number_::
	Display only the specified image (1-indexed), rather than displaying all images sequentially as standard multi-image GIF animation would do.

*-o*::
	Overlay mode. Skip the initial clearing of the frame buffer to the background color specified in the GIF file.

*-v*::
	Verbose mode. Print information about the GIF images on the standard error output.

*-z*::
	Zoom mode. Use the zoom capability of the frame buffer to enlarge the image as much as possible while maintaining a square pixel aspect ratio.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Display a GIF file on the default frame buffer
[source,bash]
----
gif-fb image.gif
----

.Display the second image of a multi-image GIF file in overlay mode
[source,bash]
----
gif-fb -i 2 -o image.gif
----

== SEE ALSO

*libfb*(3)

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

Douglas A. Gwyn

== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
