= GIF2FB(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

gif2fb - display GIF file on frame buffer

== SYNOPSIS

*gif2fb* [-H] [-v] [-F _frame_buffer_name_] [_GIF_file_name_]

== DESCRIPTION

*gif2fb* displays CompuServe GIF (Graphics Interchange Format) images on a frame buffer. If no _GIF_file_name_ is specified, it reads from standard input.

== OPTIONS

*-F* _frame_buffer_name_::
	Outputs to the specified frame buffer instead of the one specified by the *FB_FILE* environment variable (or the default system frame buffer). The requested frame buffer size will match the GIF image size.

*-H*::
	Print the GIF screen dimensions (width and height) to standard error and exit.

*-v*::
	Verbose mode. Print additional information about the GIF file structure on standard error.

*-h*::
*-?*::
	Print the usage message and exit.

== EXAMPLES

.Display a GIF image on the default frame buffer
[source,bash]
----
gif2fb image.gif
----

.Print dimensions of a GIF file
[source,bash]
----
gif2fb -H image.gif
----

== SEE ALSO

*gif-fb*(1), *libfb*(3)

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

Christopher T. Johnson

== COPYRIGHT

This software is Copyright (c) 1994-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
