= GIF2FB(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME

gif2fb - display a GIF image on a frame buffer

== SYNOPSIS

[source]
----
gif2fb [-H] [-v] [-F _frame_buffer_] [_gif_file_]
----


[[description]]
== DESCRIPTION

*gif2fb* reads a CompuServe GIF (Graphics Interchange Format) image and
displays its first picture on a frame buffer.  The GIF data may contain
1, 2, 4, or 8 bit deep pictures with one or more color maps; *gif2fb*
selects the appropriate color map and decodes the LZW-compressed image,
honoring GIF interlacing.  The frame buffer is opened at the size of the
embedded image.

If no _gif_file_ is given, the image is read from standard input (use the
shell '<' redirection construct).

[[options]]
== OPTIONS

*-F* _frame_buffer_::
  Display on the specified frame buffer rather than the one named by the
  *FB_FILE* environment variable (or the default system frame buffer).

*-H*::
  Print the GIF screen dimensions to standard error in the form
  "-w_width_ -n_height_" and exit without displaying the image.  The
  output is suitable for passing as arguments to other BRL-CAD frame
  buffer tools.

*-v*::
  Verbose.  Print details of the GIF header, image header, and code
  sizes to standard error.

*-h* | *-?*::
  Print a usage message and exit.

[[examples]]
== EXAMPLES

.Report the dimensions of a GIF image
====
[source,bash]
----
gif2fb -H image.gif
----
With *-H*, *gif2fb* prints the image dimensions to standard error as
"-w_width_ -n_height_" and exits without displaying the image.  The
reported dimensions can be used to size a matching frame buffer with
tools such as *fbserv*(1) or *pixautosize*(1).
====

.Decode a GIF piped from standard input
====
[source,bash]
----
gif2fb -v -F /dev/X < image.gif
----
Reads the GIF from standard input and displays it on frame buffer
/dev/X while printing header diagnostics, useful for inspecting an
image produced earlier in a pipeline.
====

[[see_also]]
== SEE ALSO

*brlcad*(1), *gif-fb*(1), *pix-fb*(1), *png-fb*(1)

[[diagnostics]]
== DIAGNOSTICS

Error messages are intended to be self-explanatory.

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1994-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
