= HALFTONE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

halftone - translate a black and white (BW) image to a halftoned BW image

== SYNOPSIS

*halftone* [-R] [-S] [-a] [-s _squarefilesize_] [-w _file_width_] [-n _file_height_] [-B _contrast_] [-I _Number_Intensity_Levels_] [-M _Method_] [-T _x1 y1 x2 y2 ..._] [-D _debug_level_] [_file.bw_]

== DESCRIPTION

*halftone* reads a black and white image in *bw*(5) format from the specified file (or from standard input if no file is given) and reduces the number of intensity levels from 256 to a smaller number (default is 2). It applies dithering to preserve visual detail and shading info as much as possible.

== OPTIONS

*-a*::
	Enable automatic input file sizing based on the file name or size. Note that automatic sizing cannot be used with pipes or standard input.

*-s* _squarefilesize_::
	Set both the width and height of the input image to the specified number of pixels.

*-w* _file_width_::
	Specify the width of the input image in pixels. The default is 512.

*-n* _file_height_::
	Specify the height of the input image in scanlines. The default is 512.

*-B* _contrast_::
	Specify a floating-point value to be used as the beta coefficient for an edge sharpening algorithm. The default is 0.0, which disables edge sharpening.

*-I* _Number_Intensity_Levels_::
	Specify the number of output intensity levels to use. The default is 2 (black/white, 1-bit), and the maximum is 256.

*-M* _Method_::
	Specify the halftoning method to use. The methods are:
	* *0*:: Floyd-Steinberg error diffusion (default)
	* *1*:: 45-degree classical clustered halftone screen
	* *2*:: Simple thresholding dither
	* *3*:: 0-degree dispersed halftone screen

*-R*::
	Add random noise to the dither threshold. This can sometimes improve the appearance of the output image by breaking up repeating patterns.

*-S*::
	Use a serpentine scan line path (reversing direction every other row) instead of a standard left-to-right scan. This option is only valid when using Floyd-Steinberg error diffusion (*-M 0*).

*-T* _x1 y1 x2 y2 ..._::
	Define a tone scale mapping curve using coordinate pairs (in the range 0 to 255). The curve interpolates intermediate points using cubic splines to map input pixels to output intensities. The default curve is equivalent to `-T 0 0 128 128 255 255`.

*-D* _debug_level_::
	Set the debug level. Setting this to 9 outputs all debugging messages.

*-h*::
*-?*::
	Print usage information and exit.

== FORMAT

A *bw*(5) file contains sequences of pixels. Each pixel is stored as one *unsigned char*. The first pixel in a _bw_ file is the lower left corner of the image. The pixels proceed from left-to-right across each scanline, with scanlines being written from the bottom to the top of the image.

The output from *halftone* is scaled so that each intensity level is output as 255 / (Levels - 1) * value.

== EXAMPLES

.Convert a 512x512 BW image to a binary halftoned image using Floyd-Steinberg diffusion
[source,bash]
----
halftone -M 0 < input.bw > output.bw
----

.Convert a 1024x768 BW image using classical halftone screen with 4 intensity levels
[source,bash]
----
halftone -w 1024 -n 768 -M 1 -I 4 input.bw > output.bw
----

== SEE ALSO

*rt*(1), *pix-bw*(1), *bw*(5), *bw-fb*(1)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1990-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
