= ICV(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

icv - convert, compare, and display information for various image formats

== SYNOPSIS

*icv* [-w _width_] [-n _height_] [--input-format _fmt_] [--output-format _fmt_] [-i _input_file_] [-o _output_file_] [_input_file_] [_output_file_]

*icv* info _file_ [_file_ ...]

*icv* diff [options] _img1_ _img2_

== DESCRIPTION

Without a subcommand, *icv* acts as an image format converter, reading the input image and writing it to the output file. Image formats are auto-detected based on file extensions unless overridden.

=== Supported Formats

[cols="2*"]
|===
|Format |Extension

|Black and White (Grayscale)
|bw

|Double Precision Pixel (R/G/B/A double)
|dpix

|Pixel Sequence (R/G/B unsigned char)
|pix

|Portable Network Graphics
|png

|Portable Pixmap
|ppm
|===

=== Subcommands

*info*::
	Report the width, height, format, number of channels, color space, and any embedded render information (like the database and objects used to render it) for the specified image file(s).

*diff*::
	Compare two images and report pixel differences. By default, with no output file specified, a raw PIX difference image is written to standard output.

== OPTIONS

=== Conversion Options

*-i* _file_, *--input* _file_::
	Specify the input file name. If not specified, the first positional argument is used.

*-o* _file_, *--output* _file_::
	Specify the output file name. If not specified, the second positional argument is used.

*-w* _width_, *--width* _width_::
	Specify the width of the input image. Required for raw formats (like PIX and BW) that do not encode dimensional information, unless the size can be automatically deduced from the file size.

*-n* _height_, *--height* _height_::
	Specify the height of the input image. Required for raw formats (like PIX and BW) that do not encode dimensional information.

*--input-format* _fmt_::
	Explicitly set the input image format (e.g., `png`, `pix`, `bw`).

*--output-format* _fmt_::
	Explicitly set the output image format.

*-h*, *--help*::
*-?*::
	Print conversion help and exit.

=== Diff Subcommand Options

*-o* _file_, *--output* _file_::
	Specify a file path to save the diff image output.

*--output-format* _format_::
	Explicitly set the format of the output diff image.

*--format-img1* _format_::
	Explicitly set the format of the first input image.

*--format-img2* _format_::
	Explicitly set the format of the second input image.

*--width-img1* _#_::
	Specify the width of the first input image (raw formats only).

*--height-img1* _#_::
	Specify the height of the first input image (raw formats only).

*--width-img2* _#_::
	Specify the width of the second input image (raw formats only).

*--height-img2* _#_::
	Specify the height of the second input image (raw formats only).

*-h*, *--help*::
*-?*::
	Print diff subcommand help and exit.

== EXAMPLES

.Convert a PIX file to a PNG file (specifying dimensions)
[source,bash]
----
icv -w 1024 -n 512 input.pix output.png
----

.Get information about a PNG image
[source,bash]
----
icv info model.png
----

.Compare two PNG images and write the diff image to output.png
[source,bash]
----
icv diff -o output.png image1.png image2.png
----

.Compare two raw PIX images specifying different dimensions for each
[source,bash]
----
icv diff --width-img1 512 --height-img1 512 --width-img2 1024 --height-img2 1024 img1.pix img2.pix
----

== SEE ALSO

*pix*(5), *bw*(5), *pixdiff*(1)

== AUTHOR

Clifford Yapp

== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
