= IGES-G(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: User Commands

== NAME

iges-g - IGES Translator (IGES CSG to BRL-CAD)

== SYNOPSIS

*iges-g* [-3] [-d] [-n] [-t] [-p] [-o _database.g_] [-N _solid_name_] [-x _rt_debug_flag_] [-X _NMG_debug_flag_] _file.iges_

== DESCRIPTION

*iges-g* converts the specified _file.iges_ to a BRL-CAD _database.g_ file. The input IGES file is expected to conform to IGES 5.1.

Without any of the flags *-3*, *-d*, *-n*, or *-t*, the default behavior is to convert all IGES CSG and planar face BREP objects to their BRL-CAD equivalents. Most conversions are exact, with some approximations for solids of revolution and solids of linear extrusion, which are approximated as BRL-CAD cone series and polysolids respectively. Planar faced IGES BREP objects are converted to NMG structures or BOT solids.

== OPTIONS

*-3*::
	Convert IGES drawings to BRL-CAD NMG drawings without performing the final projection into 2D space. This can produce 3D drawings if the source drawings were created from a 3D model.

*-d*::
	Convert IGES drawings to BRL-CAD NMG objects. The resulting objects will be 2D drawings rather than 3D solids.

*-n*::
	Combine all rational B-spline surfaces in the IGES file into a single BRL-CAD spline solid.

*-t*::
	Convert all trimmed surfaces in the IGES file into a single BRL-CAD NMG solid.

*-p*::
	Convert BREP objects to NMG solids rather than the default behavior of converting them to BOT solids.

*-o* _database.g_::
	Specify the output BRL-CAD database file name.

*-N* _solid_name_::
	Specify a name for the single solid created under the *-n* or *-t* options. If not specified, the default name "all" (or a unique variation of it) is used. This option is ignored if neither *-n* nor *-t* is used.

*-x* _rt_debug_flag_::
	Specify a debug flag (in hexadecimal format) for the raytrace (`rt`) library routines. See _raytrace.h_ for details.

*-X* _NMG_debug_flag_::
	Specify a debug flag (in hexadecimal format) for NMG routines. See _nmg.h_ for details.

== EXAMPLES

.Convert an IGES file to BRL-CAD database with default settings
[source,bash]
----
iges-g -o sample.g sample.iges
----

.Convert trimmed surfaces from an IGES file into a single BRL-CAD solid named 'part1'
[source,bash]
----
iges-g -t -N part1 -o parts.g sample.iges
----

== SEE ALSO

_The Initial Graphics Exchange Specification (IGES) Version 5.1_, IGES/PDES Organization, September 1991.

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHORS

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1991-2026 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
