= ISTATS(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
istats - compute basic statistics of a stream of short integers

== SYNOPSIS

[source]
----
istats [-h] [file]
----


[[description]]
== DESCRIPTION

*istats* reads a stream of 16-bit signed short integers and computes
basic statistics over the data, writing a human-readable summary to
standard output. Input is read from the named _file_ if one is given,
otherwise from standard input.

The reported statistics are the number of values (Num), the minimum
(Min) and maximum (Max) values, the sum (Sum), the arithmetic mean
(Mean), and the sample standard deviation (SStdev).

It is the short-integer analogue of *dstats*(1) and *ustats*(1), which
operate on streams of doubles and unsigned chars respectively.

[[options]]
== OPTIONS

*-h*::
  Print a usage message and exit. The *-?* form is also accepted.

[[examples]]
== EXAMPLES

.Summarize a file of signed-short sample data
====
[source,bash]
----
istats samples.shorts
----
Report the count, range, sum, mean, and sample standard deviation of
the 16-bit signed integers stored in _samples.shorts_. This is a quick
way to sanity check the dynamic range of intermediate signal-processing
data. The same data may instead be supplied on standard input, for
example as the output of another short-integer filter:
[source,bash]
----
imod -s 2 < samples.shorts | istats
----
====

[[see_also]]
== SEE ALSO

*brlcad*(1), *dstats*(1), *ustats*(1), *ihist*(1), *imod*(1)

[[author]]
== AUTHOR

BRL-CAD Team

[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
