= PIX-PS(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
pix-ps - convert a color pix file to PostScript

== SYNOPSIS

[source]
----
pix-ps [-e] [-c|-l] [-L] [-s input_squaresize] [-w input_width] [-n input_height] [-S inches_square] [-W inches_width] [-N inches_height] [infile.pix] > outfile.ps
----


[[description]]
== DESCRIPTION

*pix-ps* will take a color *pix*(5) format file of given dimensions and produce a Postscript file on the standard output. The *-w* and *-n* flags specify the input file width and number of scan lines in pixels. They can both be set to the same value via *-s.* If no input size is given, defaults of 512 are assumed.

By default the output PostScript image size is 6.75 inches. The *-c* option (on by default) will center it on a 8.5 x 11 inch page; otherwise, the *-l* option uses the lower left corner. If a different output size is desired, *-S*, *-W*, and *-N* can be used to set the size in inches analogous to the input parameters. Finally, *-L* selects landscape mode, i.e. rotates the output image by ninety degrees.

Encapsulated PostScript files can be generated via *-e.*


[[examples]]
== EXAMPLES

pix-ps -c image.pix > image.ps

Produces a 6.75 inch PostScript file from a 512x512 input image and centers it on an 8.5 x 11 inch page.

pix-ps -e -w 1024 -n 768 image.pix > image.ps

Takes the file image.pix which has the dimensions of 1024 pixels wide by 768 pixels high, and produces an Encapsulated Postscript version of it.

pix-ps -L -c -S 5.2 < image.pix > image.ps

Makes a PostScript file of the (assumed 512x512) image, with the output image 5.2 inches square, in landscape mode, centered on an 8.5 x 11 inch page.


[[see_also]]
== SEE ALSO

*brlcad*(1), *bw-ps*(1), *pix*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
