= PIXFILTER(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
pixfilter - apply a 3x3 filter to a color pix file

== SYNOPSIS

[source]
----
pixfilter [-f type] [-v] [-d div] [-o offset] [-w width] [-n height] [-s squaresize] [file.pix] > newfile.pix
----


[[description]]
== DESCRIPTION

*pixfilter* applies one of several 3x3 kernel filters to a color *pix*(5) format file. It will take a file name or else read from standard input. The input file size will be assumed to be 512 by 512 pixels unless the *-w*, and/or *-n*, or the *-s* flags are used to tell it otherwise. By default a low pass filter is used. The *-f* _type_ flag can be used to specify a different type of filter.

The _type_ choices include:


*lo*::
low pass (the default)


*hi*::
high pass


*vg*::
vertical gradient


*hg*::
horizontal gradient


*la*::
laplacian


*b*::
boxcar low pass



Most filters divide the result of the kernel multiplication by some value in order to scale it back to a 0->255 range. For example, the boxcar divides by nine. The *-d* flag can be used to change this divisor. Some filters also add an offset to their results. The output of a laplacian for example is "centered" about zero, thus it adds 128 to the answer to yield a difference from neutral grey. The *-o* flag can be used to change this offset.

The *-v* flag displays the kernel values on standard error.


[[see_also]]
== SEE ALSO

*brlcad*(1), *pixscale*(1), *pix*(5)


[[bugs]]
== BUGS

This should allow any 3x3 kernel to be specified.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
