= PIXHIST3D-PLOT3(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
pixhist3d-plot3 - output RGB color space utilization in 3D unix-plot form

== SYNOPSIS

[source]
----
pixhist3d-plot3 [[file.pix] | plot]
----


[[description]]
== DESCRIPTION

*pixhist3d-plot3* takes a color *pix*(5) format file and outputs points for each RGB color occurring in the image. The format of these points is the BRL extended three dimensional UNIX plot (see *libplot3*(3)). A red, green, and blue line is drawn along the edges of the color space indicating the coordinate axis. The resolution of the color space is 128x128x128, i.e. the least significant bit of each color plane is ignored.

These plots are best viewed on an interactive 3D UNIX plot display program, so that the color cube can be viewed from all angles. Anomalies in the colors of an image can often be seen, e.g. oversaturation resulting in intensity clipping.


[[see_also]]
== SEE ALSO

*brlcad*(1), *pixhist3d*(1), *pixhist*(1), *libplot3*(3), *plot3-fb*(1), *pix*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
