= PIXHIST3D(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
pixhist3d - display RGB color space utilization

== SYNOPSIS

[source]
----
pixhist3d [file.pix]
----


[[description]]
== DESCRIPTION

*pixhist3d* reads a *pix*(5) RGB image from _file.pix_ (or from standard input if no file is given) and builds a count of color frequencies in the RGB color space, then displays three orthographic views of that space on a framebuffer. The red, green, and blue values from 0 to 255 form a right-handed coordinate system. Each displayed face shows the frequencies integrated through the color cube perpendicular to that face. The counts are scaled so that the maximum value is full white, and any non-zero scaled count less than 20 is displayed at intensity 20 so as to remain visible.

The three faces shown on the 512x512 framebuffer are:

Lower left: red vertical, green horizontal

Upper left: blue vertical, green horizontal

Lower right: red vertical, blue horizontal

The environment variable `FB_FILE` is used to select the display device (see *brlcad*(1)). If this variable is not set, the default device for your system will be used.


[[options]]
== OPTIONS

*-h*, *-?*::
  Print a usage message and exit.


[[examples]]
== EXAMPLES

.Inspect the color distribution of a rendered image
====
[source,bash]
----
rt -o scene.pix -s 512 scene.g all.g
pixhist3d scene.pix
----
Render a scene with *rt*(1) to a *pix*(5) file, then display the three
orthographic projections of its RGB color-space usage on the framebuffer.
Bright regions reveal which colors dominate the image and how the red,
green, and blue channels are correlated.
====


[[see_also]]
== SEE ALSO

*brlcad*(1), *pixhist3d-plot3*(1), *pixhist*(1), *pixstat*(1), *rt*(1), *pix*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
