= PIXTILE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
pixtile - paste small images together into one large image

== SYNOPSIS

[source]
----
pixtile [-s squareinsize] [-w file_width] [-n file_height] [-S squareoutsize] [-W out_width] [-N out_height] [-o startframe] basename > file.pix
pixtile [-s squareinsize] [-w file_width] [-n file_height] [-S squareoutsize] [-W out_width] [-N out_height] file1 file2 ... fileN > file.pix
----


[[description]]
== DESCRIPTION

*pixtile* takes a collection of small images and places them side by side in one larger image, written to standard output. Input and output files are assumed to be in *pix*(5) format. By default the input images are 64x64 pixels and the output image is 512x512 pixels.

Images are placed from lower left to upper right. The program keeps reading small files until the next one does not exist or the output image is full. The progress of the composition is displayed on standard error.

Two modes of operation are supported. If a single _basename_ is given, the input files are expected to be named _basename.num_, where _num_ is a consecutive series of integers starting at 0 (or at the value of *-o*). If a _basename_ of "-" is given (preceded by "--" to terminate *bu_getopt*(3) processing), the stream of images is read from standard input instead, and may be split apart again with *pixbustup*(1). Alternatively, if more than one filename is supplied, those files are used explicitly and the *-o* flag is not valid.

Tiling many small low-resolution frames into a single image allows the collection to serve as an animation preview for a higher-resolution sequence.

[[options]]
== OPTIONS

*-s* _squareinsize_::
  Set both the width and height of the input images, in pixels. The default is 64.

*-w* _file_width_::
  Set the width (pixels per scanline) of the input images. The default is 64.

*-n* _file_height_::
  Set the height (number of scanlines) of the input images. The default is 64.

*-S* _squareoutsize_::
  Set both the width and height of the output image, in pixels. The default is 512.

*-W* _out_width_::
  Set the width (pixels per scanline) of the output image. The default is 512.

*-N* _out_height_::
  Set the height (number of scanlines) of the output image. The default is 512.

*-o* _startframe_::
  Set the starting frame number, substituted for _num_ in _basename.num_. The default is 0. Not valid when an explicit list of filenames is given.

*-h*, *-?*::
  Print a usage message and exit.

[[examples]]
== EXAMPLES

.Tile numbered frames into a large preview image
====
[source,bash]
----
pixtile -S 1024 -s 128 -o 2 anim > out.pix
----
Reads files _anim.2_ through _anim.65_, placing each 128x128 image from lower left to upper right into a 1024x1024 _out.pix_ image suitable for previewing an animation sequence.
====

.Combine four explicitly named tiles
====
[source,bash]
----
pixtile -s 256 lowerleft lowerright upperleft upperright > out.pix
----
Reads the four named 256x256 images and arranges them from lower left to upper right into a 512x512 _out.pix_ image.
====


[[see_also]]
== SEE ALSO

*brlcad*(1), *pixbustup*(1), *pix*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
