= PIXUNTILE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
pixuntile - break image up into separate files

== SYNOPSIS

[source]
----
pixuntile [-s squareinsize] [-w in_width] [-n in_height] [-S squareoutsize] [-W out_width] [-N out_height] [-o startframe] basename < file.pix
----


[source]
----
pixuntile [-s squareinsize] [-w in_width] [-n in_height] [-S squareoutsize] [-W out_width] [-N out_height] file1 file2... fileN < file.pix
----


[[description]]
== DESCRIPTION

*pixuntile* performs the inverse operation of *pixtile*(1). It takes a large image composed of a collection of small images and places each of them in a separate file. The input and output files are assumed to be in *pix*(5) format. By default, the input file is assumed to be 512x512 pixels in size.

The output files have a default width of 64 pixels and are usually square, i.e. have the same height as width. Specifying the *-S* flag changes the default size to _squareoutsize_ pixels in width and height. (The *-W* and *-N* flags are used for width and height, respectively. For the input file, these functions are available through the *-s*, *-w*, and *-n* flags.)

The files being produced as output will have names of the form _basename.num_, where _basename_ is given on the command line, and _num_ is a consecutive series of integers. By default the first image is assumed to be number " 0 ", but an alternate _startframe_ can be given by using the *-o* _startframe_ flag and specifying the starting output frame number, where _startframe_ is substituted for _num_ in _basename.num_.

Alternatively, if more than one _basename_ (filename) argument is supplied on the command line, the names of the files are used as the output file names.


[[example]]
== EXAMPLE

**pixuntile -s 1024 -S 128 out < in.pix** will read the 1024x1024 file _in.pix_ and place the 128x128 chunks of that file from lower left to upper right in the files _out.0_ through _out.63_.


[[see_also]]
== SEE ALSO

*pixtile*(1), *brlcad*(1), *pix*(5)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1988-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
