= PLOT3-FB(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
plot3-fb - display 3-D UNIX plot on a framebuffer

== SYNOPSIS

[source]
----
plot3-fb [-id] [-O|o] [-t line_thickness] [-F framebuffer] [-S|s squaresize] [-W|w width] [-N|n height] [<] file.plot3
----


[[description]]
== DESCRIPTION

*plot3-fb* displays a BRL extended three dimensional UNIX plot file on a framebuffer. The environment variable `FB_FILE` is used to select the display device (see *brlcad*(1)); if this variable is not set, the default device for your system will be used. Alternatively, the framebuffer may be explicitly specified by using the *-F* flag. By default, the display size is assumed to be 512x512 pixels. The *-S*, *-W*, and *-N* (or *-s*, *-w*, and *-n*) flags allow different screen sizes to be set. The plotting space will fill the given screen dimensions. No attempt is made at present to preserve aspect.

The *-O* (or *-o*) flag is for overlay mode, where the current framebuffer image will be left in the background. The *-i* flag causes the rasterized image to be plotted immediately, rather than buffering up rasterized data into bands. While useful for quick feedback on small plots, this mode is generally more expensive in CPU time. The *-d* flag outputs a very verbose debugging stream to standard error listing every UNIX plot command and the corresponding framebuffer coordinates. The *-t* flag causes all lines to be thickened perpendicular to their length, to the given number of pixels. This is especially useful when making images for recording on videotape, as single pixel lines are difficult to resolve. The thickening will be reduced so that a line will never be wider than it is long.

If _file.plot3_ is not specified, the plot commands are read from standard input.

Note that 3-D UNIX plot is a superset of the standard UNIX plot format, thus this program can display normal plot files as well.


[[see_also]]
== SEE ALSO

*plot3rot*(1), *plot3debug*(1), *libplot3*(3), *brlcad*(1)


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2026 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
