= RTSCALE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
rtscale - supplements rthide output by plotting a scale to indicate drawing size in arbitrary units.

== SYNOPSIS

[source]
----
rtscale width units intervals file.log optional_string > scale.plot3
----


[[description]]
== DESCRIPTION

*rtscale* supplements the use of *rthide* by generating a UNIX-Plot of a scale that permits the accurate measuring of *rthide* plots. *rthide* provides a hidden-line-removed plot of the geometry, and *rtscale* produces an identical plot file containing just a scale. The two files can then be concatenated making sure that the scale precedes the *rthide* file to produce a finished plot with scale.

*Rtscale* operates on the RT log file from the *rthide* run and produces a UNIX-Plot file of a scale with desired units and number of tick marks. The scale's width is given in model units. A descriptive string may be added. The scale and the strings are plotted in the lower left corner of the image.

The inputs required are: *width,* which specifies the length of the scale in model space, *units,* which may be any units (metric or English), *intervals,* which allows the user to specifies the number of tickmarks on the scale. *filename,* which names the RT log file that is used to calculate the view2model matrix for the raytraced. A view such as azimuth 45, elevation 45, is useful for measuring diagonal dimensions of the geometry. Optionally, a *descriptive string* may be given to identify the view or the model.


[[example]]
== EXAMPLE

This section shows the ordinary usage of *rtscale*. For example:


....

rtscale 30 mm 10 rt.log > scale.plot3
....

This will result in a 30 mm scale with ten tickmarks being plotted in the lower left corner of the scale.plot3 image. Alternately, a descriptive string may be given to identify the view or the model:


....

rtscale 30 mm 10 rt.log "UH-60 a90 e0" > scale.plot3
....

Note that a descriptive string longer than 28 characters will be cut off by *plot3-fb*.

The plot file is now concatenated with the plot file of the image to scale needs to be put on. The order in which they are concatenated is important: the scale is always concatenated over top of the model plot:


....

cat scale.plot3 model.plot3 >> model.w.scale.plot3
....

The resulting UNIX-Plot of the geometry with a scale added to it can be viewed in several ways. It can be overlaid in *mged*, or it can be rotated to the desired azimuth and elevation with *plot3rot* and be stored in a file or view with *plot3-fb*:


....

plot3rot -a# -e# -g model.w.scale.plot3 | plot3-fb
....


[[see_also]]
== SEE ALSO

*mged*(1), *plot3rot*(1), *rt*(1), *rthide*(1), *librt*(3), *libplot3*(3), *plot3*(5), *ray*(5V)


[[diagnostics]]
== DIAGNOSTICS

Numerous error conditions are possible, usually due to errors in the geometry database. Descriptive messages are printed on standard error (file descriptor 2).


[[author]]
== AUTHOR

*BRL-CAD Team*


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2025 United States Government as represented by the U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
