= RTWEIGHT(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
rtweight - Calculate mass, centroid, and volume of geometry using raytracing

== SYNOPSIS

[source]
----
rtweight [options]... model.g objects...
----


[[description]]
== DESCRIPTION

*rtweight* operates on the indicated _objects_ in _model.g_. Material density information and region line of sight (LOS) thickness measurements obtained via ray tracing are used to calculate the mass for each region encountered. It will calculate and report volume of the objects specified. With material properties, it will also report per-region mass information as well as the overall geometric centroid. All calculations take any Boolean operations into consideration.

*rtweight* can either use density information stored directly in a .g database or read a density file specified by the *-d* option.

If using a density file the file must contain lines with the material number, density in g/cc, and material name, each separated by some white space. See the *gqa*(1) manual page for more information about defining and managing density information.

The following options are recognized.


*-s#*::
Number of rays to fire in X and Y directions (square grid). Default is 512 (512x512). Conflicts with *-g*


*-g#*::
Distance between rays in the X and Y directions in millimeters. Conflicts with *-s*


*-a#*::
Select azimuth in degrees. Used with *-e* and conflicts with *-M*


*-e#*::
Select elevation in degrees. Used with *-a* and conflicts with *-M*


*-d file*::
Read density information from the specified file.


*-M*::
Read model2view matrix from standard input. Conflicts with *-a* and *-e*


*-r*::
Report individual region weights by region path name and also by region id number. The default only prints the total weight for all the objects specified.


*-o file*::
Send the output to a specified file. The default is to standard output.


*-P#*::
Specify the maximum number of processor cores to be used on multicore systems. The default is the maximum number of cores available for the machine. Negative numbers indicate using all except for the count specified.



*rtweight* also accepts all other options that the *rt*(1) program implements, such as for non-square views, perspective, etc.


[[see_also]]
== SEE ALSO

*mged*(1), *rt*(1), *librt*(3)


[[diagnostics]]
== DIAGNOSTICS

Numerous error conditions are possible. Descriptive messages are printed on standard error (file descriptor 2).


[[bugs]]
== BUGS

Most deficiencies observed while using the *rtweight* program are usually with the *librt*(3) package instead.


[[author]]
== AUTHOR

James E. Hunt


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1991-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
