= VDECK(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
vdeck - generate COM-GEOM decks from a GED file

== SYNOPSIS

[source]
----
vdeck file.vg \
    
----


[[description]]
== DESCRIPTION

The *vdeck* tool converts a model into an ASCII text representation separating regions (combinations with the region flag set) and primitives (also known as solids) into separate files. A list of objects to be converted are selected interactively from the table of contents. String matching operators (wild cards) like those used to specify file or directory names in *sh*(1) are provided for this purpose, as well as to search for names in the table of contents.

One or more COM-GEOM decks can be output. Each deck consists of three files: the solid, region, and region-id tables. These can be combined with *cat*(1).

A menu of the commands and their usage is available by typing *?* to the program.


[[warning]]
== WARNING

The *vdeck* tool is intended for v5 BRL-CAD geometry databases only. Files produced by older (v4 and earlier) versions of BRL-CAD may be incompatible with *vdeck* .


[[example]]
== EXAMPLE

In the following example, _<model>_ is the name of the BRL-CAD model and _<groupname>_ is a group or region. _Vdeck_ converts all of the primitives and regions within the specified group into text and writes them out to files:


....

> vdeck <model>.g
command ( ? for menu ) >> i <groupname>
command ( ? for menu ) >> d
===================================================
O U T P U T F I L E S
solid table = "solids"
region table = "regions"
region identification table = "region_ids"
command ( ? for menu ) >> q
quitting...
....


[[files]]
== FILES


_solids_::
default solid table output


_regions_::
default region table output


__region_ids__::
default region ID table output


_*.st_::
unique solid table output


_*.rt_::
unique region table output


_*.id_::
unique region ID table output


_/tmp/dis???_::
temporary file used during processing


_/tmp/reg???_::
temporary file used during processing




[[see_also]]
== SEE ALSO

*cat*(1), *gedplot*(1V), *mged*(1B)


[[authors]]
== AUTHORS

Gary S. Moss, BRL/VLD-VMB

Keith Applin, BRL/VLD-TAB


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1986-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
