= WINDOW(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
window - Creates a BRL-CAD .g file containing windows.

== SYNOPSIS

[source]
----
window [options]...
----


[[description]]
== DESCRIPTION

*window* creates a BRL-CAD database containing window models. Up to 256 windows of the same size may be generated per run. *window* uses libwdb to create the database file, with each window composed of two arb8s and four cylinders to produce rounded corners.

If run without arguments, the program enters interactive mode and prompts for all required parameters. Alternatively, options may be specified directly on the command line.


[[options]]
== OPTIONS


*-f* _name.g_::
BRL-CAD file name.


*-n #*::
The number of windows to be created (must be less than or equal to 256).


*-H #*::
Height of window in millimeters.


*-w #*::
Width of window in millimeters.


*-d #*::
Depth of window in millimeters.


*-r #*::
Radius of the corner in millimeters.




[[examples]]
== EXAMPLES

.Interactive *window* Session
[example]
====



....

The windows are composed of 2 arb8s and 4 cylinders.
The front of the window is centered at (0, 0, 0) and
extends in the negative x-direction the depth of the
window.

Enter the mged file to be created (25 char max).
	window.g
Enter the number of windows to create (26 max).
	3
Enter the height, width, and depth of the window.
	200 300 20
Enter the radius of the corner.
	30

mged file:  window.g
height of window:  200.000000 mm
width of window:  300.000000 mm
depth of window:  20.000000 mm
radius of corner:  30.000000 mm
number of windows:  3
   
....



====

.Single-Line *window* Command
[example]
====
**window -fwindow.g -n3 -H200 -w300 -d20 -r30**

====

Both of these examples create a database named window.g containing three windows with a height of 200mm, width of 300mm, depth of 20mm, and corner radius of 30mm.


[[author]]
== AUTHOR

Susan A. Coates


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2005-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[see_also]]
== SEE ALSO

bolt(1), handle(1), window_frame(1), gastank(1)


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
