= WINDOW(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
window - Creates a BRL-CAD .g file containing windows.

== SYNOPSIS

[source]
----
window [options]...
----


[[description]]
== DESCRIPTION

*window* is a program to create a BRL-CAD database of windows. Up to twenty-six windows of the same size may be created. The windows are made with rounded corners. *window* uses libwdb to create a BRL-CAD database. The windows are composed of two arb8s and four cylinders. This program may be run interactively or the user may specify options on a command line. If the user chooses to run the program interactively, he answers the questions as the program prompts him. Below are the options that can be used on the command line.


[[options]]
== OPTIONS


*-f* _name.g_::
BRL-CAD file name.


*-n #*::
The number of windows to be created (must be less than or equal to 26).


*-H #*::
Height of window in millimeters.


*-w #*::
Width of window in millimeters.


*-d #*::
Depth of window in millimeters.


*-r #*::
Radius of the corner in millimeters.




[[examples]]
== EXAMPLES

.Interactive *window* Session
[example]
====



....

The windows are composed of 2 arb8s and 4 cylinders.
The front of the window is centered at (0, 0, 0) and
extends in the negative x-direction the depth of the
window.

Enter the mged file to be created (25 char max).
	window.g
Enter the number of windows to create (26 max).
	3
Enter the height, width, and depth of the window.
	200 300 20
Enter the radius of the corner.
	30

mged file:  window.g
height of window:  200.000000 mm
width of window:  300.000000 mm
depth of window:  20.000000 mm
radius of corner:  30.000000 mm
number of windows:  3
   
....



====

.Single-Line *window* Command
[example]
====
**window -fwindow.g -n3 -H200 -w300 -d20 -r30**

====

Both of these examples create a database named window.g containing three windows with a height of 200mm, width of 300mm, depth of 20mm, and corner radius of 30mm.


[[author]]
== AUTHOR

Susan A. Coates


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2005-2025 United States Government as represented by the U.S. Army Research Laboratory.


[[see_also]]
== SEE ALSO

bolt(1), handle(1), window_frame(1), gastank(1)


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
