= WIRE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
wire - Creates a BRL-CAD .g file containing wiring or fuel lines.

== SYNOPSIS

[source]
----
wire
----


[[description]]
== DESCRIPTION

*wire* creates a BRL-CAD database of solid wires or fuel lines. This program is designed to be run strictly interactively. The user is prompted to enter the target database name, the number of wire segments, the coordinates of the starting and ending points for each segment, and the radius at each point. The program is limited to a maximum of 100 segments. The resulting wires are constructed as combinations of truncated cones (tgc) for the straight segments and spheres to produce rounded joints.


[[examples]]
== EXAMPLES

.Interactive *wire* Session
[example]
====



....

Enter mged file name (25 char max).
	wire.g
Enter the number of segments (maximum of 100).
	3
Enter starting point of segment # 1.
	0 0 0
Enter radius at the starting point of segment # 1.
	.25
Enter ending point of segment # 1.
	0 5 -3
Enter radius at the ending point of segment # 1.
	.25
Enter ending point of segment # 2.
	0 10 -3
Enter radius at the ending point of segment # 2.
	.25
Enter ending point of segment # 3.
	0 12 -2
Enter radius at the ending point of segment # 3.
	.25


mged file created:  wire.g
Segment # 1:  (0.000000, 0.000000, 0.000000) 0.250000
	      (0.000000, 5.000000, -3.000000)0.250000
Segment # 2:  (0.000000, 5.000000, -3.000000) 0.250000
	      (0.000000, 10.000000, -3.000000)0.250000
Segment # 3:  (0.000000, 10.000000, -3.000000) 0.250000
	      (0.000000, 12.000000, -2.000000)0.250000
    
....



====

In this example, a wire of three segments is made. These segments are joined together with spheres. All dimensions are in millimeters.


[[author]]
== AUTHOR

Susan A. Coates


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2005-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[see_also]]
== SEE ALSO

bolt(1), handle(1), window(1), window_frame(1), gastank(1)


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
