= WIRE(1)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
wire - Creates a BRL-CAD .g file containing wiring or fuel lines.

== SYNOPSIS

[source]
----
wire [options]...
----


[[description]]
== DESCRIPTION

*wire* is a program to create a BRL-CAD database of solid wires or fuel lines. The user enters the coordinates of the starting and ending points of the different segments of wires along with the radius at each of these points. Currently the program is limited to 10 segments. This number may be changed by changing the variable MAXSEG. MAXSEG may be no greater than 100 without changing other parts of the program. The wires are composed of cones and spheres. This program is designed to be run interactively.


[[examples]]
== EXAMPLES

.Interactive *wire* Session
[example]
====



....

Enter mged file name (25 char max).
	wire.g
Enter the number of segments (maximum of 10).
	3
Enter starting point of segment # 1.
	0 0 0
Enter radius at the starting point of segment # 1.
	.25
Enter ending point of segment # 1.
	0 5 -3
Enter radius at the ending point of segment # 1.
	.25
Enter ending point of segment # 2.
	0 10 -3
Enter radius at the ending point of segment # 2.
	.25
Enter ending point of segment # 3.
	0 12 -2
Enter radius at the ending point of segment # 3.
	.25


mged file created:  wire.g
Segment # 1:  (0.000000, 0.000000, 0.000000) 0.250000
	      (0.000000, 5.000000, -3.000000)0.250000
Segment # 2:  (0.000000, 5.000000, -3.000000) 0.250000
	      (0.000000, 10.000000, -3.000000)0.250000
Segment # 3:  (0.000000, 10.000000, -3.000000) 0.250000
	      (0.000000, 12.000000, -2.000000)0.250000
    
....



====

In this example, a wire of three segments is made. These segments are joined together with spheres. All dimensions are in millimeters.


[[author]]
== AUTHOR

Susan A. Coates


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2005-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[see_also]]
== SEE ALSO

bolt(1), handle(1), window(1), window_frame(1), gastank(1)


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
