'\" t
.\"     Title: ENIGMA
.\"    Author: Joerg Wunsch
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/04/2012
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "ENIGMA" "1" "12/04/2012" "BRL\-CAD" "BRL\-CAD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
enigma \- very simple file encryption
.SH "SYNOPSIS"
.HP \w'\fBenigma,\fR\ 'u
\fBenigma,\fR \-\-s \-\-k \fIpassword\fR \fIenigma,\fR \-\-s \-\-k \fIpassword\fR
.SH "DESCRIPTION"
.PP
\fB enigma,\fR
also known as
\fB enigma,\fR
is a
\fIvery\fR
simple encryption program, working on a "secret\-key" basis\&. It operates as a filter, i\&. e\&. it encrypts or decrypts a stream of data from standard input, and writes the result to standard output\&. It automatically detects whether the input data stream is already encrypted, and switches into decryption mode in this case\&.
.PP
There are several ways to provide the secret key to the program\&. By default, the program prompts the user on the controlling terminal for the key, using
\fBgetpass\fR(3)\&. This is the only safe way of providing it\&.
.PP
Alternatively, the key can be provided as the sole command\-line argument
\fIpassword\fR
when starting the program\&. Obviously, this way the key can easily be spotted by other users running
\fBps\fR(1)\&. As yet another alternative,
\fB enigma,\fR
can be given the option
\fB\-k\fR, and it will take the key from the environment variable
\fBCrYpTkEy\fR\&. While this at a first glance seems to be more secure than the previous option, it actually isn\*(Aqt since environment variables can also be examined with
\fBps\fR(1)\&. Thus this option is mainly provided for compatibility with other implementations of
\fB enigma,\fR
.PP
When specifying the option
\fB\-s\fR,
\fB enigma,\fR
modifies the encryption engine in a way that is supposed to make it a little more secure, but incompatible with other implementations\&.
.SS "Warning"
.PP
The cryptographic value of
\fB enigma,\fR
is rather small\&. This program is only provided here for compatibility with other operating systems that also provide an implementation\&. For real encryption, refer to
\fBbdes\fR(1)
(from the DES distribution package), or
\fBpgp\fR(1)
(from the ports collection)\&. However, restrictions for exporting, importing or using such tools might exist in some countries, so those stronger programs are not being shipped as part of the operating system by default\&.
.SH "ENVIRONMENT"
.PP
\fBCrYpTkEy\fR
.RS 4
used to obtain the secret key when option
\fB\-k\fR
has been given
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
man enigma | enigma > encrypted
Enter key: (XXX \-\- key not echoed)
.fi
.if n \{\
.RE
.\}
.PP
This will create an encrypted form of this man page, and store it in the file \*(Aq encrypted \*(Aq\&.
.sp
.if n \{\
.RS 4
.\}
.nf
enigma XXX < encrypted
.fi
.if n \{\
.RE
.\}
.PP
This displays the previously created file on the terminal\&.
.SH "SEE ALSO"
.PP
\fBbdes\fR(1),
\fBpgp\fR(1),
\fBps\fR(1),
\fBgetpass\fR(3)
.SH "HISTORY"
.PP
Implementations of
\fB enigma,\fR
are very common among
Unix
operating systems\&. This implementation has been taken from the
\fICrypt\fR
\fIBreaker\*(Aqs\fR
\fIWorkbench\fR
which is in the public domain\&.
.SH "AUTHOR"
.PP
\fBJoerg Wunsch\fR
.RS 4
enigma
.RE
