/*
 *			mged/Cakefile
 */
#define       CONFIGDEFS      MGED_CONFIG "-Dyylex=cmd_nop"

#define SRCDIR	mged
#define PRODUCTS	mged cad_boundp cad_parea
#define STATIC_PRODUCTS mged.tcl
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	ged dodraw dozoom titles scroll \
			usepen dir columns mover tedit \
			cmd chgview chgmodel chgtree \
			rtif anal typein predictor \
			buttons menu adc edsol edarb edpipe edars \
			proc_reg polyif red \
			mater plot overlay inside \
			concat utility1 utility2 track arbs \
			facedef set animedit db comb_std \
			solids_on_ray history \
			TCP_FILES attach dm-plot dm-ps \
			MGED_OBJS vdraw

/*#define USING_NEW_SO*/
#include "../Cakefile.defs"
#include "../Cakefile.prog"

#if HAS_TCP
#    define COMPLETE_LIBES	\
	LIBPKG LIBWDB LIBRT LIBBN LIBBU LIBBU_LIBES LIBTK LIBTCL MGED_LIBES LIBREDBLACK LIBTERMIO LIBES
#    define	TCP_FILES	vrlink
#else
#    define COMPLETE_LIBES	\
	LIBWDB LIBRT LIBBN LIBBU LIBBU_LIBES LIBTK LIBTCL MGED_LIBES LIBREDBLACK LIBTERMIO LIBES
#    define	TCP_FILES	/**/
#endif

mged:	OBJ LIBRT_DEP LIBBN_DEP LIBBU_DEP LIBWDB_DEP LIBTCL_DEP LIBTK_DEP LIBDM_DEP LIBREDBLACK_DEP
	sh ../sh/newvers.sh version "Graphics Editor (MGED)"
	CC CFLAGS -c vers.c
	CC -o mged LDFLAGS OBJ COMPLETE_LIBES vers.o

cad_boundp: cad_boundp.o
	CC -o cad_boundp LDFLAGS cad_boundp.o LIBES

cad_parea: cad_parea.o
	CC -o cad_parea LDFLAGS cad_parea.o LIBES

#include "../Cakefile.rules"
