/*
 *			mged/Cakefile
 */
#define	CONFIGDEFS	MGED_CONFIG

#define SRCDIR	mged
#define PRODUCTS	mged
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	ged dodraw dozoom titles scroll \
			usepen dir columns mover tedit \
			cmd chgview chgmodel chgtree \
			rtif anal typein \
			buttons clip menu adc edsol edarb \
			ars proc_reg hideline \
			spline mater plot overlay inside \
			utility1 utility2 track arbs \
			facedef arb ell half tgc torus \
			attach dm-tek dm-plot dm-ps \
			dm-tek4109 MGED_OBJS

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define COMPLETE_LIBES	\
	LIB_PRE''LIBRT RT_LIBES LIBMALLOC MGED_LIBES LIBES

mged:	OBJ LIBRT
	sh ../newvers.sh version "Graphics Editor (MGED)"
	CC CFLAGS -c vers.c
	CC -o mged LDFLAGS OBJ COMPLETE_LIBES vers.o

#include "../Cakefile.rules"
