.TH MGED 1 BRL/CAD
.SH NAME
mged \- multi-display interactive combinatorial solid geometry editor
.SH SYNOPSIS
.B mged
database.g
.SH DESCRIPTION
.I Mged\^
interactively edits the specified database file
.I database.g
on any one of a number of display devices, including
any UNIX-plot device,
a Vector General 3300,
a Megatek 7250,
a Tektronix 4014 or compatable display,
a Tektronix 4109 or compatable display,
a Raster Technologies One/80,
an Evans and Sutherland Picture System 300,
or a Silicon Graphics IRIS 2400 or 3030 workstation.
.P
For detailed documentation,
obtain a copy of
the guide ``Computer Graphics for Target Descriptions''
or
BRL Technical Report ARBRL-TR-02480, ``GED:  An Interactive
Solid Modeling System for Vulnerability Assessments''.
.P
SIGINT aborts the current command.
.P
"q" or EOF exits the program.
.SH HINTS
.I Mged\^
database names conventionally end with
.BR .g .
.P
.SH EXAMPLE
.RS
$ \|\fImged \|tank.g\fP
.RE
.SH "SEE ALSO"
.I
Computer Graphics for Target Descriptions
.br
rt(1), libged(3), librt(3).
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHORS
Keith Applin
.br
Doug Gwyn
.br
Chuck Kennedy
.br
Gary Kuehl
.br
Gary Moss
.br
Mike Muuss
.br
Chuck Stanley
.br
Bob Suckling
.br
Earl Weaver
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
