.TH VAS4 1 BRL/CAD
.SH NAME
vas4 \- control Lyon Lamb Video Animation System VAS4 to record videotape
.SH SYNOPSIS
.B vas4
.B keyword
.RB [ options ]
.SH DESCRIPTION
The Lyon Lamb VAS IV
is a video animation controller designed specifically for frame
by frame recording and editing of video tape.
The
.I vas4
command initiates a variety of actions within both the
VAS IV controller and associated Video Tape Recorder (VTR),
allowing the animated sequences to be recorded on video tape.
The specified 
keyword determines the action to be performed.
Additional options specified are
dependent upon the keyword selected.
.SH KEYWORDS
.TP
init\ \ \ \ 
Initialize the VAS IV
.TP
rewind
Rewind the VTR.  A problem here is that the VAS IV provides no feedback to
indicate when the rewind is complete.  This command will return immediately
and it is up to the user to estimate when the rewind is complete.
.TP
play\ \ \ \ 
Place the VTR into play mode
.TP
stop\ \ \ \ 
Stop the VTR
.TP
fforward
Fast forward the VTR.  This action has the same problem as \fIrewind\fR.
.TP
new [sn]
Initiates the recording of a new scene.  This keyword has a single option
which is an integer specifying the scene number (sn).  If the scene number
is not specified the scene number will default to 1.  Only the 4-second
matte title image produced by the VAS will actually be recorded.  This
title recording identifies and initiates a new scene.  The actual user
images are recorded using the \fIrecord\fR option.
.TP
record [nf]
Records the currently displayed image by adding frames to the current 
scene.  A single option may be specified by specifying the integer
number of video frames (nf) to record.  A default value of 1 is used if
the option is not specified.  The \fInew\fR option must be executed to initiate
the scene.  This option may be repeated for each image as required.
.TP
sequence [n nf] [start]
Provides an automated method for recording a sequence of images.  The option
n specifies the number of images and nf specifies the number of frames per
image.  If n is specified, nf must also be specified.  The parameter
start specifies an alternate starting index.  The default is 0.  It cannot
be specified unless n and nf are also specified.  For more details of this
option, see SEQUENCE RECORDING below.
.TP
status
Queries the VAS and the VTR, and prints their current status.
.TP
time0
Seek to timer value 00:00:00.
.TP
reset_time
Reset tape time to 00:00:00.  This is only safe when the tape is playing
or not moving.
.TP
search n
Search for frame #n.
.TP 
old sn start
Record over an old scene, given scene number (sn) and starting frame (start).

.SH EXAMPLES
.nf
vas4	init
vas4	rewind
vas4	new		will start a new recording with scene 1
vas4	new	2	will start a new recording of scene 2
vas4	record	3	will record 3 video frames of the currently displayed image
.fi
.SH TYPICAL SEQUENCE
The following example illustrates a typical recording sequence using 
the \fIvas4\fR command.  Suppose the user wants to produce a video consisting 
of 10 seconds of color bars, 4 seconds for title, 1 second for each of a
10-image sequence and 5 seconds of credits, then the following sequence
of commands would be used.  Comments indicated by "/* */" are explanations not 
to be included in the command.  Statements enclosed in "( )" describe an
action to perform, but not a precise command.
.nf
	FB_FILE=/dev/ik0v
	export FB_FILE
	fbcbars			# Display color bars, switch to RS-170
	vas4 init		# Initialize VAS IV
	vas4 new 1		# Initiate new scene 1, record title matte
	vas4 reset_time		# Set VTR time counter to 00:00:00
	vas4 record 10sec	# Record 10 seconds (of color bars)
	(display title image)
	vas4 record 4sec	/*Record 4 seconds of title image*/
	(display image #1)
	vas4 record 1sec	/*Record 1 second of image #1*/
	(display image #2)
	vas4 record 1sec	/*Record 1 second of image #2*/
	(repeat display/record sequence for remaining images)
	(display credits image)
	vas4 record 5sec	/*Record 5 seconds of credits image*/
	vas4 time0		# Return VTR to time 00:00:00
	vas4 stop		# Stop VTR
	vas4 init		# Force VAS-IV out of record mode
.fi

.SH SEQUENCE RECORDING
Since the typical sequence described above will cover many applications,
the "sequence" option is provided to perform the described sequence.  To 
make this option general and provide access to a wide range of display
techniques, the user must provide a program or shell script in the 
current directory named "display_image".  The "sequence" option will
perform the steps described below.  The "sequence" command requires two 
integer values n and nf to be specified.  The parameter n specifies how many
images to record and nf specifies the number of frames per recording.
.LP
Note that the following is a description of the steps performed
by "sequence", not commands to be entered.
.nf
	vas4 init		/*Initialize VAS IV*/
	fbcbars			/*Display color bars*/
	vas4 new 1		/*Initiate new scene*/
	vas4 record 300		/*Record 10 seconds of color bars*/
	for (i=start; i<n; i++){
		display_image i
		vas4 record nf
	}
	vas4 record 900		/*Record last frame for 30 seconds*/
	vas4 init		/*Stop the sequence*/
	vas4 rewind		/*and rewind the tape*/
.fi


.LP
Assuming that a sequence of \fIrle\fR files exist which are named image100.rle,
image101.rle, image102.rle, . . . image129.rle, then the following could be
used as the contents to a shell script named \fIdisplay_image\fR.
.sp
.ce
rle-fb image$1.rle

.LP
In this case, the integer command line parameter supplied by the
sequence option is used to construct the appropriate image file name.
Assuming that the user wanted to record these 30 images with 3 video
frames per image, then the following single command could be used:

.ce
vas4  sequence  30  3  100

.LP
Since a shell script or even a program is used for "display_image", more
complex methods of displaying the image may be used.  For example, the
appropriate commands may be included to read an image from magtape and
display, thus reducing the impact of storing image files on the disk. 

.SH SPECIAL NOTES
Page B-1 of the VAS IV Operations Manual states: "The microprocessor in
the VAS IV is driven by interrupts derived from the video source,
therefore, in order to operate the controller video \fBmust\fR be
present at the input connector J4. Also the sync portion of the video
signal must be in accordance with EIA RS-170 or RS-170A specification.
.LP
This statement plus experience indicates that the video source must be a
stable RS-170 during the entire recording process.
This sync dependency further implies that communication with the VAS IV
controller may not be reliable unless correct video is supplied.
Therefore, the associated framebuffer should be placed into EXTERNAL SYNC
operation before beginning operations with the VAS IV.
For an Ikonas framebuffer, this is done by setting FB_FILE to /dev/ik0v,
(where ``0'' is the unit number, and ``v'' specifies RS-170 style video),
and then running
.I fbclear
or
.I fbcbars
Any operations which will change the RS170 setting
should be avoided during the recording process.
.SH TAPE PREPARATION
Before using a new tape to record an animation sequence, it \fImust\fR be
prepared by recording any signal on the VTR, to establish valid time codes.
The best way to do this preparation is to set the
ENC-6 encoder switches to 'VIDEO INT' & 'BLACK', insert the new tape,
simultaneously press
the 'RECORD' & 'PLAY' buttons on the VTR and wait until the entire tape
has been recorded with the black signal.
.SH FILES
.nf
/dev/vas	tty port connected to the VAS IV
.fi
.SH SEE ALSO
brlcad(1), fbcbars(1), rle-fb(1), pix-fb(1), rle-ik(1)
.br
VAS IV Operations Manual, 
Lyon-Lamb Video Animation Systems, Inc., 4531 Empire Avenue, Burbank, 
CA, 91505, (818) 843-4831
.SH AUTHORS
Steven G. Satterfield, U.S. Naval Academy
.br
Michael John Muuss, BRL
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
