.TH IGES-G 1 BRL-CAD
.\"                       I G E S - G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
iges-g \- IGES Translator (IGES CSG to BRL-CAD)
.SH SYNOPSIS
.B iges-g
[-X NMG_debug_flag] [-x rt_debug_flag] [-N solid_name] [-b] [-n|d|3|t] -o database.g file.iges
.SH DESCRIPTION
.I iges-g\^
converts the specified
.I file.iges
to a BRL-CAD
.I database.g
file. The IGES file is expected to conform to IGES 5.1.
The
.I -n
option specifies that all rational B-spline surfaces in the IGES file should be
combined into one BRL-CAD spline solid.
The
.I -d
option indicates that IGES drawings should be converted to BRL-CAD NMG objects.
Theses objects will be two-dimensional drawings, not solids.
The
.I -3
option is the same as the
.I -d
option except the final projection into 2D is not performed. This may produce 3D drawings
in cases where the drawings have been produced from a 3D model.
The
.I -t
option requests all the trimmed surfaces in the IGES file be converted to
a single BRL-CAD NMG solid.
The
.I -N
option provides a name to be used for the single solid created under the
.I -n
or
.I -t
options, and is ignored for other options.
The
.I -p
option indicates that BREP objects should be converted to NMG solids rather than the default BOT solids.
The
.I -X
and
.I -x
options allow the setting of debug flags for the NMG routines and the rt library
respectively. See
.I nmg.h
and
.I debug.h
for details.
The
.I -b
option indicates that BREP solids should be written to the BRL-CAD model as NMG solids rather than
the default BOT solids.
The absence of any of the
.I -n
,
.I -d
, or
.I -t
options results in the default behavior where
all IGES CSG and planar face BREP objects are converted to BRL-CAD
equivalents. Most conversions are exact, with the exceptions of the solid of
revolution and the solid of linear extrusion. These solids do not exist in BRL-CAD
and are therefore approximated. The solid of revolution is built from a series of
truncated right cones developed by approximating the curve to be revolved with a series
of straight line segments. The extrusion is similarly handled by approximating the
curve to be extruded with straight line segments and using that to build a BRL-CAD
.I polysolid.
Planar faced IGES BREP objects are converted to BRL-CAD NMG structures.
.SH EXAMPLE
.RS
$ \|\fIiges-g \|-o sample.g \|sample.iges\fP
.RE
.SH "SEE ALSO"
.I
The Initial Graphics Exchange Specification (IGES) Version 5.1,
IGES/PDES Organization, September 1991.
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHORS
John Anderson
.br
Susanne Muuss
.br
Phil Dykstra
.br
Earl Weaver
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
