/*
 *		tclscripts/rtwizard/Cakefile
 */
#include "../../Cakefile.defs"

#define PRODUCTS	lib examples *.tcl *.tk *.itcl *.itk tclIndex 
#define STATIC_PRODUCTS	lib examples *.tcl *.tk *.itcl *.itk tclIndex 
#define SRCDIR	tclscripts/rtwizard
#undef BINDIR
#define BINDIR	TCLSCRIPTSDIR/rtwizard

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

tclIndex:
	../tclscripts/ami.tcl ../tclscripts/rtwizard

clean&:
	@echo "" > /dev/null

noprod&:
	rm -f tclIndex

clobber&:
	@echo "" > /dev/null

#include "../../Cakefile.rules"

