.TH PATCH-G 1 BRL-CAD
.\"                      P A T C H - G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
patch\(hyg \- convert FASTGEN ASCII databases into binary MGED databases.
.SH SYNOPSIS
.B patch-g [options] output.g
.SH DESCRIPTION
This program converts FASTGEN geometry into BRL-CAD
.IR mged (1)
formats. FASTGEN is
a modeling system used by the Air Force and Navy to create military target
descriptions. FASTGEN databases consist of the following primitives which
can be converted by
.IR patch-g
: polygons, plates, boxes, wedges, cylinders, spheres, and rods.
It is recommended that
.IR patch-g
be run with the
.B -p
option for most uses.
.PP
.IR patch-g
requires that the FASTGEN file be run through the pre-processor
.IR rpatch.
This is achieved by executing
.IR rpatch < fastgen_file > file.rpatch .
Once this step is executed,
.IR patch-g
can be used to convert the intermediate file into a binary
.IR brlcad (1)
".g" file.
.PP
.IR patch-g
will provide messages when encountering problems in the conversion of FASTGEN
geometry. For further debugging information, the -d flag with levels 1-3 of
debugging can be provided.
.PP
The available options are:
.TP
.B -T tolerance_distance
The
.IR tolerance_distance
is specified in inches. Any two vertices within this distance
from each other will be considered the same vertex.
.TP
.B -A perp_tolerance
the
.IR perp_tolerance
is specified as the cosine of an angle (0.0 through 1.0). If the
cosine of the angle between two vectors is less than the specified
tolerance, then the vectors are considered perpendicular.
.TP
.B -x librt_debug_flag
Specifies a flag for debugging the
.IR librt
package.
.TP
.B -X NMG_debug_flag
Specifies a flag for NMG routine debugging.
.TP
.B -p
Produce polysolid output rather than the default NMG solids.
.TP
.B -6
Convert plate-mode triangles using ARB6 solids.
.TP
.B -f preprocessed_input_file
Use the specified file as the input for conversion.
.TP
.B -i labels_file
Specifies desired group names to override defaults.
.TP
.B -m materials_file
Specifies material properties to be assigned to components.
.TP
.B -a
Process phantom armor.
.TP
.B -n
Process volume mode as plate mode.
.TP
.B -t title
Specifies a title for the output model.
.TP
.B -o top_level_name
Specifies a name for the top level object (default is
.B all
).
.TP
.B -r
Reverse normals for plate mode triangles.
.TP
.B -c ``X Y Z''
Specifies centroid for some plate mode surface normal calulations.
.TP
.B -d debug_level
Specifies a debug level (1-3).
.SH EXAMPLE
.I
rpatch < fastgen_file > file.rpatch
.br
.I
patch-g -p -f file.rpatch  file.g
.SH DIAGNOSTICS
The diagnostics are intended to be self-explanatory.
.SH SEE ALSO
brlcad(1), mged(1)
.SH AUTHOR
Bill Mermagen, Jr.
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH BUG REPORTS
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
