/*
 *			libfb/Cakefile
 *
 *  Note that it may be necessary to link with other (vendor specific)
 *  libraries when using libfb.  For a list of the libraries required
 *  find the symbol LIBFB_LIBES in ../Cakefile.defs in the section on
 *  the machine architecture you are using.
 *
 *  $Header$
 */

#define	CONFIGDEFS	LIBFB_CONFIG

#define PRODUCTS	libfb.ARCH_SUF
#define SRCDIR	libfb
#define FILES	fb_generic fb_log fb_paged_io fb_rect fb_util getput server \
		if_disk if_debug if_stack if_mem if_null tcl fb_obj fbserv_obj \
		LIBFB_OBJS
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	fb_version
#define LIBRARY_TITLE		"BRL-CAD FrameBuffer Library"

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc -lm -lX11 -brtl -L../.libbu.sp3 -lbu -L../.libpkg.sp3 -lpkg -L../.libtcl8.4.sp3 -ltcl
#endif

#ifdef	LIBFB_SETUP
#define	EXTRA_SETUP	LIBFB_SETUP
#endif

#include "../Cakefile.lib"

#include "../Cakefile.rules"
