/*
 *			unigraphics/Cakefile
 */
#define SRCDIR	unigraphics
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#if defined(UGOPEN_LIBES)
#define PRODUCTS ug-g
#else
#define PRODUCTS /**/
#endif
#include "../Cakefile.prog"

#if defined(UGOPEN_LIBES)

#define FILES ug-g ug_misc

ug-g:	OBJ LIBBU_DEP LIBBN_DEP LIBRT_DEP LIBTCL_DEP LIBWDB_DEP LIBUGOPEN_DEP
	CC -o ug-g LDFLAGS OBJ LIBBU LIBBN LIBRT LIBTCL LIBWDB UGOPEN_LIBES -lfpe STANDARD_LIBES -rpath UGOPEN_LIB_DIR

#endif

#include "../Cakefile.rules"
