/*
 *			html/manuals/libbu/Cakefile
 */
#include "../../../Cakefile.defs"

#define PRODUCTS	*.html
#define STATIC_PRODUCTS	*.html
#define SRCDIR	libbu
#undef BINDIR
#define BINDIR	BASEDIR/html/manuals/libbu
#undef BINPERM
#define BINPERM 444

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

clean&:
	@echo "" > /dev/null

noprod&:
	@echo "" > /dev/null

clobber&:
	@echo "" > /dev/null

#include "../../../Cakefile.rules"
