/*
 *			libwdb/Cakefile
 */
#define PRODUCTS	libwdb.ARCH_SUF
#define SRCDIR	libwdb
#define FILES	wdb reg spl ars arbn units
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#include "../Cakefile.lib"
#include "../Cakefile.rules"
