= LIBDM
Robert G. Parker <mulferts@austin.dsccc.com>
:doctype: book
:toc:
:toclevels: 3

== Preface

LIBDM provides the <<api,API>> for accessing BrlCad's display managers. Display managers can be thought of as configurable drawing machines that grind away on generic drawing commands called vlists resulting in display manager specific drawing actions. Vlists are capable of specifying points, lines and polygons in 3D. Display managers are also capable of drawing 2D points, lines, and strings.

The following DM (display manager) types are supported:



.Key Frame
[cols="2*"]
|===
|DM Type
|Canvas Type

|X
|X window
|ogl
|mixed X/OpenGL window
|ps
|postscript file
|plot
|unix plot file
|===




== Application Programming Interface

[[api]]
=== LIBDM's Application Programming Interface

_struct dm *_ *DM_OPEN* _( int dtype, int argc, char *argv[] )_

__DM_OPEN__ creates a display manager of type _dtype_ and returns a pointer to its _dm_ structure. _argc_ and _argv_ are passed to <<dm_p,dm_processOptions>> for interpretation. __DM_NULL__ is returned if unable to acquire a display manager.




----

    int dtype;
    int argc;
    char *argv[];
    struct dm *dmp;

    /*
     * Open a 512x512 X display manager window on the local
     * display using my_default_bindings to set default key
     * and mouse button bindings.
     */
    dtype = DM_TYPE_X;
    argv[0] = "X_open";
    argv[1] = "-i";
    argv[2] = "my_default_bindings";
    argv[3] = "-S";
    argv[4] = "512";
    argv[5] = "-d";
    argv[6] = ":0";
    argv[7] = (char *)NULL;
    dmp = DM_OPEN(dtype, argc, argv);
     
----



_int_ *DM_CLOSE* _( struct dm *dmp )_

__DM_CLOSE__ closes the display manager indicated by _dmp_.




----

            /* open a display manager */
    dmp = DM_OPEN(dtype, argc, argv);

              .  .  .

    /* close the display manager */
    DM_CLOSE(dmp);
  
----



_int_ *DM_DRAW_BEGIN*_( struct dm *dmp )_

__DM_DRAW_BEGIN__ prepares the display manager indicated by _dmp_ for a round of drawing.




----

            /* begin another drawing sequence */
    (void)DM_DRAW_BEGIN(dmp);
  
----



_int_ *DM_DRAW_END* _( struct dm *dmp )_

__DM_DRAW_END__ ends the drawing sequence for the display manager indicated by _dmp_. This should be called before the next call to __<<dm_draw_begin,DM_DRAW_BEGIN>>__ in order to see the results of the current drawing sequence.




----

          /* end the current drawing sequence */
    (void)DM_DRAW_END(dmp);
      
----



_int_ *DM_NORMAL* _( struct dm *dmp )_

__DM_NORMAL__ restores the display manager indicated by _dmp_ to a normal mode of operation (i.e. not scaled, rotated, displaced, etc.).




----

            /* restore to normal mode */
    (void)DM_NORMAL(dmp);
        
----



_int_*DM_LOADMATRIX* __( struct dm *dmp, mat_t mat, int which_eye )__

__DM_LOADMATRIX__ loads the display manager indicated by _dmp_ with a new transformation matrix. _mat_ indicates the matrix to be loaded. __which_eye__ denotes the eye the matrix applies to and can have a value of 0 to indicate non-stereo, a value of 1 to indicate the right eye, or a value of 2 to indicate the left eye.




----

              /* load the display manager with mat --- not using stereo */
    (void)DM_LOADMATRIX(dmp, mat, 0);
----



_int_ *DM_DRAW_STRING_2D* __( struct dm *dmp, char *str, int x, int y, int size, int use_aspect )__

__DM_DRAW_STRING_2D__ draws a string in the display manager window indicated by _dmp_. _str_ is a pointer to the string to be drawn. x and y indicate where to begin drawing the string and are expected to be in the range [-2048,2047]. The _size_ argument indicates the font size to use (currently used only by dm-ps). The expected values for _size_ are 0 for small, 1 for medium, 2 for large, and 3 for huge. __use_aspect__ indicates whether to use the aspect ratio to modify the starting point where the string will be drawn.




----

          /*
     * - draw the string starting at the lower left corner
     * - use the small font
     * - don't use aspect ratio to modify string placement
     */
    (void)DM_DRAW_STRING_2D(dmp, "starting string at lower left", -2040, -2040, 0, 0)
      
----



_int_ *DM_DRAW_LINE_2D* _( struct dm *dmp, int x1, int y1, int x2, int y2 )_

__DM_DRAW_LINE_2D__ is used to draw two-dimensional lines in the display manager window indicated by _dmp. x1, y1, x2,_ and _y2_ indicate the coordinates for the line to be drawn.




----

          /* draw a line from the lower left corner of the window to the upper right corner */
    (void)DM_DRAW_LINE_2D(dmp, -2048, -2048, 2047, 2047);
  
----



_int_ *DM_DRAW_POINT_2D* _( struct dm *dmp, int x, int y )_

__DM_DRAW_POINT_2D__ draws a point in the display manager window indicated by _dmp_. _x_ and _y_ indicate the coordinates for the point to be drawn.




----

          /* draw a yellow dot in the center of the window */
    (void)DM_SET_FGCOLOR(dmp, 230, 230, 0, 1);
    (void)DM_DRAW_POINT_2D(dmp, 0, 0);
  
----



_int_ *DM_DRAW_VLIST* __( struct dm *dmp, struct rt_vlist *vp )__

__DM_DRAW_VLIST__ takes the vlist pointer _vp_ and interprets it for drawing into the display manager window indicated by _dmp_ .




----

          /* draw the vlists pointed to by view_list_ptr */
    (void)DM_DRAW_VLIST(dmp, view_list_ptr);
    
----



_int_ *DM_SET_FGCOLOR* _( struct dm *dmp, short r, short g, short b, int strict )_

__DM_SET_FGCOLOR__ sets the color for drawing in the display manager indicated by _dmp_. _r, g,_ and _b_ denote the color and have values in the range [0,255]. _Strict_ specifies to really use this color (i.e. don't allow ogl to do fancy things with the color when depth cueing).




----

          /* set the drawing color to red */
    (void)DM_SET_FGCOLOR(dmp, 220, 0, 0, 1);
    
----



_int_ *DM_SET_BGCOLOR* _( struct dm *dmp, short r, short g, short b )_

__DM_SET_BGCOLOR__ sets the background color for the display manager indicated by _dmp. r, g,_ and _b_ denote the color and have values in the range [0,255].




----

          /* set the background color to red */
    (void)DM_SET_BGCOLOR(dmp, 220, 0, 0);
      
----



_int_ *DM_GET_BGCOLOR* __( struct dm *dmp, Tcl_Interp *interp )__

__DM_SET_BGCOLOR__ gets the background color for the display manager indicated by _dmp_ and places the result in interp.




----

          /* get the background color */
    return DM_GET_BGCOLOR(dmp, interp);
  
----



_int_ *DM_SET_LINE_ATTR* _( struct dm *dmp, int width, int style )_

__DM_SET_LINE_ATTR__ sets the display managers (i.e. dmp) line width to width and sets its line style to _style_ . Currently, there are only 2 valid values for _style: 0_ for solid lines and 1 for dashed lines.




----

          /* set the display manager up to draw fat dashed lines */
    (void)DM_SET_LINE_ATTR(dmp, 10, 1);

    
----



_int_ *DM_SET_WIN_BOUNDS* _( struct dm *dmp, int clip[6] )_

__DM_SET_WIN_BOUNDS__ sets the view clipping planes for the display manager indicated by _dmp. clip_ is interpreted as follows: {XMIN, XMAX, YMIN, YMAX, ZMIN, ZMAX}




----

          int clip[6] = { -2048, 2047, -2048, 2047, -2048, 2047 };

    /* set the display managers clipping planes */
    (void)DM_SET_WIN_BOUNDS(dmp, clip);
  
----



_int_ *DM_ENDDLIST* _( struct dm *dmp )_

__DM_ENDDLIST__ ends the definition of the display list currently being defined for the display manager indicated by _dmp_.




----

          /* define display list 1 to draw objects */
    (void)DM_BEGINDLIST(dmp, 1);

    /* Put code to draw objects here */

    (void)DM_ENDDLIST(dmp);
    
----



_int_ *DM_DRAWDLIST* _( struct dm *dmp, unsigned int list )_

__DM_DRAWDLIST__ draws the previously defined display list list in the display manager indicated by _dmp_.




----

          unsigned int i;

    /* draw display lists 1 through 9 */
    for (i = 1; i < 10; ++i)
       (void)DM_DRAWDLIST(dmp, i);
----



_int_ *DM_FREEDLISTS* _( struct dm *dmp, unsigned int list, int range )_

__DM_FREEDLISTS__ frees the display lists indicated by _list and range. list_ indicates the display list to start with and range indicates the number of display lists to be freed.




----

       /* free display lists 10 through 29 */
    (void)DM_FREEDLISTS(dmp, 10, 20);
      
----




=== LIBDM's Other Support Routines

_int_ *dm_share_list* _( struct dm *dmp1, struct dm *dmp2 )_

__dm_share_dlist__ provides a way to (un)share display lists. If dmp1 and dmp2 are not NULL, dmp1 will share its display lists with dmp2. If dmp2 is NULL, dmp1 will no longer share its display lists.

_void_ *dm_fogHint* _( struct dm *dmp, int fastfog )_

__dm_fogHint__ is used to give a hint to the display manager about whether to use an efficient fog calculation method or the most accurate. Note - this is currently only implemented by the ogl display manager.




----

              /* use the most efficient method for calculating fog */
    dm_fogHint(dmp, 1);

    /* use the most accurate method for calculating fog */
    dm_fogHint(dmp, 0);

        
----



_int_ *dm_limit* _( val )_

__dm_limit__ takes an integer argument and returns zero if (NOISE <= val < = NOISE) where NOISE is the size of the dead spot around zero. If ( val < -NOISE ), the return value is _( val + NOISE )_. If _( NOISE < val ),_ the return value is _( val - NOISE )._




----

              /* The examples below assume that NOISE is 16 */

    /* i = 0 */
    i = dm_limit(16);

    /* i = 1 */
    i = dm_limit(17);

    /* i = 0 */
    i = dm_limit(-16);

    /* i = -1 */
    i = dm_limit(-17);
  
----



_int_ *dm_unlimit* _( val )_

__dm_unlimit__ takes an integer value and returns zero if _( val == 0 )._ If _( 0 < val ),_ the return value is _( NOISE + val ). If ( val < 0 ),_ the return value is _( -NOISE + val )._ In short, dm_unlimit puts NOISE back into val.




----

            /* i = 0 */
    i = dm_unlimit(0);

    /* i = 17 */
    i = dm_unlimit(1);

    /* i = -17 */
    i = dm_unlimit(-1);
      
----



__fastf_t__ *dm_wrap* _( val )_

__dm_wrap__ wraps _val_ into the range [-1.0, 1.0].




----

              /* f = 0.9 */
    f = dm_wrap(0.9);

    /* f = -0.5 */
    f = dm_wrap(1.5);

    /* f = 0.0 */
    f = dm_wrap(6.0);

    /* f = 1.0 */
    f = dm_wrap(7.0);

    /* f = 0.5 */
    f = dm_wrap(-1.5);

    /* f = -1.0 */
    f = dm_wrap(-5.0);

        
----



_int_ *dm_processOptions*__(struct dm *dmp, struct bu_vls *vls, int argc, char *argv[])__

__dm_processOptions__ is used primarily by LIBDM's display manager open routines to process options. The table below lists the available options. Note - the application would not typically call processOptions. The application would instead build the desired options into the argv list that is supplied to the call to DM_OPEN.



.Key Frame
[cols="2*"]
|===
|Options
|Description

|-d string
|This option specifies where to draw the display manager. string is expected to be in the same form as the X DISPLAY environment variable.
|-i init_script
|This option specifies a Tcl script to use to initialize the display manager.
|-N height
|This option specifies the number of scanlines or height to make the display manager window.
|-n name
|This option specifies a name to use for the display manager.
|-S size
|This option specifies the display manager windows square size.
|-s
|This option turns on stereo mode and is currently only available with the ogl display manager.
|-t 0|1
|This option specifies whether the display manager window will be a top level window or an embedded window. A non-zero value indicates a top level window, while zero indicates an embedded window.
|-W width
|This option specifies the width in pixels of the display manager window.
|===



_void_ *dm_configureWindowShape* _( dmp )_

__dm_configureWindowShape__ is used to update the internal state of a display manager after its window has been newly created or resized. This routine is typically called by an event handler.

_void_ *dm_zbuffer* __( struct dm *dmp, zbuffer_on )__

__dm_zbuffer__ is used to turn Z-buffering on/off. Note - zbuffering is only supported by the _ogl_ display manager.




----

              /* turn zbuffering on */
    dm_zbuffer(dmp, 1);
  
----



_void_ __dm_lighting__ __( struct dm *dmp, int lighting_on )__

__dm_lighting__ is used to turn lighting on/off. Note - lighting is only supported by the ogl display manager.




----

              /* turn lighting on */
    dm_lighting(dmp, 1);
        
----



__fastf_t__ *dm_Xx2Normal* _( struct dm *dmp, int x )_

__dm_Xx2Normal__ takes x in X screen coordinates and returns a value in the range [-1.0, 1.0]. dmp indicates the display manager of interest.

__fastf_t__ *dm_Xy2Normal* __( struct dm *dmp, int y, int use_aspect )__

__dm_Xy2Normal__ takes y in X screen coordinates and returns a value in the range [-1.0, 1.0]. _dmp_ indicates the display manager of interest. __use_aspect specifies__ whether to use the window's aspect ratio in the calculation.

_int_ *dm_Normal2Xx* __( struct dm *dmp, fastf_t x )__

__dm_Normal2Xx__ takes x in normalized coordinates and returns a value in X screen coordinates. _dmp_ indicates the display manager of interest

_int_ *dm_Normal2Xy* __( struct dm *dmp, fastf_t y )__

__dm_Normal2Xy__ takes y in normalized coordinates and returns a value in X screen coordinates. _dmp_ indicates the display manager of interest.

_int_ *Dm_Init* __( Tcl_Interp *interp )__

__Dm_Init initializes__ LIBDM's tcl commands. _interp_ indicates the Tcl interpreter.


=== LIBDM's Tcl Interface

*dm_bestXType* _display_

__dm_bestXType__ returns the best available display manager type that can be used on the X server indicated by _display_. _Display_ is specified the same and has the same meaning as the X DISPLAY environment variable.

*dm_validXType* _display dtype_

__dm_validXType__ returns 1 if dtype is a valid display manager type for the X server indicated by _display_. Otherwise, 0 is returned. _Display_ is specified the same and has the same meaning as the X DISPLAY environment variable.


== Display Manager Objects

=== NAME

dm_open - create and manipulate a display manager object.


=== SYNOPSIS

*dm_open* [ _pathName_ type [options]]


=== COMMAND LINE OPTIONS

Option:

*-N* _height_

Specifies the window's height (i.e. number of raster lines).

Option:

*-W* _width_

Specifies the window's width.

Option:

*-S* _size_

Specifies the window's square size (i.e. width and height).

Option:

*-i* _initproc_

Specifies the initialization proc. This proc is called with the pathName as an argument.

Option:

*-t* _0|1>_

Specifies the toplevel flag. 0 indicates the display manager object is an internal window, while 1 indicates a toplevel window.

Option:

*-d* _dpy_

Specifies the display string in a format understood by X windows.


=== DESCRIPTION

The dm_open command creates a new window (given by the pathName argument) and makes it into a display manager object for displaying geometry. Additional options, described above, may be specified on the command line to configure aspects of the display manager object. The dm_open command returns its pathName argument. At the time this command is invoked, there must not exist a window named pathName, but pathName's parent must exist.


=== METHODS

The *dm_open* command creates a new Tcl command whose name is pathName. This command may be used to invoke various operations on the display manager object. It has the following general form:

_pathName option ?arg arg ...?_

Option and the args determine the exact behavior of the command. The following commands are possible for display manager objects:

_pathName_ *bg ["r g b"]*

Set/get the background color. The rgb components are expected to be integers between 0 and 255. pathName bounds [xmin xmax ymin ymax zmin zmax]

Set/get the window bounds. Some display managers use this to calculate clipping planes (i.e. X).

_pathName_ *clear*

Clear the drawing area using the background color.

_pathName_ *close*

Close the display manager object.

_pathName_ *configure*

Called to handle Configure events.

_pathName_ *debug [0|1]*

Set/get debug mode. 0 indicates debugging is off while 1 indicates debugging is on.

_pathName_ *drawBegin*

Begin the drawing sequence.

_pathName_ *drawEnd*

End the drawing sequence. This will cause the graphics pipe to be flushed.

_pathName drawGeom_ *geo_obj(s)*

Draw one or more drawable geometry objects.

_pathName_ *drawLine x1 y1 x2 y2*

Draw the 2D line indicated by endpoints (x1, y1) and (x2, y2). The given coordinates are expected to be in the range [-1, 1].

_pathName_ *drawPoint x y*

Draw the 2D point at position (x, y).

_pathName_ *drawSList slp*

Draw the solid list specified by the solid list pointer (i.e.slp).

_pathName_ *drawString str x y size use_aspect*

Draw the 2D string starting at position (x, y). The x and y coordinates are expected to be in the range [-1, 1]. The size is currently ignored. The use_aspect flag indicates whether or not to use the aspect ratio to modify the starting position.

_pathName_ *drawVList vlp*

Draw the vector list specified by the vector list pointer (i.e.vlp).

_pathName_ *fg ["r g b"]*

Set/get the foreground color. The rgb components are expected to be integers between 0 and 255.

_pathName_ *flush*

Flushes the X server's request buffer.

_pathName_ *get_aspect*

Get the window's aspect ratio (i.e. width / height).

_pathName_ *light [0|1]*

Set/get light mode. 0 indicates light is off while 1 indicates light is on.

_pathName_ *linestyle [0|1]*

Set/get linestyle. 0 indicates solid lines while 1 indicates dashed lines.

_pathName_ *linewidth [width]*

Set/get linewidth. This setting determines how fat to draw the wireframe lines.

_pathName_ *listen [port]*

Set/get the port used to listen for framebuffer clients. Port values less than zero turn off listening.

_pathName_ *loadmat mat*

Load the matrix, mat, into the display manager. This is typically a model2view matrix.

_pathName_ *normal*

Restore display manager to a normal mode of operation (i.e. not scaled, rotated, displaced, etc.).

_pathName_ *observer [subcommand]*

This command is used to maintain a list of observers. Observers are objects who have registered an interest in when this display manager object receives pixels in its role as a framebuffer server. Whenever pixel data is received the observers on the list are notified.

_pathName_ *observer attach obs [command]*

Add the specified observer, obs, to the list of observers. If command is specified then it is executed each time pixel data is received. Otherwise, the observer is expected to have an update method which is called with the name of this display manager object as an argument.

_pathName observer detach obs_

Remove the specified observer, obs, from the list of observers.

_pathName_ *observer show*

Return the list of observers for this display manager object.

_pathName_ *perspective [0|1]*

Set/get perspective mode. 0 indicates perspective is off, while 1 indicates perspective is on.

_pathName_ *refreshfb*

Draws/displays the pixels stored in the widget's framebuffer.

_pathName_ *size [width height]*

Set/get the window size.

_pathName_ *sync*

Flushes the X server's request buffer and waits until all events have been processed.

_pathName_ *zbuffer [0|1]*

Set/get zbuffer mode. 0 indicates that zbuffer is off, while 1 indicates zbuffer is on.

_pathName_ *zclip [0|1]*

Set/get zclipping mode. 0 indicates zclipping is off, while 1 indicates zclipping is on.




----

The following sequence creates a display manager object and draws two yellow lines that connect the opposite corners of the window.
cwish> dm_open .d X -t 0 -s 400
.d
cwish> pack .d -expand yes -fill both
cwish> .d drawBegin
cwish> .d fg "255 255 0"
cwish> .d drawLine -1 1 1 -1
cwish> .d drawLine -1 -1 1 1
cwish> .d drawEnd
----




[[libfbgeneric]]
== Generic frame buffer routines


[source,c]
----
fb *fb_open(* fbfile, int fb_close ( fbp ) fb * fbp, int fb_read ( fbp , x , y , addr , count ) fb * fbp, RGBpixel *addr;, long count;);
int fb_write(* fbp, RGBpixel * addr, long count, int fb_rmap ( fbp , cmap ) fb * fbp, ColorMap * cmap);
int fb_wmap(* fbp, ColorMap * cmap);
int fb_clear(* fbp, RGBpixel * colorp);
char *fb_gettype(* fbp);
int fb_getwidth(* fbp);
int fb_getheight(* fbp);

----


[[libfbhardware]]
== Hardware specific frame buffer routines


[source,c]
----
int fb_cursor(* fbp, int fb_scursor ( fbp , mode , x , y ) fb * fbp, int fb_setcursor ( fbp , bits , xbits , ybits , xorig , yorig ) fb * fbp, unsigned char bits[], int xbits, ybits;, int xorig, yorig;);
int fb_window(* fbp, int fb_zoom ( fbp , x , y ) fb * fbp, / *Buffered frame buffer I/O: */ int fb_ioinit ( fbp ) fb * fbp);
int fb_seek(* fbp, void fb_tell ( fbp , xp , yp ) fb * fbp, int *xp , * yp);
int fb_rpixel(* fbp, RGBpixel * pixelp);
int fb_wpixel(* fbp, RGBpixel * pixelp);
int fb_flush(* fbp);
void fb_log(format [ , arg ] ... );

----


[[description]]
== DESCRIPTION

These routines are designed to provide a device-independent method of using frame buffers or files containing frame buffer images. The coordinate system used is first-quadrant (0..width-1, 0..height-1), with integer addressing. Translation to hardware coordinate systems is handled by the library.

This version of the library assumes that red, green, and blue intensities are described by unsigned 8-bit bytes in the range (0..255). The library interface uses arrays of *RGBpixel* s, which is a typedef for an array of three unsigned chars (this was done to avoid structure padding). Note that a pointer to an *RGBpixel* is thus the name of the *RGBpixel* itself, i.e. no ampersand is needed.

The exact interpretation of color maps tends to be somewhat device specific. The three ColorMap arrays each have 256 entries of unsigned 16-bit values. In order to accommodate color maps with differing amounts of output resolution, the color map entries are fixed-point fractions in the range (0.0..1.0). In integer notation, the range is (0..65525). For devices with less than 16 bits of output from their color maps, the left-most portion of each entry is used.

__Fb_open__ is used to open a frame buffer file _fbfile_. The file may be either the name of a supported frame buffer interface, referenced as "/dev/interface", or the name of a UNIX file. The routine will try to determine if the file opened was a real frame buffer by examining the name, and if so will perform whatever initialization actions are necessary. If the value of _fbfile_ is NULL and the environment variable `FB_FILE` is set, then the value of `FB_FILE` is used; otherwise the default frame buffer device for the system is used. See below for more details. The _width_ and _height_ parameters specify the initial size of display desired. If these are zero the default sizes for that device will be used. On a successful open, the frame buffer I/O (fb) structure pointer is returned. This structure contains size you were actually given, as well as the maximum possible size for the selected device. A return of FB_NULL indicates failure.

__Fb_close__ simply closes the frame buffer.

__Fb_read__ reads _count_ pixels from the frame buffer starting at the location specified by _x_ and _y_, and places them at program memory address specified by _addr_. __Fb_read__ returns the number of pixels actually read, or -1 on error.

__Fb_write__ writes _count_ pixels from program address _addr_ into the frame buffer starting at the location specified by _x_ and _y_. __Fb_write__ returns the number of pixels actually written, or -1 on error.

__Fb_rmap__ reads in the color map from the frame buffer and leaves at the location pointed to by _cmap_.

__Fb_wmap__ writes the color map pointed to by _cmap_ into the frame buffer. If the value of _cmap_ is NULL then a linear color map is used as the default.

__Fb_clear__ erases the frame buffer by setting all pixels to the given color. If the color pointer is NULL, black will be used. On a UNIX file, this entails writing the entire file, which is an expensive operation, whereas on most frame buffer displays this can be done in less than a second by a special command.

__Fb_gettype__ returns a pointer to a string describing the frame buffer specified by the fb pointer.

__Fb_getwidth__ and __Fb_getheight__ returns the current size of the fb frame buffer.

The following routines work in conjunction with those described above to provide functions which only apply if the frame buffer file is actually a hardware frame buffer display.

__Fb_cursor__ places the cursor at the image space coordinates given by _x_ and _y_. If the mode is non-zero, the cursor is made visible, and if mode is zero, the cursor is turned off.

__Fb_scursor__ is the same as __fb_cursor__ except that it places the cursor at the *screen* space coordinates given by _x_ and _y_.

__Fb_setcursor__ allows the user to set the bitmap used to represent the cursor, thereby changing the cursor shape. This is not necessarily supported by all hardware. The argument _bits_ is a pointer to an array of unsigned chars containing the bits of the cursor. The arguments _xbits_ and _ybits_ specify the size of the cursor bitmap. The number of bytes in the `bits` array will be the width rounded up to a multiple of eight (so that the cursor "scanlines" are byte aligned) times the height. `bits`[0] is the lower left corner, `bits`[1] is to the right of it, etc. The next line of the `bits` array goes above the current one. Within a byte the most significant bit is the leftmost. The values _xorig_ and _yorig_ specify which bit in the bitmap actually gets placed at the location specified in the cursor move routines. Again, a first quadrant coordinate system is used.

__Fb_window__ sets the frame buffer window center position to the image space coordinates given by _x_ and _y_. This command is usually used in conjunction with the __fb_zoom__ routine.

__Fb_zoom__ sets the zoom factor for the X coordinate to _x_ and the zoom factor for the Y coordinate to _y_. Zooming is generally done by pixel replication in hardware.

The following routines work in conjunction with those described above to provide buffered reading and writing of frame buffer images either to a real frame buffer or a UNIX file. The routines use a simple paging strategy to hold “bands” of the image in core. Since horizontal bands are buffered, the ideal motion is to scan left to right, then bottom to top.

__Fb_ioinit__ should be called before using any of the other buffered I/O routines and repeated whenever the frame buffer is reopened.

__Fb_seek__ is used to position the current read/write pointer to the location to the next position to be read or written. It is not necessary to do a __fb_seek__ after every read or write since both __fb_rpixel__ and __fb_wpixel__ imply an automatic move to the next pixel. If you read or write the last pixel on a scan line, the pointer will automatically move to the beginning of the following scan line.

__Fb_tell__ returns the current location of the read write pointer in terms of (X,Y) coordinates on the frame buffer. The X and Y values are returned into the integers pointed to by _xp_ and _yp_.

__Fb_rpixel__ reads the pixel at the current frame buffer location and returns it into the location specified by _pixelp_.

__Fb_wpixel__ writes the pixel pointed to by _pixelp_ at the current frame buffer location.

__Fb_flush__ caused any current buffered frame buffer pages to be written out. Unnecessary writes are avoided by the use of page reference bits.

The following is a printing routine which this library uses to indicate errors.

__Fb_log__ will convert, format and print its _args_ under control of _format_ to the standard error output. For more detailed information on the specification of the control string, see *printf*(3S). This function may be supplied by the application if different behavior is desired.


[[fb_file_devices]]
== FB_FILE DEVICES

The following devices are supported by the library; not all may be available on any given system. New device support can be incorporated by the addition of a single module to the library.


`/dev/debug` _[num]_::
The "/dev/debug" interface prints one line to logs each call to the frame buffer library._num_ is a bitvector indicating the levels of verbosity of the output. See *fb.h* for the bit definitions.


_filename_::
Disk file interface


*hostname:* _[devicename]_::
TCP-based network links to a remote framebuffer, where _devicename_ is any from this list, for example, fictitious.brlcad.org:/dev/ik0 or fictitious.brlcad.org:/dev/sgi. A *hostname* with a null _devicename_ will select the default display device on that host. If explicitly specifying a remote device, be careful not to omit the colon between the host and device name, or you will be specifying a local disk file as the result. Note that for security reasons, it is not permitted to access a disk file via the remote interface.




[[examples]]
== EXAMPLES

_Libfb_ can be loaded with any C program:


----

			$  /bin/cc  program.c  -lfb -l\<system-library...\>
		
----

where _<system-library>_ denotes specific libraries necessary on a particular machine. All machines with networking will require the "-lpkg" option. Machines which support the X Windows(tm) system will require the "-lX11" option.


[[return_values]]
== RETURN VALUES

__fb_close__, __fb_write__, __fb_read__, __fb_wmap__, __fb_rmap__, __fb_clear__, __fb_cursor__, __fb_scursor__, __fb_setcursor__, __fb_window__, __fb_zoom__, __fb_ioinit__, __fb_seek__, __fb_wpixel__, __fb_rpixel__ and __fb_flush__ return -1 to indicate failure. __Fb_open__ returns FB_NULL to indicate failure, and a non-null fb structure pointer upon success. __fb_read__, and __fb_write__ return the number of pixels actually read or written. __fb_gettype__ returns a pointer to a NULL terminated description string.
