/*
 *			remrt/Cakefile
 *
 *  $Header$
 */

#define CONFIGDEFS	RFBD_CONFIG

#define SRCDIR	remrt
#define PRODUCTS	remrt rtsrv
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	remrt rtsrv


#include "../Cakefile.defs"
#include "../Cakefile.prog"

#if NFS
#	define	RTDIR	../.rt.MTYPE
#else
#	define	RTDIR	../rt
#endif

#define REMRT_PIECES	\
		ihost.o RTDIR/opt.o \
		LIBFB LIBFB_LIBES LIBRT LIBRT_LIBES LIBES

#define	RTSRV_PIECES	\
		RTDIR/opt.o \
		RTDIR/shade.o \
		RTDIR/sh_text.o RTDIR/sh_cloud.o \
		RTDIR/worker.o RTDIR/wray.o \
		RTDIR/material.o RTDIR/refract.o RTDIR/sh_stack.o \
		RTDIR/sh_plastic.o RTDIR/sh_cook.o \
		RTDIR/mathtab.o \
		RTDIR/sh_wood.o RTDIR/turb.o \
		RTDIR/sh_marble.o RTDIR/sh_stxt.o \
		RTDIR/sh_points.o RTDIR/sh_toyota.o \
		RTDIR/sh_Nfbm.o RTDIR/sh_camo.o RTDIR/sh_cloud3d.o \
		RTDIR/sh_spm.o RTDIR/sh_light.o RTDIR/do.o \
		LIBPKG LIBPKG_LIBES \
		LIBRT LIBRT_LIBES LIBES

#define OBJS	/**/

/* Explicit composition of each product */

/* LIBRT is needed to get htond, parser, etc */
remrt:	remrt.o ihost.o OBJS
	sh ../newvers.sh version "Network-Distributed RT (REMRT)"
	CC CFLAGS -c vers.c
	CC LDFLAGS -o remrt remrt.o vers.o OBJS REMRT_PIECES

/* Specially compiled version of RT view.c */
view.o:	../rt/view.c
	CC CFLAGS -DRTSRV -c ../rt/view.c

rtsrv:	rtsrv.o view.o OBJS
	CC LDFLAGS -o rtsrv rtsrv.o view.o OBJS RTSRV_PIECES

#include "../Cakefile.rules"
