#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: combobox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::combobox .cb -labeltext "Font:" -labelpos w -selectioncommand {
    puts "selected: [.cb getcurselection]"
}
pack .cb

.cb insert list end Ariel Courier Helvetica Knarly Lucida \
    Rumpus Symbol Times "Zapf Dingbats"
