#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: fileselectiondialog in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

iwidgets::fileselectiondialog .fsd -modality application

button .select -text "Files..." -command {
    if {[.fsd activate]} {
        puts "selected: [.fsd get]"
    } else {
        puts ""
    }
}
pack .select -side left
