#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: hyperhelp in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

button .push -text "Help..." -command {
    set win [iwidgets::hyperhelp .#auto -title "Hyperhelp demo" -modality none \
        -topics {demo} -helpdir [file join ${iwidgets::library} demos]]
    $win showtopic demo
    $win activate
}
pack .push
