#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: spindate in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::spindate .sd -monthformat brief
pack .sd
