#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: watch in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Iwidgets 3.0

set tk_strictMotif 1

iwidgets::watch .w -state disabled -showampm no -width 155 -height 155
pack .w -padx 10 -pady 10 -fill both -expand yes

proc fix_time {} {
    if {! [winfo exists .w]} return
    .w show
    after 1000 fix_time
}
fix_time
