/*
 *			burst/Cakefile
 *
 *	Author:		Gary S. Moss
 *			U. S. Army Ballistic Research Laboratory
 *			Aberdeen Proving Ground
 *			Maryland 21005-5066
 *			(301)278-6651 or AV-298-6651
 *
 *	$Header$ (BRL)
 *
 * FONTDIR is pathname to font file (times.r.6) which is included with sources
 * but on real BSD systems is found in /usr/lib/vfont.
 */
#define CONFIGDEFS	LGT_CONFIG -I. /* -DDEBUG */

#define SRCDIR	burst
#define PRODUCTS	burst
#define	SRCSUFF	.c
#define MANSECTION	1
#define FILES	burst error fb glob grid gridrotate idents\
		paint plot prnt trie ui\
		Hm HmGetc HmGlob Sc Tc
#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */
PRODUCTS:	OBJ
	CC LDFLAGS -o burst OBJ LIB_PRE''LIBRT RT_LIBES LIB_PRE''LIBFB LIBTERMLIB LIBES -ltermlib -lm

all&: PRODUCTS

test&:	all tfiles/ktank.g
	./burst -b < tfiles/ktank.in
	@if test $? -ne 0 \
	then	echo "Test failed."; exit 1 \
	fi
	diff tfiles/ktank.burst tfiles/ktank.burst.bak
	@if test $? -ne 0 \
	then	echo "Test failed."; exit 1 \
	fi
	diff tfiles/ktank.shotlines tfiles/ktank.shotlines.bak
	@if test $? -ne 0 \
	then	echo "Test failed."; exit 1 \
	fi
	@echo "Tested OK."

untest&:
	rm -f tfiles/ktank.burst tfiles/ktank.shotlines tfiles/ktank.plot \
		tfiles/ktank.pix tfiles/ktank.g tfiles/ktank.log

tfiles/ktank.g:
	asc2g < tfiles/ktank.asc > tfiles/ktank.g

#include "../Cakefile.rules"
