/*
 *			burst/Cakefile
 *
 *	Author:		Gary S. Moss
 *			U. S. Army Ballistic Research Laboratory
 *			Aberdeen Proving Ground
 *			Maryland 21005-5066
 *			(301)278-6651 or AV-298-6651
 *
 *	$Header$ (BRL)
 *
 * FONTDIR is pathname to font file (times.r.6) which is included with sources
 * but on real BSD systems is found in /usr/lib/vfont.
 */
#define CONFIGDEFS	LGT_CONFIG -DDEBUG -I.

#define SRCDIR	burst
#define PRODUCTS	burst
#define	SRCSUFF	.c
#define MANSECTION	1
#define FILES	burst error fb glob grid gridrotate idents\
		paint plot prnt trie ui
#define MYLIBES	Hm/libHm.a Sc/libSc.a Tc/libTc.a
#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

Hm/libHm.a:
	cd Hm; make install

Sc/libSc.a:
	cd Sc; make install

Tc/libTc.a:
	cd Tc; make install

burst:	OBJ MYLIBES
	CC LDFLAGS -o burst OBJ LIBRT RT_LIBES LIBFB LIBTERMLIB LIBES MYLIBES -ltermlib -lm

test&:	burst
	./burst < tfiles/ktank.in

#include "../Cakefile.rules"
