svn del       README
svn del       TODO
svn del       data/STEPTools_merged_schema/modified_step_merged_cad_schema.exp
svn del       data/ap210e2/Cable_db.stp
svn del       data/ap210e2/FlasherThruHole.stp
svn del       data/ap210e2/PDES-181.stp
svn del       data/ap210e2/SurfaceMountFlasher.stp
svn del       data/ap227/mitre.p21
svn del       data/ap227/mitre.step.txt
svn del       data/ap242/ap242e1.exp
svn del       data/cd209
svn del       data/cd209/ATS1-out.stp
svn del       data/cd209/ATS10-out.stp
svn del       data/cd209/ATS10Mod0-out.stp
svn del       data/cd209/ATS10Mod0-outresult.stp
svn del       data/cd209/ATS1Mod0-out.stp
svn del       data/cd209/ATS1Mod0-outresult.stp
svn del       data/cd209/ATS2-out.stp
svn del       data/cd209/ATS2Mod0-out.stp
svn del       data/cd209/ATS2Mod0-outresult.stp
svn del       data/cd209/ATS3-out.stp
svn del       data/cd209/ATS3Mod0-out.stp
svn del       data/cd209/ATS3Mod0-outresult.stp
svn del       data/cd209/ATS4-out.stp
svn del       data/cd209/ATS4Mod0-out.stp
svn del       data/cd209/ATS4Mod0-outresult.stp
svn del       data/cd209/ATS7-out.stp
svn del       data/cd209/ATS7Mod0-out.stp
svn del       data/cd209/ATS7Mod0-outresult.stp
svn del       data/cd209/ATS8-out.stp
svn del       data/cd209/ATS8Mod0-out.stp
svn del       data/cd209/ATS8Mod0-outresult.stp
svn del       data/cd209/part409cdts_wg3n2617mim_lf.exp
svn del       data/cd242
svn del       data/cd242/242_n2813_mim_lf.exp
svn del       data/wip210e3
svn del       data/wip210e3/210e3_v1_47_mim_lf.exp
svn del       doc/man/man1/dataprobe.1
svn del       doc/man/man1/mkProbe.1
svn del       src/clSchemas
svn del       src/clSchemas/example
svn del       src/clSchemas/example/SdaiAll.cc
svn del       src/clSchemas/example/SdaiEXAMPLE_SCHEMA.cc
svn del       src/clSchemas/example/SdaiEXAMPLE_SCHEMA.h
svn del       src/clSchemas/example/SdaiEXAMPLE_SCHEMA.init.cc
svn del       src/clSchemas/example/Sdaiclasses.h
svn del       src/clSchemas/example/compstructs.cc
svn del       src/clSchemas/example/schema.cc
svn del       src/clSchemas/example/schema.h
svn del       src/clprobe-ui
svn del       src/clprobe-ui/dpmenuitem.cc
svn del       src/clprobe-ui/dpmenuitem.h
svn del       src/clprobe-ui/headerdisp.cc
svn del       src/clprobe-ui/headerdisp.h
svn del       src/clprobe-ui/instcmdbufdisp.cc
svn del       src/clprobe-ui/instcmdbufdisp.h
svn del       src/clprobe-ui/probe.cc
svn del       src/clprobe-ui/probe.h
svn del       src/clprobe-ui/probemain.cc
svn del       src/clprobe-ui/sclfilechooser.cc
svn del       src/clprobe-ui/sclfilechooser.h
svn del       src/clprobe-ui/seedefines.h
svn del       src/clprobe-ui/seestreditors.cc
svn del       src/clprobe-ui/seestreditors.h
svn del       src/clprobe-ui/seinstdisp.cc
svn del       src/clprobe-ui/seinstdisp.h
svn del       src/clprobe-ui/setypedisp.cc
svn del       src/clprobe-ui/setypedisp.h
svn del       src/clprobe-ui/stepentdescriptor.cc
svn del       src/clprobe-ui/stepentdescriptor.h
svn del       src/clprobe-ui/stepenteditor.cc
svn del       src/clprobe-ui/stepenteditor.h
svn del       src/clstepcore/ExpDict.inline.cc
svn del       src/clstepcore/Registry.inline.cc
svn del       src/clstepcore/STEPattribute.inline.cc
svn del       src/clstepcore/SingleLinkList.inline.cc
svn del       src/express/exptoks.h
svn del       src/test/schema-loc
svn del       test/cpp/stepcore
svn del       test/cpp/stepcore/CMakeLists.txt
svn del       test/cpp/stepcore/test_SupertypesIterator.cc
