/*
 *			libsysv/Cakefile
 *
 *  On all machines, this library provides routines missing from SysV:
 *	BSD-style regular expression interface
 *	BSD "select" interface (on selected machines)
 *
 *  On a Berkeley machine, this library additionally provides:
 *	getopt
 *	strchr
 *
 */
#define PRODUCTS	libsysv.ARCH_SUF
#define SRCDIR	libsysv
#define FILES	regex redata bsdselect EXTRA_FILES
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#ifdef	LIBSYSV_SETUP
#	define	EXTRA_SETUP	LIBSYSV_SETUP
#endif

#ifdef BSD
# if	BSD < 43
#	define EXTRA_FILES	getopt memset
# else
#	define EXTRA_FILES	getopt
# endif
#else
#	define EXTRA_FILES	/**/
#endif

#include "../Cakefile.lib"
#include "../Cakefile.rules"
