/*
 *			libsysv/Cakefile
 *
 *  On all machines, this library provides routines missing from SysV:
 *	BSD-style regular expression interface
 *	BSD "select" interface (on selected machines)
 *
 *  On a Berkeley machine, this library additionally provides:
 *	strchr
 *
 */
#define PRODUCTS	libsysv.ARCH_SUF
#define SRCDIR	libsysv
#define FILES regex redata
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	libsysv_version
#define LIBRARY_TITLE		"BRL-CAD System V Compatibility Library"

#include "../Cakefile.defs"

#define CPP_ONLY	1	/* needed for conf.h to stay pure */
#include "../h/conf.h"		/* to get HAVE_POSIX_REGEXEC */

#if !defined(HAVE_POSIX_REGEXEC)
#	define	EXTRA_OBJ	regcomp.o regexec.o regfree.o regerror.o
#endif

#ifdef	LIBSYSV_SETUP
#	define	EXTRA_SETUP	LIBSYSV_SETUP
#endif

#include "../Cakefile.lib"
#include "../Cakefile.rules"
