/*
 *			libitcl/Cakefile
 */
#define SRCDIR	libitcl
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#if !defined(BUILD_LIBRARY)
#define	BUILD_LIBRARY	ar r
#define ITCL_OPTS	--srcdir=[[pwd]]/../SRCDIR --quiet \
			 --cache-file cache.MTYPE  \
			 --exec-prefix=BASEDIR --prefix=BASEDIR \
			 --with-tcl=[[pwd]]/LIBTCL_DIR \
			 --with-tk=[[pwd]]/LIBTK_DIR
#define PRODUCTS	libitcl3.0.a& itclsh& libitk3.0.a& itkwish&
#define	AFTER_MAKE	rm -f libitcl.a libitk.a ; ln -s libitcl3.0.a libitcl.a ; ln -s libitk3.0.a libitk.a
#else
/* Shared library case */
#define ITCL_OPTS	--srcdir=[[pwd]]/../SRCDIR/ --enable-shared --quiet \
			 --cache-file cache.MTYPE \
			 --exec-prefix=BASEDIR --prefix=BASEDIR \
			 --with-tcl=[[pwd]]/LIBTCL_DIR \
			 --with-tk=[[pwd]]/LIBTK_DIR
#define PRODUCTS	libitcl3.0.so& itclsh& libitk3.0.so& itkwish&
#define SHARED_PRODUCT	libitcl3.0.so''[[LIBVERS]] libitk3.0.so''[[LIBVERS]]
#define	AFTER_MAKE	/* mv -f libitcl3.0.so libitcl3.0.so''[[LIBVERS]] ; \
			mv -f libitk3.0.so libitk3.0.so''[[LIBVERS]] ; \
			sharedliblink.sh libitcl3.0.so''[[LIBVERS]] ; \
			sharedliblink.sh libitk3.0.so''[[LIBVERS]] ; */ \
			rm -f libitcl.so libitk.so ; \
			ln -s libitk3.0.so libitk.so ; \
			ln -s libitcl3.0.so libitcl.so
#endif

/* Rule to see if cake is running with -s flag */
#define MINUS_S	[[echo CAKEFLAGS | tr '\040' '\012' | sed -n -e /-s/p ]]

PRODUCTS: Makefile.MTYPE cache.MTYPE
	echo cakeflags=CAKEFLAGS
	echo make MINUS_S -f Makefile.MTYPE CAKEFLAGS all
	make MINUS_S -f Makefile.MTYPE CAKEFLAGS all
	echo \"AFTER_MAKE\"
	AFTER_MAKE

Makefile.MTYPE cache.MTYPE:		if not exist Makefile.MTYPE or not exist cache.MTYPE
	( \C\F\L\A\G\S=\"GFLAG OPTIMIZER PROFILER\"; \
		INSTALL=[[pwd]]/../SRCDIR/config/install-sh ; \
		\A\F\T\E\R\_\M\A\K\E=\"AFTER_MAKE\"; \
		\R\A\N\L\I\B=\"RANLIB\"; \
		\L\D\F\L\A\G\S=\"LDFLAGS\"; \
		\S\H\L\I\B\_\L\D=\"BUILD_LIBRARY\"; \
		 export INSTALL \C\F\L\A\G\S \R\A\N\L\I\B \L\D\F\L\A\G\S; \
		 export \S\H\L\I\B\_\L\D \A\F\T\E\R\_\M\A\K\E; \
		 echo ../SRCDIR/configure ITCL_OPTS; \
		 ../SRCDIR/configure ITCL_OPTS; \
		 echo ../SRCDIR/fix_makefile.sh '>' Makefile.MTYPE; \
		 ../SRCDIR/fix_makefile.sh > Makefile.MTYPE)

clean&:	Makefile.MTYPE
	make -f Makefile.MTYPE clean

noprod&:
	rm -rf libtcl.*

#ifdef NFS
clobber&:
	rm -f *.MTYPE *.o config.log config.status Makefile lib* itclsh itkwish *.a *.so
	rm -rf itcl itk iwidgets*
#else
clobber&:
	rm -f *.MTYPE *.o config.log config.status Makefile lib* itclsh itkwish *.a *.so
#endif

install&: Makefile.MTYPE
	make -f Makefile.MTYPE install
	( cd BASEDIR/lib; AFTER_MAKE )

install-nobak&: Makefile.MTYPE
	make -f Makefile.MTYPE install
	( cd BASEDIR/lib; AFTER_MAKE )

itclsh: Makefile.MTYPE
	make -f Makefile.MTYPE itclsh

itkwish: Makefile.MTYPE
	make -f Makefile.MTYPE itkwish

test&: Makefile.MTYPE
	make -f Makefile.MTYPE test

/* dltest:			if not exist dltest
	cp -r ../SRCDIR/"unix"/dltest .
*/
