#!/bin/sh
#			B R L M A N
#
#  A substitute for the "man" command for those systems that do not
#  have NROFF.  Henry Spencer's "nroff -man" replacement called AWF
#  is used instead.
#
#  Michael John Muuss, BRL, 23-June-1991.
#  Public Domain, Distribution Unlimited
#
#  @(#) $Header$ (BRL)

if test $# -lt 1
then
	echo "Usage: $0 command"
	echo "  To obtain help about that command"
	exit 1
fi

# Use MANPAGER, else use PAGER, else use "more" command.
MORE="more -s -f"
if test "$PAGER" != ""
then
	MORE="${PAGER}"
fi
if test "${MANPAGER}" != ""
then
	MORE="${MANPAGER}"
fi

eval `machinetype.sh -v`		# sets $BASEDIR

# Ensure that MANPATH is set and has BRL-CAD materials listed first.
MANPATH=${BASEDIR}/man:${MANPATH}

PATH_ELEMENTS=`echo ${MANPATH} | sed 's/^://
				s/:://g
				s/:$//
				s/:\\.:/:/g
				s/:/ /g'`

for PLACE in ${PATH_ELEMENTS}
do
	PATTERN="${PLACE}/man?/$1.?"
	TRY=`eval echo ${PATTERN}`
	if test "${TRY}" != "${PATTERN}"
	then
		# Found something(s), format it/them
		echo ${TRY}
		awf -man ${TRY} | ${MORE}
	fi
done

exit 0
