/*
 *			brlman/Cakefile
 *
 *  Note:  The file "awf" needs to know where ../awf/Cakefile put the
 *  pieces (ETCDIR by default).
 */
#include "../Cakefile.defs"

#define PRODUCTS	awf brlman
#define SRCDIR	brlman
#define FILES	/**/
#define	SRCSUFF	/**/
#define MANSECTION	1

#define STATIC_PRODUCTS	PRODUCTS	/* Force PRODUCTS into dist */

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule shoudl take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

#include "../Cakefile.rules"
