
/* 
 * DO NOT EDIT!
 *
 * The code in this file was automatically generated. See the files
 * src/tokenlist.txt and tools/maketokens.tcl from the tkhtml source
 * distribution.
 */

HtmlTokenMap HtmlMarkupMap[] = {
  {"a",            Html_A,            HTMLTAG_INLINE, HtmlAnchorContent, 0},
  {"address",      Html_ADDRESS,      0, 0, 0},
  {"applet",       Html_APPLET,       HTMLTAG_INLINE, 0, 0},
  {"area",         Html_AREA,         0|HTMLTAG_EMPTY, 0, 0},
  {"base",         Html_BASE,         0|HTMLTAG_EMPTY, 0, 0},
  {"basefont",     Html_BASEFONT,     0, 0, 0},
  {"b",            Html_B,            HTMLTAG_INLINE, 0, 0},
  {"big",          Html_BIG,          HTMLTAG_INLINE, 0, 0},
  {"blockquote",   Html_BLOCKQUOTE,   HTMLTAG_BLOCK, 0, 0},
  {"body",         Html_BODY,         0, 0, 0},
  {"br",           Html_BR,           HTMLTAG_INLINE|HTMLTAG_EMPTY, 0, 0},
  {"button",       Html_BUTTON,       0, 0, 0},
  {"caption",      Html_CAPTION,      0, 0, 0},
  {"center",       Html_CENTER,       HTMLTAG_BLOCK, 0, 0},
  {"cite",         Html_CITE,         HTMLTAG_INLINE, 0, 0},
  {"code",         Html_CODE,         HTMLTAG_INLINE, 0, 0},
  {"dd",           Html_DD,           0, HtmlLiContent, 0},
  {"dfn",          Html_DFN,          HTMLTAG_INLINE, 0, 0},
  {"dir",          Html_DIR,          HTMLTAG_BLOCK, HtmlUlContent, 0},
  {"div",          Html_DIV,          HTMLTAG_BLOCK, 0, 0},
  {"dl",           Html_DL,           HTMLTAG_BLOCK, HtmlDlContent, 0},
  {"dt",           Html_DT,           0, HtmlLiContent, 0},
  {"em",           Html_EM,           HTMLTAG_INLINE, 0, 0},
  {"fieldset",     Html_FIELDSET,     HTMLTAG_INLINE, 0, 0},
  {"font",         Html_FONT,         HTMLTAG_INLINE, 0, 0},
  {"form",         Html_FORM,         HTMLTAG_BLOCK, HtmlFormContent, 0},
  {"frame",        Html_FRAME,        0|HTMLTAG_EMPTY, 0, 0},
  {"frameset",     Html_FRAMESET,     0, 0, 0},
  {"h1",           Html_H1,           HTMLTAG_BLOCK, 0, 0},
  {"h2",           Html_H2,           HTMLTAG_BLOCK, 0, 0},
  {"h3",           Html_H3,           HTMLTAG_BLOCK, 0, 0},
  {"h4",           Html_H4,           HTMLTAG_BLOCK, 0, 0},
  {"h5",           Html_H5,           HTMLTAG_BLOCK, 0, 0},
  {"h6",           Html_H6,           HTMLTAG_BLOCK, 0, 0},
  {"head",         Html_HEAD,         0, HtmlHeadContent, 0},
  {"hr",           Html_HR,           HTMLTAG_BLOCK|HTMLTAG_EMPTY, 0, 0},
  {"html",         Html_HTML,         0, 0, 0},
  {"i",            Html_I,            HTMLTAG_INLINE, 0, 0},
  {"iframe",       Html_IFRAME,       0, 0, 0},
  {"img",          Html_IMG,          HTMLTAG_INLINE|HTMLTAG_EMPTY, 0, 0},
  {"input",        Html_INPUT,        HTMLTAG_INLINE|HTMLTAG_EMPTY, 0, 0},
  {"isindex",      Html_ISINDEX,      HTMLTAG_BLOCK|HTMLTAG_EMPTY, 0, 0},
  {"kbd",          Html_KBD,          HTMLTAG_INLINE, 0, 0},
  {"label",        Html_LABEL,        HTMLTAG_INLINE, 0, 0},
  {"legend",       Html_LEGEND,       HTMLTAG_INLINE, 0, 0},
  {"li",           Html_LI,           0, HtmlLiContent, 0},
  {"link",         Html_LINK,         0|HTMLTAG_EMPTY, 0, 0},
  {"map",          Html_MAP,          HTMLTAG_INLINE, 0, 0},
  {"menu",         Html_MENU,         HTMLTAG_BLOCK, HtmlUlContent, 0},
  {"meta",         Html_META,         0|HTMLTAG_EMPTY, 0, 0},
  {"noframes",     Html_NOFRAMES,     0, 0, 0},
  {"noscript",     Html_NOSCRIPT,     0, 0, 0},
  {"object",       Html_OBJECT,       0, 0, 0},
  {"ol",           Html_OL,           HTMLTAG_BLOCK, HtmlUlContent, 0},
  {"option",       Html_OPTION,       HTMLTAG_INLINE, HtmlPcdataContent, 0},
  {"p",            Html_P,            HTMLTAG_BLOCK, HtmlInlineContent, 0},
  {"param",        Html_PARAM,        0|HTMLTAG_EMPTY, 0, 0},
  {"pre",          Html_PRE,          HTMLTAG_BLOCK, 0, 0},
  {"s",            Html_S,            HTMLTAG_INLINE, 0, 0},
  {"samp",         Html_SAMP,         HTMLTAG_INLINE, 0, 0},
  {"script",       Html_SCRIPT,       HTMLTAG_INLINE|HTMLTAG_EMPTY, 0, 0},
  {"select",       Html_SELECT,       HTMLTAG_INLINE, 0, 0},
  {"small",        Html_SMALL,        HTMLTAG_INLINE, 0, 0},
  {"span",         Html_SPAN,         HTMLTAG_INLINE, 0, 0},
  {"strike",       Html_STRIKE,       HTMLTAG_INLINE, 0, 0},
  {"strong",       Html_STRONG,       HTMLTAG_INLINE, 0, 0},
  {"style",        Html_STYLE,        0|HTMLTAG_EMPTY, 0, 0},
  {"sub",          Html_SUB,          HTMLTAG_INLINE, 0, 0},
  {"sup",          Html_SUP,          HTMLTAG_INLINE, 0, 0},
  {"table",        Html_TABLE,        HTMLTAG_BLOCK, HtmlTableContent, 0},
  {"tbody",        Html_TBODY,        0, 0, 0},
  {"td",           Html_TD,           0, HtmlTableCellContent, 0},
  {"textarea",     Html_TEXTAREA,     HTMLTAG_INLINE|HTMLTAG_PCDATA, 0, 0},
  {"tfoot",        Html_TFOOT,        0, 0, 0},
  {"th",           Html_TH,           0, HtmlTableCellContent, 0},
  {"thead",        Html_THEAD,        0, 0, 0},
  {"title",        Html_TITLE,        0, 0, 0},
  {"tr",           Html_TR,           0, HtmlTableRowContent, 0},
  {"tt",           Html_TT,           HTMLTAG_INLINE, 0, 0},
  {"u",            Html_U,            HTMLTAG_INLINE, 0, 0},
  {"ul",           Html_UL,           HTMLTAG_BLOCK, HtmlUlContent, 0},
  {"var",          Html_VAR,          HTMLTAG_INLINE, 0, 0},
  {"comment",      Html_COMMENT,      0, 0, 0},
  {"embed",        Html_EMBED,        0|HTMLTAG_EMPTY, 0, 0},
  {"listing",      Html_LISTING,      0, 0, 0},
  {"marquee",      Html_MARQUEE,      0, 0, 0},
  {"nextid",       Html_NEXTID,       0|HTMLTAG_EMPTY, 0, 0},
  {"nobr",         Html_NOBR,         HTMLTAG_INLINE, 0, 0},
  {"noembed",      Html_NOEMBED,      0, 0, 0},
  {"plaintext",    Html_PLAINTEXT,    0, HtmlInlineContent, 0},
  {"wbr",          Html_WBR,          HTMLTAG_INLINE|HTMLTAG_EMPTY, 0, 0},
  {"xmp",          Html_XMP,          0, 0, 0},
  {"bgsound",      Html_BGSOUND,      0|HTMLTAG_EMPTY, 0, 0},
};
