.TH SSAMP-BW 1 BRL-CAD
.\"                     S S A M P - B W . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
ssamp-bw \- convert spectral sample data into a monochrome image
.SH
SYNOPSIS
.B ssamp-bw
.RB [ \-v ]
.RB [ \-s\  squarefilesize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
.RB [ \-l\  lower_wavelen]
.RB [ \-u\  upper_wavelen]
.RB [ \-m\  minval]
.RB [ \-M\  maxval]
file.ssamp
.SH DESCRIPTION
.IR ssamp-bw (1)
reads a
.IR ssamp (5)
format file of spectral samples for the named file,
and produces a monochrome image in
.IR bw (5)
format.
The spectral definition is read from a second file named
file.ssamp.spect
.PP
Using the
.B \-l
and
.B \-u
parameters, a filter is constructed to select the energy collected
over a portion of the spectrum.
This filter is convolved with each pixel of the two-dimensional input
file and the power levels are summed into a two-dimensional array of
scalor results.
.PP
The scalor array is scanned to compute the maximum and minimum
power levels encountered in this image.
These are used to drive an "automatic gain control" algorithm
which maximizes the use of the limited 0..255 intensity output range.
Using the
.B \-m
and
.B \-M
options, either the minimum or maximum values (or both) may
be over-ridden from the command line.
This is particularly useful when processing a series of
.I ssamp
files
(e.g. for an animation sequence)
and you don't want the gain control settings changing
from frame to frame.
.PP
The
.B \-v
option sets "verbose" mode,
causing the spectral sampling definition and the filter kernel to be
printed on standard error.
.SH EXAMPLE
.sp .5
  ssamp-bw -s512 -M0.3 -l3000 -u5000 moss.ssamp | bw-fb -s512
.sp .5
This converts the energy received in the 3-5 micron ("mid-IR") band
into a monochrome image,
clamping any power greater than 0.3 to a value of 255 in the output,
and displays this monochrome image on the current framebuffer.
.SH "SEE ALSO"
rttherm(1), bw-fb(1), dpix-pix(1), pix(5)
.SH DIAGNOSTICS
If the
.I pix
file is shorter than expected,
or the size parameters are given incorrectly,
an error is printed.
.PP
If the spectral range specified for the filter is outside the
spectral range sampled in the input file, the program aborts with an error.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
