.TH SSAMP-BW 1 BRL-CAD
.\"                     S S A M P - B W . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
ssamp-bw \- convert spectral sample data into a monochrome image
.SH
SYNOPSIS
.B ssamp-bw
.RB [ \-v ]
.RB [ \-s\  squarefilesize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
.RB [ \-l\  lower_wavelen]
.RB [ \-u\  upper_wavelen]
.RB [ \-m\  minval]
.RB [ \-M\  maxval]
file.ssamp
.SH DESCRIPTION
.IR ssamp-bw (1)
reads a
.IR ssamp (5)
format file of spectral samples for the named file,
and produces a monochrome image in
.IR bw (5)
format.
The spectral definition is read from a second file named
file.ssamp.spect
.PP
Using the
.B \-l
and
.B \-u
parameters, a filter is constructed to select the energy collected
over a portion of the spectrum.
This filter is convolved with each pixel of the two-dimensional input
file and the power levels are summed into a two-dimensional array of
scalor results.
.PP
The scalor array is scanned to compute the maximum and minimum
power levels encountered in this image.
These are used to drive an "automatic gain control" algorithm
which maximizes the use of the limited 0..255 intensity output range.
Using the
.B \-m
and
.B \-M
options, either the minimum or maximum values (or both) may
be over-ridden from the command line.
This is particularly useful when processing a series of
.I ssamp
files
(e.g. for an animation sequence)
and you don't want the gain control settings changing
from frame to frame.
.PP
The
.B \-v
option sets "verbose" mode,
causing the spectral sampling definition and the filter kernel to be
printed on standard error.
.SH EXAMPLE
.sp .5
  ssamp-bw -s512 -M0.3 -l3000 -u5000 moss.ssamp | bw-fb -s512
.sp .5
This converts the energy received in the 3-5 micron ("mid-IR") band
into a monochrome image,
clamping any power greater than 0.3 to a value of 255 in the output,
and displays this monochrome image on the current framebuffer.
.SH "SEE ALSO"
rttherm(1), bw-fb(1), dpix-pix(1), pix(5)
.SH DIAGNOSTICS
If the
.I pix
file is shorter than expected,
or the size parameters are given incorrectly,
an error is printed.
.PP
If the spectral range specified for the filter is outside the
spectral range sampled in the input file, the program aborts with an error.
.SH AUTHOR
Michael John Muuss
.SH SOURCE
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
