.TH PIX2ASC 1 BRL-CAD
.\"                      P I X 2 A S C . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
pix2asc,
asc2pix \- encode and decode color pixel files
.SH SYNOPSIS
.B pix2asc
< file.pix > file.a_pix
.br
.B asc2pix
< file.a_pix > file.pix
.SH DESCRIPTION
.I Pix2asc
and
.I asc2pix
are simple filters which convert color
.IR pix (5)
files from their binary form to a portable ASCII form, and back.
.I Pix2asc
reads the binary file on standard in and writes ASCII on standard out.
.I Asc2pix
does the reverse.
.PP
The binary file consists of a sequence
of three-tuples of
.B unsigned chars
representing the
red, green, and blue intensities for each pixel.
The ASCII version of the file has
one RGB pixel per newline-terminated line, with each
pixel represented as six hexadecimal digits.
.PP
When moving
.IR pix (5)
files between UNIX systems
via tape (see
.IR tar (1)
and
.IR cpio (1))
or via network (see
.IR rcp (1)
and
.IR ftp (1)),
this conversion to ASCII is unnecessary,
as all UNIX files are byte streams, regardless of the underlying hardware.
However, when transporting images to non-UNIX machines,
these tools are invaluable.
Note that
.IR rt (1)
can directly generate the ASCII form of an image file using the
.B \-O
flag, allowing it to be easily used on non-UNIX systems.
.SH SEE ALSO
brlcad(1), pix(5)
.SH AUTHOR
Michael John Muuss
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
