.TH SHOWSHOT 1
.\"                     S H O W S H O T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.SH NAME
showshot \- generate MGED commands to represent a ray through some geometry
.SH SYNOPSIS
.BR "showshot  [ -n " name " ] [ -r " radius " ] "
.SH DESCRIPTION
.I Showshot
reads the specification for a ray through some geometry
and generates
.IR mged (1)
commands to produce a database object representing the ray.
The input should consist of lines of the form
.sp
.ce
.I "object  x_in  y_in  z_in  x_out  y_out  z_out"
.sp
as might be obtained from
.IR nirt (1),
where
.I object
is the name of a database object along the ray,
and
(\fIx_in\fR, \fIy_in\fR, \fIz_in\fR)
and
(\fIx_out\fR, \fIy_out\fR, \fIz_out\fR)
are the points at which the ray enters and exits
.I object,
respectively.
The first and last lines of input are assumed to correspond to
the first and last objects encountered along the ray.
Otherwise, the lines of input may be in any order.

The first
.IR mged (1)
command generated by
.I showshot
produces an RCC
to represent the ray itself.
This cylinder has its vertex at the entry point for the first object
along the ray
and extends to the exit point for the last object\(emall
the other coordinates in the input are ignored.
.I Showshot
then generates commands to make the solid a member of a region,
which is assigned the color 255 255 0 (yellow).
Finally,
.I showshot
generates commands to create a group
that contains the ray region and each of the objects specified in the input.
.SS Options
The command-line options and their meanings are given below.
.TP 12
.BI -n " name"
Specifies that the string
.I name
be used as the root for the names of the new database objects.
The ray solid and ray region will be called
\fIname\fR.s and \fIname\fR.r,
respectively,
and the group will be called
.I name.
Default is ray.\fIPID\fR,
where
.I PID
is the process ID of the
.I showshot
process.
.TP 12
.BI -r " radius"
Specifies that the RCC representing the ray should have a radius of
.I radius
units.
Default is 1.
.SH DIAGNOSTICS
If
\fIname\fR.s
is longer than the fifteen-character limit imposed by
.IR mged (1)
or the input stream does not conform to the expected format,
then
.IR showshot
complains and exits with status 1.
.SH SEE ALSO
mged(1), nirt(1)
.SH AUTHOR
Paul Tanenbaum
