/*                     S T E P - G . C P P
 * BRL-CAD
 *
 * Copyright (c) 1994-2026 United States Government as represented by
 * the U.S. Army Research Laboratory.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this file; see the file named COPYING for more
 * information.
 */
/** @file step/step-g.cpp
 *
 * C++ main() for step-g converter.
 *
 */

#include "common.h"

#include <iostream>

#include "bu/app.h"
#include "bu/time.h"
#include "bu/file.h"
#include "bu/log.h"
#include "bu/cmdschema.h"
#include "bu/vls.h"

//
// step-g related headers
//
#include <BRLCADWrapper.h>
#include <STEPWrapper.h>

//
// include NIST step related headers
//
#include <sdai.h>
#include <STEPfile.h>
#include "Factory.h"
#include "schema.h"

void
usage()
{
    std::cerr << "Usage: step-g [-v] -o outfile.g infile.stp \n" << std::endl;
}

struct OutputFile {
    const char *filename;
    bool overwrite;
};

static int
parse_opt_O(struct bu_vls *error_msg, const char *arg, void *set_var)
{
    OutputFile *ofile = (OutputFile *)set_var;

    if (!ofile || !arg || !arg[0]) {
	if (error_msg)
	    bu_vls_printf(error_msg, "-O requires an output filename\n");
	return -1;
    }
    ofile->filename = arg;
    ofile->overwrite = true;
    return 0;
}

struct step_g_args {
    int dry_run;
    int verbose;
    OutputFile overwrite_output;
    const char *output_file;
    const char *summary_log_file;
};

static const struct bu_cmd_option step_g_options[] = {
    BU_CMD_FLAG("D", NULL, struct step_g_args, dry_run,
	"Dry run (output file is not written)"),
    BU_CMD_FLAG("v", NULL, struct step_g_args, verbose, "Verbose output"),
    BU_CMD_CUSTOM("O", NULL, struct step_g_args, overwrite_output, parse_opt_O,
	"file.g", "Set output file and permit overwrite"),
    BU_CMD_FILE("o", NULL, struct step_g_args, output_file, "file.g",
	"Set output file"),
    BU_CMD_FILE("S", NULL, struct step_g_args, summary_log_file, "file",
	"Write a conversion summary log"),
    BU_CMD_OPTION_NULL
};

static const struct bu_cmd_operand step_g_operands[] = {
    BU_CMD_OPERAND("input_file", BU_CMD_VALUE_FILE, 1, 1,
	"Input STEP file", NULL),
    BU_CMD_OPERAND_NULL
};

static const char *step_g_output_options[] = {"O", "o", NULL};
static const struct bu_cmd_constraint step_g_constraints[] = {
    BU_CMD_CONSTRAINT_OPTIONS(step_g_output_options, 1, 1,
	"specify exactly one of -o or -O"),
    BU_CMD_CONSTRAINT_NULL
};

static const struct bu_cmd_schema step_g_schema = {
    "step-g", "Convert an ISO 10303 STEP file to a BRL-CAD database",
    step_g_options, step_g_operands, BU_CMD_PARSE_INTERSPERSED,
    BU_CMD_SCHEMA_CONSTRAINTS(NULL, step_g_constraints)
};

int
main(int argc, const char *argv[])
{
    int ret = 0;
    int64_t elapsedtime;

    bu_setprogname(argv[0]);

    elapsedtime = bu_gettime();

    /*
     * You have to initialize the schema before you do anything else.
     * This initializes all of the registry information for the schema
     * you plan to use.  The SchemaInit() function is generated by
     * fedex_plus.  See the 'extern' stmt above.
     *
     * The registry is always going to be in memory.
     */

    // InstMgr instance_list;
    // Registry registry (SchemaInit);
    // STEPfile sfile (registry, instance_list);

    // process command line arguments
    struct step_g_args args = {0, 0, {NULL, false}, NULL, NULL};
    struct bu_vls parse_msgs = BU_VLS_INIT_ZERO;

    ++argv; --argc;
    int operand_index = bu_cmd_schema_parse_complete(&step_g_schema, &args,
	&parse_msgs, argc, argv);

    if (bu_vls_strlen(&parse_msgs) > 0) {
	bu_log("%s\n", bu_vls_cstr(&parse_msgs));
    }
    if (operand_index < 0) {
	usage();
	bu_exit(1, NULL);
    }
    bu_vls_free(&parse_msgs);

    argc -= operand_index;
    argv += operand_index;
    OutputFile ofile = args.overwrite_output;
    if (!ofile.filename)
	ofile.filename = args.output_file;

    if (!ofile.overwrite) {
	/* check our inputs/outputs */
	if (bu_file_exists(ofile.filename, NULL)) {
	    bu_exit(1, "ERROR: refusing to overwrite existing output file:"
		        "\"%s\". Please remove the existing file, change the "
			"output file name, or use the '-O' option to force an"
			" overwrite.", ofile.filename);
	}
    }
    if (!bu_file_exists(argv[0], NULL) && !BU_STR_EQUAL(argv[0], "-")) {
	bu_exit(2, "ERROR: unable to read input \"%s\" STEP file", argv[0]);
    }

    std::string iflnm = argv[0];
    std::string oflnm = ofile.filename;

    STEPWrapper *step = new STEPWrapper();

    step->dry_run = args.dry_run;
    step->summary_log_file= const_cast<char *>(args.summary_log_file);

    step->Verbose(args.verbose);

    /* load STEP file */
    if (step->load(iflnm)) {

	step->printLoadStatistics();

	elapsedtime = bu_gettime() - elapsedtime;
	{
	    struct bu_vls vls = BU_VLS_INIT_ZERO;
	    int seconds = elapsedtime / 1000000;
	    int minutes = seconds / 60;
	    int hours = minutes / 60;

	    minutes = minutes % 60;
	    seconds = seconds %60;

	    bu_vls_printf(&vls, "Load time: %02d:%02d:%02d\n", hours, minutes, seconds);
	    std::cerr << bu_vls_addr(&vls) << std::endl;
	    bu_vls_free(&vls);
	}
	elapsedtime = bu_gettime();

	BRLCADWrapper *dotg  = new BRLCADWrapper();
	if (!dotg) {
	    std::cerr << "ERROR: unable to create BRL-CAD instance" << std::endl;
	    ret = 3;
	} else {

	    dotg->dry_run = args.dry_run;
	    std::cerr << "Writing output file [" << oflnm << "] ...";
	    if (dotg->OpenFile(oflnm)) {
		step->convert(dotg);
		dotg->Close();
		std::cerr << "done!" << std::endl;
	    } else {
		std::cerr << "ERROR: unable to open BRL-CAD output file [" << oflnm << "]" << std::endl;
		ret = 4;
	    }

	    delete dotg;
	}
    }
    delete step;
    Factory::DeleteObjects();

    elapsedtime = bu_gettime() - elapsedtime;
    {
	struct bu_vls vls = BU_VLS_INIT_ZERO;
	int seconds = elapsedtime / 1000000;
	int minutes = seconds / 60;
	int hours = minutes / 60;

	minutes = minutes % 60;
	seconds = seconds %60;

	bu_vls_printf(&vls, "Convert time: %02d:%02d:%02d\n", hours, minutes, seconds);
	std::cerr << bu_vls_addr(&vls) << std::endl;
	bu_vls_free(&vls);
    }

    return ret;
}


// Local Variables:
// tab-width: 8
// mode: C++
// c-basic-offset: 4
// indent-tabs-mode: t
// c-file-style: "stroustrup"
// End:
// ex: shiftwidth=4 tabstop=8
