/*
 *			libpkg/Cakefile
 */

#define	CONFIGDEFS	LIBPKG_CONFIG

#define PRODUCTS	libpkg.ARCH_SUF
#define SRCDIR	libpkg
#define FILES	pkg
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#ifdef	LIBPKG_SETUP
#define	EXTRA_SETUP	LIBPKG_SETUP
#endif

#include "../Cakefile.lib"
#include "../Cakefile.rules"
