.so defs.mm
.H 1 Introduction
.H 1 "User Interface"
.H 2 "Program Invocation"
.H 2 "Command Input"
.H 2 "Screen Layout"
.H 2 "Hierarchical Menus"
.H 2 "Scrolling Region"
.H 1 "Shotlining Options"
.H 2 "Attack Direction"
.H 2 "Cell Size"
.H 2 "Dithering"
.H 2 "Gridding"
.H 3 "Envelope"
.H 4 "Enclose target"
.H 4 "Enclose portion of target"
.H 3 "Input shot coordinates"
.H 4 "Target coordinate system"
.H 5 "Type in 3-D coordinates"
.H 5 "Read file of 3-D coordinates"
.H 4 "Shotline coordinate system"
.H 5 "Type in 2-D coordinates"
.H 5 "Read file of 2-D coordinates"
.H 1 "Bursting Options"
.H 2 "Method of Locating Burst Point"
.H 3 "Input burst point coordinates"
.H 4 "Type in 3-D coordinates"
.H 4 "Read file of 3-D coordinates"
.H 3 "Burst on contact"
.H 4 "Ground plane bursting"
.H 4 "Burst on armor"
.H 2 "Bursting Parameters"
.H 3 "Burst distance"
.H 3 "Sampling cone half angle"
.H 3 "Deflected sampling cone"
.H 3 "Number of sampling rays"
.H 3 "Maximum barriers"
.H 1 "Output Options"
.H 2 "UNIX Plot File"
.H 2 "Frame Buffer Image"
.H 2 "Burst Point Library"
.H 2 "Shotline File"
.H 2 "Grid File"
.H 2 "Script File"
.H 2 "Error Log"
.H 1 Conclusion


