/*
 *	Cake(1) specification file for libredblack(3)
 */
#define SRCDIR	libredblack
#define PRODUCTS	libredblack.ARCH_SUF
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#define FILES	\
		rb_create rb_delete rb_diag rb_extreme	\
		rb_free rb_insert rb_order_stats	\
		rb_rotate rb_search rb_walk
	

#define VERSION_VARIABLE	rb_version
#define LIBRARY_TITLE		"The BRL-CAD Red-Black Library"

#include "../Cakefile.lib"

#include "../Cakefile.rules"
