(* This is a test file for the EXPRESS parser (libexpress) and
 * pretty printer (exppp), parts of STEPcode (formerly NIST's SCL).
 *)

SCHEMA lost_unique_qualifiers;

  TYPE label = STRING;
  END_TYPE;

  ENTITY connection_zone_interface_plane_relationship
    SUBTYPE OF ( shape_aspect, shape_aspect_relationship );
    UNIQUE
      ur1 : SELF\shape_aspect_relationship.name;
  END_ENTITY;

  ENTITY shape_aspect;
      name  : label;
  END_ENTITY;

  ENTITY shape_aspect_relationship;
      name  : label;
  END_ENTITY;

END_SCHEMA;
