/*
 *			btclsh/Cakefile
 *
 */
#define CONFIGDEFS	BTCLSH_CONFIG 

#define SRCDIR	bwish
#define PRODUCTS	btclsh
#if 0
#define STATIC_PRODUCTS btclsh.tcl
#endif
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	main input tcl cmd

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#if HAS_TCP
#    define COMPLETE_LIBES	\
	LIBPKG LIBWDB LIBRT LIBBN LIBBU LIBBU_LIBES LIBTERMIO BTCLSH_LIBES LIBES
#else
#    define COMPLETE_LIBES	\
	LIBWDB LIBRT LIBBN LIBBU LIBBU_LIBES LIBTERMIO BTCLSH_LIBES LIBES
#endif

btclsh:	OBJ LIBRT_DEP LIBBN_DEP LIBBU_DEP LIBWDB_DEP LIBTCL_DEP
	sh ../sh/newvers.sh version "BrlCad Tclsh (BTCLSH)"
	CC CFLAGS -c vers.c
	CC -o btclsh LDFLAGS OBJ COMPLETE_LIBES vers.o

#include "../Cakefile.rules"
