#!/bin/sh

# This script uses the Boost library utility program 'bcp' to
# determine the minimum subset of the Boost libraries required for a
# BRL-CAD build.  (These instructions were written using version bcp
# version 1.49.0.)

# The user must have the program 'bcp' on his host build machine.  On
# a Debian 7.1 system, the program 'bcp' is installed with package
# 'libboost-dev".

# Set the absolute path to 'bcp' on the next line:
BCP=/usr/bin/bcp

# Download the latest version of the Boost library into this directory
# and unpack it.  Ensure its unpacked directory name is listed next:
BSRCDIR=./boost_1_54_0

# Provide a list of files to search for Boost dependencies in file
# 'boost-using-dirs.txt' in this directory.  (Note that files must be
# listed using full paths or complete relative paths in relation to
# this directory.)

# The file list was generated by first running the following commands
# at the BRL-CAD source directory:
#
#   $ find . -name "*.h"   -exec grep -l 'include <boost' {} \; -print >  boost-using-files.txt
#   $ find . -name "*.cpp" -exec grep -l 'include <boost' {} \; -print >> boost-using-files.txt
#
# Then all files in this directory and below were stripped out:
#
#   $ mv boost-using-files.txt t.txt
#   $ grep -v -e /src/other/boost t.txt > boost-using-files.txt
#
# Duplicate files were removed, and path names changed to be relative
# to this directory.  Following is the defined file name:
MLIST=boost-using-files.txt

# Finally, provide the name of the directory to receive the subset
# (note the directory must exist):
BOOST_DEPS_DIR=./boost-subset

# Now we run bcp to determine dependencies:
$BCP --scan --boost=$BSRCDIR `cat $MLIST` $BOOST_DEPS_DIR
