/*
 *			pro-engineer/Cakefile
 */
#include "../../../Cakefile.defs"

#define PRODUCTS	helpfiles.txt  proe-brl.hlp
#define STATIC_PRODUCTS	 helpfiles.txt  proe-brl.hlp
#define SRCDIR	fullhelp
#undef BINDIR
#define BINDIR	BASEDIR/pro-engineer/text/fullhelp
#undef BINPERM
#define BINPERM 444

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo SRCDIR:  all done

#include "../../../Cakefile.rules"
