
/* 
 * DO NOT EDIT!
 *
 * The code in this file was automatically generated. See the files
 * src/tokenlist.txt and tools/maketokens.tcl from the tkhtml source
 * distribution.
 */


#define Html_Text    1
#define Html_Space   2
#define Html_Unknown 3
#define Html_Block   4
#define HtmlIsMarkup(X) ((X)->base.type>Html_Block)
#define Html_A               5
#define Html_ADDRESS         6
#define Html_APPLET          7
#define Html_AREA            8
#define Html_BASE            9
#define Html_BASEFONT        10
#define Html_B               11
#define Html_BIG             12
#define Html_BLOCKQUOTE      13
#define Html_BODY            14
#define Html_BR              15
#define Html_BUTTON          16
#define Html_CAPTION         17
#define Html_CENTER          18
#define Html_CITE            19
#define Html_CODE            20
#define Html_DD              21
#define Html_DFN             22
#define Html_DIR             23
#define Html_DIV             24
#define Html_DL              25
#define Html_DT              26
#define Html_EM              27
#define Html_FIELDSET        28
#define Html_FONT            29
#define Html_FORM            30
#define Html_FRAME           31
#define Html_FRAMESET        32
#define Html_H1              33
#define Html_H2              34
#define Html_H3              35
#define Html_H4              36
#define Html_H5              37
#define Html_H6              38
#define Html_HEAD            39
#define Html_HR              40
#define Html_HTML            41
#define Html_I               42
#define Html_IFRAME          43
#define Html_IMG             44
#define Html_INPUT           45
#define Html_ISINDEX         46
#define Html_KBD             47
#define Html_LABEL           48
#define Html_LEGEND          49
#define Html_LI              50
#define Html_LINK            51
#define Html_MAP             52
#define Html_MENU            53
#define Html_META            54
#define Html_NOFRAMES        55
#define Html_NOSCRIPT        56
#define Html_OBJECT          57
#define Html_OL              58
#define Html_OPTION          59
#define Html_P               60
#define Html_PARAM           61
#define Html_PRE             62
#define Html_S               63
#define Html_SAMP            64
#define Html_SCRIPT          65
#define Html_SELECT          66
#define Html_SMALL           67
#define Html_SPAN            68
#define Html_STRIKE          69
#define Html_STRONG          70
#define Html_STYLE           71
#define Html_SUB             72
#define Html_SUP             73
#define Html_TABLE           74
#define Html_TBODY           75
#define Html_TD              76
#define Html_TEXTAREA        77
#define Html_TFOOT           78
#define Html_TH              79
#define Html_THEAD           80
#define Html_TITLE           81
#define Html_TR              82
#define Html_TT              83
#define Html_U               84
#define Html_UL              85
#define Html_VAR             86
#define Html_COMMENT         87
#define Html_EMBED           88
#define Html_LISTING         89
#define Html_MARQUEE         90
#define Html_NEXTID          91
#define Html_NOBR            92
#define Html_NOEMBED         93
#define Html_PLAINTEXT       94
#define Html_WBR             95
#define Html_XMP             96
#define Html_BGSOUND         97
#define Html_TypeCount 98
#define HTML_MARKUP_HASH_SIZE 109
#define HTML_MARKUP_COUNT 93
