/*
 *			libtclcad/Cakefile
 */

#define SRCDIR	libtclcad
#define PRODUCTS	libtclcad.ARCH_SUF
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	tclcad_version
#define LIBRARY_TITLE		"BRL-CAD specific routines for Tcl/Tk"

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc -brtl -L../.libbu.sp3 -lbu -L../.libbn.sp3 -lbn -L../.libtcl8.4.sp3 -ltcl8.4 -L../.libtk8.4.sp3 -ltk8.4
#endif

/* Eliminate the normal BRL-CAD defines */
#undef CFLAGS
/* Keep the -64 flag, etc */
#define CFLAGS  GFLAG -I''INCDIR -I''XINCDIR

#define FILES	tkImgFmtPIX tclcad

#include "../Cakefile.lib"
#include "../Cakefile.rules"
