/*
 *			librt/Cakefile
 */
#define SRCDIR	librt
#define PRODUCTS	librt.ARCH_SUF
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

/* Separate into orderly groupings:
 *	Raytrace logic
 *	Database handling
 *	Geometry routines
 *	Utility routines
 */
#define FILES	\
	shoot \
	cut bool \
	db_open db_scan db_lookup db_io db_alloc db_walk \
	db_path db_tree db_anim \
	memalloc tabdata \
	table dir tree prep font \
	g_arb g_ars g_ebm g_ell g_half g_pg g_rec g_sph g_nurb \
	g_tgc g_torus g_vol g_arbn g_part g_pipe g_nmg \
	g_rpc g_rhc g_epa g_ehy g_eto g_grip g_hf \
	cmd mater roots \
	sphmap rtlex vlist regionfix \
	nmg_mk nmg_misc nmg_bool nmg_eval nmg_inter nmg_plot nmg_ck \
	nmg_mesh nmg_fcut nmg_class nmg_mod nmg_index \
	nmg_rt_isect nmg_rt_segs nmg_manif \
	nmg_visit nmg_info nmg_pr \
	units msr vert nmg_extrude nmg_tri nmg_fuse nmg_pt_fu \
	rtassoc \
	pr LIBRT_TIMER storage global snoise \
	rt_dspline

#define NURB_OBJ	\
        nurb_basis.o nurb_bound.o nurb_diff.o nurb_eval.o nurb_flat.o \
        nurb_knot.o nurb_norm.o nurb_poly.o nurb_ray.o nurb_refine.o \
        nurb_solve.o nurb_split.o nurb_util.o nurb_xsplit.o nurb_copy.o \
        nurb_c2.o oslo_calc.o oslo_map.o nurb_plot.o nurb_bezier.o nurb_trim.o \
	nurb_interp.o nurb_reverse.o nurb_tess.o nurb_trim_util.o


#define PLOT_OBJ	plot3.o htond.o

/* Oddly, this line needs to be present to keep IBM AIX cpp happy. */
#ifdef FAST_SQRT
#	define	EXTRA_OBJ	FAST_SQRT PLOT_OBJ NURB_OBJ
#else
#	define	EXTRA_OBJ	PLOT_OBJ NURB_OBJ
#endif

#define VERSION_VARIABLE	rt_version
#define LIBRARY_TITLE		"The BRL-CAD Ray-Tracing Library"

#include "../Cakefile.lib"

/*
 *  Special rules for additions from other directories
 */
%.o&:	libplot3,,%,o			if exist ../libplot3/%.c

#if NFS
%.o:	../libnurb/%.c			if exist ../.libnurb.MTYPE/%.o
	cp ../.libnurb.MTYPE/%.o %.o
#else
%.o:	../libnurb/%.c			if exist ../libnurb/%.o
	cp ../libnurb/%.o %.o
#endif

#include "../Cakefile.rules"
