/*
 *			liborle/Cakefile
 */

#define PRODUCTS	liborle.ARCH_SUF
#define SRCDIR	liborle
#define FILES	rle
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	liborle_version
#define LIBRARY_TITLE		"University of Utah RLE Library, Version 2"

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc
#endif

#include "../Cakefile.lib"
#include "../Cakefile.rules"
