/*
 *			liborle/Cakefile
 */

#define PRODUCTS	liborle.ARCH_SUF
#define SRCDIR	liborle
#define FILES	rle
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#include "../Cakefile.lib"
#include "../Cakefile.rules"
