'\" te	(causes both "tbl" and "eqn" to be invoked)
'\"	man_tem -- template for VMB software manual entry
.TH COMMAND 1V VMB
'\"	last edit:	85/03/22	Your name
'\"	SCCS ID:	@(#)librle.3	1.1
.SH NAME
command \- perform some action
.SH SYNOPSIS
.B command
[
.B \-x
] arg ...
.SH DESCRIPTION
.I Command\^
performs the following actions...
.P
If the
.B \-x
option is supplied,
.I command\^
also does something else...
.SH DEFINITIONS
Special
.I terms\^
are defined here.
(This section should seldom be required.)
.SH DISCUSSION
Here is the theory of operation, \fIetc.\^\fR ...
(This section is rarely useful.)
.SH HINT(S)
This program is tricky.
Here are some helpful hints ...
(This section is rarely needed.)
.SH CAVEAT(S)
These are things to watch out for,
but are not actual problems ...
(This section is rare.)
.SH WARNING(S)
You can get in trouble
if you don't look out for ...
(This section is optional.)
.SH RESTRICTIONS
This program is not fully general ...
(This section is optional.)
.SH EXAMPLE(S)
The following invocation
does something neat:
.RS
$ \|\fIcommand \|\-x \|arg1 \|arg2
.br
User input is in italics.
.br
^D\fR
.br
Computer output is in roman font.
'\" Only show computer output if it is helpful.
.RE
.SH FILES
.RI /usr/tmp/cmd ???
.br
/vld/lib/man_tem
.SH "SEE ALSO"
ash(1V), man(1), troff(1), man(5).
'\" All VMB documents have a "V" following the section number.
.SH DIAGNOSTICS
Errors cause the message
``Wow! I'm confused''
to be printed on the standard error output
and the following behavior ...
(This section may be omitted if errors ``can't happen''.)
.SH "EXIT CODES"
Exit status 0 is returned if the
.I command\^
succeeds;
otherwise various non-zero values
are returned.
(If this section is omitted,
then the
.I command\^
is assumed to return 0 status when it succeeds
and small positive non-zero values when it fails.)
.SH AUTHOR(S)
Your name, BRL/VLD-VMB
.SH BUGS
The following deficiencies are known ...
(This section may be omitted if there are no bugs.)
