#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: scrolledlistbox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish -f "$0" ${1+"$@"}
package require -exact Iwidgets 2.2

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell
. configure -background white

iwidgets::scrolledlistbox .slb -labeltext "Scrolledlistbox" \
    -vscrollmode dynamic -hscrollmode none \
    -selectmode single \
    -labelpos nw -selectioncommand {
        puts "click: [.slb getcurselection]"
    }

pack .slb -padx 4 -pady 4

.slb configure -items {Hello World!}
.slb insert 1 Cruel
.slb delete "Hello"
.slb insert 0 "Goodbye"

button .add -text "Add" -command {
    .slb insert end "Goodbye!"
}
pack .add -padx 4 -pady 4

button .del -text "Delete" -command {
    .slb delete 0
}
pack .del -padx 4 -pady 4
