#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: selectionbox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish -f "$0" ${1+"$@"}
package require -exact Iwidgets 2.2

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::selectionbox .sb -selectionlabel "Font:" -height 2i -items {
    Ariel
    Courier
    Helvetica
    Knarly
    Lucida
    Rumpus
    Symbol
    Times
    "Zapf Dingbats"
}
pack .sb
