/* 
 * zlibtclStubInit.c --
 */

#include "zlibtcl.h"

/*
 * Remove macros that will interfere with the definitions below.
 */


/*
 * WARNING: The contents of this file is automatically generated by the
 * genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the zlibtcl.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

ZlibtclStubs zlibtclStubs = {
    TCL_STUB_MAGIC,
    NULL,
    zlibVersion, /* 0 */
    zError, /* 1 */
    crc32, /* 2 */
    adler32, /* 3 */
    NULL, /* 4 */
    NULL, /* 5 */
    NULL, /* 6 */
    NULL, /* 7 */
    NULL, /* 8 */
    NULL, /* 9 */
    deflateInit_, /* 10 */
    deflateInit2_, /* 11 */
    deflate, /* 12 */
    deflateEnd, /* 13 */
    deflateSetDictionary, /* 14 */
    deflateCopy, /* 15 */
    deflateReset, /* 16 */
    deflateParams, /* 17 */
    compress, /* 18 */
    compress2, /* 19 */
    inflateInit_, /* 20 */
    inflateInit2_, /* 21 */
    inflate, /* 22 */
    inflateEnd, /* 23 */
    inflateSetDictionary, /* 24 */
    inflateSync, /* 25 */
    inflateReset, /* 26 */
    uncompress, /* 27 */
    NULL, /* 28 */
    NULL, /* 29 */
    gzopen, /* 30 */
    gzdopen, /* 31 */
    gzsetparams, /* 32 */
    gzread, /* 33 */
    gzwrite, /* 34 */
    NULL, /* 35 */
    gzputs, /* 36 */
    gzgets, /* 37 */
    gzputc, /* 38 */
    gzgetc, /* 39 */
    gzflush, /* 40 */
    gzseek, /* 41 */
    gzrewind, /* 42 */
    gztell, /* 43 */
    gzeof, /* 44 */
    gzclose, /* 45 */
    gzerror, /* 46 */
};

/* !END!: Do not edit above this line. */
