/* 
 * pngtclStubInit.c --
 */

#include "pngtcl.h"

/*
 * Remove macros that will interfere with the definitions below.
 */

/*
 * WARNING: The contents of this file is automatically generated by the
 * genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the pngtcl.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

PngtclStubs pngtclStubs = {
    TCL_STUB_MAGIC,
    NULL,
    png_access_version_number, /* 0 */
    png_set_sig_bytes, /* 1 */
    png_sig_cmp, /* 2 */
    png_check_sig, /* 3 */
    png_create_read_struct, /* 4 */
    png_create_write_struct, /* 5 */
    png_get_compression_buffer_size, /* 6 */
    png_set_compression_buffer_size, /* 7 */
    png_reset_zstream, /* 8 */
#if !defined(PNG_USER_MEM_SUPPORTED)
    NULL, /* 9 */
#else  /* !PNG_USER_MEM_SUPPORTED */
    png_create_read_struct_2, /* 9 */
#endif /* !PNG_USER_MEM_SUPPORTED */
#if !defined(PNG_USER_MEM_SUPPORTED)
    NULL, /* 10 */
#else  /* !PNG_USER_MEM_SUPPORTED */
    png_create_write_struct_2, /* 10 */
#endif /* !PNG_USER_MEM_SUPPORTED */
    png_write_chunk, /* 11 */
    png_write_chunk_start, /* 12 */
    png_write_chunk_data, /* 13 */
    png_write_chunk_end, /* 14 */
    png_create_info_struct, /* 15 */
    png_info_init, /* 16 */
    png_write_info_before_PLTE, /* 17 */
    png_write_info, /* 18 */
    png_read_info, /* 19 */
#if !defined(PNG_TIME_RFC1123_SUPPORTED)
    NULL, /* 20 */
#else  /* !PNG_TIME_RFC1123_SUPPORTED */
    png_convert_to_rfc1123, /* 20 */
#endif /* !PNG_TIME_RFC1123_SUPPORTED */
#if defined(_WIN32_WCE) || !defined(PNG_WRITE_tIME_SUPPORTED)
    NULL, /* 21 */
#else  /* _WIN32_WCE !PNG_WRITE_tIME_SUPPORTED */
    png_convert_from_struct_tm, /* 21 */
#endif /* _WIN32_WCE !PNG_WRITE_tIME_SUPPORTED */
#if defined(_WIN32_WCE) || !defined(PNG_WRITE_tIME_SUPPORTED)
    NULL, /* 22 */
#else  /* _WIN32_WCE !PNG_WRITE_tIME_SUPPORTED */
    png_convert_from_time_t, /* 22 */
#endif /* _WIN32_WCE !PNG_WRITE_tIME_SUPPORTED */
#if !defined(PNG_READ_EXPAND_SUPPORTED)
    NULL, /* 23 */
#else  /* !PNG_READ_EXPAND_SUPPORTED */
    png_set_expand, /* 23 */
#endif /* !PNG_READ_EXPAND_SUPPORTED */
#if !defined(PNG_READ_EXPAND_SUPPORTED)
    NULL, /* 24 */
#else  /* !PNG_READ_EXPAND_SUPPORTED */
    png_set_gray_1_2_4_to_8, /* 24 */
#endif /* !PNG_READ_EXPAND_SUPPORTED */
#if !defined(PNG_READ_EXPAND_SUPPORTED)
    NULL, /* 25 */
#else  /* !PNG_READ_EXPAND_SUPPORTED */
    png_set_palette_to_rgb, /* 25 */
#endif /* !PNG_READ_EXPAND_SUPPORTED */
#if !defined(PNG_READ_EXPAND_SUPPORTED)
    NULL, /* 26 */
#else  /* !PNG_READ_EXPAND_SUPPORTED */
    png_set_tRNS_to_alpha, /* 26 */
#endif /* !PNG_READ_EXPAND_SUPPORTED */
#if !defined(PNG_READ_BGR_SUPPORTED) && !defined(PNG_WRITE_BGR_SUPPORTED)
    NULL, /* 27 */
#else  /* !PNG_READ_BGR_SUPPORTED !PNG_WRITE_BGR_SUPPORTED */
    png_set_bgr, /* 27 */
#endif /* !PNG_READ_BGR_SUPPORTED !PNG_WRITE_BGR_SUPPORTED */
#if !defined(PNG_READ_GRAY_TO_RGB_SUPPORTED)
    NULL, /* 28 */
#else  /* !PNG_READ_GRAY_TO_RGB_SUPPORTED */
    png_set_gray_to_rgb, /* 28 */
#endif /* !PNG_READ_GRAY_TO_RGB_SUPPORTED */
#if !defined(PNG_READ_RGB_TO_GRAY_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 29 */
#else  /* !PNG_READ_RGB_TO_GRAY_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_rgb_to_gray, /* 29 */
#endif /* !PNG_READ_RGB_TO_GRAY_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_READ_RGB_TO_GRAY_SUPPORTED)
    NULL, /* 30 */
#else  /* !PNG_READ_RGB_TO_GRAY_SUPPORTED */
    png_set_rgb_to_gray_fixed, /* 30 */
#endif /* !PNG_READ_RGB_TO_GRAY_SUPPORTED */
#if !defined(PNG_READ_RGB_TO_GRAY_SUPPORTED)
    NULL, /* 31 */
#else  /* !PNG_READ_RGB_TO_GRAY_SUPPORTED */
    png_get_rgb_to_gray_status, /* 31 */
#endif /* !PNG_READ_RGB_TO_GRAY_SUPPORTED */
    png_build_grayscale_palette, /* 32 */
#if !defined(PNG_READ_STRIP_ALPHA_SUPPORTED)
    NULL, /* 33 */
#else  /* !PNG_READ_STRIP_ALPHA_SUPPORTED */
    png_set_strip_alpha, /* 33 */
#endif /* !PNG_READ_STRIP_ALPHA_SUPPORTED */
#if !defined(PNG_READ_SWAP_ALPHA_SUPPORTED) && !defined(PNG_WRITE_SWAP_ALPHA_SUPPORTED)
    NULL, /* 34 */
#else  /* !PNG_READ_SWAP_ALPHA_SUPPORTED !PNG_WRITE_SWAP_ALPHA_SUPPORTED */
    png_set_swap_alpha, /* 34 */
#endif /* !PNG_READ_SWAP_ALPHA_SUPPORTED !PNG_WRITE_SWAP_ALPHA_SUPPORTED */
#if !defined(PNG_READ_INVERT_ALPHA_SUPPORTED) && !defined(PNG_WRITE_INVERT_ALPHA_SUPPORTED)
    NULL, /* 35 */
#else  /* !PNG_READ_INVERT_ALPHA_SUPPORTED !PNG_WRITE_INVERT_ALPHA_SUPPORTED */
    png_set_invert_alpha, /* 35 */
#endif /* !PNG_READ_INVERT_ALPHA_SUPPORTED !PNG_WRITE_INVERT_ALPHA_SUPPORTED */
#if !defined(PNG_READ_FILLER_SUPPORTED) && !defined(PNG_WRITE_FILLER_SUPPORTED)
    NULL, /* 36 */
#else  /* !PNG_READ_FILLER_SUPPORTED !PNG_WRITE_FILLER_SUPPORTED */
    png_set_filler, /* 36 */
#endif /* !PNG_READ_FILLER_SUPPORTED !PNG_WRITE_FILLER_SUPPORTED */
#if !defined(PNG_READ_SWAP_SUPPORTED) && !defined(PNG_WRITE_SWAP_SUPPORTED)
    NULL, /* 37 */
#else  /* !PNG_READ_SWAP_SUPPORTED !PNG_WRITE_SWAP_SUPPORTED */
    png_set_swap, /* 37 */
#endif /* !PNG_READ_SWAP_SUPPORTED !PNG_WRITE_SWAP_SUPPORTED */
#if !defined(PNG_READ_PACK_SUPPORTED) && !defined(PNG_WRITE_PACK_SUPPORTED)
    NULL, /* 38 */
#else  /* !PNG_READ_PACK_SUPPORTED !PNG_WRITE_PACK_SUPPORTED */
    png_set_packing, /* 38 */
#endif /* !PNG_READ_PACK_SUPPORTED !PNG_WRITE_PACK_SUPPORTED */
#if !defined(PNG_READ_PACKSWAP_SUPPORTED) && !defined(PNG_WRITE_PACKSWAP_SUPPORTED)
    NULL, /* 39 */
#else  /* !PNG_READ_PACKSWAP_SUPPORTED !PNG_WRITE_PACKSWAP_SUPPORTED */
    png_set_packswap, /* 39 */
#endif /* !PNG_READ_PACKSWAP_SUPPORTED !PNG_WRITE_PACKSWAP_SUPPORTED */
#if !defined(PNG_READ_SHIFT_SUPPORTED) && !defined(PNG_WRITE_SHIFT_SUPPORTED)
    NULL, /* 40 */
#else  /* !PNG_READ_SHIFT_SUPPORTED !PNG_WRITE_SHIFT_SUPPORTED */
    png_set_shift, /* 40 */
#endif /* !PNG_READ_SHIFT_SUPPORTED !PNG_WRITE_SHIFT_SUPPORTED */
#if !defined(PNG_READ_INTERLACING_SUPPORTED) && !defined(PNG_WRITE_INTERLACING_SUPPORTED)
    NULL, /* 41 */
#else  /* !PNG_READ_INTERLACING_SUPPORTED !PNG_WRITE_INTERLACING_SUPPORTED */
    png_set_interlace_handling, /* 41 */
#endif /* !PNG_READ_INTERLACING_SUPPORTED !PNG_WRITE_INTERLACING_SUPPORTED */
#if !defined(PNG_READ_INVERT_SUPPORTED) && !defined(PNG_WRITE_INVERT_SUPPORTED)
    NULL, /* 42 */
#else  /* !PNG_READ_INVERT_SUPPORTED !PNG_WRITE_INVERT_SUPPORTED */
    png_set_invert_mono, /* 42 */
#endif /* !PNG_READ_INVERT_SUPPORTED !PNG_WRITE_INVERT_SUPPORTED */
#if !defined(PNG_READ_BACKGROUND_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 43 */
#else  /* !PNG_READ_BACKGROUND_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_background, /* 43 */
#endif /* !PNG_READ_BACKGROUND_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_READ_16_TO_8_SUPPORTED)
    NULL, /* 44 */
#else  /* !PNG_READ_16_TO_8_SUPPORTED */
    png_set_strip_16, /* 44 */
#endif /* !PNG_READ_16_TO_8_SUPPORTED */
#if !defined(PNG_READ_DITHER_SUPPORTED)
    NULL, /* 45 */
#else  /* !PNG_READ_DITHER_SUPPORTED */
    png_set_dither, /* 45 */
#endif /* !PNG_READ_DITHER_SUPPORTED */
#if !defined(PNG_READ_GAMMA_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 46 */
#else  /* !PNG_READ_GAMMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_gamma, /* 46 */
#endif /* !PNG_READ_GAMMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_READ_EMPTY_PLTE_SUPPORTED) && !defined(PNG_WRITE_EMPTY_PLTE_SUPPORTED)
    NULL, /* 47 */
#else  /* !PNG_READ_EMPTY_PLTE_SUPPORTED !PNG_WRITE_EMPTY_PLTE_SUPPORTED */
    png_permit_empty_plte, /* 47 */
#endif /* !PNG_READ_EMPTY_PLTE_SUPPORTED !PNG_WRITE_EMPTY_PLTE_SUPPORTED */
#if !defined(PNG_WRITE_FLUSH_SUPPORTED)
    NULL, /* 48 */
#else  /* !PNG_WRITE_FLUSH_SUPPORTED */
    png_set_flush, /* 48 */
#endif /* !PNG_WRITE_FLUSH_SUPPORTED */
#if !defined(PNG_WRITE_FLUSH_SUPPORTED)
    NULL, /* 49 */
#else  /* !PNG_WRITE_FLUSH_SUPPORTED */
    png_write_flush, /* 49 */
#endif /* !PNG_WRITE_FLUSH_SUPPORTED */
    png_start_read_image, /* 50 */
    png_read_update_info, /* 51 */
    png_read_rows, /* 52 */
    png_read_row, /* 53 */
    png_read_image, /* 54 */
    png_write_row, /* 55 */
    png_write_rows, /* 56 */
    png_write_image, /* 57 */
    png_write_end, /* 58 */
    png_read_end, /* 59 */
    png_destroy_info_struct, /* 60 */
    png_destroy_read_struct, /* 61 */
    png_read_destroy, /* 62 */
    png_destroy_write_struct, /* 63 */
    NULL, /* 64 */
    png_write_destroy, /* 65 */
    png_set_crc_action, /* 66 */
    png_set_filter, /* 67 */
#if !defined(PNG_WRITE_WEIGHTED_FILTER_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 68 */
#else  /* !PNG_WRITE_WEIGHTED_FILTER_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_filter_heuristics, /* 68 */
#endif /* !PNG_WRITE_WEIGHTED_FILTER_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_compression_level, /* 69 */
    png_set_compression_mem_level, /* 70 */
    png_set_compression_strategy, /* 71 */
    png_set_compression_window_bits, /* 72 */
    png_set_compression_method, /* 73 */
#if defined(PNG_NO_STDIO)
    NULL, /* 74 */
#else  /* PNG_NO_STDIO */
    png_init_io, /* 74 */
#endif /* PNG_NO_STDIO */
    png_set_error_fn, /* 75 */
    png_get_error_ptr, /* 76 */
    png_set_write_fn, /* 77 */
    png_set_read_fn, /* 78 */
    png_get_io_ptr, /* 79 */
    png_set_read_status_fn, /* 80 */
    png_set_write_status_fn, /* 81 */
#if !defined(PNG_USER_MEM_SUPPORTED)
    NULL, /* 82 */
#else  /* !PNG_USER_MEM_SUPPORTED */
    png_set_mem_fn, /* 82 */
#endif /* !PNG_USER_MEM_SUPPORTED */
#if !defined(PNG_USER_MEM_SUPPORTED)
    NULL, /* 83 */
#else  /* !PNG_USER_MEM_SUPPORTED */
    png_get_mem_ptr, /* 83 */
#endif /* !PNG_USER_MEM_SUPPORTED */
#if !defined(PNG_READ_USER_TRANSFORM_SUPPORTED) && !defined(PNG_LEGACY_SUPPORTED)
    NULL, /* 84 */
#else  /* !PNG_READ_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
    png_set_read_user_transform_fn, /* 84 */
#endif /* !PNG_READ_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
#if !defined(PNG_WRITE_USER_TRANSFORM_SUPPORTED) && !defined(PNG_LEGACY_SUPPORTED)
    NULL, /* 85 */
#else  /* !PNG_WRITE_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
    png_set_write_user_transform_fn, /* 85 */
#endif /* !PNG_WRITE_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
#if !defined(PNG_READ_USER_TRANSFORM_SUPPORTED) && !defined(PNG_WRITE_USER_TRANSFORM_SUPPORTED) && !defined(PNG_LEGACY_SUPPORTED)
    NULL, /* 86 */
#else  /* !PNG_READ_USER_TRANSFORM_SUPPORTED !PNG_WRITE_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
    png_set_user_transform_info, /* 86 */
#endif /* !PNG_READ_USER_TRANSFORM_SUPPORTED !PNG_WRITE_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
#if !defined(PNG_READ_USER_TRANSFORM_SUPPORTED) && !defined(PNG_WRITE_USER_TRANSFORM_SUPPORTED) && !defined(PNG_LEGACY_SUPPORTED)
    NULL, /* 87 */
#else  /* !PNG_READ_USER_TRANSFORM_SUPPORTED !PNG_WRITE_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
    png_get_user_transform_ptr, /* 87 */
#endif /* !PNG_READ_USER_TRANSFORM_SUPPORTED !PNG_WRITE_USER_TRANSFORM_SUPPORTED !PNG_LEGACY_SUPPORTED */
#if !defined(PNG_READ_USER_CHUNKS_SUPPORTED)
    NULL, /* 88 */
#else  /* !PNG_READ_USER_CHUNKS_SUPPORTED */
    png_set_read_user_chunk_fn, /* 88 */
#endif /* !PNG_READ_USER_CHUNKS_SUPPORTED */
#if !defined(PNG_READ_USER_CHUNKS_SUPPORTED)
    NULL, /* 89 */
#else  /* !PNG_READ_USER_CHUNKS_SUPPORTED */
    png_get_user_chunk_ptr, /* 89 */
#endif /* !PNG_READ_USER_CHUNKS_SUPPORTED */
#if !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 90 */
#else  /* !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_set_progressive_read_fn, /* 90 */
#endif /* !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 91 */
#else  /* !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_get_progressive_ptr, /* 91 */
#endif /* !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 92 */
#else  /* !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_process_data, /* 92 */
#endif /* !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 93 */
#else  /* !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_progressive_combine_row, /* 93 */
#endif /* !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_malloc, /* 94 */
    png_free, /* 95 */
    png_free_data, /* 96 */
#if !defined(PNG_FREE_ME_SUPPORTED)
    NULL, /* 97 */
#else  /* !PNG_FREE_ME_SUPPORTED */
    png_data_freer, /* 97 */
#endif /* !PNG_FREE_ME_SUPPORTED */
#if !defined(PNG_USER_MEM_SUPPORTED)
    NULL, /* 98 */
#else  /* !PNG_USER_MEM_SUPPORTED */
    png_malloc_default, /* 98 */
#endif /* !PNG_USER_MEM_SUPPORTED */
#if !defined(PNG_USER_MEM_SUPPORTED)
    NULL, /* 99 */
#else  /* !PNG_USER_MEM_SUPPORTED */
    png_free_default, /* 99 */
#endif /* !PNG_USER_MEM_SUPPORTED */
    png_memcpy_check, /* 100 */
    png_memset_check, /* 101 */
#if !defined(USE_FAR_KEYWORD)
    NULL, /* 102 */
#else  /* !USE_FAR_KEYWORD */
    png_far_to_near, /* 102 */
#endif /* !USE_FAR_KEYWORD */
    png_error, /* 103 */
    png_chunk_error, /* 104 */
    png_warning, /* 105 */
    png_chunk_warning, /* 106 */
    png_get_valid, /* 107 */
    png_get_rowbytes, /* 108 */
#if !defined(PNG_INFO_IMAGE_SUPPORTED)
    NULL, /* 109 */
#else  /* !PNG_INFO_IMAGE_SUPPORTED */
    png_get_rows, /* 109 */
#endif /* !PNG_INFO_IMAGE_SUPPORTED */
#if !defined(PNG_INFO_IMAGE_SUPPORTED)
    NULL, /* 110 */
#else  /* !PNG_INFO_IMAGE_SUPPORTED */
    png_set_rows, /* 110 */
#endif /* !PNG_INFO_IMAGE_SUPPORTED */
    png_get_channels, /* 111 */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 112 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_image_width, /* 112 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 113 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_image_height, /* 113 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 114 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_bit_depth, /* 114 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 115 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_color_type, /* 115 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 116 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_filter_type, /* 116 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 117 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_interlace_type, /* 117 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 118 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_compression_type, /* 118 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 119 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_pixels_per_meter, /* 119 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 120 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_x_pixels_per_meter, /* 120 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 121 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_y_pixels_per_meter, /* 121 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 122 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_get_pixel_aspect_ratio, /* 122 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 123 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_x_offset_pixels, /* 123 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 124 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_y_offset_pixels, /* 124 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 125 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_x_offset_microns, /* 125 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
#if !defined(PNG_EASY_ACCESS_SUPPORTED)
    NULL, /* 126 */
#else  /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_y_offset_microns, /* 126 */
#endif /* !PNG_EASY_ACCESS_SUPPORTED */
    png_get_signature, /* 127 */
#if !defined(PNG_READ_bKGD_SUPPORTED)
    NULL, /* 128 */
#else  /* !PNG_READ_bKGD_SUPPORTED */
    png_get_bKGD, /* 128 */
#endif /* !PNG_READ_bKGD_SUPPORTED */
#if !defined(PNG_bKGD_SUPPORTED)
    NULL, /* 129 */
#else  /* !PNG_bKGD_SUPPORTED */
    png_set_bKGD, /* 129 */
#endif /* !PNG_bKGD_SUPPORTED */
#if !defined(PNG_READ_cHRM_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 130 */
#else  /* !PNG_READ_cHRM_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_get_cHRM, /* 130 */
#endif /* !PNG_READ_cHRM_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_READ_cHRM_SUPPORTED) || !defined(PNG_FIXED_POINT_SUPPORTED)
    NULL, /* 131 */
#else  /* !PNG_READ_cHRM_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
    png_get_cHRM_fixed, /* 131 */
#endif /* !PNG_READ_cHRM_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
#if !defined(PNG_cHRM_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 132 */
#else  /* !PNG_cHRM_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_cHRM, /* 132 */
#endif /* !PNG_cHRM_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_cHRM_SUPPORTED) || !defined(PNG_FIXED_POINT_SUPPORTED)
    NULL, /* 133 */
#else  /* !PNG_cHRM_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
    png_set_cHRM_fixed, /* 133 */
#endif /* !PNG_cHRM_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
#if !defined(PNG_READ_gAMA_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 134 */
#else  /* !PNG_READ_gAMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_get_gAMA, /* 134 */
#endif /* !PNG_READ_gAMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_READ_gAMA_SUPPORTED)
    NULL, /* 135 */
#else  /* !PNG_READ_gAMA_SUPPORTED */
    png_get_gAMA_fixed, /* 135 */
#endif /* !PNG_READ_gAMA_SUPPORTED */
#if !defined(PNG_gAMA_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 136 */
#else  /* !PNG_gAMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_gAMA, /* 136 */
#endif /* !PNG_gAMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_gAMA_SUPPORTED)
    NULL, /* 137 */
#else  /* !PNG_gAMA_SUPPORTED */
    png_set_gAMA_fixed, /* 137 */
#endif /* !PNG_gAMA_SUPPORTED */
#if !defined(PNG_READ_hIST_SUPPORTED)
    NULL, /* 138 */
#else  /* !PNG_READ_hIST_SUPPORTED */
    png_get_hIST, /* 138 */
#endif /* !PNG_READ_hIST_SUPPORTED */
#if !defined(PNG_hIST_SUPPORTED)
    NULL, /* 139 */
#else  /* !PNG_hIST_SUPPORTED */
    png_set_hIST, /* 139 */
#endif /* !PNG_hIST_SUPPORTED */
    png_get_IHDR, /* 140 */
    png_set_IHDR, /* 141 */
#if !defined(PNG_READ_oFFs_SUPPORTED)
    NULL, /* 142 */
#else  /* !PNG_READ_oFFs_SUPPORTED */
    png_get_oFFs, /* 142 */
#endif /* !PNG_READ_oFFs_SUPPORTED */
#if !defined(PNG_oFFs_SUPPORTED)
    NULL, /* 143 */
#else  /* !PNG_oFFs_SUPPORTED */
    png_set_oFFs, /* 143 */
#endif /* !PNG_oFFs_SUPPORTED */
#if !defined(PNG_READ_pCAL_SUPPORTED)
    NULL, /* 144 */
#else  /* !PNG_READ_pCAL_SUPPORTED */
    png_get_pCAL, /* 144 */
#endif /* !PNG_READ_pCAL_SUPPORTED */
#if !defined(PNG_pCAL_SUPPORTED)
    NULL, /* 145 */
#else  /* !PNG_pCAL_SUPPORTED */
    png_set_pCAL, /* 145 */
#endif /* !PNG_pCAL_SUPPORTED */
#if !defined(PNG_READ_pHYs_SUPPORTED)
    NULL, /* 146 */
#else  /* !PNG_READ_pHYs_SUPPORTED */
    png_get_pHYs, /* 146 */
#endif /* !PNG_READ_pHYs_SUPPORTED */
#if !defined(PNG_pHYs_SUPPORTED)
    NULL, /* 147 */
#else  /* !PNG_pHYs_SUPPORTED */
    png_set_pHYs, /* 147 */
#endif /* !PNG_pHYs_SUPPORTED */
    png_get_PLTE, /* 148 */
    png_set_PLTE, /* 149 */
#if !defined(PNG_READ_sBIT_SUPPORTED)
    NULL, /* 150 */
#else  /* !PNG_READ_sBIT_SUPPORTED */
    png_get_sBIT, /* 150 */
#endif /* !PNG_READ_sBIT_SUPPORTED */
#if !defined(PNG_sBIT_SUPPORTED)
    NULL, /* 151 */
#else  /* !PNG_sBIT_SUPPORTED */
    png_set_sBIT, /* 151 */
#endif /* !PNG_sBIT_SUPPORTED */
#if !defined(PNG_READ_sRGB_SUPPORTED)
    NULL, /* 152 */
#else  /* !PNG_READ_sRGB_SUPPORTED */
    png_get_sRGB, /* 152 */
#endif /* !PNG_READ_sRGB_SUPPORTED */
#if !defined(PNG_sRGB_SUPPORTED)
    NULL, /* 153 */
#else  /* !PNG_sRGB_SUPPORTED */
    png_set_sRGB, /* 153 */
#endif /* !PNG_sRGB_SUPPORTED */
#if !defined(PNG_sRGB_SUPPORTED)
    NULL, /* 154 */
#else  /* !PNG_sRGB_SUPPORTED */
    png_set_sRGB_gAMA_and_cHRM, /* 154 */
#endif /* !PNG_sRGB_SUPPORTED */
#if !defined(PNG_READ_iCCP_SUPPORTED)
    NULL, /* 155 */
#else  /* !PNG_READ_iCCP_SUPPORTED */
    png_get_iCCP, /* 155 */
#endif /* !PNG_READ_iCCP_SUPPORTED */
#if !defined(PNG_iCCP_SUPPORTED)
    NULL, /* 156 */
#else  /* !PNG_iCCP_SUPPORTED */
    png_set_iCCP, /* 156 */
#endif /* !PNG_iCCP_SUPPORTED */
#if !defined(PNG_READ_sPLT_SUPPORTED)
    NULL, /* 157 */
#else  /* !PNG_READ_sPLT_SUPPORTED */
    png_get_sPLT, /* 157 */
#endif /* !PNG_READ_sPLT_SUPPORTED */
#if !defined(PNG_sPLT_SUPPORTED)
    NULL, /* 158 */
#else  /* !PNG_sPLT_SUPPORTED */
    png_set_sPLT, /* 158 */
#endif /* !PNG_sPLT_SUPPORTED */
#if !defined(PNG_READ_TEXT_SUPPORTED)
    NULL, /* 159 */
#else  /* !PNG_READ_TEXT_SUPPORTED */
    png_get_text, /* 159 */
#endif /* !PNG_READ_TEXT_SUPPORTED */
#if !defined(PNG_TEXT_SUPPORTED)
    NULL, /* 160 */
#else  /* !PNG_TEXT_SUPPORTED */
    png_set_text, /* 160 */
#endif /* !PNG_TEXT_SUPPORTED */
#if !defined(PNG_READ_tIME_SUPPORTED)
    NULL, /* 161 */
#else  /* !PNG_READ_tIME_SUPPORTED */
    png_get_tIME, /* 161 */
#endif /* !PNG_READ_tIME_SUPPORTED */
#if !defined(PNG_tIME_SUPPORTED)
    NULL, /* 162 */
#else  /* !PNG_tIME_SUPPORTED */
    png_set_tIME, /* 162 */
#endif /* !PNG_tIME_SUPPORTED */
#if !defined(PNG_READ_tRNS_SUPPORTED)
    NULL, /* 163 */
#else  /* !PNG_READ_tRNS_SUPPORTED */
    png_get_tRNS, /* 163 */
#endif /* !PNG_READ_tRNS_SUPPORTED */
#if !defined(PNG_tRNS_SUPPORTED)
    NULL, /* 164 */
#else  /* !PNG_tRNS_SUPPORTED */
    png_set_tRNS, /* 164 */
#endif /* !PNG_tRNS_SUPPORTED */
#if !defined(PNG_READ_sCAL_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 165 */
#else  /* !PNG_READ_sCAL_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_get_sCAL, /* 165 */
#endif /* !PNG_READ_sCAL_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_READ_sCAL_SUPPORTED) || defined(PNG_FLOATING_POINT_SUPPORTED) || !defined(PNG_FIXED_POINT_SUPPORTED)
    NULL, /* 166 */
#else  /* !PNG_READ_sCAL_SUPPORTED PNG_FLOATING_POINT_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
    png_get_sCAL_s, /* 166 */
#endif /* !PNG_READ_sCAL_SUPPORTED PNG_FLOATING_POINT_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
#if !defined(PNG_sCAL_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 167 */
#else  /* !PNG_sCAL_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_set_sCAL, /* 167 */
#endif /* !PNG_sCAL_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_sCAL_SUPPORTED) || defined(PNG_FLOATING_POINT_SUPPORTED) || !defined(PNG_FIXED_POINT_SUPPORTED)
    NULL, /* 168 */
#else  /* !PNG_sCAL_SUPPORTED PNG_FLOATING_POINT_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
    png_set_sCAL_s, /* 168 */
#endif /* !PNG_sCAL_SUPPORTED PNG_FLOATING_POINT_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
#if !defined(PNG_UNKNOWN_CHUNKS_SUPPORTED)
    NULL, /* 169 */
#else  /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
    png_set_keep_unknown_chunks, /* 169 */
#endif /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
#if !defined(PNG_UNKNOWN_CHUNKS_SUPPORTED)
    NULL, /* 170 */
#else  /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
    png_set_unknown_chunks, /* 170 */
#endif /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
#if !defined(PNG_UNKNOWN_CHUNKS_SUPPORTED)
    NULL, /* 171 */
#else  /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
    png_set_unknown_chunk_location, /* 171 */
#endif /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
#if !defined(PNG_UNKNOWN_CHUNKS_SUPPORTED)
    NULL, /* 172 */
#else  /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
    png_get_unknown_chunks, /* 172 */
#endif /* !PNG_UNKNOWN_CHUNKS_SUPPORTED */
    png_set_invalid, /* 173 */
#if !defined(PNG_INFO_IMAGE_SUPPORTED)
    NULL, /* 174 */
#else  /* !PNG_INFO_IMAGE_SUPPORTED */
    png_read_png, /* 174 */
#endif /* !PNG_INFO_IMAGE_SUPPORTED */
#if !defined(PNG_INFO_IMAGE_SUPPORTED)
    NULL, /* 175 */
#else  /* !PNG_INFO_IMAGE_SUPPORTED */
    png_write_png, /* 175 */
#endif /* !PNG_INFO_IMAGE_SUPPORTED */
#if !defined(PNG_INTERNAL) || defined(PNG_USE_GLOBAL_ARRAYS) || defined(PNG_NO_EXTERN) && !defined(PNG_ALWAYS_EXTERN)
    NULL, /* 176 */
#else  /* !PNG_INTERNAL PNG_USE_GLOBAL_ARRAYS PNG_NO_EXTERN !PNG_ALWAYS_EXTERN */
    png_sig_bytes, /* 176 */
#endif /* !PNG_INTERNAL PNG_USE_GLOBAL_ARRAYS PNG_NO_EXTERN !PNG_ALWAYS_EXTERN */
    png_get_copyright, /* 177 */
    png_get_header_ver, /* 178 */
    png_get_header_version, /* 179 */
    png_get_libpng_ver, /* 180 */
#if !defined(PNG_INTERNAL) || defined(PNG_READ_BIG_ENDIAN_SUPPORTED) || !defined(PNG_READ_pCAL_SUPPORTED) && !defined(PNG_READ_oFFs_SUPPORTED)
    NULL, /* 181 */
#else  /* !PNG_INTERNAL PNG_READ_BIG_ENDIAN_SUPPORTED !PNG_READ_pCAL_SUPPORTED !PNG_READ_oFFs_SUPPORTED */
    png_get_int_32, /* 181 */
#endif /* !PNG_INTERNAL PNG_READ_BIG_ENDIAN_SUPPORTED !PNG_READ_pCAL_SUPPORTED !PNG_READ_oFFs_SUPPORTED */
#if !defined(PNG_INTERNAL) || defined(PNG_READ_BIG_ENDIAN_SUPPORTED)
    NULL, /* 182 */
#else  /* !PNG_INTERNAL PNG_READ_BIG_ENDIAN_SUPPORTED */
    png_get_uint_32, /* 182 */
#endif /* !PNG_INTERNAL PNG_READ_BIG_ENDIAN_SUPPORTED */
#if !defined(PNG_INTERNAL) || defined(PNG_READ_BIG_ENDIAN_SUPPORTED)
    NULL, /* 183 */
#else  /* !PNG_INTERNAL PNG_READ_BIG_ENDIAN_SUPPORTED */
    png_get_uint_16, /* 183 */
#endif /* !PNG_INTERNAL PNG_READ_BIG_ENDIAN_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 184 */
#else  /* !PNG_INTERNAL */
    png_read_init, /* 184 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 185 */
#else  /* !PNG_INTERNAL */
    png_read_init_2, /* 185 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 186 */
#else  /* !PNG_INTERNAL */
    png_write_init, /* 186 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 187 */
#else  /* !PNG_INTERNAL */
    png_write_init_2, /* 187 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 188 */
#else  /* !PNG_INTERNAL */
    png_create_struct, /* 188 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 189 */
#else  /* !PNG_INTERNAL */
    png_destroy_struct, /* 189 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 190 */
#else  /* !PNG_INTERNAL */
    png_create_struct_2, /* 190 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 191 */
#else  /* !PNG_INTERNAL */
    png_destroy_struct_2, /* 191 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 192 */
#else  /* !PNG_INTERNAL */
    png_info_destroy, /* 192 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 193 */
#else  /* !PNG_INTERNAL */
    png_zalloc, /* 193 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 194 */
#else  /* !PNG_INTERNAL */
    png_zfree, /* 194 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 195 */
#else  /* !PNG_INTERNAL */
    png_reset_crc, /* 195 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 196 */
#else  /* !PNG_INTERNAL */
    png_write_data, /* 196 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 197 */
#else  /* !PNG_INTERNAL */
    png_read_data, /* 197 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 198 */
#else  /* !PNG_INTERNAL */
    png_crc_read, /* 198 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_zTXt_SUPPORTED) && !defined(PNG_READ_iTXt_SUPPORTED) && !defined(PNG_READ_iCCP_SUPPORTED) && !defined(PNG_READ_sPLT_SUPPORTED)
    NULL, /* 199 */
#else  /* !PNG_INTERNAL !PNG_READ_zTXt_SUPPORTED !PNG_READ_iTXt_SUPPORTED !PNG_READ_iCCP_SUPPORTED !PNG_READ_sPLT_SUPPORTED */
    png_decompress_chunk, /* 199 */
#endif /* !PNG_INTERNAL !PNG_READ_zTXt_SUPPORTED !PNG_READ_iTXt_SUPPORTED !PNG_READ_iCCP_SUPPORTED !PNG_READ_sPLT_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 200 */
#else  /* !PNG_INTERNAL */
    png_crc_finish, /* 200 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 201 */
#else  /* !PNG_INTERNAL */
    png_crc_error, /* 201 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 202 */
#else  /* !PNG_INTERNAL */
    png_calculate_crc, /* 202 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_FLUSH_SUPPORTED)
    NULL, /* 203 */
#else  /* !PNG_INTERNAL !PNG_WRITE_FLUSH_SUPPORTED */
    png_flush, /* 203 */
#endif /* !PNG_INTERNAL !PNG_WRITE_FLUSH_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 204 */
#else  /* !PNG_INTERNAL */
    png_save_uint_32, /* 204 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_pCAL_SUPPORTED)
    NULL, /* 205 */
#else  /* !PNG_INTERNAL !PNG_WRITE_pCAL_SUPPORTED */
    png_save_int_32, /* 205 */
#endif /* !PNG_INTERNAL !PNG_WRITE_pCAL_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 206 */
#else  /* !PNG_INTERNAL */
    png_save_uint_16, /* 206 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 207 */
#else  /* !PNG_INTERNAL */
    png_write_sig, /* 207 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 208 */
#else  /* !PNG_INTERNAL */
    png_write_IHDR, /* 208 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 209 */
#else  /* !PNG_INTERNAL */
    png_write_PLTE, /* 209 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 210 */
#else  /* !PNG_INTERNAL */
    png_write_IDAT, /* 210 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 211 */
#else  /* !PNG_INTERNAL */
    png_write_IEND, /* 211 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_gAMA_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 212 */
#else  /* !PNG_INTERNAL !PNG_WRITE_gAMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_write_gAMA, /* 212 */
#endif /* !PNG_INTERNAL !PNG_WRITE_gAMA_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_gAMA_SUPPORTED) || !defined(PNG_FIXED_POINT_SUPPORTED)
    NULL, /* 213 */
#else  /* !PNG_INTERNAL !PNG_WRITE_gAMA_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
    png_write_gAMA_fixed, /* 213 */
#endif /* !PNG_INTERNAL !PNG_WRITE_gAMA_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_sBIT_SUPPORTED)
    NULL, /* 214 */
#else  /* !PNG_INTERNAL !PNG_WRITE_sBIT_SUPPORTED */
    png_write_sBIT, /* 214 */
#endif /* !PNG_INTERNAL !PNG_WRITE_sBIT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_cHRM_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED)
    NULL, /* 215 */
#else  /* !PNG_INTERNAL !PNG_WRITE_cHRM_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
    png_write_cHRM, /* 215 */
#endif /* !PNG_INTERNAL !PNG_WRITE_cHRM_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_cHRM_SUPPORTED) || !defined(PNG_FIXED_POINT_SUPPORTED)
    NULL, /* 216 */
#else  /* !PNG_INTERNAL !PNG_WRITE_cHRM_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
    png_write_cHRM_fixed, /* 216 */
#endif /* !PNG_INTERNAL !PNG_WRITE_cHRM_SUPPORTED !PNG_FIXED_POINT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_sRGB_SUPPORTED)
    NULL, /* 217 */
#else  /* !PNG_INTERNAL !PNG_WRITE_sRGB_SUPPORTED */
    png_write_sRGB, /* 217 */
#endif /* !PNG_INTERNAL !PNG_WRITE_sRGB_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_iCCP_SUPPORTED)
    NULL, /* 218 */
#else  /* !PNG_INTERNAL !PNG_WRITE_iCCP_SUPPORTED */
    png_write_iCCP, /* 218 */
#endif /* !PNG_INTERNAL !PNG_WRITE_iCCP_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_sPLT_SUPPORTED)
    NULL, /* 219 */
#else  /* !PNG_INTERNAL !PNG_WRITE_sPLT_SUPPORTED */
    png_write_sPLT, /* 219 */
#endif /* !PNG_INTERNAL !PNG_WRITE_sPLT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_tRNS_SUPPORTED)
    NULL, /* 220 */
#else  /* !PNG_INTERNAL !PNG_WRITE_tRNS_SUPPORTED */
    png_write_tRNS, /* 220 */
#endif /* !PNG_INTERNAL !PNG_WRITE_tRNS_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_bKGD_SUPPORTED)
    NULL, /* 221 */
#else  /* !PNG_INTERNAL !PNG_WRITE_bKGD_SUPPORTED */
    png_write_bKGD, /* 221 */
#endif /* !PNG_INTERNAL !PNG_WRITE_bKGD_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_hIST_SUPPORTED)
    NULL, /* 222 */
#else  /* !PNG_INTERNAL !PNG_WRITE_hIST_SUPPORTED */
    png_write_hIST, /* 222 */
#endif /* !PNG_INTERNAL !PNG_WRITE_hIST_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_TEXT_SUPPORTED) && !defined(PNG_WRITE_pCAL_SUPPORTED) && !defined(PNG_WRITE_iCCP_SUPPORTED) && !defined(PNG_WRITE_sPLT_SUPPORTED)
    NULL, /* 223 */
#else  /* !PNG_INTERNAL !PNG_WRITE_TEXT_SUPPORTED !PNG_WRITE_pCAL_SUPPORTED !PNG_WRITE_iCCP_SUPPORTED !PNG_WRITE_sPLT_SUPPORTED */
    png_check_keyword, /* 223 */
#endif /* !PNG_INTERNAL !PNG_WRITE_TEXT_SUPPORTED !PNG_WRITE_pCAL_SUPPORTED !PNG_WRITE_iCCP_SUPPORTED !PNG_WRITE_sPLT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_tEXt_SUPPORTED)
    NULL, /* 224 */
#else  /* !PNG_INTERNAL !PNG_WRITE_tEXt_SUPPORTED */
    png_write_tEXt, /* 224 */
#endif /* !PNG_INTERNAL !PNG_WRITE_tEXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_zTXt_SUPPORTED)
    NULL, /* 225 */
#else  /* !PNG_INTERNAL !PNG_WRITE_zTXt_SUPPORTED */
    png_write_zTXt, /* 225 */
#endif /* !PNG_INTERNAL !PNG_WRITE_zTXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_iTXt_SUPPORTED)
    NULL, /* 226 */
#else  /* !PNG_INTERNAL !PNG_iTXt_SUPPORTED */
    png_write_iTXt, /* 226 */
#endif /* !PNG_INTERNAL !PNG_iTXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_oFFs_SUPPORTED)
    NULL, /* 227 */
#else  /* !PNG_INTERNAL !PNG_WRITE_oFFs_SUPPORTED */
    png_write_oFFs, /* 227 */
#endif /* !PNG_INTERNAL !PNG_WRITE_oFFs_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_pCAL_SUPPORTED)
    NULL, /* 228 */
#else  /* !PNG_INTERNAL !PNG_WRITE_pCAL_SUPPORTED */
    png_write_pCAL, /* 228 */
#endif /* !PNG_INTERNAL !PNG_WRITE_pCAL_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_pHYs_SUPPORTED)
    NULL, /* 229 */
#else  /* !PNG_INTERNAL !PNG_WRITE_pHYs_SUPPORTED */
    png_write_pHYs, /* 229 */
#endif /* !PNG_INTERNAL !PNG_WRITE_pHYs_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_tIME_SUPPORTED)
    NULL, /* 230 */
#else  /* !PNG_INTERNAL !PNG_WRITE_tIME_SUPPORTED */
    png_write_tIME, /* 230 */
#endif /* !PNG_INTERNAL !PNG_WRITE_tIME_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_sCAL_SUPPORTED) || !defined(PNG_FLOATING_POINT_SUPPORTED) || defined(PNG_NO_STDIO)
    NULL, /* 231 */
#else  /* !PNG_INTERNAL !PNG_WRITE_sCAL_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED PNG_NO_STDIO */
    png_write_sCAL, /* 231 */
#endif /* !PNG_INTERNAL !PNG_WRITE_sCAL_SUPPORTED !PNG_FLOATING_POINT_SUPPORTED PNG_NO_STDIO */
#if !defined(PNG_INTERNAL) || !defined(PNG_FIXED_POINT_SUPPORTED) || defined(PNG_WRITE_sCAL_SUPPORTED) && defined(PNG_FLOATING_POINT_SUPPORTED) && !defined(PNG_NO_STDIO)
    NULL, /* 232 */
#else  /* !PNG_INTERNAL !PNG_FIXED_POINT_SUPPORTED PNG_WRITE_sCAL_SUPPORTED PNG_FLOATING_POINT_SUPPORTED !PNG_NO_STDIO */
    png_write_sCAL_s, /* 232 */
#endif /* !PNG_INTERNAL !PNG_FIXED_POINT_SUPPORTED PNG_WRITE_sCAL_SUPPORTED PNG_FLOATING_POINT_SUPPORTED !PNG_NO_STDIO */
#if !defined(PNG_INTERNAL)
    NULL, /* 233 */
#else  /* !PNG_INTERNAL */
    png_write_finish_row, /* 233 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 234 */
#else  /* !PNG_INTERNAL */
    png_write_start_row, /* 234 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_GAMMA_SUPPORTED)
    NULL, /* 235 */
#else  /* !PNG_INTERNAL !PNG_READ_GAMMA_SUPPORTED */
    png_build_gamma_table, /* 235 */
#endif /* !PNG_INTERNAL !PNG_READ_GAMMA_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 236 */
#else  /* !PNG_INTERNAL */
    png_combine_row, /* 236 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_INTERLACING_SUPPORTED)
    NULL, /* 237 */
#else  /* !PNG_INTERNAL !PNG_READ_INTERLACING_SUPPORTED */
    png_do_read_interlace, /* 237 */
#endif /* !PNG_INTERNAL !PNG_READ_INTERLACING_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_INTERLACING_SUPPORTED)
    NULL, /* 238 */
#else  /* !PNG_INTERNAL !PNG_WRITE_INTERLACING_SUPPORTED */
    png_do_write_interlace, /* 238 */
#endif /* !PNG_INTERNAL !PNG_WRITE_INTERLACING_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 239 */
#else  /* !PNG_INTERNAL */
    png_read_filter_row, /* 239 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 240 */
#else  /* !PNG_INTERNAL */
    png_write_find_filter, /* 240 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 241 */
#else  /* !PNG_INTERNAL */
    png_write_filtered_row, /* 241 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 242 */
#else  /* !PNG_INTERNAL */
    png_read_finish_row, /* 242 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 243 */
#else  /* !PNG_INTERNAL */
    png_read_start_row, /* 243 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 244 */
#else  /* !PNG_INTERNAL */
    png_read_transform_info, /* 244 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_FILLER_SUPPORTED)
    NULL, /* 245 */
#else  /* !PNG_INTERNAL !PNG_READ_FILLER_SUPPORTED */
    png_do_read_filler, /* 245 */
#endif /* !PNG_INTERNAL !PNG_READ_FILLER_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_SWAP_ALPHA_SUPPORTED)
    NULL, /* 246 */
#else  /* !PNG_INTERNAL !PNG_READ_SWAP_ALPHA_SUPPORTED */
    png_do_read_swap_alpha, /* 246 */
#endif /* !PNG_INTERNAL !PNG_READ_SWAP_ALPHA_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_SWAP_ALPHA_SUPPORTED)
    NULL, /* 247 */
#else  /* !PNG_INTERNAL !PNG_WRITE_SWAP_ALPHA_SUPPORTED */
    png_do_write_swap_alpha, /* 247 */
#endif /* !PNG_INTERNAL !PNG_WRITE_SWAP_ALPHA_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_INVERT_ALPHA_SUPPORTED)
    NULL, /* 248 */
#else  /* !PNG_INTERNAL !PNG_READ_INVERT_ALPHA_SUPPORTED */
    png_do_read_invert_alpha, /* 248 */
#endif /* !PNG_INTERNAL !PNG_READ_INVERT_ALPHA_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_INVERT_ALPHA_SUPPORTED)
    NULL, /* 249 */
#else  /* !PNG_INTERNAL !PNG_WRITE_INVERT_ALPHA_SUPPORTED */
    png_do_write_invert_alpha, /* 249 */
#endif /* !PNG_INTERNAL !PNG_WRITE_INVERT_ALPHA_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_FILLER_SUPPORTED) && !defined(PNG_READ_STRIP_ALPHA_SUPPORTED)
    NULL, /* 250 */
#else  /* !PNG_INTERNAL !PNG_WRITE_FILLER_SUPPORTED !PNG_READ_STRIP_ALPHA_SUPPORTED */
    png_do_strip_filler, /* 250 */
#endif /* !PNG_INTERNAL !PNG_WRITE_FILLER_SUPPORTED !PNG_READ_STRIP_ALPHA_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_SWAP_SUPPORTED) && !defined(PNG_WRITE_SWAP_SUPPORTED)
    NULL, /* 251 */
#else  /* !PNG_INTERNAL !PNG_READ_SWAP_SUPPORTED !PNG_WRITE_SWAP_SUPPORTED */
    png_do_swap, /* 251 */
#endif /* !PNG_INTERNAL !PNG_READ_SWAP_SUPPORTED !PNG_WRITE_SWAP_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_PACKSWAP_SUPPORTED) && !defined(PNG_WRITE_PACKSWAP_SUPPORTED)
    NULL, /* 252 */
#else  /* !PNG_INTERNAL !PNG_READ_PACKSWAP_SUPPORTED !PNG_WRITE_PACKSWAP_SUPPORTED */
    png_do_packswap, /* 252 */
#endif /* !PNG_INTERNAL !PNG_READ_PACKSWAP_SUPPORTED !PNG_WRITE_PACKSWAP_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_RGB_TO_GRAY_SUPPORTED)
    NULL, /* 253 */
#else  /* !PNG_INTERNAL !PNG_READ_RGB_TO_GRAY_SUPPORTED */
    png_do_rgb_to_gray, /* 253 */
#endif /* !PNG_INTERNAL !PNG_READ_RGB_TO_GRAY_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_GRAY_TO_RGB_SUPPORTED)
    NULL, /* 254 */
#else  /* !PNG_INTERNAL !PNG_READ_GRAY_TO_RGB_SUPPORTED */
    png_do_gray_to_rgb, /* 254 */
#endif /* !PNG_INTERNAL !PNG_READ_GRAY_TO_RGB_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_PACK_SUPPORTED)
    NULL, /* 255 */
#else  /* !PNG_INTERNAL !PNG_READ_PACK_SUPPORTED */
    png_do_unpack, /* 255 */
#endif /* !PNG_INTERNAL !PNG_READ_PACK_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_SHIFT_SUPPORTED)
    NULL, /* 256 */
#else  /* !PNG_INTERNAL !PNG_READ_SHIFT_SUPPORTED */
    png_do_unshift, /* 256 */
#endif /* !PNG_INTERNAL !PNG_READ_SHIFT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_INVERT_SUPPORTED) && !defined(PNG_WRITE_INVERT_SUPPORTED)
    NULL, /* 257 */
#else  /* !PNG_INTERNAL !PNG_READ_INVERT_SUPPORTED !PNG_WRITE_INVERT_SUPPORTED */
    png_do_invert, /* 257 */
#endif /* !PNG_INTERNAL !PNG_READ_INVERT_SUPPORTED !PNG_WRITE_INVERT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_16_TO_8_SUPPORTED)
    NULL, /* 258 */
#else  /* !PNG_INTERNAL !PNG_READ_16_TO_8_SUPPORTED */
    png_do_chop, /* 258 */
#endif /* !PNG_INTERNAL !PNG_READ_16_TO_8_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_DITHER_SUPPORTED)
    NULL, /* 259 */
#else  /* !PNG_INTERNAL !PNG_READ_DITHER_SUPPORTED */
    png_do_dither, /* 259 */
#endif /* !PNG_INTERNAL !PNG_READ_DITHER_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_DITHER_SUPPORTED) || !defined(PNG_CORRECT_PALETTE_SUPPORTED)
    NULL, /* 260 */
#else  /* !PNG_INTERNAL !PNG_READ_DITHER_SUPPORTED !PNG_CORRECT_PALETTE_SUPPORTED */
    png_correct_palette, /* 260 */
#endif /* !PNG_INTERNAL !PNG_READ_DITHER_SUPPORTED !PNG_CORRECT_PALETTE_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_BGR_SUPPORTED) && !defined(PNG_WRITE_BGR_SUPPORTED)
    NULL, /* 261 */
#else  /* !PNG_INTERNAL !PNG_READ_BGR_SUPPORTED !PNG_WRITE_BGR_SUPPORTED */
    png_do_bgr, /* 261 */
#endif /* !PNG_INTERNAL !PNG_READ_BGR_SUPPORTED !PNG_WRITE_BGR_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_PACK_SUPPORTED)
    NULL, /* 262 */
#else  /* !PNG_INTERNAL !PNG_WRITE_PACK_SUPPORTED */
    png_do_pack, /* 262 */
#endif /* !PNG_INTERNAL !PNG_WRITE_PACK_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_WRITE_SHIFT_SUPPORTED)
    NULL, /* 263 */
#else  /* !PNG_INTERNAL !PNG_WRITE_SHIFT_SUPPORTED */
    png_do_shift, /* 263 */
#endif /* !PNG_INTERNAL !PNG_WRITE_SHIFT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_BACKGROUND_SUPPORTED)
    NULL, /* 264 */
#else  /* !PNG_INTERNAL !PNG_READ_BACKGROUND_SUPPORTED */
    png_do_background, /* 264 */
#endif /* !PNG_INTERNAL !PNG_READ_BACKGROUND_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_GAMMA_SUPPORTED)
    NULL, /* 265 */
#else  /* !PNG_INTERNAL !PNG_READ_GAMMA_SUPPORTED */
    png_do_gamma, /* 265 */
#endif /* !PNG_INTERNAL !PNG_READ_GAMMA_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_EXPAND_SUPPORTED)
    NULL, /* 266 */
#else  /* !PNG_INTERNAL !PNG_READ_EXPAND_SUPPORTED */
    png_do_expand_palette, /* 266 */
#endif /* !PNG_INTERNAL !PNG_READ_EXPAND_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_EXPAND_SUPPORTED)
    NULL, /* 267 */
#else  /* !PNG_INTERNAL !PNG_READ_EXPAND_SUPPORTED */
    png_do_expand, /* 267 */
#endif /* !PNG_INTERNAL !PNG_READ_EXPAND_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 268 */
#else  /* !PNG_INTERNAL */
    png_handle_IHDR, /* 268 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 269 */
#else  /* !PNG_INTERNAL */
    png_handle_PLTE, /* 269 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 270 */
#else  /* !PNG_INTERNAL */
    png_handle_IEND, /* 270 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_bKGD_SUPPORTED)
    NULL, /* 271 */
#else  /* !PNG_INTERNAL !PNG_READ_bKGD_SUPPORTED */
    png_handle_bKGD, /* 271 */
#endif /* !PNG_INTERNAL !PNG_READ_bKGD_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_cHRM_SUPPORTED)
    NULL, /* 272 */
#else  /* !PNG_INTERNAL !PNG_READ_cHRM_SUPPORTED */
    png_handle_cHRM, /* 272 */
#endif /* !PNG_INTERNAL !PNG_READ_cHRM_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_gAMA_SUPPORTED)
    NULL, /* 273 */
#else  /* !PNG_INTERNAL !PNG_READ_gAMA_SUPPORTED */
    png_handle_gAMA, /* 273 */
#endif /* !PNG_INTERNAL !PNG_READ_gAMA_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_hIST_SUPPORTED)
    NULL, /* 274 */
#else  /* !PNG_INTERNAL !PNG_READ_hIST_SUPPORTED */
    png_handle_hIST, /* 274 */
#endif /* !PNG_INTERNAL !PNG_READ_hIST_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_iCCP_SUPPORTED)
    NULL, /* 275 */
#else  /* !PNG_INTERNAL !PNG_READ_iCCP_SUPPORTED */
    png_handle_iCCP, /* 275 */
#endif /* !PNG_INTERNAL !PNG_READ_iCCP_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_iTXt_SUPPORTED)
    NULL, /* 276 */
#else  /* !PNG_INTERNAL !PNG_iTXt_SUPPORTED */
    png_handle_iTXt, /* 276 */
#endif /* !PNG_INTERNAL !PNG_iTXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_oFFs_SUPPORTED)
    NULL, /* 277 */
#else  /* !PNG_INTERNAL !PNG_READ_oFFs_SUPPORTED */
    png_handle_oFFs, /* 277 */
#endif /* !PNG_INTERNAL !PNG_READ_oFFs_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_pCAL_SUPPORTED)
    NULL, /* 278 */
#else  /* !PNG_INTERNAL !PNG_READ_pCAL_SUPPORTED */
    png_handle_pCAL, /* 278 */
#endif /* !PNG_INTERNAL !PNG_READ_pCAL_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_pHYs_SUPPORTED)
    NULL, /* 279 */
#else  /* !PNG_INTERNAL !PNG_READ_pHYs_SUPPORTED */
    png_handle_pHYs, /* 279 */
#endif /* !PNG_INTERNAL !PNG_READ_pHYs_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_sBIT_SUPPORTED)
    NULL, /* 280 */
#else  /* !PNG_INTERNAL !PNG_READ_sBIT_SUPPORTED */
    png_handle_sBIT, /* 280 */
#endif /* !PNG_INTERNAL !PNG_READ_sBIT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_sCAL_SUPPORTED)
    NULL, /* 281 */
#else  /* !PNG_INTERNAL !PNG_READ_sCAL_SUPPORTED */
    png_handle_sCAL, /* 281 */
#endif /* !PNG_INTERNAL !PNG_READ_sCAL_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_sPLT_SUPPORTED)
    NULL, /* 282 */
#else  /* !PNG_INTERNAL !PNG_READ_sPLT_SUPPORTED */
    png_handle_sPLT, /* 282 */
#endif /* !PNG_INTERNAL !PNG_READ_sPLT_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_sRGB_SUPPORTED)
    NULL, /* 283 */
#else  /* !PNG_INTERNAL !PNG_READ_sRGB_SUPPORTED */
    png_handle_sRGB, /* 283 */
#endif /* !PNG_INTERNAL !PNG_READ_sRGB_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_tEXt_SUPPORTED)
    NULL, /* 284 */
#else  /* !PNG_INTERNAL !PNG_READ_tEXt_SUPPORTED */
    png_handle_tEXt, /* 284 */
#endif /* !PNG_INTERNAL !PNG_READ_tEXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_tIME_SUPPORTED)
    NULL, /* 285 */
#else  /* !PNG_INTERNAL !PNG_READ_tIME_SUPPORTED */
    png_handle_tIME, /* 285 */
#endif /* !PNG_INTERNAL !PNG_READ_tIME_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_tRNS_SUPPORTED)
    NULL, /* 286 */
#else  /* !PNG_INTERNAL !PNG_READ_tRNS_SUPPORTED */
    png_handle_tRNS, /* 286 */
#endif /* !PNG_INTERNAL !PNG_READ_tRNS_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_READ_zTXt_SUPPORTED)
    NULL, /* 287 */
#else  /* !PNG_INTERNAL !PNG_READ_zTXt_SUPPORTED */
    png_handle_zTXt, /* 287 */
#endif /* !PNG_INTERNAL !PNG_READ_zTXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_HANDLE_AS_UNKNOWN_SUPPORTED)
    NULL, /* 288 */
#else  /* !PNG_INTERNAL !PNG_HANDLE_AS_UNKNOWN_SUPPORTED */
    png_handle_as_unknown, /* 288 */
#endif /* !PNG_INTERNAL !PNG_HANDLE_AS_UNKNOWN_SUPPORTED */
#if !defined(PNG_INTERNAL)
    NULL, /* 289 */
#else  /* !PNG_INTERNAL */
    png_handle_unknown, /* 289 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 290 */
#else  /* !PNG_INTERNAL */
    png_check_chunk_name, /* 290 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 291 */
#else  /* !PNG_INTERNAL */
    png_do_read_transformations, /* 291 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 292 */
#else  /* !PNG_INTERNAL */
    png_do_write_transformations, /* 292 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL)
    NULL, /* 293 */
#else  /* !PNG_INTERNAL */
    png_init_read_transformations, /* 293 */
#endif /* !PNG_INTERNAL */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 294 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_read_chunk, /* 294 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 295 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_read_sig, /* 295 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 296 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_check_crc, /* 296 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 297 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_crc_skip, /* 297 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 298 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_crc_finish, /* 298 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 299 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_fill_buffer, /* 299 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 300 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_save_buffer, /* 300 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 301 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_restore_buffer, /* 301 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 302 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_read_IDAT, /* 302 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 303 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_process_IDAT_data, /* 303 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 304 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_process_row, /* 304 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 305 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_handle_unknown, /* 305 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 306 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_have_info, /* 306 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 307 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_have_end, /* 307 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 308 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_have_row, /* 308 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 309 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_push_read_end, /* 309 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 310 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_process_some_data, /* 310 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED)
    NULL, /* 311 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
    png_read_push_finish_row, /* 311 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED) || !defined(PNG_tEXt_SUPPORTED)
    NULL, /* 312 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_tEXt_SUPPORTED */
    png_push_handle_tEXt, /* 312 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_tEXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED) || !defined(PNG_tEXt_SUPPORTED)
    NULL, /* 313 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_tEXt_SUPPORTED */
    png_push_read_tEXt, /* 313 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_tEXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED) || !defined(PNG_zTXt_SUPPORTED)
    NULL, /* 314 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_zTXt_SUPPORTED */
    png_push_handle_zTXt, /* 314 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_zTXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED) || !defined(PNG_zTXt_SUPPORTED)
    NULL, /* 315 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_zTXt_SUPPORTED */
    png_push_read_zTXt, /* 315 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_zTXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED) || !defined(PNG_iTXt_SUPPORTED)
    NULL, /* 316 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_iTXt_SUPPORTED */
    png_push_handle_iTXt, /* 316 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_iTXt_SUPPORTED */
#if !defined(PNG_INTERNAL) || !defined(PNG_PROGRESSIVE_READ_SUPPORTED) || !defined(PNG_iTXt_SUPPORTED)
    NULL, /* 317 */
#else  /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_iTXt_SUPPORTED */
    png_push_read_iTXt, /* 317 */
#endif /* !PNG_INTERNAL !PNG_PROGRESSIVE_READ_SUPPORTED !PNG_iTXt_SUPPORTED */
};

/* !END!: Do not edit above this line. */
