/*
 *			conv/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	conv
#define PRODUCTS	asc2g g2asc conv-vg2g pix2asc asc2pix euclid-g g-euclid \
			euclid_format tankill-g g-tankill viewpoint-g dxf-g g-nmg \
			g-euclid1 fast4-g proe-g
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

proe-g: proe-g.o
	CC LDFLAGS proe-g.o LIBWDB LIBRT LIBRT_LIBES LIBES -o proe-g

fast4-g: fast4-g.o
	CC LDFLAGS fast4-g.o LIBWDB LIBRT LIBRT_LIBES LIBES -o fast4-g

asc2g:	asc2g.o
	CC LDFLAGS asc2g.o LIBWDB LIBRT LIBRT_LIBES LIBES -o asc2g

g2asc:	g2asc.o
	CC LDFLAGS g2asc.o LIBWDB LIBRT LIBRT_LIBES LIBES -o g2asc

conv-vg2g:	conv-vg2g.o
	CC LDFLAGS conv-vg2g.o -o conv-vg2g

pix2asc:	pix2asc.o
	CC LDFLAGS pix2asc.o -o pix2asc

asc2pix:	asc2pix.o
	CC LDFLAGS asc2pix.o -o asc2pix

euclid-g:	euclid-g.o
	CC LDFLAGS euclid-g.o LIBWDB LIBRT LIBRT_LIBES LIBES -o euclid-g

g-euclid:	g-euclid.o
	CC LDFLAGS g-euclid.o LIBRT LIBRT_LIBES LIBES -o g-euclid

g-euclid1:	g-euclid1.o
	CC LDFLAGS g-euclid1.o LIBRT LIBRT_LIBES LIBES -o g-euclid1

euclid_format:	euclid_format.o
	CC LDFLAGS euclid_format.o LIBRT LIBRT_LIBES LIBES -o euclid_format

tankill-g:	tankill-g.o
	CC LDFLAGS tankill-g.o LIBWDB LIBRT LIBRT_LIBES LIBES -o tankill-g

g-tankill:	g-tankill.o
	CC LDFLAGS g-tankill.o LIBRT LIBRT_LIBES LIBES -o g-tankill

viewpoint-g:	viewpoint-g.o
	CC LDFLAGS viewpoint-g.o LIBWDB LIBRT LIBRT_LIBES LIBES -o viewpoint-g

dxf-g:	dxf-g.o
	CC LDFLAGS dxf-g.o LIBWDB LIBRT LIBRT_LIBES LIBES -o dxf-g

g-nmg:	g-nmg.o
	CC LDFLAGS g-nmg.o LIBWDB LIBRT LIBRT_LIBES LIBES -o g-nmg

#include "../Cakefile.rules"
