/*
 *			conv/Cakefile
 */

#define SRCDIR	conv
#define PRODUCTS	asc2g g2asc conv-vg2g pix2asc asc2pix
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

asc2g:	asc2g.o
	CC CFLAGS asc2g.o -o asc2g

g2asc:	g2asc.o
	CC CFLAGS g2asc.o -o g2asc

conv-vg2g:	conv-vg2g.o
	CC CFLAGS conv-vg2g.o -o conv-vg2g

pix2asc:	pix2asc.o
	CC CFLAGS pix2asc.o -o pix2asc

asc2pix:	asc2pix.o
	CC CFLAGS asc2pix.o -o asc2pix

#include "../Cakefile.rules"
