.TH FAST4-G 1 BRL-CAD
.SH NAME
fast4-g \- FASTGEN4 Translator (FASTGEN4 to BRL-CAD)
.SH SYNOPSIS
.B fast4-g
[-dnw] [-a min_angle] [-x RT_DEBUG_FLAG] [-X NMG_DEBUG_FLAG] [-D tol_dist] [-P tol_cosine] file.fastgen4 file.g
.SH DESCRIPTION
.I fast4-g\^
converts the specified
.I file.fastgen4
to a BRL-CAD
.I file.g
file.
The
.I -d
option prints debugging information and the
.I -w
option prints warnings whenever an object is assigned a default name (no
name specified in the FASTGEN4 file).
The
.I -n
option results in a BRL-CAD model built from NMGs instead of the default polysolids.
The
.I min_angle
is the smallest angle (degrees) between two adjacent faces that will not be considered
an error in a PLATE-MODE component. If a PLATE_MODE component has two adjacent faces
that make an angle smaller than
the minimum, then that component will be converted using an ARB6 solid for each
PLATE-MODE triangle.
The
.I tol_dist
is the maximum distance (in mm) between two vertices at which the two vertices
will be considered to be the same vertex.
The
.I tol_cosine
is the maximum cosine of the angle between two planes at which the two planes
will be considered to be parallel.
The
.I file.fastgen4
file is expected to be in the FASTGEN 4.1 format as defined in the
FASTGEN 4.1 User Manual.
.I CCONE1
and
.I CCONE2
elements are converted to BRL-CAD truncated right cylinders
.I (TRC).
.I CHEX1
and
.I CHEX2
elements are converted to BRL-CAD arbitrary convex polyhedrons
.I (ARB8).
.I CLINE
elements are converted to BRL-CAD right circular cylinders
.I (RCC)
and two or more CLINES originating or terminating at the same vertex
are joined with a BRL-CAD sphere
.I (SPH).
.I CQUAD
and
.I CTRI
elements are converted to faces of a BRL-CAD n-manifold geometry
.I (NMG)
object. For plate mode, these faces are copied and extruded by
the indicated thickness to create a real surface where one is only
implied in the FASTGEN4 data.  The default is to convert these objects
to BRL-CAD polysolids.  The
.I -n
option results in these
.I NMG
objects being output directly as
.I NMG
solids.
.I CSPHERE
elements are converted to BRL-CAD spheres
.I (SPH)
solids. BRL-CAD region ident numbers are assigned by combining the
FASTGEN4 group and component numbers:
.nf
	ident = group x 1000 + component
.fi
and object names are assigned from the FASTGEN4
.I $NAME
elements using an algorithm to create unique BRL-CAD names.
.SH EXAMPLE
.RS
$ \|\fIfast4-g \|sample.fastgen4 \|sample.g\fP
.RE
.SH "SEE ALSO"
.I
patch-g
.br
.I
FASTGEN 4.1 User's Manual,
XRESV Tech Note 94-01,
Hugh Griffis and Maty Lentz,
April 1994
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
Some objects represented in FASTGEN4 format may be too complex or
too vaguely defined to be converted to BRL-CAD format using the preferred
algorithm. These are typically objects described in plate mode.
In most of these cases the converter will make a second attempt
at converting the problem object using a simpler, but less accurate,
method of combining a series of BRL-CAD
.I ARB6
solids, one for each face of the original FASTGEN4 object.
Errors in the FASTGEN4 file will have unpredictable results on the BRL-CAD
output file. It is wise to examine the resulting model.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army  Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
