.TH G-SHELL.RECT 1 BRL-CAD
.SH NAME
g-shell.rect \- Produce triangulated shell from BRL-CAD model
.SH SYNOPSIS
.B g-shell.rect
[-d debug_level] [-n] [-g cell_size] [-i initial_ray_dir] [-d debug_level] -o brlcad_output_file database.g object(s)
.SH DESCRIPTION
.I g-shell.rect\^
converts the specified
.I objects(s)
from a BRL-CAD model
.I database.g
to a single NMG solid using raytracing. Rays are fired in a uniform grid
with spacing specified in millimeters using the
.I -g
option (default is 50mm). The
.I -d
option requests debug information and produces more extensive messages as the
.I debug_level
increases.  The direction for the first set of rays is chosen by calculating
the presented area of the bounding box of the
.I object(s)
and selecting the direction with the largest area. The user may override this
by specifying a desired initial ray direction using the
.I -i
option. The ray direction must be spcified as
.I X, Y,
or
.I Z.
The best results are usually obtained by raytracing in the direction that produces the
most hits first. The initial shell is constructed using only the first and last
intersections with the
.I object(s).
This will typically result in some rather large faces with normals at right angles
to the ray direction. These faces are then subdivided (according to the
.I cell_size
) and additional rays fired from the other two directions are used to refine their
shape. The
.I -n
option requests that this additional refinement not be done. The resulting NMG solid
will be named
.I shell
and will be written to the specified
.I brlcad_output_file.
.SH EXAMPLE
.RS
$ \|\fIg-shell.rect \|-o shell.g \|sample.g \|sample_object\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
