.TH PROE-G 1 BRL-CAD
.SH NAME
proe-g \- Pro/Engineer Translator (Pro/Engineer to BRL-CAD)
.SH SYNOPSIS
.B proe-g
[-dpsar] [-u reg_exp] [-x RT_DEBUG_FLAG] [-X NMG_DEBUG_FLAG] file.brl file.g
.SH DESCRIPTION
.I proe-g\^
converts the specified
.I file.brl
to a BRL-CAD
.I file.g
file.
The
.I -d
option prints debugging information.
The
.I -p
option results in a BRL-CAD model built from polysolids instead of NMGs.
The
.I -s
option requests that the Pro/E parts be written as BRL-CAD
.I ARB
solds, if possible. This will only be done if this simplification
results in no loss of accuracy. The
.I ARB
solid will raytrace faster than
.I polysolids
or
.I NMG's.
The
.I -a
option implies that all the parts in the Pro/E model should be converted to
BRL-CAD
.I air
regions.
The
.I -r
flag indicates that the model should not be rotated, translated, or scaled, but left in
the same orientation and size as it was created in
.I Pro/E.
This allows the user to convert parts that are referenced by previously converted
assemblies, so that the transformation matrix in the referencing assembly will
size and position the part.
The
.I file.brl
file is expected to be output from the
.I BRL-CAD
menu option of the Pro/Engineer
.I EXPORT
menu. This menu option is a Pro/Develop application produced by the USARL.
.SH EXAMPLE
.RS
$ \|\fIproe-g -p \|sample.brl \|sample.g\fP
.RE
.SH "SEE ALSO"
.I
Pro/Engineer Modeling User's Guide,
Version 13.0,
Parametric Technology Corporation
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army  Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
