.\" Copyright (c) 1988, University of Utah
.TH GETBOB 1 "Jun 24, 1988" 1
.UC 4 
.SH NAME
getbob \- Display RLE files on HP Bobcat screens.
.SH SYNOPSIS
.B getbob
[
.B \-l
] [
.B \-g
.I gamma
] [
.B \-p
.I x y
] [
.B \-d
.I display
] [
.B \-x
.I driver
] [
.I infile
]
.SH DESCRIPTION
.I Getbob
reads a file in
.IR RLE (5)
format and displays it on an HP bobcat screen.
It uses a dithering technique to take a
full-color or gray scale image into the limited number of colors
typically available.
.SH OPTIONS
.TP
.B \-l
Use a linear map.
.TP
.BI \-g " gamma"
Use a gamma correction value of 
.IR gamma .
.TP
.BI \-d " device"
Use the device specified.  The default is /dev/graphics.
.TP
.BI \-x " driver"
Use the driver specified.  The default is hp98710.
.TP
.BI \-p " x y"
Position image lower left hand corner on the display.  The
x and y position is given in pixels with the origin taken as
the lower left hand corner of the display.  This flag is only
useful with the
.BR \-d ,
and
.B \-x
flags.
.TP
.I  infile
This option is used to name the input file.  If not present, input is taken
from
.I stdin.
.SH SEE ALSO
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Mark Bloomenthal, University of Utah
