.\" Copyright (c) 1986, University of Utah
.TH GETFB 1 "Feb 12, 1987" 1
.UC 4
.SH NAME
getfb \- display an RLE file on a BRL libfb frame buffer.
.SH SYNOPSIS
.B getfb
[
.B \-d
] [
.I infile
]
.SH DESCRIPTION
This program displays an
.IR RLE (5)
file on any frame buffer supported by the BRL
.IR libfb .
The option
.B \-d
prints the image header information and turns on debugging of the
.I RLE
file.  All of the
.I RLE
opcodes will be printed as they are read from the input file.
If an input
.I rlefile
is not specified, input will be taken from standard input.
.SH SEE ALSO
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Paul Stay, Ballistic Research Laboratory.
.SH LIMITATIONS
Will only display images up to 1024 pixels wide.  Will not display
black and white (single channel) images correctly.  Ignores color map
in
.I RLE
file.
