.\" Copyright (c) 1989, David Koblas
.TH GIFTORLE 1
.UC 4
.SH NAME
giftorle \- Convert GIF images to RLE format
.SH SYNOPSIS
.B giftorle
[
.B \-c
]
[
.B \-o
.I outfile.rle
]
[
.I infile.gif ...
]
.SH DESCRIPTION
.I Giftorle
converts a file from Graphics Interchange Format (GIF) format into RLE format.
Multiple input images may be converted,
these will be written sequentially to the output RLE file.
The origin of a GIF image is at the upper left, while the origin of an
RLE image is at the lower left.  This program automatically flips the
image to preserve its orientation.
.SH OPTIONS
.TP
.B \-c
Preserve the colormap that the GIF image contains, otherwise the
colormap is applied to input image.
.TP
.BI \-o " outfile.rle"
If specified, the output will be written to this file.  If
.I outfile.rle
is "\-", or if it is not specified, the output will be written to the
standard output stream.
.TP
.I infile.gif ...
The input will be read from these files.  If
.I infile.gif
is "\-" or is not specified, the input will be read from the standard
input stream.
.SH MISC
GIF and Graphics Interchange Format are both trademarks of CompuServe
Incorporated.
.SH SEE ALSO
.IR rletogif (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
David Koblas (koblas@mips.com or koblas@cs.uoregon.edu)


