.\" Copyright (c) 1986, University of Utah
.TH MERGECHAN 1 "Nov 8, 1987" 1
.UC 4
.SH NAME
mergechan \- merge channels from several RLE files into a single output stream
.SH SYNOPSIS
.B mergechan
[
.B \-a
] [
.B \-o
.I outfile
]
.I infiles ...
.SH DESCRIPTION
.I Mergechan
takes input from several RLE files and combines them into a single output
stream.  Each channel in the output stream comes from the respective filename
specified on the input (i.e., channel zero is taken from the first file,
channel one from the next, etc).  The same file can be specified more than
once.  If the
.B \-a
flag is given, the channels are numbered from -1 (the alpha channel) instead
of zero.  All of the input channels must have exactly the same dimensions
(use
.IR crop (1)
to adjust files to fit each other).

Mergechan is typically used to introduce an alpha mask from another source
into an image, or combine color channels digitized independently.

If \fB\-o\fP is specified, the output will be written to
.IR outfile .
.SH SEE ALSO
.IR crop (1),
.IR rleswap (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
John W. Peterson, University of Utah.
.SH BUGS
Mergechan is totally ignorant of the color maps of the input files.

The restriction that all input files must be the same size could probably
be removed.
