.\" Copyright (c) 1990, University of Michigan
.TH RLEPRINT 1 "June 12, 1990" 1
.UC 4
.SH NAME
rleprint \- Print the values of all the pixels in the file.
.SH SYNOPSIS
.B rleprint
[
.B \-a
] [
.I infile
]
.SH DESCRIPTION
This program reads an
.IR RLE (5)
image and prints the values of all the pixels to the standard output.
Each pixel is printed on a single line.  For example, a count of all
the unique pixel values in the file could be obtained by
.br
rleprint pic.rle | sort \-u | wc
.TP
.I infile
The input will be read from this file.  If
.I infile
is "\-" or is not specified, the input will be read from the standard
input stream.
.SH OPTIONS
.TP
.B \-a
Print the alpha value (if available) as the last entry on the line.
.SH SEE ALSO
.IR rlehdr (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Spencer W. Thomas
.SH BUGS
This program is of limited utility because of the sheer volume of
output it generates.
