.\" Copyright (c) 1990, University of Michigan
.TH RLESKEL 1 "June 12, 1990" 1
.UC 4
.SH NAME
rleskel \- A skeleton tool.
.SH SYNOPSIS
.B rleskel
[
.B \-o
.I outfile
] [
.I infile
]
.SH DESCRIPTION
This program reads an
.IR RLE (5)
image and writes it to the specified output file.  All images in
the input file will be copied.  The program is not normally compiled
and installed, it exists solely to serve as a starting point for
writing simple "filter" tools, just as this man page serves as a starting
point for the documentation of simple tools.
.SH OPTIONS
.TP
.BI \-o " outfile"
If specified, the output will be written to this file.  If
.I outfile
is "\-", or if it is not specified, the output will be written to the
standard output stream.
.TP
.I infile
The input will be read from this file.  If
.I infile
is "\-" or is not specified, the input will be read from the standard
input stream.
.SH SEE ALSO
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Spencer W. Thomas
