.\" Copyright (c) 1986, University of Utah
.TH RLESTEREO 1 "July 31, 1990" 1
.UC 4
.SH NAME
rlestereo \- produce anaglyph from stereo pair
.SH SYNOPSIS
.B rlestereo
.\" sample options...
[
.B \-l
.I "leftscale"
]
[
.B \-r
.I "rightscale"
]
.I "leftimage rightimage"
.SH DESCRIPTION
.IR Rlestereo
reads the two named RLE files and produces a single image suitable for
viewing
with red-blue or red-green glasses.

The 'left' image is converted to
greyscale and written on the red channel.  The 'right' image is converted
to greyscale and written on the blue or green channel.  The intensity of the
two channels may be scaled in order to compensate for the relative
intensities of the two base colors as viewed through the glasses.
.SH OPTIONS
.TP
.B \-g
The right-eye image is written to the green channel rather than the
blue.
.TP
.BI \-l " leftscale"
Scale the intensities of the left-eye greyscale image by the given amount.
The default value is 0.7.
.TP
.B \-r " rightscale"
Scale the intensities of the right-eye greyscale image by the given amount.
The default value is 1.0.
.SH SEE ALSO
.IR urt (1),
.IR RLE (5).
.br
.sp 1
Cardboard glasses are available at many comic book stores.
.SH AUTHOR
Craig Kolb, Yale University
