.\" Copyright (c) 1986, University of Utah
.\" Copyright (c) 1990, University of Michigan
.TH RLETOTARGA 1 "March 16, 1991" 1
.UC 4
.SH NAME
rletotarga \- Convert an RLE(5) image file to Truevision TARGA format.
.SH SYNOPSIS
.B rletotarga
[
.I infile
]
.I outfile
.SH DESCRIPTION
.I Rletotarga
reads a file in RLE(5) format and converts it to
Truevision's TARGA format.
If no input file is specified, the data is
read from stdin.
The output TARGA file will be in one of three formats, depending on the
contents of the RLE file: 8\-bit B/W (format #3), 24\- or 32\-bit
true color (format #2).  Only the first image in the RLE file is read.
.SH SEE ALSO
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Andrew C. Hadenfeldt, University of Nebraska\-Lincoln
