.\" Copyright (c) 1986, University of Utah
.\" Template man page.  Taken from wtm's page for getcx3d
.TH RLETOPAINT 1 "Month X, YYYY" 1
.UC 4 
.SH NAME
rletopaint \- convert an RLE file to MacPaint format using dithering
.SH SYNOPSIS
.B rletopaint
.\" sample options...
[
.B \-l
] [
.B \-r
] [
.B \-g
[
.I gamma
]
] [
.B \-o
.I outfile.paint
] [
.I infile 
]
.SH DESCRIPTION
.IR Rletopaint
converts a file from
.IR RLE (5)
format to MacPaint format.  The program uses 
dithering to convert from a full 24 bit color image to a bitmapped image.
If the RLE file is larger than a MacPaint image (576\(mu720) it is cropped to 
fit.

Because MacPaint files have their coordinate origin in the upper left instead
of the lower left, the RLE file should be piped through
.IR rleflip "(1) \-v"
before 
.IR rletopaint.

The resulting file can be downloaded to a Macintosh in binary mode,
and should be given a type of 
.I PNTG
and a creator of 
.IR MPNT ,
so it will be recognized as a MacPaint file.
.SH OPTIONS
.TP
.B \-l
Use a linear map in the conversion from 24 bits to bitmapped output.
.TP
\fB\-g\ \fR[\fI\ gamma\ \fR]
Use a gamma map of 
.I gamma
(gamma is 2.0 if not specified).
.TP
.B \-r
Invert the sense of the output pixels (white on black instead of black
on white).  For normal images, you probably want this flag.
.SH SEE ALSO
.IR painttorle(1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
John W. Peterson.  Byte compression routine by Jim Schimpf.
.SH BUGS
Should use a color map in the file, if present.
