.TH RLETORAST 1 "1990" 1
.UC 4
.SH NAME
rletorast \- Convert an RLE file to a Sun rasterfile.
.SH SYNOPSIS
.B rletorast
[
.B \-o
.I outfile.ras
] [
.I infile
]
.SH DESCRIPTION
This program converts an
.IR RLE (5)
file to a Sun raster file.
.TP
.BI \-o \ outfile.ras
If specified, the output will be written to this file.  If
.I outfile.ras
is "\-", or if it is not specified, the output will be written to the
standard output stream.  The input file should have either 1 or 3
channels, and may have an alpha channel.  Depending on the input,
either a gray scale or color raster file will be generated.  If an
alpha channel is present, a 32 bit raster will always be made.  Since
the Sun raster format and RLE disagree on the origin location, the
image is automatically flipped to maintain its orientation.
.TP
.I infile
The input will be read from this file.  If
.I infile
is "\-" or is not specified, the input will be read from the standard
input stream.

The programs
.IR mcut (1),
.IR rlequant (1),
.IR to8 (1),
and
.IR tobw (1)
will make a 1 channel RLE image from an 3 channel (full color) image.
If the original image also had an alpha channel,
.I rleswap -d -1
can be used to delete it.
.SH SEE ALSO
.na
.IR mcut (1),
.IR rastorle (1),
.IR rlequant (1),
.IR rleswap (1),
.IR to8 (1),
.IR tobw (1),
.IR urt (1),
.IR RLE (5).
.ad b
.SH AUTHOR
Ed Falk, Sun Microsystems.
