.\" Copyright (c) 1990, University of Michigan
.TH RLETOTIFF 1 "July 3, 1990" 1
.UC 4 
.SH NAME
rletotiff \- Convert 24 bit RLE image files to TIFF.
.SH SYNOPSIS
.B rletotiff
[
.B \-{cC}
]
.B \-o 
.I outfile.tif
[
.B \-v
] [ 
.I infile.rle
]
.SH DESCRIPTION
This program converts a 24 bit image in
.IR RLE (5)
format into 
.I TIFF
form.  Only a single image will be converted.
.SH OPTIONS
.TP
.B \-{cC}
Sets the type of compression used in the output file.  
.B \-c
(the default) will cause the output file to be compressed using the
Lempel-Ziv-Welch (LZW) algorithm.
.B \-C
will suppress any compression.
.TP
.BI \-o " outfile.tif"
The output will be written to this file.  
.I outfile.tif
must be a real file, the special cases described in
.I urt (1)
do not apply.  Note also that this "option" is not optional.  The
.B \-o
flag is required for consistency with the other tools.
.TP
.B \-v
Flip image vertically.
.TP
.I infile.rle
The input will be read from this file.  If
.I infile.rle
is "\-" or is not specified, the input will be read from the standard
input stream.
.SH SEE ALSO
.IR tifftorle (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Bailey Brown, University of Michigan.
