.\" -*- Text -*-
.\" Copyright (c) 1990, University of Michigan
.\" Template man page.  
.TH SHOW3 1 "February, 1992" 1
.UC 4 
.SH NAME
show3 \- flip through three IFF ILBM files in rapid succession
.SH SYNOPSIS
.B show3 
.I redfile greenfile bluefile
.B show3
.I filename
.SH DESCRIPTION
.I Show3
will render the three specified IFF ILBM files in three different
screens, then flip through them in rapid succession, thus combining
them into a single picture. Its main use is to combine the three
r, g, b components of a picture created by saving a picture rendered
using 
.I getami \-3
into the original picture.

If 
.I show3
is called using the second form, then the extensions ".r",
".g", and ".b" will be appended to the file name given, to produce the
required three file names.

Click the left mouse button to exit from this program.

This program will only work if you have Christian Weber's 
.I iff.library
in your LIBS: directory.
.SH CAVEAT
As with 
.IR "getami \-3" ,
the screen will flicker, especially in conjunction
with interlace. If you are sensitive to screen flicker, please do not
use this program.
.SH BUGS
Displaying three images with different resolutions is a sure way to
crash the machine. Use this program only for the purpose for which it
is intended.
.SH AUTHOR
Kriton Kyrimis (kyrimis%theseas@csi.forth.gr), based on showiff.c
by Christian A. Weber, distributed with his iff.library.
