.\" Copyright (c) 1990, University of Michigan
.TH TIFFTORLE 1 "July 3, 1990" 1
.UC 4 
.SH NAME
tifftorle \- Convert TIFF image files to RLE.
.SH SYNOPSIS
.B tifftorle
[
.B \-o 
.I outfile.rle
]
.I infile.tif

.SH DESCRIPTION
This program converts a TIFF image to
.IR RLE (5)
format.  
.SH OPTIONS
.TP
.BI \-o " outfile.rle"
If specified, the output will be written to this file.  If 
.I outfile.rle
is "\-", or if it is not specified, the output will be written to the
standard output stream.
.TP
.I infile.tif
The input will be read from this file.
.I infile.tif
must be a real file, the special cases described in 
.IR urt (1)
do not apply here.
.SH LIMITATIONS
Can't handle RGB TIFF files with a separate planar configuration.
.br
Can't handle tiled TIFF files.
.SH SEE ALSO
.IR tifftorle (1),
.IR urt (1),
.IR libtiff,
.IR RLE (5).
.SH AUTHOR
Bailey Brown, University of Michigan.
.br
Extended by David R. L. Worthington, SRI International to single
channel TIFF files.
.br
Extended by Spencer W. Thomas, University of Michigan to TIFF files
with fewer than 8 bits/sample.
.br
Requires libtiff, by Sam Leffler.
.SH BUGS
Doesn't copy alpha channel when present.
