#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es OK Aceptar
::msgcat::mcset es Close Cerrar
::msgcat::mcset es Cancel Cancelar
::msgcat::mcset es Warning Atención
::msgcat::mcset es Ok Aceptar
::msgcat::mcset es {unknown option '%s' in snit_messageBox} {Opción desconocida '%s' en snit_messageBox}
::msgcat::mcset es Abort Abortar
::msgcat::mcset es Retry Reintentar
::msgcat::mcset es Ignore Ignorar
::msgcat::mcset es Yes Sí
::msgcat::mcset es No No
::msgcat::mcset es {unknown type: '%s' in snit_messageBox} {Tipo desconocido '%s' en snit_messageBox}
::msgcat::mcset es {bad default option: '%s' in snit_messageBox} {Opción por defecto incorrecta: '%s' en snit_messageBox}
::msgcat::mcset es Action Acción
::msgcat::mcset es {New password} {Nueva contraseña}
::msgcat::mcset es Uncrypt Desencriptar
::msgcat::mcset es {Choose action to perform:} {Escoja la acción a realizar:}
::msgcat::mcset es {Enter password} {Entre la contraseña}
::msgcat::mcset es Password: Contraseña:
::msgcat::mcset es {Enter password to encrypt:} {Entre la contraseña para encriptar}
::msgcat::mcset es {Password must have at least 4 characters} {La contraseña debe tener al menos 4 caracteres}
::msgcat::mcset es {Change page type} {Cambiar el tipo de página}
::msgcat::mcset es {Choose a new page type for page '%s'} {Escoja un nuevo tipo de página para la página '%s'}
::msgcat::mcset es {Current type: %s} {Tipo actual: %s}
::msgcat::mcset es {New type:} {Nuevo tipo:}
::msgcat::mcset es {Yes to all} {Sí a todo}
::msgcat::mcset es {No to all} {No a todo}
::msgcat::mcset es {Do not show again for this session} {No mostrar otra vez para esta sesión}
::msgcat::mcset es {Repeat my answer} {Repetir mi contestación}
::msgcat::mcset es {Choose action to perform} {Seleccione la acción a realizar}
::msgcat::mcset es Password Contraseña
::msgcat::mcset es {Enter password to encrypt} {Introduzca contraseña para encriptar }
::msgcat::mcset es Previous Previo
::msgcat::mcset es Next Siguiente
::msgcat::mcset es Finish Finalizar
