/*
 *			tclscripts/pl-dm/Cakefile
 */
#include "../../Cakefile.defs"

#define PRODUCTS	*.tcl tclIndex
#define STATIC_PRODUCTS	*.tcl tclIndex
#define SRCDIR	pl-dm
#undef BINDIR
#define BINDIR	TCLSCRIPTSDIR/pl-dm

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

tclIndex:
	../ami.tcl ../../tclscripts/pl-dm

clean&:
	@echo "" > /dev/null

noprod&:
	rm -f tclIndex

clobber&:
	@echo "" > /dev/null

#include "../../Cakefile.rules"
