/*
 *			iges/Cakefile
 */

#define SRCDIR	iges
#define PRODUCTS	iges-g g-iges
#define	SRCSUFF	.c
#define MANSECTION	1

#define STATIC_PRODUCTS	../SRCDIR/ge6.igs ../SRCDIR/wing128.igs \
	../SRCDIR/woodie.igs

#define FILES	 main usage readstart recsize readrec readglobal \
	readstrg readint readflt readtime makedir readcols \
	findp summary stack readtree showtree convtree \
	freetree \
	makemembers convsolids readname convassem matmult \
	readcnv evalxform readmatrix makegroup block2 \
	sphere wedge tor cyl cone ell convinst \
	extrude extrudcirc extrudcon getcurve \
	revolve splinef readdbl brlabs docolor spline convsurf \
	b-spline brep get_outer_shell add_inner_shell make_face \
	add_face add_loop get_edge_list read_edge_list \
	get_vertex_list read_vertex_list get_vertex get_att \
	read_att check_names planar_nurb g-iges iges conv_drawings orient_loops \
	trimsurf iges_types make_nurb_face get_iges_vertex get_cnurb_curve \
	do_subfigs

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

#define I_G_OBJ main.o usage.o readstart.o recsize.o readrec.o readglobal.o \
        readstrg.o readint.o readflt.o readtime.o makedir.o readcols.o \
        findp.o summary.o stack.o readtree.o showtree.o convtree.o \
        freetree.o \
        makemembers.o convsolids.o readname.o convassem.o matmult.o \
        readcnv.o evalxform.o readmatrix.o makegroup.o block2.o \
        sphere.o wedge.o tor.o cyl.o cone.o ell.o convinst.o \
        extrude.o extrudcirc.o extrudcon.o getcurve.o \
        revolve.o splinef.o readdbl.o brlabs.o docolor.o spline.o convsurf.o \
        b-spline.o brep.o get_outer_shell.o add_inner_shell.o make_face.o \
        add_face.o add_loop.o get_edge_list.o read_edge_list.o \
        get_vertex_list.o read_vertex_list.o get_vertex.o get_att.o \
        read_att.o check_names.o planar_nurb.o conv_drawings.o orient_loops.o \
	trimsurf.o iges_types.o make_nurb_face.o get_iges_vertex.o get_cnurb_curve.o \
	do_subfigs.o

iges-g:	I_G_OBJ LIBRT_DEP LIBWDB_DEP LIBBN_DEP LIBBU_DEP
	newvers.sh version "IGES-to-BRLCAD Translator"
	CC CFLAGS -c vers.c
	CC LDFLAGS -o iges-g I_G_OBJ vers.o LIBWDB LIBRT LIBBN LIBBU LIBBU_LIBES LIBES

#define G_I_OBJ g-iges.o iges.o

g-iges: G_I_OBJ LIBRT_DEP LIBBN_DEP LIBBU_DEP
	newvers.sh version "BRLCAD-to-IGES Translator"
	CC CFLAGS -c vers.c
	CC LDFLAGS -o g-iges G_I_OBJ vers.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES

#include "../Cakefile.rules"
