/*
 *			iges-g/Cakefile
 */

#define SRCDIR	iges-g
#define PRODUCTS	iges-g
#define	SRCSUFF	.c
#define MANSECTION	1

#define STATIC_PRODUCTS	../SRCDIR/ge6.igs ../SRCDIR/wing128.igs \
	../SRCDIR/woodie.igs

#define FILES	 main usage readstart recsize readrec readglobal \
	readstrg readint readflt readtime makedir readcols \
	findp summary stack readtree showtree convtree \
	copytree arrange bubbleup treecheck freetree \
	makemembers convsolids readname convassem matmult \
	readcnv evalxform readmatrix makegroup block2 \
	sphere wedge tor cyl cone ell convinst \
	extrude extrudcirc extrudcon getcurve \
	revolve splinef readdbl brlabs docolor spline convsurf \
	b-spline brep get_outer_shell add_inner_shell make_face \
	add_face add_loop get_edge_list read_edge_list \
	get_vertex_list read_vertex_list get_vertex get_att \
	read_att check_names

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

iges-g:	OBJ
	sh ../newvers.sh version "IGES-to-BRLCAD Translator"
	CC CFLAGS -c vers.c
	CC LDFLAGS -o iges-g OBJ vers.o LIB_PRE''LIBWDB LIB_PRE''LIBRT RT_CONFIG LIBRT_LIBES LIBES

#include "../Cakefile.rules"
