.TH IGES-G 1 BRL-CAD
.SH NAME
iges-g \- IGES Translator (IGES CSG to BRL-CAD)
.SH SYNOPSIS
.B iges-g
file.iges database.g
.SH DESCRIPTION
.I iges-g\^
converts the specified
.I file.iges
to a BRL-CAD
.I database.g
file. The IGES file is expected to conform to the ANSI standard,
ASME Y14.26M-1989, which
is esentially IGES 4.0. All IGES CSG objects are converted to BRL-CAD
equivalents. Most conversions are exact, with the exceptions of the solid of
revolution and the solid of linear extrusion. These solids do not exist in BRL-CAD
and are therefore approximated. The solid of revolution is built from a series of
truncated right cones developed by approximating the curve to be revolved with a series
of straight line segements. The extrusion is similarly handled by approximating the
curve to be extruded with straight line segments and using that to build a BRL-CAD
polysolid. An all-encompassing group is created, with the name "all", that includes
all the objects in the database not referenced by other objects.
IGES non-uniform rational B-spline surfaces (NURBS) are also converted, but this translator is not intended
to be a BREP translator at this time. All NURBS are combined into
a single BRLCAD spline solid named "nurb.s".
.SH EXAMPLE
.RS
$ \|\fIiges-g \|sample.iges \|sample.g\fP
.RE
.SH "SEE ALSO"
ASME Y14.26M-1989,
.I
Digital Representation for Communication of Product Definition Data.
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHORS
John Anderson
.br
Susanne Muuss
.br
Phil Dykstra
.br
Earl Weaver
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
