/*
 *			jove/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	jove
#define PRODUCTS	jove findcom
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	xxx

/* Don't let this JOVE get installed automatically,
 * as it may be different from the JOVE provided in /usr/brl/bin.
 */
#define DONT_INSTALL	1

#define JOVE_OBJ	jove_buf.o \
		jove_c.o \
		jove_delete.o \
		jove_disp.o \
		jove_draw.o \
		jove_extend.o \
		jove_funcs.o \
		jove_insert.o \
		jove_io.o \
		jove_main.o \
		jove_marks.o \
		jove_misc.o \
		jove_proc.o \
		jove_re.o \
		jove_screen.o \
		jove_term.o \
		jove_tune.o \
		jove_wind.o 


#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */
/* Do not use LIBES symbol.  We don't need anything but libc */

jove:	JOVE_OBJ
	sh ../SRCDIR/mkversion.sh
	CC LDFLAGS -o jove JOVE_OBJ version.o LIBTERMLIB

findcom:	findcom.o jove_tune.o
	CC LDFLAGS findcom.o jove_tune.o -o findcom

#include "../Cakefile.rules"
