/*
 *			jove/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	jove
#define PRODUCTS	jove findcom teach-jove
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	xxx

/* Don't let this JOVE get installed automatically,
 * as it may be different from the JOVE provided in /usr/brl/bin.
 */
/* #define DONT_INSTALL	1 */

#define JOVE_OBJ	jove_buf.o \
		jove_c.o \
		jove_delete.o \
		jove_disp.o \
		jove_draw.o \
		jove_extend.o \
		jove_funcs.o \
		jove_insert.o \
		jove_io.o \
		jove_main.o \
		jove_marks.o \
		jove_misc.o \
		jove_proc.o \
		jove_re.o \
		jove_screen.o \
		jove_term.o \
		jove_wind.o \
		tune.o \
		version.o


#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */
/* Do not use LIBES symbol.  We don't need anything but libc */

jove:	FRC JOVE_OBJ
	CC LDFLAGS -o jove JOVE_OBJ LIBTERMLIB
	rm -f version.o

findcom:	findcom.o tune.o
	CC LDFLAGS findcom.o tune.o -o findcom
	rm -f tune.o

teach-jove:	../SRCDIR/teach-jove.sh
	sed -e \'s;BinDir;BINDIR;\' -e \'s;LibDir;LIBDIR;\' < ../SRCDIR/teach-jove.sh > teach-jove

FRC:
	rm -f tune.o
	rm -f version.o
	sed -e \'s;BinDir;BINDIR;\' -e \'s;LibDir;LIBDIR;\' < ../SRCDIR/jove_tune.c > ../SRCDIR/tune.c
	if test ! -f version.number ; then echo 0 > version.number; fi
	c=`cat version.number`; \\
	rm -f version.number ../SRCDIR/version.c; \\
	echo $c | \\
		awk '{version = \$1 + 1; };END{printf "\%d\\\\n", version > "version.number"; }'; \\
	c=`cat version.number`; \\
	echo "char	version[] = \\\\"2.$c\\\\";" > ../SRCDIR/version.c
	touch FRC

#define EXTRA_INSTALL_TARGETS install-library

#include "../Cakefile.rules"

install-library&:
	cp ../SRCDIR/doc/describe.com LIBDIR/.
	cp ../SRCDIR/doc/teach-jove LIBDIR/.
