/*
 *			jove/Cakefile
 *
 *  $Header$
 */

#define SRCDIR	jove
#define PRODUCTS	jove findcom teach-jove
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	xxx

/* Don't let this JOVE get installed automatically,
 * as it may be different from the JOVE provided in /usr/brl/bin.
 */
#define DONT_INSTALL	1

#define JOVE_OBJ	jove_buf.o \
		jove_c.o \
		jove_delete.o \
		jove_disp.o \
		jove_draw.o \
		jove_extend.o \
		jove_funcs.o \
		jove_insert.o \
		jove_io.o \
		jove_main.o \
		jove_marks.o \
		jove_misc.o \
		jove_proc.o \
		jove_re.o \
		jove_screen.o \
		jove_term.o \
		jove_wind.o \
		tune.o \
		version.o


#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */
/* Do not use LIBES symbol.  We don't need anything but libc */

jove:	JOVE_OBJ
	CC LDFLAGS -o jove JOVE_OBJ LIBTERMLIB

findcom:	findcom.o tune.o
	CC LDFLAGS findcom.o tune.o -o findcom

teach-jove:	teach-jove.sh FRC
	sed -e 's;BinDir;$(BINDIR);' -e 's;LibDir;$(LIBDIR);' < teach-jove.sh > teach-jove

tune.c:		jove_tune.c FRC
	sed -e 's;LibDir;$(LIBDIR);' < jove_tune.c > tune.c

version.c:	FRC
	if test ! -f version.number ; then echo 0 > version.number; fi
	c=`cat version.number`; \
	rm -f version.number version.c; \
	echo $$c | \
		awk '{version = $$1 + 1; };END{printf "%d\n", version > "version.number"; }'; \
	c=`cat version.number`; \
	echo "char	version[] = \"2.$$c\";" > version.c

FRC:

#include "../Cakefile.rules"
