= Untitled
:doctype: article
:toc:
:toclevels: 3


* ../x.php[Articles]

** ../../articles/en/about.php[About BRL-CAD]

*** ../../articles/en/about.php#article-body[Introduction]
** ../../articles/en/build_pattern.php[Build Pattern]

*** ../../articles/en/build_pattern.php#build_pattern_generalinfo[Build Pattern Information]
*** ../../articles/en/build_pattern.php#build_pattern_names[Pattern Name]
*** ../../articles/en/build_pattern.php#build_pattern_fields[Common Fields For All Pattern Fields]
*** ../../articles/en/build_pattern.php#build_pattern_stringsub[Strings Substitution]
*** ../../articles/en/build_pattern.php#build_pattern_recpatterns[Rectangular Patterns]
*** ../../articles/en/build_pattern.php#build_pattern_spherical[Spherical Patterns]
*** ../../articles/en/build_pattern.php#build_pattern_cylind[Cylindrical Patterns]
** ../../articles/en/build_region.php[Build Region]
** ../../articles/en/camo_shader.php[Camouflage Shader]

*** ../../articles/en/camo_shader.php#Introduction[Introduction]
*** ../../articles/en/camo_shader.php#Limitations[Limitations]
** ../../articles/en/ged.php[GED]

*** ../../articles/en/ged.php#Preface[Preface]
*** ../../articles/en/ged.php#INTRODUCTION[Introduction]
*** ../../articles/en/ged.php#COMGEOM_BACKGROUND[Comgeom Background]
*** ../../articles/en/ged.php#COMPUTER_GRAPHICS[Computer Graphics]
*** ../../articles/en/ged.php#APPROACH_TO_THE_PROBLEM[Approach To The Problem]
*** ../../articles/en/ged.php#GED_OVERVIEW[GED Overview]
*** ../../articles/en/ged.php#GED_INTERNAL_DATA_STRUCTURE[GED Internal Data Structure]
*** ../../articles/en/ged.php#KEYBOARD_COMMANDS[Keyboard Commands]
*** ../../articles/en/ged.php#PERIPHERAL_DEVICES[Peripheral Devices]
*** ../../articles/en/ged.php#ANGLE_DISTANCE_CURSOR[ADC]
*** ../../articles/en/ged.php#VIEWING_FUNCTIONS[Viewing Functions]
*** ../../articles/en/ged.php#SELECTING_OBJECTS_FOR_EDITING[Selecting Objects For Editing]
*** ../../articles/en/ged.php#OBJECT_EDITING[Object Editing]
*** ../../articles/en/ged.php#SOLID_EDITING[Solid Editing]
*** ../../articles/en/ged.php#CONCLUSION[Conclusion]
** ../../articles/en/mged.php[MGED]

*** ../../articles/en/mged.php#Preface[Preface]
*** ../../articles/en/mged.php#Modeling_With_CSG[Modeling With CSG]

**** ../../articles/en/mged.php#Starting_MGED[Starting MGED]
**** ../../articles/en/mged.php#The_Screen_Coordinate_System[The Screen Coordinate System]
**** ../../articles/en/mged.php#Creating_Geometry[Creating Geometry]
**** ../../articles/en/mged.php#Editing_Solids[Editing Solids]
**** ../../articles/en/mged.php#Adding_a_Base[Adding A Base]
**** ../../articles/en/mged.php#Adding_a_fillet[Adding A Fillet]
*** ../../articles/en/mged.php#New_Graphical_User_Interface[MGED’s New Graphical User Interface]

**** ../../articles/en/mged.php#47403072[MGED’s New Graphical User Interface]
*** ../../articles/en/mged.php#cmd_line_ed[Command Line Editing]

**** ../../articles/en/mged.php#Emacs_Bindings[Emacs Bindings]
**** ../../articles/en/mged.php#VI_Bindings[Vi Bindings]
**** ../../articles/en/mged.php#Insert_Mode[Insert Mode]
**** ../../articles/en/mged.php#Command_Mode[Command Mode]
*** ../../articles/en/mged.php#MGED_User_Commands[MGED User Commands]

**** ../../articles/en/mged.php#MGEDDeveloperCommands[MGED Developer Commands]
*** ../../articles/en/mged.php#MGED_Tcl_Variables[MGED Tcl Variables]
*** ../../articles/en/mged.php#MGED_Environment_Variable[MGED Environment Variable]
*** ../../articles/en/mged.php#MGED_Callback[MGED Callback]
*** ../../articles/en/mged.php#Glossary[Glossary]
*** ../../articles/en/mged.php#BRL-CAD_Solid[BRLCAD Solids]
** ../../articles/en/mgedrc.php[MGEDRC]
** ../../articles/en/nirt.php[About Nirt]

*** ../../articles/en/nirt.php#NIRT_Basic_Syntax_and_operations[Nirt: Basic Syntax and Operations]

**** ../../articles/en/nirt.php#Command_Line_Help[Command Line Help]
**** ../../articles/en/nirt.php#Loading_a_Model[Loading A Model]
**** ../../articles/en/nirt.php#Shooting_a_Ray[Shooting a Ray]
**** ../../articles/en/nirt.php#Moving_the_Origination_Point[Moving The Origination Point]
**** ../../articles/en/nirt.php#Backing_Out_of_a_Model[Backing Out of a Model]
**** ../../articles/en/nirt.php#Changing_the_Direction_of_the_Ray[Changing the Direction of the Ray]
**** ../../articles/en/nirt.php#Reporting_of_Overlaps[Reporting of Overlaps]
*** ../../articles/en/nirt.php#Graphical_Visualization[Graphical Visualization: NIRT in MGED]

**** ../../articles/en/nirt.php#Basic_Usage[Basic Usage]
**** ../../articles/en/nirt.php#Backing_Out_with_NIRT_in_MGED[Backing Out with NIRT in MGED]
**** ../../articles/en/nirt.php#Ray_Segment_Coloring_with_Nirt[Ray Segment Coloring with NIRT and MGED]
**** ../../articles/en/nirt.php#Mouse-Based[Mouse-Based NIRT Usage]
**** ../../articles/en/nirt.php#Configuring_NIRT[Configuring NIRT]
*** ../../articles/en/nirt.php#Reporting_Options[Reporting Options]

**** ../../articles/en/nirt.php#How_to_Change_the_Reporting_Format[How To Change The Report Format]
**** ../../articles/en/nirt.php#Handling_Attribute_Reporting[Handling Attribute Reporting]
**** ../../articles/en/nirt.php#Changing_Units[Changing Units]
*** ../../articles/en/nirt.php#Other_Options[Other Options]

**** ../../articles/en/nirt.php#Silent_and_Verbose_Modes[Silent and Verbose Modes]
**** ../../articles/en/nirt.php#Using_Air_Regions[Using Air Regions]
**** ../../articles/en/nirt.php#Reading_an_Orientation[Reading an Orientation Matrix and Command]
*** ../../articles/en/nirt.php#Scripting_NIRT[Scripting NIRT]

**** ../../articles/en/nirt.php#Command_Line_Scripts[Command Line Scripts]
**** ../../articles/en/nirt.php#Scripts_Files[Scripts Files]
**** ../../articles/en/nirt.php#Defining_a_Custom[Defining a Custom Reporting Format]
**** ../../articles/en/nirt.php#Customizing_Report_Output_in_MGED[Customizing Report Output in MGED]
**** ../../articles/en/nirt.php#Reporting_Attributes_in_MGED[Reporting Attributes in MGED]
**** ../../articles/en/nirt.php#Available_Information_for_Inclusion_in_Reports[Available Information for Inclusion in Reports]
*** ../../articles/en/nirt.php#Summary[Summary]
** ../../articles/en/oed.php[oed]

*** ../../articles/en/oed.php#oed_Basic_Syntax_and_Operations[oed - Basic Syntax and Operations]
*** ../../articles/en/oed.php#Right_Hand_Path_Section[Right Hand Path Selection]
*** ../../articles/en/oed.php#Flexible_Manipulation[Flexible_Manipulation]
*** ../../articles/en/oed.php#sub_combination_editing[Sub-Combination Editing]
*** ../../articles/en/oed.php#Summary[Summary]
** ../../articles/en/pipes.php[Pipe]

*** ../../articles/en/pipes.php#pipe_general_use[General Use]
*** ../../articles/en/pipes.php#pipe_make_coil[Making a Coil]
** ../../articles/en/projection_shader.php[Projection Shader]

*** ../../articles/en/projection_shader.php#projshader_general[General]
*** ../../articles/en/projection_shader.php#projshader_getimage[Create/Obtain an Image to Project]
*** ../../articles/en/projection_shader.php#projshader_resize[Resize the Graphics Display]
*** ../../articles/en/projection_shader.php#projshader_actframe[Ensure the Framebuffer is Active]
*** ../../articles/en/projection_shader.php#projshader_dispimage[Display the Image]
*** ../../articles/en/projection_shader.php#projshader_overlayimage[Overlay the Image]
*** ../../articles/en/projection_shader.php#projshader_savesettingsfile[Save the Projection Shader Settings File]
*** ../../articles/en/projection_shader.php#projshader_render[Render the Image]
*** ../../articles/en/projection_shader.php#projshader_projectfront[Project the Image on the Front]
** ../../articles/en/tire.php#Overview[Tire]

*** ../../articles/en/tire.php#Specifying_a_Tire[Specifying Tire]
*** ../../articles/en/tire.php#Options_for_Tire[Options for Tire]
*** ../../articles/en/tire.php#Setting_Tire_Thickness[Setting Tire Thickness]
*** ../../articles/en/tire.php#Changing_the_Rim_width[Changing the Rim Width]
*** ../../articles/en/tire.php#Changing_the_Redial[Changing the Radial]
*** ../../articles/en/tire.php#Other_Options[Other Options]
*** ../../articles/en/tire.php#Structure_of_a_Tire[Structure of a Tire Model]
*** ../../articles/en/tire.php#Summary[Summary]
** ../../articles/en/TEMPLATE.php[Template]
* ../xx.php[Books]

** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php[BRL-CAD Tutorial Series-VolumeI]

*** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php#whatisbrlcad[What is Brlcad ?]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php#whycsg[Why CSG Modeling?]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php#packagecontent[Package Content]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php#libraries[Libraries]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php#toolsutilities[Tools Utilities]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php#benchmarkingimages[Benchmark Testing]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeI.php#acknowledgments[Acknowledgments]
** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php[BRL-CAD Tutorial Series-VolumeII]

*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Preface[Preface]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Acknowledgments[Acknowledgments]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-1[Creating Primitive Shapes]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#launching_mged[Launching the MGED Program]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#entering_commands[Entering Commands]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#using_gui[Using Gui]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#open_new_database[Open New Database]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#create_new_database[Create New Database]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#assign_title[Assign Title]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#set_units[Set Units]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#select_primitive[Select Primitive]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#create_sphere_cmd_line[Create Sphere Cmd Line]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#clear_window[Clear Window]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#draw_object[Draw Object]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#erase_from_window[Erase From Window]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#create_sphere_gui[Create Sphere Gui]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#view_params[View Params]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#list_db_contents[List db Contents]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#kill_object[Kill Object]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#editing_commands[Editing Commands]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#quitting[Quitting]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#creating_primitive_shapes_review[Creating Primitive Shapes Review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-2[Learning the Viewing Options]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#creating_radio[Creating Radio]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#locating_viewing_info_cmd_window[Locating Viewing info Cmd Window]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#entering_commands[Entering Commands]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#entering_commands[Entering Commands]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#coord_sys_summary[Coord sys Summary]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#view_radio_angles[View Radio Angles]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#shift_grips[Shift Grips]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#learning_viewing_options_review[Learning viewing options Review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lessons-3[Using the Insert Command to Size and Place Shapes]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#new_db_myShapes[New db MyShapes]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#sphere_make[Sphere Make]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#using_in[Using in]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#args_on_one_line[Args on one Line]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#command_combined_in[Command Combined in]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mged_naming_conventions[Mged Naming Conventions]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#view_shapes[View Shapes]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#using_insert_command_quit[Using insert command quit]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#using_insert_command_review[using insert command review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-4[Assigning Material Properties and Raytracing]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#assigning_material_properties_and_raytracing_opendb[Assigning material properties and raytracing opendb]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#create_region[Create Region]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#assign_material_prop[Assign Material Prop]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#clear_window_new_region[Clear Window New Region]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#raytrace_model[Raytrace Model]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#layers_graphics_window[Layers Graphics Window]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#clear_graphics_window[Clear Graphics Window]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#assigning_material_properties_and_raytracing_review[Review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-5[Learning About Boolean Expressions]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#boolean_tools[Boolean Tools]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#making_regions_bool_ops[Making regions bool ops]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#operator_precedence[Operator Precedence]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#learning_boolean_operations_review[Review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-6[Creating a Goblet]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_new_database[Goblet New Database]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_view_data_tree[Goblet view Data Tree]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#raytracing_goblet[Raytracing Goblet]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#creating_goblet_review[Creating Goblet Review]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#making_goblet_regions[Making Goblet Regions]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#making_goblet_region_comb[Making Goblet Region Comb]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#making_goblet_region_comb[Making Goblet Region Comb]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-8[Assigning Material Properties to Your Goblet]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_review_opening_db[Goblet review opening db]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_assign_colors[Goblet assign colors]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_transparency_mirror[Goblet transparency mirror]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_newforms_raytrace[Goblet newforms Raytrace]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_material_properties_review[Goblet material properties review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson[Assigning More Material Properties to Your Goblet]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_specular_diffuse[Goblet specular diffuse]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_refractive_index[Goblet refractive index]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_shininess[Goblet shininess]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_extinction[Goblet extinction]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_emission[Goblet emission]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_shader_attributes[Goblet shader attributes]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#goblet_material_properties2_review[Goblet material properties2 review]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-9[Creating a Globe in a Display Box]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#globe_in_display_newdb[Globe in display newdb]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#globe_create_display_box[Globe create display box]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#create_globe_in_box[Create globe in box]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#globe_assign_mater_prop[Globe assign mater prop]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#globe_move_rotate[Globe move rotate]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#globe_use_color_tool[Globe use color tool]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#globe_in_display_box_review[Globe in display box review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-11[Refining the Mug]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_new_db[Mug new db]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_outside_cyl[Mug outside cyl]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_handle[Mug handle]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_comb1[Mug comb1]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_comb2[Mug comb2]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_region[Mug region]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_review[Mug review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-12[Creating the Mug Through the GUI]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_mater_prop_mater_cmd[Mug mater prop mater cmd]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_raytrace1[Mug raytrace1]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_refining[Mug refining]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#mug_torus_cup_combine[Mug torus cup combine]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#refining_mug_review[Refining mug review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-13[Placing Shapes in 3-D Space]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_create_tabletop[candle create tabletop]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_create_base[candle create base]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_create_candle[candle create candle]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_create_flame[candle create flame]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_create_combination[candle create combination]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_check_data_tree[candle check data tree]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_assign_mater_prop[candle assign mater prop]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_raytrace[candle raytrace]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#placing_shapes_in_3d_review[placing shapes in 3d review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-14[Gaining More Practice Placing Shapes in Space]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_base_1st_sphere[candle base 1st sphere]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#multipane_feature[multipane feature]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#copies_of_shapes[copies of shapes]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#practice_make_regions_spheres[practice make regions spheres]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_base_spheres_combine[candle base spheres combine]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#placing_shapes_in_3d_2_review[placing shapes in 3d 2 review]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_assign_mater_prop[candle assign mater prop]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#candle_raytrace[candle raytrace]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#placing_shapes_in_3d_review[placing shapes in 3d review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-15[Creating a Toy Truck]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_cab_in_cmd[truck cab in cmd]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_hood_in_cmd[truck hood in cmd]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_cab_wheel_well[truck cab wheel well]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#ok_accept_apply_reset_cancel_dismiss[ok accept apply reset cancel dismiss]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_wheel_well_prim_edit_cpy[truck wheel well prim edit cpy]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_cab_shape_comb[truck cab shape comb]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_body_in_cmd[truck body in cmd]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#prim_ed_wheel_wells[prim ed wheel wells]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_body_wheel_wells_comb[truck body wheel wells comb]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_cab_body_region[truck cab body region]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_wheels[truck wheels]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_wheels_region[truck wheels region]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_regions_mater_props[truck regions mater props]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#on_screen_help[on screen help]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#stacker_shading[stacker shading]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#using_stacker_shading[using stacker shading]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_combine_regions[truck combine regions]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#truck_raytracing[truck raytracing]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#creating_toy_truck_review[creating toy truck review]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#Lesson-16[Learning Modeling Techniques and Structures]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#radio_shapes_to_regions[Radio shapes to regions]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#body_of_radio[body of radio]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#radio_other_regions[radio other regions]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#radio_assembly_comb[radio assembly comb]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#radio_assign_mater_props[radio assign mater props]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#radio_internal_components[radio internal components]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#radio_specialty_models[radio specialty models]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#radio_structure_redefinition[radio structure redefinition]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeII.php#modeling_techniques_and_structures_review[modeling techniques and structures review]
** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php[BRL-CAD_Tutorial_Series-VolumeIII]

*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#volIIIintro[Introduction]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#modelprocess[The Model Process]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#The_Importance_of_the_Model_Mission[The Importance of the Model Mission]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#M_O_D_E_L_A_Five-Step_Approach_to_Creating_Effective_Models[M-O-D-E-L: A Five-Step Approach to Creating Effective Models]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php##projshader_resize[Projshader resize]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#projshader_getimage[Projshader getimage]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#projshader_actframe[Projshader actframe]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#projshader_dispimage[Projshader dispimage]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#projshader_overlayimage[Projshader overlay image]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#projshader_savesettingsfile[Projshader savesettings file]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#projshader_projectfront[Projshader projectfront]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_generalinfo[Build pattern generalinfo]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_generalinfo[Build pattern general Info]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_names[Build pattern names]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_fields[Build pattern fields]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_stringsub[Build pattern stringsub]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_recpatterns[Build pattern recpatterns]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_cylind[Build pattern cyl ind]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_spherical[Build pattern spherical]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#volIIImodelprocess[Model process]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#volIIImeasuringdata[Measuring data]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#volIIIorganizing[organizing]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#volIIIdevgeometry[develop geometry]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#build_pattern_recpatterns[Build pattern recpatterns]
** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php[BRL-CAD_Tutorial_Series-VolumeIV]

*** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#chapt_introduction[Introduction]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Background_Purpose_and_Scope[Background, Purpose, and Scope]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#The_Need_for_Conversion[The Need for Conversion]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#chapt_pert_char[Pert char]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#CSG_vs._BREP[CSG_vs._BREP]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Prerelease_6.0_Database_vs._Current_Format[Prerelease 6.0 Database vs. Current Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converters_Currently_Available_in_BRL-CAD[Converters Currently Available in BRL-CAD]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#sec_convert_from_to_ascii[Convert from to ascii]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_ASCII[Converting From ASCII]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_ASCII[Converting_to_ASCII]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#sec_convert_to_brlcad[Convert to brlcad]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#General_Information_About_Converting_to_BRL-CAD[General Information About Converting to BRL-CAD]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_AutoCAD_DXF_Format[Converting From AutoCAD DXF Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_Elysium_Neutral_Facetted_Format[Converting From Elysium Neutral Facetted Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_EUCLID_Format[Converting From EUCLID Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_FASTGEN_Format[Converting From FASTGEN Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_IGES_Format[Converting From IGES Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_Jack[Converting From Jack]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_NASTRAN_Format[Converting From NASTRAN Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_Pro_E_Format[Converting From Pro/E Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_STL_Format[Converting From STL Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_TANKILL_Format[Converting From TANKILL Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_Unigraphics_Format[Converting From Unigraphics Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_From_Viewpoint_Datalabs_Format[Converting From Viewpoint Datalabs Format]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#sec_convert_from_brlcad[Convert from brlcad]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#General_Information_About_Converting_From_BRL-CAD[General Information About Converting From BRL-CAD]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_ACAD_Format[Converting to ACAD Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_AutoCAD_DXF_Format[Converting to AutoCAD DXF Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_EUCLID_Format[Converting to EUCLID Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_IGES_Format[Converting to IGES Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_Jack[Converting to Jack]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_STL_Format[Converting to STL Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_TANKILL_Format[Converting to TANKILL Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_VRML_Format[Converting to VRML Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_Wavefront_Format[Converting to Wavefront Format]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIV.php#Converting_to_X3D_Format[Converting to X3D Format]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#sec_build_new_converter[Build new converter]

**** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#General_Information_About_Building_a_New_Converter[General Information About Building a New Converter]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#Converting_From_BRL-CAD[Converting From BRL-CAD]
**** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#Converting_to_BRL-CAD[Converting to BRL-CAD]
*** ../../books/BRL-CAD_Tutorial_Series-VolumeIII.php#sec_postconversion_issues[Postconversion issues]
* ../xxx.php[Lessons]

** ../../lessons/en/mged01_creating_primitive_shapes.php[Mged01 creating primitive shapes]

*** ../../lessons/en/mged01_creating_primitive_shapes.php#launching_mged[Launching Mged]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#entering_commands[Entering commands]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#using_gui[Using gui]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#open_new_database[Open new database]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#create_new_database[Create new database]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#assign_title[Assign title]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#set_units[Set units]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#select_primitive[Select primitive]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#create_sphere_cmd_line[Create sphere cmd line]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#clear_window[Clear window]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#clear_window[Clear window]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#draw_object[Draw object]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#erase_from_window[Erase from window]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#create_sphere_gui[Create sphere gui]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#view_params[view params]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#list_db_contents[List db contents]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#kill_object[Kill object]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#editing_commands[Editing commands]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#quitting[Quitting]
*** ../../lessons/en/mged01_creating_primitive_shapes.php#creating_primitive_shapes_review[Creating primitive shapes review]
** ../../lessons/en/mged02_learning_viewing_options.php[Mged02 Learning Viewing Options in MGED]

*** ../../lessons/en/mged02_learning_viewing_options.php#creating_radio[Creating radio]
*** ../../lessons/en/mged02_learning_viewing_options.php#entering_commands[Locating viewing info cmd window]
*** ../../lessons/en/mged02_learning_viewing_options.php#viewing_system_elements[Viewing system elements]
*** ../../lessons/en/mged02_learning_viewing_options.php#coord_sys_summary[Coord sys summary]
*** ../../lessons/en/mged02_learning_viewing_options.php#view_radio_angles[View radio angles]
*** ../../lessons/en/mged02_learning_viewing_options.php#shift_grips[Shift grips]
*** ../../lessons/en/mged02_learning_viewing_options.php#learning_viewing_options_review[Learning viewing options review]
** ../../lessons/en/mged03_using_insert_command.php[Command to Size and Place Shapes]

*** ../../lessons/en/mged03_using_insert_command.php#new_db_myShapes[New db MyShapes]
*** ../../lessons/en/mged03_using_insert_command.php#sphere_make[Sphere Make]
*** ../../lessons/en/mged03_using_insert_command.php#using_in[Using in]
*** ../../lessons/en/mged03_using_insert_command.php#args_on_one_line[Args on one Line]
*** ../../lessons/en/mged03_using_insert_command.php#command_combined_in[Command Combined in]
*** ../../lessons/en/mged03_using_insert_command.php#mged_naming_conventions[Mged Naming Conventions]
*** ../../lessons/en/mged03_using_insert_command.php#view_shapes[View Shapes]
*** ../../lessons/en/mged03_using_insert_command.php#using_insert_command_quit[Using insert command quit]
*** ../../lessons/en/mged03_using_insert_command.php#using_insert_command_review[using insert command review]
** ../../lessons/en/mged04_assign_mat_prop_rt.php#6[Assigning Material Properties and Raytracing]

*** ../../lessons/en/mged04_assign_mat_prop_rt.php#assigning_material_properties_and_raytracing_opendb[Assigning material properties and raytracing opendb]
*** ../../lessons/en/mged04_assign_mat_prop_rt.php#create_region[Create Region]
*** ../../lessons/en/mged04_assign_mat_prop_rt.php#assign_material_prop[Assign Material Prop]
*** ../../lessons/en/mged04_assign_mat_prop_rt.php#clear_window_new_region[Clear Window New Region]
*** ../../lessons/en/mged04_assign_mat_prop_rt.php#raytrace_model[Raytrace Model]
*** ../../lessons/en/mged04_assign_mat_prop_rt.php#layers_graphics_window[Layers Graphics Window]
*** ../../lessons/en/mged04_assign_mat_prop_rt.php#clear_graphics_window[Clear Graphics Window]
*** ../../lessons/en/mged04_assign_mat_prop_rt.php#assigning_material_properties_and_raytracing_review[Review]
** ../../lessons/en/mged05_learning_boolean_expressions.php#7[Learning About Boolean Expressions]

*** ../../lessons/en/mged05_learning_boolean_expressions.php#boolean_tools[Boolean tools]
*** ../../lessons/en/mged05_learning_boolean_expressions.php#boolean_operations[Boolean operations]
*** ../../lessons/en/mged05_learning_boolean_expressions.php#making_regions_bool_ops[Making regions bool ops]
*** ../../lessons/en/mged05_learning_boolean_expressions.php#operator_precedence[Operator precedence]
*** ../../lessons/en/mged05_learning_boolean_expressions.php#learning_boolean_operations_review[Learning boolean operations review]
** ../../lessons/en/mged06_creating_a_goblet.php#8[Creating a Goblet]

*** ../../lessons/en/mged06_creating_a_goblet.php#goblet_new_database[Goblet New Database]
*** ../../lessons/en/mged06_creating_a_goblet.php#goblet_view_data_tree[Goblet view Data Tree]
*** ../../lessons/en/mged06_creating_a_goblet.php#raytracing_goblet[Raytracing Goblet]
*** ../../lessons/en/mged06_creating_a_goblet.php#creating_goblet_review[Creating Goblet Review]
*** ../../lessons/en/mged06_creating_a_goblet.php#making_goblet_regions[Making Goblet Regions]
*** ../../lessons/en/mged06_creating_a_goblet.php#making_goblet_region_comb[Making Goblet Region Comb]
*** ../../lessons/en/mged06_creating_a_goblet.php#making_goblet_region_comb[Making Goblet Region Comb]
** ../../lessons/en/mged07_goblet_material_properties.php#9[Assigning Material Properties to Your Goblet]

*** ../../lessons/en/mged07_goblet_material_properties.php#goblet_review_opening_db[Goblet review opening db]
*** ../../lessons/en/mged07_goblet_material_properties.php#goblet_assign_colors[Goblet assign colors]
*** ../../lessons/en/mged07_goblet_material_properties.php#goblet_transparency_mirror[Goblet transparency mirror]
*** ../../lessons/en/mged07_goblet_material_properties.php#goblet_newforms_raytrace[Goblet newforms Raytrace]
*** ../../lessons/en/mged07_goblet_material_properties.php#goblet_material_properties_review[Goblet material properties review]
** ../../lessons/en/mged08_goblet_material_properties2.php#10[Assigning More Material Properties to Your Goblet]

*** ../../lessons/en/mged08_goblet_material_properties2.php#goblet_specular_diffuse[Goblet specular diffuse]
*** ../../lessons/en/mged08_goblet_material_properties2.php#goblet_refractive_index[Goblet refractive index]
*** ../../lessons/en/mged08_goblet_material_properties2.php#goblet_shininess[Goblet shininess]
*** ../../lessons/en/mged08_goblet_material_properties2.php#goblet_extinction[Goblet extinction]
*** ../../lessons/en/mged08_goblet_material_properties2.php#goblet_emission[Goblet emission]
*** ../../lessons/en/mged08_goblet_material_properties2.php#goblet_shader_attributes[Goblet shader attributes]
** ../../lessons/en/mged09_globe_in_display_box.php#goblet_material_properties2_review#11[Goblet material properties2 review]

*** ../../lessons/en/mged09_globe_in_display_box.php[Creating a Globe in a Display Box]
*** ../../lessons/en/mged09_globe_in_display_box.php#globe_in_display_newdb[Globe in display newdb]
*** ../../lessons/en/mged09_globe_in_display_box.php#globe_create_display_box[Globe create display box]
*** ../../lessons/en/mged09_globe_in_display_box.php#create_globe_in_box[Create globe in box]
*** ../../lessons/en/mged09_globe_in_display_box.php#globe_assign_mater_prop[Globe assign mater prop]
*** ../../lessons/en/mged09_globe_in_display_box.php#globe_move_rotate[Globe move rotate]
*** ../../lessons/en/mged09_globe_in_display_box.php#globe_use_color_tool[Globe use color tool]
*** ../../lessons/en/mged09_globe_in_display_box.php#globe_in_display_box_review[Globe in display box review]
** ../../lessons/en/mged10_creating_mug.php#12[Refining the Mug]

*** ../../lessons/en/mged10_creating_mug.php#mug_new_db[Mug new db]
*** ../../lessons/en/mged10_creating_mug.php#mug_outside_cyl[Mug outside cyl]
*** ../../lessons/en/mged10_creating_mug.php#mug_handle[Mug handle]
*** ../../lessons/en/mged10_creating_mug.php#mug_comb1[Mug comb1]
*** ../../lessons/en/mged10_creating_mug.php#mug_comb2[Mug comb2]
*** ../../lessons/en/mged10_creating_mug.php#mug_region[Mug region]
*** ../../lessons/en/mged10_creating_mug.php#mug_review[Mug review]
** ../../lessons/en/mged11_refining_mug.php#14[Creating the Mug Through the GUI]

*** ../../lessons/en/mged11_refining_mug.php#mug_mater_prop_mater_cmd[Mug mater prop mater cmd]
*** ../../lessons/en/mged11_refining_mug.php#mug_raytrace1[Mug raytrace1]
*** ../../lessons/en/mged11_refining_mug.php#mug_refining[Mug refining]
*** ../../lessons/en/mged11_refining_mug.php#mug_torus_cup_combine[Mug torus cup combine]
*** ../../lessons/en/mged11_refining_mug.php#refining_mug_review[Refining mug review]
** ../../lessons/en/mged12_mug_through_gui.php#15[Creating the Mug Through the GUI]

*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_create_body[Mug gui create body]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_create_handle[Mug gui create handle]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_create_rim[Mug gui create rim]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_create_combinations[Mug gui create combinations]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_make_region[Mug gui make region]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_check_tree[Mug gui check tree]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_comb_edit_props[Mug gui comb edit props]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_gui_raytracing[Mug gui raytracing]
*** ../../lessons/en/mged12_mug_through_gui.php#mug_through_gui_review[Mug through gui review]
** ../../lessons/en/mged13_placing_shapes_in_3d.php#16[Placing Shapes in 3-D Space]

*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_create_tabletop[candle create tabletop]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_create_base[candle create base]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_create_candle[candle create candle]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_create_flame[candle create flame]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_create_combination[candle create combination]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_check_data_tree[candle check data tree]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_assign_mater_prop[candle assign mater prop]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#candle_raytrace[candle raytrace]
*** ../../lessons/en/mged13_placing_shapes_in_3d.php#placing_shapes_in_3d_review[placing shapes in 3d review]
** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#17[Gaining More Practice Placing Shapes in Space]

*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#candle_base_1st_sphere[candle base 1st sphere]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#multipane_feature[multipane feature]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#copies_of_shapes[copies of shapes]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#practice_make_regions_spheres[practice make regions spheres]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#candle_base_spheres_combine[candle base spheres combine]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#placing_shapes_in_3d_2_review[placing shapes in 3d 2 review]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#candle_assign_mater_prop[candle assign mater prop]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#candle_raytrace[candle raytrace]
*** ../../lessons/en/mged14_placing_shapes_in_3d_2.php#placing_shapes_in_3d_review[placing shapes in 3d review]
** ../../lessons/en/mged15_creating_a_toy_truck.php#17[Creating a Toy Truck]

*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_cab_in_cmd[truck cab in cmd]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_hood_in_cmd[truck hood in cmd]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_cab_wheel_well[truck cab wheel well]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#ok_accept_apply_reset_cancel_dismiss[ok accept apply reset cancel dismiss]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_wheel_well_prim_edit_cpy[truck wheel well prim edit cpy]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_cab_shape_comb[truck cab shape comb]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_body_in_cmd[truck body in cmd]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#prim_ed_wheel_wells[prim ed wheel wells]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_body_wheel_wells_comb[truck body wheel wells comb]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_cab_body_region[truck cab body region]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_wheels[truck wheels]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_wheels_region[truck wheels region]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_regions_mater_props[truck regions mater props]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#on_screen_help[on screen help]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#stacker_shading[stacker shading]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#using_stacker_shading[using stacker shading]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_combine_regions[truck combine regions]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#truck_raytracing[truck raytracing]
*** ../../lessons/en/mged15_creating_a_toy_truck.php#creating_toy_truck_review[creating toy truck review]
** ../../lessons/en/mged16_mod_tech_struct.php#19[Learning Modeling Techniques and Structures]

*** ../../lessons/en/mged16_mod_tech_struct.php#radio_shapes_to_regions[Radio shapes to regions]
*** ../../lessons/en/mged16_mod_tech_struct.php#body_of_radio[body of radio]
*** ../../lessons/en/mged16_mod_tech_struct.php#radio_other_regions[radio other regions]
*** ../../lessons/en/mged16_mod_tech_struct.php#radio_assembly_comb[radio assembly comb]
*** ../../lessons/en/mged16_mod_tech_struct.php#radio_assign_mater_props[radio assign mater props]
*** ../../lessons/en/mged16_mod_tech_struct.php#radio_internal_components[radio internal components]
*** ../../lessons/en/mged16_mod_tech_struct.php#radio_specialty_models[radio specialty models]
*** ../../lessons/en/mged16_mod_tech_struct.php#radio_structure_redefinition[radio structure redefinition]
*** ../../lessons/en/mged16_mod_tech_struct.php#modeling_techniques_and_structures_review[modeling techniques and structures review]
* ../xxxx.php[Man 1]

** ../../man1/en/ap-pix.php[AP Pix]
** ../../man1/en/asc2dsp.php[Asc2dsp]
** ../../man1/en/asc2g.php[ASC2G]
** ../../man1/en/asc-nmg.php[ASC NMG]
** ../../man1/en/asc-plot3.php[ASC PLOT 3]
** ../../man1/en/azel.php[Azel]
** ../../man1/en/bary.php[Bary]
** ../../man1/en/benchmark.php[Benchmark]
** ../../man1/en/bot_dump.php[Bot Dump]
** ../../man1/en/brep_simple.php[Brep Simple]
** ../../man1/en/brlcad.php[Brlcad]
** ../../man1/en/brlcad-config.php[BrlCad Config]
** ../../man1/en/buffer.php[Buffer]
** ../../man1/en/bw3-pix.php[BW 3 Pix]
** ../../man1/en/bwcrop.php[BwCrop]
** ../../man1/en/bwdiff.php[BWDfiff]
** ../../man1/en/bw-fb.php[BW FB]
** ../../man1/en/bwfilter.php[BW Filter]
** ../../man1/en/bwhist.php[Bwhist]
** ../../man1/en/bwhisteq.php[Bwhisteq]
** ../../man1/en/bw-imp.php[Bw Imp]
** ../../man1/en/bwmod.php[Bwmod]
** ../../man1/en/bw-pix.php[BW PIX]
** ../../man1/en/bw-png.php[BW PNG]
** ../../man1/en/bw-ps.php[BW PS]
** ../../man1/en/bwrect.php[BW Rect]
** ../../man1/en/bw-rle.php[BW RLE]
** ../../man1/en/bwrot.php[BW ROT]
** ../../man1/en/bwscale.php[BW SCALE]
** ../../man1/en/bwshrink.php[BW Shrink]
** ../../man1/en/bwstat.php[BW STAT]
** ../../man1/en/bwthresh.php[BW THRESH]
** ../../man1/en/cad_boundp.php[CAP Boundp]
** ../../man1/en/cad_parea.php[CAD Parea]
** ../../man1/en/cell-fb.php[Cell FB]
** ../../man1/en/cmap-fb.php[Cmap FB]
** ../../man1/en/coil.php[Coil]
** ../../man1/en/comgeom-g.php[Comgeom G]
** ../../man1/en/conv-vg2g.php[Conv vg2g]
** ../../man1/en/cv.php[Cv]
** ../../man1/en/cy-g.php[Cy-g]
** ../../man1/en/db.php[db]
** ../../man1/en/dbclean.php[Db Clean]
** ../../man1/en/dbcp.php[Db cp]
** ../../man1/en/decimate.php[Decimate]
** ../../man1/en/dpix-pix.php[Dpix pix]
** ../../man1/en/dxf-g.php[Dxf-g]
** ../../man1/en/enf-g.php[enf-g]
** ../../man1/en/euclid-g.php[euclid-g]
** ../../man1/en/fast4-g.php[Fast4-g]
** ../../man1/en/fbanim.php[Fbanim]
** ../../man1/en/fb-bw.php[Fb-bw]
** ../../man1/en/fbcbars.php[Fbcbars]
** ../../man1/en/fbclear.php[Fbclear]
** ../../man1/en/fbcmap.php[Fbcmap]
** ../../man1/en/fb-cmap.php[Fb Cmap]
** ../../man1/en/fbcmrot.php[Fbcmrot]
** ../../man1/en/fbcolor.php[Fbcolor]
** ../../man1/en/fbfade.php[Fbfade]
** ../../man1/en/fb-fb.php[FB-FB]
** ../../man1/en/fbframe.php[Fb Frame]
** ../../man1/en/fbfree.php[Fb Free]
** ../../man1/en/fbgamma.php[Fb Gamma]
** ../../man1/en/fbgrid.php[Fb Grid]
** ../../man1/en/fbhelp.php[Fb Help]
** ../../man1/en/fblabel.php[Fb Label]
** ../../man1/en/fbline.php[Fb Line]
** ../../man1/en/fb-pix.php[Fb pix]
** ../../man1/en/fb-png.php[Fb Png]
** ../../man1/en/fbpoint.php[Fb Point]
** ../../man1/en/fb-rle.php[Fb RLE]
** ../../man1/en/fbscanplot.php[Fb Scanplot]
** ../../man1/en/fbserv.php[Fb Serv]
** ../../man1/en/fbstretch.php[Fb Stretch]
** ../../man1/en/fbzoom.php[Fb zoom]
** ../../man1/en/firpass.php[Fir pass]
** ../../man1/en/g2asc.php[G2asc]
** ../../man1/en/g-acad.php[g-aced]
** ../../man1/en/gdiff2.php[Gdiff2]
** ../../man1/en/g_diff.php[G Diff]
** ../../man1/en/g-dxf.php[G dxf]
** ../../man1/en/g-egg.php[G-egg]
** ../../man1/en/gencolor.php[Gen Color]
** ../../man1/en/g-euclid.php[g-euclid]
** ../../man1/en/gif2fb.php[Gif 2 fb]
** ../../man1/en/gif-fb.php[Gif Fb]
** ../../man1/en/g-iges.php[g-iges]
** ../../man1/en/g_lint.php[G Lint]
** ../../man1/en/g_niff.php[G-niff]
** ../../man1/en/g-nmg.php[G nmg]
** ../../man1/en/g-obj.php[G obj]
** ../../man1/en/gqa.php[gqa]
** ../../man1/en/g-raw.php[G raw]
** ../../man1/en/g-shell-rect.php[G Shell Rect]
** ../../man1/en/g-step.php[G Step]
** ../../man1/en/g-stl.php[G-stl]
** ../../man1/en/g-tankill.php[G tankill]
** ../../man1/en/g-var.php[G-var]
** ../../man1/en/g-x3d.php[G x3d]
** ../../man1/en/halftone.php[Halftone]
** ../../man1/en/hex.php[hex]
** ../../man1/en/iges-g.php[Iges-g]
** ../../man1/en/imgdims.php[Imgdims]
** ../../man1/en/irdisp.php[Irdisp]
** ../../man1/en/ir-X.php[Ir-X]
** ../../man1/en/loop.php[Loop]
** ../../man1/en/mac-pix.php[Mac Pix]
** ../../man1/en/mged.php[Mged]
** ../../man1/en/morphedit.php[Morphedit]
** ../../man1/en/nastran-g.php[Nastran]
** ../../man1/en/nirt.php[Nirt]
** ../../man1/en/nmg-bot.php[nmg-bot]
** ../../man1/en/nmg-rib.php[Nmg-rib]
** ../../man1/en/obj-g.php[obj-g]
** ../../man1/en/patch-g.php[Patch G]
** ../../man1/en/pictx.php[Pictx]
** ../../man1/en/pix2asc.php[Pix 2 asc]
** ../../man1/en/pix-alias.php[Pix Alias]
** ../../man1/en/pixautosize.php[Pix Autosize]
** ../../man1/en/pixbackgnd.php[Pix Backgnd]
** ../../man1/en/pixbgstrip.php[Pix Gstrip]
** ../../man1/en/pixblend.php[Pix Blend]
** ../../man1/en/pixborder.php[Pix border]
** ../../man1/en/pixbustup.php[Pix Bustup]
** ../../man1/en/pix-bw.php[Pix Bw]
** ../../man1/en/pix-bw3.php[Pix Bw 3]
** ../../man1/en/pixclump.php[Pix Clump]
** ../../man1/en/pixcmp.php[Pix Cmp]
** ../../man1/en/pixcolors.php[Pix Color]
** ../../man1/en/pixcut.php[Pix Cut]
** ../../man1/en/pixdiff.php[Pix Diff]
** ../../man1/en/pixfade.php[Pix Fade]
** ../../man1/en/pix-fb.php[Pix fb]
** ../../man1/en/pixfilter.php[Pix Filter]
** ../../man1/en/pixhalve.php[Pix Halve]
** ../../man1/en/pixhist.php[Pix hist]
** ../../man1/en/pixhist3d.php[Pix hist3d]
** ../../man1/en/pixhist3d-plot3.php[Pix hist3d Plot3]
** ../../man1/en/pixinterp2x.php[Pix Interp2x]
** ../../man1/en/pixmatte.php[Pix Matte]
** ../../man1/en/pixmerge.php[Pix Merge]
** ../../man1/en/pixmorph.php[Pix Morph]
** ../../man1/en/pix-png.php[Pix Png]
** ../../man1/en/pix-ppm.php[Pix Ppm]
** ../../man1/en/pix-ps.php[Pix ps]
** ../../man1/en/pixrect.php[Pix Rect]
** ../../man1/en/pix-rle.php[Pix rle]
** ../../man1/en/pixrot.php[Pix rot]
** ../../man1/en/pixsaturate.php[Pix saturate]
** ../../man1/en/pixscale.php[pixscale]
** ../../man1/en/pixshrink.php[Pix Shrink]
** ../../man1/en/pixstat.php[Pix Stat]
** ../../man1/en/pixsubst.php[Pix subst]
** ../../man1/en/pix-sun.php[Pix Sun]
** ../../man1/en/pixtile.php[Pixtile]
** ../../man1/en/pixuntile.php[Pix untile]
** ../../man1/en/plot3-asc.php[Plot3 Asc]
** ../../man1/en/pixcolors.php[Plot 3 Color]
** ../../man1/en/plot3debug.php[Plot 3 debug]
** ../../man1/en/plot3-fb.php[Plot3-fb]
** ../../man1/en/plot3getframe.php[Plot 3 get frame]
** ../../man1/en/plot3-hpgi.php[Plot 3 hpgi]
** ../../man1/en/plot3line2.php[Plot 3 line 2]
** ../../man1/en/plot3-plot3.php[Plot 3]
** ../../man1/en/plot3-ps.php[Plot3 ps]
** ../../man1/en/plot3rot.php[Plot 3 rot]
** ../../man1/en/plot3-tek.php[Plot 3 tek]
** ../../man1/en/plot3-X.php[Plot3 x]
** ../../man1/en/ply-g.php[ply g]
** ../../man1/en/png-bw.php[Png bw]
** ../../man1/en/png-fb.php[Png fb]
** ../../man1/en/png_info.php[Png Info]
** ../../man1/en/png-pix.php[Png Pix]
** ../../man1/en/random.php[Random]
** ../../man1/en/ramapid.php[Ramapid]
** ../../man1/en/remrt.php[Remrt]
** ../../man1/en/reshoot.php[Reshoot]
** ../../man1/en/rel-fb.php[Rle Fb]
** ../../man1/en/rle-pix.php[Rle Pix]
** ../../man1/en/rpatch.php[Rpatch]
** ../../man1/en/rt.php[Rt]
** ../../man1/en/rtarea.php[Rtarea]
** ../../man1/en/rt_bot_faces.php[Rt Bot Faces]
** ../../man1/en/rtcheck.php[Rt Check]
** ../../man1/en/rtedge.php[R Tedge]
** ../../man1/en/rtexample.php[Rt example]
** ../../man1/en/rtg3.php[RTG3]
** ../../man1/en/rthide.php[RT Hide]
** ../../man1/en/rtpp.php[RT PP]
** ../../man1/en/rtrange.php[Rt Range]
** ../../man1/en/rtray.php[R Tray]
** ../../man1/en/rtscale.php[Rt Scale]
** ../../man1/en/rtshot.php[Rt shot]
** ../../man1/en/rtwalk.php[Rt Walk]
** ../../man1/en/rtweight.php[Rt Weight]
** ../../man1/en/rtwizard.php[Rt Wizard]
** ../../man1/en/rtxray.php[Rt xray]
** ../../man1/en/scriptsort.php[Script sort]
** ../../man1/en/secpass.php[Sec Pass]
** ../../man1/en/shapefact.php[Shape Fact]
** ../../man1/en/showshot.php[Show Shot]
** ../../man1/en/showtherm.php[Show Therm]
** ../../man1/en/stl-g.php[Stl g]
** ../../man1/en/sun-pix.php[Sun Pix]
** ../../man1/en/tankill-g.php[Tankill G]
** ../../man1/en/terrain.php[Terrain]
** ../../man1/en/tire.php[Tire]
** ../../man1/en/ug-g.php[Ug g]
** ../../man1/en/vdeck.php[Vdeck]
** ../../man1/en/viewpoint-g.php[View Point]
** ../../man1/en/wavelet.php[wavelet]
** ../../man1/en/wdb_example.php[Wdb Example]
* ../xxxxx.php[Man 3]

** ../../man3/en/libfb.php[Lib fb]
** ../../man3/en/librole.php[Lib Role]
** ../../man3/en/libplot3.php[Lib Plot3]
** ../../man3/en/librt.php[Librt]
** ../../man3/en/libwdb.php[Libwdb]
** ../../man3/en/redblack.php[Red Black]
* ../xxxxxx.php[Man 5]

** ../../man5/en/attributes.php[Attributes]
** ../../man5/en/bw.php[bw]
** ../../man5/en/cmap.php[Cmap]
** ../../man5/en/dsp.php[Dsp]
** ../../man5/en/pix.php[Pix]
** ../../man5/en/plot3.php[Plot 3]
* ../xxxxxxx.php[Mann]

** ../../mann/en/3ptarb.php[3 Ptarb]
** ../../mann/en/adc.php[ADC]
** ../../mann/en/ae.php[AE]
** ../../mann/en/alias-pix.php[Alias Pix]
** ../../mann/en/analyze.php[Analyze]
** ../../mann/en/animmate.php[Animmate]
** ../../mann/en/apropos.php[Apropos]
** ../../mann/en/aproposdevel.php[Apropos Devel]
** ../../mann/en/aproposlib.php[Apropos Lib]
** ../../mann/en/arced.php[Arced]
** ../../mann/en/area.php[Area]
** ../../mann/en/arot.php[Arot]
** ../../mann/en/attach.php[Attach]
** ../../mann/en/attr.php[Attr]
** ../../mann/en/autoview.php[Auto View]
** ../../mann/en/B.php[B]
** ../../mann/en/bb.php[BB]
** ../../mann/en/bev.php[Bev]
** ../../mann/en/bo.php[Bo]
** ../../mann/en/bolt.php[Bolt]
** ../../mann/en/bot_condense.php[Bot Condense]
** ../../mann/en/bot_decimate.php[Bot Decimate]
** ../../mann/en/bot_face_fuse.php[Bot Face Fuse]
** ../../mann/en/bot_face_sort.php[Bot Face Sort]
** ../../mann/en/bot_flip.php[Bot Flip]
** ../../mann/en/bot_sync.php[Bot Sync]
** ../../mann/en/bot_vertex_fuse.php[Bot Vertex Fuse]
** ../../mann/en/brep.php[Brep]
** ../../mann/en/build_region.php[Build Region]
** ../../mann/en/c.php[C]
** ../../mann/en/cat.php[Cat]
** ../../mann/en/center.php[Center]
** ../../mann/en/color.php[Color]
** ../../mann/en/comb.php[Comb]
** ../../mann/en/comb_color.php[Comb Color]
** ../../mann/en/copyeval.php[CopyEval]
** ../../mann/en/copymat.php[Copy Mat]
** ../../mann/en/cp.php[CP]
** ../../mann/en/cpi.php[CPI]
** ../../mann/en/d.php[D]
** ../../mann/en/db.php[DB]
** ../../mann/en/dbconcat.php[DB Concat]
** ../../mann/en/db_glob.php[DB Glob]
** ../../mann/en/dbupgrade.php[DB Upgrade]
** ../../mann/en/debugbu.php[De Bugbu]
** ../../mann/en/debugdir.php[De Bugdir]
** ../../mann/en/debuglib.php[De Buglib]
** ../../mann/en/debugnmg.php[De Bugnmg]
** ../../mann/en/decompose.php[De Compose]
** ../../mann/en/delay.php[Delay]
** ../../mann/en/dm.php[DM]
** ../../mann/en/draw.php[Draw]
** ../../mann/en/dup.php[Dup]
** ../../mann/en/E.php[E]
** ../../mann/en/eac.php[EAC]
** ../../mann/en/echo.php[Echo]
** ../../mann/en/e_command.php[E Command]
** ../../mann/en/edcodes.php[Ed Codes]
** ../../mann/en/edcolor.php[Ed Color]
** ../../mann/en/edcomb.php[Ed Comb]
** ../../mann/en/edgedir.php[Ed Gedir]
** ../../mann/en/edit.php[Edit]
** ../../mann/en/edit_translate.php[Edit Translate]
** ../../mann/en/edmater.php[Ed Mater]
** ../../mann/en/eqn.php[EQN]
** ../../mann/en/erase.php[Erase]
** ../../mann/en/ev.php[EV]
** ../../mann/en/exists.php[Exists]
** ../../mann/en/exit.php[Exit]
** ../../mann/en/expand.php[Expand]
** ../../mann/en/extrude.php[Extrude]
** ../../mann/en/eye_pt.php[Eye Pt]
** ../../mann/en/facedef.php[Face Def]
** ../../mann/en/facetize.php[Facetize]
** ../../mann/en/find.php[Find]
** ../../mann/en/fracture.php[Fracture]
** ../../mann/en/g.php[G]
** ../../mann/en/garbage_collect.php[Garbage Collect]
** ../../mann/en/gastank.php[Gastank]
** ../../mann/en/gqa.php[GQA]
** ../../mann/en/gr.php[GR]
** ../../mann/en/graph.php[Graph]
** ../../mann/en/gui.php[Gui]
** ../../mann/en/handle.php[Handle]
** ../../mann/en/help.php[Help]
** ../../mann/en/helpdevel.php[Help Devel]
** ../../mann/en/helplib.php[Help Lib]
** ../../mann/en/hide.php[Hide]
** ../../mann/en/history.php[History]
** ../../mann/en/i.php[I]
** ../../mann/en/idents.php[Idents]
** ../../mann/en/igraph.php[I Graph]
** ../../mann/en/ill.php[ILL]
** ../../mann/en/in.php[IN]
** ../../mann/en/inside.php[Inside]
** ../../mann/en/Introduction.php[Introduction]
** ../../mann/en/item.php[ITEM]
** ../../mann/en/journal.php[Journal]
** ../../mann/en/keep.php[Keep]
** ../../mann/en/keypoint.php[Key Point]
** ../../mann/en/kill.php[Kill]
** ../../mann/en/killall.php[Kill All]
** ../../mann/en/killtree.php[Kill Tree]
** ../../mann/en/knob.php[Knob]
** ../../mann/en/l.php[L]
** ../../mann/en/labelvert.php[Labelvert]
** ../../mann/en/lc.php[Lc]
** ../../mann/en/listeval.php[Listeval]
** ../../mann/en/loadtk.php[Load Tk]
** ../../mann/en/lookat.php[Lookat]
** ../../mann/en/ls.php[Ls]
** ../../mann/en/M.php[M]
** ../../mann/en/make.php[Make]
** ../../mann/en/make_pnts.php[Make Pnts]
** ../../mann/en/mater.php[Mater]
** ../../mann/en/matpick.php[Mat Pick]
** ../../mann/en/mirface.php[MirFace]
** ../../mann/en/mrot.php[Mrot]
** ../../mann/en/mv.php[Mv]
** ../../mann/en/mvall.php[Mvall]
** ../../mann/en/nirt.php[Nirt]
** ../../mann/en/nmg_collapse.php[NMG Collapse]
** ../../mann/en/nmg_simplify.php[NMG Simplify]
** ../../mann/en/oed.php[oed]
** ../../mann/en/opendb.php[Open DB]
** ../../mann/en/orientation.php[Orientation]
** ../../mann/en/orot.php[Orot]
** ../../mann/en/oscale.php[Oscale]
** ../../mann/en/overlay.php[Over Lay]
** ../../mann/en/p.php[P]
** ../../mann/en/pathlist.php[Pathlist]
** ../../mann/en/paths.php[Path]
** ../../mann/en/permute.php[Permute]
** ../../mann/en/picket_fence.php[Picket Fence]
** ../../mann/en/plot.php[Plot]
** ../../mann/en/prcolor.php[Pr Color]
** ../../mann/en/prefix.php[Prefix]
** ../../mann/en/press.php[Press]
** ../../mann/en/preview.php[Preview]
** ../../mann/en/prj_add.php[Prj Add]
** ../../mann/en/ps.php[Ps]
** ../../mann/en/pull.php[Pull]
** ../../mann/en/push.php[Push]
** ../../mann/en/put_comb.php[Put Comb]
** ../../mann/en/putmat.php[Putmat]
** ../../mann/en/q.php[Q]
** ../../mann/en/qorot.php[Qorot]
** ../../mann/en/qray.php[Qray]
** ../../mann/en/query_ray.php[Query Ray]
** ../../mann/en/quit.php[Quit]
** ../../mann/en/qvrot.php[Qvrot]
** ../../mann/en/r.php[R]
** ../../mann/en/rcc-blend.php[Rcc Blend]
** ../../mann/en/rcc-cap.php[Rcc Cap]
** ../../mann/en/rcc-tgc.php[Rcc Tgc]
** ../../mann/en/rcc-tor.php[rcc-tor]
** ../../mann/en/rcodes.php[Rocdes]
** ../../mann/en/red.php[Red]
** ../../mann/en/refresh.php[Refresh]
** ../../mann/en/regdebug.php[Regdebug]
** ../../mann/en/regdef.php[Regdef]
** ../../mann/en/regions.php[Regions]
** ../../mann/en/reid.php[Reid]
** ../../mann/en/release.php[Release]
** ../../mann/en/rfarb.php[Rfarb]
** ../../mann/en/rm.php[RM]
** ../../mann/en/rmater.php[Rmater]
** ../../mann/en/rot.php[Rot]
** ../../mann/en/rotobj.php[Rotobj]
** ../../mann/en/rpp-arch.php[Rpp Arch]
** ../../mann/en/rpp-cap.php[Rpp Cap]
** ../../mann/en/rrt.php[RRT]
** ../../mann/en/rt.php[Rt]
** ../../mann/en/rtarea.php[Rt area]
** ../../mann/en/rtcheck.php[Rt Check]
** ../../mann/en/saveview.php[Save View]
** ../../mann/en/sca.php[Sca]
** ../../mann/en/search.php[Search]
** ../../mann/en/sed.php[Sed]
** ../../mann/en/setview.php[Set View]
** ../../mann/en/shader.php[Shader]
** ../../mann/en/shell.php[Shell]
** ../../mann/en/showmats.php[Show Mats]
** ../../mann/en/size.php[Size]
** ../../mann/en/solids.php[Solids]
** ../../mann/en/sph-part.php[Sph Part]
** ../../mann/en/status.php[Status]
** ../../mann/en/summary.php[Summary]
** ../../mann/en/sv.php[Sv]
** ../../mann/en/sync.php[Sync]
** ../../mann/en/t.php[T]
** ../../mann/en/ted.php[Ted]
** ../../mann/en/title.php[Title]
** ../../mann/en/tol.php[Tol]
** ../../mann/en/tops.php[Tops]
** ../../mann/en/tor-rcc.php[Tor rcc]
** ../../mann/en/tra.php[Tra]
** ../../mann/en/track.php[Track]
** ../../mann/en/translate.php[Translate]
** ../../mann/en/tree.php[Tree]
** ../../mann/en/units.php[Units]
** ../../mann/en/vars.php[Vars]
** ../../mann/en/vdraw.php[Vdraw]
** ../../mann/en/view.php[View]
** ../../mann/en/viewsize.php[Viewsize]
** ../../mann/en/vnirt.php[Vnirt]
** ../../mann/en/voxelize.php[Voxelize]
** ../../mann/en/vquery_ray.php[Vquery Ray]
** ../../mann/en/vrot.php[vrot]
** ../../mann/en/wcodes.php[Wcodes]
** ../../mann/en/whatid.php[What Id]
** ../../mann/en/whichair.php[WhichAir]
** ../../mann/en/which_shader.php[Which Shader]
** ../../mann/en/who.php[Who]
** ../../mann/en/window.php[Window]
** ../../mann/en/window_frame.php[Window Frame]
** ../../mann/en/wire.php[Wire]
** ../../mann/en/wmater.php[Wmater]
** ../../mann/en/x.php[X]
** ../../mann/en/xpuch.php[Xpuch]
** ../../mann/en/Z.php[Z]
** ../../mann/en/zoom.php[zoom]
* ../xxxxxxxx.php[Presentations]

** ../../presentations/en/Introduction-brlcad-app-devel.php[Application Development with BRL-CAD]
** ../../presentations/en/Introduction-to-tcltk.php[Introduction To TclTK]
* ../xxxxxxxxx.php[Specifications]

** ../../specifications/en/BRL_CAD_g_format_V5.php[BRL-CAD G Format V5]

*** ../../specifications/en/BRL_CAD_g_format_V5.php#Background_and_Terminology[Background and Terminology]

**** ../../specifications/en/BRL_CAD_g_format_V5.php#Format_of_Data_Elements_Database_External_Format[Format of Data Elements Database External Format]
*** ../../specifications/en/BRL_CAD_g_format_V5.php#Definition_of_a_Single_Generic_Database_Object[Definition of a Single, Generic Database Object]

**** ../../specifications/en/BRL_CAD_g_format_V5.php#Object_Structure[Object Structure]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Flags[Flags]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Object_Type[Object Type]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Object_Length[Object Length]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Object_Name[Object Name]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Object_Attributes[Object Attributes]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Object_Body[Object Body]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Padding_and_Length_Rounding[Padding and Length Rounding]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#How_Objects_Are_Grouped_into_a_Database[How Objects Are Grouped into a Database]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Details_of_BRL-CAD-Specific_Nongeometric_Database_Object_Types[Details of BRL-CAD-Specific Nongeometric Database Object Types]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Details_of_BRL-CAD-Specific_Geometric_Database_Object_Types[Details of BRL-CAD-Specific Geometric Database Object Types]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Extensions_for_Deferred_Implementation[Extensions for Deferred Implementation]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Community_Feedback_on_the_Proposal[Community Feedback on the Proposal]
**** ../../specifications/en/BRL_CAD_g_format_V5.php#Database_Library_Application_Programming_Interface[Database Library Application Programming Interface (API)]
