#!/bin/sh

F="/usr/share/applications/defaults.list"
G="/etc/gnome/defaults.list"
H="mged.desktop"

if [ ! -f $F ] && [ ! -h $F ]
then
	if [ -f $G ]
	then
		ln -s $G $F || :
	else
		echo "[Default Applications]" > $F || :
	fi
fi

sed --follow-symlinks -i "/application\/brlcad-v[45]/d" $F || :

echo "application/brlcad-v4=$H" >> $F || :
echo "application/brlcad-v5=$H" >> $F || :

source /etc/profile.d/brlcad.sh || :

update-mime-database /usr/share/mime || :
