/*
 *			zlib/Cakefile
 */
#define SRCDIR	libz
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#if !defined(BUILD_LIBRARY)
#define PRODUCTS	libz.a
#define CONFIG_OPTS	-p BASEDIR
#define	AFTER_MAKE	/**/
#define	FIX_FILE	afile
#else
#define PRODUCTS	libz.so
#define SHARED_PRODUCT	libz.so''[[LIBVERS]]
#define CONFIG_OPTS	-s -p BASEDIR
#define	AFTER_MAKE	mv libz.so SHARED_PRODUCT ; sharedliblink.sh SHARED_PRODUCT
#define	FIX_FILE	sfile
#endif

PRODUCTS: Makefile.MTYPE
	make -f Makefile.MTYPE PRODUCTS
	AFTER_MAKE

Makefile.in:	if not exist Makefile.in
	cp ../SRCDIR/Makefile.in .

Makefile.MTYPE:	Makefile.in	if not exist Makefile.MTYPE
	( \C\C=\"CC\"; \
		\C\F\L\A\G\S=\"GFLAG OPTIMIZER PROFILER -I../SRCDIR\"; \
		\R\A\N\L\I\B=\"RANLIB\"; \
		\L\D\F\L\A\G\S=\"LDFLAGS\"; \
		export \C\C \C\F\L\A\G\S \R\A\N\L\I\B \L\D\F\L\A\G\S; \
		../SRCDIR/configure CONFIG_OPTS; \
		../SRCDIR/fix_makefile.sh FIX_FILE  >  Makefile.MTYPE)


clean&:
	make -f Makefile.MTYPE clean

noprod&:
	rm -rf *.so *.a

clobber&: Makefile.MTYPE
	make -f Makefile.MTYPE clean
	rm -f *.MTYPE Makefile

install&: Makefile.MTYPE
	cp ../SRCDIR/zlib.h .
	cp ../SRCDIR/zconf.h .
	make -f Makefile.MTYPE install prefix=BASEDIR

install-nobak&: Makefile.MTYPE
	cp ../SRCDIR/zlib.h .
	cp ../SRCDIR/zconf.h .
	make -f Makefile.MTYPE install prefix=BASEDIR

test&: Makefile.MTYPE
	make -f Makefile.MTYPE test

