/*
 *			html/ReleaseNotes/Rel5.0/Cakefile
 */
#include "../../../Cakefile.defs"

#define PRODUCTS	*.html
#define STATIC_PRODUCTS	*.html
#define SRCDIR	Rel5.0
#undef BINDIR
#define BINDIR	BASEDIR/html/ReleaseNotes/Rel5.0
#undef BINPERM
#define BINPERM 444

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

#include "../../../Cakefile.rules"
