/*
 *			tab/Cakefile
 */

#define SRCDIR	tab
#define PRODUCTS	tabinterp txyz-pl tabsub scriptsort script-tab
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define FILES	tabinterp txyz-pl tabsub

/* Explicit composition of each product */

tabinterp: tabinterp.o LIBRT_DEP
	CC LDFLAGS tabinterp.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o tabinterp

tabsub:	tabsub.o  LIBRT_DEP
	CC LDFLAGS tabsub.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o tabsub

txyz-pl:	txyz-pl.o LIBPLOT_DEP
	CC LDFLAGS txyz-pl.o LIBPLOT LIBES -o txyz-pl

scriptsort:	scriptsort.o script.o LIBBU_DEP
	CC LDFLAGS scriptsort.o script.o LIBBN LIBBU LIBBU_LIBES LIBES -o scriptsort

script-tab:	script-tab.o  LIBRT_DEP
	CC LDFLAGS script-tab.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o script-tab

#include "../Cakefile.rules"
