/*
 *			tab/Cakefile
 */

#define SRCDIR	tab
#define PRODUCTS	tabinterp txyz-pl tabsub
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define FILES	tabinterp txyz-pl tabsub

/* Explicit composition of each product */

tabinterp: tabinterp.o LIBRT_DEP
	CC LDFLAGS tabinterp.o LIBRT LIBRT_LIBES LIBES -o tabinterp

tabsub:	tabsub.o  LIBRT_DEP
	CC LDFLAGS tabsub.o LIBRT LIBRT_LIBES LIBES -o tabsub

txyz-pl:	txyz-pl.o LIBPLOT_DEP
	CC LDFLAGS txyz-pl.o LIBPLOT LIBES -o txyz-pl

#include "../Cakefile.rules"
