#define FLOAT	1
#define INT	2
#define	SHELL	3
#define COMMENT	4
#define	START	5
#define	VIEWSIZE 6
#define EYEPT	7
#define	LOOKATPT 8
#define VIEWROT	9
#define ORIENTATION 10
#define END	11
#define TREE	12
#define MULTIVIEW	13
#define ANIM	14
#define MATRIX	15
#define RMUL	16
#define LMUL	17
#define RBOTH	18
#define RSTACK	19
#define RARC	20
#define CLEAN	21
#define SET	22
#define WIDTH	23
#define HEIGHT	24
#define PERSPECTIVE 25
#define ANGLE	26
#define	AE	27
#define OPT	28
#define STRING	29
#define SEMI	30
#define PATH	31
