/*
 *			iwidgets/Cakefile
 */
#define SRCDIR	iwidgets4.0.1
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#define IWIDGET_OPTS	--prefix=BASEDIR --with-tcl=[[pwd]]/LIBTCL_DIR --with-tk=[[pwd]]/LIBTK_DIR \
			--with-itcl=[[pwd]]/../libitcl''ITCL_VERS \
			--cache-file cache.MTYPE

/* Rule to see if cake is running with -s flag */
#define MINUS_S	[[echo CAKEFLAGS | tr '\040' '\012' | sed -n -e /-s/p ]]

all&: Makefile.MTYPE cache.MTYPE
	echo cakeflags=CAKEFLAGS
	echo make MINUS_S -f Makefile.MTYPE CAKEFLAGS all
	make MINUS_S -f Makefile.MTYPE CAKEFLAGS all

Makefile.MTYPE cache.MTYPE:		if not exist Makefile.MTYPE or not exist cache.MTYPE
	( INSTALL=[[pwd]]/../SRCDIR/config/install-sh ; \
		 export INSTALL; \
		 echo ../SRCDIR/configure IWIDGET_OPTS; \
		 ../SRCDIR/configure IWIDGET_OPTS; \
		mv Makefile Makefile.MTYPE)

clean&:	Makefile.MTYPE
	make -f Makefile.MTYPE clean

noprod&: Makefile.MTYPE
	make -f Makefile.MTYPE clean

clobber&:
	rm -f *.MTYPE config.log config.status *.tcl

install&: Makefile.MTYPE
	make -f Makefile.MTYPE install

install-nobak&: Makefile.MTYPE
	make -f Makefile.MTYPE install

test&: Makefile.MTYPE
	make -f Makefile.MTYPE test

