.TH BW 5 BRL-CAD
.\"                           B W . 5
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2008 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
bw \- Black and White image file format and utilities
.SH FORMAT
A
.I bw
file contains sequences of pixels.
Each pixel is stored as one \fBunsigned char\fR, and thus
ranges in intensity from 0 (black) to 255 (white).
The first pixel in a
.I bw
file is the lower left corner of the image.
The pixels proceed from left-to-right across each scanline,
with scanlines being written from the bottom to the top of the image.
.PP
By convention,
.I bw
images are usually square, and thus their dimensions
can be determined by the file size.  If this is not the case, often
only the file width need be known by a program reading the file.  History
has left us with two "standard" sizes, 512x512 and the "higher" 1024x1024.
A common practice for other file sizes is to include the file width in
the filename.
.PP
At some time in the future
.I bw
files will probably get self-typing headers so that parameters such as
their size can be automatically determined by programs.
.SH UTILITIES
.B bw-fb
display a .bw format image on a framebuffer.
.br
.B fb-bw
produce a .bw file from a framebuffer image.
.br
.B bw-pix
convert a .bw file to a color .pix file.
.br
.B pix-bw
convert a color .pix file to a .bw file.
.br
.B bwstat
gives statistics concerning a .bw file.
.br
.B bwhist
displays a histogram on a framebuffer.
.br
.B bwmod
a filter to shift and scale pixel intensities.
.br
.B bwdiff
yields the difference between two .bw files.
.br
.B bwrect
extracts an arbitrary rectangle from a .bw file.
.br
.B bwcrop
maps any quadrilateral in a .bw file into any rectangle.
.br
.B bwrot
rotates, reverses, or inverts a .bw file.
.br
.B bwscale
scales a .bw file larger or smaller.
.br
.B bwfilter
a variety of 3x3 kernel filters for .bw images.
.br
.B bw3-pix
merges three .bw files into one .pix file.
.br
.B pix-bw3
separates .pix file RGB colors into three .bw files.
.br
.SH FILES
file.bw
.SH SEE ALSO
brlcad(1), pix(5), and above named programs.
