'\" t
.\"     Title: BW
.\"    Author:
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/04/2012
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "BW" "5" "12/04/2012" "BRL\-CAD" "BRL\-CAD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bw \- Black and White image file format and utilities
.SH "FORMAT"
.PP
A
\fIbw\fR
file contains sequences of pixels\&. Each pixel is stored as one
\fBunsigned char\fR, and thus ranges in intensity from 0 (black) to 255 (white)\&. The first pixel in a
\fIbw\fR
file is the lower left corner of the image\&. The pixels proceed from left\-to\-right across each scanline, with scanlines being written from the bottom to the top of the image\&.
.PP
By convention,
\fIbw\fR
images are usually square, and thus their dimensions can be determined by the file size\&. If this is not the case, often only the file width need be known by a program reading the file\&. History has left us with two "standard" sizes, 512x512 and the "higher" 1024x1024\&. A common practice for other file sizes is to include the file width in the filename\&.
.PP
At some time in the future
\fIbw\fR
files will probably get self\-typing headers so that parameters such as their size can be automatically determined by programs\&.
.SH "UTILITIES"
.PP
\fBbw\-fb\fR
display a \&.bw format image on a framebuffer\&.
.PP
\fBfb\-bw\fR
produce a \&.bw file from a framebuffer image\&.
.PP
\fBbw\-pix\fR
convert a \&.bw file to a color \&.pix file\&.
.PP
\fBpix\-bw\fR
convert a color \&.pix file to a \&.bw file\&.
.PP
\fBbwstat\fR
gives statistics concerning a \&.bw file\&.
.PP
\fBbwhist\fR
displays a histogram on a framebuffer\&.
.PP
\fBbwmod\fR
a filter to shift and scale pixel intensities\&.
.PP
\fBbwdiff\fR
yields the difference between two \&.bw files\&.
.PP
\fBbwrect\fR
extracts an arbitrary rectangle from a \&.bw file\&.
.PP
\fBbwcrop\fR
maps any quadrilateral in a \&.bw file into any rectangle\&.
.PP
\fBbwrot\fR
rotates, reverses, or inverts a \&.bw file\&.
.PP
\fBbwscale\fR
scales a \&.bw file larger or smaller\&.
.PP
\fBbwfilter\fR
a variety of 3x3 kernel filters for \&.bw images\&.
.PP
\fBbw3\-pix\fR
merges three \&.bw files into one \&.pix file\&.
.PP
\fBpix\-bw3\fR
separates \&.pix file RGB colors into three \&.bw files\&.
.SH "FILES"
.PP
file\&.bw
.SH "SEE ALSO"
.PP
\fBbrlcad\fR(1),
\fBpix\fR(5), and above named programs\&.
.SH "AUTHOR"
.PP
BRL\-CAD Team
.SH "COPYRIGHT"
.PP
This software is Copyright (c) 1989\-2012 by the United States Government as represented by U\&.S\&. Army Research Laboratory\&.
.SH "BUG REPORTS"
.PP
Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad\&.org>\&.
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
