'\" t
.\"     Title: CMAP
.\"    Author:
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/04/2012
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "CMAP" "5" "12/04/2012" "BRL\-CAD" "BRL\-CAD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cmap \- Framebuffer colormap file format and utilities
.SH "FORMAT"
.PP
A
\fIcmap\fR
file is a storage format for framebuffer colormaps\&. It is an ascii file with one line per colormap entry\&. In order to accommodate colormaps of any "depth" (number of bits per entry), 16 bit unsigned integers were selected (see
\fBlibfb\fR(3)
for a discussion of the C program interface to colormaps)\&. A value of zero corresponds to full off, or black, a value of 65535 decimal or ffff hexadecimal corresponds to full on, or white\&. A given device will use as many of the "leftmost" bits as it can support\&.
.PP
Each line of the file has a decimal colormap index, followed by a tab character, and then three 4 digit hexadecimal values, separated by spaces, which correspond to the red, green, and blue, channels\&. Any blank lines or lines beginning with non\-numeric characters are ignored, and can thus be used for comments\&.
.PP
There is no requirement for all 256 entries to be specified\&. What is done with any unspecified entries is up to the individual programs using the colormap\&.
.SH "EXAMPLE"
.PP
The beginning of an eight bit inverse video colormap might look as follows:
.sp
.if n \{\
.RS 4
.\}
.nf
	# Inverse video colormap
	0       ff00 ff00 ff00
	1       fe00 fe00 fe00
	2       fd00 fd00 fd00
	3       fc00 fc00 fc00
	4       fb00 fb00 fb00

.fi
.if n \{\
.RE
.\}
.SH "UTILITIES"
.PP
\fBfb\-cmap\fR
save a colormap from a framebuffer\&.
.PP
\fBcmap\-fb\fR
load a saved colormap into a framebuffer\&.
.PP
\fBfbcmap\fR
loads one of several "standard" colormaps\&.
.PP
\fBfbgamma\fR
loads gamma correcting colormaps\&.
.SH "FILES"
.PP
file\&.cm
.SH "SEE ALSO"
.PP
\fBbrlcad\fR(1), and above named programs\&.
.SH "AUTHOR"
.PP
BRL\-CAD Team
.SH "COPYRIGHT"
.PP
This software is Copyright (c) 1989\-2012 by the United States Government as represented by U\&.S\&. Army Research Laboratory\&.
.SH "BUG REPORTS"
.PP
Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad\&.org>\&.
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
