'\" t
.\"     Title: PIX
.\"    Author:
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/04/2012
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "PIX" "5" "12/04/2012" "BRL\-CAD" "BRL\-CAD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pix \- Color RGB image file format and utilities
.SH "FORMAT"
.PP
A
\fIpix\fR
file contains sequences of pixels\&. Each pixel is stored as three
\fBunsigned char\fRs, first red, then green, then blue\&. The intensity of each color ranges from 0 ("off") to 255 ("on")\&. The first pixel in a
\fIpix\fR
file is the lower left corner of the image\&. The pixels proceed from left\-to\-right across each scanline, with scanlines being written from the bottom to the top of the image\&.
.PP
By convention,
\fIpix\fR
images are usually square, and thus their dimensions can be determined by the file size\&. If this is not the case, often only the file width need be known by a program reading the file\&. History has left us with two "standard" sizes, 512x512 and the "higher" 1024x1024\&. A common practice for other file sizes is to include the file width in the filename\&.
.PP
At some time in the future
\fIpix\fR
files will probably get self\-typing headers so that parameters such as their size can be automatically determined by programs\&.
.SH "UTILITIES"
.PP
\fBpix\-fb\fR
display a \&.pix format image on a framebuffer\&.
.PP
\fBfb\-pix\fR
produce a \&.pix file from a framebuffer image\&.
.PP
\fBpix\-bw\fR
convert a \&.pix file to a black and white \&.bw file\&.
.PP
\fBbw\-pix\fR
convert a black and white \&.bw file to a \&.pix file\&.
.PP
\fBap\-pix\fR
convert an Applicon Color Plotter file to a \&.pix file\&.
.PP
\fBpixtile\fR
combine several small \&.pix files into one large one\&.
.PP
\fBpixstat\fR
gives statistics concerning a \&.pix file\&.
.PP
\fBpixhist\fR
displays a color histogram on a framebuffer\&.
.PP
\fBpixhist3d\fR
display three views of an RGB color space histogram on a framebuffer\&.
.PP
\fBpixhist3d\-pl\fR
unix plot of RGB color space utilization\&.
.PP
\fBpixdiff\fR
shows which pixels/colors differ between two \&.pix files\&.
.PP
\fBpixrect\fR
extracts an arbitrary rectangle from a \&.pix file\&.
.PP
\fBpixrot\fR
rotate, reverse, or invert a \&.pix file\&.
.PP
\fBpixscale\fR
scale a \&.pix file up or down\&.
.PP
\fBpixfilter\fR
a collection of 3x3 kernel filters for \&.pix files\&.
.PP
\fBbw3\-pix\fR
merges three \&.bw files into one \&.pix file\&.
.PP
\fBpix\-bw3\fR
separates \&.pix file RGB colors into three \&.bw files\&.
.SH "FILES"
.PP
file\&.pix
.SH "SEE ALSO"
.PP
\fBbrlcad\fR(1),
\fBbw\fR(5), and above named programs\&.
.SH "AUTHOR"
.PP
BRL\-CAD Team
.SH "COPYRIGHT"
.PP
This software is Copyright (c) 1989\-2012 by the United States Government as represented by U\&.S\&. Army Research Laboratory\&.
.SH "BUG REPORTS"
.PP
Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad\&.org>\&.
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
