/*
 *			tk/Cakefile
 */

#define SRCDIR	tk
#define PRODUCTS	wish bwish tktest
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"

/* Eliminate the normal BRL-CAD defines */
#undef CFLAGS
/* Keep the -64 flag, etc */
#define CFLAGS TK_DEFS  GFLAG -I''INCDIR -I''XINCDIR

#define HEADER_FILES ../libtk/tkInt.h ../libtk/tkPort.h ../libtk/tkUnixPort.h \
			../libtcl/limits.h ../libtcl/stdlib.h ../libtcl/unistd.h

/* Explicit composition of each product */

everything&::	PRODUCTS

wish: tkAppInit.o LIBTCL_DEP LIBTK_DEP
	CC LDFLAGS -o wish tkAppInit.o LIBTK LIBTCL LIBTCL_LIBES -L''XLIBDIR -lX11 LIBES

bwish: bwish.o LIBTCLCAD_DEP LIBTCL_DEP LIBTK_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS -o bwish bwish.o LIBTCLCAD LIBTK LIBTCL LIBRT LIBBN LIBBU LIBBU_LIBES -L''XLIBDIR -lX11 LIBES

tktest: tkTest.o tkSquare.o LIBTCL_DEP LIBTK_DEP LIBBU_DEP LIBBN_DEP LIBRT_DEP
	CC LDFLAGS -o tktest tkTest.o tkSquare.o LIBTK LIBTCL LIBRT LIBBU LIBBU_LIBES LIBBN -L''XLIBDIR -lX11 LIBES

tkAppInit.o: ../SRCDIR/tkAppInit.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/tkAppInit.c

bwish.o: ../SRCDIR/bwish.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/bwish.c

tkTest.o: ../SRCDIR/tkTest.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/tkTest.c

tkSquare.o: ../SRCDIR/tkSquare.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/tkSquare.c
/*
%.h:
        cp ../libtk/%.h %.h */

#include "../Cakefile.rules"
