/*
 *			tk/Cakefile
 */

#define SRCDIR	tk
#define PRODUCTS	wish bwish tktest
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"

#undef unix

/* Eliminate the normal BRL-CAD defines */
#undef CFLAGS
/* Keep the -64 flag, etc */
#define CFLAGS TK_DEFS  GFLAG -I''INCDIR -I''XINCDIR

#define HEADER_FILES ../libtk/generic/tkInt.h ../libtk/generic/tkPort.h \
	../libtk/unix/tkUnixPort.h \
	../libtcl/compat/limits.h ../libtcl/compat/stdlib.h ../libtcl/compat/unistd.h

/* Explicit composition of each product */

everything&::	PRODUCTS

wish: tkAppInit.o LIBTCL_DEP LIBTK_DEP
	CC LDFLAGS -o wish tkAppInit.o LIBTK LIBTCL LIBTCL_LIBES -L''XLIBDIR -lX11 LIBES

bwish: bwish.o LIBTCLCAD_DEP LIBTCL_DEP LIBTK_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS -o bwish tkAppInit.o bwish.o LIBTCLCAD LIBTK LIBTCL LIBTCL_LIBES LIBRT LIBBN LIBBU LIBBU_LIBES -L''XLIBDIR -lX11 LIBES

tktest: tkTest.o tkSquare.o LIBTCL_DEP LIBTK_DEP LIBBU_DEP LIBBN_DEP LIBRT_DEP
	CC LDFLAGS -o tktest tkAppInit.o tkTest.o tkSquare.o LIBTK LIBTCL LIBTCL_LIBES LIBRT LIBBU LIBBU_LIBES LIBBN -L''XLIBDIR -lX11 LIBES

tkAppInit.o: ../SRCDIR/tkAppInit.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/tkAppInit.c

bwish.o: ../SRCDIR/bwish.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/bwish.c

tkTest.o: ../SRCDIR/tkTest.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/tkTest.c

tkSquare.o: ../SRCDIR/tkSquare.c HEADER_FILES
	CC CFLAGS -c ../SRCDIR/tkSquare.c

#include "../Cakefile.rules"
