.TH ALIAS-PIX 1 BRL/CAD
.SH NAME
alias\(hypix	\- convert an image from Alias(tm) pix format to BRL PIX(5) format
.SH SYNOPSIS
.B alias-pix
[
.I \-v
]
< ALIASpixfile > BRLpixfile 
.SH DESCRIPTION
.Ialias\(hypix
converts the 
.I Alias pix
format file on the standard input to an 
.I BRL PIX(5)
format file on the standard output.
.SH OPTIONS
.TP
.B \-v
print a text summary of the Alias pix file header on standard error output.
