.TH BW-PNG 1 BRL/CAD
.SH NAME
bw-png	\- convert a BRL BW(5) format image to a PNG (Portable Network Graphics) format
.SH SYNOPSIS
.B bw-png
.RB [ \-a ]
.RB [ \-s squaresize]
.RB [ \-w file_width]
.RB [ \-n file_height]
 [BRLbwfile] > PNG_file
.SH DESCRIPTION
.I bw-png
converts a
.I BRL BW(5)
format file to a
.I PNG
format file on the standard output. The PNG file created will be an Gray scale file with a bit-depth of 8 and a file gamma of 1.0.
.SH OPTIONS
.TP
.B \-a
autosize the input file to determine file image height and width
.TP
.B \-n file_height
tells
.I bw-png
that the input is
.I file_height
scanlines tall
.TP
.B \-s squaresize
sets both the width and the height for the input to be
.I squaresize
.TP
.B \-w file_width
tells
.I bw-png
that the input is
.I file_width
pixels wide


