.TH LOOP 1B BRL/CAD
.SH NAME
loop \- generate integer indices for shell loops, etc
.SH SYNOPSIS
.B loop
.B start
.B finish
[
.B increment
]
.SH DESCRIPTION
.I loop\^
generates a sequence of integers between
.B start
and
.B finish
inclusive, one per line, on stdout.
This is mostly useful for driving loops when writing Shell programs
.IR sh (1).
The default increment is +1 when start<finish, and -1 when start>finish.
An optional
.B increment
may be specified.
If
.B increment
is zero, then the
.B start
value will be generated continuously.
.SH AUTHORS
Phil Dykstra
.br
Douglas P. Kingston III
.br
Michael John Muuss
.SH BUGS
This program just scratches the surface.
The shells could benefit from a greater ability to perform math.
Limitless opportunities for extensions exist, but
this simple version is adequate for most shell scripts
dealing with sequences of images, etc.
