.TH PIX-SUN 1 BRL/CAD
.SH NAME
pix\(hysun	\- convert a BRL PIX(5) format image to a Sun Rasterfile format
.SH SYNOPSIS
.B pix-sun
.RB [ \-d ]
.RB [ \-s\  squaresize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
< BRLpixfile > rasterfile
.SH DESCRIPTION
.Ipix\(hysun
converts the 
.I BRL PIX(5)
format file on the standard input to a
.I Sun Rasterfile
format file on the standard output.  The rasterfile produced is a
"standard" (as opposed to "byte encoded") image, with
8 bits per pixel, with a pallete of 256 colors.
.SH OPTIONS
.TP
.B \-d
use a dither map
.TP
.B \-n file_height
tells
.I pix\(hysun
that the input is
.I file_height
scanlines tall
.TP
.B \-s squaresize
sets both the width and the height for the input to be
.I squaresize
.TP
.B \-w file_width
tells
.I pix\(hysun
that the input is
.I file_width
pixels wide


