.TH PIX-ALIAS 1 BRL/CAD
.SH NAME
pix\(hyalias	\- convert an image from BRL PIX(5) format to Alias(tm) pix format
.SH SYNOPSIS
.B pix-alias
[
.I \-s squaresize
]
[
.I \-w file_width
]
[
.I \-n file_height
]
< BRLpixfile > ALIASpixfile
.SH DESCRIPTION
.Ipix\(hyalias
converts the 
.I BRL PIX(5)
format file on the standard input to an 
.I Alias pix
format file on the standard output.
.SH OPTIONS
.TP
.B \-n file_height
tells
.I pix\(hyalias
that the input is
.I file_height
scanlines tall
.TP
.B \-s squaresize
sets both the width and the height for the input to be
.I squaresize
.TP
.B \-w file_width
tells
.I pix\(hyalias
that the input is
.I file_width
pixels wide


