.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.TH PIXBORDER 1
.SH NAME
pixborder \- add a 1-pixel-wide border to regions of a specified color
.SH SYNOPSIS
.B pixborder
.RB [ \-b\  "'R\ G\ B']"
.RB [ \-i\  "'R\ G\ B']"
.RB [ \-t\  "'R\ G\ B']"
.RB [ \-B\  "'H\ S\ V']"
.RB [ \-I\  "'H\ S\ V']"
.RB [ \-T\  "'H\ S\ V']"
.RB [ \-x\  left_edge]
.RB [ \-y\  top_edge]
.RB [ \-X\  right_edge]
.RB [ \-Y\  bottom_edge]
.RB [ \-ah ]
.RB [ \-n\  file_height]
.RB [ \-s\  squaresize]
.RB [ \-w\  file_width]
[file.pix]
.SH DESCRIPTION
.I Pixborder
reads an input stream of
.I pix
data,
looking for maximal contiguous regions of
a specified interior color,
and writes out the
.I pix
data
with all pixels on the boundaries of these regions changed to
a specified border color.
A pixel is considered to be on the boundary if its color
is the specified interior color
and at least one of its four neighbors
(left, right, above, and below) has some other color.
The data is read from
.I file.pix
if it is specified;
otherwise,
.I pixborder
reads from the standard input.

By default,
.I pixborder
expects a 512 \(mu 512 image,
interpreting regions using an interior color of 255 255 255,
and changing boundary pixels to a border color of 1 1 1.
The
.B -i
option causes
.I pixborder
to replace
the default interior color by
.IR "R G B" .
The
.B -b
option likewise sets
the border color to
.IR "R G B" .

Variation in the color of the region interior
may be accomodated by the
.B -t
option,
with which one specifies a symmetric tolerance
for each of the red, green, and blue channels.
Any color
within the specified tolerance of the nominal interior color
is treated as though it were the interior color.

The
.BR -B , -I ,
and
.B -T
options are analogous to
.BR -b , -i ,
and
.BR -t ,
respectively,
except that they are used to specify colors
in the HSV color model.
.IR H , S ,
and
.I V
are reals,
with
\fIH\fR in [0,\ 360)
and
\fIS\fR, \fIV\fR in [0,\ 1].


.SH HINT
To obtain borders more than one pixel wide,
one can run several copies of
.I pixborder
in a pipeline.
In doing this together with the
.BR -x , -y , -X ,
and
.B -Y
options
to get, for instance, a border made up of constant-thickness
segments of different colors,
one should produce all the segments of a given layer
before beginning any segments of the next inner layer.
.SH AUTHOR
Paul Tanenbaum
