.\" Set the interparagraph spacing to 1 (default is 0.4)
.PD 1v
.\"
.\" The man page begins...
.\"
.TH PIXCLUMP 1
.SH NAME
pixclump \- quantize the colors in a pix(5) stream
.SH SYNOPSIS
.B pixclump
.RB [ \-c\  R/G/B]"
.RB [ \-f\  color_file]
.RB [ \-x\  debug_flags]
[infile.pix [outfile.pix]]

.SH DESCRIPTION
.I Pixclump
reads an input stream of
.I pix
data,
converts each pixel to one of a set of specified colors,
and writes out these quantized pixels.

The colors
may be specified
either on the command line,
with one
.B -c
option per color,
or in a file specified with the
.B -f
option.

Each pixel in the input stream
is compared to all of the specified colors
and replaced on the output by the specified color most resembling it.
.I Pixclump
computes the difference between an input pixel and a specified color
as the sum of the squares of the differences in their respective
red, green, and blue channels.

The
.B -x
option may be used to selectively enable
various diagnostic print statements.

.SH HINT
A typical use for
.I pixclump
is in renormalizing an image.
For example,
if a tool such as
.I pixscale
has been used to transform
an image containing a relatively small number of colors,
.I pixclump
will change pixels whose colors have been interpolated
back to one of the original colors.

.SH AUTHOR
Paul Tanenbaum
