.TH PIXCOLORS 1 BRL/CAD
.SH NAME
pixcolors	\- Count/list color values used in a PIX(5) format image
.SH SYNOPSIS
.B pixcolors
.RB [ \-v ]
< pixfile 
.SH DESCRIPTION
.I Pixcolors
reports on the standard output the number of distinct colors used in the
.I pix(5)
format file on the standard input.
.SH OPTIONS
.TP
.BI \-v
Causes a sorted list of the unique colors
used to be printed on standard output in addition to the count report.
