.TH QUERY  1 BRL/CAD
.SH NAME
query \- query the user for input
.SH SYNOPSIS
.B query
.RB [ \-t [seconds] ]
.RB [ \-r [response]]
.SH DESCRIPTION
By default, 
.I query
reads a line from standard input and echoes it to standard output.
options include:
.TP
.B \-t [seconds]
Timeout after second seconds.  If no input has been seen by this time,
query will echo the default response value to standard output and
standard error.
.TP
.B \-r [response]
Change the default response to response.  The default
response is "y" if not set with this option.  The \-r option is
only useful in conjunction with -t.
.SH DIAGNOSTICS
Exit status is 0 if everything is OK, 1 for usage error.
.SH AUTHOR
Christopher T. Johnson
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
