/*
 *			pro-engineer/Cakefile
 */
#include "../../Cakefile.defs"

#define PRODUCTS	Makefile proe-brl.c proe-brl
#define STATIC_PRODUCTS	 Makefile proe-brl.c proe-brl
#define SRCDIR	sgi_mips4
#undef BINDIR
#define BINDIR	BASEDIR/pro-engineer/sgi_mips4
#undef BINPERM
#define BINPERM 755

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo SRCDIR:  all done

#include "../../Cakefile.rules"
