/*
 *			pro-engineer/Cakefile
 */
#include "../../Cakefile.defs"

#define PRODUCTS	Makefile proe-brl.c proe-brl proe-brl.dll
#define STATIC_PRODUCTS	 Makefile proe-brl.c proe-brl proe-brl.dll
#define SRCDIR	../sgi_mips4
#undef BINDIR
#define BINDIR	BASEDIR/pro-engineer/sgi_mips4
#undef BINPERM
#define BINPERM 755

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	\B\A\S\E\D\I\R=\"BASEDIR\"; \
	export \B\A\S\E\D\I\R; \
	make proe-brl
	\B\A\S\E\D\I\R=\"BASEDIR\"; \
	export \B\A\S\E\D\I\R; \
	make proe-brl.dll

#include "../../Cakefile.rules"
