.TH RT 1 BRL-CAD
./"                           R T . 1
./" BRL-CAD
./"
./" Copyright (c) 1984-2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
rt \- raytrace an \fBmged\fP model, giving a shaded picture
.SH SYNOPSIS
.B rt
[ options ... ]
model.g
objects ...
.SH DESCRIPTION
.I Rt
operates on the indicated
.I objects
in the input
.I model.g
and produces a color shaded image as the output.
By default, the output is placed on the current framebuffer
as it is computed.  The environment variable FB_FILE specifies
the current framebuffer, see
.IR brlcad (1).
Alternatively, the output can be stored in a pixel file
.RI ( pix (5)
format)
by specifying
.B \-o
.B output.pix
in the option list.
The orientation of the rays to be fired may be specified by
the
.B \-a
and
.B \-e
options, in which case the model will be autosized, and the grid
will be centered on the centroid of the model, with ray spacing
chosen to span the entire set of
.I objects.
Alternatively,
with the
.B \-M
option, a transformation matrix may be provided on standard input
which maps model-space to view-space.
In this case, the grid ranges from -1.0 <= X,Y <= +1.0 in view space,
with the size of the grid (number of rays fired) specified with
.BR \-s .
The
.B \-M
option is most useful when
.B rt
is being invoked from a shell script created by an
.IR mged (1)
\fIsaveview\fR command.
.LP
The following options are recognized:
.TP
.B \-a#
selects auto-sizing, and gives the view azimuth in degrees.  Used with
.B \-e
and conflicts with
.B \-M
.TP
.B \-b ``# #''
is sometimes useful for debugging.  A single ray is fired at the pixel
coordinates specified.
This is best when accompanied by debugging options.  Note that the standard
.IR getopt (3)
routine only allows options to have one parameter, so the X and Y
pixel coordinates need to be combined into one string parameter by enclosing
them in double quotes.  This option must follow any viewing parameters.
.TP
.B \-c ``script_command''
is used to supply on the command line any command that can appear
in a
.B \-M
command script.
For example,
.B \-c ``set''
will print the values of all settable variables.
.TP
.B \-d#
turns on the reporting of pixel distances,
so that each pixel is represented by 3 bytes of color information
followed by 8 bytes for a double (in IEEE format)
giving the distance to the ray's first hit.
The default is 0,
which causes
.I rt (1)
to write only the color information.
See
.IR pix (5)
and
.IR pixd (5).
.TP
.B \-e#
selects auto-sizing, and gives the view elevation in degrees.  Used with
.B \-a
and conflicts with
.B \-M
.TP
.B -f#
sets the expected playback rate in frames-per-second.
The default is 30fps.
Several time-evolving shaders
such as
.I fire
and
.I grass
need to know the time at which each frame and pixel occurs to drive their
evolution.
.TP
.B \-g#
is used to set the grid cell width, in millimeters.
Ordinarily, the cell width is computed by dividing the view size by
the number of pixels of width, so this option need not be used.
To obtain exactly 1 inch ray spacing, specify
.B \-g25.4.
If the grid cell width is specified and
the grid cell height is \fInot\fR specified,
the grid cell height defaults to be the same as the width.
.TP
.B \-h density,r,g,b
enables an exponential shading of the void between the eye and the
first hit location.  This allows a cheap simulation of atmospheric haze
with lower performance impact that explicit modeling of the air volume.
The haze is computed using the form:
.sp
.br
f = e^(-dist * density)
.br
g = 1.0 - f
.br
color = color * f + hazeRGB * g
.sp
.br
The color values are optional.  If not specified they will have the passable
values 0.8 .9 .99.
.sp
.br
Example usage: -h '2.5e-8,.75,.95,.99'
.TP
.B \-i
enables \fIincremental mode\fR processing.
First a single ray is fired.
Then, the screen is subdivided into four parts by evenly subdividing
in the vertical and horizontal directions.
The previously fired ray was the lower left corner;
three more rays are fired.
This process recurses until full resolution has been reached.
Assumes square image.
Also assumes fast path between CPU and display hardware.
.TP
.B \-j
.B xmin,ymin,xmax,ymax
enables \fIjust this sub-rectangle\fR processing.
Specifies the screen coordinates of the lower left and upper right
corner of a rectangle within the rectangle (0,0) (width-1,height-1).
Ray-tracing will be limited to just those pixels within the sub-rectangle,
and only those pixels will be transmitted to the framebuffer.
The corner pixels (xmin,ymin) and (xmax,ymax) are included in
the sub-rectangle.
This option exists primarily for
.IR mged (1)
to allow sweeping out a rectangular portion of the view for ray-tracing.
.TP
.B \-l#
Select lighting model.  Default is 0.
Model 0 is a full lighting model with the ability to implement
Phong shading, transparent and reflective objects, shadow penumbras,
texture maps, etc.
In addition to ambient light, a small amount of light is
supplied from eye position.
All objects in the active model space with a material property
string of ``light'' represent additional light sources
(up to 16 are presently permitted),
and shadow computations will be initiated automaticly.
(This mechanism is subject to further change).
Model 1 is a diffuse-lighting model only, and is intended for
debugging.
Model 2 displays the surface normals as colors, and is useful
for examining curvature and surface orientation.
Model 3 is a three-light diffuse-lighting model, and is intended
for debugging.
Model 4 is a curvature debugging display, showing the inverse
radius of curvature.
Model 5 is a curvature debugging display, showing the principal
direction vector.
Model 6 is for debugging the UV parameterization used for surface
texturing.  It is exactly the same as applying the texture 'testmap'
to every region.  The U parameter is displayed in the red channel
and the V parameter is displayed in the blue channel.
Model 7 is for using photon mapping to simulate global illumination
and caustics in a given scene.  Options to photon mapping are passed
through the -l parameter in the following format: -l7,Num_Photons,Caustics_Percent,
Irradiance_Rays,Angular_Tolerance,Random_Seed,Importance_Mapping_Toggle,
Irradiance_Hypersampling_Toggle,Visual_Irradiance_Toggle,Scale_Lumens,Load_Save_File
Example: -l7,16384,0,10,60.0,0,0,0,0,1.0,scene.pm.
Note: If just -l7 is used then the default values above will be applied.  Light sources
must also be explicitly defined with lumens defined for each source, i.e default light
sources will not work.
.TP
.B \-n#
defines the height of the image as a number of scanlines.
.TP
.B \-o
.B output.pix
Specify the name of a file to store the
.IR pix (5)
format output.
The
.IR pix-fb (1)
utility can be used later to display ``.pix'' files.
.TP
.B \-p#
Sets the perspective, in degrees, ranging  0 <= # < 180.
.TP
.B \-r
requests that overlapping regions be reported. (conflicts with -R)
.TP
.B \-s#
specifies the
number of rays to fire in the X and Y directions on a square grid.
The default size is 512 pixels.
There is no maximum size limit.
.TP
.B \-v#
sets the verbosity bit vector flags for rt.
Use \-v\ 0 for no output or \-v\ fff for all available output.
See include/brlcad/rtprivate.h for various bit definitions.
.TP
.B \-w#
defines the width of each scanline in pixels.
.TP
.B \-x#
sets the
.IR librt (3)
debug flags to the given hexadecimal bit vector.
See librt/debug.h for the bit definitions.
.B \-!#
sets the
.IR libbu (3)
debug flags to the given hexadecimal bit vector.
See h/bu.h for the bit definitions.
.TP
.B \-A#
sets the ambient light intensity,
as a fraction of the total light in the scene
in the range of 0.0 to 1.0.
.TP
.B \-B
The ``benchmark'' flag.  When specified, all intentional random effects
such as ray dither, color dither, etc, are turned off, to allow
benchmark timing comparison and benchmark result comparison.
.TP
.B \-C#/#/#
sets the background color to the RGB value #/#/#, where each #
is in the range of 0 to 255.
All non-background colors will be dithered away from this value.
.TP
.B \-D#
The "desired frame" flag, specifies frame number to start with.
Specify the desired ending (kill-after) frame with
.B \-K#
.TP
.B \-E#
sets the distance from the eye point to the center of the model RPP.
Only useful with auto-sizing, conflicts with
.B \-M
.TP
.B \-F\ framebuffer
indicates that the output should be sent to the indicated framebuffer.
See
.IR libfb (3)
for more details on the specification of a framebuffer.
.TP
.B \-G#
sets the grid cell height, in millimeters.
.TP
.B \-H#
The "hypersample" flag, specifies number of extra rays to fire
for each pixel, to obtain more accurate results
without needing to store the extra pixels.
Causes
.B \-J1
to be set.
The final colors of all rays are averaged together.
Better results can be obtained by simply increasing the resolution,
and decimating the results with a filter such as
.IR pixhalve (1).
.TP
.B \-I
Turns on interactive mode.  If this flag is off, and your image is
"large" (>= 256x256) it will lower the priority of the rt process.
.TP
.B \-J#
The "jitter" flag, is a bit vector.
If one (-J1), randomizes the point from which each ray
is fired by +/- one half of the pixel size.  Useful if doing your own
post filtering for antialiasing, or to eliminate systematic
errors.  This has been useful in obtaining more accurate results
in a volume-calculating raytraces as well.
If two (-J2), shifts the origin of the output frame once for each frame.
The shift is along a circular path in the plane of the frame,
with a period of ten seconds, and a radius of +/- 1/4 pixel width.
If three (-J3), performs both operations.
.TP
.B \-K#
sets the final (kill-after) frame number.
Used with animation scripts in conjunction with
.B \-D#
.TP
.B \-M
Read animation matrix or animation script from standard input.
Conflicts with
.B \-a
and
.B \-e
.TP
.B \-N#
Sets the NMG_debug flags to the given hexadecimalbit vector.
See h/nmg.h for the bit definitions.
.TP
.B \-O
.B output.dpix
Specify the name of a file to store the double-precision floating-point
version of the image.
.IR dpix-pix (1)
can be used to later convert the file to
.IR pix (5)
format output.
(Deferred implementation).
.TP
.B \-P#
Specify the maximum number of processors (in a multi-processor system) to be
used for this execution.  The default is system dependent.
On ``dedicated'' multi-processors, such as workstations and super-minis,
the default is usually set for the maximum number of processors,
while on shared multi-processors, such as SuperComputers,
usually just one processor is used by default.
.TP
.B \-Q x,y
Query pixel ray with debugging.  The option is used to
specify a single pixel for which the debug flags should be turned on.
The computation of all other pixels will be performed without debugging.
This is similar to the \-b option, except that it does not limit rendering
to the single ray.  The entire image is computed.  This option is useful in
debugging problems which arise from specific computation sequences (such as
the order of random numbers previously drawn).
.TP
.B \-R
requests that overlapping regions not be reported. (confilcts with -r)
.TP
.B \-S
Turns on stereo viewing.
The left-eye image is drawn in red,
and the right-eye image is drawn in blue.
.TP
.B \-T#
or
.B \-T#,#
or
.B \-T#/#
Sets the calculation tolerances used by
.IR librt (3).
If only one number is given, it specifies the distance tolerance.
Any two entities closer than this distance are considered to be the same.
The default distance tolerance is 0.005mm.
If the second number is given, it specifies the value of the dot product
below which two lines are to be considered perpendicular.
This number should be near zero, but in any case should be less than 1.
The default perpendicular tolerance is 1e-6.
If both calculation tolerances are provided, they shall be separated
by either a slash ("/") or a comma (","), with no white space between them.
For example, the default tolerances would be specified as
.B \-T0.005/1e-6
on the command line.
.TP
.B \-U#
Sets the "use_air" value.
Default is 0, which ignores regions that have non-zero aircode values.
.TP
.B \-V#
Sets the view aspect.  This is the ratio of width over height and can
be specified as either a fraction or a colon-separated ratio.
For example, the NTSC aspect ratio can be specified by either
.B \-V1.33
or
.B \-V4:3
.TP
.B \-W
Sets the background image color to white.
.TP
.B \-X#
Turns on the
.IR rt (1)
program debugging flags.  See rt/rdebug.h for the meaning of these bits.
.TP
.B \-!#
Turns on the
.IR libbu (3)
library debugging flags.  See h/bu.h for the meaning of these bits.
In particular, specifying
.B \-!1
will cause
.I bu_bomb()
to dump core, rather than logging the error and exiting.
This is useful with
.IR dbx (1)
for debugging.
.PP
The
.B rt
program is a simple front-end to
.IR librt (3)
which can be invoked directly, or via the
.B rt
command in
.IR mged (1).
.SH "ANIMATION SCRIPTS"
.PP
For information on the animation script language accepted by
.B rt
please refer to the manual pages for
.IR tabinterp (1),
.IR tabsub (1),
and
.IR anim_script (1).
Also please consult the HTML documentation for a complete animation
tutorial.
.SH "NTSC ANIMATION TIPS"
.PP
When using
.B rt
to create an animation sequence destined for NTSC video,
it is useful to give all these options in conjunction:
.B \-V4:3
.B \-c
"set gamma=2.2"
.B \-w1440
.B \-n972
.B \-J1
and then post-proces the output using
.IR pixhalve (1)
for final display.
Performing the gamma correction inside
.B rt
instead of post-processing the
.IR pix (5)
file with
.IR bwmod (1)
avoids Mach-bands in dark regions of the image, and retains the
maximum amount of image detail.
.SH "SEE ALSO"
brlcad(1), mged(1), lgt(1), pix-fb(1), rtray(1), rtpp(1),
librt(3), ray(5V), pix(5).
.SH DIAGNOSTICS
Numerous error conditions are possible.
Descriptive messages are printed on standard error.
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH COPYRIGHT
This software is Copyright (C) 1984-2005 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH BUGS
Most deficiencies observed while using the
.B rt
program are usually with the
.IR librt (3)
package instead.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>, or via the "cadbug.sh" script.
