.TH RTAREA 1 BRL-CAD
./"                       R T A R E A . 1
./" BRL-CAD
./"
./" Copyright (c) 1987-2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
rtarea \- Calculate exposed and presented surface areas
.SH SYNOPSIS
.B rtarea
[ options ... ]
model.g
objects ...
.SH DESCRIPTION
.I Rtarea
calculates the exposed and presented surface areas of specified
geometry objects from a particular view.  The summary output includes
details for individual regions, assemblies (combinations that contain
regions), and summarized totals.  The exposed area is the occluded 2D
projection of the specified geometry.  That is to say that if another
object is in front, it will reduce the amount of exposed area.  The
presented area is the unoccluded 2D projection of the geometry, where
hidden objects will report their presented area regardless of any
objects that are in front.
.PP
It presently does not compute the entire surface area of objects
displayed though that would be a nice feature to have.
.PP
The model geometry is the list of
.I objects
in the input database
.IR model.g .
.TP
.B \-X\ #
Set rtarea debug flags to a (hexadecimal) number.
A flag value of 1 causes 3-D plot output to be written to stdout.
All solid RPPs are plotted as grey boxes, and the walk path is
in alternating blue and green segments.
A flag value of 2 adds red segments for all attempted steps,
as well as the final steps.
A flag value of 3 adds some debugging prints to stderr in addition
to the plots.  This is useful for immediate path review, eg,
.sp .5
        rtarea -X 1 ... | tiris
.TP
.B \-x\ #
Set librt debug flags to a (hexadecimal) number.
.TP
.B \-n\ # of steps
.TP
.B \-v\ viewsize
.LP
The
.B rtarea
program employs
.IR librt (3)
for the geometry interrogation.
.sp
.SH "SEE ALSO"
mged(1), rt(1), pix-fb(1), librt(3), pix(5).
.SH DIAGNOSTICS
Numerous error conditions are possible.
Descriptive messages are printed on standard error.
.SH AUTHOR
Christopher Sean Morrison
John R. Anderson
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH COPYRIGHT
This software is Copyright (C) 1987-2005 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <bugs@brlcad.org>.
