.TH RTCHECK 1 BRL-CAD
.\"                      R T C H E C K . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 1988-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.UC 4
.SH NAME
rtcheck \- Make UNIX-Plot of overlaps in an \fBmged\fP model, using raytracing
.SH SYNOPSIS
.B rtcheck
[ options ... ]
model.g
objects ...
> overlaps.pl
.SH DESCRIPTION
.I Rtcheck
operates on the indicated
.I objects
in the input
.I model.g
and produces a floating point 3-D BRL-style
.IR plot (5)
format file on standard output, in millimeters.
.LP
The orientation of the rays to be fired may be specified by
the
.B \-a
and
.B \-e
options, in which case the model will be autosized, and the grid
will be centered on the centroid of the model, with ray spacing
chosen to span the entire set of
.I objects.
Alternatively,
with the
.B \-M
option, a transformation matrix may be provided on standard input
which maps model-space to view-space.
In this case, the grid ranges from -1.0 <= X,Y <= +1.0 in view space,
with the size of the grid (number of rays fired) specified with the
.B \-s
option.
The
.B \-M
option is most useful when
.B rtcheck
is being automaticly invoked from within
.IR mged (1)
using the
\fIrtcheck\fR command in
.IR mged .
.LP
The following options are recognized.
.TP
.B \-g#
The grid cell width, in millimeters.  Ordinarily, the cell width is
computed by dividing the view size by the number of pixels of width.
This option provides an alternate direct means to set the grid cell
width.
.TP
.B \-s#
Number of rays to fire in X and Y directions (square grid).
Default is 512 (512x512).
.TP
.B \-r
Report unique overlaps. At the end of a view, a list of unique pairs
of overlapping regions is printed, along with a count of the number
of detected overlaps for each pair. Not all detected
overlap combinations are necessarily listed, as the overlap
partition may mask a second overlap that is a continuation of an
already detected overlap.
.TP
.B \-a#
Select azimuth in degrees.  Used with
.B \-e
and conflicts with
.B \-M
.TP
.B \-e#
Select elevation in degrees.  Used with
.B \-a
and conflicts with
.B \-M
.TP
.B \-G
Sets the grid cell height, in millimeters.
.TP
.B \-M
Read model2view matrix from standard input.
Conflicts with
.B \-a
and
.B \-e
.TP
.B \-P#
Specify the maximum number of processors (in a multi-processor system) to be
used for this execution.  The default is 1.
.LP
.B rtcheck
also accepts all other options that the
.IR rt (1)
program implements, such as for non-square views, perspective, etc.
.LP
The
.B rtcheck
program is a simple front-end to
.IR librt (3)
which is most useful when used from
.IR mged (1).
The output can be independently viewed using the UNIX-plot
viewers like
.IR pl-fb (1),
.IR pl-sgi (1),
.IR tplot (1),
etc
.SH "SEE ALSO"
mged(1), rt(1), rtray(1), rtpp(1), pl-fb(1), pl-sgi(1), tplot(1),
libplot3(3), librt(3), plot(5).
.SH DIAGNOSTICS
Numerous error conditions are possible.
Descriptive messages are printed on standard error (file descriptor 2).
.SH AUTHORS
Michael John Muuss
.br
Gary S. Moss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5066
.SH COPYRIGHT
This software is Copyright (c) 1988-2006 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH BUGS
Most deficiencies observed while using the
.B rtcheck
program are usually with the
.IR librt (3)
package instead.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
