.TH RTG3 1 BRL-CAD
./"                         R T G 3 . 1
./" BRL-CAD
./"
./" Copyright (c) 1989-2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.\" @(#) $Header$ (BRL)
.UC 4
.SH NAME
rtg3 \(em raytrace a model, writing a COVART (GIFT) 3-component format
shotline file
.SH SYNOPSIS
.B rtg3
[ options ... ]
model.g
objects ...
> model.cov
.SH DESCRIPTION
.I Rtg3
operates on the indicated
.I objects
in the input
.I model.g
and produces a GIFT/COVART
shotline file with three components per line, and both
entrance and exit obliquity angles
on standard output.
The region ID field of the output
file is set to the region id of each intersected region (partition).
If the ray partition is followed by air,
the aircode for the air region (and the line-of-sight thickness of the air)
is noted on the shotline header line.
.LP
The orientation of the rays to be fired may be specified by
the
.B \-a
and
.B \-e
options, in which case the model will be autosized, and the grid
will be centered on the centroid of the model, with ray spacing
chosen to span the entire set of
.I objects.
Alternatively,
with the
.B \-M
option, a transformation matrix may be provided on standard input
which maps model-space to view-space.
In this case, the grid ranges from -1.0 <= X,Y <= +1.0 in view space,
with the size of the grid (number of rays fired) specified with
.BR \-s .
This option is most useful when
.B rtg3
is being invoked from a shell script created by an
.IR mged (1)
\fIsaveview\fR command.  Note that it conflicts with
.B \-G#
and
.BR \-g# ;
negative hit distances have been seen when this
conflict was not avoided.
.LP
The following options are recognized.
.TP
.B \-s#
Number of rays to fire in X and Y directions (square grid).
Default is 512 (512x512).
.TP
.B \-a#
Select azimuth in degrees.  Used with
.B \-e
and conflicts with
.BR \-M .
.TP
.B \-e#
Select elevation in degrees.  Used with
.B \-a
and conflicts with
.BR \-M .
.TP
.B \-M
Read model2view matrix from standard input.
Conflicts with
.B \-a
and
.BR \-e .
.TP
.B \-g#
Select grid cell width.  Do not use with the
.B \-s#
option.
.TP
.B \-G#
Select grid cell height.  If \fInot\fR specified, cell height equals
cell width.  Do not use with the
.B \-s#
option.
.TP
.B \-U #
sets the Boolean variable
.I use_air
to the given value.
The default for
.IR rtg3 (1)
is on, i.e.
.BR \-U1 ,
but the effect of air regions may be disabled with
.BR \-U0 .
.TP
.B \-o
.B output.cov
specifies a named file for COVART-format output.
By default, the shotlines are written to stdout.
.TP
.B \-x#
Set librt debug flags to (hexadecimal) number.
.TP
.B \-c """set ray_data_file=ray_file_name""
specifies a file name for ray data output.  This output consists of one line of data
for each shotline in the shotline output file. Each line contains azimuth, elevation; x, y, and z of the ray start point;
x, y, and z of the ray direction; the corresponding line number in the shotline file; and the coordinates of the first hit
point along this ray.
.TP
.B \-c """set rt_cline_radius=#"""
Tells
.IR rtg3 (1)
to use the provided number (in millimeters) as the additional radius to add to CLINE
solids.
.TP
.B \-c """set save_overlaps=1"""
Tells
.IR rtg3 (1)
to act like the
.IR FASTGEN4
raytracer. Specifically, overlap handling is changed to agree with that of
.IR FASTGEN4.
.LP
The
.B rtg3
program is a simple front-end to
.IR librt (3)
which is most useful when used with
.IR mged (1)
and
.IR covart (1V).
.LP
A color vector display of ray-model intersections can be written to
.I rtg3.pl
by specifying the
.B \-X80000000
option.
The resulting plot file can be displayed with \fIpl-fb\fR or \fIpl-sgi\fR.
.SH "FORMAT"
The general layout of the output format is:
.LP
Overall header line (one per run)
.LP
View header line (one per view)
.LP
Ray (shotline) header line (one per ray)
.LP
Component line (one for each three components in this ray)
.LP
The
.B GIFT-3
shotline format has a different convention for the location of
the start point (and thus the location of parametric distance zero)
along the ray.  This difference is handled automatically in
.I rtg3
by translating the ray's zero distance to the plane containing the
model origin, by adding a distance correction factor.
For each ray, both
the cell center coordinates and
the coordinates actually fired from are output.
.LP
Obliquity angles (declensions off the normal) are computed internally
in
.I radians
but output in
.I degrees
to satisfy the
.B GIFT-3
format.  Note that internally,
.I librt
normals always point outward, whereas
.B GIFT
normals point inward.
.LP
.B GIFT
zero-fills the fields of the component card
if there are less than three components.  Neither
COVART II nor COVART III require this zero-filling, so it is omitted by
.I rtg3.
.SH EXAMPLE
This section will acquaint the user with the ordinary usage of \fIrtg3\fR.
A GIFT-3 output file is produced by giving the command:

.nf
.ce
\fIrtg3 -s32 model.g all.g > file\fR
.fi

This will a 32 by 32 ray file of the named model.  If a bounding-box
plot file is to be made as part of producing visual output, use

.nf
.ce
 \fIrtg3 -s32 -x80000000 model.g\fR
.fi

The bounding boxes for the objects in the database specified will
automatically be put into a file called \fIrtrpp.plot\fR.  Now,
to compute the color rays use

.nf
.ce
 \fIrtg3 -s32 -X80000000 model.g\fR
.fi

The results will be automatically stored in \fIrtg3.pl\fR.  The rays
will be colored green where they traverse solids in the model, and blue
where they traverse air within the model.
.LP
The two plot files can now be combined into a single picture and
displayed:

.nf
.ce
 \fIcat rtrpp.plot rtg3.pl | pl-sgi\fR
.fi

.SH "OVERLAP REPORTING"
\fIRTG3\fR shares overlap handling and reporting with the rest of the
\fIRT\fR family of applications.  A brief description of the overlap
reporting follows.
.LP
The first one hundred (100) overlaps are individually reported.  Thereafter,
only one out of each additional one hundred overlaps are reported, and
the user is notified that overlap printouts are being omitted.  This
alerts the user that more overlaps exist, but that they are too numerous to
list individually.  The general overlap message takes the following form:

.nf
.ce
 \fI"OVERLAP1: reg=region_name isol=solid_name"\fR
.ce
 \fI"OVERLAP2: reg=region_name isol=solid_name"\fR
.ce
 \fI"OVERLAP depth #mm at (x, y, z) sx# sy# lvl#"\fR
.fi

This means that OVERLAP1 and OVERLAP2 share a common space (depth) of
#millimeters starting at the point x, y, z in model coordinates, and
at the ray coordinates (screen coordinates) sx and sy.  Level refers to the
level of recursion, and will typically be zero unless glass or mirror
objects are present.
.SH "SEE ALSO"
covart(1V), gift(1V), mged(1),
rt(1), rtray(1),
librt(3), plot3(5), ray(5V).
.br
``\fICOVART II \(em A Simulation Program for Computation of Vulnerable Areas
and Repair Times \(em User Manual\fR'', Joint Technical Coordinating
Group for Munitions Effectiveness, Anti-Air Aerial Target
Vulnerability Working Group, 61-JTCG/ME-84-3.
.SH DIAGNOSTICS
Numerous error conditions are possible, usually due to errors in
the geometry database.
Descriptive messages are printed on standard error (file descriptor 2).
.SH AUTHORS
Dr. Susanne Muuss
.br
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5066
.SH COPYRIGHT
This software is Copyright (C) 1989-2005 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH BUGS
The COVART file format permits multiple views to be stored in one file.
.I Rtg3
presently can only compute a single view.
.LP
Most deficiencies observed while using the
.B rtg3
program are usually with the
.IR librt (3)
package instead.  If the \fB\-s#\fR option is used together with the
\fB\-G#\fR and \fB\-g#\fR options, negative hit distances will be
seen.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
