.\" @(#) $Header$ (BRL)
.TH RTHIDE 1 BRL-CAD
.UC 4
.SH NAME
rthide \(em ray-traces a model and writes a hidden line removed UNIX-Plot
file.
.SH SYNOPSIS
.B rthide
[ options ... ]
model.g
objects ...
> model.pl
.SH DESCRIPTION
.I Rthide
operates on the indicated
.I objects
in the input
.I model.g
and produces a hidden line removed UNIX-Plot
file with bas-relief features.  \fBrthide\fR produces plots by drawing a
boundary whenever a change in region_id is detected.  It also recognizes
and portrays abrupt changes in surface curvature and changes in surface
height.  This permits the recognition of pits, protrusions, and changes in
surface curvature.
.LP
The orientation of the rays to be fired may be specified by
the
.B \-a
and
.B \-e
options, in which case the model will be autosized, and the grid
will be centered on the centroid of the model, with ray spacing
chosen to span the entire set of
.I objects.
Alternatively,
with the
.B \-M
option, a transformation matrix may be provided on standard input
which maps model-space to view-space.
In this case, the grid ranges from -1.0 <= X,Y <= +1.0 in view space,
with the size of the grid (number of rays fired) specified with
.B \-s
This option is most useful when
.B rthide
is being invoked from a shell script created by an
.IR mged (1)
\fIsaveview\fR command.
.LP
The following options are recognized.
.TP
.B \-s#
Number of rays to fire in X and Y directions (square grid).
Default is 512 (512x512).
.TP
.B \-a#
Select azimuth in degrees.  Used with
.B \-e
and conflicts with
.B \-M
.TP
.B \-A#
Select angle for shading.  Default is 5.0 degrees. 89.0 will produce
a plot where only steep drops and rises are shaded.
.TP
.B \-e#
Select elevation in degrees.  Used with
.B \-a
and conflicts with
.B \-M
.TP
.B \-M
Read model2view matrix from standard input.
Conflicts with
.B \-a
and
.B \-e
.TP
.B \-g#
Select grid cell width.
.TP
.B \-G#
Select grid cell height.  If \fInot\fR specified, cell height equals
cell width.
.TP
.B \-U #
sets the Boolean variable
.I use_air
to the given value.
.TP
.B \-o
.B output.pl
specifies a named file for output.
By default, the plot is written to hide.pl.
.TP
.B \-x#
Set librt debug flags to (hexadecimal) number.
.LP
The
.B rthide
program is a simple front-end to
.IR librt (3)
which is most useful when used with
.IR mged (1).
.SH EXAMPLE
This section shows the ordinary usage of \fIrthide\fR.  For example,

.nf
	\fIrthide -a# -e# -s32 model.g all.g > file.pl\fR
.fi

results in a 32 by 32 UNIXplot file of the named model at the specified
azimuth and elevation.  There will be some cross-hatching
of the plot based on surface curvature.  In order to minimize
this cross-hatching, an angle can be specified:

.nf
	 \fIrthide -a# -e# -s32 -A89.0  model.g all.g > file.pl\fR
.fi

elliminates cross-hatching due to curvature.  However, 
cross-hatching resulting from sharp
changes in gradient cannot be elliminated.
.LP
The plotfile resulting from an \fIrthide\fR run can be viewed directly
via \fIpl-sgi\fR and may be rotated with \fBplrot\fR at the user's option:

.nf
	\fIpl-sgi hide.pl\fR  or \fIplrot -a# -e# -g hide.pl | pl-sgi\fR
.fi

or it can be overlayed onto a solid model in \fImged\fR:

.nf
	\fImged>\fR
	\fIoverlay hide.pl\fR
.fi

This technique can be used to position and plot \fIrthide\fR output.
.LP
The output of \fBrthide\fR can be overlaid on top of a \fBrt\fR
shaded image, for ``edge enhancement''.  Here is a complete example,
which assumes that FB_FILE points to a valid framebuffer:
.nf
	AZ=35
	EL=25
	# Directly to the framebuffer
	rt -s512 -a$AZ -e$EL moss.g all.g 2> rt.log
	rthide -A89.9 -s256 -a$AZ -e$EL -o rthide.pl moss.g all.g 2> rthide.log
	eval `rtregis rthide.log rt.log` < rthide.pl | pl-fb -o -s512
.fi
.SH "SEE ALSO"
cell-fb(1),
mged(1), pl-sgi(1), plrot(1), rt(1), rtray(1), rtregis(1), rtscale(1),
librt(3), libplot3(3), plot3(5), ray(5V).
.SH DIAGNOSTICS
Numerous error conditions are possible, usually due to errors in
the geometry database.
Descriptive messages are printed on standard error (file descriptor 2).
.SH AUTHORS
Susanne Muuss, J.D.
.br
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5066
.SH COPYRIGHT
This software is Copyright (C) 1990-2005 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH BUGS
.LP
Most deficiencies observed while using the
.B rthide
program are usually with the
.IR librt (3)
package instead.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
