.TH RTRANGE 1 BRL-CAD
.\"                      R T R A N G E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 1991-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.UC 4
.SH NAME
rtrange \(em raytraces a model and visualizes range data in a UNIX-Plot file.
.SH SYNOPSIS
.B rtrange
[ options ... ]
model.g
objects ...
> model.pl
.SH DESCRIPTION
.I Rtrange
operates on the indicated
.I objects
in the input
.I model.g
and produces a range data UNIX-Plot file of the geometry ray-traced.  The
algorithm is based on plotting hit distances for all the pixels ray-traced.
The output is in the versatile, machine independent, UNIX-Plot file format.
This file is a true vector plot which retains the original model units.
.LP
The orientation of the rays to be fired may be specified by
the
.B \-a
and
.B \-e
options, in which case the model will be autosized, and the grid
will be centered on the centroid of the model, with ray spacing
chosen to span the entire set of
.I objects.
Alternatively,
with the
.B \-M
option, a transformation matrix may be provided on standard input
which maps model-space to view-space.
In this case, the grid ranges from -1.0 <= X,Y <= +1.0 in view space,
with the size of the grid (number of rays fired) specified with
.B \-s.
This option is most useful when
.B rtrange
is being invoked from a shell script created by an
.IR mged (1)
\fIsaveview\fR command.
.LP
The following options are recognized.
.TP
.B \-s#
Number of rays to fire in X and Y directions (square grid).
Default is 512 (512x512).
.TP
.B \-a#
Select azimuth in degrees.  Used with
.B \-e
and conflicts with
.B \-M
.TP
.B \-e#
Select elevation in degrees.  Used with
.B \-a
and conflicts with
.B \-M
.TP
.B \-M
Read model2view matrix from standard input.
Conflicts with
.B \-a
and
.B \-e
.TP
.B \-U #
sets the Boolean variable
.I use_air
to the given value.
.TP
.B \-o
.B output.pl
specifies a named file for output.
By default, the plot is written to standard out.
.SH EXAMPLE
This section shows the ordinary usage of \fIrtrange\fR.  For example,

.nf
	\fIrtrange -s32 model.g all.g > file.pl\fR
.fi

results in a 32 by 32 range data UNIX-plot file of the named model.
.LP
The plotfile resulting from an \fIrtrange\fR can be viewed directly
via \fIpl-sgi\fR:

.nf
	\fIpl-sgi file.pl\fR
.fi

It can also be rotated by \fBplrot\fR and sent to a framebuffer:

.nf
	\fIplrot -a# -e# -g file.pl | pl-fb\fR
.fi

Likewise, it can be overlayed onto a solid model in \fImged\fR:

.nf
	\fImged>\fR
	\fIoverlay hide.pl\fR
.fi

.SH "SEE ALSO"
mged(1),
pl-sgi(1), plrot(1),  rt(1), rtray(1),
librt(3), libplot3(3), plot3(5), ray(5V).
.SH DIAGNOSTICS
Numerous error conditions are possible, usually due to errors in
the geometry database.
Descriptive messages are printed on standard error (file descriptor 2).
.SH AUTHORS
Susanne Muuss, J.D.
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5066
.SH COPYRIGHT
This software is Copyright (c) 1991-2007 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH BUGS
.LP
Most deficiencies observed while using the
.B rtrange
program are usually with the
.IR librt (3)
package instead.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
