.TH RTREGIS 1 BRL-CAD
.\"                      R T R E G I S . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 1991-2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.UC 4
.SH NAME
rtregis \(em register overlay of a UNIX-Plot onto a rendered image.
.SH SYNOPSIS
.B rtregis
plot.log pix.log
> regtistration.matrix
.SH DESCRIPTION
.I rtregis
makes it easy and fast to overlay a UNIX-Plot file produced with \fBrthide\fR
or \fBrtrange\fR onto its equivalent color shaded image produced with \fBrt\fR or \fBcell-fb\fR.
.LP
.I rtregis
produces a script containing a call to \fBplrot\fR with the \fB-m\fR and \fB-S\fR parameters to
supply it with a registration matrix and a space command.  The registration
matrix is produced by \fBrtregis\fR from the
.B RT
log files for a UNIX-Plot file and a rendered shaded image file.
Both the UNIX-Plot image and the rendered shaded image must have been
ray-traced from the same orientation.  The output from
.B rtregis
is a matrix and a space command that are to be used as input parameters
to
.B plrot.
They may not be used together with
.B \-a, \-e, \-s, \-g
options to
.B plrot.
Output is written to standard out unless it is redirected.
The output can often be included directly in a shell script using
grave accents.
.SH EXAMPLE
This section shows the ordinary usage of \fIrtregis\fR.  For example,

.nf
	\fIrtregis plot.log pix.log  > registration.matrix.file\fR
.fi

results in a file containing the registration matrix and alternate
space command for \fBplrot\fR.  It also contains a call to \fBplrot\fR and
can be edited to send the \fBplrot\fR output a file.

.nf
	 \fIsh registration.matrix.file > file.pl\fR
.fi

This results in a registered plot file.
.LP
Now the registered plot file can be overlaid onto the rendered shaded image:

.nf
	\fIpix-fb file.pix\fR
	\fIpl-fb -o file.pl\fR
.fi

This command pair results in the plot file being overlaid on top of
the rendered shaded image that was in the framebuffer.
The result can then be converted to Impress or PostScript and sent
to a printer:

.nf
	\fIfb-pix | pix-bw | bw-impress (or bw-ps) | qpr\fR
.fi

.SH "SEE ALSO"
bw-impress(1), bw-ps(1),
cell-fb(1),
mged(1),
pl-fb(1), plrot(1), pl-sgi(1), rt(1), rthide(1),
pix-bw(1), pix-fb(1),
librt(3), libplot3(3), plot3(5), ray(5V).
.SH DIAGNOSTICS
Descriptive messages are printed on standard error (file descriptor 2).
.SH AUTHORS
Susanne Muuss, J.D.
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5066
.SH COPYRIGHT
This software is Copyright (C) 1991-2005 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
