.TH RTSCALE 1 BRL-CAD
.\"                      R T S C A L E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 1991-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.UC 4
.SH NAME
rtscale \(em supplements \fBrthide\fR output by plotting a scale to indicate
drawing size in arbitrary units.
.SH SYNOPSIS
.B rtscale
width units intervals file.log [optional string] > scale.pl
.SH DESCRIPTION
.I Rtscale
supplements the use of \fBrthide\fR by generating a UNIX-Plot of a scale that
permits the accurate measuring of \fBrthide\fR plots.  \fBrthide\fR provides
a hidden-line-removed plot of the geometry, and \fBrtscale\fR produces
an identical plot file containing just a scale.   The two files can then
be concatenated making sure that the scale precedes the \fBrthide\fR file
to produce a finished plot with scale.
.LP
\fBRtscale\fR operates on the RT log file from the \fBrthide\fR run and
produces a UNIX-Plot file of a scale with desired units and number
of tick marks.  The scale's width is given in model units.  A descriptive
string may be added.  The scale and the strings are plotted
in the lower left corner of the image.
.LP
The inputs required are:
.B width,
which specifies the length of the scale in model space,
.B units,
which may be any units (metric or English),
.B intervals,
which allows the user to specifies the number of tickmarks on the scale.
.filename,
which names the  RT log file that is used to calculate the view2model matrix
for the raytraced. A view such as azimuth 45, elevation 45, is useful for
measuring diagonal dimensions of the geometry.
Optionally, a
.B descriptive string
may be given to identify the view or the model.
.SH EXAMPLE
This section shows the ordinary usage of \fIrtscale\fR.  For example:

.nf
	\fIrtscale 30 mm 10 rt.log > scale.pl\fR
.fi

This will result in a 30 mm scale with ten tickmarks being plotted in the
lower left corner of the scale.pl image.  Alternately, a descriptive
string may be given to identify the view or the model:

.nf
	\fIrtscale 30 mm 10 rt.log "UH-60 a90 e0" > scale.pl\fR
.fi

Note that a descriptive string longer than 28 characters will be cut
off by \fBpl-fb\fR.
.PP
The plot file is now concatenated
with the plot file of the image to scale needs to be put on.  The order in
which they are concatenated is important: the scale is always concatenated
over top of the model plot:

.nf
	\fIcat scale.pl model.pl >> model.w.scale.pl\fR
.fi

The resulting UNIX-Plot of the geometry with a scale added to it can be
viewed in several ways.  It can be overlaid in \fBmged\fR, or it can be
rotated to the desired azimuth and elevation with \fBplrot\fR and be
stored in a file or view with \fBpl-sgi\fR or \fBpl-fb\fR:

.nf
	\fIplrot -a# -e# -g model.w.scale.pl | pl-sgi\fR

				or

	\fIplrot -a# -e# -g model.w.scale.pl | pl-fb \fR
.fi
.SH "SEE ALSO"
mged(1),
plrot(1), pl-sgi(1), rt(1), rthide(1),
librt(3), libplot3(3), plot3(5), ray(5V).
.SH DIAGNOSTICS
Numerous error conditions are possible, usually due to errors in
the geometry database.
Descriptive messages are printed on standard error (file descriptor 2).
.SH AUTHOR
Susanne Muuss, J.D.
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5066
.SH COPYRIGHT
This software is Copyright (c) 1991-2007 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
