.TH RTWALK 1 BRL-CAD
.\"                       R T W A L K . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 1987-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
rtwalk \- generate viewpoint animation between two points
.SH SYNOPSIS
.B rtwalk
[ options ... ]
startX startY startZ
destX destY destZ
model.g
objects ...
.SH DESCRIPTION
.I Rtwalk
generates a viewpoint animation control script that takes the eye
between given start and end points, without walking through any
geometry.
The model geometry is the list of
.I objects
in the input database
.IR model.g .
The primary output is in the form of an old-format
RT viewpoint animation control script
(which is also suitable for input to the MGED ``rmat'' command)
in the file ``rtwalk.mat''.
.TP
.B \-X\ #
Set rtwalk debug flags to (hexadecimal) number.
A flag value of 1 causes 3-D plot output to be written to stdout.
All solid RPPs are plotted as grey boxes, and the walk path is
in alternating blue and green segments.
A flag value of 2 adds red segments for all attempted steps,
as well as the final steps.
A flag value of 3 adds some debugging prints to stderr in addition
to the plots.  This is useful for immediate path review, eg,
.sp .5
        rtwalk -X 1 ... | tiris
.TP
.B \-x\ #
Set librt debug flags to (hexadecimal) number.
.TP
.B \-n\ # of steps
.TP
.B \-v\ viewsize
.LP
The
.B rtwalk
program employs
.IR librt (3)
for the geometry interrogation.
This program is currently in fledgling form, and is likely to
evolve into an important tool for motion path generation and
validation, interference checking in part articulation,
and numerically controlled milling.
.LP
This program is especially interesting when used on complex scenes
like those made by proc-db/clutter.c, eg:
.sp .5
      rtwalk -X1 -- -3470 -3470 650 3470 3470 650 ../proc-db/c.g clut |
      plot-fb -i
.sp
.SH "SEE ALSO"
mged(1), rt(1), pix-fb(1), rtray(1), rtpp(1),
librt(3), ray(5V), pix(5).
.SH DIAGNOSTICS
Numerous error conditions are possible.
Descriptive messages are printed on standard error.
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH COPYRIGHT
This software is Copyright (c) 1987-2007 United States Government as
represented by the U.S. Army Research Laboratory. All rights reserved.
.SH BUGS
Most deficiencies observed while using the
.B rtwalk
program are usually with the
.IR librt (3)
package instead.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
