/*
 *			libfft/Cakefile
 */
#define PRODUCTS	libfft.ARCH_SUF
#define SRCDIR	libfft
#define FILES	rfft16 rfft32 rfft64 rfft128 rfft256 rfft512 \
		irfft16 irfft32 irfft64 irfft128 irfft256 irfft512 \
		fftfast splitdit ditsplit

#define EXTRA_CLEAN	fftc ifftc

#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	fft_version
#define LIBRARY_TITLE		"BRL-CAD FFT Library"

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc -lm
#endif

#include "../Cakefile.lib"


/* Don't use LIBES here, we don't want to tangle with the
 * shared libraries still being prepared at this point.
 * Go straight to the system libraries.  We don't need much.
 */

fftc: fftc.o splitditc.o
	CC LDFLAGS -o fftc fftc.o splitditc.o -lm

ifftc: ifftc.o ditsplitc.o
	CC LDFLAGS -o ifftc ifftc.o ditsplitc.o -lm

rfft%.o:	fftc
	./fftc % > rfft%.c
	CC CFLAGS -c rfft%.c
	rm -f rfft%.c

irfft%.o:	ifftc
	./ifftc % > irfft%.c
	CC CFLAGS -c irfft%.c
	rm -f irfft%.c

#include "../Cakefile.rules"

