/*
 *			libfft/Cakefile
 */
#define PRODUCTS	libfft.ARCH_SUF
#define SRCDIR	libfft
#define FILES	rfft16 rfft32 rfft64 rfft128 rfft256 \
		irfft16 irfft32 irfft64 irfft128 irfft256 \
		fftfast splitdit ditsplit

#define EXTRA_CLEAN	fftc ifftc

#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"
#include "../Cakefile.lib"

fftc: fftc.o splitditc.o
	CC LDFLAGS -o fftc fftc.o splitditc.o LIBES

ifftc: ifftc.o ditsplitc.o
	CC LDFLAGS -o ifftc ifftc.o ditsplitc.o LIBES

rfft%.o:	fftc
	./fftc % > rfft%.c
	CC CFLAGS -c rfft%.c
	rm -f rfft%.c

irfft%.o:	ifftc
	./ifftc % > irfft%.c
	CC CFLAGS -c irfft%.c
	rm -f irfft%.c

#include "../Cakefile.rules"

