# BRL-CAD
# Copyright (c) 2026 United States Government as represented by
# the U.S. Army Research Laboratory.
# SPDX-License-Identifier: BSD-3-Clause

include("${CMAKE_CURRENT_LIST_DIR}/test_helpers.cmake")

function(expect_failure step)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE status
    OUTPUT_FILE "${TEST_DIR}/${step}.log" ERROR_FILE "${TEST_DIR}/${step}.log"
    WORKING_DIRECTORY "${TEST_DIR}" TIMEOUT 120)
  if(NOT "${status}" STREQUAL "1")
    file(READ "${TEST_DIR}/${step}.log" output)
    message(FATAL_ERROR "${step} did not fail cleanly (${status}): ${output}")
  endif()
endfunction()

file(REMOVE "${TEST_DIR}/source.g")
file(WRITE "${TEST_DIR}/fixture.tcl"
  "in box.s rpp 0 10 0 20 0 30\n"
  "r box.r u box.s\n"
  "put left comb tree {l box.r {1 0 0 40 0 1 0 0 0 0 1 0 0 0 0 1}}\n"
  "put right comb tree {l box.r {0 -1 0 0 1 0 0 50 0 0 1 5 0 0 0 0.5}}\n"
  "put pair comb tree {u {l left} {l right}}\n"
  "put overlapping comb tree {u {l left} {l box.r}}\n"
  "brep box.s brep box.brep\n"
  "put placed-brep comb tree {l box.brep {1 0 0 40 0 1 0 0 0 0 1 0 0 0 0 1}}\n"
  "q\n")
run_checked(create "${MGED}" -c "${TEST_DIR}/source.g" "source fixture.tcl")
run_checked(export "${GIGES}" -o "${TEST_DIR}/source.igs" "${TEST_DIR}/source.g" box.r)

if(CASE STREQUAL "positional")
  run_checked(all-tops "${MGED}" -c "${TEST_DIR}/source.g" "comb all u pair u overlapping u placed-brep")
  foreach(mode selected all explicit)
    set(flags)
    set(objects)
    if(mode STREQUAL "selected")
      set(objects all)
    elseif(mode STREQUAL "explicit")
      set(flags -o "${TEST_DIR}/${mode}.IGES")
    endif()
    if(mode STREQUAL "explicit")
      run_checked(${mode}-export "${GIGES}" ${flags} "${TEST_DIR}/source.g")
    else()
      run_checked(${mode}-export "${GIGES}" "${TEST_DIR}/source.g" "${TEST_DIR}/${mode}.IGES" ${objects})
    endif()
    run_checked(${mode}-import "${IGESG}" --strict "${TEST_DIR}/${mode}.IGES" "${TEST_DIR}/${mode} output.g")
    run_checked(${mode}-rays "${RAY_CHECK}" "${TEST_DIR}/source.g" all
      "${TEST_DIR}/${mode} output.g" iges_geometry)
  endforeach()

  file(WRITE "${TEST_DIR}/ignored.igs" "do not replace positional export destination")
  file(WRITE "${TEST_DIR}/ignored.g" "do not replace positional import destination")
  foreach(extension g igs)
    file(SHA256 "${TEST_DIR}/ignored.${extension}" before_${extension})
  endforeach()
  run_checked(override-export "${GIGES}" -o "${TEST_DIR}/override.igs"
    "${TEST_DIR}/source.g" "${TEST_DIR}/ignored.igs" box.r)
  run_checked(override-import "${IGESG}" -o "${TEST_DIR}/override.g"
    "${TEST_DIR}/override.igs" "${TEST_DIR}/ignored.g")
  run_checked(override-rays "${RAY_CHECK}" "${TEST_DIR}/source.g" box.r "${TEST_DIR}/override.g" iges_geometry)
  foreach(extension g igs)
    file(SHA256 "${TEST_DIR}/ignored.${extension}" after)
    if(NOT before_${extension} STREQUAL after)
      message(FATAL_ERROR "Explicit -o did not protect ignored positional destination")
    endif()
  endforeach()

  foreach(extension igs iges)
    run_checked(name-${extension} "${MGED}" -c "${TEST_DIR}/source.g" "comb selection.${extension} u box.r")
    expect_failure(ambiguous-${extension} "${GIGES}" "${TEST_DIR}/source.g" "selection.${extension}")
    if(EXISTS "${TEST_DIR}/selection.${extension}")
      message(FATAL_ERROR "Ambiguous object argument was used as an output filename")
    endif()
    run_checked(object-${extension} "${GIGES}" -o "${TEST_DIR}/object-${extension}.igs"
      "${TEST_DIR}/source.g" "selection.${extension}")
    run_checked(object-${extension}-import "${IGESG}" "${TEST_DIR}/object-${extension}.igs"
      "${TEST_DIR}/object-${extension}.g")
    run_checked(object-${extension}-rays "${RAY_CHECK}" "${TEST_DIR}/source.g" box.r
      "${TEST_DIR}/object-${extension}.g" iges_geometry)
  endforeach()
  file(SHA256 "${TEST_DIR}/source.igs" before)
  expect_failure(positional-alias "${IGESG}" "${TEST_DIR}/source.igs" "${TEST_DIR}/source.igs")
  file(SHA256 "${TEST_DIR}/source.igs" after)
  if(NOT before STREQUAL after)
    message(FATAL_ERROR "Positional alias replaced the input")
  endif()
  expect_failure(extra-argument "${IGESG}" "${TEST_DIR}/source.igs" "${TEST_DIR}/extra.g" extra)
  expect_failure(missing-output "${IGESG}" "${TEST_DIR}/source.igs")
elseif(CASE STREQUAL "aliases")
  foreach(kind same hard symbolic)
    foreach(extension g igs)
      set(source "${TEST_DIR}/source.${extension}")
      file(SHA256 "${source}" original)
      if(kind STREQUAL "same")
        set(alias "${source}")
      else()
        set(alias "${TEST_DIR}/alias-${kind}.${extension}")
        file(REMOVE "${alias}")
        set(flags)
        if(kind STREQUAL "symbolic")
          set(flags SYMBOLIC)
        endif()
        file(CREATE_LINK "${source}" "${alias}" ${flags} RESULT link_status)
        if(NOT "${link_status}" STREQUAL "0")
          message(STATUS "Skipping unavailable ${kind} link: ${link_status}")
          continue()
        endif()
      endif()
      if(extension STREQUAL "g")
        expect_failure(export-${kind} "${GIGES}" -o "${alias}" "${source}" box.r)
      else()
        expect_failure(import-${kind} "${IGESG}" -o "${alias}" "${source}")
      endif()
      file(SHA256 "${source}" after)
      if(NOT original STREQUAL after)
        message(FATAL_ERROR "${kind} alias changed the input")
      endif()
    endforeach()
  endforeach()
  file(WRITE "${TEST_DIR}/protected.g" "retain existing output")
  file(SHA256 "${TEST_DIR}/protected.g" original)
  expect_failure(report-alias "${IGESG}" --report "${TEST_DIR}/protected.g"
    -o "${TEST_DIR}/protected.g" "${TEST_DIR}/source.igs")
  file(WRITE "${TEST_DIR}/invalid.igs" "not an IGES file")
  expect_failure(invalid-input "${IGESG}" -o "${TEST_DIR}/protected.g" "${TEST_DIR}/invalid.igs")
  file(SHA256 "${TEST_DIR}/protected.g" after)
  if(NOT original STREQUAL after)
    message(FATAL_ERROR "Failed import replaced the existing destination")
  endif()
elseif(CASE STREQUAL "write_failure")
  if(EXISTS "/dev/full")
    expect_failure(full-file "${GIGES}" -o /dev/full "${TEST_DIR}/source.g" box.r)
    execute_process(COMMAND "${GIGES}" "${TEST_DIR}/source.g" box.r
      RESULT_VARIABLE status OUTPUT_FILE /dev/full ERROR_FILE "${TEST_DIR}/stdout-full.log" TIMEOUT 120)
    if(NOT "${status}" STREQUAL "1")
      message(FATAL_ERROR "stdout write failure returned ${status}")
    endif()
  endif()
elseif(CASE STREQUAL "drawing_default")
  run_checked(datum "${IGESG}" --strict --report "${TEST_DIR}/datum.json"
    -o "${TEST_DIR}/datum.g" "${CMAKE_CURRENT_LIST_DIR}/datum.igs")
  file(READ "${TEST_DIR}/datum.json" report)
  string(JSON count GET "${report}" statistics datums_written)
  string(JSON projected GET "${report}" options project_drawings)
  if(NOT count EQUAL 1 OR projected)
    message(FATAL_ERROR "Default datum import lost its model-space representation")
  endif()
elseif(CASE STREQUAL "multi_file")
  file(MAKE_DIRECTORY "${TEST_DIR}/files")
  # Remove only known outputs from earlier executions of this test.
  foreach(index RANGE 0 3)
    if(index EQUAL 0)
      set(stem box_r)
    else()
      set(stem "box_r-${index}")
    endif()
    file(REMOVE "${TEST_DIR}/files/${stem}.igs")
  endforeach()
  run_checked(multi "${GIGES}" -m -o "${TEST_DIR}/files" "${TEST_DIR}/source.g" pair)
  set(index 0)
  foreach(reference left right)
    if(index EQUAL 0)
      set(stem box_r)
    else()
      set(stem box_r-1)
    endif()
    run_checked(import-${reference} "${IGESG}" --strict --repair none
      --report "${TEST_DIR}/${reference}.json" -o "${TEST_DIR}/${reference}.g"
      "${TEST_DIR}/files/${stem}.igs")
    check_complete_report("${TEST_DIR}/${reference}.json")
    run_checked(rays-${reference} "${RAY_CHECK}" "${TEST_DIR}/source.g" "${reference}"
      "${TEST_DIR}/${reference}.g" iges_geometry)
    file(SHA256 "${TEST_DIR}/files/${stem}.igs" before_${index})
    math(EXPR index "${index} + 1")
  endforeach()
  run_checked(multi-again "${GIGES}" -m -o "${TEST_DIR}/files" "${TEST_DIR}/source.g" pair)
  file(SHA256 "${TEST_DIR}/files/box_r.igs" after_0)
  file(SHA256 "${TEST_DIR}/files/box_r-1.igs" after_1)
  if(NOT before_0 STREQUAL after_0 OR NOT before_1 STREQUAL after_1 OR
      NOT EXISTS "${TEST_DIR}/files/box_r-2.igs" OR NOT EXISTS "${TEST_DIR}/files/box_r-3.igs")
    message(FATAL_ERROR "Multi-file export did not preserve existing files and distinct occurrences")
  endif()
elseif(CASE STREQUAL "representations")
  foreach(order parent-first child-first)
    if(order STREQUAL "parent-first")
      set(roots left box.r)
    else()
      set(roots box.r left)
    endif()
    run_checked(${order}-export "${GIGES}" -o "${TEST_DIR}/${order}.igs"
      "${TEST_DIR}/source.g" ${roots})
    run_checked(${order}-import "${IGESG}" --strict --repair none
      --report "${TEST_DIR}/${order}.json" -o "${TEST_DIR}/${order}.g" "${TEST_DIR}/${order}.igs")
    check_complete_report("${TEST_DIR}/${order}.json")
    run_checked(${order}-rays "${RAY_CHECK}" "${TEST_DIR}/source.g" overlapping
      "${TEST_DIR}/${order}.g" iges_geometry)
  endforeach()
  foreach(mode faceted trimmed flattened)
    if(mode STREQUAL "faceted")
      set(flags -f -P 2)
      set(object left)
    elseif(mode STREQUAL "trimmed")
      set(flags -t -P 2)
      set(object left)
    else()
      set(flags --flatten-brep)
      set(object placed-brep)
    endif()
    run_checked(${mode}-export "${GIGES}" ${flags} -o "${TEST_DIR}/${mode}.igs"
      "${TEST_DIR}/source.g" "${object}")
    run_checked(${mode}-import "${IGESG}" --strict --repair none --report "${TEST_DIR}/${mode}.json"
      -o "${TEST_DIR}/${mode}.g" "${TEST_DIR}/${mode}.igs")
    check_complete_report("${TEST_DIR}/${mode}.json")
    run_checked(${mode}-rays "${RAY_CHECK}" "${TEST_DIR}/source.g" left
      "${TEST_DIR}/${mode}.g" iges_geometry)
  endforeach()
else()
  message(FATAL_ERROR "Unknown I/O case: ${CASE}")
endif()
