/*
 *			fbed/Cakefile
 */
/* #define CONFIGDEFS	-DSTATIC= */	/* debugging only */

#define SRCDIR	fbed
#define PRODUCTS	fbed
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	fbed char sgi_dep empty execshell getfont getinput glob \
		fill_buf pos_pad prnt squash try

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

fbed:	OBJ
	CC LDFLAGS -o fbed OBJ LIB_PRE''LIBFB LIBFB_LIBES LIB_PRE''LIBTERMIO LIB_PRE''LIBCURSOR LIBTERMLIB LIBES

#include "../Cakefile.rules"
