.TH FBED 1 BRL/CAD
.SH NAME
fbed \- framebuffer editor
.SH SYNOPSIS
.B fbed
[
.B \-ph
]
.SH DESCRIPTION
.I Fbed\^
is a screen editor for framebuffer images.
.P
If the
.B \-p
option is supplied,
.I fbed\^
uses the
.SM
.B GTCO
bitpad to position the cursor on the screen.  This option does not prevent
the user from positioning the cursor with the keyboard commands also.  The
.B \-h
option is for editing
1024x1024 images;  the default is 512x512.
.SH HINTS
This program may require a little practice, be sure to save a copy of the
input files until you are confident.  There is an on-line menu available
by typing a `?'.  The first time using the program you should start out
by listing the menu and finding the command for saving (Run-Length Encoding)
your image and use it if you don't already have a copy.
.P
.I fbed
will work on
.SM
.B UNIX
files if you don't need to see what is happening.
.SH CAVIATS
 As far as data tablets go,
there is currently only support for the
.SM
.B GTCO
bitpad and it assumes that there is only one available.  The subroutines
dealing with this should be made into a library and generalized to allow
for different hardware and multiple devices on the system.
.SH WARNING
Be careful not to use the
.B \-p
option unless you are sitting next to a
.SM
.B GTCO
bitpad which is operational, or the program will hang.
.SH EXAMPLE
.RS
\fIfbed \|\-h\fR
.RE
.SH "SEE ALSO"
fb-rle(1), rle-fb(1), libfb(3)
.SH AUTHOR
Gary S. Moss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH BUG REPORTS
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.ARPA>.
