/*                        P L U G I N S . C
 * BRL-CAD
 *
 * Copyright (c) 2019-2020 United States Government as represented by
 * the U.S. Army Research Laboratory.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this file; see the file named COPYING for more
 * information.
 */

#include "common.h"

#include <stdio.h>
#include <bu.h>
#include <ged.h>

int
main(int ac, char *av[]) {
    struct ged *gbp;

    bu_setprogname(av[0]);

    if (ac != 2) {
	printf("Usage: %s file.g\n", av[0]);
	return 1;
    }
    if (!bu_file_exists(av[1], NULL)) {
	printf("ERROR: [%s] does not exist, expecting .g file\n", av[1]);
	return 2;
    }

    gbp = ged_open("db", av[1], 1);

    const char * const *ged_cmds = NULL;
    size_t ged_cmd_cnt = ged_cmd_list(&ged_cmds);

    for (size_t i = 0; i < ged_cmd_cnt; i++) {
	bu_log("%s\n", ged_cmds[i]);
    }

#if 0
    for (size_t i = 0; i < ged_cmd_cnt; i++) {
	bu_log("ged_execing %s\n", ged_cmds[i]);
	ged_exec(gbp, 1, (const char **)&ged_cmds[i]);
    }
#endif

    /* These are the commands from the MGED and libtclcad command tables, the
     * latter being limited to the ones with a non-null ged function pointer.*/
    const char *app_cmds[] = {
	"%",
	"35,25",
	"3ptarb",
	"45,45",
	"accept",
	"adc",
	"adjust",
	"ae",
	"ae2dir",
	"aet",
	"aip",
	"analyze",
	"annotate",
	"arb",
	"arced",
	"area",
	"arot",
	"attach",
	"attr",
	"autoview",
	"B",
	"bb",
	"bev",
	"bo",
	"bomb",
	"bot",
	"bot_condense",
	"bot_decimate",
	"bot_dump",
	"bot_face_fuse",
	"bot_face_sort",
	"bot_flip",
	"bot_fuse",
	"bot_merge",
	"bot_smooth",
	"bot_split",
	"bot_sync",
	"bottom",
	"bot_vertex_fuse",
	"brep",
	"c",
	"cat",
	"cc",
	"center",
	"check",
	"clear",
	"clone",
	"closedb",
	"cmd_win",
	"coil",
	"color",
	"comb",
	"comb_color",
	"combmem",
	"constraint",
	"copyeval",
	"copymat",
	"cp",
	"cpi",
	"d",
	"db",
	"dbconcat",
	"dbfind",
	"db_glob",
	"dbip",
	"dbot_dump",
	"dbversion",
	"debug",
	"debugbu",
	"debugdir",
	"debuglib",
	"debugnmg",
	"decompose",
	"delay",
	"dir2ae",
	"dm",
	"draw",
	"dsp",
	"dump",
	"dup",
	"e",
	"E",
	"eac",
	"echo",
	"edarb",
	"edcodes",
	"edcolor",
	"edcomb",
	"edgedir",
	"edit",
	"edmater",
	"env",
	"eqn",
	"erase",
	"ev",
	"exists",
	"exit",
	"expand",
	"extrude",
	"eye",
	"eye_pos",
	"eye_pt",
	"facedef",
	"facetize",
	"fb2pix",
	"fbclear",
	"find_arb_edge",
	"find_bot_edge",
	"find_bot_pnt",
	"find_pipe_pnt",
	"form",
	"fracture",
	"front",
	"g",
	"gdiff",
	"get",
	"get_autoview",
	"get_bot_edges",
	"get_comb",
	"get_dbip",
	"get_dm_list",
	"get_eyemodel",
	"get_more_default",
	"get_sed",
	"get_sed_menus",
	"get_solid_keypoint",
	"get_type",
	"glob",
	"gqa",
	"graph",
	"grid",
	"grid2model_lu",
	"grid2view_lu",
	"has_embedded_fb",
	"heal",
	"hide",
	"hist",
	"history",
	"how",
	"human",
	"i",
	"idents",
	"ill",
	"illum",
	"importFg4Section",
	"in",
	"inside",
	"isize",
	"item",
	"joint",
	"joint2",
	"journal",
	"keep",
	"keypoint",
	"kill",
	"killall",
	"killrefs",
	"killtree",
	"knob",
	"l",
	"labelface",
	"labelvert",
	"lc",
	"left",
	"lint",
	"listeval",
	"loadtk",
	"loadview",
	"lod",
	"log",
	"lookat",
	"ls",
	"lt",
	"M",
	"m2v_point",
	"make",
	"make_name",
	"make_pnts",
	"mat4x3pnt",
	"mat_ae",
	"match",
	"mater",
	"mat_mul",
	"matpick",
	"mat_scale_about_pnt",
	"metaball_delete_pnt",
	"metaball_move_pnt",
	"mged_update",
	"mged_wait",
	"mirface",
	"mirror",
	"mmenu_get",
	"mmenu_set",
	"model2grid_lu",
	"model2view",
	"model2view_lu",
	"mouse_add_metaball_pnt",
	"mouse_append_pipe_pnt",
	"mouse_move_metaball_pnt",
	"mouse_move_pipe_pnt",
	"mouse_prepend_pipe_pnt",
	"move_arb_edge",
	"move_arb_face",
	"mrot",
	"mv",
	"mvall",
	"nirt",
	"nmg",
	"nmg_collapse",
	"nmg_fix_normals",
	"nmg_simplify",
	"ocenter",
	"oed",
	"oed_apply",
	"oed_reset",
	"oill",
	"open",
	"opendb",
	"orient",
	"orientation",
	"orot",
	"o_rotate",
	"orotate",
	"o_scale",
	"oscale",
	"otranslate",
	"output_hook",
	"overlay",
	"ox",
	"oxscale",
	"oxy",
	"oy",
	"oyscale",
	"ozscale",
	"p",
	"pathlist",
	"paths",
	"permute",
	"perspective",
	"pipe_append_pnt",
	"pipe_delete_pnt",
	"pipe_move_pnt",
	"pipe_prepend_pnt",
	"pix2fb",
	"plot",
	"pmat",
	"pmodel2view",
	"png",
	"png2fb",
	"pngwf",
	"pnts",
	"postscript",
	"prcolor",
	"prefix",
	"press",
	"preview",
	"process",
	"protate",
	"ps",
	"pscale",
	"pset",
	"ptranslate",
	"pull",
	"push",
	"put",
	"put_comb",
	"putmat",
	"put_sed",
	"q",
	"qorot",
	"qray",
	"quat",
	"query_ray",
	"quit",
	"qvrot",
	"r",
	"rate",
	"rcodes",
	"rear",
	"rect",
	"red",
	"refresh",
	"regdebug",
	"regdef",
	"regions",
	"reject",
	"release",
	"reset",
	"restore",
	"rfarb",
	"right",
	"rm",
	"rmap",
	"rmat",
	"rmater",
	"rmats",
	"rot",
	"rot_about",
	"rotate_arb_face",
	"rotobj",
	"rot_point",
	"rrt",
	"rselect",
	"rset",
	"rt",
	"rtabort",
	"rtarea",
	"rtcheck",
	"rtedge",
	"rt_gettrees",
	"rtweight",
	"rtwizard",
	"save",
	"savekey",
	"saveview",
	"sca",
	"screengrab",
	"search",
	"sed",
	"sed_apply",
	"sedit",
	"sed_reset",
	"select",
	"set_more_default",
	"set_output_script",
	"set_transparency",
	"set_uplotOutputMode",
	"setview",
	"shaded_mode",
	"shader",
	"share",
	"shells",
	"showmats",
	"sill",
	"simulate",
	"size",
	"slew",
	"solid_report",
	"solids",
	"solids_on_ray",
	"srot",
	"sscale",
	"status",
	"stuff_str",
	"summary",
	"sv",
	"svb",
	"sxy",
	"sync",
	"t",
	"ted",
	"tie",
	"tire",
	"title",
	"tol",
	"top",
	"tops",
	"tra",
	"track",
	"tracker",
	"translate",
	"tree",
	"ULL",
	"unhide",
	"units",
	"v2m_point",
	"vars",
	"vdraw",
	"version",
	"view",
	"view2grid_lu",
	"view2model",
	"view2model_lu",
	"view2model_vec",
	"viewdir",
	"view_ring",
	"viewsize",
	"vnirt",
	"voxelize",
	"vquery_ray",
	"vrot",
	"wcodes",
	"whatid",
	"whichair",
	"whichid",
	"which_shader",
	"who",
	"winset",
	"wmater",
	"x",
	"xpush",
	"ypr",
	"Z",
	"zap",
	"zoom",
	"zoomin",
	"zoomout",
	NULL
    };
    int app_cmd_cnt = 0;
    const char *ccmd = app_cmds[app_cmd_cnt];
    while (ccmd) {
	bu_log("\nTest %d: ged_execing app command %s\n", app_cmd_cnt, ccmd);
	int ret = ged_exec(gbp, 1, (const char **)&ccmd);
	if (ret != GED_OK && ret != GED_HELP) {
	    bu_log("%s\n", bu_vls_cstr(gbp->ged_result_str));
	}
	bu_vls_trunc(gbp->ged_result_str, 0);
	app_cmd_cnt++;
	ccmd = app_cmds[app_cmd_cnt];
    }

    ged_close(gbp);
    BU_PUT(gbp, struct ged);
    return 0;
}

/*
 * Local Variables:
 * tab-width: 8
 * mode: C
 * indent-tabs-mode: t
 * c-file-style: "stroustrup"
 * End:
 * ex: shiftwidth=4 tabstop=8
 */

