/*
 *			bench/Cakefile
 */

#define SRCDIR	bench
#define	PRODUCTS	pixcmp
#define	SRCSUFF	.c
#define MANSECTION	9

#define FILES	pixcmp

#include "../Cakefile.defs"

#ifdef NFS
/* Pick up any shell scripts needed */
%.sh:					if exist ../SRCDIR/%.sh
	rm -f %.sh
	ln ../SRCDIR/%.sh %.sh
#endif

#include "../Cakefile.prog"

clobber&: xxclober
	@echo "About to wipe out all pictures and binary files in this directory"
	@echo "Send SIGINT (typ. ^C) within 3 seconds to abort"
	@sleep 3
	rm -f *.log.* *.pix.*	# old versions
	rm -f *.log *.pix	# last try

#define clobber	xxclober	/* rename "clobber" in Cakefile.rules */

clean&:
	@echo "Removing object files and pixcmp"
	rm -f *.o pixcmp

pixcmp:		OBJ
	CC LDFLAGS -o pixcmp OBJ

#include "../Cakefile.rules"
