'\" t
.\"     Title: PIXCMP
.\"    Author:
.\" Generator: DocBook XSL-NS Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 12/04/2012
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "PIXCMP" "1" "12/04/2012" "BRL\-CAD" "BRL\-CAD"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pixcmp \- compare two pix image files pixel by pixel
.SH "SYNOPSIS"
.HP \w'\fBpixcmp\fR\ 'u
\fBpixcmp\fR [\fIOPTIONS\fR] \fIFILE1\fR [\fIFILE2\fR\ [\fISKIP1\fR\ [\fISKIP2\fR]]]
.SH "DESCRIPTION"
.PP
\fBpixcmp\fR
is a program to compare two BRL\-CAD pix image files pixel by pixel\&. The following
\fIOPTIONS\fR
are available:
.PP
\fB\-l\fR
.RS 4
Output pixel numbers, counting from 1, and values for all pixels that differ\&.
.RE
.PP
\fB\-b\fR
.RS 4
Use bytes instead of pixels for both processing and output\&. With this option, the
\fB\-i\fR
SKIP values should be specified as bytes instead of pixels\&.
.RE
.PP
\fB\-i\fR \fISKIP\fR
.RS 4
Skip the first SKIP pixels of input (for FILE1 and FILE2)\&.
.RE
.PP
\fB\-i\fR \fISKIP1\fR:\fISKIP2\fR
.RS 4
Skip the first SKIP1 pixels of FILE1 and the first SKIP2 pixels of FILE2\&.
.RE
.PP
\fB\-s\fR
.RS 4
Silent output\&. Only return an exit status\&.
.RE
.PP
SKIP1 and SKIP2 are the number of pixels to skip in each file\&.
.PP
If FILE is `\fB\-\fR` or missing,
\fBpixcmp\fR
reads from the standard input\&.
.SH "RETURN VALUES"
.PP
The
\fBpixcmp\fR
utility returns
0
if there are no differences,
1
if there are only off\-by\-one differences,
2
if there are off\-by\-many errors,
126
if there are file processing problems, and
127
if there are argument processing or usage errors\&.
.SH "EXAMPLES"
.PP
\fBpixcmp \-l file1 file2\fR
.RS 4
The two files are compared pixel by pixel with each difference printed instead of just the summary\&.
.RE
.PP
\fBpixdiff file1\&.pix file2\&.pix | pixcmp \- file3\&.pix\fR
.RS 4
The
\fIpixdiff\fR
tool compares the pixels in file1\&.pix with those in file2\&.pix and then outputs a resulting `diff` image which is then processed by
\fBpixcmp\fR
as input and compared against file3\&.pix, reporting on the differences\&.
.RE
.SH "SEE ALSO"
.PP
\fBbrlcad\fR(1),
\fBpixdiff\fR(1),
\fBpix\fR(5),
\fBbw\fR(5)
.SH "AUTHOR"
.PP
Christopher Sean Morrison
Charles M\&. Kennedy
Michael John Muuss
.SH "COPYRIGHT"
.PP
This software is Copyright (c) 2007\-2012 by the United States Government as represented by U\&.S\&. Army Research Laboratory\&.
.SH "BUG REPORTS"
.PP
Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad\&.org>\&.
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
