/*
 *			comgeom-g/Cakefile
 */

#define SRCDIR	comgeom-g
#define PRODUCTS	comgeom-g
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	cvt solid read region

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

comgeom-g:	OBJ
	CC LDFLAGS -o comgeom-g OBJ LIBWDB LIBRT LIBBN LIBBU LIBBU_LIBES LIBES

#include "../Cakefile.rules"
