#!/bin/sh
#$Id: checkout,v 2.2.1.8 1997/11/05 22:02:26 sauderd DP3.1 $

co README
co Makefile
#co sclprefixes.h this has been moved to the arch dir
co sdai.h
co sdai.cc
co sdaiEnum.h
co sdaiEnum.cc
co sdaiSelect.h
co sdaiSelect.cc
co sdaiString.h
co sdaiString.cc
co sdaiBinary.h
co sdaiBinary.cc
co sdaiApplication_instance.h
co sdaiApplication_instance.cc
co Registry.h
# co Registry.cc
co Registry.inline.cc
co dictdefs.h
co ExpDict.inline.cc
co ExpDict.cc
co ExpDict.h
# co RegistryClasses.h
# co RegistryClasses.inline.cc
# co RegistryClasses.cc
co SingleLinkList.h
co SingleLinkList.cc
co SingleLinkList.inline.cc
co STEPattribute.h
co STEPattribute.cc
co STEPattribute.inline.cc
co STEPattributeList.h
co STEPattributeList.cc
co STEPcomplex.h
co STEPcomplex.cc
co STEPaggregate.h
co STEPaggregate.cc
co STEPundefined.h
co STEPundefined.cc
co baseType.h
co read_func.cc
co read_func.h
co scl_osschema.h
#co corbaIncludes.h
co complexSupport.h
co entnode.cc
co entlist.cc
co multlist.cc
co orlist.cc
co complexlist.cc
co collect.cc
co non-ors.cc
co match-ors.cc
co trynext.cc
co print.cc
