/*
 *			sig/Cakefile
 */

#define SRCDIR	sig

#define PRODUCTS	a-d d-a i-d d-i bw-d d-bw f-d d-f f-i i-f c-d i-a \
			u-a u-d u-f u-bw d-u \
			dwin dauto dmod dfft dconv imod umod \
			ddisp fhor \
			dstat dsel \
			dpeak syn damdf dauto2 ihist istat ustat

#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"


a-d: a-d.o LIBBU_DEP
	CC LDFLAGS -o a-d a-d.o LIBBU LIBBU_LIBES LIBES

d-a: d-a.o
	CC LDFLAGS -o d-a d-a.o LIBES

i-d: i-d.o
	CC LDFLAGS -o i-d i-d.o LIBES

d-i: d-i.o
	CC LDFLAGS -o d-i d-i.o LIBES

d-u: d-u.o
	CC LDFLAGS -o d-u d-u.o LIBES

bw-d: bw-d.o
	CC LDFLAGS -o bw-d bw-d.o LIBES

d-bw: d-bw.o
	CC LDFLAGS -o d-bw d-bw.o LIBES

d-f: d-f.o
	CC LDFLAGS -o d-f d-f.o LIBES

f-d: f-d.o
	CC LDFLAGS -o f-d f-d.o LIBES

f-i: f-i.o
	CC LDFLAGS -o f-i f-i.o LIBES

i-f: i-f.o
	CC LDFLAGS -o i-f i-f.o LIBES

c-d: c-d.o
	CC LDFLAGS -o c-d c-d.o LIBES

i-a: i-a.o
	CC LDFLAGS -o i-a i-a.o LIBES

u-a: u-a.o
	CC LDFLAGS -o u-a u-a.o LIBES

u-d: u-d.o
	CC LDFLAGS -o u-d u-d.o LIBES

u-f: u-f.o
	CC LDFLAGS -o u-f u-f.o LIBES

u-bw: u-bw.o
	CC LDFLAGS -o u-bw u-bw.o LIBES

/* Processors */

dwin: dwin.o coswin.o hamwin.o
	CC LDFLAGS -o dwin dwin.o coswin.o hamwin.o LIBES

dauto: dauto.o
	CC LDFLAGS -o dauto dauto.o LIBES

dmod: dmod.o
	CC LDFLAGS -o dmod dmod.o LIBES

dfft: dfft.o interp.o butter.o
	CC LDFLAGS -o dfft dfft.o interp.o butter.o LIBFFT LIBES

dconv: dconv.o
	CC LDFLAGS -o dconv dconv.o LIBFFT LIBES


ddisp: ddisp.o LIBFB_DEP LIBBU_DEP
	CC LDFLAGS -o ddisp ddisp.o LIBFB LIBFB_LIBES LIBBU LIBBU_LIBES LIBES

fhor: fhor.o LIBFB_DEP LIBBU_DEP
	CC LDFLAGS -o fhor fhor.o LIBFB LIBFB_LIBES LIBBU LIBBU_LIBES LIBES

imod: imod.o
	CC LDFLAGS -o imod imod.o  LIBES

umod: umod.o
	CC LDFLAGS -o umod umod.o LIBES



/* Misc */

dstat: dstat.o
	CC LDFLAGS -o dstat dstat.o  LIBES

dsel: dsel.o
	CC LDFLAGS -o dsel dsel.o LIBES

istat: istat.o
	CC LDFLAGS -o istat istat.o  LIBES

ustat: ustat.o
	CC LDFLAGS -o ustat ustat.o  LIBES



/* Experimental */

dpeak: dpeak.o
	CC LDFLAGS -o dpeak dpeak.o LIBES

syn: syn.o
	CC LDFLAGS -o syn syn.o  LIBES

damdf: damdf.o
	CC LDFLAGS -o damdf damdf.o LIBES

dauto2: dauto2.o
	CC LDFLAGS -o dauto2 dauto2.o LIBES

ihist: ihist.o
	CC LDFLAGS -o ihist ihist.o LIBES

#include "../Cakefile.rules"
