/*
 *			awf/Cakefile
 *
 *  The actual formatter is located in "../brlman", because it needs to
 *  be installed in BINDIR.
 *
 *  Note:  The file "brlman/awf" needs to be modified when the definition of
 *  ETCDIR is changed.
 */
#include "../Cakefile.defs"

#define PRODUCTS	common dev.dumb mac.man mac.ms \
			pass1 pass2.base pass2.man pass2.ms pass3 \
			AWF_COPYRIGHT
#define SRCDIR	awf
#undef BINDIR
#define BINDIR	ETCDIR
#undef BINPERM
#define BINPERM MANPERM
#define FILES	/**/
#define	SRCSUFF	/**/
#define MANSECTION	1

#define STATIC_PRODUCTS	PRODUCTS	/* Force PRODUCTS into dist */

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

#include "../Cakefile.rules"
