/* 
 * tkStubInit.c --
 *
 *	This file contains the initializers for the Itk stub vectors.
 *
 * Copyright (c) 1998-1999 by XXXX
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * RCS: $Id$
 */

#include "itkInt.h"

/*
 * Remove macros that will interfere with the definitions below.
 */

/*
 * WARNING: The contents of this file is automatically generated by the
 * tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the generic/itk.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

ItkIntStubs itkIntStubs = {
    TCL_STUB_MAGIC,
    ITKINT_STUBS_EPOCH,
    ITKINT_STUBS_REVISION,
    0,
    0, /* 0 */
    0, /* 1 */
    Itk_ConfigBodyCmd, /* 2 */
    Itk_UsualCmd, /* 3 */
    Itk_ClassOptionDefineCmd, /* 4 */
    Itk_ClassOptionIllegalCmd, /* 5 */
    Itk_ConfigClassOption, /* 6 */
    Itk_CreateClassOptTable, /* 7 */
    Itk_FindClassOptTable, /* 8 */
    0, /* 9 */
    Itk_CreateClassOption, /* 10 */
    Itk_FindClassOption, /* 11 */
    Itk_DelClassOption, /* 12 */
    0, /* 13 */
    Itk_OptListInit, /* 14 */
    Itk_OptListFree, /* 15 */
    Itk_OptListAdd, /* 16 */
    Itk_OptListRemove, /* 17 */
};

static ItkStubHooks itkStubHooks = {
    &itkIntStubs
};

ItkStubs itkStubs = {
    TCL_STUB_MAGIC,
    ITK_STUBS_EPOCH,
    ITK_STUBS_REVISION,
    &itkStubHooks,
    Itk_Init, /* 0 */
    Itk_SafeInit, /* 1 */
    0, /* 2 */
    0, /* 3 */
    0, /* 4 */
    0, /* 5 */
    0, /* 6 */
    0, /* 7 */
    0, /* 8 */
    0, /* 9 */
    0, /* 10 */
    0, /* 11 */
    0, /* 12 */
    Itk_ArchetypeInit, /* 13 */
};

/* !END!: Do not edit above this line. */

struct ItkStubAPI itkStubAPI = {
    &itkStubs,
    &itkIntStubs
};
