/*
 *			liboptical/Cakefile
 */
#define SRCDIR	liboptical
#define PRODUCTS	liboptical.ARCH_SUF
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc -lm -brtl -L../.libbu.sp3 -lbu -L../.libbn.sp3 -lbn -L../.libtcl8.4.sp3 -ltcl -L../.librt.sp3 -lrt
#endif

#define FILES	\
	init \
	refract \
	wray \
	shade \
	material \
	photonmap \
	sh_air \
	sh_brdf \
	sh_billboard \
	sh_camo \
	sh_cloud \
	sh_cook \
	sh_fire \
	sh_flat \
	sh_gauss \
	sh_grass \
	sh_light \
	sh_noise \
	sh_null \
	sh_plastic \
	sh_points \
	sh_prj \
	sh_rtrans \
	sh_scloud \
	sh_spm \
	sh_stack \
	sh_stxt \
	sh_tcl\
	sh_text \
	sh_toyota \
	sh_treetherm \
	sh_wood \
	turb

#define VERSION_VARIABLE	liboptical_version
#define LIBRARY_TITLE		"The BRL-CAD Optical Shader Library"

#include "../Cakefile.lib"
#include "../Cakefile.rules"
