#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset en Contents {}
::msgcat::mcset en Search {}
::msgcat::mcset en More {}
::msgcat::mcset en Text {}
::msgcat::mcset en Forward {}
::msgcat::mcset en Backward {}
::msgcat::mcset en {Consider case} {}
::msgcat::mcset en {From beginning} {}
::msgcat::mcset en Home {}
::msgcat::mcset en Previus {}
::msgcat::mcset en Next {}
::msgcat::mcset en {Search in page...} {}
::msgcat::mcset en {Search more} {}
::msgcat::mcset en Close {}
