#-*-mode: TCL; coding: utf-8;-*-
::msgcat::mcset es Contents Contenido
::msgcat::mcset es Search Búsqueda
::msgcat::mcset es More Más
::msgcat::mcset es Home Inicio
::msgcat::mcset es Previus Previo
::msgcat::mcset es Next Siguiente
::msgcat::mcset es {Search in page...} {Buscar en la página}
::msgcat::mcset es {Search more} {Buscar siguiente}
::msgcat::mcset es Close Cerrar
::msgcat::mcset es Ok Aceptar
::msgcat::mcset es Cancel Cancelar
::msgcat::mcset es Text Texto
::msgcat::mcset es Forward {Hacia alante}
::msgcat::mcset es Backward {Hacia atrás}
::msgcat::mcset es {Consider case} {Distinguir mayusculas}
::msgcat::mcset es {From beginning} {Desde el comienzo}
