CFLAGS = -g -Wall -ansi -pedantic
CXXFLAGS = $(CFLAGS)

perplex : perplex.o scanner.o parser.o mbo_getopt.o
	$(CXX) -o $@ $^ -lm

perplex.o scanner.c : perplex.h parser.h
perplex.o mbo_getopt.o : mbo_getopt.h

scanner.c : scanner.re
	re2c -c -o $@ $<

parser.c parser.h : parser.y
	lemon -q $<

.PHONY : clean

clean :
	-rm -f perplex *.o scanner.c parser.c parser.h
