/*
 *			db/Cakefile
 *
 *  This Cakefile is for a recipient machine.
 *  The function is to take the distributed .asc files, and
 *  create the local binary form in .g files.
 *
 *  The STATIC_PRODUCTS definition will cause special things to
 *  happen in the "inst-dist" rule, so that the ASCII files
 *  get into the distribution directory.
 *  What is still missing is some automation to generate the
 *  .asc files from updated binary .g files on the master machine,
 *  but of course, it is hard to know which directory to look in,
 *  so for now this will remain a manual process.
 */

#define PRODUCTS	bldg391.g crod.g demo.g \
	ktank.g moss.g prim.g \
	star.g truck.g world.g cube.g axis.g \
	woodsman.g m35.g lgt-test.g
#define STATIC_PRODUCTS		\
	../SRCDIR/bldg391.asc ../SRCDIR/crod.asc ../SRCDIR/demo.asc \
	../SRCDIR/ktank.asc ../SRCDIR/moss.asc ../SRCDIR/prim.asc \
	../SRCDIR/star.asc ../SRCDIR/truck.asc \
	../SRCDIR/world.asc ../SRCDIR/cube.asc ../SRCDIR/axis.asc \
	../SRCDIR/woodsman.asc ../SRCDIR/m35.asc \
	../SRCDIR/lgt-test.asc ../SRCDIR/lgt-test.ldb \
	../SRCDIR/lgt-test.mdb ../SRCDIR/lgt-test.key

#define SRCDIR	db
#define FILES	/**/
#define	SRCSUFF	.asc
#define MANSECTION	9

#include "../Cakefile.defs"

/* Prevent actual installation */
#define DONT_INSTALL	1
#undef BINDIR
#define BINDIR	/tmp
#define AFTERINSTALL	rm

/* Default rule */
everything&::	PRODUCTS

#if defined(NFS)
#	define	CONV	../.conv.MTYPE/asc2g
#else
#	define	CONV	../conv/asc2g
#endif

%.g:	../SRCDIR/%.asc				if exist ../SRCDIR/%.asc
	CONV < ../SRCDIR/%.asc > %.g

#include "../Cakefile.rules"
