/*
 *			canon/Cakefile
 */

#define SRCDIR	canon
#define PRODUCTS	canonize pix-ipu ipustat ipuscan png-ipu

#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	asize canonize canonlib canonserver ipuscan ipustat pix-ipu


#include "../Cakefile.defs"

#if defined(__CAKE__5d) || defined(__CAKE__6d) || defined(__CAKE__7d) || \
 defined(__CAKE__irix4) || defined(__CAKE__irix5) || defined( __CAKE__irix6) || \
 defined(__CAKE__m3i62) || defined(__CAKE__m4i62) || defined(__CAKE__m4i64) || \
 defined(__CAKE__m4i65)
#	define DSLIB	-lds
#else
#	define DSLIB
#endif

/* XXX
 * The following is necessary because SGI's <sys/dsreq.h> won't pass the
 * -ansiposix flag on their own compiler under Irix 4.0.1 or 5.  Sigh.
 */

#if defined(__CAKE__5d) || defined(__CAKE__irix4)
# undef CFLAGS
# define CFLAGS -O -DIRIX=4 -I../h
#endif

#if defined(__CAKE__6d) || defined(__CAKE__irix5)
# undef CFLAGS
# define CFLAGS -O -I../h -DIRIX=5 -DHAVE_REGEX_DECL=1
#endif


#include "../Cakefile.prog"
/* Explicit composition of each product */

canonize : canonize.o canonlib.o asize.o
	CC LDFLAGS -o canonize canonize.o canonlib.o asize.o DSLIB LIBES

pix-ipu : pix-ipu.o canonlib.o asize.o
	CC LDFLAGS -o pix-ipu pix-ipu.o canonlib.o asize.o DSLIB LIBES

png-ipu : png-ipu.o canonlib.o asize.o
	CC LDFLAGS -o png-ipu png-ipu.o canonlib.o asize.o LIBBU LIBBU_LIBES LIBPNG LIBZ DSLIB LIBES

/* XXX Probably should be called ipu-pix */
ipuscan : ipuscan.o canonlib.o asize.o
	CC LDFLAGS -o ipuscan ipuscan.o canonlib.o asize.o DSLIB LIBES

ipustat : ipustat.o canonlib.o
	CC LDFLAGS -o ipustat ipustat.o canonlib.o DSLIB LIBES

#include "../Cakefile.rules"
