/*
 *			libtermio/Cakefile
 */
#define PRODUCTS	libtermio.ARCH_SUF
#define SRCDIR	libtermio
#define FILES	termio
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#include "../Cakefile.lib"
#include "../Cakefile.rules"
