/*
 *			libtermio/Cakefile
 */
#define PRODUCTS	libtermio.ARCH_SUF
#define SRCDIR	libtermio
#define FILES	termio
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	libtermio_version
#define LIBRARY_TITLE		"BRL-CAD Terminal Mode Compatibility Library"

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc
#endif

#include "../Cakefile.lib"
#include "../Cakefile.rules"
