.TH VDECK 1 VMB
.\"                        V D E C K . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.\"
.\" File name macro to make listing files easier
.\"
.de FN
\fI\|\\$1\|\fP
..
.\"
.\" Begin actual content
.\"
.SH NAME
vdeck \- generate COM-GEOM decks from a GED file

.SH SYNOPSIS
.B vdeck
.RB file .vg

.SH DESCRIPTION
The
.I vdeck
tool converts a model into an ASCII text representation separating
regions (combinations with the region flag set) and primitives (also
known as solids) into separate files.  A list of objects to be
converted are selected interactively from the table of contents.
String matching operators (wild cards) like those used to specify file
or directory names in
.IR sh\^ (1)
are provided for this purpose, as well as to search for names in the
table of contents.
.P
One or more COM-GEOM decks can be output.  Each deck consists of three
files: the solid, region, and region-id tables.  These can be combined
with
.IR cat\^ (1).
.P
A menu of the commands and their usage is available by typing
.B ?
to the program.

.SH WARNING
The
.I vdeck
tool is intended for v5 BRL-CAD geometry databases only.  Files
produced by older (v4 and earlier) versions of BRL-CAD may be
incompatible with
.IR vdeck\^.

.SH EXAMPLE
In the following example,
.I <model>
is the name of the BRL-CAD model and
.I <groupname>
is a group or region.  
.I Vdeck
converts all of the primitives and regions within the specified group
into text and writes them out to files:
.PP
.nf
> vdeck <model>.g 
command ( ? for menu ) >> i <goupname> 
command ( ? for menu ) >> d 
=================================================== 
O U T P U T F I L E S 
solid table = "solids" 
region table = "regions" 
region identification table = "region_ids" 
command ( ? for menu ) >> q 
quitting... 
.fi

.SH FILES
.TP
.FN solids
default solid table output
.TP
.FN regions
default region table output
.TP
.FN region_ids
default region
.SM ID
table output
.TP
.FN *.st
unique solid table output
.TP
.FN *.rt
unique region table output
.TP
.FN *.id
unique region
.SM ID
table output
.TP
.FN /tmp/dis???
temporary file used during processing
.TP
.FN /tmp/reg???
temporary file used during processing
.SH "SEE ALSO"
cat(1), gedplot(1V), mged(1B).
.SH AUTHORS
Gary S. Moss, BRL/VLD-VMB
.br
Keith Applin, BRL/VLD-TAB
