.\" Copyright (c) 1988, University of Utah
.TH GRAYTORLE 1 "Jun 24, 1988" 1
.UC 4 
.SH NAME
graytorle \- Merges gray scale images into an RLE format file.
.SH SYNOPSIS
.B graytorle 
[
.B \-a
] [
.B \-h
.I hdrsize
] [
.B \-o
.I outfile
] 
.I xsize ysize
.I infiles
.SH DESCRIPTION
.I Graytorle
reads a list of 8-bit gray scale images in unencoded binary format and converts
them to an
.IR RLE (5)
image with the number of channels corresponding to the number of input files.
A command line option allows specifying one of the files as an alpha channel.
.SH OPTIONS
.TP
.B \-a
Designates the first file in the input list as being information for the
alpha channel of the image.
.TP
.BI \-h " hdrsize"
Often gray scale image files include some sort of header information.  This
option allows specification of a count of bytes to discard at the beginning
of each input file.
.TP
.I xsize
Specifies the horizontal resolution of the input files.
.TP
.I ysize
Specifies the vertical resolution of the input files.
.TP
.BI \-o " outfile"
This option is used to name the output file.  Otherwise, output is written
to
.I stdout.
.TP
.I infiles
List of input files.
.SH SEE ALSO
.IR rletogray (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Michael J. Banks, University of Utah.


