.\" Copyright (c) 1986, University of Utah
.TH RLESPLICE 1 "Nov 12, 1986" 1
.UC 4 
.SH NAME
rlesplice \- Splice two RLE files together horizontally or vertically.
.SH SYNOPSIS
.B rlesplice
.B \-{hv}
[
.B \-c
] [
.B \-o
.I outfile
] 
.I infile1 infile2
.SH DESCRIPTION
.IR rlesplice
splices two RLE images together either vertically or horizontally.  If one
image is smaller, then its background value or black is used to pad that image
to equal the larger dimension in the other image.  The 
.B \-c
flag is used to
specify whether the smaller image should be centered when put next to the
larger.  Presently the two images must have the same number of color channels,
the same presence of an alpha channel, and the same colormap size and length.
The colormap from the first image is used for the resultant image.
.SH SEE ALSO
.IR rlecomp (1),
.IR rlepatch (1),
.IR unslice (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Martin R. Friedmann
