.\" Copyright (c) 1988, University of Utah
.TH RLETOGRAY 1 "Jun 24, 1988" 1
.UC 4 
.SH NAME
rletogray \- Splits an RLE format file into gray scale images.
.SH SYNOPSIS
.B rletogray
[
.B \-o
.I prefix
] [
.I infile
]

.SH DESCRIPTION
.I Rletogray
reads a file in
.IR RLE (5)
format and splits the file into unencoded binary files, one for each channel
in the RLE file.  The output file names will be constructed from the
input file name or a specified prefix.
.PP
If an input 
.I infile
is specified, then the output file names will be in the form
"\fIrlefileroot\fP.{alpha, red, green, blue}",
where
.I rlefileroot
is 
.I infile
with any ".rle" suffix stripped off.  If the option
.BI \-o " prefix"
is specified, then the output file names will be of the form
"\fIprefix\fP.{alpha, red, green, blue}".
If neither option is given, then the output file names will be 
"out.{alpha, red, green, blue}".
Input will be read from
.I infile
if specified, from standard input, otherwise.  If more channels than
just red, green, blue, and alpha are
present in the input, numeric suffixes will be used for the others.
.SH OPTIONS
.TP
.BI \-o \ prefix
Specifies the output file name prefix to be used.
.TP
.I  infile
This option is used to name the input file.  If not present, input is taken
from
.I stdin.
.SH SEE ALSO
.IR rletoraw (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Michael J. Banks, University of Utah.
