/*
 *			I R P R E P
 */
#define CONFIGDEFS	RT_CONFIG -I''XINCDIR

#define SRCDIR	irprep
#define PRODUCTS	firpass secpass shapefact all_sf \
			display ir-X ir-sgi irdisp
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define FILES	firpass secpass shapefact all_sf subroutines


/* Explicit composition of each product */

firpass:	firpass.o subroutines.o
	CC LDFLAGS firpass.o subroutines.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o firpass

secpass:        secpass.o subroutines.o
        CC LDFLAGS secpass.o subroutines.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o secpass

shapefact:  shapefact.o
        CC LDFLAGS shapefact.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o shapefact

all_sf:  all_sf.o
        CC LDFLAGS all_sf.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o all_sf

display:  display.o
        CC LDFLAGS display.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o display

ir-X:	ir-X.o
	CC LDFLAGS ir-X.o -L''XLIBDIR -lX11 -o ir-X

ir-sgi:	ir-sgi.o
	CC LDFLAGS ir-sgi.o LIBFB_LIBES -o ir-sgi

irdisp:	irdisp.o
	CC LDFLAGS irdisp.o LIBFB_LIBES -o irdisp

lint:
	lint LFLAGS -I''INCDIR ../irprep/firpass.c ../irprep/subroutines.c > SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/secpass.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/shapefact.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/all_sf.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/display.c >>SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/ir-X.c >>SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/irdisp.c >>SRCDIR.lint

#include "../Cakefile.rules"
