/*
 *			I R P R E P
 */
#define CONFIGDEFS	RT_CONFIG

#define SRCDIR	irprep
#define PRODUCTS	firpass secpass shapefact \
			display see pictx
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define FILES	firpass secpass shapefact subroutines

/* Explicit composition of each product */

firpass:	firpass.o subroutines.o LIBRT
	CC LDFLAGS firpass.o subroutines.o LIB_PRE''LIBRT RT_LIBES LIBMALLOC LIBES -o firpass

secpass:        secpass.o subroutines.o LIBRT
        CC LDFLAGS secpass.o subroutines.o LIB_PRE''LIBRT RT_LIBES LIBMALLOC LIBES -o secpass

shapefact:  shapefact.o LIBRT
        CC LDFLAGS shapefact.o LIB_PRE''LIBRT RT_LIBES LIBMALLOC LIBES -o shapefact

display:  display.o LIBRT
        CC LDFLAGS display.o LIB_PRE''LIBRT RT_LIBES LIBMALLOC LIBES -o display

see:	see.o
	CC LDFLAGS -I/usr/X11/include see.o -L/usr/X11/lib -lX11 -o see

pictx:	pictx.o
	CC LDFLAGS -I/usr/X11/include pictx.o -L/usr/X11/lib -lX11 -o pictx

lint:
	lint LFLAGS -I''INCDIR ../irprep/firpass.c ../irprep/subroutines.c > SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/secpass.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/shapefact.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/display.c >>SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/see.c >>SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/pictx.c >>SRCDIR.lint

#include "../Cakefile.rules"
