/*
 *			I R P R E P
 */
#define CONFIGDEFS	RT_CONFIG -I''XINCDIR

#define SRCDIR	irprep
#define PRODUCTS	firpass secpass shapefact all_sf \
			display see see2 pictx pictsgi
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

#define FILES	firpass secpass shapefact all_sf subroutines


/* Explicit composition of each product */

firpass:	firpass.o subroutines.o
	CC LDFLAGS firpass.o subroutines.o LIBRT RT_LIBES LIBES -o firpass

secpass:        secpass.o subroutines.o
        CC LDFLAGS secpass.o subroutines.o LIBRT RT_LIBES LIBES -o secpass

shapefact:  shapefact.o
        CC LDFLAGS shapefact.o LIBRT RT_LIBES LIBES -o shapefact

all_sf:  all_sf.o
        CC LDFLAGS all_sf.o LIBRT RT_LIBES LIBES -o all_sf

display:  display.o
        CC LDFLAGS display.o LIBRT RT_LIBES LIBES -o display

see:	see.o
	CC LDFLAGS see.o -L''XLIBDIR -lX11 -o see

see2:	see2.o
	CC LDFLAGS see2.o LIBFB_LIBES -o see2

pictsgi:	pictsgi.o
	CC LDFLAGS pictsgi.o LIBFB_LIBES -o pictsgi

pictx:	pictx.o
	CC LDFLAGS pictx.o -L''XLIBDIR -lX11 -o pictx

lint:
	lint LFLAGS -I''INCDIR ../irprep/firpass.c ../irprep/subroutines.c > SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/secpass.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/shapefact.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/all_sf.c ../irprep/subroutines.c >> SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/display.c >>SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/see.c >>SRCDIR.lint
	lint LFLAGS -I''INCDIR ../irprep/pictx.c >>SRCDIR.lint

#include "../Cakefile.rules"
