.TH ANIM_TURN 1 BRL-CAD
.\"                    A N I M _ T U R N . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 1993-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
anim_turn - make animation table for vehicle with front-wheel steering.
.SH SYNOPSIS
.B anim_turn -l length
.B [-a angle]
.B [-r radius]
.B [-f factor]
.B [-p integer]
.B < in.table
.B > out.table
.SH DESCRIPTION
The motion of a front wheel steered vehicle is not simple - the
instaneous velocity of the front wheels is in the direction they are
pointed, while the instantaneous velocity of the back wheels is the
direction the vehicle is pointed. The purpose of
.I anim_turn
is to
produce a complete animation table for such a vehicle, given a table
specifying the desired position of the front axle at each relevant
time step. The input table should contain four columns, specifying the
time and 3D position of the center of the front axle. Actually, the path
is assumed to be confined to an x-y plane, but the three columns are
included for consistency with other animation routines.
.PP
The output is normally a seven-column table which is a copy of
the input table with three extra columns specifying the yaw,
pitch, and roll of the truck at each time. The pitch and roll
are always zero, since the motion is assumed be in an x-y plane.
.PP
The
.B \-l#
option is not optional, and is used to specify the length
of the wheelbase (from the front axle to the rear axle).
.PP
.SH OPTIONS
.TP
.B \-a#
.I Track
assumes that the truck should initially be oriented
along the line defined by the first two positions in the input table.
Otherwise, the desired initial yaw of the truck can be specified with the
.B \-a#
option.
.TP
.B \-r#
Specify the radii of the front wheels. If this option is selected,
.I track
will create an animation script to animate the front wheels. The output
table would contain four columns: time, swivel-angle, roll, and a zero
channel. These represent the orientation of the front wheels, in terms
of yaw, pitch, and roll, and the table can be piped directly to
.IR anim_script .
.TP
.B \-f#
Specify a factor to be used to animate a steering wheel. If this option
is selected, the output table will contain four columns: time, swivel,
and two zero columns. This table can be used directly by
.I anim_script
to make an animation script for a steering wheel. The argument to the
option should be the factor by which to exagerate the swiveling of
the wheels. For
example, on a typical truck, you may need to turn the steering wheel 360
degrees in order for the wheels to swivel 20 degrees. To model this
effect, a factor of 18 would be used.
.TP
.B \-p#
Specify the ratio of input rows to output rows,
which must be an integer. The default, of course, is one. The accuracy
of the output depends on having a large number of input lines, which is
not usually a problem in animations, which require a large number of
frames per second. However, if a test animation with a small number of
frames per second is being created, the user should give an input table
with a high number of input rows and reduce the output with the
.B \-p#
option. For example, if
.B in.table
contains 30 rows for each second of the
animation, then the command
.sp
.B
anim_turn -l 3000 -p10 < in.table > out.table
.sp
would produce an animation table containing 3 rows for each second of
the animation.
.SH BUGS
The algorithm used only works for motion in an x-y plane.
.SH AUTHOR
Carl J. Nuzman
.SH COPYRIGHT
This software is Copyright (c) 1993-2006 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
