.TH CHAN_PERMUTE.C 1 BRL-CAD
.\"                 C H A N _ P E R M U T E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 1993-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
chan_permute - operate on columns of files.
.SH SYNOPSIS
.B chan_permute
.B -i infile1 id id ...
.B [-i infile2 id ...]
.B -o outfile1 id id ...
.B [-o outfile2 id ...]
.SH DESCRIPTION
This program mixes, matches, and merges ASCII files organized in
channels or columns. Each word, separated by whitespaces, should be less
than 40 characters long. The channels in each input file are specified
and then mapped to the desired channels in the output file(s). These are
the sort of things that can be done using
.I cut
and
.I paste,
but when
working on animation tables it's often nice to be able to do it in one
step.
.PP
.BR Infile s
are files to be read from,
.BR outfile s
are files to be written
to, and each
.B id
is a small positive integer identifying a channel. All of the
input
.BR id 's
should be distinct integers, or the results are not guaranteed.
.PP
.I Chan_permute
interprets
.B -i stdin
as standard input and
.B -o stdout
as
standard output.
.SH EXAMPLES
The command
.sp
chan_permute -i foo 0 1 2 -o stdout 2 1 0
.sp
reverses the order of foo's three columns and sends them to standard output.
.sp
.sp
The command
.sp
chan_permute -i file1 0 1 -i file2 2 3 -o file3 2 0 1 -o file4 3 0 1
.sp
creates file3 and file4, each containing one of the columns of file2
followed by both columns of file1.
.SH BUGS
A given file may be referenced
more than once for input, but may not be referenced for input and output
together or output and output together. In the latter case, the second
output reference overrides the other. 	The
.BR id 's
must be integers
somewhere between 0 and the number of arguments, inclusive.
.SH AUTHOR
Carl J. Nuzman
.SH COPYRIGHT
	This software is Copyright (c) 1993-2007 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
