.TH CHAN_MULT 1 BRL-CAD
./"                    C H A N _ M U L T . 1
./" BRL-CAD
./"
./" Copyright (c) 1993-2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
chan_mult - multiply columns of data by a given factor
.PP
chan_add - add a given value to columns of data
.SH SYNOPSIS
chan_mult factor num_columns column [column column ...] < infile > outfile
.PP
chan_add value num_columns column [column column ...] < infile > outfile
.SH DESCRIPTION
.I Mult_chan
will multiply all numbers in the specified columns by the given
factor. The infile is
an ASCII file, with columns separeted by white space. The columns are
numbered from 0 to (n-1).
.I Add_chan
behaves analogously, but with
addition rather than multiplication.
.SH EXAMPLES
These routines are useful for converting between units in animation
tables.
.PP
To multiply all but the first column of a four column file by 2.54:
.PP
.B
chan_mult 2.54 4 1 2 3
.PP
To add ten to the first six columns of an eight-column file:
.PP
.B
chan_add 10.0 8 0 1 2 3 4 5
.PP
To convert the second of three columns from Fahrenheit to Celcius:
.PP
.B
chan_add -32 3 1
.br
.B
chan_mult 0.56 3 1
.SH BUGS
The files must contain numbers and whitespaces only.
.SH AUTHOR
Carl J. Nuzman
.SH COPYRIGHT
This software is Copyright (C) 1993-2005 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
