= PIX(5)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
pix - Color RGB image file format and utilities

[[format]]
== FORMAT

A _pix_ file contains sequences of pixels. Each pixel is stored as three *unsigned char* s, first red, then green, then blue. The intensity of each color ranges from 0 ("off") to 255 ("on"). The first pixel in a _pix_ file is the lower left corner of the image. The pixels proceed from left-to-right across each scanline, with scanlines being written from the bottom to the top of the image.

By convention, _pix_ images are usually square, and thus their dimensions can be determined by the file size. If this is not the case, often only the file width need be known by a program reading the file. History has left us with two "standard" sizes, 512x512 and the "higher" 1024x1024. A common practice for other file sizes is to include the file width in the filename.

At some time in the future _pix_ files will probably get self-typing headers so that parameters such as their size can be automatically determined by programs.


[[utilities]]
== UTILITIES

*pix-fb* display a .pix format image on a framebuffer.

*fb-pix* produce a .pix file from a framebuffer image.

*pix-bw* convert a .pix file to a black and white .bw file.

*bw-pix* convert a black and white .bw file to a .pix file.

*ap-pix* convert an Applicon Color Plotter file to a .pix file.

*pixtile* combine several small .pix files into one large one.

*pixstat* gives statistics concerning a .pix file.

*pixhist* displays a color histogram on a framebuffer.

*pixhist3d* display three views of an RGB color space histogram on a framebuffer.

*pixhist3d-plot3* unix plot of RGB color space utilization.

*pixdiff* shows which pixels/colors differ between two .pix files.

*pixrect* extracts an arbitrary rectangle from a .pix file.

*pixrot* rotate, reverse, or invert a .pix file.

*pixscale* scale a .pix file up or down.

*pixfilter* a collection of 3x3 kernel filters for .pix files.

*bw3-pix* merges three .bw files into one .pix file.

*pix-bw3* separates .pix file RGB colors into three .bw files.


[[files]]
== FILES

file.pix


[[see_also]]
== SEE ALSO

*brlcad*(1), *bw*(5), and above named programs.


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 1989-2025 by the United States Government as represented by U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
