/*
 *			tclscripts/nirt/Cakefile
 */
#include "../../Cakefile.defs"

#define PRODUCTS	*.tcl *.tk *.sh tclIndex
#define STATIC_PRODUCTS	*.tcl *.tk *.sh tclIndex
#define SRCDIR	nirt
#undef BINDIR
#define BINDIR	TCLSCRIPTSDIR/nirt

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

ami&:
	../ami.tcl ../../tclscripts/nirt

#include "../../Cakefile.rules"
