.TH MK_HANDLE 1 BRL-CAD
.\"                    M K _ H A N D L E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
mk_handle \- creates an mged file containing handles
.SH SYNOPSIS
.B mk_handle
[ options... ]
.SH DESCRIPTION
Mk_handle is a program to create an mged data base of handles.
Up to twenty-six handles of the same dimensions may
be created.  Mk_handle uses libwdb to create an mged data base.
The handles are composed of three cylinders, two tori, and two
arb8s.  This
program may be run interactively or the user may specify options on
a command line.  If the user chooses to run the program interactively
he answers the questions as the program prompts him.  Below are the
options that can be used on the command line.
.SS Options
.TP "\w'-G ``n cflag gflag vsize\'\'\     |'u"
.BI \-fname.g\^
Mged file name.
.TP
.BI \-n#\^
The number of handles to be created.  This number must be less than or
equal to 26.
.TP
.BI \-l#\^
Length of handle in millimeters.
.TP
.BI \-h#\^
Height of handle in millimeters.
.TP
.BI \-r1#\^
Radius, r1, of the tori in millimeters.
.TP
.BI \-r2#\^
Radius, r2, of the tori and radius of the cylinders in millimeters
.TP
.SH EXAMPLE
The following is an example from an interactive session.
.sp
.nf
$ mk_handle

This program constructs a handle with the base centered
at (0,0,0) and the height extending in the positive z-
direction.  The handle will be composed of 3 cylinders,
2 tori, and 2 arb8s.

Enter the name of the mged file to be created (25 char max).
	handle.g
Enter the number of handles to create (26 max).
	3
Enter the length and height of handle in mm.
	200 100
Enter the radius of the tori in mm.
	20
Enter the radius of the cylinders in mm.
	10

mged file name:  handle.g
length:  200.000000 mm
height:  100.000000 mm
radius of tori:  20.000000 mm
radius of cylinders:  10.000000 mm
number of handles:  3

.fi
The following is the same example where all dimensions are on the
command line.
.nf

	mk_handle -fhandle.g -n3 -l200 -h100 -r120 -r210

.fi
In both these examples three handles are created with
a length of 200mm, height of 100mm, a radius of 20mm for the rounding,
and a radius of 10mm for the cylinders.  The mged file created in
each case is handle.g.

.SH  SEE ALSO
mk_bolt(1), mk_window(1), mk_winfrm(1), mk_gastank(1)

.SH AUTHOR
Susan A. Coates
