.TH MK_WIRE 1 BRL-CAD
./"                      M K _ W I R E . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
mk_wire \- creates an mged file containing wiring or fuel lines
.SH SYNOPSIS
.B mk_handle
[ options... ]
.SH DESCRIPTION
Mk_wire is a program to create an mged data base of solid
wires or fuel lines.
The user enters the coordinates of the starting and ending points of the
different segments of wires along with the radius at each of these points.
Currently the program is limited to 10 segments.  This number may be
changed by changing the variable MAXSEG.  MAXSEG may be no greater than
100 with out changing other parts of the program.
The wires are composed of cones and spheres.
This program is designed to be run interactively.
.TP
.SH EXAMPLE
The following is an example from an interactive session.
.sp
.nf
$ mk_wire
Enter mged file name (25 char max).
	wire.g
Enter the number of segments (maximum of 10).
	3
Enter starting point of segment # 1.
	0 0 0
Enter radius at the starting point of segment # 1.
	.25
Enter ending point of segment # 1.
	0 5 -3
Enter radius at the ending point of segment # 1.
	.25
Enter ending point of segment # 2.
	0 10 -3
Enter radius at the ending point of segment # 2.
	.25
Enter ending point of segment # 3.
	0 12 -2
Enter radius at the ending point of segment # 3.
	.25


mged file created:  wire.g
Segment # 1:  (0.000000,0.000000,0.000000) 0.250000
              (0.000000,5.000000,-3.000000) 0.250000
Segment # 2:  (0.000000,5.000000,-3.000000) 0.250000
              (0.000000,10.000000,-3.000000) 0.250000
Segment # 3:  (0.000000,10.000000,-3.000000) 0.250000
              (0.000000,12.000000,-2.000000) 0.250000

.fi
In this example a wire of three segments is made.  These segments
are joined together with spheres.  All dimensions are in millimeters.

.SH  SEE ALSO
mk_bolt(1), mk_handle(1), mk_window(1), mk_winfrm(1), mk_gastank(1)

.SH AUTHOR
Susan A. Coates
