# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded DbPage 1.0 [list source [file join $dir DbPage.itk]]
package ifneeded ExamplePage 1.0 [list source [file join $dir ExamplePage.itk]]
package ifneeded FbPage 1.0 [list source [file join $dir FbPage.itk]]
package ifneeded FeedbackDialog 1.0 [list source [file join $dir FeedbackDialog.itk]]
package ifneeded FrameBufferDialog 1.0 [list source [file join $dir FrameBufferDialog.itk]]
package ifneeded FullColorPage 1.0 [list source [file join $dir FullColorPage.itk]]
package ifneeded GhostPage 1.0 [list source [file join $dir GhostPage.itk]]
package ifneeded HelpPage 1.0 [list source [file join $dir HelpPage.itk]]
package ifneeded HighlightedPage 1.0 [list source [file join $dir HighlightedPage.itk]]
package ifneeded IntroPage 1.0 [list source [file join $dir IntroPage.itk]]
package ifneeded LinePage 1.0 [list source [file join $dir LinePage.itk]]
package ifneeded MGEDpage 1.0 [list source [file join $dir MGEDpage.itk]]
package ifneeded PictureTypeA 1.0 [list source [file join $dir PictureTypeA.itcl]]
package ifneeded PictureTypeB 1.0 [list source [file join $dir PictureTypeB.itcl]]
package ifneeded PictureTypeBase 1.0 [list source [file join $dir PictureTypeBase.itcl]]
package ifneeded PictureTypeC 1.0 [list source [file join $dir PictureTypeC.itcl]]
package ifneeded PictureTypeD 1.0 [list source [file join $dir PictureTypeD.itcl]]
package ifneeded PictureTypeE 1.0 [list source [file join $dir PictureTypeE.itcl]]
package ifneeded PictureTypeF 1.0 [list source [file join $dir PictureTypeF.itcl]]
package ifneeded Wizard 1.0 [list source [file join $dir Wizard.itk]]
