/*
 *			rt/Cakefile
 */
#define CONFIGDEFS	RT_CONFIG

#define SRCDIR	rt
#define PRODUCTS	rt rtrad rtpp rtray rtshot rtwalk rtcheck rtg3 rtxray
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* light.h material.h mathtab.h rad.h rdebug.h */
#define FILES	\
	rtshot \
	rt opt do worker \
	view viewpp viewray viewrad viewcheck viewg3 \
	regionfix \
	shade sh_text sh_cloud mathtab \
	material refract sh_stack \
	sh_plastic sh_cook wray sh_spm sh_light \
	sh_marble sh_stxt sh_points

/* Explicit composition of each product */

#define	RT_OBJ	rt.o opt.o do.o worker.o sh_text.o sh_cloud.o view.o wray.o \
		mathtab.o material.o refract.o \
		shade.o sh_stack.o sh_plastic.o \
		sh_cook.o sh_spm.o sh_light.o sh_marble.o \
		sh_stxt.o sh_points.o

#if defined(old_CRAY1)
/* XMP UNICOS version, sigh */
#	define	XMP_MULTI	/lib/multi/libc.o \
		/lib/multi/libu.o \
		/lib/multi/libm.o 

rt:	RT_OBJ LIBRT
	echo "nodeflib;symbols=off;map=stat;stack=200000+60000;heap=50000+50000" >segldr.cmds
	segldr -ort RT_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBSYSV LIBMALLOC XMP_MULTI segldr.cmds
#else

rt:	RT_OBJ LIBRT
	CC LDFLAGS RT_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rt

#endif

#define RTRAY_OBJ	rt.o opt.o do.o worker.o viewray.o regionfix.o \
			wray.o mathtab.o material.o

rtray:	RTRAY_OBJ LIBRT
	CC LDFLAGS RTRAY_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtray

#define RTPP_OBJ	rt.o opt.o do.o worker.o viewpp.o mathtab.o \
			material.o

rtpp:	RTPP_OBJ LIBRT
	CC LDFLAGS RTPP_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtpp

#define RTXRAY_OBJ	rt.o opt.o do.o worker.o mathtab.o \
			material.o viewxray.o

rtxray:	RTXRAY_OBJ LIBRT
	CC LDFLAGS RTXRAY_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtxray

#define RTRAD_OBJ	rt.o opt.o do.o worker.o mathtab.o \
			material.o viewrad.o

rtrad:	RTRAD_OBJ LIBRT
	CC LDFLAGS RTRAD_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtrad

#define RTSCAT_OBJ	rt.o opt.o do.o worker.o mathtab.o \
			material.o viewscat.o

rtbscat: RTSCAT_OBJ LIBRT LIBRAD
	CC LDFLAGS RTSCAT_OBJ LIB_PRE''LIBRAD LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtbscat

#define RTCHECK_OBJ	rt.o opt.o do.o worker.o viewcheck.o \
			mathtab.o material.o

rtcheck: RTCHECK_OBJ LIBRT
	CC LDFLAGS RTCHECK_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtcheck

rtshot:	rtshot.o LIBRT
	CC LDFLAGS rtshot.o LIB_PRE''LIBRT LIBRT_LIBES LIBMALLOC LIBES -o rtshot

rtwalk:	rtwalk.o LIBRT
	CC LDFLAGS rtwalk.o LIB_PRE''LIBRT LIBRT_LIBES LIBMALLOC LIBES -o rtwalk

#define RTG3_OBJ	rt.o opt.o do.o worker.o viewg3.o regionfix.o \
			mathtab.o material.o

rtg3:	RTG3_OBJ LIBRT
	CC LDFLAGS RTG3_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtg3

#define RTHIDE_OBJ	rt.o opt.o do.o worker.o viewhide.o regionfix.o \
			mathtab.o material.o

rthide:	RTHIDE_OBJ LIBRT
	CC LDFLAGS RTHIDE_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rthide

#define RTDUMMY_OBJ	rt.o opt.o do.o worker.o viewdummy.o regionfix.o \
			mathtab.o material.o

rtdummy:	RTDUMMY_OBJ LIBRT
	CC LDFLAGS RTDUMMY_OBJ LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtdummy

rtexample:	LIBRT rtexample.o
	CC LDFLAGS rtexample.o LIB_PRE''LIBRT LIB_PRE''LIBFB LIBFB_LIBES LIBRT_LIBES LIBMALLOC LIBES -o rtexample

#include "../Cakefile.rules"
