.\" @(#) $Header$ (BRL)
.TH RTHIDE 1 BRL/CAD
.UC 4
.SH NAME
rthide \(em raytrace a model, writing a UNIX-Plot hidden line removed
file.
.SH SYNOPSIS
.B rthide
[ options ... ]
model.g
objects ...
> model.pl
.SH DESCRIPTION
.I Rthide
operates on the indicated
.I objects
in the input
.I model.g
and produces a hidden line removed UNIX-Plot
file with bas-relief features.
.LP
The orientation of the rays to be fired may be specified by
the
.B \-a
and
.B \-e
options, in which case the model will be autosized, and the grid
will be centered on the centroid of the model, with ray spacing
chosen to span the entire set of
.I objects.
Alternatively,
with the
.B \-M
option, a transformation matrix may be provided on standard input
which maps model-space to view-space.
In this case, the grid ranges from -1.0 <= X,Y <= +1.0 in view space,
with the size of the grid (number of rays fired) specified with
.B \-s
This option is most useful when
.B rthide
is being invoked from a shell script created by an
.IR mged (1)
\fIsaveview\fR command.
.LP
The following options are recognized.
.TP
.B \-s#
Number of rays to fire in X and Y directions (square grid).
Default is 512 (512x512).
.TP
.B \-a#
Select azimuth in degrees.  Used with
.B \-e
and conflicts with
.B \-M
.TP
.B \-A#
Select angle for shading.  Default is 5.0 degrees. 89.0 will produce
a plot where only steep drops and rises are shaded.
.TP
.B \-e#
Select elevation in degrees.  Used with
.B \-a
and conflicts with
.B \-M
.TP
.B \-M
Read model2view matrix from standard input.
Conflicts with
.B \-a
and
.B \-e
.TP
.B \-g#
Select grid cell width.
.TP
.B \-G#
Select grid cell height.  If \fInot\fR specified, cell height equals
cell width.
.TP
.B \-U #
sets the Boolean variable
.I use_air
to the given value.
.TP
.B \-o
.B output.pl
specifies a named file for output.
By default, the plot is written to hide.pl.
.TP
.B \-x#
Set librt debug flags to (hexadecimal) number.
.LP
The
.B rthide
program is a simple front-end to
.IR librt (3)
which is most useful when used with
.IR mged (1).
.SH EXAMPLE
This section will acquaint the user with the ordinary usage of \fIrthide\fR.

.nf
.ce
\fIrthide -s32 model.g all.g > file.pl\fR
.fi

This will result in a 32 by 32 UNIXplot file of the named model.  There will 
be some shading of the plot based on surface curvature.  In order to minimize
this shading, an angle can be specified:

.nf
.ce
 \fIrthide -s32 -A89.0  model.g all.g > file.pl\fR
.fi

elliminates shading due to curvature.  However, shading resulting from sharp
changes in gradient cannot be elliminated.
.LP
The plotfile resulting from an \fIrthide\fR run can be viewed directly
via \fIpl-sgi\fR:

.nf
.ce
 \fIpl-sgi hide.pl\fR
.fi

or it can be overlayed onto a solid model in \fImged\fR:

.nf
.ce
\fImged>\fR
\fIoverlay hide.pl\fR
.fi

This technique can be used to position and plot \fIrthide\fR output.
.SH "OVERLAP REPORTING"
\fIRthide\fR shares overlap handling and reporting with the rest of the
\fIRT\fR family of applications.  A brief description of the overlap
reporting follows.
.LP
The first one hundred (100) overlaps are individually reported.  Thereafter,
only one out of each additional one hundred overlaps are reported, and
the user is notified that overlap printouts are being omitted.  This
alerts the user that more overlaps exist, but that they are too numerous to
list individually.  The general overlap message takes the following form:

.nf
.ce
 \fI"OVERLAP1: reg=region_name isol=solid_name"\fR
.ce
 \fI"OVERLAP2: reg=region_name isol=solid_name"\fR
.ce
 \fI"OVERLAP depth #mm at (x, y, z) sx# sy# lvl#"\fR
.fi

This means that OVERLAP1 and OVERLAP2 share a common space (depth) of
#millimeters starting at the point x, y, z in model coordinates, and 
at the ray coordinates (screen coordinates) sx and sy.  Level refers to the
level of recursion, and will typically be zero unless glass or mirror
objects are present.
.SH "SEE ALSO"
mged(1),
rt(1), rtray(1),
librt(3), libplot3(), plot3(5), ray(5V).
.SH DIAGNOSTICS
Numerous error conditions are possible, usually due to errors in
the geometry database.
Descriptive messages are printed on standard error (file descriptor 2).
.SH AUTHORS
Susanne Muuss, J.D.
.br
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005-5066
.SH COPYRIGHT
This software is Copyright (C) 1990 by the United States Army.
All rights reserved.
.SH BUGS
.LP
Most deficiencies observed while using the
.B rthide
program are usually with the
.IR librt (3)
package instead.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
