.TH RPATCH 1 BRL/CAD
.SH NAME
rpatch \- convert FASTGEN ASCII databases into a format suitable for
.I patch-g.
.SH SYNOPSIS
.I rpatch
[-D] [-3] < FASTGEN_FILE > OUTPUT_FILE
.SH DESCRIPTION
This program reformats FASTGEN files to a form usable by
.I patch-g.
The
.I -D
option handles type 3 components as donuts rather than triangles. The
.I -3
option reads FASTGEN3 format files (coordinates are each 10 columns wide).
.SH EXAMPLE
.I
rpatch < fastgen_file > file.rpatch
.SH DIAGNOSTICS
The diagnostics are intended to be self-explanatory.
.SH SEE ALSO
brlcad(1), mged(1), patch-g(1)
.SH AUTHOR
John R. Anderson
.SH BUG REPORTS
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
