.TH BOT_SHELL-VTK 1 BRL-CAD
.\"                B O T _ S H E L L - V T K . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
bot_shell-vtk \- VTK polydata converter (BRL-CAD to VTK)
.SH SYNOPSIS
.B bot_shell-vtk [-m] [-n] [-d debug_level] [-g cell_size] -o vtk_polydata_output brlcad_database.g object1 [object2 object3 ...]
.SH DESCRIPTION
.I bot_shell-vtk
uses raytracing to extract the exterior triangles from a model made up
of BOT primitives. The default operation is to fire a single ray at each
triangle of each BOT primitive in the specified objects. The rays are fired
anti-normalward towards the center of each triangle from outside the model
bounding box. If the triangle currently under consideration appears as the
first object hit along the ray, then that triangle is included in the
VTK polydata output (thus retaining only exterior triangles). Non-BOT
primitives ancountered along the rays may hide BOT triangles, but non-BOT
primitives do not contribute to the output.
The
.I -m
option may be specified to enable both the first and last triangles along
each ray to be added to the output. This can improve performance, by reducing
the number of rays fired, but may reduce performance for complex models
because it requires processing each ray completely through the model.
If the
.I -n
option is specified, the the output will include vertex normals in the
VTK output. If the BOT primitives of the input BRL-CAD model do not
have vertex normal information, this option will not add any information
to the output, but will greatly increase the size of the outout file.
If the
.I -g
option is specified, then the rays are fired from a uniform grid for
three orthogonal directions rather than at each individual triangle. This
can give a fairly rapid result for larger cell sizes, but is likely to miss
some triangles. The
.I cell_size
must be specified in millimeters.
The
.I -d
option may be used to get debug output during processing. This is likely to
only be useful for developers.
.SH EXAMPLE
.RS
$ \|\fIbot_shell-vtk \| -o output.vtk \| sample.g \| the_exterior\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
