.TH BOT_DUMP 1 BRL-CAD
.\"                      B O T _ D U M P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2008-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
bot_dump \- export polygonal BoT primitives without performing evaluation
.SH SYNOPSIS
.B bot_dump [-b] [-n] [-m directory] [-o file] [-t dxf|obj|sat|stl] [-u units] [-v] geom.g [bot1 bot2 ...]
.SH DESCRIPTION
.I bot_dump
.P
The
.I -b
option may be specified to indicate that the output file should be in
a binary format (e.g., for formats that support ascii and binary
formats like stl).
.P
If the
.I -n
option is specified, BoT surface normals will be included in the output
of
.I obj
files. This option is specific to
.I obj
file generation since normal vector outputs are already an integral
part of the
.I stl
file outputs and both the
.I dxf
and
.I sat
file formats do not support or require surface normal generation.
.P
If the
.I -m
option is specified, then BoTs will be output to the directory name
specified with one BoT per file.
.P
The
.I -o
option specifies what output file the BoT data should be dumped to.
.P
The
.I -t
is used to specify the desired output file type.  The default output
type is STL in ASCII format.
.P
The
.I -u
option takes a units string that indicates the unit conversion to
perform during output (converting from internal millimeter values to
the unit type specified).
.SH EXAMPLE
.RS
$ \|\fIbot_dump \| -o some_bot_dump.dxf \| -t dxf \| sample.g \| some_bot\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
