.TH STL-G 1 BRL-CAD
.SH NAME
bot_shell-vtk \- VTK polydata converter (BRL-CAD to VTK)
.SH SYNOPSIS
.B bot_shell-vtk [-m] [-n] [-d debug_level] [-g cell_size] -o vtk_polydata_output brlcad_database.g object1 [object2 object3 ...]
.SH DESCRIPTION
.I Bot_shell-vtk
uses raytracing to extract the exterior triangles from a model made up
of BOT primitives. The default operation is to fire a single ray at each
triangle of each BOT primitive in the specified objects. The rays are fired
anti-normalward towards the center of each triangle from outside the model
bounding box. If the triangle currently under consideration appears as the
first object hit along the ray, then that triangle is included in the
VTK polydata output (thus retaining only exterior triangles). Non-BOT
primitives ancountered along the rays may hide BOT triangles, but non-BOT
primitives do not contribute to the output.
The
.I -m
option may be specified to enable both the first and last triangles along
each ray to be added to the output. This can improve performance, by reducing
the number of rays fired, but may reduce performance for complex models 
because it requires processing each ray completely through the model.
If the
.I -n
option is specified, the the output will include vertex normals in the
VTK output. If the BOT primitives of the input BRL-CAD model do not
have vertex normal information, this option will not add any information
to the output, but will greatly increase the size of the outout file.
If the
.I -g
option is specified, then the rays are fired from a uniform grid for
three orthogonal directions rather than at each individual triangle. This
can give a fairly rapid result for larger cell sizes, but is likely to miss
some triangles. The
.I cell_size
must be specified in millimeters.
The
.I -d
option may be used to get debug output during processing. This is likely to
only be useful for developers.
.SH EXAMPLE
.RS
$ \|\fIbot_shell-vtk \| -o output.vtk \| sample.g \| the_exterior\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BND/EAB Advanced Computer Systems Team
.br
The U. S. Army  Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
