.TH DBUPGRADE 1 BRL-CAD
.\"                     D B U P G R A D E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2002-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.UC 4
.SH NAME
dbupgrade \(em a program to upgrade BRL-CAD \fBmged\fR geometry databases files to the current version.
.SH SYNOPSIS
.B dbupgrade
input.g
output.g
.SH DESCRIPTION
.I dbupgrade
operates on the indicated input geometry database
.I input.g
recognizing the version of the BRL-CAD database provided as input and
then converting it to the current database version.  Output is then saved to the specified
.I output.g
file.
.LP
Note that this tool does not automatically ``fix'' an existing (v4
format) binary database that was transferred from a
binary-incompatible platform.  However, if you run
.B dbupgrade
on the file before transferring from that platform, the upgraded
output file will be platform independent.
.PP
Running
.B dbupgrade
removes the need to run
.IR g2asc (1)
and
.IR asc2g (1)
on a database.  The latest BRL-CAD geometry database format is
platform independent.
.SH "SEE ALSO"
mged(1), g2asc(1), asc2g(1).
.SH DIAGNOSTICS
Numerous error conditions are possible, usually due to errors in
the geometry database.
Descriptive messages are printed on standard error (file descriptor 2).
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
