.TH DXF-G 1 BRL-CAD
.\"                        D X F - G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
dxf-g \- DXF Translator (DXF to BRL-CAD)
.SH SYNOPSIS
.B dxf-g
[-c] [-d] [-v] [-s scale_factor] [-t tolerance] file.dxf database.g
.SH DESCRIPTION
.I dxf-g\^
converts the specified
.I file.dxf
to a BRL-CAD
.I database.g
file.

The following options are available:

.TP
.B \-c
Only the first color seen for a layer should be used. Without this option,
layers may be broken into seperate BOT primitives according to color assigned.

.TP
.B \-d
Sets a debug flag. The only effect is to cause a core dump on failure.
This is probably not useful except for developers.
.TP
.B \-v
Produces very verbose output on stderr.
.TP
.B \-s \fIscale_factor\fR
Provides a scale factor to be applied to the DXF input. This can be used for DXF files
that do not provide units information.
.TP
.B -t \fItolerance\fR
Specifies the maximum distance (in mm) between two vertices at which the two vertices
will be considered to be the same vertex.

.P
The
.B file.dxf
file is expected to be in the ASCII Autodesk DXF format as defined in the
Autocad 2006 manuals. This converter handles entities of types:
.IP
POLYLINE
.br
LWPOLYLINE
.br
LEADER
.br
DIMENSION
.br
VERTEX
.br
LINE
.br
CIRCLE
.br
ARC
.br
ELLIPSE
.br
3DFACE
.br
TEXT
.br
MTEXT
.br
.ATTRIB
.br
SOLID
.br
SPLINE
.P
The POLYLINE entities in AUTOCAD are actually a container for numerous different entity types. The types
of POLYLINE entities converted include:
.IP
3D polylines
.br
3D polygon meshes
.br
polyface meshes.
.P
SOLID entities are 2D shapes with a solid fill, but this converter does not do
any filling.
Each layer is converted to a seperate object. Colors are also converted.
.SH EXAMPLE
.RS
$ \|\fIdxf-g \|sample.dxf \|sample.g\fP
.RE
.SH "SEE ALSO"
.I
http://images.autodesk.com/adsk/files/dxf_format.pdf
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
