.TH FAST4-G 1 BRL-CAD
.\"                      F A S T 4 - G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2011 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
fast4-g \- FASTGEN4 Translator (FASTGEN4 to BRL-CAD)
.SH SYNOPSIS
.B fast4-g
[-dwq] [-o plot_file] [-m muves_warnings] [-c id_list] [-x RT_DEBUG_FLAG] [-b BU_DEBUG_FLAG] file.fastgen4 file.g
.SH DESCRIPTION
.I fast4-g\^
converts the specified
.I file.fastgen4
to a BRL-CAD
.I file.g
file.
.PP
The
.I -d
option prints debugging information and the
.I -w
option prints warnings whenever an object is assigned a default name (no
name specified in the FASTGEN4 file).
.PP
The
.I -q
option requests quiet mode, so that nothing will be printed except errors.
.PP
The
.I -b
option specifies a value for a debug flag for libbu and the
.I -x
option specifies a value for the librt debug flag.
.PP
The
.I -o
option indicates that all CTRI and CQUAD elements that get processed should be output to the
specified plot_file in libplot3 format.  This plot file can be viewed in MGED using the
.I overlay
command.
.PP
The
.I -m
option requests that information about any CHGCOMP and CBACKING elements be output in the specified
.I muves_warnings
file.
.PP
The
.I -c
option allows the user to specify a restricted set of components to process from the
input file. The
.I id_list
may be a comma separated list of ident numbers and ranges. For example,
.I -c 3002,5678,9213,1002-1100
will convert only the regions with idents of 3002,5678,9213, and everything from 1002 through 1100.
.PP
If you have a FASTGEN2 or FASTGEN3 format file, they can be converted by processing them with
.I rpatch
and then providing the resulting rpatch file to the
.I patch-g
converter.  See their respective manual pages for more information.
.PP
The
.I file.fastgen4
file is expected to be in the FASTGEN 4.1 format as defined in the
FASTGEN 4.1 User Manual.
.PP
.I CCONE1, CCONE2,
and
.I CCONE3
elements are converted to BRL-CAD truncated right cylinders
.I (TRC). CHEX2
elements are converted to BRL-CAD arbitrary convex polyhedrons
.I (ARB8).
.I CLINE
elements are converted to BRL-CAD cline solids.
.I CQUAD
,
.I CTRI
, and
.I CHEX1
elements are converted to faces of a BRL-CAD BOT (Bag Of Triangles).
.I CSPHERE
elements are converted to BRL-CAD sphere
.I (SPH)
solids. BRL-CAD region ident numbers are assigned by combining the
FASTGEN4 group and component numbers:
.nf
	ident = group x 1000 + component
.fi
and object names are assigned from the FASTGEN4
.I $NAME
elements using an algorithm to create unique BRL-CAD names.
.SH EXAMPLE
.RS
$ \|\fIfast4-g \|sample.fastgen4 \|sample.g\fP
.RE
.SH "SEE ALSO"
rpatch(1), patch-g(1)
.br
.I
FASTGEN 4.1 User's Manual,
XRESV Tech Note 94-01,
Hugh Griffis and Maty Lentz,
April 1994
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
