.TH G-NMG 1 BRL-CAD
.\"                        G - N M G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
g-nmg \- Perform Boolean evaluations to produce NMG objects
.SH SYNOPSIS
.B g-nmg
[-v] [-b] [-t calc_dist_tol] [-a abs_tess_tol] [-n norm_tess_tol] [-r rel_tess_tol]
[-o outfile.g] infile.g object(s)
.SH DESCRIPTION
.I g-nmg
performs the Boolean operations in the specified
.I object(s)
and writes the resulting NMG primitives (or BOT primitives, if the
.I
-b
option is specified) to
.I outfile.g
or to
.I stdout
if the
.I -o
option is not used.

The following options are available:
.TP
.B \-a abs_tess_tol
Specify an absolute tessellation tolerance (in millimeters).
This requires that the maximum absolute error from the tessellated surface to the actual
surface must not be greater than
.I abs_tess_tol.
.TP
.B \-b
Convert the results to a BOT primitive (triangle representation) instead of leaving it as an NMG.
.TP
.B \-n norm_tess_tol
Specify a surface normal error tolerance (in degrees) for the tessellation.
.TP
.B \-o outfile.g
Specify the name of the file to be created.  This should not be the same as the input file.
.TP
.B \-r rel_tess_tol
Specify a relative error tolerance. This effectively
sets an absolute tolerance for each primitive solid by multiplying the
overall size of the solid by
.I rel_tess_tol.
This allows small objects to be tessellated with small tolerances, while large objects are tessellated with large tolerances.
For example, specifying
.I \-r 0.1
when tesselating an object 2m in size, will result in a tolerance of .2m (2.0 * 0.1).
The same option will cause a 5cm object to be tesselated with a tolerance of 0.5cm.
.TP
.B \-t calc_dist_tol
Specify a calculational distance tolerance (in millimeters).
This tolerance is used to distinguish neighboring vertices.
Any two vertices less than this tolerance distance apart will be considered the same vertex.
The default value is 0.005mm.
Prior to performing the Boolean operations for each region, the involved primitive solids
are converted to a planar facetted approximation and stored as NMG solids. This tessellation
can be controlled using the tessellation tolerances.
.TP
.B \-v
Produce copious progress information.
.TP
.B \-x
Set librt debug flags.
The definitions of these flags may be found in
.I librt/debug.h
.TP
.B \-X
Set NMG routines debug flags.
The definitions of these flags may be found in
.I h/nmg.h.
.SH EXAMPLE
.RS
$ \|\fIg-nmg \|-o shell.g \|sample.g \|sample_object\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH BUGS
Boolean operations under finite precision arithmetic are not guaranteed to be solvable.  As a result this command can fail.  Scaling geometry adjusting tolerance values, and restructuring the boolean tree will often result in a successful tesselation.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
