.TH G-VRML 1 BRL-CAD
.\"                       G - V R M L . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
g-vrml \- Perform Boolean evaluations to produce a VRML version 2.0 file
.SH SYNOPSIS
.B g-vrml
[-v] [-d calc_dist_tol] [-a abs_tess_tol] [-n norm_tess_tol] [-r rel_tess_tol]
[-x librt_debug_flag] [-X NMG_debug_flag] [-u units_name] [-o outfile] infile.g object(s)
.SH DESCRIPTION
.I g-vrml
performs the Boolean operations specified in any regions in the specified
.I object(s)
and writes the resulting NMG objects to
.I outfile
or to
.I stdout
if the
.I -o
option is not used. The output is in VRML version 2.0 format. The
.I -v
option requests verbose output while the conversion is taking place. The
.I -d
option specifies a calculational distance tolerance (in millimeters). This
tolerance is used to distinguish neighboring vertices. Any two vertices less than
this tolerance distance apart will be considered the same vertex. The default value
is 0.005mm.
Prior to performing the Boolean operations for each region, the involved primitive solids
are converted to a planar facetted approximation and stored as NMG solids. This tessellation
can be controlled using the tessellation tolerances. The
.I -a
option may be used to specify an absolute tessellation tolerance (in millimeters). This
requires that the maximum absolute error from the tessellated surface to the actual
surface must not be greater than
.I abs_tess_tol.
The
.I -n
option specifies a surface normal error tolerance (in degrees) for the tessellation.
The
.I -r
option may be used to set a relative error tolerance. This effectively
sets an absolute tolerance for each primitive solid by multiplying the
overall size of the solid by
.I rel_tess_tol.
The
.I -x
and
.I -X
options are used to set debug flags for
.I librt
and the
.I NMG
routines respectively. The definitions of these flags may be found in
.I librt/debug.h
and
.I h/nmg.h.
The
.I -u
option can be used to set the units for the resulting VRML file (the default is mm).
Any units name that MGED accepts will work here.
.SH EXAMPLE
.RS
$ \|\fIg-vrml \|-o shell.wrl \|sample.g \|sample_object\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson (with update to VRML 2.0 by John P. Williams, QUADRA Enterprises)
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
