.TH G-X3D 1 BRL-CAD
.\"                        G - X 3 D . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
g-x3d \- Perform Boolean evaluations to produce an X3D facetted model
.SH SYNOPSIS
.B g-x3d
[-v] [-d calc_dist_tol] [-a abs_tess_tol] [-n norm_tess_tol] [-r rel_tess_tol]
[-x librt_debug_flag] [-X NMG_debug_flag] [-u units_name] [-o outfile] infile.g object(s)
.SH DESCRIPTION
.I g-x3d
performs the Boolean operations specified in any regions in the specified
.I object(s)
and writes the resulting facetted objects to
.I outfile
or to
.I stdout
if the
.I -o
option is not used. The output is in X3D facetted format. The
.I -v
option requests verbose output while the conversion is taking place. The
.I -d
option specifies a calculational distance tolerance (in millimeters). This
tolerance is used to distinguish neighboring vertices. Any two vertices less than
this tolerance distance apart will be considered the same vertex. The default value
is 0.005mm.
Prior to performing the Boolean operations for each region, the involved primitive solids
are converted to a planar facetted approximation and stored as NMG solids. This tessellation
can be controlled using the tessellation tolerances. The
.I -a
option may be used to specify an absolute tessellation tolerance (in millimeters). This
requires that the maximum absolute error from the tessellated surface to the actual
surface must not be greater than
.I abs_tess_tol.
The
.I -n
option specifies a surface normal error tolerance (in degrees) for the tessellation.
The
.I -r
option may be used to set a relative error tolerance. This effectively
sets an absolute tolerance for each primitive solid by multiplying the
overall size of the solid by
.I rel_tess_tol.
The
.I -x
and
.I -X
options are used to set debug flags for
.I librt
and the
.I NMG
routines respectively. The definitions of these flags may be found in
.I librt/debug.h
and
.I h/nmg.h.
The
.I -u
option can be used to set the units for the resulting X3D file (the default is mm).
Any units name that MGED accepts will work here.
.SH EXAMPLE
.RS
$ \|\fIg-x3d \|-o shell.x3d \|sample.g \|sample_object\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
Robert Parker
.SH SOURCE
The SURVICE Engineering Co.
.br
Aberdeen, MD
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
