.TH G2ASC 1 BRL-CAD
.\"                        G 2 A S C . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
g2asc,
asc2g \- convert between binary and ASCII \fBmged\fP geometry databases.
.SH SYNOPSIS
.B g2asc
file.g file.asc
.br
.B asc2g
file.asc file.g
.SH DESCRIPTION
The local machine binary representation
of an
.IR mged (1)
database is inherently non-portable.
.I g2asc
and
.I asc2g
are simple filters which convert between
the binary form and an ASCII representation.
Any warning messages are written to standard error.
.PP
The ASCII representation of BRL-CAD geometry databases is not a fixed
format and is allowed to change without deprecation notice.  In
general, this will not occur any more frequently than the binary
geometry database format changes, though both are open specifications.
Regardless, the ASCII representation is subject to change without
notice and should not be relied upon by external codes.  Currently,
the ASCII representation is a Tcl script that is parsed by a
simplified geometry command interpreter.
.PP
.I g2asc
and
.I asc2g
are typically used to convert binary
.IR mged (1)
files to an ASCII format.  This was traditionally performed so the
files could be transferred to another machine in a portable format.
Although no longer necessary for the current binary geometry database
files that are created by mged ("v5" format), the g2asc conversion
process is still necessary if manipulating older ("v4" format)
geometry database files.  On the local machine, files are converted to
ASCII using
.IR g2asc (1),
then transferred to the remote machine.  On the remote machine, the files
are then converted back to the binary representation for that machine using
.IR asc2g (1).
.SH EXAMPLE
.I
g2asc  file.g  file.asc
.br
scp file.asc remote:file.asc
.br
rsh remote "asc2g  file.asc  file.g"
.SH DIAGNOSTICS
The diagnostics are intended to be self-explanatory.
.SH SEE ALSO
brlcad(1), mged(1)
.SH AUTHOR
Charles Michael Kennedy
.br
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH BUG REPORTS
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
