.TH NMG-RIB 1 BRL-CAD
.\"                      N M G - R I B . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
nmg-rib \- Convert polygonal NMG to Renderman Interface Bytestream (RIB)
.SH SYNOPSIS
.B nmg-rib
.RB [-t] database.nmg nmg_solid ...
.SH DESCRIPTION
The
.I nmg-rib
program
reads the geometry database
.I database.nmg
and converts the named polygonal NMG solids to RIB format polygons.
If the
.B \-t
option is given, the NMG solid will be triangulated first.
If NMG a vertexuse normal is present for a vertexuse, it is used as the RIB
vertex normal.  Otherwise, the NMG face normal is used.
.SH EXAMPLE
.nf
% \fBmged box.g\fR
BRL-CAD Release 4.1   Graphics Editor (MGED)
    Tue Dec 15 15:49:30 EST 1992, Compilation 9
    stay@wolf:/m/dist4.1/mged

mged> \fBl box.s\fR
box.s:  ARB8
        1 (0.5, -0.5, -0.5)
        2 (0.5, 0.5, -0.5)
        3 (0.5, 0.5, 0.5)
        4 (0.5, -0.5, 0.5)
        5 (-0.5, -0.5, -0.5)
        6 (-0.5, 0.5, -0.5)
        7 (-0.5, 0.5, 0.5)
        8 (-0.5, -0.5, 0.5)
mged> \fBfacetize box.nmg box.s\fR
facetize:  tessellating primitives with tolerances a=0, r=0.01, n=0
facetize:  evaluating Boolean expressions
facetize:  converting NMG to database format
facetize:  wrote 6.38 Kbytes to database
mged> \fBq\fR
% \fBnmg-rib box.g box.nmg\fR
Polygon "P" [ -0.5 -0.5 0.5\ \ 0.5 -0.5 0.5\ \ 0.5 0.5 0.5\ \ -0.5 0.5 0.5\ \  ] "N" [ 0 0 1\ \ 0 0 1\ \ 0 0 1\ \ 0 0 1\ \  ]
Polygon "P" [ 0.5 0.5 -0.5\ \ 0.5 -0.5 -0.5\ \ -0.5 -0.5 -0.5\ \ -0.5 0.5 -0.5\ \  ] "N" [ 0 0 -1\ \ 0 0 -1\ \ 0 0 -1\ \ 0 0 -1\ \  ]
Polygon "P" [ 0.5 0.5 0.5\ \ 0.5 0.5 -0.5\ \ -0.5 0.5 -0.5\ \ -0.5 0.5 0.5\ \  ] "N" [ 0 1 0\ \ 0 1 0\ \ 0 1 0\ \ 0 1 0\ \  ]
Polygon "P" [ -0.5 -0.5 -0.5\ \ 0.5 -0.5 -0.5\ \ 0.5 -0.5 0.5\ \ -0.5 -0.5 0.5\ \  ] "N" [ 0 -1 0\ \ 0 -1 0\ \ 0 -1 0\ \ 0 -1 0\ \  ]
Polygon "P" [ -0.5 -0.5 -0.5\ \ -0.5 -0.5 0.5\ \ -0.5 0.5 0.5\ \ -0.5 0.5 -0.5\ \  ] "N" [ -1 0 0\ \ -1 0 0\ \ -1 0 0\ \ -1 0 0\ \  ]
Polygon "P" [ 0.5 -0.5 0.5\ \ 0.5 -0.5 -0.5\ \ 0.5 0.5 -0.5\ \ 0.5 0.5 0.5\ \  ] "N" [ 1 0 0\ \ 1 0 0\ \ 1 0 0\ \ 1 0 0\ \  ]
%

.SH AUTHOR
Lee A. Butler
