.TH NMG-RIB 1 BRL-CAD
.\"                      N M G - R I B . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
nmg-rib \- Convert polygonal NMG to Renderman Interface Bytestream (RIB)
.SH SYNOPSIS
.B nmg-rib
.RB [-t] database.nmg nmg_solid ...
.SH DESCRIPTION
The
.I nmg-rib
program
reads the geometry database
.I database.nmg
and converts the named polygonal NMG solids to RIB format polygons.
If the
.B \-t
option is given, the NMG solid will be triangulated first.
If NMG a vertexuse normal is present for a vertexuse, it is used as the RIB
vertex normal.  Otherwise, the NMG face normal is used.
.SH EXAMPLE
.nf
% \fBmged box.g\fR
BRL-CAD Release 4.1   Graphics Editor (MGED)
    Tue Dec 15 15:49:30 EST 1992, Compilation 9
    stay@wolf:/m/dist4.1/mged

mged> \fBl box.s\fR
box.s:  ARB8
        1 (0.5, -0.5, -0.5)
        2 (0.5, 0.5, -0.5)
        3 (0.5, 0.5, 0.5)
        4 (0.5, -0.5, 0.5)
        5 (-0.5, -0.5, -0.5)
        6 (-0.5, 0.5, -0.5)
        7 (-0.5, 0.5, 0.5)
        8 (-0.5, -0.5, 0.5)
mged> \fBfacetize box.nmg box.s\fR
facetize:  tessellating primitives with tolerances a=0, r=0.01, n=0
facetize:  evaluating Boolean expressions
facetize:  converting NMG to database format
facetize:  wrote 6.38 Kbytes to database
mged> \fBq\fR
% \fBnmg-rib box.g box.nmg\fR
Polygon "P" [ -0.5 -0.5 0.5\ \ 0.5 -0.5 0.5\ \ 0.5 0.5 0.5\ \ -0.5 0.5 0.5\ \  ] "N" [ 0 0 1\ \ 0 0 1\ \ 0 0 1\ \ 0 0 1\ \  ]
Polygon "P" [ 0.5 0.5 -0.5\ \ 0.5 -0.5 -0.5\ \ -0.5 -0.5 -0.5\ \ -0.5 0.5 -0.5\ \  ] "N" [ 0 0 -1\ \ 0 0 -1\ \ 0 0 -1\ \ 0 0 -1\ \  ]
Polygon "P" [ 0.5 0.5 0.5\ \ 0.5 0.5 -0.5\ \ -0.5 0.5 -0.5\ \ -0.5 0.5 0.5\ \  ] "N" [ 0 1 0\ \ 0 1 0\ \ 0 1 0\ \ 0 1 0\ \  ]
Polygon "P" [ -0.5 -0.5 -0.5\ \ 0.5 -0.5 -0.5\ \ 0.5 -0.5 0.5\ \ -0.5 -0.5 0.5\ \  ] "N" [ 0 -1 0\ \ 0 -1 0\ \ 0 -1 0\ \ 0 -1 0\ \  ]
Polygon "P" [ -0.5 -0.5 -0.5\ \ -0.5 -0.5 0.5\ \ -0.5 0.5 0.5\ \ -0.5 0.5 -0.5\ \  ] "N" [ -1 0 0\ \ -1 0 0\ \ -1 0 0\ \ -1 0 0\ \  ]
Polygon "P" [ 0.5 -0.5 0.5\ \ 0.5 -0.5 -0.5\ \ 0.5 0.5 -0.5\ \ 0.5 0.5 0.5\ \  ] "N" [ 1 0 0\ \ 1 0 0\ \ 1 0 0\ \ 1 0 0\ \  ]
%

.SH AUTHOR
Lee A. Butler
