.TH PLY-G 1 BRL-CAD
.SH NAME
ply-g \- Stanford PLY format Translator (PLY to BRL-CAD)
.SH SYNOPSIS
.B ply-g
[-s scale_factor] [-v] [-d] file.ply file.g
.SH DESCRIPTION
.I ply-g
converts the specified
.I file.ply
to a BRL-CAD
.I file.g
file. The
.I -v
option (verbose) prints much information about what the process is doing.
The
.I -d
option sets a debug flag which will cause a core dump on error.
The
.I -s
option specifies a scale factor to be applied to the PLY data. By convention, PLY data is typically in meters,
so the default scale factor is 1000. The scale factor supplied on the command line will replace the default
scale factor. So, for example, specifying a scale factor of 500 will halve the size of the resulting BRL-CAD
model as compared to converting it without specifying a scale factor.
The
.I file.ply
file is expected to be in the Stanford PLY format (ASCII or binary).
.SH EXAMPLE
.RS
$ \|\fIply-g \|sample.ply \|sample.g\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army  Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
