.TH PROE-G 1 BRL-CAD
.\"                       P R O E - G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
proe-g \- Pro/Engineer Translator (Pro/Engineer to BRL-CAD)
.SH SYNOPSIS
.B proe-g
[-darS] [-i initial_ident] [-I constant_ident] [-m material_code] [-u reg_exp] [-x RT_DEBUG_FLAG] file.brl file.g
.SH DESCRIPTION
.I proe-g\^
converts the specified
.I file.brl
to a BRL-CAD
.I file.g
file.
The
.I -d
option prints debugging information.
The
.I -a
option implies that all the parts in the Pro/E model should be converted to
BRL-CAD
.I air
regions.
The
.I -i
option sets the starting ident number for the regions created. As each
new region is created, this number will be incremented before assigning
the next ident number (conflicts with
.I -I
). The
.I -I
option sets a constant ident number that will be assigned to all the regions created (conflicts with
.I -i
).
The
.I -m
option sets a material code that will be assigned to all the regions created (default is 1).
The
.I -r
flag indicates that the model should not be rotated, translated, or scaled, but left in
the same orientation and size as it was created in
.I Pro/E.
This allows the user to convert parts that are referenced by previously converted
assemblies, so that the transformation matrix in the referencing assembly will
size and position the part.
The
.I -x
option sets an RT debug flags (see librt/debug.h).
The
.I file.brl
file is expected to be output from the
.I BRL-CAD
menu option of the Pro/Engineer
.I EXPORT
menu. This menu option is a Pro/Develop application produced by the USARL.
.PP
Note that the routine documented here is obsolete, and only maintained for compatability with
older versions of Pro/Engineer. The current method of converting from Pro/Engineer to BRL-CAD
is still a two step process, but a newer Pro/Toolkit application must be installed (see ``install.doc''
in the ``pro-engineer'' directory of the BRL-CAD distribution). From within Pro/Engineer, the ``proe-brl''
option must be selected from the ``File'' menu, and the user will be prompted for an output file name,
a starting ident number, a maximum tessellation error, and an additional curvature correction.
The output from this new routine, is a Tcl script that may be converted to a BRL-CAD model using ``asc2g''
or by sourcing the file during an MGED session.
.SH EXAMPLE
.RS
$ \|\fIproe-g \|sample.brl \|sample.g\fP
.RE
.SH "SEE ALSO"
.I
Pro/Engineer Modeling User's Guide,
Version 13.0,
Parametric Technology Corporation
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army  Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
