.TH STL-G 1 BRL-CAD
./"                        S T L - G . 1
./" BRL-CAD
./"
./" Copyright (c) 2005 United States Government as represented by
./" the U.S. Army Research Laboratory.
./"
./" This document is made available under the terms of the GNU Free
./" Documentation License or, at your option, under the terms of the
./" GNU General Public License as published by the Free Software
./" Foundation.  Permission is granted to copy, distribute and/or
./" modify this document under the terms of the GNU Free Documentation
./" License, Version 1.2 or any later version published by the Free
./" Software Foundation; with no Invariant Sections, no Front-Cover
./" Texts, and no Back-Cover Texts.  Permission is also granted to
./" redistribute this document under the terms of the GNU General
./" Public License; either version 2 of the License, or (at your
./" option) any later version.
./"
./" You should have received a copy of the GNU Free Documentation
./" License and/or the GNU General Public License along with this
./" document; see the file named COPYING for more information.
./"
./"./"./"
.SH NAME
stl-g \- Stereolithography Translator (STL to BRL-CAD)
.SH SYNOPSIS
.B stl-g
[-db] [-i initial_ident] [-I constant_ident] [-m material_code] [-N forced_name] [-c units] [-t tolerance] [-x RT_DEBUG_FLAG] file.stl file.g
.SH DESCRIPTION
.I stl-g
converts the specified
.I file.stl
to a BRL-CAD
.I file.g
file. Use the
.I -b
option if you have a binary STL file (the default is ASCII).
The
.I -d
option prints debugging information.
The
.I -c
option specifies the units that are used in the STL file. The
.I units
string may be "mm", "in", "ft", ... (default is "mm").
The
.I -t
option specifies a tolerance distance (in mm) such that any two vertices
within tolerance distance of each other are treated as the same vertex.
The
.I -i
option sets the starting ident number for the regions created. As each
new region is created, this number will be incremented before assigning
the next ident number (conflicts with
.I -I
). The
.I -I
option sets a constant ident number that will be assigned to all the regions created (conflicts with
.I -i
).
The
.I -m
option sets a material code that will be assigned to all the regions created (default is 1).
The
.I -N
option sets a name for the resulting BRL-CAD object. STL files typically do not contain any
object names.
The
.I -x
option sets an RT debug flag (see librt/debug.h).
The
.I file.stl
file is expected to be a stereolithography file.
.SH EXAMPLE
.RS
$ \|\fIstl-g \|sample.stl \|sample.g\fP
.RE
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army  Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
