.TH VIEWPOINT-G 1 BRL-CAD
.\"                  V I E W P O I N T - G . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
viewpoint-g \- VIEWPOINT Translator (VIEWPOINT to BRL-CAD)
.SH SYNOPSIS
.B viewpoint-g
[-t tolerance] -c input_coordinates_file -e input_elements_file [-o database.g]
.SH DESCRIPTION
.I viewpoint-g\^
converts the specified input files to a BRL-CAD
.I database.g
file. The
.I tolerance
provided is the maximum distance (in mm) between two
vertices at which they will be considered to be the same vertex. The
.I input_coordinates_file
and the
.I input_elements_file
are expected to be in the
.I VIEWPOINT
triangulated format as provided by
.I Viewpoint Datalabs.
In this format each object is represented as a group of
elements, and each element is a group of triangular facets.
.SH EXAMPLE
.RS
$ \|\fIviewpoint-g \|-e viewpoint.elems \|-c viewpoint.coords \|-o sample.g\fP
.RE
.SH SEE ALSO
.nf
Viewpoint Dataset Catalog
Viewpoint Datalabs Int'l
625 South State Street
Orem, UT     84058
(801)229-3000
.fi
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
John Anderson
.SH SOURCE
SLAD/BVLD/VMB Advanced Computer Systems Team
.br
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, MD  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
