/*
 *		CAKE(1) specification file for G_LINT(1)
 *
 * $Header$
 */

#define	SRCDIR	g_lint
#define	PRODUCTS	g_lint
#define	SRCSUFF		.c
#define	MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

g_lint:	g_lint.o LIBRT_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS g_lint.o LIBRT LIBBN LIBBU LIBBU_LIBES  LIBES -o g_lint

solshoot:	solshoot.o LIBRT_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS solshoot.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o solshoot

testfree:	testfree.o LIBRT_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS testfree.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES -o testfree

#include "../Cakefile.rules"
