/*
 *			html/manuals/mged/animmate/Cakefile
 */
#include "../../../../Cakefile.defs"

#define PRODUCTS	*.html *.txt *.gif *.png
#define STATIC_PRODUCTS	*.html *.txt *.gif *.png
#define SRCDIR	animmate
#undef BINDIR
#define BINDIR	BASEDIR/html/manuals/mged/animmate
#undef BINPERM
#define BINPERM 444

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

clean&:
	@echo "" > /dev/null

noprod&:
	@echo "" > /dev/null

clobber&:
	@echo "" > /dev/null

#include "../../../../Cakefile.rules"
