/*
 *			libcursor/Cakefile
 */

#define PRODUCTS	libcursor.ARCH_SUF
#define SRCDIR	libcursor
#define FILES	cursor
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	libcursor_version
#define LIBRARY_TITLE		"BRL-CAD libcursor"

#include "../Cakefile.defs"

#include "../Cakefile.lib"
#include "../Cakefile.rules"
