/*
 *			libcursor/Cakefile
 */

#define PRODUCTS	libcursor.ARCH_SUF
#define SRCDIR	libcursor
#define FILES	cursor
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	libcursor_version
#define LIBRARY_TITLE		"BRL-CAD libcursor"

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc -lcurses
#endif

#include "../Cakefile.lib"
#include "../Cakefile.rules"
