.TH CANONIZE 1 BRLCAD
.\"                     C A N O N I Z E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
canonize \- queue a pix file to a printer using MDQS

.SH SYNOPSIS
.B canonize
.RB [ \-ah ]
.RB [ \-s\ squarefilesize]
.br
.RB [ \-w\ filewidth]
.RB [ \-n\ fileheight]
.br
.br
.RB [ \-g\ {cg|rgb|scan}]
.br
.RB [ \-t\ {u|l|m}]
.RB [ \-C\ {1-99}]
.RB [ \-q\ queue]
.br
.RB [ \-R\ dpi ]
.RB [ \-M\ xmag:ymag ]
.RB [ \-m]
.br
.RB [ \-X\ page_xoff]
.RB [ \-Y\ page_yoff]
.br
.RB [ \-N\ printheight]
.RB [ \-W\ printwidth]
.br
.RB [ \-v]
.RB [ \-q\ queue]
[file.pix ...]
.SH DESCRIPTION
.I Canonize
is a user agent for printing
.IR pix (5)
format files using a Canon(tm) CLC500 and the MDQS queuing system.
It can read the image from the standard input, or can send one or
more files whose names are specified on the command line.

By default, the image is printed using the "cg" gamma map (computer graphics),
with paper from the "upper" paper tray, and the image proportionally
scaled to fill the print area on the page.

.SH OPTIONS
.TP
\-a
Causes
.IR canonize
to attempt to determine the size of the image by using stat(2) to
find out the number of bytes in the file.  This option cannot be
used if the image is provided on the standard input.
.TP
\-h
indicates that the input image is 1024 pixels square.
.TP
\-s squaresize
sets the image width and height to the size given.
.TP
\-w filewidth
sets the image width to be
.IR filewidth
pixels.  By default the image is assumed to be 512 pixels wide.
.TP
\-n fileheight
specifies the height of the image in pixels.
By default the image is assumed to be 512 pixels wide.
.TP
\-g gammatype
Select the gamma correction map to apply to the image before printing.
There are three gamma compensation maps in the CLC500.  Canon
recommends the "cg" map for computer graphics images which have not
been gamma corrected.  The "rgb" gamma map is said to be designed
for images which have already been gamma corrected.  The "scan"
gamma map is the one used by the CLC500 when printing images
obtained from the built in scanner.
.TP
\-t trayname
selects the tray from which paper should be taken to
produce the print.  The options are "u" for the upper tray, "l" for
the lower tray, and "m" for manual feed.
.TP
\-C #copies
Specifies the number of prints of the image desired.
This number must be in the range 1-99.
.TP
\-q queuename
queue job to MDQS queue "queuename".  By default, the job is
queued to the queue "canon".
.TP
\-R dpi
Print image with dpi dots-per-inch on the output page.  This option disables
the automatic scaling of the image.
.TP
\-M xmag:ymag
Print the image with a magnification of "xmag" in the
X dimension and "ymag" in the y dimension.
.TP
\-X page_xoff
Specifies the offset of left side of the image from the left side of the
output page.
This option is available only when
.IR \-R
or
.IR \-M
have been specified, and are especially useful in conjunction with the
.IR \-m
option.
.TP
\-Y page_xoff
Specifies the distance from the top of the page to the top of the image.
This option is available only when
.IR \-R
or
.IR \-M
have been specified, and are especially useful in conjunction with the
.IR \-m
option.
.TP
\-N
Specifies the height of the image on the output page.
This option is available only when
.IR \-A
AutoScaling (on by default).
The image is scaled equally in the X and Y dimensions to make it fit the
available print area as closely as possible.
.IR \-R
or
.IR \-M
have been specified, and are especially useful in conjunction with the
.IR \-m
option.
.TP
\-W
Specifies the width of the image on the output page.
This option is available only when
.IR \-R
or
.IR \-M
have been specified, and are especially useful in conjunction with the
.IR \-m
option.
.TP
\-m
causes the image to be repeated accross the page.
.TP
\-v
Turn on debugging output.
.SH Notes
The Canon CLC500(tm) prints at 400dpi on the output page.  This results
in approximately 2550 by 3300 pixels on an 8.5 inch by 11 inch page. Images of
less than 1024 by 1024 pixels do not look especially pleasing when printed
using AutoScaling.  This is because the pixels become enlarged enough to be
annoying.

Because high resolution images occupy a substantial amount of disk space, it
is relatively easy to run the MDQS queue server out of disk space by queuing
many images at once.

.SH "SEE ALSO"
pix-fb(1), pix-ipu(1), IPU Programmer's Manual
.SH DIAGNOSTICS
If the
.IR -a
option is specified when the image is being redirected from the standard input
.IR canonize
will abort.
This avoids wasting paper printing an image using incorrect dimensions.
.SH AUTHOR
Lee A. Butler
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
