/*
 *			h/Cakefile
 */
#include "../Cakefile.defs"

#define PRODUCTS	*.h
#define SRCDIR	h
#define FILES	/**/
#define	SRCSUFF	.h
#define MANSECTION	5

/*
 *  There is nothing to compile.  The "inst-dist" rules should take
 *  all the headers and send them to distribution directory,
 *  on the master machine.  Otherwise, do nothing.
 */

all&:
	@echo "h:  all done"

/* Override the modes for the headers */
#undef	BINDIR
#undef	BINPERM
#define	BINDIR	INCLUDE_DIR
#define	BINPERM	LIBPERM

#include "../Cakefile.rules"
