/*
 *			libbu/Cakefile
 */
#define       CONFIGDEFS	LIBBU_CONFIG

#define SRCDIR	libbu
#define PRODUCTS	libbu.ARCH_SUF
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#define FILES	\
	badmagic bitv bomb \
	convert association \
	getopt hist ispar linebuf list \
	log magic malloc mappedfile memset \
	parallel parse printb ptbl semaphore \
	rb_create rb_delete rb_diag rb_extreme	\
	rb_free rb_insert rb_order_stats	\
	rb_rotate rb_search rb_walk		\
	vfont brlcad_path xdr lex \
	vls htond htonf units bu_tcl color cmd \
	cmdhist cmdhist_obj observer avs hook mro fopen_uniq hash

#define VERSION_VARIABLE	bu_version
#define LIBRARY_TITLE		"The BRL-CAD Utility Library"

#include "../Cakefile.lib"

#include "../Cakefile.rules"
