/*
 *			libbu/Cakefile
 */
#define SRCDIR	libbu
#define PRODUCTS	libbu.ARCH_SUF
#define	SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#define FILES	\
	badmagic bitv bomb \
	getopt ispar linebuf \
	log magic malloc memset \
	parallel printb ptbl semaphore \
	vls

#define VERSION_VARIABLE	bu_version
#define LIBRARY_TITLE		"The BRL-CAD Utility Library"

#include "../Cakefile.lib"

#include "../Cakefile.rules"
