/*
 *		libpng/Cakefile
 */

#define SRCDIR	libpng
#define PRODUCTS	libpng.ARCH_SUF
#define SRCSUFF	.c
#define MANSECTION	3

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc -lm -brtl -L../.libz.sp3 -lz
#endif

#define FILES png pngset pngget pngrutil pngtrans pngwutil \
	pngread pngrio pngwio pngwrite pngrtran \
	pngwtran pngmem pngerror pngpread

#define VERSION_VARIABLE	png_version
#define LIBRARY_TITLE		"PNG Reference Library"

#include "../Cakefile.lib"

#include "../Cakefile.rules"

