= AE(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
ae - Sets the view orientation for the _mged_ display by rotating the eye point about the center of the viewing cube. Without arguments, returns the current azimuth, elevation, and twist.

== SYNOPSIS

[source]
----
ae [ [-i]azimuth elevation [twist]]
----


[[description]]
== DESCRIPTION

Set the view orientation for the _mged_ display by rotating the eye point about the center of the viewing cube. The eye point is determined by the supplied azimuth and elevation angles (degrees). The _azimuth_ angle is measured in the _xy_ plane with the positive _x_ direction corresponding to an azimuth of 0°. Positive azimuth angles are measured counter-clockwise about the positive _z_ axis. Elevation angles are measured from the _xy_ plane with +90° corresponding to the positive _z_ direction and -90 corresponding to the negative _z_ direction. If an optional _twist_ angle is included, the view will be rotated about the viewing direction by the specified _twist_ angle. The _-i_ option results in the angles supplied being interpreted as increments. If no arguments are supplied, the command will return the current azimuth, elevation, and twist. See also the *view* command.


[[examples]]
== EXAMPLES

The examples show how to change views by entering azimuth and elevation angles, adding a twist angle, and having the angles supplied being treated as increments.

.Top view
[example]
====
mged>**ae -90 90**

====

.Right-hand side view
[example]
====
mged>**ae 270 0**

The view is from the right-hand side.

====

.View from a specific azimuth and elevation with a twist angle.
[example]
====
mged>**ae 35 25 10**

The view is from azimuth 35, elevation 25, with a view rotated by 10 degrees.

====

.The azimuth and elevation angles supplied are treated as increments.
[example]
====
mged>**ae -i 0 0 5**

Rotates the current view through 5 degrees about the viewing direction.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
