= APROPOS(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
apropos - Searches _mged_ command help and manual pages for keywords.

== SYNOPSIS

[source]
----
apropos [-k|-K] {keyword}
----


[[description]]
== DESCRIPTION

The *apropos* command searches _mged_ command manual pages and displays the
commands that match in ranked order.

By default, or with *-k*, *apropos* searches command names, synopses, and brief
descriptions. With *-K*, it searches the full text of the command manual pages.


[[examples]]
== EXAMPLES

.List commands having "region" in their names, synopses, or descriptions.
[example]
====
mged>**apropos region**




....

build_region eac edcodes edcomb em idents item lm r rcodes read_muves red
regdef regions reid remat summary wcodes whatid whichair whichid
	
....



====

.List commands whose full manual page text contains "boolean operations."
[example]
====
mged>**apropos -K "boolean operations"**

....

bev ev region facetize search npush comb r bigE nmg_fix_normals exists tol

....

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
