= E(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
E - Display objects in evaluated form.

== SYNOPSIS

[source]
----
E [-s] object [object ...]
----


[[description]]
== DESCRIPTION

The *E* command evaluates the specified object trees and displays a faceted
approximation of the resulting geometry. Unlike *draw* or *e*, which display
objects using the normal display-list pipeline, *E* shows the evaluated boolean
result. This is useful when checking what a tree actually resolves to, but it
is usually slower than ordinary drawing.

The *-s* option requests a slower, more accurate approximation.

Historically this command has also been referred to informally as "bigE".


[[examples]]
== EXAMPLES

.Display the evaluated result of a region tree.
[example]
====
mged> **E -s suspension.r**

Evaluates the booleans in _suspension.r_ and displays a more accurate faceted
approximation of the resulting volume.
====


[[see_also]]
== SEE ALSO

*draw*(nged), *e*(nged), *ev*(nged)


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
