= BREP INFO(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED User Commands

== NAME
brep info - Report information about components of a specified BRep solid.

== SYNOPSIS

[source]
----
brep {obj}info [C2|C3|E|F|L|SB|T|TB|V] [arguments]
----


[[description]]
== DESCRIPTION

If _obj_ is not a brep object, then *brep* will quit and report that fact. Otherwise, it prints a textual description of the requested information. With not arguments supplied, a summary of data present in the brep object is printed. Otherwise, more detailed information about specified components will be reported.


Return information for one or more 2D parametric space geometric curves.




Return information for one or more 3D geometric curves.




Return information for one or more topological 3D edges.




Return information for one or more topological faces.




Return information for one or more 2D parametric space topological trimming loops.




Return information for one or more surfaces.




Return information for one or more piecewise Bezier surfaces.




Return information for one or more 2D parametric space topological trims.




Return information for one or more 2D piecewise Bezier trims.




Return information for one or more 3D vertices.




[[examples]]
== EXAMPLES

.Object Summary
[example]
====
mged>**brep Brep_1.s info**


....

Brep_1.s -- Valid: YES, Solid: YES, Plate mode: NO
faces:     597
surfaces:  597
edges:     1475
3d curve:  1475
vertices:  976
loops:     715
trims:     3056
2d curves: 3056
        
....



Reports counts for the various object types, as well as object level info about solidity, validity and plate mode status.

====

.First Object Face
[example]
====
mged>**brep Brep_1.s info F 1**


....

face[ 1]: surface(1) reverse(0) loops(1)
	loop[ 1]: type(outer) 4 trims(4, 5, 6, 7)
		trim[ 4]: edge( 1) v0( 2) v1( 1) tolerance(0.001, 0.001)
			type(mated   -u iso) rev3d(0) 2d_curve(4)
			domain(0, 1) start(1.62, 3.14159) end(1.62, 4.43206e-09)
			surface points start(32.4121, 148.588, 55) end(20.4121, 148.588, 55)
		trim[ 5]: edge( 3) v0( 1) v1( 3) tolerance(0.001, 0.001)
			type(mated   -south side iso) rev3d(0) 2d_curve(5)
			domain(0, 1) start(1.62, 4.43206e-09) end(16.62, 4.43206e-09)
			surface points start(20.4121, 148.588, 55) end(20.4121, 148.588, 40)
		trim[ 6]: edge( 4) v0( 3) v1( 4) tolerance(0.001, 0.001)
			type(mated   -u iso) rev3d(1) 2d_curve(6)
			domain(0, 1) start(16.62, 4.43206e-09) end(16.62, 3.14159)
			surface points start(20.4121, 148.588, 40) end(32.4121, 148.588, 40)
		trim[ 7]: edge( 5) v0( 4) v1( 2) tolerance(0.001, 0.001)
			type(mated   -north side iso) rev3d(1) 2d_curve(7)
			domain(0, 1) start(16.62, 3.14159) end(1.62, 3.14159)
			surface points start(32.4121, 148.588, 40) end(32.4121, 148.588, 55)
        
....



Reports information about the consituent components that make up the topological face.

====

.First Surface
[example]
====
mged>**brep Brep_1.s info S 1**


....

surface[ 1]: ON_NurbsSurface u(0, 18.24) v(0, 3.14159)
NURBS form of Surface:
ON_NurbsSurface dim = 3 is_rat = 1
        order = 2 X 3 cv_count = 2 X 5
Knot Vector 0 ( 2 knots )
index                     value  mult       delta
    0                        0     1
    1       18.239999999999998     1       18.24
Knot Vector 1 ( 6 knots )
index                     value  mult       delta
    0                        0     2
    2       1.5707963267949001     2       1.571
    4         3.14159265358979     2       1.571
Control Points  10 rational points
  index               value
  CV[ 0][ 0] [20.412069387140399, 148.58793061285999, 56.619999999999997, 1] = (20.412069387140399, 148.58793061285999, 56.619999999999997)
  CV[ 0][ 1] [14.433512681697321, 109.31017402594885, 40.036385950782346, 0.70710678118654802] = (20.412069387140399, 154.58793061285999, 56.619999999999997)
  CV[ 0][ 2] [26.412069387140399, 154.58793061285999, 56.619999999999997, 1] = (26.412069387140399, 154.58793061285999, 56.619999999999997)
  CV[ 0][ 3] [22.918794055935898, 109.31017402594885, 40.036385950782346, 0.70710678118654802] = (32.412069387140399, 154.58793061285999, 56.619999999999997)
  CV[ 0][ 4] [32.412069387140399, 148.58793061285999, 56.619999999999997, 1] = (32.412069387140399, 148.58793061285999, 56.619999999999997)

  CV[ 1][ 0] [20.412069387140399, 148.58793061285999, 38.380000000000003, 1] = (20.412069387140399, 148.58793061285999, 38.380000000000003)
  CV[ 1][ 1] [14.433512681697321, 109.31017402594885, 27.138758261939714, 0.70710678118654802] = (20.412069387140399, 154.58793061285999, 38.380000000000003)
  CV[ 1][ 2] [26.412069387140399, 154.58793061285999, 38.380000000000003, 1] = (26.412069387140399, 154.58793061285999, 38.380000000000003)
  CV[ 1][ 3] [22.918794055935898, 109.31017402594885, 27.138758261939714, 0.70710678118654802] = (32.412069387140399, 154.58793061285999, 38.380000000000003)
  CV[ 1][ 4] [32.412069387140399, 148.58793061285999, 38.380000000000003, 1] = (32.412069387140399, 148.58793061285999, 38.380000000000003)
        
....



Detailed information on the geometric data defining the surface.

====

.Multiple loops
[example]
====
mged>**brep Brep_1.s info L 1,5,12**


....

loop[1] on face 1 with 4 trims
trims: 4,5,6,7

loop[5] on face 5 with 4 trims
trims: 20,21,22,23

loop[12] on face 12 with 4 trims
trims: 48,49,50,51
        
....



Report the trims making up multiple loops.

====


[[author]]
== AUTHOR

BRLCAD-TEAM


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
