= BREP SELECTION(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED User Commands

== NAME
brep selection - Operate on components of a specified BRep solid.

== SYNOPSIS

[source]
----
brep {obj} selection {append|translate} {selection_name} {startx starty startz dirx diry dirz}
----


[[description]]
== DESCRIPTION

If _obj_ is not a brep object, then *brep* will quit and report that fact. Otherwise, attempt to operate on the selected components. This command should be viewed as dangerous and experimental - it can change BRep data, but it does not guarantee preservation of solidity while doing so - if edge curve points are moved, for example, an otherwise solid BRep object will no longer be solid.


Translate a surface control vertex


[[examples]]
== EXAMPLES

.Append a ray-defined selection.
[example]
====
mged> **brep hull.brep selection append leading_edge 0 0 0 0 0 1**

Creates or extends the _leading_edge_ selection on _hull.brep_ using a ray that starts at the model origin and points in the positive Z direction.

====



[[author]]
== AUTHOR

BRLCAD-TEAM


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
