= COPYEVAL(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
copyeval - Creates a new primitive object called __new_ primitive__ by applying the transformation matrices accumulated along the __path_to_old_primitive__ to the leaf primitive shape object at the end of the path and saving the result under the name __new_ primitive__.

== SYNOPSIS

[source]
----
copyeval {new_primitive path_to_old_primitive}
----


[[description]]
== DESCRIPTION

Objects in a _BRL-CAD_ model are stored as Boolean trees (combinations), with the members being primitive shapes or other Boolean trees. Each member has a transformation matrix associated with it. This arrangement allows a primitive to be a member of a combination, and that combination may be a member of another combination, and so on. When a combination is displayed, the transformation matrices are applied to its members and passed down through the combinations to the leaf (primitive shape) level. The accumulated transformation matrix is then applied to the primitive before it is drawn on the screen. The *copyeval* command creates a new primitive object called __new_ primitive__ by applying the transformation matrices accumulated along the __path_to_old_primitive__ to the leaf primitive shape object at the end of the path and saving the result under the name __new_ primitive.__ The __path_to_old_ primitive__ must be a legitimate path ending with a primitive shape.


[[examples]]
== EXAMPLES

The example shows the use of the *copyeval* command to create a new primitive by applying the transformation matrices along the path to the old primitive.

.Create a new primitive object by applying the transformation matrices along the path to the old primitive.
[example]
====
mged>**copyeval shapeb comb1/comb2/comb3/shapea**

Creates _shapeb_ from _shapea_ by applying the accumulated transformation matrices from the path comb1/comb2/comb3.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
