= EDCODES(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME

edcodes - Puts the user into an editor to edit a file that has been
filled with the ident, air code, material code, LOS, and name of all
the regions in the specified objects.

== SYNOPSIS

[source]
----
edcodes [-i] [-n] [-r] [-E editor] {object(s)}
----


[[description]]
== DESCRIPTION

Puts the user into an editor to edit a file that has been filled with
the ident, air code, material code, LOS, and name of all the regions
in the specified objects. The user may then modify the entries (except
for the names).

The editor used is whatever the user has set in the environment
variable _EDITOR_. If _EDITOR_ is not set, then your system default is
used. The *-E* option can override that editor choice for the current
command invocation.

The file is sorted by order of appearance by default. The *-r* flag
sorts regions into alphabetical order using the full path. The *-i*
flag sorts by ident. The *-n* flag skips the editor step and reports
only the region names encountered below the specified objects.


[[examples]]
== EXAMPLES

The example shows the use of the *edcodes* command for editing the
region codes in the files of two objects.

.Edit the region codes of two objects.

[example]
====

mged> **edcodes object1 object2**::

Enables the user to edit the region codes for all regions below
_object1_ and _object2_.


====

[[author]]
== AUTHOR

BRL-CAD Team

[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
