= EDITIT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
editit - open a file in an external text editor

== SYNOPSIS

[source]
----
editit [opts] <filename>
editit -f <file>
editit -e <editstring> <filename>
----


[[description]]
== DESCRIPTION

The *editit* command opens a file in an external text editor. The editor used is determined by the current environment (typically the `EDITOR` environment variable or a system default).

The file to edit can be specified as a positional argument or via the `-f` option. Only one file specification is allowed per invocation.

=== Options

*-f file*::
Specify the file to edit. Equivalent to providing `filename` as a positional argument.

*-e editstring*::
Specify an edit string to pass to the editor (deprecated; prefer specifying the editor via the environment).

[[examples]]
== EXAMPLES

.Open a file in the editor
[example]
====
mged> **editit /tmp/myconfig.tcl**

Opens `/tmp/myconfig.tcl` in the system's default text editor.
====

.Use the -f flag
[example]
====
mged> **editit -f /tmp/notes.txt**

Opens `/tmp/notes.txt` using the `-f` flag form.
====

[[see_also]]
== SEE ALSO

*saveview*(nged)


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
