= EDIT TRANSLATE(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
edit translate - Translates the positions of _object_ s, using coordinates, offsets, and objects as reference points.

== SYNOPSIS

[source]
----
edit translate [] <to> object... \
     \
    
 [-n] -k {<from_object> | <from_position>}
 [-n] [-a | -r] {<to_object> | <to_position>}
 [{<coords>} | { [ -x {x | <x-obj>}] [ -y {y | <y-obj>}] [ -z {z | <z-obj>}]}]
  [path/] object [<offset_distance>]
 x [ y [z]]
----


[[description]]
== DESCRIPTION

Used to move one or more instances of primitive or combination objects. The positions of _object_'s are translated from _from_ to _to_.

See the *edit* command's manual for more information.


[[examples]]
== EXAMPLES

.A not particularly useful demonstration of the command's capabilities.
[example]
====

mged> **edit translate -k 0 0 0 -a . obj1 obj2 obj3 obj4 obj5**::
Moves every instance of each obj[1-5] in the same direction and by the same distance it is from the origin. The result is a (rather inflexible) "explosion" of the objects from the origin.



====

.Move several objects together.
[example]
====

mged> **edit translate -a -z obj1 obj2 obj3 obj4 obj5**::
The _from_ point defaults to the bounding box center of the first target _object_, which is obj2. Every instance of objects obj2 - obj5 is moved _from_ obj2 _to_ the z-axis of obj1. If the z-coordinate of _from_ was 7, and the z-coordinate of _to_ was 5, then each object would move -2 units in the z-axis.



====

.Align several objects to the same point on an axis.
[example]
====

mged> **edit translate -k . -a -z obj1 obj2 obj3 obj4 obj5**::
Sets the elevation of obj[2-5] to the elevation of obj1. Each object uses its own bounding box center as the _from_ point in an operation that moves _to_ the bounding box center of obj1.



====

.Move several objects to the same point.
[example]
====

mged> **edit translate -k . -a obj1 obj2 obj3 obj4 obj5**::
Each object uses its own bounding box center as the _from_ point in an operation that moves _to_ the bounding box center of obj1. All _object_ s end up centered on obj2.



====

.Explicitly set the z-axis of an obj.
[example]
====

mged> **edit translate -a -z 7.8 obj**::
Moves obj _from_ its bounding box center _to_ 7.8 on the z-axis.



====

.Move several objects from their own natural origins to their own bounding box centers.
[example]
====

mged> **edit translate -n -k . -a . obj1 obj2 obj3**::
The _object_ s are moved from their own natural origins to their own bounding box centers.



====

.Set the z-axis of the center of one object to the z-axis of the natural origin of another object.
[example]
====

mged> **edit translate -n -a -z obj2/obj3 obj1**::
Moves obj1 up or down _from_ the elevation of its bounding box center _to_ the apparent elevation of the natural origin of the instance of obj3 in obj2.



====

.Same result as above, but moving _from_ the natural origin of obj1 rather than its bounding box center.
[example]
====

mged> **edit translate -n -k obj1 -n -a -z obj2/obj3 obj1**::



mged> **edit translate -n -k . -n -a -z obj2/obj3 obj1**::




====

.The use of _object_ paths and individual coordinate specifiers.
[example]
====

mged> **edit translate -a -x 8 -z 42 obj1/obj2/obj3**::
Moves the instance of ob3 in obj2 _from_ the apparent bounding box center of obj3 _as offset by_ obj1/obj2, _to_ x=8, z=42, without moving in the y-axis. Note that this is not the same as *-a 8 0 42*. Also note that only the matrix of obj2 is modified. No matter the length of the path, only the combination containing the actual object being translated will be modified. If the only component of the path were obj3, then if obj3 were a primitive it would be modified or if obj3 were a combination the matrices of all objects it holds would be modified.



====

.Translations using relative positions.
[example]
====

mged> **edit translate -k obj1 -r -z 5 obj2**::



mged> **edit translate -a -z obj1 0 0 5 obj2**::



These commands perform the same function. The z-coordinate of the bounding box center of obj2 is moved to the z-coordinate of the bounding box center of obj1 _plus 5 units_.



====

.This example breaks down a particularly complex translation.
[example]
====

mged> **edit translate -k -x c/obj1 1.5 -y c/obj2 0 3 -z c/obj3 0 0 10 -a -x b/c/obj4 2 -y b/c/obj5 0 4 -z b/c/obj6 0 0 20 obj7 obj8**::
Every use of *translate* involves a _from_ point and a _to_ point. One of the more flexible features of the edit commands is the capability to use an object and an offset to specify each axis of these points individually. The command in this example can be broken down to three simpler commands, in order to ease comprehension:


mged> **edit translate -k -x c/obj1 1.5 -a -x b/c/obj4 2 obj7 obj8**::



mged> **edit translate -k -y c/obj2 0 3 -a -y b/c/obj5 0 4 obj7 obj8**::



mged> **edit translate -k -z c/obj3 0 0 10 -a -z b/c/obj6 0 0 20 obj7 obj8**::
In the first shortened command, the _from_ point is set to the x-coordinate of the apparent point of the bounding box center of the instance of obj1 in combination c, _plus 1.5_. The _to_ point is set to the x-coordinate of the apparent point of the bounding box center of the specific instance of obj4 in combination c in combination b, _plus 2_. Both obj7 and obj8 move from _from_ to _to_, ending up the same relative distance from each other.The other shortened commands are similar.
+
By splitting the larger command, an interesting detail was revealed. In the larger command, every point was set explicitly, so none defaulted. In the first shortened command, the _y_ and _z_ _from_ values default to the bounding box center of obj7. Since the _y_ and _z_ _to_ values default to the values set by _from_, neither obj7 nor obj8 will move in the _y_ or _z_ axes.



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
