= FRACTURE(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
fracture - Creates a new NMG shape for every face in the specified __NMG_shape__.

== SYNOPSIS

[source]
----
fracture {NMG_shape} [prefix]
----


[[description]]
== DESCRIPTION

Creates a new NMG shape for every face in the specified __NMG_shape__. The new shapes will be named by adding an underscore and a number to the _prefix_. If no _prefix_ is specified, then the __NMG_shape__ name provided is used in place of the _prefix_.


[[examples]]
== EXAMPLES

The example shows the use of the *fracture* command to create a new NMG shape with a given prefix for every face in the specified __NMG _shape__.

.Create an NMG shape with a specific prefix for every face in a specified NMG shape.
[example]
====

mged> **fracture shape1.nmg f**::
Creates a series of NMG shapes named f_#, one for each face in _shape1.nmg_ .



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
