= GARBAGE_COLLECT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
garbage_collect - Eliminates unused space in a BRL-CAD database file.

== SYNOPSIS

[source]
----
garbage_collect [-h | --help]
garbage_collect [-c | --confirm]
----


[[description]]
== DESCRIPTION

Eliminates unused space in a BRL-CAD database file.

The operation is intentionally guarded: the actual rewrite is performed only
when *-c* or *--confirm* is supplied. Invoking the command with no arguments
prints the help text.


[[options]]
== OPTIONS

*-h*, *--help*::
Print help and exit.

*-c*, *--confirm*::
Execute the garbage-collection operation.


[[examples]]
== EXAMPLES

The example shows the use of the *garbage_collect* command to delete unused space in a BRL-CAD database file.

.Delete unused space in a BRL-CAD database file.
[example]
====

mged> **garbage_collect**:: -c
Cleans out unused space in the database.



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
