= HELPLIB(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
helplib - Returns a list of available _library_ commands along with a one-line usage message for each. If a command is supplied as an argument, the one-line usage message for that command is returned.

== SYNOPSIS

[source]
----
helplib [command]
----


[[description]]
== DESCRIPTION

Returns a list of available _library_ commands along with a one-line usage message for each. If a command is supplied as an argument, the one-line usage message for that command is returned. The *help, helpdevel, ?, ?devel,* and *?lib* commands provide additional information on available commands.


[[examples]]
== EXAMPLES

The example shows the use of the *helplib* command to display a one-line usage message for a specific library command.

.Display a one-line usage message for a specific library command.
[example]
====

mged> **helplib mat_trn**::
Displays a one-line usage message for the *mat_trn* command.



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
