= HELPDEVEL(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
helpdevel - Returns a list of available _developer_ commands along with a one-line usage message for each. If a command is supplied as an argument, the one-line usage message for that command is returned.

== SYNOPSIS

[source]
----
helpdevel [command]
----


[[description]]
== DESCRIPTION

Returns a list of available _developer_ commands along with a one-line usage message for each. If a command is supplied as an argument, the one-line usage message for that command is returned. The *help, helplib, ?, ?devel,* and *?lib* commands provide additional information on available commands.


[[examples]]
== EXAMPLES

The example shows the use of the *helpdevel* command to display a one-line usage message for a specified developer command.

.Display a one-line usage message for a specified developer command.
[example]
====

mged> **helpdevel winset**::
Displays a one-line usage message for the *winset* command.



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
