= INSIDE(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
inside - Creates a new shape that is _inside_ an existing shape.

== SYNOPSIS

[source]
----
inside [outside_shape_name new_inside_shape_name] {parameters}
----


[[description]]
== DESCRIPTION

Creates a new shape that is _inside_ an existing shape. This command is typically used to create an _inside_ shape that can be subtracted from the original shape to produce a hollow shell. The command is typically used with no arguments, and it prompts the user for all needed information; however, all the parameters may be supplied on the command line. If MGED is in primitive edit mode when the *inside* command is issued, then the shape currently being edited will be used as the __outside_shape__. Similarly, if MGED is in matrix edit mode when the *inside* command is executed, then the current key shape will be used as the outside shape.


[[examples]]
== EXAMPLES

The first example shows the use of the *inside* command to create a shape inside another shape such that all its faces are 1 unit from the corresponding faces of the outside shape. The second example shows the use of the *inside* command to create a shape inside the current key shape or the shape currently being edited. The faces of the new shape will be 1 unit from the corresponding faces of the current outside shape.

.Create a shape inside of an existing shape.
[example]
====

mged> **inside out_arb in_arb 1 1 1 1 1 1**::
Creates a shape named __in_arb__ such that each face is 1 unit from the corresponding face in __out_arb__.



====

.Creates a shape inside of the current key shape or the shape being edited.
[example]
====
mged>**inside in_arb 1 1 1 1 1 1**

Creates a shape named __in_arb__ such that each face is 1 unit from the corresponding face in the current key shape or the shape currently being edited.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
