= JOURNAL(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
journal - Starts or stops the journaling of MGED commands to a file.

== SYNOPSIS

[source]
----
journal [-d] [journal_file_name]
----


[[description]]
== DESCRIPTION

Starts or stops the journaling of MGED commands to a file. If executed with no arguments, the command stops journaling. If __journal_file_name__ is provided, that file will become the recipient of the journaling. If a _-d_ option is also provided, the journaling will include the delays between commands. Journaling is off by default.


[[examples]]
== EXAMPLES

The example shows the use of the *journal* command to start the journaling of a specified file.

.Start the journaling of a specified file.
[example]
====

mged> **journal journal_file**::
Starts journaling to __journal_file__.



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
