= KILLALL(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
killall - Deletes the specified _objects_ from the current database and removes all references to them from all combinations in the database.

== SYNOPSIS

[source]
----
killall [-n] {objects}
----


[[description]]
== DESCRIPTION

Deletes the specified _objects_ from the current database and removes all references to them from all combinations in the database. Note that the _objects_ are killed immediately unless the *-n* flag is passed. The *-n* flag causes the command to return a string of the objects that would be killed in a scriptable list format without actually killing them. See also the *killrefs* command.

*Use this command with caution.* Killed objects cannot be recovered so *keep* a backup.


[[examples]]
== EXAMPLES

The example shows the use of the *killall* command to delete specified objects and to remove all references to them from the database.

.Delete specified objects and all references to them from the database.
[example]
====

mged> **killall group1 region2 shapeb**::
Deletes _group1_, _region2_, and _shapeb_ and removes all references to these objects from the database.



====


[[see_also]]
== SEE ALSO

*kill*(nged) *killtree*(nged)


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
