= LABELVERT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
labelvert - Labels the vertices of the indicated _objects_ with their coordinate values in the MGED display window.

== SYNOPSIS

[source]
----
labelvert {objects}
----


[[description]]
== DESCRIPTION

Labels the vertices of the indicated _objects_ with their coordinate values in the MGED display window. The _objects_ must have already been displayed using *e, E, ev, B*, or any other command that results in the display of an object.


[[examples]]
== EXAMPLES

The example shows the use of the *labelvert* command to label the vertices of a designated shape with their coordinate values.

.Label the vertices of a particular shape with their coordinate values.
[example]
====

mged> **labelvert shapeb**::
Places coordinate values in the display near the vertices of _shapeb_ .



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
