= LC(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
lc - Lists codes (i.e. region attributes) 'region_id', 'material_id', 'los', 'aircode', 'region name', 'region parent' within a group or combination.

== SYNOPSIS

[source]
----
lc [-d|-m|-s] [-r] [-z] [-0|-1|-2|-3|-4|-5] [-f {fileName}] {groupName}
----


[[description]]
== DESCRIPTION

The 'lc' command lists a set of codes (i.e. attributes) of regions within a group/combination. Listed in columns are the following: 'region_id', 'material_id', 'los', 'aircode', 'region name', 'region parent'. If a value is unset, it is reported as '--'.


[[options]]
== OPTIONS


*-d*::
Specifies to list only regions with shared 'region_id' values.


*-m*::
Specifies to list only regions with shared 'region_id' values where one or more of the objects in the set of objects defined by shared 'region_id' value reports a different 'material_id', 'aircode' and/or 'los' values. Essentially, this allows users to quickly find and resolve inconsistent codes (i.e, id settings) within a 'region_id' group.


*-s*::
Specifies to list only one region with each combination of 'region_id', 'material_id', 'los', and 'aircode'.


*-r*::
Remove regions from the list in which their parent is a region and the region is subtracted within the parent. The '-r' option can be combined with any other option.


*-z*::
Specifies descending (z-a) sort order.


*-0*
*-1*
*-2*
*-3*
*-4*
*-5*::
Selects the sort key. *-1* through *-5* sort by region ID, material ID, LOS,
air code, and region name respectively; *-1* is the default. *-0* keeps the
stored order. The duplicate-filtering options *-d*, *-m*, and *-s* may still
sort records as needed to detect matching codes. The displayed region-parent
column is not a sort-key option.


*-f FileName*::
Identifies output should be to a file and specifies the file name. If the path is not included as part of the 'FileName' the path will be the 'current directory'.

[[examples]]
== EXAMPLES

.Find regions that share a region id but disagree on other code settings.
[example]
====
mged>**lc -m vehicle.c**

Lists only the regions below _vehicle.c_ that share a region id while disagreeing on material, LOS, or aircode values, which is useful before normalizing region attributes with *edcodes*.
====



[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
