= MAN(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
man - Opens the graphical man page viewer.

== SYNOPSIS

[source]
----
man [cmdname]
man [-g | --gui] [cmdname]
man [--no-gui] [-L language] [-S section] [cmdname]
man [-k|-K] keyword
man [-h | --help]
----


[[description]]
== DESCRIPTION

Launches the BRL-CAD manual page viewer for the specified command name.

By default, *man* starts the GUI viewer when possible. It can also force GUI or
non-GUI mode and can select a manual language or manual section before
launching `brlman`.

The *-k* and *-K* options search manual pages instead of opening a named page.
The *-k* option searches names, synopses, and brief descriptions; *-K*
searches the full manual page text.


[[options]]
== OPTIONS

*-h*, *--help*::
Print help and exit.

*-g*, *--gui*::
Force use of the graphical manual page viewer.

*--no-gui*::
Force command-line viewer mode.

*-L*, *--language* _lang_::
Select the manual language to request from `brlman`.

*-S*, *--section* _section_::
Select the manual section to request from `brlman`.

*-k* _keyword_::
Search manual page names, synopses, and brief descriptions.

*-K* _keyword_::
Search the full manual page text.


[[examples]]
== EXAMPLES

.Open the *view* manual page in the default viewer mode.
[example]
====
mged> **man view**

Launches the BRL-CAD manual page viewer on the `view` command page.

====

.Open a specific section in command-line mode.
[example]
====
mged> **man --no-gui -S 1 rt**

Launches `brlman` in non-GUI mode and requests section `1` for `rt`.

====

.Search command manual pages.
[example]
====
mged> **man -K "boolean operations"**

Opens the graphical manual page viewer with ranked full-text results.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2016-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
