= ATTR(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
material - Used to create, change, retrieve, assign, import, or view materials and their properties.

== SYNOPSIS

[source]
----
material assign {object_name} {material_name}
----

[source]
----
material create {object_name} {material_name}
----

[source]
----
material destroy {material_object}
----

[source]
----
material get {material_object} {name | parent | source}
----

[source]
----
material get {material_object} {physical | mechanical | optical | thermal} {property_name}
----

[source]
----
material set {material_object} {name | parent | source} {property_value}
----

[source]
----
material set {material_object} {physical | mechanical | optical | thermal} {property_name} {property_value}
----

[source]
----
material remove {material_object} {name | parent | source}
----

[source]
----
material remove {material_object} {physical | mechanical | optical | thermal} {property_name}
----

[source]
----
material import (--id | --name) {file_name}
----


[[description]]
== DESCRIPTION

Used to create, change, retrieve, assign, import, or view materials and their properties. Property, property-group, and material-object names are case-sensitive and should not contain whitespace.

A newly formed material will have a minimum of the following data set on creation:




* name

Material objects have a name (separate from the database object name), parent value, and source value. All three are variable-length strings.

In addition to the three variable length string properties, material objects also contain four key-value lists used for storing additional material information:


* physical
* mechanical
* optical
* thermal




[[attr_subcommands]]
== SUB-COMMANDS


*assign*::
Set the material_name property of the specified object to the specified material. Operates similarly to attr set.


*create*::
Initialize a new material and set its name property to the specified value.


*destroy*::
Destroy the material object.


*get*::
Retrieve a direct property (name, parent, or source), or a named property from one of the four material property groups.


*import*::
Import a density file's entries into material objects. Exactly one naming mode is required: --id creates database object names from the density-table IDs (prefixed with `matl`), while --name uses the density-table material names.


*remove*::
Remove a material property from the object. For name, parent, and source this clears the direct property.


*set*::
Set a direct property or a property in one of the material's four material groups.




[[examples]]
== EXAMPLES

The examples demonstrate the use of the *material* command and subcommands.

.Import a density file to material objects.
[example]
====

mged> **material import --id .density**::
Imports the density file _.density_ to material objects and names the objects based on the file's ids.



====

.Get the density attribute of the material "copper" within the physical property group.
[example]
====

mged> **material get copper physical density**::
Outputs the value of density.



====


[[author]]
== AUTHOR

BRL-CAD Team


[[copyright]]
== COPYRIGHT

This software is Copyright (c) 2008-2026 United States Government as represented by the U.S. Army Research Laboratory.


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
