= NMG_SIMPLIFY(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
nmg_simplify - Attempts to convert an existing nmg_shape to a simpler primitive shape type.

== SYNOPSIS

[source]
----
nmg_simplify [[arb] | [tgc] | [poly]] {new_shape nmg_shape}
----


[[description]]
== DESCRIPTION

Attempts to convert an existing nmg_shape to a simpler primitive shape type. The user may specify which type to attempt by including _arb, tgc,_ or _poly_ on the command line. If no shape type is specified, all will be attempted in the above order. If _tgc_ is specified, the code will attempt to determine if the __nmg_shape__ is an approximation of a TGC shape.


[[examples]]
== EXAMPLES

The example shows the use of the *nmg_simplify* command to convert an existing nmg shape to a polysolid.

.Convert an existing shape to a polysolid.
[example]
====
mged>**nmg_simplify poly shapea.poly shapea.nmg**

Converts the nmg shape named _shapea.nmg_ to a polysolid named _shapea.poly_.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
