= OED(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
oed - Places MGED directly into the matrix edit mode.

== SYNOPSIS

[source]
----
oed {path_lhs} [{path_rhs}]
----


[[description]]
== DESCRIPTION

Places MGED directly into matrix edit mode.

When only __path_lhs__ is specified, it is the complete path to the
object being edited. The matrix immediately above its final component is
selected, and the center of that object's bounding box is used as the
editing keypoint.

When __path_rhs__ is specified, it must be a path ending in a primitive
shape, and __path_lhs__ must be a path to a combination that includes the
first component of __path_rhs__ as one of its members. The edited matrix
is the matrix between the final component of __path_lhs__ and the first
component of __path_rhs__. The final component of __path_rhs__ supplies
the keypoint during object editing.

Note that for scripting the object to be edited must be in view so a *B* or *draw* must be used on the object before using the *oed* command.


[[examples]]
== EXAMPLES

The examples show both ways to place MGED into matrix edit mode.

.Place MGED in matrix edit mode.
[example]
====
mged>**oed group1/group2 region1/shapea**

Places MGED into matrix edit mode, editing the matrix in _group2_ that corresponds to _region1_, using _shapea_ as the reference shape.

====

.Use an object's bounding-box center as the keypoint.
[example]
====
mged>**oed group1/group2/region1**

Places MGED into matrix edit mode, editing the matrix above _region1_ and
using the center of _region1_'s bounding box as the keypoint.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
