= OPENDB(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
opendb - Closes the current database file and opens _database.g_.

== SYNOPSIS

[source]
----
opendb [-f] [database.g]
----


[[description]]
== DESCRIPTION

Closes the current database file and opens _database.g_. If _database.g_ is not found, the user is prompted to create a new database of that name. If _database.g_ is not specified on the command line, the name of the current database file is returned.

If the -f option is specified and the database.g is a v4 geometry database, the file will be read with a flipped binary endianness encoding. This is useful for binary-incompatible v4 geometry files that were created on a different platform type.

Binary-incompatible v4 geometry database files that can be auto-detected will be automatically converted if all resulting matrices are valid.

The *opendb* command will look in the current working directory for the file. If the file is in another directory, use the relative or full path to the file or use the *pwd* and *cd* commands to navigate to the file's directory.


[[examples]]
== EXAMPLES

The first example shows the use of the *opendb* command to close the current database file and open the one specified. The second example shows the use of the command with no database name, which returns the name of the current database file.

.Close the current database and open another one.
[example]
====
mged>**opendb model.g**

Closes the current database file and opens _model.g_.

====

.Return the name of the current database file.
[example]
====
mged>**opendb**

Returns the name of the current database file.

====

.Open and upgrade a binary-incompatible v4 file.
[example]
====



....

mged> opendb -f model.g
mged> dbupgrade
    
....



Closes any currently open database and opens _model.g_ as a binary-incompatible v4 geometry database.

====

.Open a database using the full path to the file.
[example]
====



....

  mged> opendb C:/cad_work/model.g
    
....



Closes any currently open database and opens _model.g_ located at C:\cad_work\.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
