= PIPE_PREPEND_PNT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
pipe_prepend_pnt - Insert a control point at the beginning of a PIPE primitive.

== SYNOPSIS

[source]
----
pipe_prepend_pnt pipe {x y z}
----


[[description]]
== DESCRIPTION

The *pipe_prepend_pnt* command inserts a control point at the beginning of the
specified PIPE primitive.

The point argument is interpreted in the current view. The command preserves the
depth of the existing first point and uses the supplied view-space position to
compute the new model-space location.

The alternate command name *mouse_prepend_pipe_pnt* is also available.


[[examples]]
== EXAMPLES

.Add a new point at the beginning of a pipe.
[example]
====
mged> **pipe_prepend_pnt fuel_line.s {90 40 0}**

Adds a new leading PIPE point to _fuel_line.s_ using the current view for
placement.

====


[[see_also]]
== SEE ALSO

*mouse_prepend_pipe_pnt*(nged), *pipe_append_pnt*(nged), *pipe_move_pnt*(nged)


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
