= PLOT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
plot - Creates a UNIX plot of the current MGED display.

== SYNOPSIS

[source]
----
plot [-float] [-zclip] [-2d] [-grid] [output_file] [filter]
----


[[description]]
== DESCRIPTION

Creates a UNIX plot of the current MGED display. If an __output_file__ is specified, the plot is stored in that file. If a _filter_ is specified, the output is sent to that _filter_. The *-float* option requests a plot file with real numbers rather than integers. The *-zclip* option requests that the plot be clipped to the viewing cube in the Z-direction. The *-2d* option requests a two-dimensional plot (the default is 3D). The *-grid* option is intended to include a grid in the plot, but is currently not implemented. This command does not use the _dm-plot_ display manager. The *pl* command performs the same function, but does use the _dm-plot_ display manager.


[[examples]]
== EXAMPLES

The example shows the use of the *plot* command to create a UNIX plot of the current MGED display and pipe the results to the specified command.

.Create a UNIX plot of the current MGED display and send the results to a specified command.
[example]
====
mged>plot -float | pldebug

Creates a UNIX plot of the current MGED display and pipe the results to the *pldebug* command.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
