= PLOT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
plot - Creates a UNIX plot of the current MGED display.

== SYNOPSIS

[source]
----
plot [-2|-3] [-f] [-g] [-z] output_file
plot [-2|-3] [-f] [-g] [-z] | filter [filter_argument ...]
----


[[description]]
== DESCRIPTION

Creates a UNIX plot of the current MGED display. If an __output_file__ is
specified, the plot is stored in that file. If the first output word is `|`,
the remaining words form a filter command and the plot is written to its
standard input. The *-f* option requests a plot file with real numbers rather
than integers. The *-z* (or *-Z*) option requests that the plot be clipped to
the viewing cube in the Z-direction. The *-2* option requests a two-dimensional
plot; *-3* explicitly requests the default three-dimensional plot. The *-g*
option is accepted but grid output is not implemented. This command does not
use the _dm-plot_ display manager. The *pl* command performs the same function,
but does use the _dm-plot_ display manager. The dimension options *-2* and
*-3* are mutually exclusive.


[[examples]]
== EXAMPLES

The example shows the use of the *plot* command to create a UNIX plot of the current MGED display and pipe the results to the specified command.

.Create a UNIX plot of the current MGED display and send the results to a specified command.
[example]
====
mged>plot -f | pldebug

Creates a UNIX plot of the current MGED display and pipe the results to the *pldebug* command.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
