= POSTSCRIPT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
postscript - Temporarily attaches the _Postscript_ display manager and outputs the current MGED display to the specified __output_file__ in _PostScript_ format.

== SYNOPSIS

[source]
----
postscript [-a author] [-b] [-c r/g/b] [-f font] [-s size] [-t title] [-x offset] [-y offset] output_file
----


[[description]]
== DESCRIPTION

Temporarily attaches the _PostScript_ display manager and outputs the current
MGED display to the specified __output_file__ in _PostScript_ format. The
following options control the generated output:

*-a* _author_::
Set the PostScript creator/author string.

*-b*::
Draw a border around the output.

*-c* _r/g/b_::
Set the border color. Each channel is a base-ten integer from 0 through 255.
The color may be written as _r/g/b_, _r,g,b_, _r;g;b_, or as three separate
arguments (_r g b_).

*-f* _font_::
Set the PostScript font.

*-s* _size_in_inches_::
Set the drawing size in inches.

*-t* _title_::
Set the PostScript title string.

*-x* _offset_::
Set the X offset in inches.

*-y* _offset_::
Set the Y offset in inches.


[[examples]]
== EXAMPLES

The first example shows the use of the *postscript* command to place a _PostScript_ version of the current MGED display in a specified file and give it a particular title. The second example adds a border and sets its color.

.Place a _PostScript_ version of the current MGED display in a specified file.
[example]
====
mged>**postscript -t "Test Title" test.ps**

Places a _PostScript_ version of the current MGED display in a file named _test.ps_ and titles it Test Title.

====

.Specify a border color for a _PostScript_ version of the current MGED display.
[example]
====
mged>**postscript -b -c "40;80;160" -t "Bordered View" bordered.ps**

Places a _PostScript_ version of the current MGED display in __bordered.ps__
with a blue border.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
