= PREVIEW(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
preview - Allows the user to _preview_ animation scripts in MGED.

== SYNOPSIS

[source]
----
preview [-e] [-v] [-d delay] [-D start_frame_number] [-K end_frame_number] [-o image_name.ext] rt_script_file
----


[[description]]
== DESCRIPTION

Allows the user to _preview_ animation scripts in MGED. The _-d_ option provides a delay in seconds to be applied between each frame (the default is no delay). The _-D_ option allows the user to specify a starting frame number, and the _-K_ option allows the specification of an ending frame number. The _-v_ flag indicates that the objects displayed in the MGED graphics window should be displayed in evaluated mode, as would be the result of the *ev* command. Note that this may significantly slow the _preview_.  The _-e_ option retains an overlay of the camera eye path.  With _-o image_name.ext_, each displayed frame is written using the supplied base name and extension (or the default PIX form when no extension is supplied).


[[examples]]
== EXAMPLES

The example shows the use of the *preview* command to preview specified frames of an animation script.

.Preview an animation script.
[example]
====
mged>**preview -D 101 -K 237 script.rt**

Displays the animation script stored in the file named _script.rt_ from frame number 101 through frame number 237.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
