= PUSH(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
push - Forces the effects of all transformation matrices that appear in any combinations in the trees from the specified _objects_ down to the primitive shapes.

== SYNOPSIS

[source]
----
push [objects]
----


[[description]]
== DESCRIPTION

Forces the effects of all transformation matrices that appear in any combinations in the trees from the specified _objects_ down to the primitive shapes. This will change the parameters of the _primitive shapes_ if any of the transformation matrices are not identity matrices. All the transformation matrices visited will be set to identity matrices. This command will fail, and no changes will be made, if any primitive shape referenced by the list of _objects_ is positioned differently in two or more _combinations_. The *xpush* command will perform a similar function, even if some shapes are multiply referenced.


[[examples]]
== EXAMPLES

The example shows the use of the *push* command to push the effects of any transformation matrices in the trees headed by two specified objects down to the primitive shapes.

.Push the effects of any transformation matrices in trees headed by two specified objects down to the primitive shapes.
[example]
====
mged>**push group1 regiona**

Pushes the effects of any transformation matrices in the trees headed by _group1_ and _regiona_ down to the primitive shapes.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
