= PUT_COMB(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
put_comb - Insert combinations and regions - allows definition of both boolean expressions and standard attribute values.

== SYNOPSIS

[source]
----
put_comb {comb_name} [is_Region  [[id] | [air] | [material] | [los]]] {color} {shader} {inherit} {boolean_expr}
----


[[description]]
== DESCRIPTION

Command for inserting regions and combinations with attributes set using a single line command - useful in scripting situations.


[[examples]]
== EXAMPLES

The *put_comb* expects one of two particular forms of input - combination or region.

.Specifying a combination using *put_comb*
[example]
====
mged>**put_comb test.c n 255/255/255 plastic n "u sph.s u arb8.s"**

Creates a combination that is not a region, using the plastic shader, consisting of the union of sph.s and arb8.s".


....

mged> l test.c
test.c:  --
Shader 'plastic'
   u sph.s
   u arb8.s
mged> attr get test.c
oshader {plastic}
....

====

.Specifying a region using *put_comb*
[example]
====
mged>**put_comb test.r y 1001 0 32 1 255/255/255 plastic y "u sph.s u arb8.s"**

Creates a combination that is a region, with region id 1001, air flag off, material 32, los 1, white in color, using the plastic shader, inheriting, consisting of the union of sph.s and arb8.s"


....

mged> l test.r
test.r:  REGION id=1001 (air=0, los=1, GIFTmater=32) --
Shader 'plastic'
(These material properties override all lower ones in the tree)
   u sph.s
   u arb8.s
mged> attr get test.r
region {R} inherit {1} oshader {plastic} region_id {1001}
material_id {32} los {1}
....

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
