= PUTMAT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
putmat - Replaces the existing transformation matrix in the combination specified that corresponds to the member specified.

== SYNOPSIS

[source]
----
putmat comb_name/member_name [I | m0 m1 m2 m3 ... m15]
----


[[description]]
== DESCRIPTION

Without a replacement matrix, reports the transformation matrix for the member
arc.  With a replacement, replaces the existing transformation matrix in the
specified combination.  The replacement may be *I* for the identity matrix, a
single quoted string containing 16 finite numbers, or 16 finite numbers listed
row-by-row. The *copymat* command allows the user to copy an existing
transformation matrix.


[[examples]]
== EXAMPLES

The example shows the use of the *putmat* command to set the transformation matrix for a specified region in a specified group to the identity matrix.

.Set the transformation matrix for a specified region in a specified group to the identity matrix.
[example]
====
mged>**putmat group1/regiona I**

Sets the transformation matrix for _regiona_ in _group1_ to the identity matrix.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
