= QOROT(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
qorot - Rotates an object through the specified _angle_ (in degrees).

== SYNOPSIS

[source]
----
qorot {x y z dx dy dz angle}
----


[[description]]
== DESCRIPTION

Rotates an object through the specified _angle_ (in degrees). This command requires that MGED already be in _matrix edit_ mode. The edited object is rotated about the axis defined by the start point (_x y z_) and the direction vector (_dx dy dz_).


[[examples]]
== EXAMPLES

The example shows the use of the *qorot* command to rotate a currently edited object through a specified angle and starting point and in a particular direction.

.Rotate a currently edited object.
[example]
====
mged>**qorot 1 2 3 0 0 1 25**

Rotates the currently edited object through 25° about the axis through the point (1, 2, 3) and in the Z-direction.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
