= RCC-CAP(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
rcc-cap - Used to round the end of a cylinder with an ellipsoid.

== SYNOPSIS

[source]
----
rcc-cap {rccname newname} [height] [b] [t]
----


[[description]]
== DESCRIPTION

Used to round the end of a cylinder with an ellipsoid. It creates an ELL shape with the given height at one end (base [_b_] or top [_t_]) of the specified RCC. If the height option is not specified, a spherical cap will be generated. The default end is the base.


[[examples]]
== EXAMPLES

The two examples show the use of the *rcc-cap* command to round the base and the top of a cylinder with an ellipsoid.

.Round the base of a specified cylinder.
[example]
====
mged>**rcc-cap rcc.s cap.s 20**

Creates an ELL shape named _cap.s_ with a radius of 20 units at the base of _rcc.s_.

====

.Round the top of a specified cylinder.
[example]
====
mged>**rcc-cap rcc.s cap.s 20 t**

Creates an ELL shape named _cap.s_ with a radius of 20 units at the top of _rcc.s_.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
