= RMATER(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
rmater - Reads the specified _file_ and sets the combination shader, color, and inheritance values according to those listed in the _file_.

== SYNOPSIS

[source]
----
rmater {file}
----


[[description]]
== DESCRIPTION

Reads the specified _file_ and sets the combination shader, color, and inheritance values according to those listed in the _file_. The format of the _file_ is expected to be as produced by the *wmater* command.


[[examples]]
== EXAMPLES

The example shows the use of the *rmater* command to read a specified file and set the combination attributes according to those in the file.

.Set combination attributes according to those listed in a specified file.
[example]
====
mged>**rmater mater_file**

Reads the file named __mater_file__ and sets the combination attributes according to those listed in the file.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
