= SCA(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
sca - Used to apply a scaling factor.

== SYNOPSIS

[source]
----
sca {[sfactor] | [x-sfactor y-sfactor z-sfactor]}
----


[[description]]
== DESCRIPTION

Applies a scaling factor to an object or view. When passed one parameter, an "object or view" is applied a uniform scale factor. When passed three parameters, an "object" is applied a unique scale factor to each axis. The effect is determined by the Transform option in the Settings menu. This is normally affected by the current mode of operation in MGED (e.g., matrix edit, primitive edit, or viewing).

NOTE: Three parameters can only be applied in "matrix edit" mode. Only scale pipe and tori primitives uniformly otherwise raytracer and other errors may occur.


[[examples]]
== EXAMPLES

The example shows the use of the *sca* command to apply a scaling factor to an object or view.

.Apply a scaling factor to an object or view.
[example]
====
mged>**sca 2**

In matrix edit mode, the object being affected will get twice as big. In view mode, the size of the view will be doubled (showing twice the volume of space, hence making objects appear half their previous size on the display).

====

.Apply a scaling factor to an object.
[example]
====
mged>**sca 2 1 1**

In matrix edit mode, the object being affected will get twice as big along the x-axis.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
