= SCREENGRAB(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
screengrab - Save the current MGED display visual or framebuffer contents to an image file.

== SYNOPSIS

[source]
----
screengrab [-F] [--format fmt] {image_file}
----


[[description]]
== DESCRIPTION

Generates an image file containing either the current application display manager's visual representation of the current scene or (when the *-F* option is specified) the contents of the current application embedded framebuffer.

The output format of the image file will be deduced from the filename, but if the caller wishes to ensure a specific format the *--format* may be used.


[[examples]]
== EXAMPLES

.Write a PNG image file of the MGED framebuffer contents.
[example]
====
mged>**screengrab -F fb.png**

Writes the contents of the active MGED framebuffer to the image file _fb.png_.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
