= SHELL(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
shells - Separates the specified NMG shape into its constituent shells.

== SYNOPSIS

[source]
----
shells [NMG_shape]
----


[[description]]
== DESCRIPTION

Separates the specified NMG shape into its constituent shells. Each shell is written to the database as a separate NMG object with a name of the form shell with a number appended to make the name unique. If the _NMG_ has only one shell, then only one new object will be created. This differs from the *decompose* command in that *decompose* will actually break the object into a number of separate shells if possible.


[[examples]]
== EXAMPLES

The example shows the use of the *shells* command to break an NMG shape into its constituent shells.

.Break an NMG shape into its constituent shells.
[example]
====
mged>**object.nmg**

Breaks the NMG shape named _object.nmg_ into its constituent shells.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
