= SOURCE(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
source - Reads an external file and executes its contents.

== SYNOPSIS

[source]
----
source {example.txt}
----


[[description]]
== DESCRIPTION

The *source* command reads and executes an external file. The command will look in the current working directory for the file. If the file is in another directory, use the relative or full path to the file or use the *pwd* and *cd* commands to navigate to the file's directory.


[[examples]]
== EXAMPLES

.Read in an external file.
[example]
====
mged>**source example.txt**

Reads and executes the file example.txt located in the current working directory.

====

.Read in an external file using the full path to the file.
[example]
====
mged>**source C:/cad_work/example.txt**

Reads and executes the file example.txt located at C:\cad_work\.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
