= SUMMARY(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
summary - The *summary* command with no arguments lists the number of primitive shapes, regions, and nonregion combinations in the current database.

== SYNOPSIS

[source]
----
summary [p] [r] [g]
----


[[description]]
== DESCRIPTION

The *summary* command with no arguments lists the number of primitive shapes, regions, and nonregion combinations in the current database. If the _p_ argument is supplied, then the name of each _primitive shape_ is also listed. Similarly, the _r_ flag asks for the _region_ names, and _g_ asks for the names of all the combinations (including _region_). The flags may be concatenated to get combined output.


[[examples]]
== EXAMPLES

The example shows the use of the *summary* command with an argument to list a summary of primitive shapes and regions for the current database.

.List a summary of primitive shapes and regions for the current database.
[example]
====
mged>**summary pr**

Lists a summary of primitive shapes and regions for the current database.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
