= VARS(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
vars - With no arguments, will list all the MGED variables and their values.

== SYNOPSIS

[source]
----
vars [variable=value]
----


[[description]]
== DESCRIPTION

With no arguments, will list all the MGED variables and their values. If a _variable=value_ string is included on the command line, then that _value_ is assigned to the specified _variable_. Note that no spaces are allowed around the =. The available _variables_ are as follows:


* autosize -- if nonzero, then MGED will set the view size whenever it draws to an empty display.
* rateknobs -- if nonzero, then the knobs and sliders act as rate adjustments; otherwise, they act as absolute adjustments.
* sliders -- if nonzero, the sliders are displayed.
* faceplate -- if nonzero, the MGED faceplate is displayed.
* orig_gui -- if nonzero, the viewing menu is displayed.
* linewidth -- indicates how wide to draw lines.
* linestyle -- set line style of wireframe shapes. Currently not being used.
* hot_key -- the X11 keysym definition for the key to toggle the __send_key__ value. The default is 0xFFC6 (65478 decimal), which is the F9 key. The keysym values are defined in the X11 file named _keysymdef.h_.
* context -- if nonzero (the default), then primitive editing parameters entered via the *p* command will be applied to the edited shape in the context of the combination tree above it in the displayed hierarchy. This means, for example, a translation applied to a shape will translate the shape to some point such that when the transformation matrices for that path are applied, the edited shape will appear at the specified location. If _context_ is set to zero, then the primitive edit operations will be applied directly to the edited shape. This means that a translation to a specific point may result in the edited shape being drawn at a point different from that specified (due to transformations in the _combination_ tree above it). Note that this only affects primitive edit operations that use the _p_ command.
* dlist -- if nonzero, use display lists.
* use_air -- if nonzero, use air while raytracing.
* listen -- if nonzero, listen for connections to MGEDs built-in fbserv.
* port -- port for the built-in fbserv to use.
* fb -- if nonzero, then framebuffer is active.
* fb_all -- if nonzero, use entire geometry window for the framebuffer; otherwise, use only the rectangular area.
* fb_overlay -- if nonzero, overlay framebuffer image over geometry; otherwise, draw geometry over the framebuffer image.
* mouse_behavior -- see the following list of mouse behaviors:

** c -- fire ray for combination edit selection.
** d -- default behavior (i.e., as found in classic MGED).
** m -- fire ray for matrix edit selection.
** p -- paint rectangular area.
** q -- fire query rays.
** r -- raytrace rectangular area.
** s -- fire ray for primitive edit selection.
** z -- zoom rectangular area.
* coords -- see the following list of coordinate systems to use for transformations:

** m -- model coordinates.
** v -- view coordinates.
** o -- object coordinates.
* rotate_about -- see the following list of centers of rotation:

** v -- view center.
** e -- eye.
** m -- model origin.
** k -- keypoint.
* transform -- see the following list of things to transform:

** a -- transform the angle distance cursor if active; otherwise same as v.
** e -- apply transformations to the edit.
** v -- apply transformations to the view.
* predictor -- if nonzero, the predictor frame will be displayed.
* predictor_advance -- the number of seconds into the future to advance the predictor frame.
* predictor_length -- not currently used.
* perspective -- if greater than zero, this is the perspective angle in degrees; otherwise, perspective is turned off.
* perspective_mode -- if nonzero, turn perspective on; otherwise, turn it off.
* toggle_perspective -- used to toggle among the four canned perspective angles (i.e., 30, 45, 60, and 90).
* nmg_eu_dist -- when the _-u_ option to the *ev* command is used, the NMG edgeuses are drawn this distance (mm) away from the actual edge.
* eye_sep_dist -- if greater than zero, this is the eye separation distance (mm) for stereo viewing; otherwise, stereo is off.
* union_op -- not currently used.
* intersection_op -- not currently used.
* difference_op -- not currently used.


[[examples]]
== EXAMPLES

The example shows the use of the *vars* command with an argument.

.Display the sliders.
[example]
====
mged>**vars sliders=1**

Turns on the _sliders_.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
