= VOXELIZE(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
voxelize - Takes as input a primitive or a collection of primitives, __old_obj__, and creates a region __new_obj__ which is the collection of voxels(RPPs) approximating the __old_obj__.

== SYNOPSIS

[source]
----
voxelize [-s dx/dy/dz] [-d level] [-t fraction] new_obj old_obj [old_obj ...]
----


[[description]]
== DESCRIPTION

Takes one or more existing geometry objects and creates __new_obj__, a region
containing the RPP voxels that approximate their volume.  The output name must
not already exist.

== OPTIONS

*-s* _dx/dy/dz_::
Set positive voxel dimensions in current units.  The value may be written as
`dx/dy/dz`, `dx,dy,dz`, `dx;dy;dz`, a quoted `"dx dy dz"` argument, or three
separate numeric arguments.  The default is `1 1 1`.

*-d* _level_::
Set a positive ray-sampling detail level; the command shoots _level_ squared
rays through each voxel row.  The default is `1`.

*-t* _fraction_::
Set the inclusive 0 through 1 fill fraction required for a voxel to be kept.
The default is `0.5`.

Very small positive voxel dimensions can increase the output size
exponentially.


[[examples]]
== EXAMPLES

The following example shows the use of the *voxelize* command to create a voxelized version of an existing object (__old_object__) and naming the output(__new_object__).

.Create a voxelized version of an existing primitive or collection.
[example]
====

mged> **voxelize -d 2 -s "100 100 100" -t 0.3 newregion.r oldregion.r**::
Creates a voxelized region corresponding to the original region _oldregion.r_.
+
The region _newregion.r_ consists of the resulting voxels.
+
The _-d 2_ option means that on each voxel row, 2*2(=4) rays are uniformly shot over the area and an approximation of the volume is reached from the raytrace data of these four rays.
+
_-s "100 100 100"_ sets the size of the voxels as 100 current units in each dimension. Note that setting the voxel size too small can increase the filesize exponentially.
+
_-t 0.3_ means that a voxel region is considered to be "filled" if the approximated volume of _oldregion.r_ filling this voxel region is 30% of its total volume.



====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
