= WMATER(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
wmater - Lists the shader name and parameters, RGB color, __RGB_valid__ flag, and the inheritance flag to the specified _file_ for the listed _objects_.

== SYNOPSIS

[source]
----
wmater {file} {objects}
----


[[description]]
== DESCRIPTION

Lists the shader name and parameters, RGB color, __RGB_valid__ flag, and the inheritance flag to the specified _file_ for the listed _objects_. The format used is compatible with the *rmater* command. If _file_ already exists, the new data is appended to it.


[[examples]]
== EXAMPLES

The example shows the use of the *wmater* command to list the shader parameters of two objects to a specified file.

.List the shader parameters of two objects to a specified file.
[example]
====
mged>**wmater mater_file group1 regiona**

Lists the shader parameters of _group1_ and _regiona_ to __mater_file__.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
