/*
 *			pix/Cakefile
 */
#include "../Cakefile.defs"

#define STATIC_PRODUCTS	moss.pix moss.log \
			world.pix world.log \
			star.pix star.log \
			bldg391.pix bldg391.log \
			m35.pix m35.log \
			lgt1.pix lgt2.pix \
			lgt3.pix sphflake.pix
#define SRCDIR	pix
#define FILES	/**/
#define	SRCSUFF	.pix
#define MANSECTION	9

/*  Note that there really isn't anything to install.
 *  All that matters is getting the various files to the distribution
 *  directory on the master machine.
 *  The pictures will be distributed in pix(5) format, not ASCII.
 */

all&:	STATIC_PRODUCTS
	@echo "pix:  all done"

#include "../Cakefile.rules"
