.\"                                      Hey, EMACS: -*- nroff -*-
.TH POLYVIEW 1x "February 20, 2000" vdslib
.SH NAME
polyview \- a sample program that displays polygon mesh surfaces using vdslib
.SH SYNOPSIS
.B polyview
.RI [ options ]
.SH DESCRIPTION
\fBpolyview\fP is a program that displays \fI.poly\fP files using
vdslib to reduce the number of triangles used depending on the
distance between the observer and the object being viewed and the
requested quality.  As the number of triangles is reduced, the
rendering speed is increased, specially for large models.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-h\fP
Show summary of options.
.TP
\fB\-pf\fP \fIfilename\fP
open .poly file filename
.TP
\fB\-w\fP
display in wireframe mode (default)
.TP
\fB\-s\fP
display in shaded mode
.TP
\fB\-z\fP
set the initial zoom factor [0]
.TP
\fB\-bg\fP \fIr g b\fP
set background color [1 1 1]
.TP
\fB\-oc\fP \fIr g b\fP
set the diffuse color [.5 .5 .5]
.TP
\fB\-q\fP \fIx y z r\fP
set quaternion rotation [0 0 0 1]
.TP
\fB\-o\fP \fIfoo.ppm\fP
save window as PPM file then exit
.SH SEE ALSO
\fBvdslib online documentation.\fP
.SH AUTHOR
\fBpolyview\fP was written by Kevin Scott and is distributed as part
of \fBvdslib\fP, developed by Dr. David Patrick Luebke
<luebke@cs.virginia.edu>, Department of Computer Science, University
of Virginia.
.P
This manual page was written by Marcelo E. Magallon
<mmagallo@debian.org>, for the Debian GNU/Linux system (but may be
used by others).
