.TH TABSUB 1 BRL-CAD
.\"                       T A B S U B . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2006 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
tabsub \- macro expand an input table into an animation script
.SH SYNOPSIS
.B tabsub
.B template_file
.B <table.final
.B >>script
.SH DESCRIPTION
.I tabsub
takes as input a data table on standard input
(such as might have been produced by
.IR tabinterp (1)
or similar tool),
and a template file named on the command line.
For each row (line) of the input table, one complete copy of
the template file is output on standard output.
As the template is output,
any macro invocations in the template file are replaced with
the data values from the input table's current row.
In the input table, any blank lines or lines with a pound sign ('#')
as the first character are ignored, allowing comments to be
added to the input table.
.PP
Macro invocations in the template file all begin with an at-sign ('@').
In order to send an at-sign through to the output, a second at-sign
must immediately follow it, \fIe.g.\fR when '@@' is encountered in the
template, a single '@' is output.
To output the data value found in a given channel in the current
input row of the data table, the at-sign is followed by the channel
number, \fIe.g.\fR to output the value in channel four, specify '@4',
and to output the value in channel 42, specify '@42'.
In some circumstances it my be desirable to highlight the difference
between channel value substitution, and literal numeric values.
To facilitate this, the channel number may be enclosed in parenthesis
to explicitly delimit the macro invocation.  For example, channel
four could also be specified as '@(4)', and channel 42 as '@(42)'.
This second notation is generally preferred.
.PP
The
.I tabsub
program is intended primarily for creating scripts relating to animation.
To facilitate this, a variety of more complex macros also exist.
.sp .5
   @(line)
.sp .5
will output the row (line) number of the input table which is currently
being processed, with the first line being numbered zero.
This is useful for creating frame numbers, or other sequence tags
in the output.
.sp .5
   @(time)
.sp .5
will output the time value which is always found in the left-most column
of the current row.
.PP
The more complex macros can also take arguments.
If the first character of an argument is an at-sign ('@')
(or percent-sign ('%'), for backwards compatibility), then
the number that follows signifies an input channel substitution
as before.  Otherwise the value is taken literally.
.PP
The
.B rot
macro is used to convert three Euler angles given in degrees
into a rotation expressed as a
4x4 homogeneous transformation matrix.
.sp .5
   @(rot x_angle y_angle z_angle)
.sp .5
The arguments may be either numeric constants, column value macros,
or a combination of both.
The matrix is generated by calling the
.IR libbn (3)
routine
.B bn_mat_angles
which performs the rotation around the Z axis first, then Y, then X.
For example, the macro
.sp .5
   @(rot 0 0 45)
.sp .5
creates the following matrix, a 45 degree rotation about Z:
.sp .5
.nf
.ne 4
7.071067812e-01 -7.071067812e-01 0.000000000e+00 0.000000000e+00
7.071067812e-01 7.071067812e-01 -0.000000000e+00 0.000000000e+00
0.000000000e+00 0.000000000e+00 1.000000000e+00 0.000000000e+00
0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00
.fi
.sp .5
Similarly, the macro
.sp .5
   @(rot @4 @5 90)
.sp .5
creates a rotation matrix where the angle of rotation around X is
taken from input channel four, the Y angle is taken from input channel five,
and the Z angle is fixed at 90 degrees.
.PP
The
.B xlate
macro converts three distances (which must be
specified in millimeters if the output script is destined for
processing by
.IR rt (1)
or
.IR mged (1))
into a translation expressed as a
4x4 homogeneous transformation matrix.
.sp .5
   @(xlate dx dy dz)
.sp .5
The matrix is generated by invoking the C macro
.B MAT_DELTAS
found in h/vmath.h.
For example, the macro
.sp .5
   @(xlate 100 -20 300)
creates the following matrix:
.sp .5
.nf
1.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+02
0.000000000e+00 1.000000000e+00 0.000000000e+00 -2.000000000e+01
0.000000000e+00 0.000000000e+00 1.000000000e+00 3.000000000e+02
0.000000000e+00 0.000000000e+00 0.000000000e+00 1.000000000e+00
.fi
.sp .5
Similarly, the macro
.sp .5
  @(xlate 13 @7 0)
.sp .5
creates a matrix where the origin is translated 13 units (mm) in X,
and the number of units found in input channel 7 in Y.
No translation occurs in Z.
.PP
The
.B orient
macro combines the operation of the
.B rot
zand
.B xlate
macros, and also offers optional scaling.
The invocation is one of:
.sp .5
   @(orient tx ty tz rx ry rz)
.br
   @(orient tx ty tz rx ry rz scale)
.sp .5
where all rotation is done first, then the translation,
and then the scaling (if given).
.PP
The
.B ae
command converts
.IR mged (1)
style azimuth and elevation angle given in degrees
into a rotation expressed as a
4x4 homogeneous transformation matrix.
.sp .5
   @(ae azimuth elevation)
.sp .5
The matrix is generated by calling the
.IR libbn (3)
routine
.B bn_mat_ae
.PP
The
.B arb_rot_pt
command generates an arbitrary rotation matrix, expressed
as a center of rotation, a second point defining the axis of
rotation, and an angle of rotation expressed as an angle in degrees
into a rotation expressed as a
4x4 homogeneous transformation matrix.
.sp .5
   @(arb_rot_pt p1[x] p1[y] p1[z] p2[x] p2[x] p2[z] ang)
.sp .5
The matrix is generated by calling the
.IR libbn (3)
routine
.B bn_mat_arb_rot
.PP
The
.B arb_rot_dir
command generates an arbitrary rotation matrix, expressed
as a center of rotation, a direction vector defining the axis of rotation,
and an angle of rotation expressed as an angle in degrees
into a rotation expressed as a
4x4 homogeneous transformation matrix.
The direction vector need not be unit length.
.sp .5
   @(arb_rot_pt pt[x] pt[y] pt[z] dir[x] dir[x] dir[z] ang)
.sp .5
The matrix is generated by calling the
.IR libbn (3)
routine
.B bn_mat_arb_rot
.PP
The
.B quat
command converts a quaternion into a
4x4 homogeneous transformation matrix.
.sp .5
   @(quat x y z w)
.sp .5
.PP
The
.B fromto
command is used to rotate the given axis to point in the same direction
as the vector formed by subtracting the 'next' point from the 'cur' point.
.sp .5
   @(fromto axis cur_x cur_y cur_z next_x next_y next_z)
.sp .5
The
.I axis
argument must be one of these six strings:
\fI+X, -X, +Y, -Y, +Z, -Z\fR,
where the axis letter is capitalized.
The matrix is generated by calling the
.IR libbn (3)
routine
.B bn_mat_fromto
where the 'from' argument is derived from the
.I axis
given, and the 'to' argument is the unit-length difference 'next'-'cur'.
.SH "RT SCRIPT-LANGUAGE BUILT-INS"
.PP
It is worth noting that the "anim" command in the
.IR rt (1)
animation scripting language
also offers some of these capabilities via built-in shortcuts.
In addition to being able to provide the full 4x4 matrix as an
argument to the "anim ... matrix" command, there are special
keywords:
"xlate", "translate" which take 3 arguments
and pass them to the macro MAT_DELTAS,
"rot" which takes 3 arguments and passes them to bn_mat_angles(),
"scale" which takes one argument as a uniform scale factor
(e.g. a value of 2 makes the subtree twice as large, scaled around
the origin)
and
"scale_about" which passes 4 arguments (point and scale factor)
and calls bn_mat_scale_about_pt().
An example of making an ellipse 1/5th the original size looks like this:
.sp .5
   anim ellipse.r/ellipse.s matrix rarc
      scale_about 16.1309 46.6556 -3.72252    0.2;
.sp .5
.SH EXAMPLE1
.PP
Based upon the example started in the manual page for
.IR tabinterp (1),
here is a Bourne shell script which will generate the
necessary template file using a ``here document'',
and then process the 8-channel output table
left in the file "table.final".
.sp .5
.nf
#!/bin/sh
# This template will be instantiated once for each frame to be made.
cat << EOF > template

start @(line);
clean;
lookat_pt @(3) @(4) @(5);
viewsize @(7);
anim all.g/actor.g matrix rmul
 @(xlate @0 @1 @2);
anim all.g/light.r material rparam
 inten=@(6) angle=70 invisible=1;
end;
! framedone.sh actor.pix.@(line);

EOF
# This is the start of the animation script, which will be appended to below.
cat << EOF > script
viewsize 3000;
eye_pt -4.429280979044739e+03 -1.633722950749571e+03 -1.624787858562220e+03;
orientation 5.435778713738288e-01 4.980973490458696e-01 4.564221286261679e-01 4.980973490458693e-01;
#frame data follows
EOF
# Append the data for each frame
tabsub ./template < table.final >> script
.fi
.sp .5
.PP
The frame number is taken from the input table line number,
and substituted into the
.I start
command.
The main actor position is taken from channels 0,1,2 and applied
(as an "articulation") to the matrix located along the arc between
"all.g" and "actor.g" in the
.I mged
database.
The camera (eye) position stays fixed for this animation, but the
camera orientation is changed by substituting channels 3,4,5 into the
.I lookat_pt
command, and the viewsize (zoom lens setting) is changed by substituting
channel 7 into the
.I viewsize
command.
The argument to the light region's material property string
is replaced with a new string that spells out the current light parameters.
After the
.I end
command, a
.IR rt (1)
shell escape is constructed, which will run a script called
"framedone.sh" with the given argument (which has been arranged
to be the file name of the
.IR pix (5)
file that
.IR rt (1)
just wrote, so that it can be post-processed, compressed,
sent to a video recorder, etc.
.PP
Try clipping this example out of the manual page
(usually found in /usr/brlcad/man/man1/tabsub.1)
and running it.
.SH EXAMPLE2
.PP
In the
.IR tabinterp (1)
manual page, mention was made of animating the flight of a rocket.
This partial example outlines how that might be accomplished.
.sp .5
.nf
tabinterp << EOF > rocket.final
# Channel allocations:
#   0,1,2	position of base of rocket
#   3,4,5	next position of base of rocket
#
# Input table column allocations:  time, X, Y, Z
file rocket.table 0 1 2;
#
times 0 4 60;
#
# Assign interpolators to output channels
interp spline 0 1 2;
#
# Get +1 "look ahead" on values, for auto-guidance
next 3 0 1;
next 4 1 1;
next 5 2 1;
EOF
cat << EOF > rocket.template

start @(line);
clean;
anim all.g/rot.g matrix rmul
 @(xlate @0 @1 @2);
anim rot.g/rocket.g matrix rmul
  @(fromto +Z @0 @1 @2 @3 @4 @5);
end;
EOF
tabsub ./rocket.template < rocket.final >> script
.fi
.sp .5
.PP
The items worthy of note are the use of the
.IR tabinterp (1)
.B next
command to place the position look-ahead into channels 3,4,5
and the matching use of the
.I tabsub
.B fromto
macro to convert the current and next positions into an
appropriate rotation.
In this case, the central axis of the rocket as found in the
.IR mged (1)
database rises up the +Z axis.
Translating the rocket into position is handled one matrix
higher up the tree, using the
.B xlate
macro.
.SH "POST PROCESSING"
.PP
.I rt
style animation scripts can be processed by
.IR rt (1)
and
.IR remrt (1)
by giving the
.B \-M
option on the command line, and providing the script on standard input.
For example, the rocket animation might be run like this:
.sp .5
rt -M -V4:3 -w1440 -n972 -p90 -o rocket.pix rocket.g all.g < script
.sp .5
to produce images in NTSC ("Academy" 4:3) aspect ratio at double the
normal resolution, suitable for later processing by
.IR pixhalve (1).
.PP
The same animation can be previewed in near real-time using
.IR mged (1).
For this example,
.IR mged (1)
would be started with
.sp .5
   mged rocket.g
.sp .5
followed by attaching to an appropriate display device.
Then, these commands would be given:
.sp .5
   e all.g
   preview script
.sp .5
.IR mged (1)
will process each frame as fast as it can, and update the screen.
.SH "SEE ALSO"
tabinterp(1), xyz-pl(1), txyz-pl(1), cut(1), paste(1), rt(1), mged(1)
.SH BUGS
There is presently a compiled-in
limit of 1023 channels in the input table.
.SH AUTHOR
Michael John Muuss
.SH SOURCE
The U. S. Army Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
