######################################################################
# Automatically generated by qmake (2.01a) Mi. Mrz 31 09:30:46 2010
######################################################################

TEMPLATE = app
TARGET = mygist
DEPENDPATH += .
INCLUDEPATH += . ../../../
CONFIG       += release x86_64

# Input
SOURCES += mygist.cpp

win32:DESTDIR = ./
LIBS          += -L../../..
!win32 {
	LIBS         += -lgecodekernel -lgecodesupport -lgecodeint -lgecodesearch -lgecodegist
}
