.\" Copyright (c) 1986, University of Utah
.\" Template man page.  Taken from wtm's page for getcx3d
.TH AVG4 1 "Nov 12, 1986" 1
.UC 4 
.SH NAME
avg4 \- Downfilter an image by simple averaging.
.SH SYNOPSIS
.B avg4
[
.B \-o
.I outfile
] [ 
.I infile
] 
.SH DESCRIPTION
.IR Avg4
downfilters an RLE image into a resulting image of 1/4th the size,
by simply averaging four pixel values in the input image to produce a single
pixel in the output.  If the original image does not contain an alpha
channel, avg4 creates one by counting the number of non-zero pixels in each
group of four input pixels and using the count to produce a coverage value. 
While the alpha channel produced this way is crude (only four levels of
coverage) it is enough to make a noticeable improvement in the edges of 
composited images.  
.SH OPTIONS
.TP
.I infile
The input will be read from this file, otherwise, input will
be taken from stdin.
.TP
.BI \-o " outfile"
If specified, output will be written to this file, otherwise it will
go to stdout.
.SH SEE ALSO
.IR fant (1),
.IR rlecomp (1),
.IR smush (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Rod Bogart, John W. Peterson
.SH BUGS
Very simple minded \- more elaborate filters could be implemented.

