.\" Copyright (c) 1986, University of Utah
.TH MCUT 1 "Nov 8, 1987" 1
.UC 4 
.SH NAME
mcut \- Quantize colors in an image using the median cut algorithm
.SH SYNOPSIS
.B mcut
[
.B \-n
.I colors
]
[
.B \-d
] [
.B \-o
.I outfile
]
.I infile
.SH DESCRIPTION
.I Mcut
reads an RLE file and tries to choose the "best" subset of colors to
represent the colors present in the original image.  A common use for this
is to display a 24 bit image on a frame buffer with only eight bits per
pixel using a 24 bit color map.  
.I Mcut
first quantizes intensity values
from eight bits to five bits, and then chooses the colors from this space.

.I Mcut
runs in two passes; the first pass scans the image to find the color
distributions, and the second pass maps the original colors into color
map indices.  The output file has a color map containing the colors
\fImcut\fP has chosen.  \fIMcut\fP also sets the picture comment
"color_map_length" equal to the number of colors it has chosen.  The
.I getx11
program (among others) will use this color map instead of dithering.
.SH OPTIONS
.TP
.BI \-n " ncolors"
Limit the number of colors chosen to ncolors.  The default is 200.
.TP
.B \-d
Uses Floyd/Steinberg dither to hide contouring.  Greatly improves images
that have a small number of colors.
.TP
.I infile
The input will be read from this file.  If it is a multi-image file,
each image will be quantized to its own colormap.
Piped input is not allowed.  
.TP
.BI \-o " outfile"
If specified, output will be written to this file, otherwise it will
go to stdout.
.SH SEE ALSO
.IR getx11 (1),
.IR rlequant (1),
.IR urt (1),
.IR RLE (5),
.br
"Color Image Quantization for Frame Buffer Display", by Paul Heckbert,
Procedings of SIGGRAPH '82, July 1982, p. 297.
.SH AUTHOR
Robert Mecklenburg, John W. Peterson, University of Utah.
.SH BUGS
The initial quantization is hardwired to five bits.  This should be an
option.

