.\" Copyright (c) 1986, University of Utah
.TH RLEMANDL 1 "Nov 8, 1987" 1
.UC 4 
.SH NAME
rlemandl \- Compute images of the Mandelbrot set.
.SH SYNOPSIS
.B rlemandl 
[ 
.B \-o
.I outfile
] [
.B \-s
.I "xsize ysize"
] [
.B \-v
]
.I "real imaginary width"
.SH DESCRIPTION
.I Rlemandl
computes images of the Mandelbrot set as an eight bit gray scale image.
The
.IR real
and
.IR imaginary
arguments specify the center of the area in the complex plane to be examined.
.IR Width
specifies the width area to be examined.
.SH OPTIONS
.TP
.BI \-o " outfile"
If specified, output will be written to this file, otherwise it will
go to stdout.
.TP
.B \-s 
.I "xsize ysize"
Specify the resolution of the image (in pixels).
.TP
.B \-v
Print a message after every 50 lines are generated.
.SH SEE ALSO
.IR urt (1),
.br
"Computer Recreations," \fIScientific American\fP, August 1985.
.SH AUTHOR
John W. Peterson, University of Utah.
.SH BUGS
What a frob.  Gratuitous features are left as exercise to the reader.
The command name is spelled incorrectly.
