.\" Copyright (c) 1990, University of Michigan
.TH RLEQUANT 1 "June 12, 1990" 1
.UC 4 
.SH NAME
rlequant \- variance based color quantization for RLE images
.SH SYNOPSIS
.B rlequant
[
.B \-b
.I bits
] [
.B \-c
] [
.B \-d
] [
.B \-f
] [
.B \-m
] [
.B \-n
.I colors
] [
.B \-o
.I outfile
] [ 
.I infile
] 
.SH DESCRIPTION
This program quantizes the colors in an RLE image using a
variance-based method.  See 
.IR colorquant (3)
for more details on the method.
.TP
.BI \-b " bits"
The colors in the input image will be "prequantized" to this many bits
before applying the variance-based method.  Two internal tables of
size 
.BR "2^(3*" bits ")"
are allocated, so values of
.I bits
greater than 6 are likely to cause thrashing or may prevent the
program from running at all.  The default value of
.I bits
is 5.  It must be less than or equal to 8 and greater than 0.
.TP
.B \-c
Only the color map will be output; the image will not be digitized.
The output file will be a 0x0 
.IR RLE
file with a color map, suitable for input to 
.IR rleldmap (1)
or
.IR rledither (1).
.TP
.B \-d
Floyd Steinberg dithering is performed on the output.  This is very helpful
for images being quantized to a small number of colors.
.TP
.B \-f
If this option is specified, a faster approximation will be used.  In
most cases, the error so introduced will be barely noticeable.
.TP
.B \-m
Computes a single color map suitable for quantizing all the input
images.  This is useful when the quantized images will be used as a
"movie" (e.g., with the 
.B \-m
flag of
.IR getx11 (1)).
The input may not come from a pipe when this option is specified,
unless
.B \-c
is also specified.
.TP
.BI \-n " colors"
The output image will be quantized to at most
.I colors
colors.  It might have fewer if the input image has only a few colors
itself.  The default value of
.I colors
is 256.  It must be less than or equal to 256.
.TP
.BI \-o " outfile"
The output will be written to the file
.IR outfile .
If not specified, or if
.I outfile
is "\-", the output will be written to the standard output stream.
.TP
.I infile
This file contains one or more concatenated RLE images.  Each will be
processed in turn.  A separate quantization map will be constructed
for each image.  If not specified, or if
.I infile
is "\-", the image(s) will be read from the standard input stream.
.SH SEE ALSO
.IR mcut (1),
.IR rledither (1),
.IR urt (1),
.IR colorquant (3),
.IR RLE (5).
.SH AUTHOR
Spencer W. Thomas
.br
Craig Kolb (Yale University) wrote the color quantization code.
.br
Rod Bogart wrote the dithering code.

