.\" -*- Text -*-
.\" Copyright (c) 1990, University of Michigan
.TH RLESELECT 1 "July 11, 1990" 1
.UC 4 
.SH NAME
rleselect \- Select images from an RLE file.
.SH SYNOPSIS
.B rleselect
[
.B \-i
.I infile 
] [
.B \-o 
.I outfile
] [
.B \-v
] [ 
.I image-numbers ...
]
.SH DESCRIPTION
This program selects images from an
.IR RLE (5)
file containing multiple concatenated images.
The selected images are specified by number; the first image in the
file is number 1.  A negative number in the
.I image-numbers
list means that all images from the previous number in the list to the
absolute value of this number should be included.  A zero in the list
is taken as '\-infinity', so that all images from the previous number
to the last image in the file will be included.  To try to clarify
this, some examples are included below.
.SH OPTIONS
.TP
.BI \-i " infile"
The input will be read from this file.  If
.I infile
is "\-" or is not specified, the input will be read from the standard
input stream.
.TP
.BI \-o " outfile"
If specified, the output will be written to this file.  If 
.I outfile
is "\-", or if it is not specified, the output will be written to the
standard output stream.
.TP
.B \-v
Verbose output.
.SH EXAMPLES
.TP
rleselect 1 4 5
Selects image 1, 4, and 5.
.TP
rleselect 4 1 5
Also selects image 1, 4, and 5.
.TP
rleselect 1 \-4 5
Selects images 1 through 4 and 5 (i.e., 1 through 5).
.TP
rleselect 3 0
Selects images 3 through the last.
.TP
rleselect \-4
Selects images 1 through 4.
.SH SEE ALSO
.IR rlesplit (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Spencer W. Thomas
