.\" Copyright (c) 1988, University of Utah
.TH RLETOABA60 1 "June 05, 1988" 1
.UC 7 
.SH NAME
rletoabA60 \- convert RLE images to Abekas yuv format
.SH SYNOPSIS
.B rletoabA60
[
.B \-c
] [
.BI \-{pP} " x y"
] [
.B \-o
.I outfile
] [
.I infile
]
.SH DESCRIPTION
This program converts an
.IR RLE (5)
file to a yuv byte file suitable for display on an Abekas A60.
Typically the yuv file is then rcp'd to the Abekas for display.
By default
.I rletoabA60
will attempt to place the image according to the placement values in
the image header.  If the image is to large to fit in the Abekas format
(720x486), the portion of the image extending off the edge will be
cropped.
.SH OPTIONS
.TP
.B \-c
Center the image on a black background.
.TP
.BI \-p " x y"
Position the lower left corner of the image at (x y).
.TP
.BI \-P " x y"
Increment the position of the image by (x y).
.LP
At most one of
.BR \-c ,
.BR \-p ,
or
.BR \-P
can be specified.
.TP
.I infile
The input will be read from this file, otherwise, input will
be taken from stdin.
.TP
.BI \-o " outfile"
If specified, output will be written to this file, otherwise it will
go to stdout.
.SH SEE ALSO
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Thomas Todd Elvins, University of Utah
