.\" Copyright (c) 1990, University of Michigan
.TH RLETOGIF 1 "July 3, 1990" 1
.UC 4 
.SH NAME
rletogif \- Convert RLE files to GIF format.
.SH SYNOPSIS
.B rletogif
[
.B \-o 
.I outfile.gif
] [
.I infile.rle
]
.SH DESCRIPTION
This program converts an
.IR RLE (5)
image file to 
.I GIF 
format.  The input file must be a single channel
(8 bit) image.  Three channel (24 bit) images can be converted to
single channel images using the programs
.IR tobw (1),
.IR to8 (1),
.IR mcut (1),
or
.IR rlequant (1).
The input image will be flipped vertically, since the 
.I GIF
origin is in the upper left, and the
.I RLE
origin is in the lower left.  Only a single image will be converted.
.SH OPTIONS
.TP
.BI \-o " outfile.gif"
If specified, the output will be written to this file.  If 
.I outfile.gif
is "\-", or if it is not specified, the output will be written to the
standard output stream.
.TP
.I infile.rle
The input will be read from this file.  If
.I infile.rle
is "\-" or is not specified, the input will be read from the standard
input stream.
.SH SEE ALSO
.IR to8 (1),
.IR mcut (1),
.IR rlequant (1),
.IR giftorle (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Bailey Brown, University of Michigan
