.TH RLETORAW 1 "1990" 1
.UC 4 
.SH NAME
rletoraw \- Convert RLE file to raw RGB form.
.SH SYNOPSIS
.B rletoraw
[
.B \-a
] [
.B \-[Ns]
] [
.B \-r
] [
.BI \-f " header-size"
] [
.BI \-t " trailer-size"
] [
.BI \-l " left-scanline-pad"
] [
.BI \-p " scanline-pad"
[
.B \-o 
.I outfile
] [
.I infile
]
.SH DESCRIPTION
This program converts an
.IR RLE (5)
image to a raw RGB form.  The output file is normally a stream of pixels
(RGBRGB...), in left-to-right, bottom-to-top order (this can be
changed with the \fB\-N\fP
or \fB\-s\fP flags).  The width and
height of the input image will be printed on the standard error
stream.
.SH OPTIONS
.TP
.B \-a
If specified, an alpha channel will be written to the output file.
This is the last output channel, unless \fB\-r\fP is specified,
in which case it will be the first.
.TP
.B \-N
If specified, the output will be written in a non-interleaved order.
I.e., all the red pixels will be written first, then all the green
pixels, etc.
.TP
.B \-s
If specified, the output will be written in a scanline-interleaved
order.  I.e., all the red pixels for a scanline will be written,
followed by all the green pixels for the scanline, etc.  The options
\fB\-N\fP and \fB\-s\fP are mutually exclusive.
.TP
.B \-r
Reverse the order of the channels in the output.  I.e., output will be
written ABGR instead of RGBA.
.TP
.BI \-f " header-size"
A header of this many zero bytes will be written to the output file.
.TP
.BI \-t " trailer-size"
A trailer of this many zero bytes will be written after the output file.
.TP
.BI \-l " left-scanline-pad"
The left (beginning) of each scanline will be padded with this many
zero bytes.
.TP
.BI \-p " left-scanline-pad"
The right (end) of each scanline will be padded with this many zero bytes.
.TP
.BI \-o \ outfile
If specified, the output will be written to this file.  If 
.I outfile
is "\-", or if it is not specified, the output will be written to the
standard output stream.
.TP
.I infile
The input will be read from this file.  If
.I infile
is "\-" or is not specified, the input will be read from the standard
input stream.
.SH SEE ALSO
.IR rawtorle (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Martin Friedmann
.SH BUGS
Basically handles input files with 1 or 3 channels (plus alpha).  Only
the first channel of a 2 channel image will be written.

The header, trailer, and pad options are of dubious utility.

