.\" Copyright (c) 1986, University of Utah
.\" Template man page.  Taken from wtm's page for getcx3d
.TH SMUSH 1 "March 15, 1987" 1
.UC 4 
.SH NAME
smush \- defocus an RLE image.
.SH SYNOPSIS
.B smush
.\" sample options...
[ 
.B \-m
.I maskfile
] [
.B \-n
] [
.B \-o
.I outfile 
] [ 
.I levels
] [
.I infile 
]
.SH DESCRIPTION
.IR Smush
convolves an image with a 5x5 Gaussian mask, blurring the image.  One 
may also provide a mask in a text file.  The file must contain an integer
to specify the size of the square mask, followed by size*size floats.
The mask will be normalized (forced to sum to 1.0) unless the 
.B \-n
flag is given. 

The resulting image is the same size as the input image, no sub-sampling takes
place.  The levels option, which defaults to one, signifies the number of
times which the image will be blurred.  Each successive blurring is done with
a more spread out mask, so a 
.I smush
of level 2 is blurrier than piping two level one
.I smush
calls.
If no input file is specified, 
.I smush
reads from stdin.  If no output file is specified with
.B \-o
it writes the result to stdout.
.SH SEE ALSO
.IR avg4 (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Rod G. Bogart
.SH BUGS
.IR Smush
should probably automatically generate different sized gaussians and other
common filters.



