.TH ALL_SF 1 BRL-CAD
.\"                       A L L _ S F . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\"
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\"
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\"
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
all_sf \- obtain shape factors between named regions of an entire mged database
.SH SYNOPSIS
all_sf model.g objects...
.SH DESCRIPTIONS
all_sf
is an interactive program used to create a file containing shape
factors between all regions of the named objects.  The shape factor
from region i to region j is the fraction of total energy radiated
from region i that is intercepted by region j.  This program finds
the shapefactors for all regions in an mged model not just shapefactors
between engine regions.
.sp
All_sf uses a Monte Carlo simulation, so increasing the number of
significant digits in the answer by one requires about one hundred
fold increase in the number of rays fired.
.sp
Three different files are created by all_sf; an output file, a longwave
radiation exchange file, and an error file.  The output file lists the
shapefactors between each region.  The longwave radiation exchange
file is for use with PRISM.  This file is not quite PRISM ready so the
user must fill in the missing parameters if it is to be used with
PRISM.  The error file is basically used for checking errors in the
program and probably will not be used by the average user.
.SH EXAMPLE
The following is an example from an interactive session.
.nf

	$ all_sf con.sph.g all.air
	Enter name of output file (25 char max).
		cs.out
	Enter name of longwave radiation exchange file (25 char max).
		cs.lwx
	Enter the name of the error file (25 char max).
		cs.err
	Database Title:  concentric spheres for use with
	Number of regions:  3
	Min & max for entire model.
		X:  -2300.000000 - 2300.000000
		Y:  -2300.000000 - 2300.000000
		Z:  -2300.000000 - 2300.000000
	Center:  0.000000, 0.000000, 0.000000

	Radius:  3984.216857
	Surface Area:  199478365.653926

	Enter the number of rays to be fired.
		50000000
	Region names in structure.
	Do you wish to enter your own seed (0) or use the default of 1 (1)?
		1
	Seed initialized
	$
.fi
.SH SEE ALSO
firpass(1), secpass(1), showtherm(1), ir-X(1), ir-sgi(1), pictx(1),
pictsgi(1),shapefact(1), User's
Manual for IRPREP (BRL-SP-96), Computer Programs
for Generating an Input File for PRISM and Displaying PRISM Results
(BRL report in progress)
.SH AUTHOR
Susan A. Coates
