.TH FIRPASS 1 BRL/CAD
.SH NAME
firpass \- interrogates an mged file to obtain the facet records of
a PRISM-ready input file, a generic thermal data file, or a geometric properties file
.SH SYNOPSIS
.B firpass
model.g objects...
.SH DESCRIPTION
Firpass is an interactive program used to create a PRISM ready input
file (when used in conjunction with secpass), a generic thermal data
file, or a
geometric properties file.  The following information about each region
of the mged description may be obtained from firpass when creating a
PRISM ready file.
.nf

	number (arbitrarily assigned by rt_shootray plus one)
	name (25 right most characters of region name)
	type (set to 1)
	exterior surface area (m**2) (surface bounding exterior air)
	mass (kg)
	specific heat (J/kg degree C)
	emissivity
	surface normal unit vector (averaged over free surface of region)
	convection coefficient (set to 1)
	region number seen by back surface (set to 0)
	region number seen by front surface (set to 0)
	shape factor (set to 0)
	hub radius (set to 0)
	bearing friction constant (set to 0)

.fi
The variables set to 0 or 1 need to be changed by the user for special
cases.
.sp
The following information about each region is obtained when creating
a generic thermal data file.
.nf

	number (arbitrarily assigned by rt_shootray plus one)
	name (25 right most characters of region name)
	volume (m**3)
	density (kg/m3)
	thermal conductivity
	specific heat
	material
	number of external convection surfaces and areas (m**2)
	number of internal convection surfaces and areas (m**2)
	number of solar loaded surfaces and areas (m**2)
	external surface area
	surface normal unit vector (averaged over free surface of region)
	absorptivity

.fi
The following information about each region is obtained when creating
a geometric properties file.
.nf

	number (arbitrarily assigned by rt_shootray plus one)
	name (25 right most characters of region name)
	centroid
	volume (m**3)
	mass (kg)
	external surface area (m**2)
	engine surface area (m**2)
	crew surface area (m**2)
	closed compartment surface area (m**2)
	material code
	density (kg/m3)
	specific heat
	absorptivity
	emissivity
	thermal conductivity (W/mK)
	material
	all adjacent regions (up to 20)

.fi
.SH EXAMPLE
The following is an example from an interactive session.
.sp
.nf
$ firpass test.veh.g vehicle air
Write output to standard out (0) or a file (1) or not at all (2)?  2
Enter name of error file to be created (15 char max).  veh.f.err
Enter name of second pass file to be created (15 char max).  veh.f.2nd
Enter name of region # & name file to be created (15 char max).  veh.f.rnn
Enter name of material id file to be read (15 char max).  prp
Enter type of file to be written.
	0 - PRISM file
	1 - Generic file
	2 - Geometric properties file
0
Enter name of facet file to be created. (15 char max)  veh.f.fac
Which release of PRISM is being used, 2.0 (2) or 3.0 (3)?  3
Should there be 3 sets of orthogonal rays fired (0) or 1 set
of rays fired (1)?
	0
3 sets of orthogonal rays will be fired.
File Used:  test.veh.g
Material ID File:  prp
Database Title:  test vehicle for use with irprep programs
Mallocing arrays.
Zeroing variables.
Center of bounding rpp ( 356.500000, 0.000000, 1250.000000 )
Length of diagonal of bounding rpp:  3829.051456
Minimums & maximums
  x:  -3472.551456 - 4185.551456
  y:  -3829.051456 - 3829.051456
  z:  -2579.051456 - 5079.051456
Model minimum & maximum.
	X:  -3001.000000 to 3714.000000
	Y:  -1350.000000 to 1350.000000
	Z:  0.000000 to 2500.000000

Enter grid spacing (mm) for fired rays.
10

SHOOTING DOWN THE 1st AXIS

SHOOTING DOWN THE 2nd AXIS

SHOOTING DOWN THE 3rd AXIS.
There are no exterior surfaces on region 19.  Setting exterior surface area
	to total surface area 31.014883
There are no exterior surfaces on region 20.  Setting exterior surface area
	to total surface area 12.235728
There are no exterior surfaces on region 21.  Setting exterior surface area
	to total surface area 10.856470


SUMMARY OF FILES USED & CREATED
	.g file used:  test.veh.g
	regions used:
		vehicle
		air
	material id file used:  prp
	second pass file created:  veh.f.2nd
	error file created:  veh.f.err
	region # & name file created:  veh.f.rnn
	facet file created:  veh.f.fac
	  (format is PRISM 3.0)


Freeing memory.
.fi
.SH CHANGES SINCE BRL-CAD RELEASE 4.0
1.  Region number and name file is created for use with shapefact and
showtherm.
.sp
.sp -1
2.  The region number is the same across all irprep files, i.e.
region numbers start at one not zero.  This affects the diagnostic
file, the second pass file, and the error file.
.sp
.sp -1
3.  When there is engine air area it is printed in the the radius
field of the PRISM facet file.
.sp
.sp -1
4.  The user is given a choice of a PRISM format of PRISM 2.0 or
PRISM 3.0 for the facet file.
.sp
.sp -1
5.  Addition air types have been added:  closed compartment air,
exhaust air, generic air 1, and generic air 2.
.sp
.sp -1
6.  An additional line was added to the end of the PRISM facet
file to indicate the end of the file.  This line is required by
PRISM.
.sp
.sp -1
7.  If the exterior surface area is zero
the total surface area is written out in the exterior surface
area field in the PRISM facet file.  PRISM will not accept zero in
this field.
.sp
.sp -1
8.  The user is given a choice of firing one set of rays or three
sets of orthogonal rays.
.sp
.SH SEE ALSO
secpass(1), shapefact(1), all_sf(1), showtherm(1), ir-X(1), ir-sgi(1), pictx(1),
pictsgi(1), User's Manual for IRPREP (BRL-SP-96), Computer Programs
for Generating an Input File for PRISM and Displaying PRISM Results
(BRL report in progress)

.SH AUTHOR
Susan A. Coates
