.TH IR-SGI 1 BRL-CAD
.\"                       I R - S G I . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
ir-sgi \- reads the file created by showtherm and draws a picture
on the screen, in an SGI environment, giving an appropriate
color to each pixel based on the temperature
.SH SYNOPSIS
ir-sgi
.SH DESCRIPTIONS
ir-sgi is an interactive program that reads the information in the file
created by showtherm and then draws an image on the screen.  The color
of each pixel is based on the temperature of the region that pixel
belongs to.
.sp
ir-sgi is designed to be run in an SGI environment (see program ir-X
for other environments).
.SH EXAMPLE
The following is an example from an interactive session.
.nf

	$ ir-sgi
	Enter name of file to be read (26 char max)
		veh.dis
	Indicate color scale to be used.
		0 - gray
		1 - black-blue-cyan-green-yellow-white
		2 - black-blue-magenta-red-yellow-white
	0
	Print scan line number (0-yes, 1-no)?
		1
	Do you wish to create a pix file (0-no, 1-yes)?
		0
	Setting color scale - gray scale - set.
	Reading file - file read.
	Width:  512
	Height:  512
	Finding min & max.
	Minimum:  22.590000
	Maximum:  46.830000
	Finding pixel bins - pixel bins found.
	Setting color for each pixel - colors found.
	Press 'z' return to end.  z
	THE END

	$
.fi
.SH SEE ALSO
firpass(1), secpass(1), shapefact(1), all_sf(1), showtherm(1), ir-X(1), pictx(1),
pictsgi(1), User's Manual for IRPREP (BRL-SP-96), Computer Programs
for Generating an Input File for PRISM and Displaying PRISM Results
(BRL report in progress)
.SH AUTHOR
Susan A. Coates
