.TH IR-X 1 BRL/CAD
.SH NAME
ir-X \- reads the file created by showtherm and draws a picture
on the screen, in an X-windows environment, giving an appropriate
color to each pixel based on the temperature
.SH SYNOPSIS
ir-X
.SH DESCRIPTIONS
ir-X is an interactive program that reads the information in the file
created by showtherm and then draws an image on the screen.  The color
of each pixel is based on the temperature of the region that pixel
belongs to.
.sp
ir-X is designed to be run in an X-windows environment.
.SH EXAMPLE
The following is an example from an interactive session.
.nf

	$ ir-X
	Enter name of file to be read (26 char max)
		veh.dis
	Indicate type of color shading to use.
		0 - gray
		1 - red
		2 - black-blue-cyan-green-yellow-white
		3 - black-blue-magenta-red-yellow-white
	0
	Do you wish to create a pix file (0-no, 1-yes)?
		0
	Zeroing color info array - finished zeroing.
	Setting up color scale - shades of gray - finished.
	Reading file - file read.
	Width:  512
	Height:  512
	Finding min & max.
	Minimum:  22.590000
	Maximum:  46.830000
	Finding pixel bins - found pixel bins.
	Putting color info in arrays - color info in arrays.
	$
.fi
.SH SEE ALSO
firpass(1), secpass(1), shapefact(1), all_sf(1), showtherm(1), ir-sgi(1), pictx(1),
pictsgi(1), User's Manual for IRPREP (BRL-SP-96), Computer Programs
for Generating an Input File for PRISM and Displaying PRISM Results
(BRL report in progress)
.SH AUTHOR
Susan A. Coates
