.TH IRDISP 1 BRL-CAD
.\"                       I R D I S P . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
irdisp \- combines the two programs showtherm and ir-sgi or ir-X
.SH SYNOPSIS
irdisp
.SH DESCRIPTIONS
irdisp is an interactive program that
combines the two programs showtherm and ir-sgi or ir-X.  Ultimately it can
read a temperature output file and display the image on the screen
without having the user call two different programs.
.SH EXAMPLE
The following is an example from an interactive session.
.nf

	$ irdisp
	This takes a BRL-CAD mged model with a PRISM
	temperature output file and raytrace and/or
	display it using sgi graphics.  Make your
	selection.
		0 - raytrace & store file
		1 - raytrace, store, and showtherm file
		2 - showtherm file
	1
	Enter .g file to be raytraced (15 char max).
		test.veh.g
	Enter the number of groups to be raytraced.
		1
	Enter group 0 (25 char max).
		vehicle

	The program showtherm is now being run.

	Type of output file to be read 0=>PRISM, 1=>generic.
		0
	Enter name of the PRISM output file to be read (26 char max).
		veh.prm
	Enter the number of regions in the PRISM file, must be more
	than eight (not including the background).
		18
	Enter name of region # & name file to be read (26 char max).
		veh.f.rnn
	Enter name of output file (26 char max).
		veh.dis
	Enter the elapsed time to create graphical representation of.
		4
	Number of regions (including the background):  19
	7/19/1984 7.000000:0.000000
	Prism out file read.
	Region # & name file opened.
	The number of regions read from the output file and the region # & name
	file was the same, 18 (does not include background in number).
	Building directory.
	File:  test.veh.g
	Database Title:  test vehicle for use with irprep programs
		vehicle loaded
	The number of regions read from the output
	file, the region # & name file, and the .g
	file are all equal.  The number of regions
	read, including the background is 19
	Preparation started.

	Minimum & maximum X:  -3001.000000 - 3714.000000
	Minimum & maximum Y:  -1350.000000 - 1350.000000
	Minimum & maximum Z:  0.000000 - 2500.000000
	Center of bounding sphere:  356.500000, 0.000000, 1250.000000
	Radius of bounding sphere:  3829.551456
	Enter multiplication factor for radius.
		.75
	Enter grid size.
		512
	Enter azimuth & elevation.
		35 25
	gridsize:  512 x 512
	azimuth:  35.000000 degrees
	elevation:  25.000000 degrees

	Select display ('X' or 'sgi') ->sgi

	The program ir-sgi is now being run.  If option
	0 or 1 was used when the name of a file is asked
	for enter the name of the file that was just
	stored.

	Enter name of file to be read (26 char max)
		veh.dis
	Indicate color scale to be used.
		0 - gray
		1 - black-blue-cyan-green-yellow-white
		2 - black-blue-magenta-red-yellow-white
	0
	Print scan line number (0-yes, 1-no)?
		1
	Do you wish to create a pix file (0-no, 1-yes)?
		0
	Setting color scale - gray scale - set.
	Reading file - file read.
	Width:  512
	Height:  512
	Finding min & max.
	Minimum:  22.590000
	Maximum:  46.830000
	Finding pixel bins - pixel bins found.
	Setting color for each pixel - colors found.
	Press 'z' return to end.  z
	THE END

	$
.fi
.SH SEE ALSO
firpass(1), secpass(1), shapefact(1), all_sf(1), showtherm(1), ir-X(1), ir-sgi(1),
pictx(1), User's Manual for IRPREP (BRL-SP-96), Computer Programs
for Generating an Input File for PRISM and Displaying PRISM Results
(BRL report in progress)
.SH AUTHOR
Susan A. Coates
