.TH SECPASS 1 BRL-CAD
.\"                      S E C P A S S . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
secpass \- interrogates an mged file to obtain the conductivity table
of the PRISM-ready input file or a generic thermal data file
.SH SYNOPSIS
.B secpass
model.g objects...
.SH DESCRIPTION
Secpass is an interactive program used to create a conductivity
table for the PRISM-ready input file (when used in conjunction
with firpass) or a generic thermal data file.  The conduction approximation
is based on the following formula from the PRISM manual.
.nf

	RK(i,j) =             1
		    ---------------------------
		      L(i)/K(i)A + L(j)/K(j)A

	RK(i,j) - conductivity between region i and j
	L(i)    - conduction path length of region i
	L(j)    - conduction path length of region j
	K(i)    - conductivity of material of region i
	K(j)    - conductivity of material of region j
	A       - shared surface area

.fi
The conduction path length is a distance between the centroid of
the region and the shared surface.  The user may select the average,
root mean squared (rms), minimum, or maximum distance for the length.
.sp
The following information about each region is obtained from
secpass when creating a PRISM ready file.
.nf

	number (same scheme as in firpass)
	number of region there is conduction between
	conduction

.fi
The following information about each region is obtained when creating
a generic thermal data file
.nf

	number
	number of adjacent regions
	shared area of each adjacent region (m**2)
	conduction distance (m)
.SH EXAMPLE
The following is an example from an interactive session.
.nf

$ secpass test.veh.g vehicle air
Write output to standard out (0) or a file(1) not at all (2)?  2
Enter name of file that has second pass information
in it (15 char max).  veh.f.2nd
Enter type of output file to be generated.
	 0 - PRISM File
	 1 - Generic File
0
Enter name of file to be created for PRISM conductivity
information (15 char max).  veh.s.con
Which release of PRISM is being used, 2.0 (2) or 3.0 (3)?  3
Which length calculation should be used when
computing conduction
between regions?
	1 - average length
	2 - rms length
	3 - minimum length
	4 - maximum length
3
Enter name of file to be created for conductivity
table (15 char max).  veh.s.tbl
Enter name of material file (15 char max).  prp
Enter name of error file to be created (15 char max).  veh.s.err
Should there be 3 sets of orthogonal rays fired (0) or 1 set (1)?
	3
3 sets of orthogonal rays will be fired.
Database title:  test vehicle for use with irprep programs
Number of regions in mged file:  21
Mallocing arrays.
cond malloced
loop malloced
All variables zeroed.
second pass file opened
The number of regions read was 21
Center of bounding rpp ( 356.500000, 0.000000, 1250.000000 )
Length of diagonal of bounding rpp:  3829.051456
Minimums & maximums of grid:
  -3472.551456 - 4185.551456
  -3829.051456 - 3829.051456
  -2579.051456 - 5079.051456

Model minimum & maximum.
	X:  -3001.000000 to 3714.000000
	Y:  -1350.000000 to 1350.000000
	Z:  0.000000 to 2500.000000

Enter spacing (mm) between fired rays.  10

grid spacing:  10.000000

Shooting down 1st axis.

Shooting down the 2nd axis.

Shooting down the 3rd axis.


SUMMARY OF FILES USED & CREATED
	.g file used:  test.veh.g
	regions used:
		vehicle
		air
	file containing second pass information:  veh.f.2nd
	material file used:  prp
	conductivity file created:  veh.s.con
	  (format is PRISM 3.0)
	conductivity table file created:  veh.s.tbl
	error file created:  veh.s.err


Freeing memory.
.fi
.SH CHANGES SINCE BRL-CAD RELEASE 4.0
1.  Made the numbering scheme for regions the same throughout all
irprep programs, i.e. region numbers start at one not zero.  This
affects the format of the diagnostic and error files.
.sp
.sp -1
2.  Correct the format of the conductivity file for PRISM.  The
larger region number must come first.
.sp
.sp -1
3.  The user is given a choice of a 2.0 PRISM format or a 3.0 PRISM
format.
.sp
.sp -1
4.  Some diagnostic information is no longer printed out.
.sp
.sp -1
5.  The user is given a choice of firing one set of rays or three
sets of orthogonal rays.
.SH SEE ALSO
firpass(1), shapefact(1), all_sf(1), showtherm(1), ir-X(1), ir-sgi(1), pictx(1),
pictsgi(1), User's Manual for IRPREP (BRL-SP-96), Computer Programs
for Generating an Input File for PRISM and Displaying PRISM Results
(BRL report in progress)
.SH AUTHOR
Susan A. Coates
