.TH SHAPEFACT 1 BRL-CAD
.\"                    S H A P E F A C T . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005-2007 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" Redistribution and use in source (Docbook format) and 'compiled'
.\" forms (PDF, PostScript, HTML, RTF, etc), with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 
.\" 1. Redistributions of source code (Docbook format) must retain the
.\" above copyright notice, this list of conditions and the following
.\" disclaimer.
.\" 
.\" 2. Redistributions in compiled form (transformed to other DTDs,
.\" converted to PDF, PostScript, HTML, RTF, and other formats) must
.\" reproduce the above copyright notice, this list of conditions and
.\" the following disclaimer in the documentation and/or other
.\" materials provided with the distribution.
.\" 
.\" 3. The name of the author may not be used to endorse or promote
.\" products derived from this documentation without specific prior
.\" written permission.
.\" 
.\" THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\".\".\"
.SH NAME
shapefact \- obtain shape factors between named regions of mged database
.SH SYNOPSIS
shapefact model.g objects...
.SH DESCRIPTIONS
Shapefact
is an interactive program used to create a file containing shape
factors between all regions of the named objects.  The shape factor
from region i to region j is the fraction of total energy radiated
from region i that is intercepted by region j.  This file can be
used with the enhanced engine model developed by Jim Rapp at BRL
for use in the PRISM thermal simulation.
.sp
Air must be explicitly modeled since
shapefact will only calculate
shape factors between regions separated by engine air (air code of 5).
Shapefact uses a Monte Carlo simulation, so increasing the number of
significant digits in the answer by one requires about one hundred
fold increase in the number of rays fired.
.SH EXAMPLE
The following is an example from an interactive session.
.nf

	$ shapefact sph.dsk.g all.air
	Enter type of file to be written (0=>regular or 1=>generic).  0
	Enter name of output file (15 char max).
		sd.sh.reg
	Enter the name of the error file (15 char max).
		sd.sh.err
	Enter the region # & name file to be read (15 char max).
		sd.f.rnn
	Do you want to dump interm shape factors to screen (0-no, 1-yes)?  0
	Enter number of rays to be fired.  5000000
	Do you wish to enter your own seed (0) or use the default of 1 (1)?  1
	seed initialized
	Number of regions read from region # & name file:  4
	Database Title:  sphere & disk for use with shape
	Number of regions:  4
	1000000.000000 rays have been fired.
	2000000.000000 rays have been fired.
	3000000.000000 rays have been fired.
	4000000.000000 rays have been fired.
	5000000.000000 rays have been fired.
	Finding correct region numbers.
	Finished finding correct region numbers.
	$
.fi
.SH CHANGES SINCE BRL-CAD RELEASE 4.0
1.  The region number and name file is read so that the numbering
of regions is consistent across all irprep programs.
.sp
.sp -1
2.  A generic output file may now be written.
.sp
.sp -1
3.  An error file is written.
.sp
.sp -1
4.  The format of the output file has been changed.
.SH SEE ALSO
firpass(1), secpass(1), all_sf(1), showtherm(1), ir-X(1), ir-sgi(1), pictx(1),
pictsgi(1), User's Manual for IRPREP (BRL-SP-96), Computer Programs
for Generating an Input File for PRISM and Displaying PRISM Results
(BRL report in progress)
.SH AUTHOR
Susan A. Coates
