/*
 *			rfbd/Cakefile
 */

#define CONFIGDEFS	RFBD_CONFIG

#define SRCDIR	rfbd
#define PRODUCTS	rfbd
#define	SRCSUFF	.c
#define MANSECTION	1

#define FILES	rfbd

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

rfbd:	OBJ LIBFB
	CC LDFLAGS -o rfbd OBJ LIB_PRE''LIBFB RFBD_LIBES LIBES


/* Override the installation directory */
#undef	BINDIR
#define	BINDIR	ETCDIR

#include "../Cakefile.rules"
