/*
 *		tclscripts/rtwizard/lib/Cakefile
 */
#include "../../../Cakefile.defs"

#define PRODUCTS *.tcl *.itcl *.itk tclIndex pkgIndex.tcl
#define STATIC_PRODUCTS	*.tcl *.itcl *.itk tclIndex pkgIndex.tcl
#define SRCDIR	../../tclscripts/rtwizard/lib
#undef BINDIR
#define BINDIR	TCLSCRIPTSDIR/rtwizard/lib

#define FILES	/**/
#define	SRCSUFF	/**/

#define MANSECTION	3

/*
 *  There is nothing to compile.
 *  The "install-prod" rule should install PRODUCTS,
 *  and "inst-dist" rule should take care of copying to distribution dir.
 *  Nothing else to do.
 */
all&:
	@echo "SRCDIR:  all done"

pkgIndex.tcl:
	../../../tclscripts/ampi.tcl ../../../tclscripts/rtwizard/lib

tclIndex:
	../../../tclscripts/ami.tcl ../../../tclscripts/rtwizard/lib

clean&:
	@echo "" > /dev/null

noprod&:
	rm -f tclIndex pkgIndex.tcl

clobber&:
	@echo "" > /dev/null

#include "../../../Cakefile.rules"


