.TH RLE-FB 1 BRL/CAD
.SH NAME
rle\(hyfb \- decode run-length encoded image onto a frame buffer
.SH SYNOPSIS
.B rle-fb
.RB [ \-Ocdh ]
.RB [ \-F\  framebuffer]
.RB [ \-C\  r/g/b]
.RB [ \-S\  squarescrsize]
.RB [ \-W\  scr_width]
.RB [ \-N\  scr_height]
.RB [ \-X\  scr_xoff]
.RB [ \-Y\  scr_yoff]
[file.rle]
.SH DESCRIPTION
.I rle-fb\^
decodes a University of Utah
standard (Edition-3, or "Utah Raster Toolkit")
Run-Length Encoded (RLE) format file
(saved with
.IR fb-rle\^ (1)
or a similar program)
to a frame buffer.
If
.I file.rle\^
is not specified, standard input is read.
.I rle-fb\^
determines the type and size of the saved file (color or B&W)
and acts accordingly.
.PP
By default, the requested framebuffer size is the size given in the
header of the RLE file.
.TP
.B \-h
changes the screen size to 1024x1024.
.TP
.BI \-W\  scr_width
specifies the desired width of the screen, in pixels.
.TP
.BI \-N\  scr_height
specifies the desired height of the screen, in scanlines.
.TP
.BI \-S\  squarescrsize
sets the screen width and height to the indicated value.
.TP
.BI \-F\  framebuffer
This option specifies which framebuffer the image is to be diplayed on.
If not given, the environment variable
.SM \fBFB_FILE\fR
is used to select the display device (see
.IR brlcad(1) ).
If this variable is also not set, the default device for your system will
be used.
.TP
.B \-c
The ``crunch colormap'' option.
If the RLE file contains a colormap, rather than loading that colormap
into the framebuffer and allowing the framebuffer to apply the colormap
to produce the final image, this option causes the colormap to be applied
to the pixel data before it is sent to the framebuffer.
In this case, the colormap in the framebuffer is undisturbed.
This can be useful to preserve dramatic images created with wierd color maps
such that Gamma correction (eg, for film) can also be applied.
This option is recommended when producing images for export to other
display systems, so that variations in the interpretation of color maps
between different types of display hardware do
not affect the displayed image.
.TP
.B \-d
Debug option, provides a verbose description of the input file structure and 
image decoding process, written on standard error.
.TP
.B \-O
Restores the image data in \fIoverlay\fP mode.
Only areas of the original image which were not the background color are
decoded.  The rest of the image already in the frame buffer is undisturbed.
That this mode uses twice as many DMAs to the frame buffer as
the normal mode.
This is because each scanline of the
previous image must be read from the framebuffer,
the overlay portions of the new image written on top,
and the composite scanline must be written back to the framebuffer.
.TP
.BI \-C\  r/g/b
If the image is not being decoded in overlay mode, the background is
normally set to the value recorded in the RLE file.
This option permits
the user to specify an alternate background color
as a red/green/blue tripple, separated by slashes (``/'').
The color intensity in each channel ranges from 0 (dark) to 255 (bright).
.TP
.BI \-X\  scr_xoff
Specify a screen X offset, which will offset the file onto the screen
by the given amount.
Deferred implementation.
.TP
.BI \-Y\  scr_yoff
Specify a screen Y offset, which will offset the file onto the screen
by the given amount.
Deferred implementation.
.TP
.I file.rle\^
Name of file to decode, in RLE format.
If not specified, standard input is used instead.
.SH NOTES
The run length encoded image format is best used for the long-term
storage of images, as it uses less disk storage than a
.I pix(5)
file, at the expense of requiring more processing
for the encoding and decoding.
This program is also useful when using the Utah Raster Toolkit
utilities, which only operate on RLE encoded files;
this program will display their results on a framebuffer.
.PP
Compositing of images is the province of other tools.
For RLE files,
.IR comp(1)
.IR crop(1) ,
.IR repos(1) ,
.IR rlepatch(1) ,
and
.IR rlebox(1)
can be used.
For
.I pix(5)
files,
.IR pixrect(1) ,
.IR pixscale(1) ,
and
.IR pixmerge(1)
are used.
.SH EXAMPLES
.RS
.ft I
\|rle-fb \|truck.rle
.br
\|rle-fb \|\-O \|text.rle
.br
\|rle-fb \|\-C 0/255/0 \|<car.rle
.ft R
.RE
.SH SEE ALSO
brlcad(1), fb-rle(1), rle-pix(1), pix-rle(1), librle(3).
.SH AUTHOR
Michael John Muuss
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH BUG REPORTS
Reports of bugs or problems should be submitted via electronic
mail to <CAD@BRL.MIL>.
