#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: combobox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish -f "$0" ${1+"$@"}
package require -exact Iwidgets 2.2

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::combobox .cb -labeltext "Font:" -labelpos w -selectioncommand {
    puts "selected: [.cb getcurselection]"
}
pack .cb

.cb configure -items {
    Ariel
    Courier
    Helvetica
    Knarly
    Lucida
    Rumpus
    Symbol
    Times
    "Zapf Dingbats"
}
