#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: fileselectionbox in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish -f "$0" ${1+"$@"}
package require -exact Iwidgets 2.2

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::fileselectionbox .fsb -style "notif" -width 4i -height 4i
pack .fsb
