#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: spindate in [incr Widgets]
# ----------------------------------------------------------------------
#\
exec itkwish -f "$0" ${1+"$@"}
package require -exact Iwidgets 2.2

# itkwish interprets the rest...
# ----------------------------------------------------------------------
option add *textBackground seashell

iwidgets::spindate .sd -monthformat string
pack .sd
