.TH HALFTONE 1 BRL-CAD
.\"                     H A L F T O N E . 1
.\" BRL-CAD
.\"
.\" Copyright (c) 2005 United States Government as represented by
.\" the U.S. Army Research Laboratory.
.\"
.\" This document is made available under the terms of the GNU Free
.\" Documentation License or, at your option, under the terms of the
.\" GNU General Public License as published by the Free Software
.\" Foundation.  Permission is granted to copy, distribute and/or
.\" modify this document under the terms of the GNU Free Documentation
.\" License, Version 1.2 or any later version published by the Free
.\" Software Foundation; with no Invariant Sections, no Front-Cover
.\" Texts, and no Back-Cover Texts.  Permission is also granted to
.\" redistribute this document under the terms of the GNU General
.\" Public License; either version 2 of the License, or (at your
.\" option) any later version.
.\"
.\" You should have received a copy of the GNU Free Documentation
.\" License and/or the GNU General Public License along with this
.\" document; see the file named COPYING for more information.
.\"
.\".\".\"
.SH NAME
halftone \- Translate a bw file to a halftoned bw file
.SH SYNOPSIS
.B halftone
.RB [ \-hRSa ]
.RB [ \-s\  squarefilesize]
.RB [ \-w\  file_width]
.RB [ \-n\  file_height]
.RB [ \-B\  contrast]
.RB [ \-I\  Number_Intensity_Levels]
.RB [ \-M\  Method]
.RB [ \-T\  Tone_Scale_Curve_Points]
<\ file.bw
.SH DESCRIPTION
.I Halftone
reads a
.IR bw (5)
format file from the named file, or from
standard in if no file is specified, and reduces the number of intensity
levels from 256 to a default of 2.  Halftone trys to preserve as much
information as possable by applying dither.
.PP
By default, the
.I bw
file is assumed to be 512x512 pixels.
Specifying the
.B \-h
flag changes the size to 1024x1024.
.PP
If the
.B \-R
flag is specified random noise is added to the dither which can sometimes
improve the results.
.PP
The
.B \-S
flag causes a surpentine raster to be used rather than a left to right
scan.
.PP
The
.B \-a
flag is used when automatic file sizing is wanted.  This does not work on
pipes.
.PP
The
.BI \-w\  file_width
flag specifies the width of each scanline in the input file, in pixels.
.PP
The
.BI \-n\  file_height
flag specifies the height in scanlines of the input file.
.PP
.BI \-s\  squarefilesize
sets both the height and width to the size given.
.PP
.BI \-B\  contrast
will define a floating point value to be used as the Beta portion
of a edge sharpening algorthm.  The default is 0.0 which is no
sharpening.
.PP
.BI \-I\  Levels
defines the number of different intensity levels to use on output.  The
default is 2 (1 bit) and the max is 256 (8 bits).
.PP
The
.BI \-M\  method
allows a choice of dither methods.  The default is
0 a Floyd-Steinburg diffused error dither,
1 is a 45 degree classical clustered halftone screen,
2 is a simple threshold dither,
3 is a 0 degree dispersed halftone screen.
.PP
The
.BI \-T\  x1\ y1\ x2\ y2\ ...
parameter is used to define a curve to be used as a tone scale.  The
resulting curve is used to map input pixels to output pixels.  The default
curve is
-T  0 0 128 128 255 255
a curve suggested by Robert Ulichney in
Digital Halftoning
is
-T  0  0  15  0  128  100  200  200  240  255  255  255.
.SH FORMAT
A
.IR bw (5)
file contains sequences of pixels.
Each pixel is stored as one
.B unsigned char.
The first pixel in a
.I bw
file is the lower left corner of the image.
The pixels proceed from left-to-right across each scanline,
with scanlines being written from the bottom to the top of the image.
.PP
The output from
.BI halftone
is scaled so that each intensity level is output as 255/Levels*value.
.SH "SEE ALSO"
rt(1), pix-bw(1), bw(5), bw-fb(1)
.SH AUTHOR
Christopher T. Johnson
.SH SOURCE
SECAD/VLD Computing Consortium, Bldg 394
.br
The U. S. Army Ballistic Research Laboratory
.br
Aberdeen Proving Ground, Maryland  21005
.SH "BUG REPORTS"
Reports of bugs or problems should be submitted via electronic
mail to <devs@brlcad.org>.
