if(NOT DEFINED CHANGES_SOURCE_DIR)
  message(FATAL_ERROR "CHANGES_SOURCE_DIR is not defined")
endif()
if(NOT DEFINED CHANGES_API_BASELINE)
  message(FATAL_ERROR "CHANGES_API_BASELINE is not defined")
endif()
if(NOT DEFINED CHANGES_BINARY_DIR)
  set(CHANGES_BINARY_DIR "${CMAKE_BINARY_DIR}")
endif()

set(_baseline "${CHANGES_API_BASELINE}")
set(_current "${CHANGES_BINARY_DIR}/doc/changes/changes_api_current.adoc")
get_filename_component(_current_dir "${_current}" DIRECTORY)
file(MAKE_DIRECTORY "${_current_dir}")
set(CHANGES_API_BASELINE "${_current}")
include("${CMAKE_CURRENT_LIST_DIR}/changes_api_snapshot.cmake")

file(READ "${_current}" _new)
file(READ "${_baseline}" _old)
if(NOT _new STREQUAL _old)
  message(FATAL_ERROR "Public API baseline differs. Run the changes-api-snapshot target after documenting the public API change.")
endif()

message(STATUS "Public API baseline is current")
