/*
 *			off/Cakefile
 */

#define SRCDIR	off
#define PRODUCTS	off-g g-off
#define	SRCSUFF	.c
#define MANSECTION	1

#include "../Cakefile.defs"
#include "../Cakefile.prog"

/* Explicit composition of each product */

g-off:	g-off.o LIBRT_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS -o g-off g-off.o LIBRT LIBBN LIBBU LIBBU_LIBES LIBES

off-g:	off-g.o LIBWDB_DEP LIBRT_DEP LIBBN_DEP LIBBU_DEP
	CC LDFLAGS -o off-g off-g.o LIBWDB LIBRT LIBBN LIBBU LIBBU_LIBES LIBES

#include "../Cakefile.rules"
