#!/bin/sh
#
# t e m p l a t e
#
# This is a test template that does nothing.  There is a stub for the 
# start function, which is the only function that must be defined.
#
###
# Source function library
. `dirname $0`/library

# see library for a list of variables available for use in your script


start ( ) {
    log "This is the $TEST test.  It does nothing."
    return 0
}

regress $1

exit $?
