.\" Copyright (c) 1986, University of Utah
.\" Template man page.  Taken from wtm's page for getcx3d
.TH CROP 1 "Nov 12, 1986" 1
.UC 4 
.SH NAME
crop \- Change the size of an RLE image
.SH SYNOPSIS
.B crop 
[
.B \-b
] [
.I "xmin ymin xmax ymax"
]
[
.B \-o
.I outfile
] [ 
.I infile 
] 
.SH DESCRIPTION
.IR 
Crop changes the size of an RLE image.  The command line numbers
.I "xmin ymin xmax ymax"
specify the bounds of the resulting image.  If the resulting image is larger 
than the original, 
.IR crop
supplies blank pixels, otherwise pixels are thrown away.
.SH OPTIONS
.TP
.B \-b
The input image is cropped to the enclosing box.  Extra rows and columns of 
black pixels are removed.  The \fIinfile\fR must be a file; no piped input is
allowed for this option.
.TP
.BI \-o " outfile"
If specified, output will be written to this file, otherwise it will
go to stdout.
.TP
.I infile
The input will be read from this file, otherwise, input will
be taken from stdin.
.SH SEE ALSO
.IR repos(1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Rod Bogart
.SH BUGS
Could be combined with 
.IR repos .
Does not check to see if the input and output regions are disjoint.


